export default {
  id: "scene3a",
  layer: 3,
  title: "From 2a: accept Isolde’s full Warden-candidate oath on record",
  text: `The oath chamber sat three flights above the training yard, where the copper ward-bells still trembled from Cassian Rook's last drill call, and the salt wind of the Veil Sea shoved itself through every unlatched shutter as if Ashmere Collegium had invited the weather to witness. [player_name] climbed with the taste of spent magic on her tongue—ozone and chalk and the faint metallic bite that always followed a braid held too long. Her practice bruises glowed faintly blue under the linen of her sleeves. The cracked personal ward-charm at her throat clicked against her collarbone with each step, a small broken metronome she had not yet named aloud.

Cassian walked half a pace behind her, not quite escort, not quite shadow. Scorched leather gloves hung from his belt. Practice-blade oil clung to him the way some men wore cologne: deliberate, intimate, a warning you smelled before you saw the edge. Mid-thirties sat on him like a sealed file—handsome enough to distract, scarred enough to remind you distraction had a cost. When Isolde Vane's clerk opened the chamber doors, Cassian's grey-green eyes flicked once to [player_name]'s face and then away, as if looking too long might constitute a confession neither of them could afford on Collegium parchment.

The chamber smelled of beeswax, wet stone, and the sharp green of crushed ward-herbs. A long table of blackwood held a ledger already open to a blank line. Copper bells hung in a shallow arc above Isolde's chair, quieter than the yard bells, tuned for record rather than alarm. Headmistress Isolde Vane sat as if the cliff itself had taught her posture: silver hair braided tight, rings of office catching the stormlight, mouth set in the patient severity of someone who had burned candidates before and called it stewardship. Behind her, through rain-smeared glass, the Veil Sea fog climbed the cliff stairs in slow white sheets. Somewhere far below, Thorne's black sigil still clung to the stone where it had bloomed the night of [player_name]'s trial—wet, wrong, almost familiar.

"Candidate," Isolde said, and the word landed like a brand. "You will speak the full Warden-candidate oath on record. Cassian Rook stands as handler witness. The Collegium requires your voice, your blood-sigil, and your consent to be bound to Calderyn's outer song should the wards continue to thin." She gestured to the ledger. "There are candidates who hesitate. Hesitation has a body count. You held a braid longer than any in a decade, then cracked our outer ward-song in a manner that should have been impossible. That is either gift or warning. The oath decides which."

[player_name] felt the cracked charm warm against her skin—not heat exactly, more like a second pulse arguing with the first. Living-key rumors drifted through Ashmere like fog: Wardens whose blood sang the wall shut; quiet burnings when a song ran wrong; Isolde's sealed drawer that Cassian would not open. None of it was proven in this room. All of it pressed at the edges of Isolde's careful language. Consent to be bound. Should the wards continue to thin. The words left doors open and shut them at the same time.

Cassian spoke before she could. "She drills. She bleeds chalk. She does not yet know what the oath's second clause costs when the Unmade presses inland." His voice was low, brutal charm sanded down to duty. "Record the first vow if you must. Leave the binding language for a day when she has slept."

Isolde's gaze cut to him. "Your sealed inquiry does not grant you editorial rights over Collegium law, Rook. You nearly followed a man who wanted the wards down. You stayed. That staying is why you hold her leash. It is not why you rewrite my parchment."

The air thickened. [player_name] heard her own breath, the tick of rain, the soft copper shiver of the record-bells. Cassian's jaw flexed once. He did not deny Isolde's history—he never did when she used it like a knife—but something in his stillness said the knife still cut both ways. [player_name] stepped to the ledger because standing between them felt like standing in a braid mid-cast: one wrong tug and the whole song went wrong.

Ink waited. A silver stylus. A shallow dish of copper-salt for the blood-sigil. Isolde recited the first clause in a voice like warm wine poured over iron: duty to Calderyn, fidelity to the ward-song, refusal to treat with Unmade hunger. The second clause arrived softer, almost tender, and that tenderness was worse. Consent to serve as key should the Collegium name the need. Consent to let the song use what the song required. No mention of living lineage. No mention of candidates who vanished into Isolde's quiet arithmetic. Only need, and naming, and the polite fiction that naming was mercy.

[player_name]'s throat worked. She thought of the training yard—Cassian's hands correcting her wrist, the heat under bruises, the way his praise landed like a touch he would not allow himself. She thought of Thorne's mark on the cliff, black and blooming, and the impossible way her braid had answered something in the stone. Hope and dread shared the doorway again. She could refuse. She could lawyer. She could speak the full oath and learn later what she had given.

"I will speak it," she said.

Cassian's breath left him in a sound too quiet for Isolde to own. [player_name] set her palm above the copper-salt. The stylus pricked—clean, small, not theater. Her blood met the dish and darkened. She spoke the first clause clearly, voice steady enough that the record-bells chimed once in acknowledgment. When the second clause rose in her mouth, the cracked charm at her throat flared cold, then hot, then cold again, as if something in the stone below Ashmere had leaned closer to listen. She did not stop. The words left her. The ledger drank the sigil. Isolde's rings flashed as she sanded the page.

"On record," Isolde murmured. "Warden-candidate [player_name], witnessed by Cassian Rook. The Collegium holds your consent." She closed the ledger with a soft finality that felt nothing like safety. "There is a further sealing available tonight—an acceleration some candidates request when the Unmade whisper grows loud. It would bind you more closely to the outer song. Cassian objects on principle. I offer it as choice. You may also request Collegium counsel to parse the oath's residual language before any acceleration. Choose while the ink is still wet. Wet ink remembers better than dry."

Cassian had moved nearer without [player_name] noticing—near enough that practice-blade oil and salt wind braided together at the edge of her senses. His gloved knuckles rested on the blackwood table, white with restraint. "You do not have to let her hurry you into a second mouthful," he said, pitched for her alone, though Isolde heard every syllable. "Counsel can slow a blade. Acceleration can put your blood in a song you have not finished learning. I will stand either way. I will not pretend both ways cost the same."

Outside, a ward-bell on the cliff face stuttered—one wrong note in a century's habit—and steadied. Fog pressed the glass. [player_name] tasted copper. Isolde waited with the patience of a woman who had already decided which answer history would prefer, and who was polite enough to let the candidate believe the deciding still belonged to her. Cassian's eyes held something hungrier than duty and quieter than plea: the look of a man who had almost become the Dark Sovereign's echo once, and who would rather burn than watch her walk that same corridor blind.

Isolde did not fill the silence that followed her offer. Ashmere taught its headmistresses that silence was a ward of its own: it pressed candidates toward speech the way fog pressed cliffs toward drowning. [player_name] used the quiet to catalog what the chamber refused to say. No hymn naming living keys. No ledger line admitting how many candidates had spoken this same second clause and never returned to the yards. Only copper, ink, and Isolde's rings catching stormlight like small obedient suns. Bram Kestrel's forbidden shelf swam up in her memory—half-translated hymns, margins blacked out, a phrase about blood that sang walls shut—and she held it back from her face the way Cassian held back whatever lived in his sealed drawer.

"You look as if you expect the stone to answer," Isolde observed, almost kind. "Stone answers when we give it permission. That is the Collegium's oldest mercy and its oldest lie, depending on who is listening." She rose, crossed to the rain-smeared glass, and watched the fog climb. "Lord Vesper Thorne left a frequency in our cliff the night the old Warden died. Your braid answered something. I will not pretend I know yet whether it answered him, or answered the wound he left, or answered a third song we have not named. The oath does not require you to know. It requires you to stand where knowing can be made useful."

Cassian's laugh was soft and without humor. "Useful is Isolde's favorite word for expensive." He peeled one scorched glove off, then the other, and set them on the blackwood like small dead birds. His bare hands were scarred across the knuckles, a battlemage's map. "I will not open my drawer for you tonight, Headmistress. I will not recite the inquiry you buried. I will say this much for the record-bells: if you accelerate her binding before she understands what answered her braid, you are not making a Warden. You are making a fuse."

[player_name] touched the cracked charm. It was cool now, almost shy. The Veil Sea wind found a seam in the shutters and salted the chamber. She thought of Maris Quill somewhere below in the candidate halls—friend-pressure, rumor, fear—and of how easily a full oath could become a wall between them. She thought of Calderyn beyond the cliff: market cities under aurora-glass, farmlands thinning when the ward thinned, border villages already hearing Unmade whispers first. The continent did not care whether her consent was romantic. It cared whether the song held.

"I spoke what I spoke," [player_name] said. "I will not unsay it. But I will not pretend acceleration and counsel are the same kindness dressed in different ink." She met Isolde's eyes, then Cassian's. Standing between authority and the man who wanted her alive as Warden and—against better judgment—as a person felt like holding a braid with both hands while the weather tried to tear it. "Tell me what the record-bells will hear if I choose wrong."

Isolde's mouth tilted. "If you accelerate, the bells will hear a candidate who trusts the Collegium to finish what her talent began. If you call counsel, the bells will hear a candidate who trusts procedure more than hunger. Both can save a world. Both can doom one. I have buried enough tidy funerals to stop promising certainty." She returned to the table. The ledger waited like a throat. "Choose, [player_name]. The Unmade does not adjourn for our ethics."

Cassian's bare hand hovered a breath from her elbow and did not land—consent of a different kind, withheld until asked. Heat jumped the gap anyway. Outside, another wrong note tried the cliff bells and failed to become a scream. [player_name] breathed salt, beeswax, blade oil, and the copper taste of a vow still settling in her blood. The doorway of choice stayed open. Hope and dread still shared it. She had only to step.`,
  textHot: `The oath chamber sat three flights above the training yard, and [player_name] felt every stair in her thighs, in the blue-glow bruises Cassian Rook had put on her during drills, in the shameless low ache that had nothing to do with magic and everything to do with the man climbing half a pace behind her. Salt wind shoved through the shutters. Copper ward-bells still trembled from his last call. Spent magic tasted like ozone and chalk on her tongue; under it lived a hotter flavor—want, mid-burn, the kind that made her nipples tighten against linen whenever his scorched-leather scent caught up to her on a landing.

Cassian walked like a handler and a hunger. Mid-thirties, scarred, brutal charm held on a leash of Collegium duty. Practice-blade oil clung to him. When Isolde's clerk opened the chamber, his gaze dragged over [player_name]'s mouth, her throat, the cracked ward-charm nestled in the damp hollow between her collarbones, and she felt that look land between her legs as surely as a hand. He looked away first. She did not. Her cunt had opinions the ledger was not prepared to hear.

The chamber smelled of beeswax, wet stone, crushed ward-herbs. Blackwood table. Open ledger. Copper record-bells. Isolde Vane sat like the cliff had taught her how to own a room: silver braid, rings of office, mouth severe and almost tender in the way of people who burned candidates and slept afterward. Through rain-smeared glass, Veil Sea fog climbed. Thorne's black sigil still clung far below on the stone—wrong, wet, a frequency [player_name]'s body remembered even when her mouth had not confessed it.

"Candidate," Isolde said. "Full Warden-candidate oath on record. Blood-sigil. Consent to be bound to Calderyn's outer song should the wards thin." The word consent did filthy work in [player_name]'s head—Isolde meant Collegium binding; [player_name]'s body heard Cassian's voice from the yard, low against her ear while he corrected her stance, glove hot at her hip. "Hesitation has a body count. Your braid held, then cracked our song. Gift or warning. The oath decides."

Cassian cut in, voice sandpaper and heat. "She drills. She bleeds chalk. She does not yet know what the second clause costs." He stood close enough that [player_name] could have turned and put her mouth on the hinge of his jaw. "Record the first vow. Leave the binding language until she has slept."

Isolde's gaze knifed him. "Your sealed inquiry does not rewrite my parchment, Rook. You nearly followed the man who wants the wards down. You stayed. That is why you hold her leash—not why you soften her oath."

[player_name]'s pulse hammered in her throat, her wrists, the soft place behind her knees. Living-key rumors—blood that sang walls shut, quiet burnings, Isolde's sealed drawer—pressed the room without proof. She stepped to the ledger because if she stood still she might do something stupid and public: reach for Cassian's belt, ask him to put his mouth on the cracked charm, make Isolde watch what wanting looked like when it stopped pretending to be duty.

Ink. Silver stylus. Copper-salt dish. Isolde recited the first clause—duty, fidelity, refusal of Unmade hunger—and [player_name] spoke it with a steadiness that made the record-bells chime, even while her thighs pressed together under the table's shadow. The stylus pricked. Blood darkened the dish. The second clause arrived soft, almost loving: consent to serve as key should the Collegium name the need; consent to let the song use what the song required. No full map of sacrifice. Ambiguity like a tongue on a pulse point. [player_name] said the words anyway. The cracked charm flared cold-hot-cold against her skin as if the stone below Ashmere had leaned in to taste her. The ledger drank. Isolde sanded the page.

"On record," Isolde murmured. "The Collegium holds your consent." She offered more—an acceleration sealing that would bind [player_name] closer to the outer song tonight, or Collegium counsel to parse residual language before any hurry. Wet ink remembers, Isolde said, and [player_name] thought of Cassian's mouth remembering her bruises, of how wet she already was from standing in a room where power and need shared a table.

Cassian had closed the distance. Practice-blade oil and salt wind and the clean sweat under his collar hit her senses like a palm between her legs. His gloved knuckles whitened on blackwood. "You do not have to let her hurry you into a second mouthful," he said, pitched private, Isolde hearing every filthy careful syllable. "Counsel can slow a blade. Acceleration puts your blood in a song you have not finished learning. I will stand either way." His eyes said the rest: I will stand, and I will want, and if you ask me to watch Isolde bind you tighter I will do it with my jaw locked and my cock hard and my hands empty because this war does not care what we burn for.

Outside, a cliff ward-bell stuttered one wrong note and steadied. Fog pressed glass. [player_name] tasted copper and want. Her nipples ached. The soft soaked heat between her thighs had nothing to do with oaths and everything to do with the man who would rather ruin himself than let Isolde finish what the ledger had started without [player_name] choosing the shape of the ruin.

Isolde let silence work like a second pair of hands. [player_name] felt it on her skin—on the damp under her breasts, on the insides of her thighs where linen clung because want had made a mess of composure long before ink had dried. The chamber's refusal to name living keys fully only made her body louder: ambiguity was a tease, and her cunt answered teases with a slow shameless clench that had no Collegium form to file.

"You look as if you expect the stone to answer," Isolde said, almost kind, and [player_name] nearly laughed because the stone was already answering low in her belly every time Cassian shifted his weight. Isolde spoke of Thorne's frequency in the cliff, of braids that answered wounds, of oaths that did not require knowing—only usefulness. Usefulness. The word should not have stroked anything. It did. Power talk had always gone straight to [player_name]'s cunt when Cassian was in the room to hear it.

Cassian's soft humorless laugh rolled down her spine. He peeled his scorched gloves off and set them on blackwood; bare scarred knuckles flexed, and [player_name]'s mouth watered for reasons Isolde's ledger would never record. "If you accelerate her binding before she understands what answered her braid," he told Isolde, "you are not making a Warden. You are making a fuse." His eyes flicked to [player_name] on fuse, and she felt the word land like a thumb on her clit—threat and promise braided, mid-want, unfinished.

She touched the cracked charm and felt her own pulse hammer against copper and skin. Maris Quill somewhere below. Calderyn beyond, farmlands failing, Unmade whispers at the borders. The continent did not care that [player_name] was soaked for her handler. She cared anyway. "I spoke what I spoke," she said, voice steadier than the heat pooling between her legs. "Acceleration and counsel are not the same kindness." She looked at Isolde, then at Cassian, and the looking was a kind of fucking with the eyes—slow, deliberate, leaving him no doubt what her body wanted while her mouth negotiated war.

Isolde's mouth tilted. Both paths could save or doom. Certainty was a funeral she no longer promised. She returned to the table. The ledger waited like an open mouth. Cassian's bare hand hovered a breath from [player_name]'s elbow—heat jumping the gap, almost-touch worse than touch because her nipples peaked hard enough to ache and her cunt fluttered as if he had already slid two fingers into her against the blackwood while Isolde sanded pages. He did not land the hand. She did not ask. Yet.

Outside, a wrong note tried the cliff bells. [player_name] tasted salt, beeswax, blade oil, copper, and the thick sweet edge of orgasm held deliberately out of reach. Choice waited—seal or lawyer—while her body begged for a third option involving Cassian's mouth and no parchment at all. Mid-want was a ward of its own, and it was breaking.

Rain thickened against the glass until the Veil Sea became a rumor of white. [player_name] catalogued her own body the way Isolde catalogued candidates: pulse at the throat-charm; heat licking the undersides of her breasts; the slick shameful welcome between her legs every time Cassian's bare knuckles flexed; the ache in her jaw from not asking him to put his mouth there and shut the Collegium out for one filthy minute. Living-key ambiguity still hung unresolved—monster, revolutionary, or both; sacrifice map unfinished—and that unfinishedness only made the want sharper, like a braid held at the edge of breaking.

"Choose," Isolde repeated, softer now, almost a lover's cadence, and [player_name]'s cunt clenched at the timing of the word as if Cassian had whispered it against her clit. He had not. He only stood there, scarred and hard-eyed and visibly fighting the shape of his own desire under battlemage discipline, cock a private war she could feel without looking. Mid-want held them both. The ink was wet. The ward-song pressed. She still had to pick a door.`,
  choices: [
    { id: "scene4a", text: "Let Isolde almost seal the living key", textHot: "Let Isolde almost seal you while Cassian watches" },
    { id: "scene4b", text: "Lawyer the oath with Collegium counsel", textHot: "Lawyer the oath — keep him hungry" }
  ]
};
