export default {
  id: "scene6l",
  layer: 6,
  title: "Obstruction fight: break up / break open",
  text: `The obstruction fight found them in Cassian Rook’s quarters after curfew—practice-blade oil on the table, scorched leather gloves discarded like shed armor, salt wind worrying the shutters above the Veil Sea cliff. Copper bells outside kept a thin wrong watch. [player_name]’s cracked charm ticked hard enough to feel like accusation. He knew about the tip. Of course he knew. Soft nets had taught him her tells; Maris’s fear had taught him the rest; Isolde’s corridor theater had only confirmed what his sealed-past instincts already tasted.

“You obstructed me,” Cassian said, not shouting. Mid-thirties exhaustion made quiet more dangerous than volume. “You tipped Maris I would raid the lower wards. You burned hours we do not have while Calderyn’s song thins and Thorne’s mark stays wet on our stone. Tell me why before I decide whether this is a handler problem or a heartbreak.”

[player_name] stood with her back to his sealed ashwood drawer—the one he still would not open, the one that held nearly-following-Thorne like teeth. “Because you were going to lean hard enough to break her. Because Isolde burns wrong songs quiet and calls it mercy. Because living-key fog is still contested and I will not hand Maris to a machine that finishes people into keys before Bram’s hymns finish naming cost.”

“That is politics,” Cassian said. “It is also lying to my face while asking me to keep you alive as a person. Those two things do not braid clean.”

Heat and hurt shared the room with hope and dread. Mid-want from every unfinished corridor ask lived under the argument like a third pulse. Ashmere’s stones listened through the walls. Practice yards’ blue bruises glowed in memory. Ozone from a failed braid earlier still clung to [player_name]’s sleeves. She could walk out—break up the handler bond, break up the almost-romance, leave him to chase war alone. Or she could break open: tell the whole tip, the whole fear, the whole hunger, and choose him mid-war before the next raid ate what they had not yet named.

Cassian dragged a hand down his face. Brutal charm sanded to raw. “I nearly followed him once. You know the rumor shape. You do not know the village. You do not get to obstruct me into repeating a push because you’re afraid of Isolde’s ledger. If you cannot trust my hands on an interrogation, you cannot trust them on a ward-line when the Unmade presses. Say you want out of this assignment. Or say you want in—fully—and stop feeding Maris exits I haven’t earned the right to close.”

[player_name]’s mouth tasted copper. “I want you. That is the obstruction. Wanting you makes every Collegium verb feel like a trap. Protecting Maris felt like protecting the part of me that still refuses to be ink. I am not proud. I am not finished apologizing. I am asking whether we break up the lie—or break open the wanting—before Isolde’s inquiry finishes us into separate files.”

Silence held. Fog climbed the cliff stairs outside. Inland, farmlands failed in quiet increments. Lord Vesper Thorne remained unfinished as monster or revolutionary—temptation without second LI. Romance lock stayed Cassian only if they chose to keep it. Living-key sacrifice still a shape without clean edges. The Unmade still contested.

Cassian stepped close enough that scorched leather and sleeplessness filled her breath. “Break open means you stop running tips around me. Break up means I chase the war and you chase your fog alone—and I hate that sentence enough to taste blood. There is a third blade: we take this fight to the ward-line raid and let consequence decide if trust survives impact. Non-gore. Still costly. Your call.”

[player_name] looked at his scarred mouth and the sealed drawer and the unfinished war. Mid-want hummed. Hope and dread shared the doorway of his quarters. Copper bells scored the hinge: choose each other mid-fight—or carry the obstruction into a raid where holding or not-holding the ward-line would rewrite more than maps.

Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.

Ashmere Collegium held its breath the way cliff stone held salt: slowly, permanently, with a patience that punished anyone who mistook endurance for kindness. Calderyn beyond the fog was not a map problem alone; it was failing farmlands, aurora-glass markets dimming, border villages that heard Unmade whispers first. Living-key rumors remained contested on purpose. Bram’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure had a smell: spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge.

Practice yards below still carried blue-bruise afterglow; chalk circles smeared by rain waited for the next braid; copper bells scored every almost-confession happening above the waterline. Maris Quill’s fear still walked the dining halls. Ambiguity locked itself again: no confirmation [player_name] was lineage; no clean monster-label for Thorne; no opened drawer; only salt, bells, Cassian’s unfinished mouth, and choice sharpening consequence-verbs in the cliff wind. The Collegium did not gift mercy. The Unmade did not pause for romance. [player_name] carried both truths beside the cracked charm’s tick and the scorched-leather nearness of a handler who refused to let her become ink.

Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.

Ashmere Collegium held its breath the way cliff stone held salt: slowly, permanently, with a patience that punished anyone who mistook endurance for kindness. Calderyn beyond the fog was not a map problem alone; it was failing farmlands, aurora-glass markets dimming, border villages that heard Unmade whispers first. Living-key rumors remained contested on purpose. Bram’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure had a smell: spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge.

Practice yards below still carried blue-bruise afterglow; chalk circles smeared by rain waited for the next braid; copper bells scored every almost-confession happening above the waterline. Maris Quill’s fear still walked the dining halls. Ambiguity locked itself again: no confirmation [player_name] was lineage; no clean monster-label for Thorne; no opened drawer; only salt, bells, Cassian’s unfinished mouth, and choice sharpening consequence-verbs in the cliff wind. The Collegium did not gift mercy. The Unmade did not pause for romance. [player_name] carried both truths beside the cracked charm’s tick and the scorched-leather nearness of a handler who refused to let her become ink.

Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.

Ashmere Collegium held its breath the way cliff stone held salt: slowly, permanently, with a patience that punished anyone who mistook endurance for kindness. Calderyn beyond the fog was not a map problem alone; it was failing farmlands, aurora-glass markets dimming, border villages that heard Unmade whispers first. Living-key rumors remained contested on purpose. Bram’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure had a smell: spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge.`,
  textHot: `The obstruction fight found them in Cassian Rook’s quarters after curfew—and [player_name] was already wet with dread and want braided so tight she could not tell which strand made her shake. Practice-blade oil on the table. Scorched gloves discarded. Salt wind. Copper bells wrong. Her cracked charm ticked between her breasts like a second clit answering his anger. He knew about the tip. Soft net. Maris. Lower wards. Isolde’s theater. His quiet was filthier than shouting.

“You obstructed me,” Cassian said, mid-thirties exhaustion making each word land between her legs. “Tell me why before I decide if this is a handler problem or a heartbreak.”

[player_name]’s back hit his sealed ashwood drawer—the one he would not open, teeth of nearly-following-Thorne behind wood—and the impact made her cunt clench. “Because wanting you makes every Collegium verb feel like a trap. Because Isolde burns wrong songs quiet. Because I tipped Maris to keep her a person and kept you in the dark like a coward who still dreams about your glove on her pulse.”

Cassian’s laugh wrecked. He braced a hand beside her head—not trapping, consent loud in the negative space—and his thigh pressed hers through cloth. She felt him hard and restrained and furious. “You lie to my face and still get slick when I cage you against my secrets. That is not fair, [player_name]. That is also the most honest thing in this fortress tonight.”

Mid-want roared. Nipples tight. Empty aching. Romance lock Cassian only. Thorne’s temptation rumor-warm in the stone somewhere, not here, not in this fight. Living-key fog contested. Sacrifice unfinished. Unmade pressing. She could break up—walk, leave him to chase war, lose the unfinished kiss forever. Or break open—tell everything and choose him mid-war while obstruction turned into fucking-adjacent truth. Or take the fight to a ward-line raid and let impact decide.

“Break open,” she breathed, shameless, “means you fuck the caution into me after I confess every tip. Break up means I walk and hate myself wet. Raid means we spend this heat on the ward-line and pray trust survives.” She dragged his glove to her throat over the charm. “I’m sorry I obstructed you. I’m not sorry I wanted Maris alive. I’m asking which verb keeps your cock in the story without making me Isolde’s key.”

Cassian’s forehead tipped to hers—blade-oil, brutal charm sanded to ache. “If we break open, you stop running exits around me. If we raid, I need your eyes on me when the line sings wrong—not on guilt. If you walk…” His voice dropped filthy-soft. “I will chase the war and then I will chase you, and Ashmere will bill us both.”

He did not kiss her fully. Mid-want held the hinge. [player_name] stayed slick against his sealed drawer while copper bells scored the choice and hope and dread shared her cunt: choose each other mid-fight—or carry obstruction to the ward-line, hold or don’t-hold, bodies still honest under war pressure.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.

[player_name]’s nipples stayed tight under damp fabric. Every shift of cloth reminded her that Isolde’s politics and Thorne’s leftover song had both woken something filthier than fear. Cassian’s gaze kept dropping to her mouth like a man memorizing fracture lines on a body instead of a ward. When he spoke low, she felt the words between her legs—handler voice, battlemage voice, the voice of someone who had almost followed Thorne and now poured that almost into wanting her alive and wanting her, period. Sex was not violence cosplay. War magic could be brutal. What she wanted from Cassian was consent loud enough to drown Collegium ink and still leave the living-key map unfinished on purpose.

She imagined his mouth on her charm, on her breasts, on the wet seam of her through cloth until she came quiet enough that Isolde’s stones could not file the sound. The fantasy was plot, not garnish—it decided how much truth she could speak while aching. Blue-bruise memory from the yards braided with want. Calderyn’s thinning wards somehow made her hungrier for the man who taught survival without promising salvation. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence. Hope and dread shared her cunt the way they shared Ashmere’s thresholds.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.

[player_name]’s nipples stayed tight under damp fabric. Every shift of cloth reminded her that Isolde’s politics and Thorne’s leftover song had both woken something filthier than fear. Cassian’s gaze kept dropping to her mouth like a man memorizing fracture lines on a body instead of a ward. When he spoke low, she felt the words between her legs—handler voice, battlemage voice, the voice of someone who had almost followed Thorne and now poured that almost into wanting her alive and wanting her, period. Sex was not violence cosplay. War magic could be brutal. What she wanted from Cassian was consent loud enough to drown Collegium ink and still leave the living-key map unfinished on purpose.

She imagined his mouth on her charm, on her breasts, on the wet seam of her through cloth until she came quiet enough that Isolde’s stones could not file the sound. The fantasy was plot, not garnish—it decided how much truth she could speak while aching. Blue-bruise memory from the yards braided with want. Calderyn’s thinning wards somehow made her hungrier for the man who taught survival without promising salvation. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence. Hope and dread shared her cunt the way they shared Ashmere’s thresholds.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.

[player_name]’s nipples stayed tight under damp fabric. Every shift of cloth reminded her that Isolde’s politics and Thorne’s leftover song had both woken something filthier than fear. Cassian’s gaze kept dropping to her mouth like a man memorizing fracture lines on a body instead of a ward. When he spoke low, she felt the words between her legs—handler voice, battlemage voice, the voice of someone who had almost followed Thorne and now poured that almost into wanting her alive and wanting her, period. Sex was not violence cosplay. War magic could be brutal. What she wanted from Cassian was consent loud enough to drown Collegium ink and still leave the living-key map unfinished on purpose.

She imagined his mouth on her charm, on her breasts, on the wet seam of her through cloth until she came quiet enough that Isolde’s stones could not file the sound. The fantasy was plot, not garnish—it decided how much truth she could speak while aching. Blue-bruise memory from the yards braided with want. Calderyn’s thinning wards somehow made her hungrier for the man who taught survival without promising salvation. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence. Hope and dread shared her cunt the way they shared Ashmere’s thresholds.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.`,
  choices: [
    { id: "scene7l", text: "Break-open: she and Cassian choose each other mi", textHot: "Break-open: choose each other mid-fight — turn obstruction into want" },
    { id: "scene7m", text: "Raid: hold/don’t-hold the ward-line (non-gore; c", textHot: "Raid: take the fight to the ward-line — hold or don’t, bodies still honest" }
  ]
};
