export default {
  id: "scene3d",
  layer: 3,
  title: "From 2b: hide the frequency match; send Cassian after Maris’s rumor first",
  text: `The archive corridor tasted of ozone and guilt when [player_name] found Cassian Rook where Bram Kestrel's forbidden shelf threw a long shadow across the stone. She had meant—halfway down the stairs—to tell him everything: that her trial braid had not merely held, that it had answered a frequency in Ashmere's cliff that sounded like Lord Vesper Thorne's leftover song. The cracked ward-charm at her throat clicked once against her pulse as if reminding her of honesty. Salt wind shoved through a slit window. Copper ward-bells above tried a clean note and bent. She looked at Cassian's scorched gloves, at the sealed-file stillness in his mid-thirties face, at the brutal charm sanded down to handler duty—and she hid the match.

"Maris Quill," [player_name] said instead. "She has been hearing things. Or saying she has. Rumors about Unmade whispers wearing a familiar voice. If we are hunting frequencies, start with her before Isolde turns rumor into a hanging."

Cassian's grey-green eyes narrowed. Practice-blade oil clung to him; rain-dark leather darkened his cuffs. He had come from the yards or the cliff—somewhere violence and pedagogy shared a calendar. "You left Bram's shelf pale," he said. "Now you want me to lean on a fellow candidate. That is either strategy or misdirection. Which am I buying, [player_name]?"

"Strategy," she lied, and the lie tasted like copper. Living-key rumors pressed the corridor—blood that sang walls shut, quiet burnings when songs ran wrong, Isolde Vane's drawer Cassian would not open—without becoming proof. Thorne remained contested: monster, revolutionary, or both. The Unmade still pressed Calderyn's borders as hunger without a finished map. Hiding the frequency match kept those ambiguities from collapsing onto her name too early. It also put a crack between her and the man assigned to keep her alive.

Cassian stepped closer, not quite touching, close enough that salt and blade oil became a weather. "Maris collects whispers. Useful. Frightened. Possibly already half-caught in something that wears Thorne's warmth over broken glass." He tipped his head toward the candidate halls beyond the archive stair. "I can bring her in soft—questions, tea, the fiction of friendship. Or I can lean. Leaning works faster. Leaning also teaches her which of us to fear." His mouth tilted without kindness. "You are sending me after her rumor first. Say why you are not sending me after the cliff mark first."

[player_name] touched the cracked charm and felt it cool, as if disappointed. "Because rumor has a mouth we can question tonight. The mark only has stone. And because—" She stopped before truth could climb out. Because my braid sang his key. Because telling you makes me a fuse Isolde will accelerate. Because I want one more hour of being your candidate instead of your evidence. "And because Maris looked at me after the trial like she recognized the crack in the song. If she is hearing him, we need to know whether she is prey or doorway."

Cassian held her gaze long enough that the lie should have burned. Perhaps it did; he simply refused to name the smoke. "All right," he said quietly. "We go to Maris. I will not pretend I believe this is your whole inventory. I will pretend long enough to keep you breathing while I find the rest." He peeled one scorched glove off, then the other, bare scarred knuckles flexing—a battlemage's map, a man who had nearly followed Vesper once and stayed to smile like a blade. Hints only. No dump. "When we find her, you choose the temperature. Press her yourself until she names the whisper. Or stand back and let me lean hard. Both paths extract. Only one keeps your hands clean of her fear."

They climbed from archives into the candidate halls, where chalk circles smeared by rain still ghosted the practice floors and Veil Sea fog pressed the window glass in slow white sheets. Maris Quill was not hard to find: she sat on a bench outside the lower ward-lab, dark hair damp, fingers worrying a copper practice ring until the metal shone. Fellow candidate. Friend-pressure node. Eyes that flicked to [player_name] with relief and then to Cassian with the animal caution of someone who had already heard too much.

"Rook," Maris said. "Candidate." Her voice scraped. "If this is about the trial bells, I already told Isolde's clerk I heard nothing unusual."

"We are not Isolde's clerk," Cassian answered, brutal charm polite as a sheathed knife. "We are the people who notice when nothing unusual makes your hands shake."

[player_name] sat beside Maris while Cassian remained standing—height as pressure, silence as ward. The cracked charm warmed against [player_name]'s skin in guilty syncopation. She wanted to confess to Maris, to Cassian, to the stone. She did not. She asked about whispers instead: Unmade voices at the edge of sleep; warmth that felt like wine over broken glass; any name that should not fit inside a fogbank. Maris's throat worked. Somewhere far below, Thorne's black sigil still clung to cliff rock, wet and wrong and almost familiar. Hope and dread shared the hallway bench.

"I hear a man sometimes," Maris whispered at last. "Not always. When the outer song thins. He sounds kind. That is the worst part. Kindness in a whisper is how villages walk into mouths." She glanced at Cassian, then at [player_name], seeking an ally and finding a fork. "If I say more, Isolde will call it contact. If I say less, you will call it obstruction. What do you want from me that will not get me burned?"

Cassian's jaw flexed at burned—too precise a verb for accident. Living-key ambiguity thickened the air: candidates who vanished into stewardship's arithmetic; hymns Bram blacked; drawers sealed. No full sacrifice map tonight. Only pressure, rumor, and the lie [player_name] was still sitting on like a second ward.

"We want the shape of the kindness," Cassian said. "Name. Phrase. Badge. Bell-tower. Anything that turns whisper into geography." He looked at [player_name]. "Your call. You brought me here on Maris's rumor. You decide whether we press until she breaks the last seal herself, or whether I lean and become the bad weather she remembers longer than the whisper."

Rain ticked the glass. Copper bells stuttered above and steadied. [player_name] tasted ozone, salt, and the metallic bite of a withheld frequency. Maris's practice ring flashed. Cassian waited—handler, almost-lover, man with a sealed inquiry—offering two temperatures of extraction while the Unmade listened through the stone and Thorne remained unfinished in the dark. Choice opened like a corridor with two doors and no clean hands behind either.

Maris wiped her palms on her trousers and left copper smears that caught the lamplight like tiny guilty bells. "If Rook leans," she said to [player_name], soft enough to pretend Cassian could not hear, "I will say whatever ends the hour. Fear makes tidy sentences. If you press me, I might tell the untidy truth—the one that does not fit Isolde's forms." Her eyes shone wet. "I thought we were friends. Friends do not bring battlemages to benches."

"Friends keep each other off pyres," [player_name] answered, and hated how much the line sounded like Isolde. She glanced at Cassian. He gave her nothing but readiness: the coiled stillness of a man who could break a room without raising his voice, who had learned that skill in a sealed inquiry's aftermath, who would use it tonight if she nodded. Outside, fog climbed the cliff stairs toward Thorne's mark. Inside, the ward-song pressed thin. Bram's half-translated hymns waited unfinished downstairs. Isolde's parchment waited upstairs. Calderyn's farmlands waited inland for a song that might not hold.

Cassian spoke one last time, pitched for [player_name] alone though Maris heard every syllable. "Hiding things from me has a cost. I am collecting it quietly for now. When Maris is done talking—one way or the other—we are not done. You and I. The cliff. Whatever you smelled on Bram's shelf that put that lie in your mouth." He did not accuse her of the frequency match. He did not need to. The almost-knowing was its own intimacy, sharp as almost-kiss. "Pick the temperature. Press or lean. The Unmade does not adjourn while we practice mercy."

[player_name] breathed chalk, salt, blade oil, and Maris's fear. The cracked charm clicked. Living-key truth stayed contested. Thorne stayed unfinished. Desire for Cassian stayed a hazard she could feel in her wrists. She set her hands on her knees to keep them from shaking and let the choice arrive.

A porter passed at the hall's far end with a stack of chalk and did not look at them; Ashmere had trained its servants to treat candidate fear as weather. [player_name] used the interruption to steady her breath and to feel, again, the withheld frequency like a second heartbeat under the cracked charm. She wondered whether Thorne—if the whisper was truly his—could taste lies the way ward-bells tasted thinness. She wondered whether Cassian already tasted hers. The not-knowing was the point of Layer 3: living keys unnamed in full, Dark Sovereign still ambiguous, war still a pressure rather than a finished verdict.

Maris shifted on the bench, copper ring flashing. "There was a drowned bell-tower in something I dreamed," she offered, then flinched as if the dream might be evidence. "Or a Collegium badge half-heard. I am not sure which memory is mine and which was poured into me." She looked at [player_name] with something like plea. "If you press, ask about the tower first. If he leans, he will go for the badge and my throat will close. That is not advice. That is anatomy."

Cassian filed the anatomy without comment, eyes on [player_name]. Fog thickened against the glass until the Veil Sea became rumor. The outer ward-song pressed thin through the stones. Somewhere Isolde's clerk sharpened a stylus. Somewhere Bram blacked another margin. Somewhere a border village in Calderyn heard a kindness that was not kind. [player_name] held all of it beside her lie and her want and felt the doorway of choice widen—press Maris for Thorne's whisper by name, or let Cassian lean hard—and stepped toward one heat or the other with her hands still not clean.`,
  textHot: `The archive corridor tasted of ozone and guilt when [player_name] found Cassian Rook in Bram Kestrel's shadow, and her cunt clenched traitorously at the sight of him—scorched gloves, blade-oil scent, mid-thirties scarred mouth held in handler stillness—before her ethics could catch up. She had meant to tell him the trial braid answered Thorne's frequency. The cracked charm clicked at her throat like a second clit begging honesty. Salt wind shoved. Ward-bells bent overhead. She looked at the man who could ruin her with a report or a kiss and hid the match because want and fear had braided into one soaked decision.

"Maris Quill," [player_name] said, voice steadier than the heat between her thighs. "She has been hearing things. Rumors. Unmade whispers with a familiar voice. Hunt her first before Isolde turns rumor into a hanging."

Cassian's eyes narrowed. Practice-blade oil clung to him like a filthy promise. "You left Bram's shelf pale. Now you send me at a fellow candidate. Strategy or misdirection?"

"Strategy," she lied, and the lie went straight to her nipples—tight, aching—because lying to him while wet for him was its own erotic crime. Living-key rumors pressed without proof. Thorne stayed monster-or-revolutionary. Unmade hunger unfinished. Hiding the frequency kept her from becoming Isolde's fuse tonight; it also put a crack between her and the handler her body wanted inside her.

He stepped closer. Salt and blade oil became weather. Her clit pulsed. "Maris collects whispers. Possibly half-caught in something that wears Thorne's warmth over broken glass." His mouth tilted without kindness. "I can bring her soft—or I can lean. You are sending me after her rumor first. Say why not the cliff mark."

[player_name] touched the cracked charm and felt it cool, disappointed, while her cunt stayed hot and slick. Because my braid sang his key. Because telling you makes me evidence. Because I want one more hour of being the woman you almost fuck with your eyes instead of the frequency you report. Aloud: "Rumor has a mouth. The mark only has stone. Maris looked at me after the trial like she recognized the crack. Prey or doorway—we need to know."

Cassian held her gaze until the lie should have burned; smoke lived between them anyway, thick as sex. "All right. We go to Maris. I do not believe this is your whole inventory. I will pretend long enough to keep you breathing while I find the rest." He peeled his gloves off; bare scarred knuckles flexed, and [player_name]'s mouth watered for reasons that had nothing to do with war. "When we find her, you choose the temperature. Press her yourself until she names the whisper. Or stand back and let me lean hard—watch me work, want me while I do it. Both extract. Only one keeps your hands clean of her fear."

They climbed into candidate halls. Chalk circles smeared by rain. Veil Sea fog on glass. Maris Quill on a bench outside the lower ward-lab, worrying a copper ring, eyes flicking from [player_name]'s flushed throat to Cassian's standing height like she could smell the withheld fuck in the air. [player_name] sat beside her, thighs pressed tight on shameful slick, while Cassian loomed—pressure as posture, silence as a hand on the back of the neck. The cracked charm warmed in guilty syncopation with [player_name]'s clit.

She asked about whispers: Unmade voices; kindness like wine over broken glass; names that should not fit fog. Maris's throat worked. Thorne's sigil clung far below on cliff rock—wet, wrong, a frequency [player_name] still felt low in her belly and refused to confess. "I hear a man sometimes," Maris whispered. "When the outer song thins. He sounds kind. That is the worst part." She looked between them. "What do you want that will not get me burned?"

Cassian's jaw flexed at burned. Living-key fog thickened—vanished candidates, blacked hymns, sealed drawers—no full sacrifice map, only pressure. [player_name]'s nipples scraped linen every time she breathed; mid-want made interrogation feel like foreplay she should be ashamed of and was not.

"We want the shape of the kindness," Cassian said. "Name. Phrase. Badge. Bell-tower." His eyes hit [player_name] like a thumb on her clit. "Your call. Press her until she breaks the last seal—or let me lean and become the bad weather she remembers longer than the whisper. Choose while you sit there smelling like a secret, candidate. I can smell the secret. I can also smell how much you want me to lean."

Rain ticked glass. Bells stuttered. [player_name] tasted ozone, salt, withheld frequency, and her own soaked want. Maris's ring flashed. Cassian waited—cock a thick outline he did not bother to hide under handler discipline, brutal charm locked, hunger unfinished—offering two temperatures of extraction while the Unmade listened and Thorne stayed contested. Choice opened. [player_name]'s cunt ached around emptiness. She would pick a door with her whole body still lying and still hungry.

Maris wiped her palms and left copper smears. "If Rook leans," she whispered to [player_name], "I will say whatever ends the hour. If you press me, I might tell the untidy truth." Her eyes shone. "I thought we were friends."

"Friends keep each other off pyres," [player_name] said, and the word pyres stroked something dark in her while her cunt stayed shamelessly wet for the battlemage at her shoulder. Cassian's readiness rolled off him like heat—coiled, scarred, cock still half-hard from the archive lie and the corridor almost-touch. Watching him prepare to lean was its own filthy theater: authority as aphrodisiac, fear in the room amplifying the throb between [player_name]'s legs until she had to shift on the bench and feel slickness answer.

He pitched the last lines for her alone. "Hiding things from me has a cost. I am collecting it quietly. When Maris is done, we are not done—you and I, the cliff, whatever put that lie in your mouth." Almost-knowing as intimacy, sharp as a tongue. "Pick the temperature. Press or lean." His gaze dropped to [player_name]'s mouth, her throat, the tight peaks of her nipples under linen, then back up with visible effort. Mid-want held her at the edge—clit swollen, orgasm refused, war listening. "The Unmade does not adjourn while we practice mercy—or while you sit soaked for the man you just misdirected."

[player_name] breathed chalk, salt, blade oil, Maris's fear, and her own hunger. The cracked charm clicked against a pulse that wanted Cassian's mouth more than it wanted clean strategy. Living-key truth contested. Thorne unfinished. She set shaking hands on her knees and let choice arrive wet and inevitable—press Maris herself, or let him lean hard while she watched and wanted.

A porter passed with chalk and did not look; [player_name]'s body used the interruption to clench around nothing, slick and shameless, while the withheld frequency throbbed under her charm like a second clit. She wondered if Thorne could taste lies. She wondered if Cassian could taste how wet she was for him while she misdirected his hunt. Not-knowing made everything hotter—living key unnamed, Sovereign ambiguous, war as pressure, mid-want as the only finished fact in her body.

Maris shifted; copper flashed. "Drowned bell-tower in a dream," she offered, flinching. "Or a Collegium badge half-heard. If you press, ask tower first. If he leans, badge—and my throat closes." Anatomy as warning. [player_name] heard it through the pulse in her cunt.

Cassian's eyes stayed on [player_name], and the look was fucking without hands—slow, knowing, collecting the cost of her lie while his cock stayed a thick outline under discipline. Fog thickened. Ward-song thinned. Isolde's stylus somewhere. Bram's margins somewhere. Border kindness that was not kind. [player_name]'s nipples ached; her thighs slicked the bench; orgasm waited unfinished on purpose. Choice widened—press Maris until she broke on Thorne's whisper, or let Cassian lean hard while [player_name] watched and wanted—and she stepped toward one heat with her hands dirty and her cunt hungry and the living-key map still blessedly incomplete.

She catalogued her own shamelessness the way Isolde catalogued candidates: pulse hammering; nipples peaked hard enough to hurt under damp linen; cunt soaked from archive lie and hallway loom and the promise of watching Cassian lean; jaw tight from not begging him to drag her into an empty ward-lab and fuck the confession out of her before Maris said another word. He would not. Not yet. Mid-want was policy.

"Choose," Cassian murmured, and the word landed between [player_name]'s legs like two fingers crooked just shy of entry. Maris waited. The Unmade waited. Thorne's almost-familiar kindness waited in fog and stone. [player_name] tasted copper and want and the sweet cruel edge of climax held back, and she picked a door with her whole body listening—press until the whisper broke, or let him lean hard while she watched and burned. Rain thickened on the glass until her reflection looked kissed. Cassian's bare knuckles whitened once at his side—restraint she wanted to break with her mouth. Maris's fear smelled like chalk. [player_name]'s want smelled like war. She chose. Mid-want held. The ward-song pressed. Door open. Her clit throbbed once more against the seam of her clothes—unfinished, shameless, listening for his next order.

She clenched around nothing and hated how much she wanted his thigh between hers while Maris's rumor still waited uncashed—war heat and handler hunger braided so tight the Unmade could have whispered her name and she would have answered Cassian first.`,
  choices: [
    { id: "scene4g", text: "Press Maris until she names Thorne's whisper", textHot: "Press Maris until she breaks on Thorne's whisper" },
    { id: "scene4h", text: "Let Cassian lean hard on Maris", textHot: "Let him lean hard — watch and want" }
  ]
};
