export default {
  id: "scene2a",
  layer: 2,
  title: "Training yard — Cassian drills her under ward-bells; heat under bruises",
  text: `The training yard at Ashmere smelled of scorched leather, blade oil, and the ozone that clung to stone after a failed braid. Dawn had not quite decided to arrive; Veil Sea fog still licked the lower steps, and the ward-bells along the cliff spine rang thin and wrong—aftershocks of the cracked outer song, copper notes that tasted like spent magic when the wind turned.

Cassian Rook did not wait for [player_name] to finish tying her practice wrap. He tossed her a blunt sparring rod the moment her boots crossed the chalk line and came in hard enough that the first parry jarred her wrists to the bone. Mid-thirties looked like overtime and old campaigns on him: dark hair damp with fog, instructor's coat open at the throat, gloves scorched at the fingertips. A thin scar cut the corner of his mouth when he almost smiled. Almost was the whole weather of him.

"Again," he said. "You held a decade's braid and then cracked the cliff's hymn like you were answering a knock. I need to know if that was talent, accident, or invitation."

She set her feet. Salt wind lifted the loose end of her wrap. The cracked throat-charm warmed against her pulse—familiar, private, suddenly loud after last night's scream of bells. Isolde Vane had named her Warden-candidate on the terrace; Thorne's sigil still darkened the cliff face below like wet ink that refused to dry. Maris Quill had caught her sleeve in the corridor after and whispered, "Don't let Rook make you into a blade before you know who swings it," then vanished toward the dormitory stairs before [player_name] could ask what Maris had heard in the Unmade whisper that week.

Cassian's rod tapped her shoulder—correction, not kindness. "Stance wider. The Unmade does not care if you look graceful when it presses the wards. Calderyn's border villages are already hearing things in the fog—voices without mouths, hunger without a name. You felt the song crack. Tell me what it felt like, and do not tidy the answer for Isolde's ledger."

[player_name] moved. They circled. Fog pearled on the chalk. Each clash of rods sent a faint blue glow across the bruises rising on her forearms—practice magic's leftover light, pretty and useless. She talked between breaths: the braid holding clean, the sudden answer from somewhere that was not her, the frequency that felt almost familiar, as if the stone had been waiting for a harmony she had never been taught. Cassian's jaw tightened on familiar. He did not explain. He pressed her back across two chalk rings and made her recover without losing the thread of her story.

"Thorne left fingerprints in the stone the year he walked," Cassian said at last, voice flat as a sealed file. "The Collegium calls them residual. Bram Kestrel calls them hymns. I call them trouble with good manners." He feinted high; she caught it late; the rod kissed her ribs hard enough to teach and leave a warmth that would bruise blue by noon. "Your job is to hold the cliff, Candidate. My job is to keep you alive long enough to fail or succeed on purpose. Attraction to drama is optional. Survival is not."

Heat crawled up her neck that had nothing to do with sparring alone. He said attraction like a man naming a weapon on the table between them. She reset, sweat already cooling in the salt wind. Ozone prickled her palms when she tried a small ward-shove mid-strike; the shove fizzled; copper taste flooded her mouth. Cassian caught her wrist—gloved, firm, precise—and redirected the failed braid into the chalk so it scorched a clean arc instead of her bones. The smell of ozone sharpened. Somewhere above, a ward-bell stuttered and found its note again.

"See? Talent without a leash burns the hand that casts it." His eyes were storm-colored under the thinning fog. Sleep-bruised. Too sharp. "Isolde will want your oath on record by sundown. Full Warden-candidate binding—blood, name, and the Collegium's right to spend you if the wards need spending. She will call it duty. I call it a contract written by people who sleep above the waterline and send candidates to bleed on the chalk."

[player_name] pulled free. The throat-charm clicked against her collarbone. "And you? What do you call being assigned to me before the applause died?"

"Insurance." The half-smile arrived, brutal and brief. "I nearly followed a man off a cliff once. The Collegium buried the inquiry. I stayed. That makes me useful for candidates who sound like him when they sing." He did not say Thorne's name that time. He did not need to. The sigil on the cliff was answer enough, and the ambiguity sat between them like fog that would not burn off: whether Lord Vesper Thorne wanted the world rewritten honest, or eaten, or remade in a shape that still had room for mercy. Living keys. Burned candidates. Rumors Bram would only half-translate. Isolde's ledger columns that looked too neat for mercy. None of it settled. Hope and dread shared the yard with their footwork.

A pair of junior candidates lingered at the gate until Cassian's look sent them scattering; Ashmere gossip moved faster than ward-light. [player_name] wiped sweat from her brow with the wrap's end and tasted salt. "If my braid answered him," she said carefully, "does that mean I belong to his song—or that the stone was lonely enough to take any mouth?" Cassian did not answer at once. He rolled his shoulders, coat shifting, and she saw a faint blue old-bruise at his collarbone, leftover of someone else's lesson. "It means you ask better questions than Isolde likes," he said. "Keep asking them where the ledger cannot hear. And keep your feet under you when I hit."

They drilled until her shoulders burned and the ward-bells settled into a low, uneasy toll. Cassian corrected her grip, her breath, the angle of her elbow when she braided mid-motion. He made her hold a ward-thread while parrying, then drop it clean without scorched palms. Once his gloved knuckles brushed the charm at her throat by accident; both of them went still for a half-second that felt longer than the public trial. He stepped back first. Blade oil and scorched leather stayed in the air where he had been.

A runner appeared at the yard gate with Isolde's seal on a slip of parchment and was waved off by Cassian's glance alone. "Not yet," he told the empty gate, then to [player_name]: "Maris Quill is telling stories in the lower halls. Something about hearing a voice in the Unmade press—warm wine over broken glass. If that voice is Thorne's, we have a leak in more than stone. If it is fear wearing his shape, we still have a problem, because fear that accurate usually has a teacher." He watched her drink from the water skin he tossed. "You can take Isolde's full oath and let the Collegium put your name in the martyr column before the fog lifts. Or you can walk the cliff stairs with me for a private spar before the Headmistress finishes writing your future in ink that does not erase. Your call. The yard already knows which bruises are mine."

He walked her through one more sequence while the fog still clung: braid on the inhale, strike on the hold, release on the exhale so the Unmade could not ride the empty lung. [player_name]'s arms shook. Cassian did not soften the drill, but he named what she did right in a voice that felt rarer than praise—precise, almost reluctant, as if kindness were a currency he spent carefully. "Your song is loud," he said, resetting her elbow with two fingers. "Loud is useful on a cliff. Loud is also what draws sovereigns and Headmistresses alike. Learn when to mute." She tasted copper when she next braided; the throat-charm answered with a private thrum. He pretended not to notice. She pretended the thrum was only magic.

Between rounds he spoke of Calderyn in clipped pieces—farmlands failing where the ward thinned, aurora-glass markets still pretending peace, border prefects sending reports that read like prayers written by people who had stopped believing. "Isolde will tell you the Collegium is the only wall. Bram will tell you walls have prices. I will tell you both are true and neither will keep you warm if you die pretty on the chalk." He tossed her the rod again. "One more. Then you choose."

Fog thinned toward a copper dawn. Light from the waking bells striped the chalk. Somewhere below, the Veil Sea breathed against the cliff, and Thorne's mark waited like a question that had not chosen its answer—monster, revolutionary, or the worse mercy of both. [player_name] felt the choice in her sore wrists and in the place behind her sternum where Cassian's almost-smile still lived: oath and ledger under Collegium eyes, or rain and stairs and a handler who admitted he had nearly become the Dark Sovereign's echo—and who looked at her now as if teaching her power without repeating his push was the only redemption left that mattered.

The ward-song pressed soft and cracked. She had to choose before Isolde's messenger found the courage to enter the yard.`,
  textHot: `The training yard hit [player_name]'s body before her mind caught up: scorched leather, blade oil, ozone clinging to wet chalk, salt wind off the Veil Sea sliding under her practice wrap like a hand that had not asked permission. Ward-bells along Ashmere's cliff spine rang thin and wrong—aftershocks of the cracked outer song—each copper note vibrating against the cracked charm at her throat until her pulse felt shared with the stone and a little too loud between her legs.

Cassian Rook did not wait. He put a blunt rod in her hands and came in close enough that fog-damp heat off his coat reached her mouth. Mid-thirties, sleep-bruised under the eyes, instructor's coat open at a throat she should not have been watching. Gloves scorched at the fingertips. When he almost smiled, the scar at the corner of his mouth made charm look like a cut you wanted to put your tongue to. Brutal. Precise. Already under her skin like a fuse lit at both ends.

"Again." His voice lived behind her sternum. "You cracked the cliff's hymn answering something. I need to know if your body invited it."

They circled. Every parry jarred up her arms into her shoulders; every near-miss of his rod left a ghost of impact that bloomed warm under her wrap. Blue practice-light glowed faintly in the bruises rising on her forearms—pretty, useless, intimate as a fingerprint left on purpose. Salt wind lifted her hair against her damp neck. She told him the braid, the answer that was not hers, the frequency that had shivered through her ribs and lower when the song cracked—talking while he watched her mouth felt like undressing a secret in a yard with too many chalk witnesses.

Cassian's jaw flexed. "Thorne left fingerprints in the stone." Flat. Sealed-file voice. He feinted; she was late; the rod kissed her ribs with a bright shock that made her gasp and heat gather low for reasons that had nothing to do with pain alone. Sweat slid between her breasts. She hated how alive the hit made her. "Your job is the cliff. Mine is keeping you breathing. Want is optional. It is also loud when you look at me like that."

He said want like he could taste hers on the salt wind. She reset, tried a ward-shove mid-strike; ozone flared hot in her sinuses; copper flooded her tongue; the shove fizzled. Cassian caught her wrist—gloved leather warm from his skin—and redirected the braid into chalk with a motion that pressed his chest nearly to hers. Breath shared. Blade oil and rain. The failed magic scorched a clean arc. His thumb, even through the glove, rested a fraction too long against the soft inside of her wrist where her pulse hammered traitorously toward his hand.

"Talent without a leash burns the hand that casts it." Storm-colored eyes. Close enough that she could have counted the sleep-bruises if she had not been busy not leaning. "Isolde wants your oath by sundown. Blood, name, the Collegium's right to spend you when the wards go thin. She will call it duty. I call it a contract written by people who never bruise on this chalk and still sleep above the waterline."

[player_name] pulled free and felt the loss of his grip like a pulled thread low in her belly. The throat-charm clicked against her collarbone, cracked edge hot enough to feel like a mouth. "What do you call being assigned to me before the applause died?"

"Insurance." The half-smile landed full this time—weapon and wound. "I nearly followed a man off a cliff once. Buried inquiry. I stayed. That makes me the right kind of ruined to handle a candidate who sings like him." He did not need Thorne's name. The wet-black sigil on the cliff said it. Ambiguity sat thick as fog between their bodies: living keys, burned candidates, whether the Dark Sovereign wanted honesty or hunger or a rewritten world with mercy still in it. Hope and dread pressed her from both sides until her skin felt too small. Cassian's gaze dropped once—charm, mouth, the rise of her breath under the wrap—and came back up like a man choosing not to take something he had already mapped with his eyes.

Junior candidates hovered at the gate; one look from him scattered them. Gossip at Ashmere had teeth. [player_name] wiped sweat with the wrap's end and tasted salt on her lip; his eyes flicked there and away. "If my braid answered him," she said, voice rough, "do I belong to his song—or was the stone lonely enough to take any mouth?" Cassian rolled his shoulders; a faint blue old-bruise showed at his collarbone, someone else's leftover lesson, and she wanted, absurdly, to put her mouth there. "It means you ask questions Isolde would bind shut," he said, softer. "Ask them where the ledger cannot hear. And keep your feet under you when I put my hands on the correcting." The last words landed hotter than instructional.

They drilled until her thighs burned and her wrap stuck to the sweat between her shoulder blades. He corrected her grip with fingers over hers on the rod, calluses felt even through leather; corrected her breath by standing behind her and setting a gloved palm flat at her ribs—"In. Hold. Out. The Unmade presses on the exhale if you give it the opening." The palm did not linger as long as her body wanted. When it left, the absence ached. When his knuckles brushed the charm at her throat by accident, the near-touch traveled down her spine and settled heavy between her legs, a mid-want pulse she could not braid away. Both of them went still. Fog pearled on his lashes. She could have tipped her head and found his mouth. He stepped back first, and the air where he had been smelled like scorched leather and the kind of restraint that made wanting worse.

A runner with Isolde's seal hesitated at the gate; Cassian's glance sent them away without a word. He tossed [player_name] the water skin. She drank; a drop slid down her chin to the hollow of her throat; his eyes tracked it and then deliberately did not, jaw tight. "Maris Quill is telling stories," he said, voice rougher now. "A voice in the Unmade press—warm wine over broken glass. Thorne or fear wearing his mouth. Either way, leak." He took the skin back; their fingers touched bare at the neck of it—his glove peeled for the drink—and the brush of skin was brief and filthy in its cleanliness, a spark that went straight to the bruises he had put on her. "Take Isolde's full oath and let them write you into the martyr column while I watch and pretend my hands are only instructional. Or walk the cliff stairs with me for a private spar before she finishes owning your name. Closer. Fewer witnesses. My bruises already under your wrap where the blue light will find them."

He walked her through one more sequence with his chest at her back and his gloved hand spanning her ribs again—braid on the inhale, strike on the hold, release on the exhale—until the rhythm felt like something bodies did in darker rooms than yards. [player_name]'s arms shook; her thighs did worse. Cassian named what she did right in a voice low enough to feel, reluctant kindness that made her want to earn another scrap of it with her mouth. "Your song is loud," he murmured at her ear, fog-damp breath ghosting the shell of it. "Loud draws sovereigns. Loud draws Isolde. Learn when to mute before someone else puts a hand on your volume." The throat-charm thrummed against her pulse as if agreeing. He stepped away. The absence of him was a bruise of its own.

Between rounds he spoke of Calderyn while she caught her breath—failing farms, aurora-glass markets, border reports like broken prayers—and every practical sentence somehow landed on her skin. "Isolde says wall. Bram says price. I say neither keeps you warm if you die pretty on my chalk." He put the rod back in her hands; fingers brushed; heat jumped. "One more. Then you choose where this heat goes—oath or stairs—because I will not pretend I do not feel the yard getting smaller around us."

Ward-bells tolled low. Copper light striped the chalk. Below, the Veil Sea breathed, and Thorne's mark waited unanswered—hope and dread still sharing the same wet ink. [player_name]'s pulse beat against the cracked charm and against the memory of his palm at her ribs. Mid-want held her in the yard like a spell with no counterbraid: oath and ledger under his eyes, or rain on the cliff stairs where a private spar meant his body correcting hers with no railing of students to make them decent.

She felt the choice in her sore mouth and lower—survival, power, and the dangerous heat of a handler who had nearly become the sovereign's echo and who looked at her now as if teaching her without repeating his push might save them both, or ruin them slower, together.

The cracked song pressed. Isolde's messenger would find courage soon. Cassian waited, rod loose in one hand, gloves dark, want and war sharing the same scarred smile, and [player_name] knew whichever path she took, the bruises would remember him first.`,
  choices: [
    { id: "scene3a", text: "Take Isolde's full Warden oath", textHot: "Swear Isolde's full Warden oath under his eyes" },
    { id: "scene3b", text: "Private spar on the cliff stairs", textHot: "Private spar on the cliff stairs — closer" }
  ]
};
