export default {
  id: "scene6o",
  layer: 6,
  title: "She shields Cassian from Isolde’s politics",
  text: `[player_name] put her body between Cassian Rook and Isolde Vane’s politics the way he had once put his between silver thread and her blood.

They stood in the antechamber outside council—salt wind through tall glass, copper bells preparing a watch-change, prefects already arranging faces for theater. Isolde’s ashwood patience waited beyond the inner doors with the brass dual-consent key rumor-warm in memory. Cassian’s scorched leather brushed [player_name]’s shoulder as he tried to step forward first. She stepped instead.

“You will address me,” [player_name] told the nearest prefect, voice steady enough to lie about steadiness. “Handler Rook’s closeness is not your headline while my song is the one the stone answered. If Isolde wants inquiry, she inquires through the candidate who cracked the outer ward-song—not through a sealed file she kept buried until it became convenient.”

Cassian’s breath left him soft—surprise, protest, mid-want under duty. Mid-thirties exhaustion and brutal charm sanded to something almost like fear for her. “Don’t spend yourself as my shield,” he murmured for her alone. “I have survived Collegium invoices. I have not survived watching you become ink for my sake.”

“Then don’t watch,” she said, and meant watch harder. “Watch me choose.”

Isolde appeared in the inner doorway as if summoned by defiance. Old parchment smell. Ozone. The particular patience of authority. “Candidate. How noble. How theatrical. Shielding a handler with a buried push in his past while living-key language remains contested and Thorne’s frequency still hums in your charm—do you imagine the assembly hears courage, or compromised hunger?”

[player_name]’s cracked charm ticked. Living-key sacrifice still unfinished as map. Unmade still contested. Lord Vesper Thorne still unfinished as monster or revolutionary—temptation without second LI. Romance lock stayed Cassian if she kept spending herself on him instead of on Isolde’s martyrdom script. Hope and dread shared the antechamber.

“I imagine they hear a Warden-candidate refusing to let you burn the man who keeps interrupting your seals,” [player_name] said. “Access can hang. Maps can wait. Calderyn’s thinning wards are real—so is the difference between usefulness and ownership. You do not get Cassian’s throat tonight. You get mine if you insist on theater—and you will find my song less obedient than your ledger prefers.”

A murmur moved through prefects. Maris Quill’s pale face flashed at the corridor’s edge—fear, gratitude, warning. Bram Kestrel would hear of this within the hour. Blue-bruise practice yards glowed far below. Veil Sea fog climbed. Inland farmlands failed in quiet increments while Ashmere argued about who was allowed to want whom under war pressure.

Cassian’s glove found [player_name]’s wrist in plain sight—pulse, signal, heat. Not claiming as key. Claiming as the man she was shielding. Isolde’s eyes noticed. Of course they did.

“Very well,” Isolde said thinly. “Politics it is. You may go public at the next assembly and spend your name as his shield—or you may vanish into festival bells tonight and let rumor chase you both while I draft the quieter knives. Choose which story the stones keep. Relief is no longer on offer. Shadow is.”

Festival of bells: cliff tradition when copper watched changed at storm season, candidates and handlers walking fog paths with lanterns, almost-privacy under noise. Chase and reunion written into the holiday whether Isolde liked it or not. Public assembly: song as shield, closeness as vow under daylight cruelty.

Cassian leaned close. “If you go public, I stand where they can see I asked for none of your martyrdom and accepted all of your wanting. If you walk the festival path, I will chase war and then chase you—and I will find you before Isolde’s knives do. Either way, thank you for the shield. Either way, I’m still not letting her finish you into a living key while the sacrifice map is blank.”

Salt. Copper. Blade oil. Mid-want humming. Ambiguity locked. The hinge sharpened: go public to protect him—or let the chase become reunion at the cliff festival of bells while hope and dread shared every lantern in the fog.

Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.

Ashmere Collegium held its breath the way cliff stone held salt: slowly, permanently, with a patience that punished anyone who mistook endurance for kindness. Calderyn beyond the fog was not a map problem alone; it was failing farmlands, aurora-glass markets dimming, border villages that heard Unmade whispers first. Living-key rumors remained contested on purpose. Bram’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure had a smell: spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge.

Practice yards below still carried blue-bruise afterglow; chalk circles smeared by rain waited for the next braid; copper bells scored every almost-confession happening above the waterline. Maris Quill’s fear still walked the dining halls. Ambiguity locked itself again: no confirmation [player_name] was lineage; no clean monster-label for Thorne; no opened drawer; only salt, bells, Cassian’s unfinished mouth, and choice sharpening consequence-verbs in the cliff wind. The Collegium did not gift mercy. The Unmade did not pause for romance. [player_name] carried both truths beside the cracked charm’s tick and the scorched-leather nearness of a handler who refused to let her become ink.

Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.

Ashmere Collegium held its breath the way cliff stone held salt: slowly, permanently, with a patience that punished anyone who mistook endurance for kindness. Calderyn beyond the fog was not a map problem alone; it was failing farmlands, aurora-glass markets dimming, border villages that heard Unmade whispers first. Living-key rumors remained contested on purpose. Bram’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure had a smell: spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge.

Practice yards below still carried blue-bruise afterglow; chalk circles smeared by rain waited for the next braid; copper bells scored every almost-confession happening above the waterline. Maris Quill’s fear still walked the dining halls. Ambiguity locked itself again: no confirmation [player_name] was lineage; no clean monster-label for Thorne; no opened drawer; only salt, bells, Cassian’s unfinished mouth, and choice sharpening consequence-verbs in the cliff wind. The Collegium did not gift mercy. The Unmade did not pause for romance. [player_name] carried both truths beside the cracked charm’s tick and the scorched-leather nearness of a handler who refused to let her become ink.

Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.

Ashmere Collegium held its breath the way cliff stone held salt: slowly, permanently, with a patience that punished anyone who mistook endurance for kindness. Calderyn beyond the fog was not a map problem alone; it was failing farmlands, aurora-glass markets dimming, border villages that heard Unmade whispers first. Living-key rumors remained contested on purpose. Bram’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure had a smell: spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge.`,
  textHot: `[player_name] put her body between Cassian Rook and Isolde’s politics—and her cunt ached with the filth of it, shielding as intimacy, defiance as foreplay under Collegium eyes. Antechamber. Salt wind. Copper bells winding toward watch-change. Prefects arranging theater. Cassian tried to step first. She stepped instead, scorched leather brushing her shoulder like a mouth denied.

“Address me,” she told the prefect, charm ticking between her breasts, nipples tight under the sheer courage of spending herself. “His closeness is not your headline. My song cracked the ward. Inquire through me.”

Cassian’s murmur at her ear was wrecked heat. “Don’t spend yourself as my shield.” His breath hit her jaw and she went slick hard enough to hate the timing. Mid-want. Mid-war. Romance lock Cassian only. Thorne temptation rumor-warm in stone, not here.

Isolde filled the inner doorway—ashwood patience, brass key memory, living-key hunger unfinished as sacrifice map. “Shielding a handler with buried teeth while your charm hums Thorne’s frequency—courage or compromised hunger?”

[player_name] laughed once, wet with adrenaline. “You don’t get his throat. You get mine if you insist—and my song is less obedient than your ledger.” She dragged Cassian’s glove to her pulse in plain sight—filthy soft claim-without-key—and the shock went straight to her clit while Isolde watched. Hope and dread shared her body. Unmade contested. Ambiguity locked on purpose.

“Politics,” Isolde said. “Go public at assembly as his shield—or vanish into festival bells and let him chase you while I draft quieter knives.”

Cassian’s thigh brushed hers as prefects murmured. “Public means I watch you spend wet courage for me and then collect afterward off-record. Festival means I chase war and then chase you through copper dark until I find your mouth. Either way thank you. Either way you’re not her key.”

[player_name] pressed closer until the charm trapped between them burned. “If I go public I want you hard in the wings. If I take the festival path I want you to find me under bells and finish what every corridor started—without finishing the living-key map Isolde wants inked.”

He tipped his forehead to hers. Blade-oil. Brutal charm. Cock restrained by duty and gratitude. Mid-want held the hinge. Salt wind licked her throat. The choice waited slick: go public—or reunion chase at the festival of bells, want unfinished under Ashmere’s rain-dark towers.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.

[player_name]’s nipples stayed tight under damp fabric. Every shift of cloth reminded her that Isolde’s politics and Thorne’s leftover song had both woken something filthier than fear. Cassian’s gaze kept dropping to her mouth like a man memorizing fracture lines on a body instead of a ward. When he spoke low, she felt the words between her legs—handler voice, battlemage voice, the voice of someone who had almost followed Thorne and now poured that almost into wanting her alive and wanting her, period. Sex was not violence cosplay. War magic could be brutal. What she wanted from Cassian was consent loud enough to drown Collegium ink and still leave the living-key map unfinished on purpose.

She imagined his mouth on her charm, on her breasts, on the wet seam of her through cloth until she came quiet enough that Isolde’s stones could not file the sound. The fantasy was plot, not garnish—it decided how much truth she could speak while aching. Blue-bruise memory from the yards braided with want. Calderyn’s thinning wards somehow made her hungrier for the man who taught survival without promising salvation. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence. Hope and dread shared her cunt the way they shared Ashmere’s thresholds.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.

[player_name]’s nipples stayed tight under damp fabric. Every shift of cloth reminded her that Isolde’s politics and Thorne’s leftover song had both woken something filthier than fear. Cassian’s gaze kept dropping to her mouth like a man memorizing fracture lines on a body instead of a ward. When he spoke low, she felt the words between her legs—handler voice, battlemage voice, the voice of someone who had almost followed Thorne and now poured that almost into wanting her alive and wanting her, period. Sex was not violence cosplay. War magic could be brutal. What she wanted from Cassian was consent loud enough to drown Collegium ink and still leave the living-key map unfinished on purpose.

She imagined his mouth on her charm, on her breasts, on the wet seam of her through cloth until she came quiet enough that Isolde’s stones could not file the sound. The fantasy was plot, not garnish—it decided how much truth she could speak while aching. Blue-bruise memory from the yards braided with want. Calderyn’s thinning wards somehow made her hungrier for the man who taught survival without promising salvation. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence. Hope and dread shared her cunt the way they shared Ashmere’s thresholds.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.

[player_name]’s nipples stayed tight under damp fabric. Every shift of cloth reminded her that Isolde’s politics and Thorne’s leftover song had both woken something filthier than fear. Cassian’s gaze kept dropping to her mouth like a man memorizing fracture lines on a body instead of a ward. When he spoke low, she felt the words between her legs—handler voice, battlemage voice, the voice of someone who had almost followed Thorne and now poured that almost into wanting her alive and wanting her, period. Sex was not violence cosplay. War magic could be brutal. What she wanted from Cassian was consent loud enough to drown Collegium ink and still leave the living-key map unfinished on purpose.

She imagined his mouth on her charm, on her breasts, on the wet seam of her through cloth until she came quiet enough that Isolde’s stones could not file the sound. The fantasy was plot, not garnish—it decided how much truth she could speak while aching. Blue-bruise memory from the yards braided with want. Calderyn’s thinning wards somehow made her hungrier for the man who taught survival without promising salvation. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence. Hope and dread shared her cunt the way they shared Ashmere’s thresholds.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.

[player_name]’s nipples stayed tight under damp fabric. Every shift of cloth reminded her that Isolde’s politics and Thorne’s leftover song had both woken something filthier than fear. Cassian’s gaze kept dropping to her mouth like a man memorizing fracture lines on a body instead of a ward. When he spoke low, she felt the words between her legs—handler voice, battlemage voice, the voice of someone who had almost followed Thorne and now poured that almost into wanting her alive and wanting her, period. Sex was not violence cosplay. War magic could be brutal. What she wanted from Cassian was consent loud enough to drown Collegium ink and still leave the living-key map unfinished on purpose.`,
  choices: [
    { id: "scene7o", text: "Politics: she goes public to protect Cassian", textHot: "Politics: go public — spend your wet courage as his shield" },
    { id: "scene7p", text: "Chase: reunion at the cliff festival of bells", textHot: "Chase: let him find you at the festival of bells — mid-want in copper dark" }
  ]
};
