export default {
  id: "scene6p",
  layer: 6,
  title: "She walks — Cassian has to chase both war and her",
  text: `She walked.

Not out of Ashmere entirely—not yet—but out of the interrogation circle, out of Isolde’s antechamber politics, out of Cassian Rook’s reach for long enough that he would have to choose how to split himself between war and wanting. Salt wind hit [player_name]’s face on the cliff stairs like a slap that was also a kiss. Copper bells screamed a thin watch-change behind her. Veil Sea fog climbed to meet her boots. Her cracked charm ticked hard against her throat, almost-seal ghost under her sternum answering every wrong interval as if the stone itself were asking her to stay and be useful.

Cassian’s voice found her from the landing above—not shouting, not yet chasing. “If you walk, I still have a ward-line failing inland and a Headmistress sharpening knives and a badge number that wants my throat. I will chase the war. Then I will chase you. Do not make me choose the order wrongly.”

[player_name] did not turn. Mid-want burned under her ribs anyway—scorched leather memory, glove on pulse, unfinished obstruction fight, shielded almosts, raid maps on oilcloth. She had tipped Maris. She had watched blowups. She had knelt in ash. She had put her body between him and Isolde. Walking was not abandonment of the romance lock; it was a dare that trust could survive distance under apocalypse pressure. Living-key fog still contested. Sacrifice map still blank. Thorne still unfinished as monster or revolutionary. Unmade still pressing. Hope and dread sharing the stair like twin companions who refused to blink.

Practice yards’ blue bruises glowed far below through fog. Calderyn’s aurora-glass markets dimmed somewhere beyond sight. Maris Quill’s fear still walked halls [player_name] was leaving. Bram’s hymns still muttered refusal without cost. Isolde’s sealed drawer still waited with dual-consent brass and lineage pages that might name a chain without confirming [player_name]’s place—late-layer bait circling back if she chose the ledger path instead of the festival chase.

Festival of bells would light the cliff tonight: lanterns, copper noise, almost-privacy, reunion written into tradition. Cassian would find her there if she let the holiday become a hinge. Or she could circle toward Isolde’s sealed drawer while he split himself—war first, her second—and meet him at the ledger with eyes open, living-key ambiguity still locked, wanting still unfinished.

She touched the charm once, private. Rain tracked copper on the stair rail. Ozone lingered from a braid she had cast alone earlier and failed on purpose to feel the cliff answer. Cassian’s sealed past still lived behind one ashwood drawer in his quarters. Her own almost-becoming-key still lived behind Isolde’s smile. Walking forced both truths into motion.

“I’m not Isolde’s,” she said to the fog, loud enough for the landing. “I’m not walking from you. I’m walking until you prove you can chase both without making me the only war you bill.”

Boots on stone above—pursuit beginning, delayed by duty, inevitable. Mid-want hummed. Romance lock held across distance. The hinge sharpened in salt wind: reunion at the cliff festival of bells—or sealed drawer and ledger lineage fog, Cassian chasing both war and her into whichever consequence-verb she left burning behind her like a ward-light in the mist.

Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.

Ashmere Collegium held its breath the way cliff stone held salt: slowly, permanently, with a patience that punished anyone who mistook endurance for kindness. Calderyn beyond the fog was not a map problem alone; it was failing farmlands, aurora-glass markets dimming, border villages that heard Unmade whispers first. Living-key rumors remained contested on purpose. Bram’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure had a smell: spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge.

Practice yards below still carried blue-bruise afterglow; chalk circles smeared by rain waited for the next braid; copper bells scored every almost-confession happening above the waterline. Maris Quill’s fear still walked the dining halls. Ambiguity locked itself again: no confirmation [player_name] was lineage; no clean monster-label for Thorne; no opened drawer; only salt, bells, Cassian’s unfinished mouth, and choice sharpening consequence-verbs in the cliff wind. The Collegium did not gift mercy. The Unmade did not pause for romance. [player_name] carried both truths beside the cracked charm’s tick and the scorched-leather nearness of a handler who refused to let her become ink.

Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.

Ashmere Collegium held its breath the way cliff stone held salt: slowly, permanently, with a patience that punished anyone who mistook endurance for kindness. Calderyn beyond the fog was not a map problem alone; it was failing farmlands, aurora-glass markets dimming, border villages that heard Unmade whispers first. Living-key rumors remained contested on purpose. Bram’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure had a smell: spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge.

Practice yards below still carried blue-bruise afterglow; chalk circles smeared by rain waited for the next braid; copper bells scored every almost-confession happening above the waterline. Maris Quill’s fear still walked the dining halls. Ambiguity locked itself again: no confirmation [player_name] was lineage; no clean monster-label for Thorne; no opened drawer; only salt, bells, Cassian’s unfinished mouth, and choice sharpening consequence-verbs in the cliff wind. The Collegium did not gift mercy. The Unmade did not pause for romance. [player_name] carried both truths beside the cracked charm’s tick and the scorched-leather nearness of a handler who refused to let her become ink.

Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.

Ashmere Collegium held its breath the way cliff stone held salt: slowly, permanently, with a patience that punished anyone who mistook endurance for kindness. Calderyn beyond the fog was not a map problem alone; it was failing farmlands, aurora-glass markets dimming, border villages that heard Unmade whispers first. Living-key rumors remained contested on purpose. Bram’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure had a smell: spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge.

Practice yards below still carried blue-bruise afterglow; chalk circles smeared by rain waited for the next braid; copper bells scored every almost-confession happening above the waterline. Maris Quill’s fear still walked the dining halls. Ambiguity locked itself again: no confirmation [player_name] was lineage; no clean monster-label for Thorne; no opened drawer; only salt, bells, Cassian’s unfinished mouth, and choice sharpening consequence-verbs in the cliff wind. The Collegium did not gift mercy. The Unmade did not pause for romance. [player_name] carried both truths beside the cracked charm’s tick and the scorched-leather nearness of a handler who refused to let her become ink.`,
  textHot: `She walked—and [player_name]’s cunt ached with every stair as if distance itself were a denial kink she had invented to survive Collegium hunger. Salt wind slapped her face. Copper bells screamed watch-change. Veil Sea fog climbed her boots. Cracked charm ticked between her breasts; nipples tight; mid-want roaring because Cassian Rook was above her on the landing smelling of scorched leather and unfinished fights and she was making him split himself between war and her on purpose.

“If you walk,” he called, voice soft enough to feel on wet skin even at distance, “I chase the war. Then I chase you. Do not make me choose the order wrongly.”

She did not turn. Slick thighs. Empty flutter. Romance lock Cassian only—Thorne’s frequency stroking cliff stone somewhere as temptation, not lover. Living-key fog contested. Sacrifice unfinished. Unmade pressing. Hope and dread sharing her body while she dared trust to survive distance.

Festival bells tonight meant lantern fog and reunion mouth. Sealed drawer meant circling back to Isolde’s lineage ledger while he chased—dual consent, contested pages, his heat arriving mid-read like a glove on her pulse. Either path filthy with unfinished want.

“I’m not walking from you,” she told the fog, loud for him. “I’m walking until you prove you can chase both without billing me as your only war.” Her laugh broke wet. “When you find me, I want your mouth first and Isolde’s knives second. Festival or drawer—your chase, my hinge.”

Boots on stone above—pursuit delayed by duty, inevitable, hard. [player_name] pressed her palm to cold rail and felt Ashmere answer wrong and right at once. Mid-want refused tidy endings. He had not taken her yet. The ache was the point—and the plot. Copper noise. Salt. Blade-oil memory. The choice waited slick in the mist: let reunion catch her at the festival of bells—or circle to the sealed drawer’s living-key lineage fog while Cassian Rook chased both war and her under rain-dark towers.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.

[player_name]’s nipples stayed tight under damp fabric. Every shift of cloth reminded her that Isolde’s politics and Thorne’s leftover song had both woken something filthier than fear. Cassian’s gaze kept dropping to her mouth like a man memorizing fracture lines on a body instead of a ward. When he spoke low, she felt the words between her legs—handler voice, battlemage voice, the voice of someone who had almost followed Thorne and now poured that almost into wanting her alive and wanting her, period. Sex was not violence cosplay. War magic could be brutal. What she wanted from Cassian was consent loud enough to drown Collegium ink and still leave the living-key map unfinished on purpose.

She imagined his mouth on her charm, on her breasts, on the wet seam of her through cloth until she came quiet enough that Isolde’s stones could not file the sound. The fantasy was plot, not garnish—it decided how much truth she could speak while aching. Blue-bruise memory from the yards braided with want. Calderyn’s thinning wards somehow made her hungrier for the man who taught survival without promising salvation. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence. Hope and dread shared her cunt the way they shared Ashmere’s thresholds.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.

[player_name]’s nipples stayed tight under damp fabric. Every shift of cloth reminded her that Isolde’s politics and Thorne’s leftover song had both woken something filthier than fear. Cassian’s gaze kept dropping to her mouth like a man memorizing fracture lines on a body instead of a ward. When he spoke low, she felt the words between her legs—handler voice, battlemage voice, the voice of someone who had almost followed Thorne and now poured that almost into wanting her alive and wanting her, period. Sex was not violence cosplay. War magic could be brutal. What she wanted from Cassian was consent loud enough to drown Collegium ink and still leave the living-key map unfinished on purpose.

She imagined his mouth on her charm, on her breasts, on the wet seam of her through cloth until she came quiet enough that Isolde’s stones could not file the sound. The fantasy was plot, not garnish—it decided how much truth she could speak while aching. Blue-bruise memory from the yards braided with want. Calderyn’s thinning wards somehow made her hungrier for the man who taught survival without promising salvation. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence. Hope and dread shared her cunt the way they shared Ashmere’s thresholds.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.

[player_name]’s nipples stayed tight under damp fabric. Every shift of cloth reminded her that Isolde’s politics and Thorne’s leftover song had both woken something filthier than fear. Cassian’s gaze kept dropping to her mouth like a man memorizing fracture lines on a body instead of a ward. When he spoke low, she felt the words between her legs—handler voice, battlemage voice, the voice of someone who had almost followed Thorne and now poured that almost into wanting her alive and wanting her, period. Sex was not violence cosplay. War magic could be brutal. What she wanted from Cassian was consent loud enough to drown Collegium ink and still leave the living-key map unfinished on purpose.

She imagined his mouth on her charm, on her breasts, on the wet seam of her through cloth until she came quiet enough that Isolde’s stones could not file the sound. The fantasy was plot, not garnish—it decided how much truth she could speak while aching. Blue-bruise memory from the yards braided with want. Calderyn’s thinning wards somehow made her hungrier for the man who taught survival without promising salvation. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence. Hope and dread shared her cunt the way they shared Ashmere’s thresholds.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.

[player_name]’s nipples stayed tight under damp fabric. Every shift of cloth reminded her that Isolde’s politics and Thorne’s leftover song had both woken something filthier than fear. Cassian’s gaze kept dropping to her mouth like a man memorizing fracture lines on a body instead of a ward. When he spoke low, she felt the words between her legs—handler voice, battlemage voice, the voice of someone who had almost followed Thorne and now poured that almost into wanting her alive and wanting her, period. Sex was not violence cosplay. War magic could be brutal. What she wanted from Cassian was consent loud enough to drown Collegium ink and still leave the living-key map unfinished on purpose.

She imagined his mouth on her charm, on her breasts, on the wet seam of her through cloth until she came quiet enough that Isolde’s stones could not file the sound. The fantasy was plot, not garnish—it decided how much truth she could speak while aching. Blue-bruise memory from the yards braided with want. Calderyn’s thinning wards somehow made her hungrier for the man who taught survival without promising salvation. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence. Hope and dread shared her cunt the way they shared Ashmere’s thresholds.`,
  choices: [
    { id: "scene7p", text: "Chase: reunion at the cliff festival of bells", textHot: "Chase: let reunion catch you at the festival — bells, fog, unfinished mouth" },
    { id: "scene7a", text: "Sealed drawer: ledger names the living-key linea", textHot: "Sealed drawer: circle back to Isolde’s ledger — open lineage fog with him chasing" }
  ]
};
