export default {
  id: "scene7n",
  layer: 7,
  title: "Inquiry: Cassian under review for closeness to candidate",
  text: `The inquiry chamber smelled of wax, salt, and Collegium judgment—ashwood rails, ward-tape pulsing, copper bells wrong overhead. Cassian Rook stood under review for closeness to his Warden-candidate while Isolde Vane’s proxy read charges that made devotion sound like conspiracy. [player_name] sat as witness, cracked charm ticking, mid-want humming under ribs because closeness was exactly what they had chosen and exactly what Ashmere wanted to punish.

“Handler Rook’s sealed inquiry remains a matter of record,” the proxy said. “His nearness to candidate [player_name] has compromised objectivity. Soft nets, burned hours, corridor theater, dusk readings that look like courtship. The assembly prefers martyrs to handlers who smile like blades.”

Cassian’s brutal charm stayed quiet. Practice-blade oil clung to him anyway. Scorched leather. Mid-thirties exhaustion sanded into posture that refused to apologize for keeping her a person. Living-key nomenclature withheld. Thorne unfinished. Bram’s hymns unfinished. Sealed drawer shut. Hope and dread shared the chamber.

[player_name] was invited to speak. She tasted copper. “Closeness kept me from becoming ink. Distance is how candidates burn quiet. If you want objectivity, measure the Unmade pressing Calderyn—not whether my handler’s glove found my pulse when Isolde reached for thread.”

Silence. Blue-bruise memory from yards. Veil Sea fog at the windows. Inland wards thinning. Maris’s fear. Isolde’s patience elsewhere billing interest.

Cassian’s eyes found hers—one unprofessional heartbeat. “Next hinge after they adjourn,” he had told her earlier. “Testify further in full hearing—or take the public storm and hide in the lower wards while politics tries to unmake us.”

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while inquiry wax cooled and choice waited between full testimony and lower-ward hiding. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while inquiry wax cooled and choice waited between full testimony and lower-ward hiding. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while inquiry wax cooled and choice waited between full testimony and lower-ward hiding. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while inquiry wax cooled and choice waited between full testimony and lower-ward hiding. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while inquiry wax cooled and choice waited between full testimony and lower-ward hiding. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while inquiry wax cooled and choice waited between full testimony and lower-ward hiding. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while inquiry wax cooled and choice waited between full testimony and lower-ward hiding. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while inquiry wax cooled and choice waited between full testimony and lower-ward hiding. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.`,
  textHot: `Inquiry should have iced her. Instead [player_name] sat wet-thighed while Cassian Rook stood under review for the crime of wanting her alive—and wanting her. Ashwood. Wax. Ward-tape. Copper bells. His scorched leather and blade-oil filled her head until her cunt ached with every charge that named corridor theater and dusk readings like courtship.

“Closeness,” the proxy said, and [player_name]’s empty fluttered. She wanted to stand and confess filth: that his glove on her pulse made her drip; that break-open still lived in her body; that romance locked on him alone while Thorne stayed rumor. She confessed stance instead—and the stance was hot enough.

When adjournment broke, Cassian caught her in a side corridor, forehead to hers, cock hard through restraint against her hip for one stolen second. “Testify in full hearing—or hide with me in lower wards through the public storm. Either way I’ll be filthy for how you spoke me human. Either way afterward—” His gloved thumb at her lower lip. Consent loud. Mid-want unfinished on purpose.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while inquiry wax flavored her mouth and choice waited between testimony and hiding with his cock still arguing duty. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while inquiry wax flavored her mouth and choice waited between testimony and hiding with his cock still arguing duty. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while inquiry wax flavored her mouth and choice waited between testimony and hiding with his cock still arguing duty. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while inquiry wax flavored her mouth and choice waited between testimony and hiding with his cock still arguing duty. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while inquiry wax flavored her mouth and choice waited between testimony and hiding with his cock still arguing duty. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while inquiry wax flavored her mouth and choice waited between testimony and hiding with his cock still arguing duty. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while inquiry wax flavored her mouth and choice waited between testimony and hiding with his cock still arguing duty. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while inquiry wax flavored her mouth and choice waited between testimony and hiding with his cock still arguing duty. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.`,
  choices: [
    { id: "scene8n", text: "Inquiry hearing: testify for Cassian", textHot: "Inquiry hearing: testify for Cassian — swear closeness as vow under Collegium eyes" },
    { id: "scene8o", text: "Public storm: they hide together in the lower wards", textHot: "Public storm: they hide together in the lower wards — weather the blast wet and hidden" }
  ]
};
