export default {
  id: "scene3c",
  layer: 3,
  title: "From 2b: tell Cassian her braid answered Thorne’s frequency",
  text: `The archive stairwell still smelled of ozone and old parchment when [player_name] found Cassian Rook in the lower stacks, scorched gloves tucked in his belt, practice-blade oil ghosting the air like a second cataloguing system. She had come from Bram Kestrel's forbidden shelf with the cracked throat-charm warm against her pulse and Thorne's mark still wet in her mind's eye—black on cliff stone, blooming the night her braid cracked Ashmere's outer ward-song. Salt wind shoved through a high slit window. Copper ward-bells far above tried a clean note and nearly failed. Calderyn's safety felt thin as the paper Bram refused to fully translate.

Cassian looked up from a ledger of fracture reports as if he had been waiting for her particular footsteps. Mid-thirties, scarred, brutal charm held quiet in a place that punished noise. Grey-green eyes flicked to the charm at her throat, then to her mouth, then away—handler discipline performing itself. "You smell like Bram's dust and Veil Sea fog," he said. "Tell me you found a hymn that helps. Tell me you did not find a reason to run."

[player_name] did not run. She stepped between the shelves until the aisle narrowed enough that confession had nowhere to hide. "My braid answered Thorne's frequency," she said. The words left her raw. "Not metaphor. Not fear. When I held the song at trial, something in the cliff sang back in his key. Bram's margins black that part out, but the stone does not. I felt it again near the mark. I am telling you because you are my handler, and because lying to you feels like cutting my own ward."

Silence stacked between them like unread folios. Cassian's jaw flexed. He set the ledger down with careful violence, the care more frightening than a slam. "Say it again," he murmured. "Slowly. So I cannot pretend I misheard."

She said it again. Ozone tasted bright on her tongue. The cracked charm clicked. Living-key rumors—blood that sang walls shut, candidates burned quiet, Isolde's sealed drawer—pressed the stacks without becoming proof. Thorne remained contested: monster, revolutionary, or both. The Unmade still pressed inland as hunger without a finished map. [player_name] watched Cassian's face for the moment he would become Collegium property instead of the man who had nearly followed Vesper once and stayed.

He became something sharper than either. "Then we have contact without contact," Cassian said. "A frequency bridge. Isolde will call it treason's cousin. I call it a fuse with your name on it." He dragged a hand down his face, glove-leather scent rising. "I should walk this upstairs before the bells finish failing. Report Thorne-adjacent resonance, put you under formal watch, raid the lower wards for echo-traps. That is the clean path. The path that keeps my sealed inquiry from growing a second mouth."

"And the unclean path?" [player_name] asked.

His laugh was soft and without mercy. "I build a softer net. I surveil without charging. I let you breathe while I map the frequency in private, which is another way of saying I put my career in your cracked charm and hope you do not crush it." He stepped closer. Shelves boxed them in. Rain ticked the slit window. "Do not look at me like that. Soft nets fail. Soft nets get people killed at borders when the whisper becomes teeth. I am offering it anyway because you told me the truth before Isolde could smell it on you, and that kind of trust is rare enough to make a battlemage stupid."

[player_name]'s pulse hammered against copper and skin. She thought of Maris Quill in the candidate halls—friend-pressure, rumor, fear—of how easily a formal raid could shatter whatever fragile honesty still lived between women training to die usefully. She thought of Bram's half-translated hymns disagreeing with themselves. She thought of Cassian's sealed past: the pushed breach, the civilians, the smile like a blade. Enough to know his fear of soft nets was earned.

"If you report hard," she said, "Isolde accelerates everything. She will talk about keys and need and consent that tastes like ink." She did not say living key aloud as settled fact. "If you go soft, someone else may tip her first. Maris has been hearing things. Or saying she has."

Cassian's eyes narrowed. "Maris Quill collects whispers the way Bram collects margins. Useful. Dangerous. If I raid the lower wards, she will know before the dust settles. If I do not, she may still invent a story that puts you in Thorne's pocket." He braced one hand on the shelf above [player_name]'s shoulder, not touching, close enough that practice-blade oil and salt became a weather system. "You have two honest moves left in this aisle. Beg me for the softer net—ask me to risk the inquiry for your breathing room. Or tip Maris yourself that a raid is coming, buy her trust, and accept that betrayal of my tactics is a kind of protection I will hate you for and possibly forgive." His mouth tilted. "I prefer the beg. I will survive the tip. Choose like the ward-song depends on it, because it might."

Far above, a bell stuttered. In the stacks, parchment dust hung in stormlight like pale ash that refused to mean funerals yet. [player_name] felt the cracked charm warm, then cool, as if Thorne's frequency had leaned close to listen to her choosing. Hope and dread shared the narrow aisle. Cassian waited, brutal charm locked behind duty, want under the lock like a second report he refused to file.

"I told you because I trust you," [player_name] said. "What I do next is how I keep that trust from becoming a weapon aimed at Calderyn—or at you."

Cassian's gaze dropped to her mouth for one unprofessional second and climbed back. "Then keep it. Or break it carefully. Mid-mistakes kill cleaner than pretty ones." He did not step back. The lower wards hummed faintly through the stone—Unmade pressure, Collegium copper, something almost familiar that still would not name itself. Choice opened between softer net and tipped rumor, both consequential, both unfinished on the living-key question, both leaving Lord Vesper Thorne contested in the dark.

Archivist Bram Kestrel's cough echoed faintly from a distant bay, a reminder that forbidden shelves had ears even when their keeper pretended to translate elsewhere. [player_name] pictured his blacked margins, the half-hymns that hinted blood could sing walls shut without ever drawing the sacrifice map she was not ready to see. Isolde would want that map finished early. Cassian wanted her alive long enough to argue with it. The difference was a romance plot disguised as war logistics.

"If I soften the net," Cassian continued, still caging her without contact, "you will owe me honesty every dawn. No more private frequencies. No more charming your way past my questions with that look." The look he meant lived in her face whether she permitted it or not: mid-twenties witch wanting a scarred instructor while the continent thinned. "If you tip Maris, you will owe me a different honesty—the kind that admits you chose her fear over my strategy. I can work with either debt. I cannot work with surprise."

[player_name] nodded once. Rain thickened at the slit window. Somewhere in Calderyn a border village would hear the Unmade whisper before Ashmere's bells admitted the thinness. She held that knowledge beside Cassian's almost-touch and felt choice settle into her bones like copper cooling after a braid. Soft net or tipped rumor. Desire as hazard. The living key still unnamed in full. Thorne still contested. The aisle waiting.

She remembered the night of the trial in flashes that the stacks made sharper: the braid holding longer than any candidate in a decade; the outer song cracking; Isolde naming her on the spot; Cassian assigned before applause died; the black sigil blooming on the cliff like a signature written in hunger. Telling him the frequency matched was not bravery alone. It was refusing to become Isolde's tidy fuse without a witness who had already burned for believing the wrong song once.

Cassian exhaled as if he had been holding the century's ward in his lungs. "Vesper could make people feel chosen," he said, quiet enough that Bram's distant cough could not steal the words. "That was his real magic before the Collegium called him Dark Sovereign. If your braid answers him, it may be answering the part of the stone that still wants to be chosen. Or it may be answering a trap. I will not pretend I know which. Knowing too early is how I killed a village with good intentions." He tapped the shelf near her ear—soft, precise. "Softer net means I hunt the trap without hanging you in the square. Tipping Maris means you build a second line of defense that does not run through me. Both are strategies. Only one keeps my hands on the map."

[player_name] heard copper bells try again above them and fail into a minor key. She thought of Headmistress Isolde Vane's rings flashing over wet ink, of consent language that opened doors and shut them, of living-key ambiguity still fogging every honest sentence. She was mid-twenties and newly marked, and the man in front of her was mid-thirties with a sealed inquiry and a mouth that could ruin her concentration for a week. Desire as the most dangerous spell she knew.

"I need a minute to choose," she said.

"You have a minute," Cassian answered. "The Unmade is generous with minutes right before it is not." He finally stepped half a pace back, giving her air that still smelled like him. The aisle widened into a decision theater. Fracture reports waited on the table. The cracked charm waited on her pulse. Maris waited somewhere with rumors. Thorne waited in the stone. [player_name] filled her lungs with parchment and salt and the copper taste of truth already spoken, and felt the next truth—the choice—rise like a second braid.`,
  textHot: `The archive stairwell still smelled of ozone and old parchment when [player_name] found Cassian Rook in the lower stacks, and her body reacted before her ethics did—nipples tightening under linen, cunt giving a slow shameful clench at the sight of scorched gloves in his belt and the blade-oil scent that meant he had come from violence dressed as drill. She had come from Bram's forbidden shelf with the cracked throat-charm warm against her pulse and Thorne's mark wet behind her eyes. Salt wind shoved through a slit window. Ward-bells nearly failed overhead. She was already wet from deciding to tell him the truth.

Cassian looked up as if he had been waiting to be ruined by her footsteps. Mid-thirties, scarred, brutal charm quiet. His gaze flicked to her charm, her mouth, the flush at her throat—handler discipline cracking. "You smell like Bram's dust and Veil Sea fog," he said, voice low enough to stroke. "Tell me you found a hymn that helps."

She stepped into the aisle until shelves forced proximity and confession had to share breath with want. "My braid answered Thorne's frequency," she said, and saying it made her clit throb—power, danger, trust braided into one filthy pulse. "Not metaphor. The cliff sang back in his key. I am telling you because lying to you feels like cutting my own ward."

Cassian's jaw flexed. He set the ledger down with careful violence. "Say it again. Slowly." She did. Living-key rumors pressed without proof. Thorne stayed monster-or-revolutionary. Unmade hunger unfinished. [player_name] watched him choose between Collegium property and the man who almost followed Vesper—and her cunt ached for whichever man stepped closer.

He stepped closer. "Contact without contact. A fuse with your name on it." Glove-leather scent rose as he dragged a hand down his face. "I should report hard—formal watch, raid the lower wards. Clean path. Or I build a softer net, surveil without charging, put my career in your cracked charm." His laugh had no mercy. "Soft nets get people killed. I am offering one anyway because you told me the truth, and that kind of trust makes a battlemage stupid." Stupid looked good on him: pupils blown, mouth wet, cock already a thick outline against his trousers from standing near her fear.

[player_name]'s pulse hammered. Maris Quill. Bram's disagreeing hymns. "If you report hard, Isolde accelerates," she said, thighs pressed tight on slick heat. "If you go soft, someone tips her first."

He braced a hand on the shelf above her shoulder—not touching, worse than touching. Practice-blade oil and salt became weather. Her nipples peaked hard enough to hurt; her cunt fluttered as if his thigh had already slotted between hers against the folios. "Two honest moves," he murmured, voice sandpaper on her clit. "Beg me for the softer net—ask me to risk the inquiry while you stand there smelling like want. Or tip Maris that a raid is coming, buy her trust, betray my tactics with my heat still in your throat." His mouth tilted. "I prefer the beg. I will survive the tip. Choose like the ward-song depends on it."

A bell stuttered above. Parchment dust hung like pale ash. The cracked charm warmed against [player_name]'s skin while her cunt clenched on emptiness—want, unfinished, soaked for a man who might report her or ruin himself keeping her breathing. "I told you because I trust you," she said, voice rough. "What I do next is how I keep that trust from becoming a weapon."

Cassian's gaze dropped to her mouth, lingered on the damp hollow of her throat, climbed back with visible effort. His cock strained; he did not hide it. "Then keep it. Or break it carefully." He still did not step back. The lower wards hummed through stone. Choice opened—beg soft while wanting him hard, or tip Maris with betrayal hot in her throat—while living-key truth stayed contested and Lord Vesper Thorne stayed a frequency she could feel in her clit as much as her charm.

Archivist Bram Kestrel's cough echoed from a distant bay, and even that mundane sound stroked [player_name]'s nerves because everything in the stacks had become erotic by proximity—Cassian's forearm above her head, the heat rolling off him, the thick press of his cock a palm's width from her hip if she arched. She pictured blacked margins and unfinished sacrifice maps and wanted him to fuck the ambiguity out of her against the shelves until hymns made sense. He would not. Not tonight. Want was the ward.

"If I soften the net," he continued, voice filthy-soft, "you owe me honesty every dawn. No private frequencies. No charming me with that look." The look was her blown pupils, bitten lip, thighs slick. "If you tip Maris, you owe me the honesty of choosing her fear over my strategy." He leaned a fraction closer; her nipples brushed his chest through linen and she nearly moaned. "I can work with either debt. I cannot work with surprise—or with you coming on my thigh in an aisle before you pick a door."

She almost did anyway. Rain thickened. Border villages whispered. Soft net or tipped rumor. Her cunt ached, empty, shameless. Living key unnamed. Thorne contested. Cassian's mouth one breath away and refusing to close the distance until she chose.

She remembered the trial in flashes that made her wetter: braid holding; song cracking; Isolde naming her; Cassian assigned; Thorne's sigil blooming while her cunt—traitorous even then—noticed her new handler's mouth. Telling him the frequency matched was trust and arousal braided; she felt both in her clit like a struck bell.

Cassian exhaled. "Vesper could make people feel chosen." The name in his mouth stroked her. "If your braid answers him, it may want to be chosen—or it may be a trap. Knowing too early is how I killed a village with good intentions." He tapped the shelf by her ear; the vibration ran down her spine into the soaked heat between her legs. "Softer net: I hunt without hanging you. Tip Maris: you build a line that does not run through me. Only one keeps my hands on the map—and my hands, candidate, are not innocent when they are near you."

[player_name]'s nipples ached. She wanted those hands on her breasts, between her thighs, bracing her hips while he fucked frequency and fear out of her against Bram's forbidden shelf. Living-key fog still hung; Isolde's consent language still threatened; want still ruled. "I need a minute," she whispered.

"You have a minute." He stepped half a pace back. The loss of heat hurt. Air still smelled like blade oil and him. Her cunt clenched on nothing, slick, shameless, unfinished. Fracture reports waited. Maris waited. Thorne waited in the stone like a tongue against a pulse. [player_name] filled her lungs and felt choice rise like orgasm held at the edge—beg soft while wanting him hard, or tip Maris with betrayal still hot in her throat—and refused to come until the door was picked.

Dust motes drifted through stormlight and stuck to the damp at her collarbones; she imagined Cassian's tongue following them down, over the cracked charm, between her breasts, lower, until she forgot Thorne's name for one filthy minute. He would not give her that minute yet. He gave her strategy and the outline of his cock and the ethics of soft nets, and her body took all of it as foreplay.

"Look at me," he said, and she did—grey-green eyes, scar at the brow, mouth shaped for orders and apologies he had not earned the right to speak. Want punched low. Her clit pulsed against the seam of her clothes with every heartbeat. "If you beg, beg like you mean the war, not like you mean my belt. If you tip Maris, do it knowing I will smell her on your next lie." His thumb hovered near her lower lip and did not land; the almost-touch made her knees soft. "I am not a soft professor fantasy, [player_name]. I am the man who stayed when Vesper left. Staying has a body count. So does leaving. Pick which count you want me to risk for you tonight."

She tasted copper and parchment and her own want. The Unmade pressed the stone. Living-key ambiguity kept its fog. Want held her at the edge—nipples hard, cunt soaked, orgasm a door she refused to open until she chose the story door first. Cassian waited, brutal and hard and unfinished, exactly as dangerous as the frequency in the cliff. She rolled her shoulders once, felt linen scrape her aching nipples, and let the choice arrive wet and inevitable—softer net begged with her cunt still hungry, or Maris tipped while Cassian's heat still lived under her tongue like a secret kiss she had not taken. The aisle held its breath with her. War listened. Want listened harder. She picked a door with her whole soaked body. Cassian's eyes promised consequences either way—and a hunger that would outlive the consequence. She nodded once, undone.`,
  choices: [
    { id: "scene4e", text: "Beg Cassian for a softer net on Thorne", textHot: "Beg him soft while wanting him hard" },
    { id: "scene4f", text: "Tip Maris that Cassian will raid lower wards", textHot: "Tip Maris — betrayal with heat still in your throat" }
  ]
};
