export default {
  id: "scene7p",
  layer: 7,
  title: "Chase: reunion at the cliff festival of bells",
  text: `The cliff festival of bells lit Ashmere’s outer terraces with copper lanterns and salt wind—wrong intervals made ritual, Veil Sea fog turning dancers into almosts. [player_name] had walked; Cassian Rook had chased war and her both. He found her at the railing where Thorne’s mark still remembered how to bloom unfinished on the cliff face below lantern light.

“You walked,” he said, mid-thirties breath rough, scorched leather damp with fog. Practice-blade oil under festival soap. Brutal charm wrecked into honesty. “I chased maps and I chased you. I’m done pretending those are separate hunts.”

[player_name]’s cracked charm ticked. Living-key fog contested. Isolde’s politics still billing. Prefects’ chains still half-named. Bram’s hymns unfinished. Maris’s fear somewhere in lantern dark. Hope and dread shared the railing. Mid-want hummed hard enough to hurt.

Copper bells changed watch into music that almost found true intervals and failed beautifully. Calderyn inland still thinned. Unmade still pressed. Cassian’s sealed drawer still shut. He did not propose marriage. He proposed truth.

“Stay through the anniversary hour,” he said. “Or take the ledger public and name the living-key chain as far as fog allows—still short of your name confirmed if Isolde’s ink holds. Either way I’m in the sentence.”

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while festival bells scored the reunion and choice waited between anniversary truth and ledger daylight. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while festival bells scored the reunion and choice waited between anniversary truth and ledger daylight. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while festival bells scored the reunion and choice waited between anniversary truth and ledger daylight. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while festival bells scored the reunion and choice waited between anniversary truth and ledger daylight. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while festival bells scored the reunion and choice waited between anniversary truth and ledger daylight. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while festival bells scored the reunion and choice waited between anniversary truth and ledger daylight. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while festival bells scored the reunion and choice waited between anniversary truth and ledger daylight. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while festival bells scored the reunion and choice waited between anniversary truth and ledger daylight. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.`,
  textHot: `Festival fog made [player_name]’s skin damp; reunion made her cunt ache. Cassian Rook caught her at the railing—chase ending in breath and blade-oil and a mouth that had been unfinished for layers. She kissed him first, shameless, public enough to dare Isolde’s spies, private enough that her hips rolled once against his hard cock through festival cloth.

“You walked,” he said into her mouth. “I got hard chasing you and hated myself for noticing while the Unmade pressed. I’m done hating the noticing.”

Gloved hand at her waist—then under cloak, fingers skating the wet seam of her until she gasped copper into the bells. Not finishing. Mid-want lock. Consent: “Here?” he asked. “Yes—edge me,” she answered. He did—clit strokes timed to wrong copper intervals until she shook on the edge and he stopped, forehead to hers, vow unfinished.

“Anniversary truth—or ledger public,” he whispered. “Either way afterward I finish you where fog hides the sound. Romance locked. Living-key still contested. Thorne still rumor. You still mine by choice, not collar.”

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while festival bells scored her edged cunt and choice waited between anniversary truth and ledger daylight. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while festival bells scored her edged cunt and choice waited between anniversary truth and ledger daylight. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while festival bells scored her edged cunt and choice waited between anniversary truth and ledger daylight. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while festival bells scored her edged cunt and choice waited between anniversary truth and ledger daylight. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while festival bells scored her edged cunt and choice waited between anniversary truth and ledger daylight. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while festival bells scored her edged cunt and choice waited between anniversary truth and ledger daylight. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while festival bells scored her edged cunt and choice waited between anniversary truth and ledger daylight. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while festival bells scored her edged cunt and choice waited between anniversary truth and ledger daylight. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.`,
  choices: [
    { id: "scene8p", text: "Cliff anniversary: proposal of truth not marriage", textHot: "Cliff anniversary: proposal of truth not marriage — unfinished mouth in festival fog" },
    { id: "scene8a", text: "Ledger public: name the living-key chain", textHot: "Ledger public: name the living-key chain — daylight the fog as far as ink allows" }
  ]
};
