export default {
  id: "scene7m",
  layer: 7,
  title: "Raid: hold/don’t-hold the ward-line (non-gore; consequence)",
  text: `The ward-line raid began in blue hour above the cliff stairs—Ashmere’s outer song thin as wire, Veil Sea fog climbing like a second army, copper bells already missing intervals. [player_name] took position beside Cassian Rook where chalk circles smeared by rain still glowed faint from dusk practice. Scorched leather. Practice-blade oil. Mid-thirties focus that could become tenderness or violence and tonight needed both without confusing them.

“Hold means we braid until our blood-song stitches the fracture,” Cassian said, voice low for her alone. “Don’t-hold means we fall back and let Isolde’s prefects claim the theater—and maybe lose a border village’s quiet hour. Non-gore either way. Consequence either way. I want your pulse honest. I do not want your martyrdom.”

[player_name]’s cracked charm ticked. Living-key fog contested. Unmade pressure tasted like cold iron without blood-spectacle—pressure, wrong weather, stone that hummed like a toothache. Thorne’s mark somewhere behind fog remained unfinished. Maris’s fear walked halls they had left. Bram’s hymns unfinished. Isolde billing interest. Hope and dread shared the chalk line.

They braided. Salt wind. Ozone. Cassian’s glove at her wrist when the song bucked—anchor, not leash. The line held, then frayed, then asked the verb: push harder like the border mistake in his sealed past, or release and survive to fight with maps instead of martyrs. [player_name] felt mid-want even here—competence as heat, trust as plot—while war stayed brutal without becoming porn of wounds.

“Your call,” Cassian said through his teeth as the fracture brightened wrong. “Hold with me—or don’t. Either path writes aftermath: hospital quiet if the line bites back, or inquiry if closeness looks like conspiracy under Collegium eyes.”

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while the ward-line hummed and hold-or-release waited like a blade between hospital quiet and inquiry fire. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while the ward-line hummed and hold-or-release waited like a blade between hospital quiet and inquiry fire. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while the ward-line hummed and hold-or-release waited like a blade between hospital quiet and inquiry fire. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while the ward-line hummed and hold-or-release waited like a blade between hospital quiet and inquiry fire. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while the ward-line hummed and hold-or-release waited like a blade between hospital quiet and inquiry fire. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while the ward-line hummed and hold-or-release waited like a blade between hospital quiet and inquiry fire. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while the ward-line hummed and hold-or-release waited like a blade between hospital quiet and inquiry fire. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while the ward-line hummed and hold-or-release waited like a blade between hospital quiet and inquiry fire. The Unmade pressed like weather that had learned her name; Thorne’s mark on the cliff face stayed wet and unfinished as monster or revolutionary; romance locked on Cassian alone.`,
  textHot: `Raid heat should have been fear alone. It wasn’t. [player_name]’s cunt clenched when Cassian Rook’s glove found her wrist at the ward-line—scorched leather, blade-oil, mid-thirties mouth counting breaths with her while Unmade pressure made the air thick as a held orgasm denied. Copper bells wrong. Charm ticking between her breasts. Nipples tight in salt wind. Empty aching under war wool.

“Hold or don’t,” he said against her ear, and the words felt filthy because choosing with him always did. She braided wet-nerved, magic riding her like want, his thigh braced behind hers. Not sex. Bodies honest in consequence. When the fracture bucked she gasped and felt him hard for one shocked second against her hip—adrenaline and desire refusing to separate cleanly—then he angled away, consent and discipline loud.

“After,” he promised roughly. “Hospital if it bites. Inquiry if they smell how close we stand. Either way my mouth owes your pulse for staying a person on this chalk.” She dripped for the promise while choosing whether to hold the line or release it, mid-want as war engine, living-key unfinished, Thorne rumor only, romance locked.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while the ward-line hummed through her cunt and hold-or-release waited with his cock restrained by duty. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while the ward-line hummed through her cunt and hold-or-release waited with his cock restrained by duty. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while the ward-line hummed through her cunt and hold-or-release waited with his cock restrained by duty. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while the ward-line hummed through her cunt and hold-or-release waited with his cock restrained by duty. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while the ward-line hummed through her cunt and hold-or-release waited with his cock restrained by duty. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while the ward-line hummed through her cunt and hold-or-release waited with his cock restrained by duty. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while the ward-line hummed through her cunt and hold-or-release waited with his cock restrained by duty. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while the ward-line hummed through her cunt and hold-or-release waited with his cock restrained by duty. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs.`,
  choices: [
    { id: "scene8m", text: "Raid aftermath: Cassian wounded lightly / hospital vs chase", textHot: "Raid aftermath: Cassian wounded lightly / hospital vs chase — tend him hot or chase with blood-taste want" },
    { id: "scene8n", text: "Inquiry hearing: testify for Cassian", textHot: "Inquiry hearing: testify for Cassian — swear closeness as vow under Collegium eyes" }
  ]
};
