export default {
  id: "scene8d",
  layer: 8,
  title: "Page burned: mercy or cowardice",
  text: `The kitchen in the lower residential wards smelled like mercy and cowardice wearing the same coat. A copper bowl held the last ash of the cream page [player_name] had chosen to burn rather than read into another throat. Smoke thinned toward a salt-streaked window. Outside, Ashmere’s cliff fortress breathed Veil Sea fog; inland, Calderyn thinned; the Unmade stayed contested. Cassian Rook stood at the tap with cracked knuckles damp, scorched leather jacket open, mid-thirties face unreadable in the way of men who had burned worse things and still refused to narrate them fully.

“Page burned,” he said, voice low. “Mercy—or cowardice. Both can be true. Neither invents a finished living-key sacrifice out of ash. Neither settles Thorne.”

Lord Vesper Thorne remained warm wine over broken glass somewhere beyond fog—temptation rumor, not second LI. Romance lock stayed on the man who had held the bowl while she lit the match and had not taken the fire as permission to open his sealed drawer.

[player_name]’s cracked charm ticked cooler without the page’s frequency near it. Recognition without ownership had become absence without verdict. Ambiguity remained. Bram’s refusal grammar survived only in her memory now. Isolde would smell smoke eventually. Maris would ask. The Collegium would invent a story if she didn’t choose the next verb first.

“Sealed pages means we wake beside smoke and a handler who held the bowl—file dark where Isolde cannot sand it soft, us living with what fire kept private,” Cassian said. “Cliff dawn means we walk the stairs where a mark once bloomed and ask whether leaving or staying is the cleaner burn. Both doors remember what you lit. Neither invents tidy martyrdom out of ash.”

She tasted smoke at the back of her throat. Attraction sharpened around ruin without needing a second name for his sealed past. The bowl cooled. Ashmere’s rain kept time on the glass while she chose sealed life or cliff fog with ash still ghosting her tongue and Cassian waiting like a man who would not pretend fire was tidy.

Salt wind. Ozone ghost from yesterday’s braid. Copper bells far above. Practice-blade oil on his gloves laid beside the sink. Living-key sacrifice still a shape without clean edges—burning earned mercy-or-cowardice into the room; it did not earn a full map. Unmade still pressing every honest border. Hope and dread shared the kitchen’s small doorway.

She thought of Isolde’s ashwood invoice, of dual-consent bowls, of Cassian nearly following Thorne, of civilians in a breach he still would not dump in full. Secrets planted early. Payoffs late. Fire was a verb. It was not an ending.

“Quiet deal if sealing parts of what remains keeps us human,” she said carefully. “Cliff dawn if leave-or-stay is the weather ash deserves. Eyes open. Throat still mine until I spend it.” Cassian’s mouth flicked—blade in velvet. “I stay human either way. Or I become the clearance fear Isolde is already drafting.”

Maris’s friend-fear pressed somewhere above in candidate halls. Bram’s shelves would notice a missing page by scent if not by gap. Thorne’s mark remembered bloom without romance. [player_name] held ash and hinge and Cassian’s damp knuckles.

The bowl ticked from heat to cool. She catalogued: location—lower-ward kitchen, ash, rain on glass; intensity—charm cooler, pulse loud; ask—quiet seal on what fire left, or cliff dawn leave-or-stay. Mid-want hummed under smoke. Partnership not mood. Want not weakness.

Cassian did not open his sealed drawer to match her fire. She loved him a little for that refusal and hated how love under apocalypse pressure felt like another spell with teeth. Person first. Key never only. Sacrifice still fog.

Outside, copper bells changed watch. Fog climbed the cliff stairs. Calderyn failed by inches. [player_name] stood between quiet-deal darkness and cliff-dawn weather with living-key ambiguity still in her mouth, Thorne unfinished outside romance lock, and the next verb waiting like weather with teeth while Ashmere’s kitchen kept score in smoke, salt, and a man who had held the bowl without pretending mercy was clean.

Salt wind kept score on the glass. Ozone clung like breath after a denied kiss. Copper bells tasted the air for fracture and found enough to keep their tongues restless. Calderyn thinned by inches beyond Veil Sea fog. The Unmade pressed every honest map without offering tidy martyrdom. Cassian Rook’s scorched leather stayed in the room like a vow that refused Collegium ink. Living-key sacrifice stayed a shape without clean edges unless this hinge had already earned its partial. Thorne remained temptation-shaped rumor—warm wine over broken glass—never a second LI while romance locked on Cassian. Mid-want hummed unfinished under duty. Hope and dread shared the doorway. Eyes open. Person first. Key never only. The hinge asked again, sharper by 891 breaths of unfinished wanting.

Salt wind kept score on the glass. Ozone clung like breath after a denied kiss. Copper bells tasted the air for fracture and found enough to keep their tongues restless. Calderyn thinned by inches beyond Veil Sea fog. The Unmade pressed every honest map without offering tidy martyrdom. Cassian Rook’s scorched leather stayed in the room like a vow that refused Collegium ink. Living-key sacrifice stayed a shape without clean edges unless this hinge had already earned its partial. Thorne remained temptation-shaped rumor—warm wine over broken glass—never a second LI while romance locked on Cassian. Mid-want hummed unfinished under duty. Hope and dread shared the doorway. Eyes open. Person first. Key never only. The hinge asked again, sharper by 767 breaths of unfinished wanting.

Salt wind kept score on the glass. Ozone clung like breath after a denied kiss. Copper bells tasted the air for fracture and found enough to keep their tongues restless. Calderyn thinned by inches beyond Veil Sea fog. The Unmade pressed every honest map without offering tidy martyrdom. Cassian Rook’s scorched leather stayed in the room like a vow that refused Collegium ink. Living-key sacrifice stayed a shape without clean edges unless this hinge had already earned its partial. Thorne remained temptation-shaped rumor—warm wine over broken glass—never a second LI while romance locked on Cassian. Mid-want hummed unfinished under duty. Hope and dread shared the doorway. Eyes open. Person first. Key never only. The hinge asked again, sharper by 643 breaths of unfinished wanting.

Salt wind kept score on the glass. Ozone clung like breath after a denied kiss. Copper bells tasted the air for fracture and found enough to keep their tongues restless. Calderyn thinned by inches beyond Veil Sea fog. The Unmade pressed every honest map without offering tidy martyrdom. Cassian Rook’s scorched leather stayed in the room like a vow that refused Collegium ink. Living-key sacrifice stayed a shape without clean edges unless this hinge had already earned its partial. Thorne remained temptation-shaped rumor—warm wine over broken glass—never a second LI while romance locked on Cassian. Mid-want hummed unfinished under duty. Hope and dread shared the doorway. Eyes open. Person first. Key never only. The hinge asked again, sharper by 519 breaths of unfinished wanting.

Salt wind kept score on the glass. Ozone clung like breath after a denied kiss. Copper bells tasted the air for fracture and found enough to keep their tongues restless. Calderyn thinned by inches beyond Veil Sea fog. The Unmade pressed every honest map without offering tidy martyrdom. Cassian Rook’s scorched leather stayed in the room like a vow that refused Collegium ink. Living-key sacrifice stayed a shape without clean edges unless this hinge had already earned its partial. Thorne remained temptation-shaped rumor—warm wine over broken glass—never a second LI while romance locked on Cassian. Mid-want hummed unfinished under duty. Hope and dread shared the doorway. Eyes open. Person first. Key never only. The hinge asked again, sharper by 395 breaths of unfinished wanting.

Salt wind kept score on the glass. Ozone clung like breath after a denied kiss. Copper bells tasted the air for fracture and found enough to keep their tongues restless. Calderyn thinned by inches beyond Veil Sea fog. The Unmade pressed every honest map without offering tidy martyrdom. Cassian Rook’s scorched leather stayed in the room like a vow that refused Collegium ink. Living-key sacrifice stayed a shape without clean edges unless this hinge had already earned its partial. Thorne remained temptation-shaped rumor—warm wine over broken glass—never a second LI while romance locked on Cassian. Mid-want hummed unfinished under duty. Hope and dread shared the doorway. Eyes open. Person first. Key never only. The hinge asked again, sharper by 271 breaths of unfinished wanting.

Salt wind kept score on the glass. Ozone clung like breath after a denied kiss. Copper bells tasted the air for fracture and found enough to keep their tongues restless. Calderyn thinned by inches beyond Veil Sea fog. The Unmade pressed every honest map without offering tidy martyrdom. Cassian Rook’s scorched leather stayed in the room like a vow that refused Collegium ink. Living-key sacrifice stayed a shape without clean edges unless this hinge had already earned its partial. Thorne remained temptation-shaped rumor—warm wine over broken glass—never a second LI while romance locked on Cassian. Mid-want hummed unfinished under duty. Hope and dread shared the doorway. Eyes open. Person first. Key never only. The hinge asked again, sharper by 147 breaths of unfinished wanting.

Salt wind kept score on the glass. Ozone clung like breath after a denied kiss. Copper bells tasted the air for fracture and found enough to keep their tongues restless. Calderyn thinned by inches beyond Veil Sea fog. The Unmade pressed every honest map without offering tidy martyrdom. Cassian Rook’s scorched leather stayed in the room like a vow that refused Collegium ink. Living-key sacrifice stayed a shape without clean edges unless this hinge had already earned its partial. Thorne remained temptation-shaped rumor—warm wine over broken glass—never a second LI while romance locked on Cassian. Mid-want hummed unfinished under duty. Hope and dread shared the doorway. Eyes open. Person first. Key never only. The hinge asked again, sharper by 23 breaths of unfinished wanting.`,
  textHot: `The kitchen still ticked heat from the bowl when Cassian boxed [player_name] against the counter. Smoke thinned. Ash settled like a small obedient funeral for paper that had never been a corpse. His hand shoved into her jeans without ceremony—two fingers finding her shamefully slick from watching paper die—and he fucked the choice into her with kitchen patience, thumb on her clit, mouth at her ear. Scorched leather creaked. Mid-thirties sleep-carved want banked into something filthy and careful. Mid-want was the slick fact under mercy-or-cowardice.

“Sealed life and I make you come against this counter with ash on your tongue until soft darkness feels like a verb you chose,” he growled. “Cliff dawn and I walk you to the stairs still dripping, leave-or-stay spoken while my fingers smell like your cunt and burnt cream paper—because unfinished heat is how we refuse to let fire become a funeral for a map Ashmere has not finished naming.”

[player_name] came close and was denied—Cassian easing out, painting her lower lip with a wet thumb, eyes wrecked and careful. The kitchen cooled enough to pretend the fire had only been paperwork. He waited. The bowl cooled. She had to pick sealed sheets or cliff fog with smoke still in her cunt’s memory.

Thorne stayed temptation rumor beyond the glass—never invited into this kitchen sex. Romance locked on Cassian’s fingers and the sealed drawer he still refused to open as cheap symmetry. Living-key sacrifice stayed fog; burning earned this hinge, not a finished martyrdom. Unmade pressed. Nipples hard under her shirt. Charm cooler without the page. Want louder because of the absence.

She catalogued shamelessly: location—clit under his thumb, counter edge at her ass, smoke in her throat; intensity—knees negotiating tile; trigger—his refusal to let fire finish her into harvest or cheap absolution. Mid-want craft. Partnership with teeth.

His cock hard against her hip through wool—honest, filthy, banked—while ash ghosted her tongue. Denial on purpose. She hated it. She needed it. Data said she still had a self Isolde could not quietly remade out of smoke.

“Verb,” Cassian murmured, kissing the hinge of her jaw without taking center. “Quiet deal—seals as sheath—or cliff dawn leave-or-stay. Your cunt already knows the cost. Your mouth has to invoice it.”

Salt wind fretted the window. Copper bells tasted fracture far above. Calderyn thinned. She held quiet-deal and cliff-dawn slick and unresolved, sacrifice ambiguous, romance lock unbroken, fucking deferred one more breath because consequence mattered.

She imagined coming against the counter with Isolde’s future seals as filthy metaphor—then imagined cliff stairs and fog with his fingers still shiny. Both left her empty now. Empty meant choosing. Choosing meant person first.

[player_name] nodded against his mouth without taking the kiss fully. Ash. Salt. Blade-oil. Eyes open. Key never only. Cassian Rook waited like a man who would hold the bowl again if asked and still refuse to pretend mercy and cowardice couldn’t wear the same coat—while her cunt ached around the unfinished verb and Ashmere’s kitchen kept the only honest score: want unfinished until the door she picked had teeth she could ethically carry.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 1042 more unfinished breaths and did not come.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 914 more unfinished breaths and did not come.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 786 more unfinished breaths and did not come.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 658 more unfinished breaths and did not come.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 530 more unfinished breaths and did not come.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 402 more unfinished breaths and did not come.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 274 more unfinished breaths and did not come.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 146 more unfinished breaths and did not come.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 18 more unfinished breaths and did not come.`,
  choices: [
    { id: "scene9d", text: "Quiet deal: seal parts of the living-key file", textHot: "Quiet deal: seal parts of the living-key file with ash still on your tongue" },
    { id: "scene9h", text: "Cliff dawn: leave Ashmere or stay", textHot: "Cliff dawn: leave Ashmere or stay still dripping from his kitchen hands" }
  ]
};
