export default {
  id: "scene6m",
  layer: 6,
  title: "Bell-tower raid planning",
  text: `They planned the drowned bell-tower raid on the floor of the lower map-room where ward-lines glowed faintly through chalk and salt wind found every crack in the cliff fortress. Copper bells above Ashmere kept their thin watch. Veil Sea fog pressed the slit windows. Cassian Rook spread a oilcloth chart between them—blade-oil smell on his gloves, scorched leather creaking as he knelt, mid-thirties focus that made planning feel like intimacy even when the verbs were hold and don’t-hold.

“Maris named the tower beyond the fog-line,” he said. “Copper blood-rust rumors. Charm-twin possibilities. Prefects who may already be writing inland. We do not go as pilgrims. We go as a two-person braid: you on song-sense, me on impact. If the ward-line at the tower’s throat sings wrong, you decide whether we hold it shut or let it speak long enough to read. Non-gore protocol. Consequence anyway. The Unmade does not need our blood to make a point—it needs our hesitation.”

[player_name]’s cracked charm ticked against the map’s copper ink. Living-key language nowhere on the chart. Sacrifice map still unfinished. Thorne’s frequency still a contested rumor in stone. Isolde’s inquiry still drafting itself somewhere above. Hope and dread shared the oilcloth like twin compasses.

“If we raid tonight,” she said, “Isolde will call it obstruction of process. If we wait for council, the prefect chain cools and the tower keeps its ghosts. And if your closeness to me hits formal review before we move—” She glanced at his sealed past. “They will use proximity as a weapon either way.”

Cassian’s mouth flicked—blade in velvet. “They already are. Inquiry shadow is not rumor anymore; it’s a prefect with a polished badge asking how often my glove finds your pulse. We can walk into that review on purpose—honesty as shield—or we hit the tower first and let the ward-line’s truth outrun their paperwork. I’m not clean enough to pretend review won’t hurt. I’m clean enough to tell you I’d rather bleed for a held line than for Isolde’s theater.”

Blue chalk dust clung to [player_name]’s palms. Practice-yard bruise memory glowed under her sleeves. Ozone from a test braid still lived in the map-room curtains. Calderyn’s thinning song pressed inland through every incomplete ward-mark on the chart. Maris’s fear still walked memory. Bram’s hymns still muttered refusal without cost.

They traced approach routes: cliff stairs under fog, a service tunnel that smelled of old copper, a silence braid that would cost them speech for twenty minutes if cast dirty. Cassian’s shoulder brushed hers each time the chart wrinkled. Mid-want hummed under duty—unfinished corridor ask, unfinished obstruction fight, unfinished almosts that made raid-planning feel like undressing with maps.

“Hold means we risk becoming the wall,” Cassian said softly. “Don’t-hold means we risk letting something through that we then have to name. Neither choice finishes whether Thorne is monster or revolutionary. Neither opens my drawer. Neither writes your name into a lineage ledger Isolde hasn’t shown. Ambiguity stays locked. That’s the point of late layers. Tonight we only decide whether the tower hears us before the inquiry does.”

[player_name] looked at his scarred hands on the oilcloth and at the drowned tower’s inked X beyond fog. Salt. Copper. Blade oil. Trust under apocalypse pressure. The hinge sharpened: take the raid to the ward-line—or walk Cassian into closeness review and keep the wanting honest under Collegium eyes before fog and fire decided for them.

Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.

Ashmere Collegium held its breath the way cliff stone held salt: slowly, permanently, with a patience that punished anyone who mistook endurance for kindness. Calderyn beyond the fog was not a map problem alone; it was failing farmlands, aurora-glass markets dimming, border villages that heard Unmade whispers first. Living-key rumors remained contested on purpose. Bram’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure had a smell: spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge.

Practice yards below still carried blue-bruise afterglow; chalk circles smeared by rain waited for the next braid; copper bells scored every almost-confession happening above the waterline. Maris Quill’s fear still walked the dining halls. Ambiguity locked itself again: no confirmation [player_name] was lineage; no clean monster-label for Thorne; no opened drawer; only salt, bells, Cassian’s unfinished mouth, and choice sharpening consequence-verbs in the cliff wind. The Collegium did not gift mercy. The Unmade did not pause for romance. [player_name] carried both truths beside the cracked charm’s tick and the scorched-leather nearness of a handler who refused to let her become ink.

Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.

Ashmere Collegium held its breath the way cliff stone held salt: slowly, permanently, with a patience that punished anyone who mistook endurance for kindness. Calderyn beyond the fog was not a map problem alone; it was failing farmlands, aurora-glass markets dimming, border villages that heard Unmade whispers first. Living-key rumors remained contested on purpose. Bram’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure had a smell: spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge.

Practice yards below still carried blue-bruise afterglow; chalk circles smeared by rain waited for the next braid; copper bells scored every almost-confession happening above the waterline. Maris Quill’s fear still walked the dining halls. Ambiguity locked itself again: no confirmation [player_name] was lineage; no clean monster-label for Thorne; no opened drawer; only salt, bells, Cassian’s unfinished mouth, and choice sharpening consequence-verbs in the cliff wind. The Collegium did not gift mercy. The Unmade did not pause for romance. [player_name] carried both truths beside the cracked charm’s tick and the scorched-leather nearness of a handler who refused to let her become ink.

Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.

Ashmere Collegium held its breath the way cliff stone held salt: slowly, permanently, with a patience that punished anyone who mistook endurance for kindness. Calderyn beyond the fog was not a map problem alone; it was failing farmlands, aurora-glass markets dimming, border villages that heard Unmade whispers first. Living-key rumors remained contested on purpose. Bram’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure had a smell: spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge.

Practice yards below still carried blue-bruise afterglow; chalk circles smeared by rain waited for the next braid; copper bells scored every almost-confession happening above the waterline. Maris Quill’s fear still walked the dining halls. Ambiguity locked itself again: no confirmation [player_name] was lineage; no clean monster-label for Thorne; no opened drawer; only salt, bells, Cassian’s unfinished mouth, and choice sharpening consequence-verbs in the cliff wind. The Collegium did not gift mercy. The Unmade did not pause for romance. [player_name] carried both truths beside the cracked charm’s tick and the scorched-leather nearness of a handler who refused to let her become ink.`,
  textHot: `They planned the drowned bell-tower raid on the floor of the lower map-room—and [player_name] could not stop noticing Cassian Rook’s mouth while he talked hold and don’t-hold. Oilcloth chart. Blade-oil on gloves. Scorched leather. Salt wind through slit windows. Copper bells thin above. He knelt close enough that her cracked charm ticked between her breasts in time with his breath. Mid-want made every approach route feel like a path his hands might take on her body.

“You on song-sense,” he said. “Me on impact. If the ward-line sings wrong, you decide hold or release. Non-gore. Consequence anyway.” His glove traced the fog-line and [player_name] went slick watching competence, imagining that same glove tracing her inner thigh instead of copper ink.

Inquiry shadow lived in the room too—prefects asking how often his pulse-check found her wrist. Closeness as weapon. [player_name]’s nipples tightened under her shirt. “If we raid tonight I’m going to be wet the whole approach,” she admitted, shameless. “If we walk you into review first, I’ll be wet under their eyes remembering your thigh in the obstruction fight. Pick the filth you can survive.”

Cassian’s laugh wrecked. He leaned until his forehead nearly touched hers over the chart. “Romance lock. Cassian only. Thorne’s tower is temptation and rust, not a second lover. Living-key fog stays contested. I’m hard enough already from watching you read maps like you want to fuck the war into making sense.”

She caught his glove and pressed it flat over her charm—pulse, heat, claim-without-key. “Raid means I want your eyes on me when the line sings—not on Isolde’s invoice. Inquiry means I stand where they can see I’m choosing closeness on purpose. Either way you’re not leaving me as her martyr. Either way my cunt is already billing the next verb.”

He did not take her on the oilcloth. Mid-want held. Blue chalk on her palms. Empty aching. Hope and dread sharing the map-room while Veil Sea fog hid the drowned tower and Ashmere’s stones listened. The hinge waited wet: hit the ward-line—or walk him into review, closeness honest, want unfinished under copper bells.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.

[player_name]’s nipples stayed tight under damp fabric. Every shift of cloth reminded her that Isolde’s politics and Thorne’s leftover song had both woken something filthier than fear. Cassian’s gaze kept dropping to her mouth like a man memorizing fracture lines on a body instead of a ward. When he spoke low, she felt the words between her legs—handler voice, battlemage voice, the voice of someone who had almost followed Thorne and now poured that almost into wanting her alive and wanting her, period. Sex was not violence cosplay. War magic could be brutal. What she wanted from Cassian was consent loud enough to drown Collegium ink and still leave the living-key map unfinished on purpose.

She imagined his mouth on her charm, on her breasts, on the wet seam of her through cloth until she came quiet enough that Isolde’s stones could not file the sound. The fantasy was plot, not garnish—it decided how much truth she could speak while aching. Blue-bruise memory from the yards braided with want. Calderyn’s thinning wards somehow made her hungrier for the man who taught survival without promising salvation. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence. Hope and dread shared her cunt the way they shared Ashmere’s thresholds.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.

[player_name]’s nipples stayed tight under damp fabric. Every shift of cloth reminded her that Isolde’s politics and Thorne’s leftover song had both woken something filthier than fear. Cassian’s gaze kept dropping to her mouth like a man memorizing fracture lines on a body instead of a ward. When he spoke low, she felt the words between her legs—handler voice, battlemage voice, the voice of someone who had almost followed Thorne and now poured that almost into wanting her alive and wanting her, period. Sex was not violence cosplay. War magic could be brutal. What she wanted from Cassian was consent loud enough to drown Collegium ink and still leave the living-key map unfinished on purpose.

She imagined his mouth on her charm, on her breasts, on the wet seam of her through cloth until she came quiet enough that Isolde’s stones could not file the sound. The fantasy was plot, not garnish—it decided how much truth she could speak while aching. Blue-bruise memory from the yards braided with want. Calderyn’s thinning wards somehow made her hungrier for the man who taught survival without promising salvation. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence. Hope and dread shared her cunt the way they shared Ashmere’s thresholds.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.

[player_name]’s nipples stayed tight under damp fabric. Every shift of cloth reminded her that Isolde’s politics and Thorne’s leftover song had both woken something filthier than fear. Cassian’s gaze kept dropping to her mouth like a man memorizing fracture lines on a body instead of a ward. When he spoke low, she felt the words between her legs—handler voice, battlemage voice, the voice of someone who had almost followed Thorne and now poured that almost into wanting her alive and wanting her, period. Sex was not violence cosplay. War magic could be brutal. What she wanted from Cassian was consent loud enough to drown Collegium ink and still leave the living-key map unfinished on purpose.

She imagined his mouth on her charm, on her breasts, on the wet seam of her through cloth until she came quiet enough that Isolde’s stones could not file the sound. The fantasy was plot, not garnish—it decided how much truth she could speak while aching. Blue-bruise memory from the yards braided with want. Calderyn’s thinning wards somehow made her hungrier for the man who taught survival without promising salvation. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence. Hope and dread shared her cunt the way they shared Ashmere’s thresholds.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.

[player_name]’s nipples stayed tight under damp fabric. Every shift of cloth reminded her that Isolde’s politics and Thorne’s leftover song had both woken something filthier than fear. Cassian’s gaze kept dropping to her mouth like a man memorizing fracture lines on a body instead of a ward. When he spoke low, she felt the words between her legs—handler voice, battlemage voice, the voice of someone who had almost followed Thorne and now poured that almost into wanting her alive and wanting her, period. Sex was not violence cosplay. War magic could be brutal. What she wanted from Cassian was consent loud enough to drown Collegium ink and still leave the living-key map unfinished on purpose.`,
  choices: [
    { id: "scene7m", text: "Raid: hold/don’t-hold the ward-line (non-gore; c", textHot: "Raid: hit the ward-line — hold or release while your pulse owns his" },
    { id: "scene7n", text: "Inquiry: Cassian under review for closeness to c", textHot: "Inquiry: walk him into review — keep closeness honest under Collegium eyes" }
  ]
};
