export default {
  id: "scene6n",
  layer: 6,
  title: "Badge number: internal inquiry shadow on Cassian",
  text: `The badge number arrived like a bruise that had been waiting for language.

Archivist Bram Kestrel laid the half-charred impression beside a Collegium registry slate in the supervised shelf-room that smelled of old parchment and ozone. Salt wind worried the high vents. Copper bells above Ashmere kept wrong time. Cassian Rook stood very still—scorched leather, sealed past, mid-thirties mouth gone blade-flat—while [player_name]’s cracked charm ticked against her throat as if it recognized the stamped digits the way the cliff had recognized Thorne’s frequency on trial night.

“Maris half-heard it in Thorne’s last night,” Bram said carefully. “Ash-forensics filled the rest. The number belongs to a badge issued under Handler Rook’s old paired unit—years ago, border rotation, sealed inquiry adjacent. It does not prove Cassian wrote inland to a prefect. It proves someone wanted the trail to look like him. Or it proves the file the Collegium buried still has teeth.”

Isolde Vane would love either reading. Prefects already smelled blood. Internal inquiry shadow thickened from rumor into schedule: Cassian under review for closeness to a Warden-candidate whose song matched a Dark Sovereign’s leftover music. Living-key language still contested. Sacrifice map still unfinished. Unmade still pressing. Hope and dread sharing the registry slate.

Cassian did not deny the unit. He did not open his sealed drawer. “I know that number,” he said softly. “I know the village attached to the push that ate civilians. I know Vesper blamed dogma and left while I stayed and learned to smile for burial. What I do not know is who pressed that stamp into wax beside Thorne’s sigil last week—unless the Collegium’s own ghosts are writing letters again.”

[player_name] tasted copper. “If we walk into review, they will ask how often your glove finds my pulse. They will dress want as compromised judgment. If I go public—candidate statement, assembly hearing, my song as shield—they may flinch from burning you while the bells are watching. Either path costs. Neither finishes whether Thorne is monster or revolutionary. Neither names me lineage clean.”

Bram’s eyes were kind and terrified. “Ambiguity is not a luxury tonight. It is a life-support system. Do not let Isolde finish your sentences.”

Cassian’s glance found [player_name]—brutal charm sanded to asking. “I’m under shadow either way. I’d rather face review with you beside me than watch you spend yourself in politics Isolde invented. But if public is the shield that keeps my hands free for the ward-line, I will hate it and accept it. Your call. Romance is not the inquiry’s business. Surviving long enough to choose each other is.”

Practice-yard blue glowed in memory. Veil Sea fog climbed. Calderyn’s farmlands failed inland. Maris’s fear walked halls. Mid-want hummed under duty—unfinished, insistent, locked to Cassian alone. The hinge sharpened: walk into closeness review together—or go public to protect him, song spent as shield while Ashmere’s rain-dark towers kept score.

Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.

Ashmere Collegium held its breath the way cliff stone held salt: slowly, permanently, with a patience that punished anyone who mistook endurance for kindness. Calderyn beyond the fog was not a map problem alone; it was failing farmlands, aurora-glass markets dimming, border villages that heard Unmade whispers first. Living-key rumors remained contested on purpose. Bram’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure had a smell: spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge.

Practice yards below still carried blue-bruise afterglow; chalk circles smeared by rain waited for the next braid; copper bells scored every almost-confession happening above the waterline. Maris Quill’s fear still walked the dining halls. Ambiguity locked itself again: no confirmation [player_name] was lineage; no clean monster-label for Thorne; no opened drawer; only salt, bells, Cassian’s unfinished mouth, and choice sharpening consequence-verbs in the cliff wind. The Collegium did not gift mercy. The Unmade did not pause for romance. [player_name] carried both truths beside the cracked charm’s tick and the scorched-leather nearness of a handler who refused to let her become ink.

Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.

Ashmere Collegium held its breath the way cliff stone held salt: slowly, permanently, with a patience that punished anyone who mistook endurance for kindness. Calderyn beyond the fog was not a map problem alone; it was failing farmlands, aurora-glass markets dimming, border villages that heard Unmade whispers first. Living-key rumors remained contested on purpose. Bram’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure had a smell: spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge.

Practice yards below still carried blue-bruise afterglow; chalk circles smeared by rain waited for the next braid; copper bells scored every almost-confession happening above the waterline. Maris Quill’s fear still walked the dining halls. Ambiguity locked itself again: no confirmation [player_name] was lineage; no clean monster-label for Thorne; no opened drawer; only salt, bells, Cassian’s unfinished mouth, and choice sharpening consequence-verbs in the cliff wind. The Collegium did not gift mercy. The Unmade did not pause for romance. [player_name] carried both truths beside the cracked charm’s tick and the scorched-leather nearness of a handler who refused to let her become ink.

Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.

Ashmere Collegium held its breath the way cliff stone held salt: slowly, permanently, with a patience that punished anyone who mistook endurance for kindness. Calderyn beyond the fog was not a map problem alone; it was failing farmlands, aurora-glass markets dimming, border villages that heard Unmade whispers first. Living-key rumors remained contested on purpose. Bram’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure had a smell: spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge.

Practice yards below still carried blue-bruise afterglow; chalk circles smeared by rain waited for the next braid; copper bells scored every almost-confession happening above the waterline. Maris Quill’s fear still walked the dining halls. Ambiguity locked itself again: no confirmation [player_name] was lineage; no clean monster-label for Thorne; no opened drawer; only salt, bells, Cassian’s unfinished mouth, and choice sharpening consequence-verbs in the cliff wind. The Collegium did not gift mercy. The Unmade did not pause for romance. [player_name] carried both truths beside the cracked charm’s tick and the scorched-leather nearness of a handler who refused to let her become ink.

Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.`,
  textHot: `The badge number arrived like a bruise—and [player_name] felt it in her cunt as much as her throat. Bram’s supervised shelf-room. Parchment. Ozone. Salt wind. Copper bells wrong. Cassian Rook went blade-still while digits that looked like his old unit sat beside Thorne’s wax ghost. Her cracked charm ticked between her breasts. Nipples tight. Inquiry shadow meant closeness named as crime—and closeness was exactly what made her slick whenever his glove found her pulse.

“Someone wants the trail to look like me,” Cassian said softly. “Or the buried file still has teeth.” Sealed past. Nearly-following-Thorne. Brutal charm sanded to danger. [player_name] wanted to put her mouth on his throat until the Collegium forgot how to bill him.

Review would ask how often he touched her. Public would spend her song as shield. Living-key fog contested. Sacrifice unfinished. Unmade pressing. Romance lock Cassian only—Thorne temptation without lover’s claim. Mid-want made politics feel like foreplay with knives.

She stepped into Cassian’s space until scorched leather warmed her breasts through cloth. “If we face review, I want them to see my pulse under your glove on purpose. If I go public, I want you hard and furious in the wings while I spend myself protecting you—then I want you to collect afterward where Isolde’s ink can’t reach.”

Cassian’s breath punched out. His forehead tipped to hers. “You can’t say collect in a shelf-room and expect me polite.” His gloved thumb stroked her charm once—spark straight to her clit. “Inquiry beside me—or public shield. Either way you’re not Isolde’s key. Either way I’ll be aching through the hearing.”

He did not fuck her against Bram’s shelves. Mid-want held. Hope and dread shared her body. The hinge waited wet under Ashmere’s bells: face his review as vow—or go public, song as shield, want unfinished on purpose.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.

[player_name]’s nipples stayed tight under damp fabric. Every shift of cloth reminded her that Isolde’s politics and Thorne’s leftover song had both woken something filthier than fear. Cassian’s gaze kept dropping to her mouth like a man memorizing fracture lines on a body instead of a ward. When he spoke low, she felt the words between her legs—handler voice, battlemage voice, the voice of someone who had almost followed Thorne and now poured that almost into wanting her alive and wanting her, period. Sex was not violence cosplay. War magic could be brutal. What she wanted from Cassian was consent loud enough to drown Collegium ink and still leave the living-key map unfinished on purpose.

She imagined his mouth on her charm, on her breasts, on the wet seam of her through cloth until she came quiet enough that Isolde’s stones could not file the sound. The fantasy was plot, not garnish—it decided how much truth she could speak while aching. Blue-bruise memory from the yards braided with want. Calderyn’s thinning wards somehow made her hungrier for the man who taught survival without promising salvation. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence. Hope and dread shared her cunt the way they shared Ashmere’s thresholds.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.

[player_name]’s nipples stayed tight under damp fabric. Every shift of cloth reminded her that Isolde’s politics and Thorne’s leftover song had both woken something filthier than fear. Cassian’s gaze kept dropping to her mouth like a man memorizing fracture lines on a body instead of a ward. When he spoke low, she felt the words between her legs—handler voice, battlemage voice, the voice of someone who had almost followed Thorne and now poured that almost into wanting her alive and wanting her, period. Sex was not violence cosplay. War magic could be brutal. What she wanted from Cassian was consent loud enough to drown Collegium ink and still leave the living-key map unfinished on purpose.

She imagined his mouth on her charm, on her breasts, on the wet seam of her through cloth until she came quiet enough that Isolde’s stones could not file the sound. The fantasy was plot, not garnish—it decided how much truth she could speak while aching. Blue-bruise memory from the yards braided with want. Calderyn’s thinning wards somehow made her hungrier for the man who taught survival without promising salvation. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence. Hope and dread shared her cunt the way they shared Ashmere’s thresholds.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.

[player_name]’s nipples stayed tight under damp fabric. Every shift of cloth reminded her that Isolde’s politics and Thorne’s leftover song had both woken something filthier than fear. Cassian’s gaze kept dropping to her mouth like a man memorizing fracture lines on a body instead of a ward. When he spoke low, she felt the words between her legs—handler voice, battlemage voice, the voice of someone who had almost followed Thorne and now poured that almost into wanting her alive and wanting her, period. Sex was not violence cosplay. War magic could be brutal. What she wanted from Cassian was consent loud enough to drown Collegium ink and still leave the living-key map unfinished on purpose.

She imagined his mouth on her charm, on her breasts, on the wet seam of her through cloth until she came quiet enough that Isolde’s stones could not file the sound. The fantasy was plot, not garnish—it decided how much truth she could speak while aching. Blue-bruise memory from the yards braided with want. Calderyn’s thinning wards somehow made her hungrier for the man who taught survival without promising salvation. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence. Hope and dread shared her cunt the way they shared Ashmere’s thresholds.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.

[player_name]’s nipples stayed tight under damp fabric. Every shift of cloth reminded her that Isolde’s politics and Thorne’s leftover song had both woken something filthier than fear. Cassian’s gaze kept dropping to her mouth like a man memorizing fracture lines on a body instead of a ward. When he spoke low, she felt the words between her legs—handler voice, battlemage voice, the voice of someone who had almost followed Thorne and now poured that almost into wanting her alive and wanting her, period. Sex was not violence cosplay. War magic could be brutal. What she wanted from Cassian was consent loud enough to drown Collegium ink and still leave the living-key map unfinished on purpose.

She imagined his mouth on her charm, on her breasts, on the wet seam of her through cloth until she came quiet enough that Isolde’s stones could not file the sound. The fantasy was plot, not garnish—it decided how much truth she could speak while aching. Blue-bruise memory from the yards braided with want. Calderyn’s thinning wards somehow made her hungrier for the man who taught survival without promising salvation. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence. Hope and dread shared her cunt the way they shared Ashmere’s thresholds.`,
  choices: [
    { id: "scene7n", text: "Inquiry: Cassian under review for closeness to c", textHot: "Inquiry: face his review beside him — let closeness be evidence and vow" },
    { id: "scene7o", text: "Politics: she goes public to protect Cassian", textHot: "Politics: go public for him — spend your song as shield" }
  ]
};
