export default {
  id: "scene5h",
  layer: 5,
  title: "Partial hymn — she brings Cassian to Isolde’s door; dread/hope unresolved",
  text: `[player_name] brought Cassian Rook to Isolde Vane’s door with Bram’s partial hymn between them like a third pulse. Dread and hope unresolved. Salt wind in the corridor. Copper bells wrong above. Scorched leather at her back—handler, battlemage, mid-thirties, sealed past teeth, brutal charm sanded to readiness. His breath stirred her hair as she raised her hand to knock.

“Whatever she confesses,” Cassian murmured, “I’m not leaving you in that room as her key.” His fingers brushed the base of her spine—proprietary spark, asking not claiming.

The door opened on Isolde’s ashwood patience and the brass dual-consent key still catching lamp light. [player_name] laid the fragment down: living keys can be refused; cost clause missing; full sacrifice map absent; Unmade still contested; Thorne still unfinished as monster or revolutionary—temptation without second LI.

“You bring your handler like a shield,” Isolde said.

“I bring him like a witness,” [player_name] answered. “Refusal is in the hymn. Seal language stays unmarked. Bell-tower lead waits in the fog—copper evidence or rumor. We can walk it alone or with Collegium eyes. First we hear whether you’ll treat refusal as weather or as mutiny.”

Isolde’s gaze flicked to Cassian—invoice for theatrical mercy remembered—and back. “Access remains while you hunt. If Rook moves to relieve political pressure at this door, I will remember the theater. If you walk the tower alone and find blood-rust and charm-twins, I will remember the solitude. Choose which story you want the stones to keep.”

Cassian’s glove found [player_name]’s wrist in plain sight—signal, heat. Mid-want hummed under duty. Living-key ambiguity locked. Hope and dread shared the threshold. The hinge: bell-tower lead alone into copper blood-rust—or stay and watch Cassian move to relieve her while Isolde’s politics tried to swallow them both.

Ashmere Collegium held its breath the way cliff stone held salt: slowly, permanently, with a patience that punished anyone who mistook endurance for kindness. [player_name] felt that patience in her molars whenever copper bells missed their true intervals and the cracked charm at her throat answered with a tick that was almost a word. Practice yards below still carried blue-bruise afterglow; ozone from failed braids clung to rain-damp wool; Veil Sea fog climbed the stairs as if curious about every almost-confession happening above the waterline.

Calderyn beyond the fog was not a map problem alone; it was failing farmlands, aurora-glass markets dimming, border villages that heard Unmade whispers first and sent fewer letters home. Every Collegium choice eventually became inland weather. [player_name] carried that knowledge beside mid-want and duty, inseparable, while Cassian Rook’s scorched-leather nearness made survival feel like something her body could negotiate with instead of only obey.

Living-key rumors remained contested on purpose. Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne out of the wards after a border push went wrong. Thorne himself stayed unfinished: warm wine over broken glass, monster and revolutionary braided until late layers forced a cut—temptation allowed, romance lock unbroken, Cassian only.

Trust under apocalypse pressure had a smell: spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge. The next verb would cost access, innocence, or the last clean line between handler and hunger—and living-key truth would still not be finished when the bells changed watch over Ashmere’s rain-dark towers. Maris Quill’s fear still walked the dining halls. Ambiguity locked itself again: no confirmation [player_name] was lineage; no clean monster-label for Thorne; no opened drawer; only salt, bells, Cassian’s unfinished mouth, and choice sharpening consequence-verbs in the cliff wind.


Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.


Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.


Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.


Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.


Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.


Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.


Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.


Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.
`,
  textHot: `[player_name] brought Cassian to Isolde’s door with the partial hymn and a body still humming from cliff almosts. His breath in her hair. Fingers at the base of her spine sparking straight to her clit. “Not leaving you as her key,” he murmured, and she wanted to turn and finish the refused kiss against the Headmistress’s threshold like blasphemy.

Inside: ashwood, brass key, Isolde’s thin smile. [player_name] spoke refusal, missing cost, contested Unmade, Thorne unfinished—temptation not lover—while Cassian’s heat at her back made every theological word feel like foreplay she refused to gift Isolde.

“Shield or witness?” Isolde asked.

“Witness,” [player_name] said, voice rough with mid-want.

Cassian’s glove on her wrist in plain sight—pulse owned—shock filthy and public. Isolde noticed. Access dangled. Tower lead offered as solitude or partnership theater. [player_name]’s nipples tight under her shirt; cunt aching empty; charm ticking. Romance lock Cassian only. Living-key fog. The hinge wet and unresolved: walk the bell-tower alone into copper rust and charm-twins—or watch him move to relieve her at this door while hope and dread shared her body like a second hymn.

[player_name]’s cunt ached with unfinished promises; every shift of cloth reminded her that Isolde’s politics and Thorne’s leftover song had both woken something filthier than fear. Her nipples stayed tight under damp fabric. Cassian’s gaze kept dropping to her mouth like a man memorizing fracture lines on a body instead of a ward. When he spoke low, she felt the words between her legs—handler voice, battlemage voice, the voice of someone who had almost followed Thorne and now poured that almost into wanting her alive and wanting her, period.

His glove on her pulse was a filthy soft argument: not claiming as key, claiming as the man who would drag her out of silver thread even if it meant putting his hands on her in front of Collegium stone. [player_name] wanted those hands lower. Mid-want made waiting feel like edged climax denied. She went slicker for honesty than for any clean romance script, thighs pressed tight, charm ticking between her breasts like a second clit answering scorched leather and blade oil.

Thorne’s frequency in the stone stroked her ribs and made her empty flutter as if song could find her clit; she refused to confuse that wrong music with Cassian’s heat. One was temptation without romance lock. The other was a cock restrained by duty and the sheer terror of repeating an old push. Sex was not violence cosplay. War magic could be brutal. What she wanted from Cassian was consent loud enough to drown Isolde’s ink and still leave the living-key map unfinished on purpose.

She imagined his mouth on her charm, on her breasts, on the wet seam of her through cloth until she came quiet enough that Isolde’s stones could not file the sound. The fantasy was plot, not garnish—it decided how much truth she could speak while aching. Blue-bruise memory from the yards braided with want. Calderyn’s thinning wards somehow made her hungrier for the man who taught survival without promising salvation. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence. Hope and dread shared her cunt the way they shared Ashmere’s thresholds. Living-key ambiguity still contested; Thorne’s frequency still a rumor in her blood; Cassian’s sealed past still teeth behind one drawer—mystery as friction, danger as heat. Ashmere’s cliff held them above a hungry sea while [player_name] kept her heat like a ward-braid under tension—alive, unfinished, refusing tidy endings.


Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.


Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.


Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.


Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.


Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.


Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.


Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.


Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.


Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.
`,
  choices: [
    { id: "scene6h", text: "Bell-tower lead alone — she finds copper blood-rust and a cracked charm twin", textHot: "Bell-tower alone — carry the ache into copper rust without his hands on you" },
    { id: "scene6i", text: "Isolde door: Cassian moves to relieve her; she watches", textHot: "Stay and watch him relieve Isolde — pulse still owned by his glove" }
  ]
};
