export default {
  id: "scene7l",
  layer: 7,
  title: "Break-open: she and Cassian choose each other mid-war",
  text: `Cassian Rook’s quarters after the obstruction fight still held the argument in the air—practice-blade oil on the table, scorched leather gloves discarded, salt wind worrying shutters above the Veil Sea cliff. Copper bells outside kept a thin wrong watch. [player_name]’s cracked charm ticked hard enough to feel like a dare. He had asked why she tipped Maris. She had answered with fear and love braided wrong. Now the fight had nowhere left to go except break-up or break-open, and the war outside did not care which verb they chose.

“I’m done pretending handler distance keeps you alive,” Cassian said, not shouting. Mid-thirties exhaustion made quiet dangerous. “I’m done pretending wanting you is a Collegium invoice I can pay later. Choose me mid-war or walk. I will not chase you with leash language. I will not open my sealed drawer just because your mouth asks pretty. I will stand here as a man who nearly followed Thorne once and stayed—and I will ask if you can love that without making me Isolde’s tool.”

[player_name] stood with her back to the sealed ashwood drawer. Living-key fog still contested. Bram’s hymns unfinished. Isolde’s patience billing interest upstairs. Maris’s fear walking halls. Thorne unfinished as monster or revolutionary—temptation without second LI. Romance lock on Cassian alone. Hope and dread shared the room.

“I choose you,” she said, and the words tasted of copper and salt. “Not as key. Not as martyr. As the woman who tips friends and burns hours and still wants your teaching and your mouth. Mid-war. Mid-want. If that’s obstruction, bill me.”

Cassian’s brutal charm broke into something almost tender and more dangerous for it. He crossed the space. Gloved hands—then gloves off, bare palms at her jaw, consent loud in the pause before his forehead tipped to hers. “Then we break open. Not break up. Prefects’ chains still wait. Raids still wait. Inquiry still smells your closeness like evidence. None of that gets to unmake this sentence.”

They did not finish the war in that room. They finished the lie that duty required loneliness. Mid-want hummed: mouths almost, bodies almost, trust earning inches while Unmade pressed the cliff and Calderyn thinned inland. Blue-bruise memory from yards. Ozone. Chalk. Charm ticking between them like a third pulse.

Cassian kissed the corner of her mouth—unfinished on purpose—and rested his brow against hers. “Next hinge. Quiet deal on the prefect chain while we protect what we just chose—or raid the ward-line and find out whether choosing each other survives consequence that isn’t ink.”

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while they chose each other mid-war and the next verb waited between quiet deal and raid.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while they chose each other mid-war and the next verb waited between quiet deal and raid.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while they chose each other mid-war and the next verb waited between quiet deal and raid.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while they chose each other mid-war and the next verb waited between quiet deal and raid.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while they chose each other mid-war and the next verb waited between quiet deal and raid.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while they chose each other mid-war and the next verb waited between quiet deal and raid.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while they chose each other mid-war and the next verb waited between quiet deal and raid.

Ashmere held its breath the way cliff stone held salt: slowly, permanently, punishing anyone who mistook endurance for kindness. Copper bells missed another interval. [player_name]’s cracked charm ticked. Cassian Rook’s scorched leather and practice-blade oil stayed near without smothering. Inland, Calderyn’s farmlands failed in quiet increments; aurora-glass markets dimmed; border villages heard Unmade whispers first. Living-key rumors remained contested on purpose—Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne. Trust under apocalypse pressure smelled like spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge while they chose each other mid-war and the next verb waited between quiet deal and raid.`,
  textHot: `[player_name] chose him with her mouth first—not soft professor fantasy, Cassian Rook mid-thirties scarred and sleep-deprived, brutal charm sanded to want. Practice-blade oil. Scorched leather discarded. Salt wind. Copper bells wrong. Her cracked charm trapped between their chests as his bare hands framed her jaw and she went instantly, shamelessly wet.

“I choose you,” she said against his mouth. “Mid-war. Fuck the invoice.”

He groaned like a man billed past endurance. Kissed her proper—deep, controlled, filthy with restraint—thigh slotting between hers until her cunt rode the hard seam of his leg through cloth and she gasped copper. Not fucking yet. Break-open as vow and almost. His cock thick against her hip, restrained by duty and the terror of repeating an old border push. Consent loud: he paused, eyes asking; she nodded, hips answering.

“Say stop and I stop,” he murmured.

“Don’t stop choosing me,” [player_name] breathed. “Stop before we finish if the raid alarm sounds. Don’t stop the sentence.”

His hand slid under wool—palm hot on her waist, then lower, fingers finding slick evidence of how hard politics and fear had edged her all week. She clenched around nothing, then around his fingers as he stroked her clit with ruthless tenderness, forehead to hers, living-key fog still contested while he made her person-shaped with pleasure. She came quiet against his hand, biting his shoulder, charm burning. He did not take his own release—mid-want lock, cock still hard, vow unfinished on purpose.

“Next verb,” he said roughly, mouth at her ear. “Quiet deal—protect this, bargain prefect ash, then I put you on that table and finish what my fingers started. Or raid the ward-line—hold or don’t—and keep your pulse on mine while consequence writes itself in weather instead of ink.”

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while break-open still hummed in her cunt and choice waited between quiet deal and ward-line raid. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs and the Unmade pressed like weather that had learned her name.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while break-open still hummed in her cunt and choice waited between quiet deal and ward-line raid. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs and the Unmade pressed like weather that had learned her name.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while break-open still hummed in her cunt and choice waited between quiet deal and ward-line raid. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs and the Unmade pressed like weather that had learned her name.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while break-open still hummed in her cunt and choice waited between quiet deal and ward-line raid. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs and the Unmade pressed like weather that had learned her name.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while break-open still hummed in her cunt and choice waited between quiet deal and ward-line raid. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs and the Unmade pressed like weather that had learned her name.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while break-open still hummed in her cunt and choice waited between quiet deal and ward-line raid. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs and the Unmade pressed like weather that had learned her name.

Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb. “Keep that filth for the choice,” he said roughly, eyes dropping to her mouth, then to the charm, then lower for one unprofessional heartbeat. Consent stayed loud in the negative space. Sex was not violence cosplay. War magic could be brutal elsewhere. Living-key ambiguity still contested; Thorne’s frequency still rumor; sealed past still teeth behind one drawer—mystery as friction, danger as heat. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence while break-open still hummed in her cunt and choice waited between quiet deal and ward-line raid. Copper bells scored how stupid and necessary wanting him remained under war pressure as Veil Sea fog climbed the cliff stairs and the Unmade pressed like weather that had learned her name.`,
  choices: [
    { id: "scene8l", text: "Prefects’ chain: quiet deal", textHot: "Prefects’ chain: quiet deal — bargain ash then finish what his fingers started" },
    { id: "scene8m", text: "Raid aftermath: Cassian wounded lightly / hospital vs chase", textHot: "Raid aftermath: Cassian wounded lightly — hospital heat or chase with blood-taste want" }
  ]
};
