export default {
  id: "scene8b",
  layer: 8,
  title: "Ledger private: bargain with Isolde",
  text: `Isolde Vane’s ashwood office smelled of salt-cured ledgers and cooled copper bowls. Salt wind fretted the leaded glass. Ozone from a night of failed practice braids still clung to the curtains. Outside, Veil Sea fog climbed the cliff stairs of Ashmere Collegium; inland, Calderyn’s farmlands failed where outer wards thinned; every honest mouth still called the Unmade contested. [player_name] sat across from the Headmistress with the untitled ledger closed between them like a blade sheathed in private ink, and Cassian Rook stood at her left shoulder—scorched leather, practice-blade oil, mid-thirties sleep carved into brutal charm that refused to look like mentorship fluff.

“Ledger private,” Isolde said, copper-voiced. “You chose bargain over assembly theater. Wise. Or cowardly. We will discover which.” She did not open the genealogy blank. She tapped it once, as if the living-key chain could hear through wood. “Your song recognizes the singers. It does not confirm your name. Ambiguity remains. I will sell you maps, Bram’s supervised shelves, and a seal that keeps your frequency off the loudest tongues—if you give me leverage I can invoice.”

Cassian’s glove flexed. “Leverage that smells like a seal on her throat gets stopped. Partnership, Isolde. Not harvest. She bargains as a person.”

Isolde’s smile thinned to salt-air parchment. “Your theatrical mercy already has interest, Rook.” She looked at [player_name]’s cracked ward-charm as if it were a signature waiting to be claimed. “Mercy rewrite of the sacrifice language—soft darkness dressed as kindness—or quiet deal that seals parts of the living-key file where daylight cannot sand them soft. Both cost. Both keep Calderyn breathing a little longer. Neither finishes the Unmade into a tidy map. Neither settles whether Lord Vesper Thorne is monster, revolutionary, or both.”

Thorne’s name arrived like warm wine over broken glass and left without earning romance. Temptation-shaped weather only. The romance lock stayed on Cassian’s pulse-warm glove and the sealed drawer in his quarters he still would not open for her—twin tooth to Isolde’s ashwood hunger.

[player_name] tasted copper from an earlier pin-cut and refused to translate it as doom. Recognition settled—map, not surrender. Maris Quill’s dining-hall fear walked the room without a body. Archivist Bram Kestrel’s half-translated hymns sharpened in the walls. Living-key sacrifice stayed a shape without clean edges; private bargain earned access and teeth, not a finished martyrdom script.

“Mercy rewrite means you walk into binding with language that refuses to burn candidates quiet when their song runs wrong,” Isolde continued, almost tender. “Quiet deal means parts of this file stay dark on purpose—your frequency included—while we hold what we can of Calderyn’s thinning song. Choose the kind of darkness you can ethically carry.”

Cassian’s murmur found [player_name]’s temple. “Mercy rewrite keeps a corridor for shared cost later. Quiet deal keeps Isolde’s seals as sheath. Neither is soft. Pick the danger you can survive with your mouth still yours.”

Salt wind rattled the glass. Copper bells far above tasted the air for fracture. Practice yards beyond fog glowed faint bruise-blue in [player_name]’s memory. She catalogued the private room: location—Isolde’s ashwood, ledger closed, bowls cooled; intensity—charm ticking like a second heart; ask—mercy rewrite of sacrifice language, or quiet seal on parts of the living-key file.

Mid-want from unfinished corridors hummed under duty. Trust under apocalypse pressure sharpened. Cassian Rook—almost-follower of Thorne once, interrupter of seals now—waited like a man who would bill Isolde for tone and bill himself for wanting. [player_name] held the hinge with eyes open.

She thought of dual-consent bowls that had almost sealed her throat mid-reading, of Cassian’s refusal to let naming become harvest, of civilians eaten by an early breach he would not yet narrate in full. Secrets planted early. Payoffs late. Private ink earned maps and seals. It did not earn a complete sacrifice map. She held that line.

“I’ll bargain,” she said. “With him in the room. With my throat still answering to my name first. Mercy rewrite if the language can refuse quieted as a Collegium verb—or quiet deal if sealing parts of this file keeps me a person longer than Isolde’s loudest mercy.” Isolde filed the sentence like interest. Cassian’s heat along her shoulder translated bargain into partnership with teeth.

Bram’s shelves muttered behind supervised locks somewhere below. Maris’s friend-fear pressed the door from a corridor away. Thorne’s mark remembered bloom on the cliff without being invited into the romance. The Unmade pressed every honest map. Hope and dread shared the ashwood doorway.

Cassian’s thumb brushed her wrist—brief, deliberate. “Whatever you pick, I stay where her ink can see my hands on your pulse—not claiming key. Claiming person.” Isolde heard that. She did not pretend she hadn’t. “Then decide before the bowls invent a colder patience, candidate.”

[player_name] flexed copper-stained skin on her thumb. Recognition again—map, not surrender. She refused to invent belonging where the genealogy blank stopped. She refused to pretend fog was failure. Mercy rewrite or quiet deal: both doors remembered ambiguity; neither wrote her name for her; both kept Cassian Rook inside the story.

Outside, ward-bells changed watch. Fog climbed. Calderyn thinned by inches. [player_name] sat between Isolde’s invoice and Cassian’s interruption reflex with living-key truth still contested, sacrifice still fogged, Thorne still unfinished outside the romance lock, and the next verb waiting like weather with teeth. Mid-want unfinished. Consequence first. Person first. Key never only.

Salt wind kept score on the glass. Ozone clung like breath after a denied kiss. Copper bells tasted the air for fracture and found enough to keep their tongues restless. Calderyn thinned by inches beyond Veil Sea fog. The Unmade pressed every honest map without offering tidy martyrdom. Cassian Rook’s scorched leather stayed in the room like a vow that refused Collegium ink. Living-key sacrifice stayed a shape without clean edges unless this hinge had already earned its partial. Thorne remained temptation-shaped rumor—warm wine over broken glass—never a second LI while romance locked on Cassian. Mid-want hummed unfinished under duty. Hope and dread shared the doorway. Eyes open. Person first. Key never only. The hinge asked again, sharper by 674 breaths of unfinished wanting.

Salt wind kept score on the glass. Ozone clung like breath after a denied kiss. Copper bells tasted the air for fracture and found enough to keep their tongues restless. Calderyn thinned by inches beyond Veil Sea fog. The Unmade pressed every honest map without offering tidy martyrdom. Cassian Rook’s scorched leather stayed in the room like a vow that refused Collegium ink. Living-key sacrifice stayed a shape without clean edges unless this hinge had already earned its partial. Thorne remained temptation-shaped rumor—warm wine over broken glass—never a second LI while romance locked on Cassian. Mid-want hummed unfinished under duty. Hope and dread shared the doorway. Eyes open. Person first. Key never only. The hinge asked again, sharper by 550 breaths of unfinished wanting.

Salt wind kept score on the glass. Ozone clung like breath after a denied kiss. Copper bells tasted the air for fracture and found enough to keep their tongues restless. Calderyn thinned by inches beyond Veil Sea fog. The Unmade pressed every honest map without offering tidy martyrdom. Cassian Rook’s scorched leather stayed in the room like a vow that refused Collegium ink. Living-key sacrifice stayed a shape without clean edges unless this hinge had already earned its partial. Thorne remained temptation-shaped rumor—warm wine over broken glass—never a second LI while romance locked on Cassian. Mid-want hummed unfinished under duty. Hope and dread shared the doorway. Eyes open. Person first. Key never only. The hinge asked again, sharper by 426 breaths of unfinished wanting.

Salt wind kept score on the glass. Ozone clung like breath after a denied kiss. Copper bells tasted the air for fracture and found enough to keep their tongues restless. Calderyn thinned by inches beyond Veil Sea fog. The Unmade pressed every honest map without offering tidy martyrdom. Cassian Rook’s scorched leather stayed in the room like a vow that refused Collegium ink. Living-key sacrifice stayed a shape without clean edges unless this hinge had already earned its partial. Thorne remained temptation-shaped rumor—warm wine over broken glass—never a second LI while romance locked on Cassian. Mid-want hummed unfinished under duty. Hope and dread shared the doorway. Eyes open. Person first. Key never only. The hinge asked again, sharper by 302 breaths of unfinished wanting.

Salt wind kept score on the glass. Ozone clung like breath after a denied kiss. Copper bells tasted the air for fracture and found enough to keep their tongues restless. Calderyn thinned by inches beyond Veil Sea fog. The Unmade pressed every honest map without offering tidy martyrdom. Cassian Rook’s scorched leather stayed in the room like a vow that refused Collegium ink. Living-key sacrifice stayed a shape without clean edges unless this hinge had already earned its partial. Thorne remained temptation-shaped rumor—warm wine over broken glass—never a second LI while romance locked on Cassian. Mid-want hummed unfinished under duty. Hope and dread shared the doorway. Eyes open. Person first. Key never only. The hinge asked again, sharper by 178 breaths of unfinished wanting.

Salt wind kept score on the glass. Ozone clung like breath after a denied kiss. Copper bells tasted the air for fracture and found enough to keep their tongues restless. Calderyn thinned by inches beyond Veil Sea fog. The Unmade pressed every honest map without offering tidy martyrdom. Cassian Rook’s scorched leather stayed in the room like a vow that refused Collegium ink. Living-key sacrifice stayed a shape without clean edges unless this hinge had already earned its partial. Thorne remained temptation-shaped rumor—warm wine over broken glass—never a second LI while romance locked on Cassian. Mid-want hummed unfinished under duty. Hope and dread shared the doorway. Eyes open. Person first. Key never only. The hinge asked again, sharper by 54 breaths of unfinished wanting.`,
  textHot: `Isolde’s ashwood office felt like a mouth that had learned to undress with paperwork. Black wood. Salt wind at the glass. Ozone on the curtains like breath after a kiss denied. Cooled copper bowls. Closed ledger. [player_name]’s cracked charm answered between her breasts with private heat that tightened her nipples before Isolde finished saying bargain. Cassian Rook took the space at her shoulder close enough that his body heat ran down her spine like a filthy promise he refused to cash in front of the Headmistress. Scorched leather. Blade-oil. Sleep-deprived mouth that had left her wet and unfinished in corridors. Mid-want was the slick fact she carried into private ink.

“Mercy rewrite or quiet deal,” Isolde said, and the words stroked [player_name]’s sternum like a finger that had no right. “Both cost. Both keep Calderyn breathing. Neither finishes the Unmade tidy. Neither settles Thorne.”

Cassian’s voice was soft absolute at [player_name]’s ear. “She bargains as a person. If it smells like a seal, we stop.” His breath hit the hinge of her jaw. [player_name]’s cunt clenched around nothing. Isolde watched their mouths as if heat were evidence. It was.

[player_name] wanted to drag Cassian’s glove under the desk and show Isolde what frequency her body answered when stone sang wrong. She wanted to come with bargain Latin still in her mouth and then decide which darkness she could ethically carry. She wanted his thumb on her clit while dual-consent bowls cooled unused. She sat still. Private meant letting Isolde’s supervised hunger taste her song while Cassian’s heat along her back made every seal-adjacent word feel like a hand between her thighs.

Cassian’s glove found her wrist under the table edge—thumb on pulse like a wire check and a claim. The shock went straight to her clit and lodged there, throbbing. “Mercy rewrite keeps a corridor,” he murmured. “Quiet deal keeps her seals as sheath. Neither is soft. Your cunt can tell the truth your mouth is about to invoice.”

She was wet enough to feel it when she shifted. Thorne stayed warm wine over broken glass—temptation not LI. Romance locked on the man whose refusal to let bargain become harvest was hotter than any clean seduction Isolde’s office had funded.

Mercy rewrite meant walking into softened sacrifice language wet and awake—consent as verb, fucking deferred until the rewrite had ethics she could carry with Cassian at her back. Quiet deal meant seals dark on purpose while his hand stayed on her pulse through Isolde’s ink—unfinished on purpose because mid-want endings mattered.

She catalogued shamelessly: location—clit, nipples, charm, wrist; intensity—knees negotiating ashwood chair; trigger—Cassian’s interruption reflex. She imagined him bending her over the closed ledger the second Isolde looked away—glove between her legs, bargain still in her mouth, orgasm as punctuation the Headmistress would never invoice. Not yet.

When Isolde tapped the genealogy blank, the sound went through [player_name] like a nail down her spine—not pain, want. Cassian mouthed later, almost soundless, and her cunt ached around the word like a vow. Nipples hard. Thighs pressed. Living-key fog. Romance lock unbroken.

She thought of his cock hard against her knee through scorched leather—honest, filthy, banked under the table—and of how denial on purpose was partnership with teeth. Risk translated into heat. Heat into data. Data said she still had a self Isolde could not quietly remade.

“Choose,” Isolde said, and [player_name]’s clit throbbed at the copper syllable. Salt. Ozone. Blade-oil patience. She held mercy-rewrite and quiet-deal slick and unresolved, sacrifice still fog, Unmade still pressing, and let private bargain ask which darkness she could survive—while Cassian Rook’s pulse counted against her wrist like an orgasm he refused to give her on ashwood furniture.

Outside, copper bells kept score over Veil Sea fog. Calderyn thinned. Thorne’s mark remembered bloom without romance. [player_name] sat wet and awake in Isolde’s confession with mid-want as physical fact, fucking deferred until mercy rewrite or quiet seal had a name she could ethically carry without going blank.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 895 more unfinished breaths and did not come.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 767 more unfinished breaths and did not come.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 639 more unfinished breaths and did not come.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 511 more unfinished breaths and did not come.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 383 more unfinished breaths and did not come.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 255 more unfinished breaths and did not come.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 127 more unfinished breaths and did not come.`,
  choices: [
    { id: "scene9b", text: "Binding path: submit with a mercy rewrite of the sacrifice", textHot: "Binding path: submit with a mercy rewrite — softened cost, his hands still yours" },
    { id: "scene9d", text: "Quiet deal: seal parts of the living-key file", textHot: "Quiet deal: seal parts of the living-key file while his mouth finds what daylight can’t" }
  ]
};
