export default {
  id: "scene8c",
  layer: 8,
  title: "Page truth: she reads it aloud to Cassian in bed",
  text: `Cassian Rook’s quarters smelled of practice-blade oil, scorched leather, and the particular patience of a man who had learned to sleep in pieces. Salt wind fretted the cliff-side window. Copper ward-bells far above tasted Ashmere’s air for fracture. On the floor: a ward-map still faintly chalked from an off-record night. On the nightstand: a cracked notebook, a Collegium badge facedown, and the withheld page—cream, salt-cured, living-key Latin that had survived fire only because [player_name] had chosen reading over burning.

She sat against the headboard in a shift that had forgotten how to be armor. Cassian sat half-propped beside her, mid-thirties, scarred, brutal charm banked soft for once without going soft. The cracked personal ward-charm at her throat ticked warm. Outside, Veil Sea fog climbed; inland, Calderyn thinned; the Unmade stayed contested on every honest map. Lord Vesper Thorne remained temptation-shaped rumor—warm wine over broken glass—never a second LI. Romance lock stayed here, in the unfinished almost of Cassian’s mouth and the page she was about to read aloud.

“Aloud,” she said. “So you hear what I hear. So neither of us invents belonging where the ink stops.”

Cassian’s grey-dark eyes—sleep-carved, blade-trained—held hers. “I hear. If it tries to finish you into a seal mid-sentence, we stop. Partnership. Not harvest.”

[player_name] read. The page did not write her name. It named a refusal grammar Bram had half-translated: living keys could be refused; sacrifice maps could be rewritten; Collegium verbs like quieted were choices wearing duty’s coat. It pointed at a second fracture pattern inland without finishing the war into tidy martyrdom. It hummed with frequency that answered her charm without owning her. Ambiguity remained. Useful. Dangerous. Earned partial without full payoff.

Her voice roughened on the Latin. Cassian’s hand found her wrist—pulse-lock, person-claim. Heat leapt. Mid-want from war-only streaks and unfinished briefings hummed under the sheets. Trust under apocalypse pressure had never felt so much like reading forbidden ink in a bed that smelled like him.

“Hospital dawn,” Cassian murmured when she finished, forehead nearly touching hers. “Means we braid soft rebuild into the case’s living throat—gauze light, machines inventing patience, us answering what the page refused to finish. Cliff dawn means leave-or-stay weather on the stairs where Thorne’s mark once bloomed, truth spoken where fog can erase or keep us. I walk either. I will not walk a third where we pretend reading aloud finished the wanting.”

[player_name] traced the cream edge once more. Living-key sacrifice still fogged at the edges. Unmade still pressing. Isolde’s invoice waiting somewhere in ashwood. Maris’s fear. Bram’s shelves. Cassian’s sealed drawer still closed across the room like a twin tooth. Secrets planted early. Payoffs late. This hinge earned page-truth into shared air. It did not earn a finished martyrdom map.

She catalogued: location—Cassian’s bed, page between them, fog at glass; intensity—charm ticking, pulse under his thumb; ask—hospital-dawn future or cliff-dawn leave-or-stay. Hope and dread shared the pillow.

She thought of Isolde pressing martyrdom-as-duty, of Cassian nearly following Thorne once, of civilians he would not yet narrate, of a smile learned like a blade. The page’s refusal grammar did not absolve the Collegium. It did not crown Thorne prophet. It gave [player_name] a corridor for choosing with eyes open.

“I’ll choose,” she whispered. “Hospital dawn if we braid soft rebuild into what’s still living—or cliff dawn if leave-or-stay is the cleaner weather. Either way you stay inside the story as a man, not a handler invoice.” Cassian’s mouth almost found hers and stopped—mid-want craft, consequence first.

Outside, copper bells changed watch. Practice yards glowed bruise-blue through fog. Calderyn failed by inches. Thorne’s mark remembered bloom without romance invitation. The Unmade whispered at borders. [player_name] held the page and the hinge and Cassian’s heat along her side.

The room smelled of salt and oil and unfinished honesty. She refused to invent confirmation where the page stopped. She refused to pretend reading aloud was climax. Mid-want hummed. Partnership was not a mood. Want was not weakness. Person first. Key never only.

Cassian’s sealed drawer watched them from the wall like a third pulse. He did not open it. She did not ask—not tonight. Secrets still had teeth. The page between their chests was enough partial for this hinge: hospital future or cliff weather, both costly, both adult, both refusing tidy sacrifice.

Salt wind rattled the window. Ozone clung faintly from yesterday’s failed braid. [player_name] lay between cream Latin and scorched leather with living-key ambiguity still fog in her mouth, Thorne still unfinished outside romance lock, and the next verb waiting like weather with teeth—hospital dawn or cliff dawn—while Ashmere’s cliff fortress kept score in fog and copper and a bed that had learned how to hold war without becoming only war.

Salt wind kept score on the glass. Ozone clung like breath after a denied kiss. Copper bells tasted the air for fracture and found enough to keep their tongues restless. Calderyn thinned by inches beyond Veil Sea fog. The Unmade pressed every honest map without offering tidy martyrdom. Cassian Rook’s scorched leather stayed in the room like a vow that refused Collegium ink. Living-key sacrifice stayed a shape without clean edges unless this hinge had already earned its partial. Thorne remained temptation-shaped rumor—warm wine over broken glass—never a second LI while romance locked on Cassian. Mid-want hummed unfinished under duty. Hope and dread shared the doorway. Eyes open. Person first. Key never only. The hinge asked again, sharper by 771 breaths of unfinished wanting.

Salt wind kept score on the glass. Ozone clung like breath after a denied kiss. Copper bells tasted the air for fracture and found enough to keep their tongues restless. Calderyn thinned by inches beyond Veil Sea fog. The Unmade pressed every honest map without offering tidy martyrdom. Cassian Rook’s scorched leather stayed in the room like a vow that refused Collegium ink. Living-key sacrifice stayed a shape without clean edges unless this hinge had already earned its partial. Thorne remained temptation-shaped rumor—warm wine over broken glass—never a second LI while romance locked on Cassian. Mid-want hummed unfinished under duty. Hope and dread shared the doorway. Eyes open. Person first. Key never only. The hinge asked again, sharper by 647 breaths of unfinished wanting.

Salt wind kept score on the glass. Ozone clung like breath after a denied kiss. Copper bells tasted the air for fracture and found enough to keep their tongues restless. Calderyn thinned by inches beyond Veil Sea fog. The Unmade pressed every honest map without offering tidy martyrdom. Cassian Rook’s scorched leather stayed in the room like a vow that refused Collegium ink. Living-key sacrifice stayed a shape without clean edges unless this hinge had already earned its partial. Thorne remained temptation-shaped rumor—warm wine over broken glass—never a second LI while romance locked on Cassian. Mid-want hummed unfinished under duty. Hope and dread shared the doorway. Eyes open. Person first. Key never only. The hinge asked again, sharper by 523 breaths of unfinished wanting.

Salt wind kept score on the glass. Ozone clung like breath after a denied kiss. Copper bells tasted the air for fracture and found enough to keep their tongues restless. Calderyn thinned by inches beyond Veil Sea fog. The Unmade pressed every honest map without offering tidy martyrdom. Cassian Rook’s scorched leather stayed in the room like a vow that refused Collegium ink. Living-key sacrifice stayed a shape without clean edges unless this hinge had already earned its partial. Thorne remained temptation-shaped rumor—warm wine over broken glass—never a second LI while romance locked on Cassian. Mid-want hummed unfinished under duty. Hope and dread shared the doorway. Eyes open. Person first. Key never only. The hinge asked again, sharper by 399 breaths of unfinished wanting.

Salt wind kept score on the glass. Ozone clung like breath after a denied kiss. Copper bells tasted the air for fracture and found enough to keep their tongues restless. Calderyn thinned by inches beyond Veil Sea fog. The Unmade pressed every honest map without offering tidy martyrdom. Cassian Rook’s scorched leather stayed in the room like a vow that refused Collegium ink. Living-key sacrifice stayed a shape without clean edges unless this hinge had already earned its partial. Thorne remained temptation-shaped rumor—warm wine over broken glass—never a second LI while romance locked on Cassian. Mid-want hummed unfinished under duty. Hope and dread shared the doorway. Eyes open. Person first. Key never only. The hinge asked again, sharper by 275 breaths of unfinished wanting.

Salt wind kept score on the glass. Ozone clung like breath after a denied kiss. Copper bells tasted the air for fracture and found enough to keep their tongues restless. Calderyn thinned by inches beyond Veil Sea fog. The Unmade pressed every honest map without offering tidy martyrdom. Cassian Rook’s scorched leather stayed in the room like a vow that refused Collegium ink. Living-key sacrifice stayed a shape without clean edges unless this hinge had already earned its partial. Thorne remained temptation-shaped rumor—warm wine over broken glass—never a second LI while romance locked on Cassian. Mid-want hummed unfinished under duty. Hope and dread shared the doorway. Eyes open. Person first. Key never only. The hinge asked again, sharper by 151 breaths of unfinished wanting.

Salt wind kept score on the glass. Ozone clung like breath after a denied kiss. Copper bells tasted the air for fracture and found enough to keep their tongues restless. Calderyn thinned by inches beyond Veil Sea fog. The Unmade pressed every honest map without offering tidy martyrdom. Cassian Rook’s scorched leather stayed in the room like a vow that refused Collegium ink. Living-key sacrifice stayed a shape without clean edges unless this hinge had already earned its partial. Thorne remained temptation-shaped rumor—warm wine over broken glass—never a second LI while romance locked on Cassian. Mid-want hummed unfinished under duty. Hope and dread shared the doorway. Eyes open. Person first. Key never only. The hinge asked again, sharper by 27 breaths of unfinished wanting.`,
  textHot: `Cassian’s bed smelled like blade-oil and the unfinished almost of his mouth. Salt wind at the glass. Fog climbing Ashmere’s cliff. [player_name] sat against the headboard with the cream page between their chests and Cassian half over her—scorched leather discarded, sleep-carved mouth close enough to ruin her, mid-thirties heat banked on purpose. Her cracked charm pulsed between her breasts until her nipples tightened against the shift. Mid-want was not a mood. It was the slick fact she carried into reading aloud.

She read living-key Latin while his thigh slotted between hers, careful not to crush the page, filthy enough that her cunt answered the paper’s honesty with a pulse she refused to tidy. Recognition without ownership. Refusal grammar. Second fracture inland unnamed into tidy war. Sacrifice still fog. Thorne temptation not LI. Romance locked on the man whose cock was hard against her hip and denied on purpose.

“Aloud so we don’t invent belonging,” she managed, voice rough, and Cassian’s glove—discarded—left his bare fingers free to find the wet edge of her underwear and keep time there: stroke, stop, stroke—like a man who understood mid-want was the only ending Ashmere currently earned.

“Hospital dawn and I fuck you slow after the stitch-light fades until you come with my name and this page’s truth in the same breath,” he said against her pulse. “Cliff dawn and I keep you aching on the stairs—leave or stay spoken with my fingers still shiny from you—because unfinished is how grief and sex coexist without eroticizing the Unmade.”

[player_name] arched into the almost. Page between them. Choice unfinished. His mouth found her throat. His fingers found her clit and stopped just shy of enough. She cursed softly into salt air. He smiled like a blade wrapped in care.

She wanted to come with living-key Latin still in her mouth. She wanted his fingers inside her while the page crinkled against her sternum. She wanted fucking deferred one more breath because consequence mattered—and she wanted that deferral to hurt sweetly, proof she still had a self Isolde could not quiet.

Cassian’s thumb circled once—filthy punctuation—then eased away, painting her lower lip with wet honesty. “Verb,” he murmured. “Hospital soft rebuild or cliff leave-or-stay. Your cunt already voted. Your mouth has to catch up.”

Nipples hard. Thighs trembling. Charm ticking like a second clit. Living-key fog. Unmade pressing beyond fog. Thorne’s rumor-warm absence. Romance lock unbroken. She held hospital-dawn and cliff-dawn slick and unresolved while his cock stayed hard against her hip and unanswered on purpose.

Outside, copper bells tasted fracture. Inside, [player_name] catalogued shamelessly: location—clit, nipples, throat under his mouth; intensity—enough that the page shook; trigger—Cassian’s refusal to let reading become harvest or cheap climax. Mid-want craft. Partnership with teeth.

She imagined gauze light and machines inventing patience while he fucked her careful after—then imagined cliff stairs and fog while he kept her dripping through leave-or-stay. Both fantasies left her empty now. She needed the emptiness. It meant she was still choosing.

“I’ll pick,” she whispered against his mouth without taking the kiss fully. Salt. Ozone ghost. Blade-oil skin. Sacrifice still ambiguous. Eyes open. Person first. Key never only. Cassian Rook waited like a man who would walk either dawn and refuse a third where they pretended the page had finished wanting for them.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 1007 more unfinished breaths and did not come.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 879 more unfinished breaths and did not come.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 751 more unfinished breaths and did not come.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 623 more unfinished breaths and did not come.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 495 more unfinished breaths and did not come.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 367 more unfinished breaths and did not come.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 239 more unfinished breaths and did not come.

Her cunt ached around absence like a vow. Nipples hard against cloth. Charm ticking between her breasts like a second clit Isolde was not invited to touch. Cassian’s thumb on her pulse sent a filthy line straight to her clit and lodged there, throbbing. She wanted his glove between her legs and denied herself on purpose because mid-want endings mattered. Wet fabric dragged when she shifted. His body heat along her back translated duty into a hand she refused to apologize for wanting. Fucking deferred until consequence had a name. Thorne stayed temptation not lover. Romance lock unbroken. Salt on her tongue. Ozone in her sinuses. Blade-oil patience banked like a fuck held in check. She held the ache through 111 more unfinished breaths and did not come.`,
  choices: [
    { id: "scene9g", text: "Hospital dawn: Cassian and her future", textHot: "Hospital dawn: Cassian and her future — soft rebuild with his mouth still on your pulse" },
    { id: "scene9h", text: "Cliff dawn: leave Ashmere or stay", textHot: "Cliff dawn: leave Ashmere or stay with his fingers still unfinished on you" }
  ]
};
