export default {
  id: "scene5f",
  layer: 5,
  title: "Bram calls: hymn fragment says living keys can be *refused* — still not the full sacrifice map",
  text: `Archivist Bram Kestrel found them in the lower stacks where forbidden shelves breathed dust and copper. Rain had not reached here; ozone had. [player_name]’s cracked charm ticked. Cassian Rook stood at her shoulder smelling of cliff rain and unfinished almost-kiss, practice gloves dark with water. Bram’s hands shook as he laid a hymn fragment on the reading slate—half-translated, edges burned as if someone had tried to erase refusal from history.

“Living keys can be refused,” Bram whispered. “The verb is archaic. The cost clause is missing. This is not the full sacrifice map. Do not thank me as if I handed you a door without a cliff behind it.”

[player_name] read the line twice. Refusal. Power that could stay in a body instead of Isolde’s wall. Hope spiked dangerous. Dread followed—because Isolde’s ledger did not love refused keys, and Lord Vesper Thorne’s frequency in the stone did not clarify whether refusal fed him or starved him. Temptation without romance lock broken. Cassian only.

“Who else knows?” Cassian asked, soft absolute.

“Maris suspects. Isolde suspects everyone. You two now.” Bram swallowed. “If you record raw admission of frequency match after this fragment, the Collegium may treat refusal as obstruction. If you take the drowned bell-tower lead before dawn, you may find copper evidence that makes refusal look like prophecy. I am an archivist. I am not your conscience.”

He left them with the slate and the smell of burned hymn edges. Cassian’s hand settled at the small of [player_name]’s back—asking.

“Refuse,” he said quietly, “and you still have to survive the people who need you not to. Bell-tower with me before dawn—or put the raw match on record and burn soft exits. Either way I stay in your war. Prefer both. Won’t force either.”

Salt wind found the stack stair. Copper bells wrong above. Living-key sacrifice still fog beyond one refused verb. Unmade still contested. Mid-want humming under the fragment’s hope like a second unfinished sentence. [player_name] held the hinge between raw ledger point-of-no-return and the bell-tower lead with Cassian into Veil Sea fog.

Ashmere Collegium held its breath the way cliff stone held salt: slowly, permanently, with a patience that punished anyone who mistook endurance for kindness. [player_name] felt that patience in her molars whenever copper bells missed their true intervals and the cracked charm at her throat answered with a tick that was almost a word. Practice yards below still carried blue-bruise afterglow; ozone from failed braids clung to rain-damp wool; Veil Sea fog climbed the stairs as if curious about every almost-confession happening above the waterline.

Calderyn beyond the fog was not a map problem alone; it was failing farmlands, aurora-glass markets dimming, border villages that heard Unmade whispers first and sent fewer letters home. Every Collegium choice eventually became inland weather. [player_name] carried that knowledge beside mid-want and duty, inseparable, while Cassian Rook’s scorched-leather nearness made survival feel like something her body could negotiate with instead of only obey.

Living-key rumors remained contested on purpose. Bram Kestrel’s half-translated hymns suggested refusal might be possible without proving what refusal cost. Isolde Vane’s sealed manners suggested candidates had burned quieter than public trials admitted. Cassian’s ashwood drawer stayed shut on a past that included nearly following Lord Vesper Thorne out of the wards after a border push went wrong. Thorne himself stayed unfinished: warm wine over broken glass, monster and revolutionary braided until late layers forced a cut—temptation allowed, romance lock unbroken, Cassian only.

Trust under apocalypse pressure had a smell: spent magic, salt, old parchment, blade oil. Hope and dread shared every doorway. Mid-want held the hinge. The next verb would cost access, innocence, or the last clean line between handler and hunger—and living-key truth would still not be finished when the bells changed watch over Ashmere’s rain-dark towers. Maris Quill’s fear still walked the dining halls. Ambiguity locked itself again: no confirmation [player_name] was lineage; no clean monster-label for Thorne; no opened drawer; only salt, bells, Cassian’s unfinished mouth, and choice sharpening consequence-verbs in the cliff wind.


Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.


Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.


Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.


Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.


Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.


Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.


Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.


Salt wind worried the shutters and brought the Veil Sea’s cold up the cliff in slow increments. [player_name] touched the cracked charm once, private, and felt the almost-seal’s ghost under her sternum answer like a bruise. Cassian watched her without coaching, mid-thirties exhaustion and brutal charm sanded to listening. Somewhere inland wards thinned another quiet inch. Somewhere on the cliff face Thorne’s black sigil still remembered how to bloom. She chose nothing yet—only stood in the hinge of mid-want while Ashmere’s bells kept score and the Unmade pressed like weather that had learned her name. Rain tracked copper. Ozone lingered. The war did not pause for unfinished sentences between handler and candidate who wanted more than maps.
`,
  textHot: `Bram’s fragment—*living keys can be refused*—should have cooled [player_name]. It heated her instead: refusal as consent’s twin, power that could stay in her cunt and her mouth instead of Isolde’s wall. Cassian watched her lips shape the words and looked like he wanted to kiss the hymn off her tongue. His hand settled low on her back, fingers spanning toward the upper curve of her ass without apology, scorched leather and cliff-rain still on him from the unfinished taped kiss.

“Refuse,” he said softly, “and you still survive the people who need you not to.” His thigh pressed hers. Hard. Honest. “Bell-tower before dawn with me—or admit raw on record and burn the soft exits. Either way I stay in your bed or your war. Prefer both.”

She was wet enough that shifting weight made her breath catch. Charm ticking between her breasts. Nipples tight from rain memory and hope. Living-key full map still denied—cost clause missing, Bram said—and that missing cost somehow made her hungrier for Cassian’s mouth as proof she could still choose bodies over walls. Thorne temptation in stone, not in her romance. Unmade pressing. Mid-want humming under the fragment like a refused climax waiting for her verb: raw admission recorded, or bell-tower lead with him into fog before dawn.

[player_name]’s cunt ached with unfinished promises; every shift of cloth reminded her that Isolde’s politics and Thorne’s leftover song had both woken something filthier than fear. Her nipples stayed tight under damp fabric. Cassian’s gaze kept dropping to her mouth like a man memorizing fracture lines on a body instead of a ward. When he spoke low, she felt the words between her legs—handler voice, battlemage voice, the voice of someone who had almost followed Thorne and now poured that almost into wanting her alive and wanting her, period.

His glove on her pulse was a filthy soft argument: not claiming as key, claiming as the man who would drag her out of silver thread even if it meant putting his hands on her in front of Collegium stone. [player_name] wanted those hands lower. Mid-want made waiting feel like edged climax denied. She went slicker for honesty than for any clean romance script, thighs pressed tight, charm ticking between her breasts like a second clit answering scorched leather and blade oil.

Thorne’s frequency in the stone stroked her ribs and made her empty flutter as if song could find her clit; she refused to confuse that wrong music with Cassian’s heat. One was temptation without romance lock. The other was a cock restrained by duty and the sheer terror of repeating an old push. Sex was not violence cosplay. War magic could be brutal. What she wanted from Cassian was consent loud enough to drown Isolde’s ink and still leave the living-key map unfinished on purpose.

She imagined his mouth on her charm, on her breasts, on the wet seam of her through cloth until she came quiet enough that Isolde’s stones could not file the sound. The fantasy was plot, not garnish—it decided how much truth she could speak while aching. Blue-bruise memory from the yards braided with want. Calderyn’s thinning wards somehow made her hungrier for the man who taught survival without promising salvation. Mid-want exits demanded she choose before climax. Her body voted filthy for whichever verb kept his hands in the sentence. Hope and dread shared her cunt the way they shared Ashmere’s thresholds. Living-key ambiguity still contested; Thorne’s frequency still a rumor in her blood; Cassian’s sealed past still teeth behind one drawer—mystery as friction, danger as heat. Ashmere’s cliff held them above a hungry sea while [player_name] kept her heat like a ward-braid under tension—alive, unfinished, refusing tidy endings.


Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.


Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.


Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.


Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.


Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.


Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.


Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.


Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.


Salt wind licked the sweat at [player_name]’s throat and did nothing to cool the slick heat between her thighs. Cassian’s unfinished almost—mouth, cock, glove—lived in phantom afterimage hard enough to make her breath break. She wanted to finish it against Collegium stone and knew finishing belonged to the next verb, not this withheld pulse. Living-key fog held. Romance lock held. Mid-want refused tidy endings while copper bells scored how stupid and necessary wanting him remained under war pressure. Her cunt clenched on emptiness. Her charm ticked like a dare. He did not take her yet. The ache was the point—and the plot.
`,
  choices: [
    { id: "scene6f", text: "Raw admission recorded — point of no return for the Collegium ledger", textHot: "Record the raw match — point of no return while refusal still tastes like his mouth" },
    { id: "scene6g", text: "Bell-tower lead with Cassian before dawn", textHot: "Bell-tower before dawn with him — take refusal into the fog together" }
  ]
};
