const QB = "until-the-quiet-breaks", SK = "what-the-sister-kept", LK = "the-living-key", SA = "the-soft-alibi";
const r = (story, scene, find, repl, n) => ({ story, scene, find, repl, ...(n ? { n } : {}) });
export default [
  // ---- within-version repeats
  r(QB, "scene7k", `"Morning knocks like a dare," John groaned, hitching her knee higher and grinding against her clit with the base of his cock until her vision whitened. "She can dare the morning. Tonight belongs to this locked door and whatever sentence you put in my mouth before dawn."`,
    `"Morning knocks like a dare," John said into her throat, rolling his hips in slow, deep strokes that dragged every inch of him across the place that made her shake. "Let it knock. I'm not giving this door back until you've said what you came here to say."`, 1),
  r(QB, "scene7m", `Somerton's only reliable metronome. The stuck drawer hung open.`, `Somerton's only reliable metronome. The drawer still gaped where she had forced it.`, 1),
  r(QB, "scene8d", `Control as negotiation. "My life isn't only your wound.`, `Control as negotiation. "I'm not a bandage for your guilt.`, 1),
  r(SK, "scene6n", `Rhee summarized without kindness. "Or go public to protect him.`, `Rhee summarized without kindness. "Or take it to the street and shield him there.`, 1),
  r(SK, "scene8h", `Rain thickened on the glass. A foghorn rolled inland, low enough to feel in the sternum even downtown.\n\nRain thickened on the glass. A foghorn rolled inland,`, `Rain thickened on the glass. A foghorn rolled inland,`, 1),
  r(SK, "scene8o", `"Hydrate," he said, soft and ridiculous under storm weather. "Flashbulbs dehydrate. Hiding dehydrates. Loving a detective with a sealed drawer dehydrates." He almost smiled. Failed into something fonder. "I am trying to be a man who offers water before he offers forks. Soft nets start small when the city is loud."`,
    `She took the mug. Storm weather leaned on the window while he waited, and when the smile finally came it failed into something fonder. "Small things first," he said. "Water. A locked door. Soft nets start small when the city is loud."`, 1),
  r(SK, "scene9h", `"Clock," Will said softly. "Leave Harborwick free, and I respect it. Or stay in the fog with me. Either way the boards remember her. Pick."`, `"Clock," Will said softly. "Go, and I won't hold it against you. Or stay in the fog with me. Either way the boards remember her. Your call."`, 1),
  r(SK, "scene10f", `At dusk they drove to the pier district. The foghorn rolled low. The chain-link rattled. Harborwick remembered everything except the old official story, and the old official story was finally dead.\n\n`, ``, 1),
  r(LK, "scene2b", `as if roughness were the only honesty left. "Warm wine over broken glass.`, `as if roughness were the only honesty left. "The same voice. Warm wine, broken glass.`, 1),
  r(SA, "scene7a", `She nodded, eyes hot. Public method or sealed bargain.`, `She nodded, eyes hot. Neither answer came cheap.`, 1),
  r(SA, "scene7j", `In the elevator alone she pressed her palm over the wire and almost came from pressure and fear braided. Soft laughed once without sound and still had not named which danger she would feed when the doors opened on lobby light.\n\nHall carpet. Soft between being made and night-truth. Mic still kissing ribs like a secret spouse. Nolan somewhere above or across. Soft unfinished and walking.`,
    `Nolan somewhere above or across, the wire warm under her palm. Soft unfinished and walking.`, 1),
  r(SA, "scene7k", `Keep the tower name — let the desk go. Burn the night before morning owns soft.`, `Neither sentence would cost her less for waiting.`, 1),

  // ---- QB freight horn: keep scene5m (W) and scene7m (W, "Beyond Willow ... theft")
  r(QB, "scene6a", `John's jaw flexed. A freight horn complained toward the yard.`, `John's jaw flexed. Rain ticked off the gutter in uneven beats.`, 1),
  r(QB, "scene6b", `A freight horn complained toward the yard.`, `The ice machine dropped a load into its bin.`, 1),
  r(QB, "scene6e", `A freight horn complained toward the yard. The cord trembled`, `Somewhere down Market Street a car door slammed. The cord trembled`, 1),
  r(QB, "scene6e", `Freight complained toward the yard, ordinary as ever.`, `A car door slammed down Market Street, ordinary as ever.`, 1),
  r(QB, "scene6h", `A freight horn complained toward the yard.`, `The coffee urn ticked as it heated.`, 1),
  r(QB, "scene7i", `A freight horn complained toward the yard. Regulars`, `Gray light crept along the counter stools. Regulars`, 1),
  r(QB, "scene7i", `A freight horn complained toward the yard. His cock`, `A bus sighed at the corner stop and pulled away. His cock`, 1),
  r(QB, "scene7j", `A freight horn complained toward the yard. [player_name] thought of Clara`, `Somewhere a church bell counted the hour. [player_name] thought of Clara`, 1),
  r(QB, "scene7j", `A freight horn complained toward the yard. [player_name] tangled`, `Rain drummed the awning over Market Street. [player_name] tangled`, 1),
  r(QB, "scene8a", `A freight horn complained toward the yard. The cracked stool`, `A neighbor's wind chime clattered and went still. The cracked stool`, 1),
  r(QB, "scene8o", `A freight horn complained toward the yard.`, `A signal bell clanged at the crossing.`, 1),
  r(QB, "scene7h", `Freight complained toward the yard.`, `A gutter spilled over somewhere close.`, 1),
  r(QB, "scene7l", `Freight complained toward the yard.`, `A car hissed through standing water.`, 1),
  r(QB, "scene7o", `Freight complained toward the yard.`, `The porch boards creaked under them.`, 1),
  r(QB, "scene7p", `Freight complained toward the yard.`, `Wind worried the bare maple by the gate.`, 1),
  r(QB, "scene8c", `Freight complained toward the yard.`, `A dumpster lid banged in the wind.`, 1),
  r(QB, "scene8d", `Freight complained toward the yard.`, `Water ran loud in the downspout beside them.`, 1),
  r(QB, "scene8f", `Freight complained toward the yard.`, `Market Street lay empty and shining.`, 1),
  r(QB, "scene8h", `Freight complained toward the yard.`, `The mantel clock ticked into the quiet.`, 1),
  r(QB, "scene8j", `Freight complained toward the yard.`, `A gust rattled the loose pane in its frame.`, 1),
  r(QB, "scene6p", `Outside, a freight horn complained toward the yard.`, `Outside, a car crept past with its wipers slapping.`, 1),
  r(QB, "scene6p", `Outside, a freight horn complained toward the yard, ordinary Somerton going on without permission.`, `Outside, a car alarm whooped twice and quit, the town going on without permission.`, 1),
  r(QB, "scene7e", `Outside, a freight horn complained toward the yard.`, `Outside, gutters ran loud along Market Street.`, 1),
  r(QB, "scene7e", `Outside, freight complained toward the yard.`, `Outside, tires hissed on wet asphalt.`, 1),
  r(QB, "scene7n", `Outside, a freight horn complained toward the yard.`, `Outside, a garbage truck groaned through its route.`, 1),
  r(QB, "scene8a", `Outside, a freight horn complained toward the yard.`, `Outside, rain drummed on the porch roof.`, 1),
  r(QB, "scene8b", `Outside, a freight horn complained toward the yard.`, `Outside, a gutter overflowed onto the walk.`, 1),
  r(QB, "scene8e", `Outside, freight complained toward the yard.`, `Outside, the rain thinned to mist.`, 1),
  r(QB, "scene8m", `Outside, freight complained toward the yard.`, `Outside, a siren rose and faded toward the highway.`, 1),
  r(QB, "scene6i", `Somewhere a freight complained toward the yard, ordinary Somerton continuing without permission.`, `Somewhere a power saw whined into wet lumber, ordinary Somerton continuing without permission.`, 1),
  r(QB, "scene6j", `The freight horn complained toward the yard.`, `The furnace kicked on under the floorboards.`, 1),
  r(QB, "scene6k", `A freight complained toward the yard.`, `A screen door banged somewhere down the street.`, 1),
  r(QB, "scene6l", `Outside, a freight complained toward the yard.`, `Outside, a pickup idled at the light.`, 1),
  r(QB, "scene6m", `Beyond Willow, a freight horn complained toward the yard.`, `Beyond Willow, a dog barked at nothing and gave up.`, 1),
  r(QB, "scene7k", `Freight complained toward the yard, ordinary Somerton continuing without permission.`, `Gutters chattered along Willow, the town going about its business without asking.`, 1),
  r(QB, "scene8n", `Outside, freight complained toward the yard far below.`, `Outside, traffic hissed along the street far below.`, 1),
  r(QB, "scene8e", `Freight hissed toward the yard.`, `The rain eased to a hiss in the gutters.`, 1),
  r(QB, "scene8f", `Freight hissed toward the yard.`, `The neon in Mae's window buzzed and steadied.`, 1),
  r(QB, "scene8g", `Freight hissed toward the yard.`, `A pipe knocked somewhere in the walls.`, 1),
  r(QB, "scene8h", `Freight hissed toward the yard.`, `Wind threw a fistful of rain at the window.`, 1),

  // ---- LK Isolde line: keep scene5a (H, "Maybe it was.") and scene8h (H)
  r(LK, "scene6a", `Isolde watched their mouths as if heat were evidence. It was.`, `Isolde's gaze moved from his mouth to her throat, taking notes without ink. She missed nothing.`, 1),
  r(LK, "scene7a", `Isolde watched their mouths as if heat were evidence. It was.`, `Isolde's lashes lowered, as if the flush on [player_name]'s throat were a line she could read.`, 1),
  r(LK, "scene7e", `Isolde watched their mouths as if heat were evidence. It was.`, `Isolde tapped the silver once, unimpressed by how hard they were trying not to touch.`, 1),
  r(LK, "scene8a", `Isolde watched their mouths as if heat were evidence. It was.`, `Isolde's gaze dropped to her thighs and stayed there long enough to count.`, 1),
  r(LK, "scene8b", `Isolde watched their mouths as if heat were evidence. It was.`, `Isolde let the quiet stretch, measuring the color in [player_name]'s face like a debt.`, 1),
];
