export default {
  id: "scene9b",
  layer: 9,
  title: "Trial path: testify with mercy deal",
  text: `The mercy deal smelled like burnt precinct coffee and paper that had been folded too many times—Harborwick's softer justice, sealed at the edges, fluorescent and unfinished. [player_name] sat across from Captain Mara Ellison in a glass conference room that overlooked rain-needled courthouse steps while Jake Akers leaned against the wall with his cracked notebook closed for once, mid-thirties charcoal jacket, scar cutting his left eyebrow, grey-green eyes watching the plea language the way a man watches a fuse he is not allowed to stamp out.

Owen Vale would plead to lesser counts on the smuggling and evidence-tampering chain—Warehouse C, clerk initials M.K., midnight trucks that did not match any shipping board—in exchange for testimony against the clerk and a sentencing recommendation that kept a shred of supervised life instead of the deepest cut. Full name of the pier night still had to be spoken. Soft edges around the family throat. Mercy that might be wisdom or might be cowardice with better lighting. Ellison called it political weather management. Jake called it a sealed page that would itch forever.

"You testify truthfully to what you saw," Ellison said, tablet light painting her chin from below. "Owen near the pier. The kept silence. Renny's journal as chain-of-custody spine. You do not invent corpses for the cameras. You do not sandbag the clerk to spare your stepfather a harder number. In return, the deal holds—supervised truth, costly forgiveness shaped like a docket, one sealed page on collateral damage that does not need to be city weather. Akers signs as investigating detective. You sign as familial witness. Owen signs or the deal burns and we go full-blade."

Jake's cracked knuckles flexed. When Ellison's gaze flicked—almost naming Nina Solis, almost saying sealed IA the way captains say warnings—Jake did not flinch for the glass. The dark past hummed under his badge: partner's fall, hallway, silence that rhymed with a sister kept quiet. Hint deepening. Teeth showing. Brutal charm filed down to a public edge that refused to smile. "Cho's unidentified upriver remains stay *pending* in every sentence," he said. "Charm probability is not an ID. Mercy for Owen does not get to christen bone. Hope stays allowed. Dread stays honest. Anyone who collapses those for a softer headline does the chain's work for free."

[player_name] tasted copper where she had bitten her cheek. Renny—teenager when she vanished, missing seven years—had written the pier night into purple leather. [player_name] had kept Owen off the official statement for seven years of soft cowardice dressed as protection. Mercy now meant putting him under lights without cutting the family clean—supervised truth, a porch light that might still burn with conditions, a love that had to heal around one sealed page instead of living in pure daylight. Mid-twenties shame shared the glass room with mid-thirties hunger for clean pages Jake did not trust mercy to write.

Owen was brought in under escort, butter-porch calm cracked into something usable and ugly. He looked at [player_name] like a man who still wanted to sell her a softer lie and found the inventory empty. "I will name the clerk," he said. "I will name the trucks. I will not pretend I was a good stepfather. I am asking for a sentence I can survive long enough to answer what I can answer." He did not say Renny's name as corpse. Jake's stare made sure of that. Hope and dread still shared the doorway. Lab ID still pending. Charm upstairs still only *like*.

The testimony that followed in the smaller hearing room was not the full-blade circus. It was quieter, uglier in its kindness. [player_name] spoke the pier night under oath with Jake two rows back like a weather system that had decided to stay. She named Warehouse C. She named the kept detail. She named her own silence without dressing it as virtue. When defense counsel for the clerk tried to make her a liar sleeping with the detective, Jake's jaw flexed and he let her own the answer again: attraction did not invent the chain; grief did not invent Owen at the pier; Cho still said pending.

Recess found them in a courthouse stairwell that smelled like rain on concrete and floor wax, foghorn rolling inland through a cracked window. Jake stood one step below [player_name] so their eyes were level—partnership geometry disguised as logistics—and the almost-kiss of his nearness banked heat the hearing must not catalogue.

"Mercy is a verb with teeth," he said quietly. "Ellison gets political cover. Owen gets a shred of supervised life. You get to decide whether the sealed page heals or festers. I get to decide whether I can love a woman who chose costly forgiveness without confusing it for the silence that failed Renny once." His cracked knuckles brushed the rail near her hand—heat, calluses, a pulse that was not quite touching. "Solis took a fall I ordered into being. I kept a badge. I know what sealed pages cost. If you soft-rebuild with one page still healing, I will hold the itch with you and not pretend daylight was total. If you lean into costly forgiveness—Owen redeemed-ish, supervised truth, the porch light on a timer—I will stand in that weather too. I will not pretend it does not hurt. I will not invent a corpse to make the hurt cleaner."

Ellison's tablet chimed above them. Somewhere below, Owen's attorney murmured deal language. Pier salt rode the stairwell draft. Attraction hummed unwanted under procedural pressure: the sleep-deprived set of Jake's shoulders, the dangerous care of refusing to baptize bone for a softer docket, the mid-thirties heat of a man who would stand in fluorescent ruin with her mid-twenties mercy and call it partnership if she asked honestly.

[player_name] stared past him toward the rain-needled glass, toward the upriver stretch where unidentified remains waited without a name, toward Renny's room where a charm that was only *like* still winked in a drawer that smelled like absence. Hope still had a throat. Dread still had teeth. Choosing the soft rebuild meant love with one sealed page still healing—Jake and her in Harborwick weather that admitted incompleteness without calling incompleteness a lie. Choosing costly forgiveness meant Owen's supervised truth as a living cost, family not cut clean, a redemption-ish shape that would require watching him answer forever without pretending the pier night had been kindness.

In the smaller hearing room after the stairwell, Owen named the clerk under the deal's supervised lights—voice cracking where butter-porch calm used to live—while [player_name] sat with Jake two rows back and felt the old family house rearrange itself into something conditional and sharp. Mercy did not taste like absolution. Mercy tasted like rain on courthouse glass and a stepfather finally useful without being clean. Dr. Lila Cho's pending language still sat in the exhibits like a third counsel: unidentified remains, charm probability, hope and dread sharing the aisle. Nobody christened bone for a softer docket. Jake made sure of that with a look that could stop a truck and still somehow felt like care.

Ellison met them again in the glass conference room with signature tabs that smelled like sealed paper and political relief. "Soft rebuild leaves one page itching on purpose," she said. "Costly forgiveness keeps Owen answering under lights he cannot turn off. Both are quieter than full-blade. Both still name the chain. Both still refuse to let rumor invent Renny's funeral before science speaks. Akers's IA shadow does not vanish because you chose mercy grammar—Solis-shaped questions will still smell closeness. I am telling you because Layer 9 does not get to pretend seals erase teeth."

Jake's cracked knuckles brushed [player_name]'s sleeve as they left the glass—heat, calluses, unfinished almost. Pier salt rode the hallway draft from someone's open stairwell door. "I watched Solis take a fall I built," he said. "Mercy deals rhyme if you listen wrong. Listen right: this seal is sentencing weather and collateral, not a second pier-night silence. Soft rebuild means we admit the itch and heal anyway. Costly forgiveness means we watch Owen's supervised truth without confusing survival for redemption. Renny stays pointed finger until Cho earns a harder word. That is the only honest mercy I can stand inside."

Jake Akers watched her the way a man watches a fuse he helped light and then agreed to bank. "When Cho finally speaks—if Cho finally speaks—you do not owe Owen a softer science," he said. "You owe Renny honesty. Mercy today is about sentencing weather and sealed collateral, not about inventing hope or inventing funerals. Pick the ending the deal gets to keep. Soft rebuild—or the costly forgiveness that keeps Owen in the story under lights he cannot turn off. Either way I stay. Either way *pending* stays the only honest word about those remains until the lab earns a harder one."

Chain-link rattled faintly beyond the courthouse. A bailiff called for parties. Foghorn answered the river again, lonely and low. [player_name] felt Jake shift half a degree closer—blocking one more lens from the stairwell landing without touching her, a claim that was not yet public and already felt like one. Trust climbed her throat like unfinished rain. Want banked for a room without Ellison's tablet. Grief stayed holy enough that she would not eroticize the river even while her pulse remembered his nearness.

The hook sat unfinished between them: a kiss they could not spend on courthouse concrete, a sealed page that would either heal or become the bittersweet cost of mercy, and Renny's fate still contested in careful language while hope and dread refused to leave the doorway. Jake's grey-green eyes stayed on her mouth. Brutal charm's quieter twin—attention as a blade laid flat—waited for her verb.`,
  textHot: `The mercy deal smelled like burnt precinct coffee and paper folded too many times, and [player_name]'s body was already too warm for Ellison's glass conference room. Rain needled the courthouse steps below. Jake Akers leaned against the wall—mid-thirties charcoal, scar catching fluorescent light, grey-green eyes dragging over [player_name]'s mouth before they forced themselves to the plea language like professionalism were a restraint he kept on for the girl's sake.

Owen would plead lesser on the chain—Warehouse C, clerk M.K., midnight trucks—for testimony and a sentencing shred instead of the deepest cut. Soft edges. Costly forgiveness. One sealed page. [player_name]'s mid-twenties cunt clenched when Jake's gaze caught hers across the glass: brutal charm banked, velvet over blade, the almost of his attention shooting between her legs before either pretended this was only a docket.

"You testify truthfully," Ellison said. "Pier night. Kept silence. Journal as spine. No invented corpses. No sandbagging the clerk to spare Owen a harder number. Deal holds—supervised truth, sealed collateral. Akers signs. You sign. Owen signs or we go full-blade."

Jake's cracked knuckles flexed. Ellison almost named Nina Solis; Jake's jaw worked and his eyes stayed on [player_name] like her pulse was a clit he was counting through cloth. Hint deepening. Broken men should not be this hot. "Cho's remains stay *pending*," he said, voice rough enough [player_name] felt it lower. "Mercy does not christen bone. Hope allowed. Dread honest."

Owen came under escort, porch-butter calm cracked. He named the clerk and the trucks and asked for a sentence he could survive. He did not baptize Renny as corpse—Jake's stare made sure. Charm upstairs still only *like*. Lab still pending. Hope and dread still sharing [player_name]'s soaked pulse under hearing-room polyester.

She testified quieter than full-blade and somehow filthier for the kindness: pier night under oath, Warehouse C, her own silence undressed. Every warehouse mark felt like a stroke behind her navel because Jake watched her mouth from two rows back the way a man watches a body he has not been allowed to open yet. When counsel tried to make her a whore with a badge, Jake did not stand; he let her answer while slick fabric dragged her clit raw with honesty. "Attraction does not invent the chain," she said, thighs pressed. Jake's hand pressed his own thigh once—hard, choosing not to show how hard—and the denied hunger was its own stroke.

Stairwell recess. Rain on concrete. Foghorn inland. Jake stood one step below so their mouths lined up and the air between them went wet. "Mercy is a verb with teeth," he murmured against her ear, breath hot enough to stroke. "Ellison gets cover. Owen gets a shred. You decide if the sealed page heals or festers. I decide if I can fuck the shaking out of a woman who chose costly forgiveness without confusing it for the silence that failed Renny." His cracked knuckles ghosted her hip, then cupped her ass through the skirt—claim the landing must not catalogue. "Solis took a fall I ordered. I kept the badge. I know sealed pages. Soft rebuild and I hold the itch with you in bed and do not pretend daylight was total. Costly forgiveness—Owen redeemed-ish under lights—and I stand in that weather too while I put my mouth on you until you stop tasting copper. I will not invent a corpse to make either cleaner. I am hard from watching you strip truths for a softer docket, and I am choosing—right now—to keep my cock out of Ellison's paperwork."

[player_name]'s cunt fluttered. Shame and hunger and grief fucked the same oxygen. She pressed into his hand for one filthy second and felt him groan low enough only she owned it.

Rain needled the stairwell glass and made a second metronome against her pulse. Jake's mouth found the hinge of her jaw, then the place under her ear that made her knees threaten the concrete, then her lips—kiss deep enough that mercy grammar left her head and only want remained, mid-thirties hunger teaching mid-twenties shaking that costly forgiveness did not have to mean unused body. His thigh slotted between hers; she rode the pressure once, cunt dragging slick denim heat through skirt fabric, and he cursed soft into her mouth like a man praying with worse vocabulary. "I have watched captains seal pages to save metrics," he said, forehead to hers, cock hard against her hip. "I have watched myself seal a hallway to save a badge. You are not them if you choose soft rebuild or costly forgiveness with your eyes open. You are the woman who said Warehouse C under oath with mercy still in the room and still refused to christen bone. That honesty is what I want to fuck. Not the deal. Not Owen's shred. You."

His free hand cupped her breast through the blouse, thumb circling a peaked nipple until she whimpered; the other stayed possessive at her lower back, holding her on his thigh. Pier salt and burnt coffee braided in every inhale. Solis ash stirred when he added, rough: "If IA smells us, let them smell honesty. They cannot smell how you soak for a detective who will not invent funerals. That catalog stays ours." She rocked again, ruined, and he denied her the edge on purpose—backed his thigh an inch, left her aching, smiled velvet-blade and wrecked. "Ending first. Orgasm after. Cho still pending. Hope still allowed. Dread still honest. Pick the mercy-shaped fire. His grey-green eyes stayed on her ruined mouth like a vow he had not logged. "I stay for both endings. Want is not the deal. You are.""

 "If I soft-rebuild," she whispered, "I will need you to touch the sealed page like a bruise we both agreed to keep."

"You will have me." Velvet-blade wrecked laugh. "Fingers on the itch. Mouth on the pulse in your throat every time you remember saying Warehouse C with mercy still in the room. If you take costly forgiveness, you will have me against the stairwell wall the second the last escort clears—skirt up, my hand in your cunt cataloguing how wet honesty made you while Owen signed his supervised life downstairs. Ellison can seal collateral. She cannot seal how you soak for competence that still refuses to baptize bone." He slid two fingers carefully under her waistband—found her soaked, stroked once along her clit without entering, pulled back like a man who still heard bailiffs—and left her aching. "That is mine to spend on a verb. Soft rebuild with one page healing—or Owen redeemed-ish under costly lights. Either way I stay. Either way Cho says *pending*. Either way I do not fuck you into christening what science has not named."

Hope still had a throat. Dread still had teeth. Remains still unnamed. Solis ash stirred deeper without dumping every sealed hallway page. [player_name]'s nipples peaked against her blouse where Jake's gaze caught—noticed, banked, promised. Choosing soft rebuild meant love around incompleteness, Jake's body teaching her that sealed did not have to mean silent cowardice, want spent in rain-dark sheets after supervised truth. Choosing costly forgiveness meant Owen kept in the story under lights, family not severed, and a detective who would hold her through the watching without asking her to confuse redemption-ish for absolution.

"Choose," Jake said against her temple, cock hard against her hip through charcoal, deliberate denial. "Before I kiss you where Ellison's tablet can see. Soft rebuild—or costly forgiveness. Want is not the deal. The deal is which ending gets the sealed page and which night gets the man who refused to invent a funeral so your mercy would look cleaner."

He crowded her one landing higher before the bailiff's voice fully arrived—mouth on her throat, hand under her skirt again, two fingers finally pushing into her soaked cunt while his thumb worked her clit in a filthy circle timed to the foghorn. "[player_name]," he whispered against her pulse. "Mercy makes you wetter than full-blade did, and I need you to know I see it without shaming it. Soft rebuild and I will finger this sealed-page itch out of you every night until healing stops tasting like copper. Costly forgiveness and I will fuck you slow while Owen's supervised lights stay on downstairs in your head—and every time you flinch I will remind you that your cunt is not his courtroom." She came on his hand with her teeth in his collar, muffled, shaking, mid-twenties grief and mid-thirties hunger braided without eroticizing the river. He kissed her temple, withdrew slick fingers, and sucked them clean like a vow. "Sample spent. Ending still yours. Cho still says pending. Solis still partly sealed. Pick."

Bailiff called. Foghorn answered. Jake stepped away with visible effort, leaving [player_name] unused and throbbing beside a badge that smelled like salt and unfinished weather. Unidentified remains waited upriver. Renny's journal waited as spine. The hook sat between them like denied fucking: which mercy-shaped ending got Jake Akers's mouth after the last signature, while hope and dread still shared the doorway and a charm that was only *like* still winked upstairs.`,
  choices: [
    { id: "scene10b", text: "Soft rebuild with one sealed page healing", textHot: "Soft rebuild with one sealed page healing" },
    { id: "scene10f", text: "Costly forgiveness — Owen redeemed-ish", textHot: "Costly forgiveness — Owen redeemed-ish" }
  ]
};
