export default {
  id: "scene9f",
  layer: 9,
  title: "Clerk escapes: Will hunts; she waits",
  text: `The side door had unlocked itself at the wrong minute, and Marcus Hale had become weather.

[player_name] sat in a precinct chair that smelled like fear and vending-machine coffee, mid-twenties, Renny's living link, watching William Akers tape a light gauze edge that was not tonight's wound and still felt like consequence. The clerk had slipped—municipal-small vanishing into Harborwick's damp history, tip-sheets already burning somewhere, a licensing desk that knew how to rinse itself into fog. Captain Mara Ellison's radio crackled status requests that sounded like blame with a unit number. Dr. Lila Cho's memo still lived in Will's cracked notebook without baptism: remains unidentified, charm probability elevated, age range ugly with hope. Science careful. Hope employed. Dread armed. Soft had died into a hunt.

Will stood mid-thirties, scar nick pale under bay fluorescents, grey-green eyes already on the pier road east. Brutal charm locked to inventory that refused comfort. Cracked knuckles whitened once around his notebook spine, then steadied. Nina Solis ash smoked behind the gesture without unpacking: sealed IA, a teenager in the wrong hallway, Ellison's fear that Akers would make the same ashes twice by rushing fog alone. He did not dump the sealed file. He wore the worse like cologne and offered [player_name] a waiting verb disguised as logistics.

"You stay," Will said. Not a question. Soft enough for the medic bay to invent distance, hard enough that attraction pressed stupidly under procedural dread. "I hunt. Hale is minutes into municipal vanish. Owen's reach already bought him a head start the night soft ice cut. I float backup. I lean warehouses. I walk every cigarette kiosk and every after-midnight desk code until Harborwick runs out of fog or I put steel on a throat that still thinks soft might hold."

[player_name] tasted copper where she had bitten her cheek. Waiting tasted like loyalty's quieter twin and also like abandonment with a badge. She wanted to go. She wanted him not to go. She wanted Renny's map to stop costing living people hours they could not get back. Attraction hummed unwanted: soap-and-salt nearness when he leaned to check her pulse like a man counting exits, unfinished almost-kisses from rain nights that had no business surviving into a chase brief.

"If I wait," she said carefully, "I become the person who held the line at the bay while you finish what a side door stole."

"Yes," Will said. Honest because comfort was a lie he refused. "You become reachable. You become the soft that does not tip the clerk further by becoming a second moving target. Ellison gets a narrative she will hate less than a dead witness and a lost municipal throat in the same night. You do not become a clearance story. Renny does not get a false funeral because a hunt went sideways in a hallway I already know how to dream."

Ellison appeared in the bay mouth—soft voice, final weather—tablet light painting her chin. "Akers. Hunt weather. Thin ice. The familial contact stays inland. Cho's tray stays contested. If you invent a corpse in fog to make the slip feel finished, I will invent paperwork that ends your badge before Solis's sealed drawer finishes humming." Her gaze cut to [player_name]. "You wait. Waiting is not cowardice tonight. Waiting is how soft nets stop becoming tip-calls."

Will's late smile arrived and died in the same breath—weapon and wound. He crouched in front of [player_name]'s chair so their eyes leveled, mid-thirties to mid-twenties, close enough to burn. "Two endings from a wait," he murmured, for her, while Ellison's radio grumbled. "Hold the bittersweet pier promise unfinished—anniversary fog, boards that remember her, an unfinished vow that is not a wedding and not a tidy hunt story—or stay in the city cold without me. Both leave Hale weather until I catch him or I don't. Both leave Cho careful. Both leave me wanting to put you somewhere soft after rain and failure or rain and a cuff. Pick the hurt that keeps truth reachable while I chase a clerk who still thinks bracelets mean the chain is safe."

[player_name] pictured the pier at dawn with Will smelling like fog and unfinished steel—bittersweet, Renny's poster weather, a promise that refused to close because closing would invent comfort. She pictured staying in Harborwick without him—apartment inland, hoodie still folded, charm gap aching, case noise without his cracked-knuckle patience—cold as a city that had already failed her sister once. Either path kept science from baptizing bone for the sake of a slip.

"If you take the pier promise," Will said quietly, cracked knuckles finding her wrist, pulse to pulse, "I come back when I can—success or empty pier road—and we stand on the boards where she vanished and say the hard sentences without pretending the hunt finished what seven years started. Bittersweet. Unfinished on purpose. Hope still employed beside dread." His thumb brushed her knuckles. "If you stay cold without me, you keep the city and you cut the badge from the braid. I hunt alone. You rebuild alone. Soft costs hours either way. Soft also costs the romance if you choose the cold stay as severance."

Silence thickened with rain against bay glass. Will paced the choice with his voice the way he walked interview rooms—counting exits, counting lies, counting what waiting cost when soft had already bought the chain minutes. "I will still be angry in every warehouse—angry at Owen, at Hale, at seven years of scrubbed silhouettes, at myself for floating soft until a side door became the only map that failed. Anger does not cancel the braid. Want does not cancel the cost of fog. I need you to hear both sentences without sanding either into comfort while Cho's tray stays contested and your sister stays a pointed finger."

[player_name] almost laughed. Almost cried. Trust under interrogation lights had become trust under a hunt brief. The romance was whether she could love a badge after the system failed Renny—and whether he could love the woman who still fed a pier secret while choosing between unfinished pier weather and a cold stay that might be self-preservation or another kind of sanding.

"Renny kept a map," she said quietly. "I kept a lie. Owen kept a clerk on speed dial until tip weather made him useful to the wrong people. Hale kept the habit of vanishing. You kept a sealed hallway. Ellison keeps an inbox. Cho keeps bones without a name. Everybody keeps something. The question is which keeping still protects a living hope while you hunt and which keeping only protects me from wanting you back."

Will's pen—he had been writing desk codes even crouched—stopped against the cracked notebook. Respect moved through his face like weather changing. He almost kissed her then—stopped a breath short on purpose—scar nick white under bay light, all weapon and wound. The denial hung as hook. Soft was dead. The clerk had escaped. The hunt was walking. Science stayed careful. The next verb would hurt to leave while Harborwick fog pressed the glass and hope kept breathing beside dread on a lab tray that still refused to say her sister's name.

"Clock," Will said softly. "Hold the bittersweet pier promise unfinished—or stay in the city cold without me. Either way I hunt. Either way you wait through the first hours that matter most to trails. Either way Cho's pending stays a leash we do not cut for comfort. Conjugate, [player_name]."

Outside, chain-link rattled in wet wind. Somewhere east, Marcus Hale was becoming damp history with a coffee habit and a joke about soft nets. Owen Vale's lawyers would call the slip proof of overreach. Press would smell a detective chasing fog while a sister sat inland. Internal would catalogue proximity and then catalogue distance if she chose cold. Nina Solis stayed sealed—pressure deepened by association. Will wore the worse like cologne and still offered her a waiting partnership that might end on pier boards or end as severance.

[player_name] sat between vending coffee and fluorescent future, fingers laced near Will's cracked knuckles without quite taking the hunt from him, remains unnamed, charm probable, sister still missing in the only way that mattered—and the choice sitting between them like unfinished weather: bittersweet pier promise held open in fog, or stay cold in the city without the badge that had taught her how trust tasted under interrogation lights.

"Pick the verb," Will whispered. "Unfinished pier—or cold stay. My hunt either way. Soft partnership as the person who holds the bay, or soft partnership ending because waiting taught you the city is enough without me. Hurt to leave either. Good. Means you understand Layer 9 does not do tidy exits after a clerk becomes weather—and neither does a detective who is about to walk into fog with a scar nick and a sealed past and still wants to finish the kiss we keep parking behind warrants, wires, raids, and now behind a wait."

He stood. Coat. Notebook. Radio. The bay smelled like antiseptic and rain and unfinished trust. Hope argued that Hale would be caught before dawn and Renny's map would still breathe. Dread answered that municipal vanish was a skill Harborwick had taught too well. Choosing pier meant holding an unfinished anniversary promise through the hunt's uncertain return. Choosing cold stay meant keeping the city and cutting Will from the braid while science stayed careful and a killer stayed unnamed because the clerk's mouth had slipped into fog before it could earn Michael Kade or any other mid-level throat. Either verb spent the wait. Neither spent Renny early. Will waited one more breath with the patience of a man who had waited out worse rooms—then he would walk. Attention as a blade laid flat, edge available for the pier road. [player_name] drew a breath that tasted like rust and soap and loyalty's cost, and felt the next ending arrive on the sound of a hunt beginning and a choice that still refused to christen bone.`,
  textHot: `The side door had unlocked itself at the wrong minute, and Marcus Hale had become weather, and [player_name]'s cunt still answered William Akers's last soft check with a filthy pulse she refused to tidy while she sat in a precinct chair that smelled like fear and vending coffee.

Will taped gauze that was not tonight's wound and still felt like consequence—mid-thirties, scar nick pale, grey-green already on the pier road east. Brutal charm locked to inventory. Cracked knuckles whitened around notebook spine. Solis ash smoked without unpacking. Ellison's radio blamed with a unit number. Cho's memo stayed careful: remains unidentified, charm maybe. Science careful. Hope employed. Dread armed. Soft dead into a hunt. [player_name] mid-twenties, thighs tight, Renny's living link, unfinished since warehouse steel and wire alcoves and every almost-kiss parked behind procedure.

"You stay," Will said, voice sex-rough under detective flat. Soft enough for the bay to invent distance. Hard enough that attraction climbed her spine. "I hunt. Hale is municipal vanish. Owen bought him minutes. I float backup. I lean warehouses. I walk every fog until steel finds a throat—or empty pier road finds me instead."

She tasted copper and want. Waiting tasted like loyalty and abandonment with a badge. She wanted to go. She wanted him not to go. She wanted his mouth and hated that she wanted it while a clerk rinsed into damp history. Soap-and-salt when he leaned to check her pulse. Unfinished heat. Mid-thirties to mid-twenties—close enough to burn.

"If I wait," she said, "I hold the bay while you finish what a side door stole."

"Yes." Honest. Comfort refused. His thigh brushed her knee; his hand found her wrist, then—stakeout second, Ellison half-turned—slid under her shirt onto bare ribs because alive was also sex. "You stay reachable. You do not become a second moving target. Ellison hates dead witnesses more than lost clerks. You do not become clearance. Renny does not get a false funeral because my hunt went sideways in a hallway I already dream. And when I come back smelling like rain and failure or rain and a cuff, I drop to my knees between these chair thighs and eat you until the chase and Solis ash are noise under how hard you clench on my tongue."

Ellison in the bay mouth—soft, final. "Hunt weather. Familial contact inland. Cho contested. Invent a corpse in fog and I invent paperwork that ends your badge." Gaze to [player_name]. "Waiting is how soft nets stop becoming tip-calls."

Will crouched so their eyes leveled, late smile wrong—weapon and wound—cock hard under wool he did not apologize for. "Two endings from a wait," he murmured, mouth near enough that her pussy clenched empty. "Hold the bittersweet pier promise unfinished—boards, anniversary fog, hard sentences without tidy hunt stories—and before dawn or after I fuck you against a piling until honesty is just how hard you clench while fog horns speak. Or stay in the city cold without me—apartment, hoodie folded, charm gap aching, case noise without my hands—and I hunt alone while you rebuild alone, soft ending as severance even if your cunt still remembers my unfinished fingers. Both leave Hale weather. Both leave Cho careful. Both leave me hard in every fog I chase because unfinished is how your body tells truth."

[player_name] pictured pier dawn with Will smelling like fog and steel—bittersweet, Renny's poster, then his mouth, then his cock unfinished on purpose until the vow sentences landed. Pictured cold stay—city without badge braid—then the ache of cutting him loose while still wet for a hunt she had authorized by waiting. Either fantasy made her wetter. Either path kept science from baptizing bone for a slip.

"If you take the pier promise," Will said, cracked knuckles on her pulse, other hand shoving into her jeans under soaked cotton without preamble, "I come back when I can and we stand on the boards and say hard sentences—and I finish you quiet enough for festival ghosts." Two fingers slid into slick heat; she gasped; he pumped slow, filthy, precise, thumb on clit. "If you stay cold without me, you keep the city and cut the badge from the braid. I will still want your mouth in every warehouse. Want does not cancel severance. I need you to hear both without sanding either into comfort while Cho's tray stays contested and your cunt drips on a detective about to walk into fog."

She rocked on his hand, forehead to his, Renny's pointed finger and Hale's vanish braided into heat that felt like loyalty's filthy twin. "Renny kept a map," she managed. "I kept a lie. Owen kept a clerk until tip weather. Hale kept vanishing. You kept a sealed hallway. Everybody keeps something." She clenched around his fingers—claiming, demanding. "Pier promise—I wait and hold unfinished boards weather and you repay me when fog gives you back. Cold stay—I keep Harborwick without you even if it kills the braid. I am not inventing purity. I am not inventing a funeral. I am asking which hurt leaves Renny reachable while you fuck the choice into me with stakeout patience."

Will cursed soft, curled until her hips jerked, then stopped—exact, cruel, tender as a threat—withdrew to paint her lower lip. "Not yet. Not until you pick." Grief and sex sharing a body. No gore-porn. Bones unnamed. Clerk escaped. Science careful.

"Clock," he said. "Hold the bittersweet pier promise unfinished—or stay in the city cold without me. Either way I hunt. Either way you wait the hours trails care about. Either way Cho's pending stays a leash. Conjugate while I can still smell your cunt on my hand and Harborwick fog erases the curb."

Before Ellison fully turned back, he walked her into the alcove off the bay and shut the door with his heel. Dropped to a crouch despite hunt clock, despite Solis ash, despite Hale becoming weather, and put his mouth on her—tongue flat, then pointed, sucking her clit with warrant precision. She clapped a hand over her mouth. Whitened knuckles braced her thighs. "Pier means I do this after every hard sentence on the boards," he growled against wet heat. "Cold stay means this is goodbye-shaped even if my tongue still writes your name—I will not pretend severance is soft." He slid two fingers back into her while he licked; she came shaking, vision white. Will stood, wiped his mouth like a statement, forehead to hers. Cock strained, unfinished, deliberate denial. "Solis sealed. Bones unnamed. Hale weather. What does not stay unfinished is the verb."

He boxed her against cold tile, put her hand on his cock through his pants once, let her feel the unfinished claim. "Pier promise means I get your mouth on my throat when I come back from fog and my fingers back in this exact slick while fog horns speak. Cold stay means you save the soft for a city without me and I spend the hunt aching without repayment. Verb. Now. Hold the bittersweet pier promise unfinished. Or stay in the city cold—without Will. Hurt to leave either. Layer 9. Teeth. Consequence. No baptism—just us, a clerk escaped, a wait with a pulse, science still careful, and a choice that might still save what Harborwick failed once—or end the braid clean."

[player_name] sat between vending coffee and fluorescent future, wet jeans, remains unnamed, charm probable—and the choice sitting between them like unfinished fucking: bittersweet pier promise held open through hunt weather, or stay cold in the city without William Akers while Marcus Hale rinsed into fog and Cho's pending still refused to soothe anyone.

Rain thickened against the bay glass like a second recorder. Will paced once more—counting exits, counting what waiting cost when soft had already bought the chain minutes—and then put both hands on the arms of her chair so she was caged in heat and hunt-clock without being trapped. "If you hold the pier promise, I will still be angry in every warehouse and still come back smelling like your decision," he said, voice raw. "Anger does not cancel the braid. If you stay cold, I will still want your mouth when fog cools and I will not get to have it—want does not cancel severance, and severance does not invent Renny on Cho's tray. I need both sentences without comfort while your thighs are still wet from my mouth and Hale is still weather and Ellison is still inventing inland soft as policy."

His cracked knuckles brushed her jaw. Fog horns spoke from the east where the pier road waited. Renny's hoodie ghost folded inland. Charm gap ached. [player_name] pictured him walking into damp history with Solis ash under his charm and her taste still on his tongue—loyalty's filthy twin. She pictured the apartment without his cracked notebook on the table—cold stay as self-preservation that might also be another sanding. Either picture kept science careful. Either picture hurt.

"Pick," Will whispered, late smile cutting wrong, coat already half on. "Unfinished pier—or cold stay. I am still tasting you. That is not in any memo yet. Keep it that way until you choose which ending gets the hours I spend in fog—boards with honesty as jewelry, or Harborwick alone while I hunt a clerk who still thinks soft might hold and hope keeps its impossible job beside dread."`,
  choices: [
    { id: "scene10j", text: "Hold the bittersweet pier promise unfinished", textHot: "Hold the bittersweet pier promise unfinished" },
    { id: "scene10d", text: "Stay in the city cold — without Will", textHot: "Stay in the city cold — without Will" }
  ]
};
