export default {
  id: "scene6k",
  layer: 6,
  title: "Phone ash: forensics from the sink trap",
  text: `Phone ash smelled like melted plastic and Harborwick rain that had tried to put a fire out too late.

Jake Akers set the evidence tray on the back-lab table with a care that looked almost tender and almost like a threat. Mid-thirties. Scar nick pale under fluorescent strip light. Cracked notebook open to a timeline that still refused to print Renny's name on bone. Soft net had ended in an alley bin—lighter kiss, plastic warp, Owen Vale feeding a phone to panic—and now forensics had followed the ash where guilty men always hoped water would finish what fire started: down a drain, into a trap, into the kind of black sludge Dr. Lila Cho's people called recoverable if you loved dirt enough.

[player_name] stood opposite him with Renny's absence pressed under her ribs and the kept secret pressing harder—pier night, Owen, the stranger, seven years of scrubbed silhouette that ash could not undo and might yet illuminate. Unidentified partial remains still waited upriver on Cho's schedule: age range compatible, charm *like* Renny's missing bracelet piece, lab ID pending. Hope and dread shared the lab air with solvent and burnt coffee. The bones were not Renny until science said so. The SIM chip resting in a sterile dish was not confession until messages spoke.

"Sink trap," Jake said without looking up. "Owen's kitchen. Unit pulled it after the bin cooled. Ash in the alley was theater. What he rinsed afterward was insurance. People who burn phones still wash their hands like ritual can erase metadata." His late smile arrived and died in the same breath—brutal charm banked for a room that smelled like melted board and soap scum. "Cho's tech pulled a partially intact nano-SIM from the trap grease. Not a miracle. Not a resurrection. A maybe with contacts. We image what survives. We do not invent Renny's funeral out of a chip that might only prove your stepfather talks to clerks after midnight."

Captain Mara Ellison had already texted twice. Jake showed [player_name] neither message. He showed her the dish instead: black flecks, a silver square smaller than a fingernail, a label that read like patience winning a round against fire. Whitened knuckles flexed around a pen. When Ellison's name almost pulled a Solis-shaped flinch across his mouth—*not another early push, not another hallway*—he swallowed it. Hint only. Sealed file still sealed. his ex-partner taught him what ashes cost; he was trying to dig this ash without making the same weather.

"Deny the leak and dig deeper," Jake said quietly, as if finishing a bridge conversation that still lived between them. "Or follow a warehouse lead and find yourself here anyway, because burned phones and red doors rhyme in Harborwick. Either path put your hands on this table with mine. Soft died. Forensics is how soft's corpse still talks."

[player_name] tasted copper and solvent. Mid-twenties and done pretending ash was only Owen's problem. "Will the messages name her?"

"They will name whoever he reached while my unit watched his porch light perform innocence." Jake finally met her eyes—grey-green, tired, hungry for a break that would not eat them. "City clerk initials showed up once in Renny's teenage shorthand on a pier map. If this SIM loves the same alphabet, we get a thread. If it loves something else—smuggling, debt, a mid-level shadow Ellison already smells—we get a different knife. Charm probability upriver stays elevated without confirmation either way. I will not let a text string baptize those bones."

Attraction hummed unwanted under procedural dread: his competence, the dangerous care of refusing to christen remains, the way his cracked knuckle brushed hers when they both reached to steady the tray. Mid-thirties to her mid-twenties—close enough to burn, far enough that the badge still felt like a different country. She wanted his steadiness and hated that she wanted it while Renny's fate stayed contested silt and rumor.

A tech in a gown nodded from the doorway. Imaging spit progress onto a screen: fragmented timestamps, partial numbers, one string that survived grease better than fire—*call M if soft*—and a contact stub that resolved, after Jake's quiet swear, toward a Harborwick municipal directory entry half-redacted by politics and half by damage. Clerk. Not a name that wore Renny's laugh. A bureaucracy throat that might have swallowed a teenager's pointing finger.

Jake's pen scratched. Rain freckled the high lab window. Somewhere a foghorn rolled inland like the river clearing a throat that still had no sister's name. [player_name] thought of Owen's dryer-sheet kitchen, of the alley flare, of Ellison's clearance hunger, of a silver bracelet gap like a missing tooth on a dresser across town. The SIM dish winked under strip light. Hope still had a throat. Dread still had teeth.

The gown tech left them alone with the screen's glow and the trap's black history. Jake walked the perimeter of the table the way he walked interview rooms—counting exits, counting lies, counting what soft nets cost when they burned. [player_name] watched his shoulders under charcoal that still held alley rain. Attraction was a stupid animal to bring into a forensics bay, and it came anyway: the scar catching strip light, the sleep-deprived set of his mouth, the way he treated a nano-SIM like it might bite and like it might finally tell the truth about a festival night Harborwick preferred to forget.

"Walk me through what Owen rinses when he panics," Jake said. Not a quiz. A partnership verb. Full dig meant her eyes on the same grease he loved.

"Phone glow in the alley," [player_name] said. Voice held. Barely. "Bin. Fire. Then—if he is the man who made breakfast with clean hands for seven years—he goes inside and scrubs. Sink. Soap. Maybe pieces he snapped first. Maybe a SIM he thought water would erase better than flame." She swallowed. "I kept him off a statement. I know how he cleans a story. I did not know how he cleans a chip."

Jake nodded once. Respecting the line even while his eyes said he wanted to put her somewhere soft after solvent. "Ellison will ask if family interference taught him the rinse. You standing here smelling like porch weather and guilt is not interference. It is cooperation under fluorescent light that happens to hurt. Remains still unidentified. Charm still only maybe. I did not pull a sink trap because we buried your sister. I pulled it because soft ran out of road and ash is still a map if you refuse to flinch."

He turned the dish a quarter inch, as if angle could coax more contacts from grease. Outside, Harborwick warehouses hunched in fog. Inside, the clock hummed like every precinct clock that had ever watched a familial contact choose protection over pages. Renny's hoodie lived folded inland. The silver bracelet gap lived in a dish. Upriver silt kept its silence while a different silence—Owen's after-midnight clerk reach—began to crack on a lab monitor.

Jake's pen paused. "When my old partner and I—" He stopped. Charm armor sliding. Wound showing a tooth and then hiding. "When a raid goes sideways, people rinse what they can. Partners take weather. Kids in hallways pay for urgency dressed as care. I am not dumping that sealed file on your SIM dig. I am telling you why I will not rush an ID or a cuff to soothe Ellison's inbox while this chip still has a throat." His grey-green eyes found hers. "Hope stays employed. Dread stays honest. You stay in the room."

"Ellison wants this bagged and briefed before lunch," Jake said. "She wants a narrative that soft failure became hard progress. She distrusts family witnesses who arrive smelling like porch rain and guilt. She distrusts me when results leave fingerprints on more than evidence bags." His jaw worked. "Two doors from this tray. We trace the SIM messages—every fragment, every clerk ghost, every after-midnight reach—into Layer Seven with gloves and warrants and whatever courage you have left after watching plastic die. Or we choose each other mid-war—break open what obstruction and soft nets and tip weather did to us—before the clerk dig eats the last hour we have for anything that is not badge work. Trace keeps the hunt sharp. Break-open keeps the romance from becoming another sealed silence I already know how to wear."

He did not touch her mouth. The almost hung unfinished on purpose—hook as craft. Solvent stung [player_name]'s eyes. Jake's notebook spine cracked when he closed it, overuse showing like a second scar. Behind him the screen glowed with partial truths: M, soft, clerk, timestamps that refused to resurrect a girl and refused to bury her.

"Clock," Jake said softly. "Trace the SIM messages—or choose me mid-war and break open. Either way ash already spoke. Either way Cho's bones stay unnamed tonight. Pick the hurt that keeps truth reachable while Harborwick fog erases the alley where soft burned and a sink trap tried to finish the job."

Jake angled the sterile dish so the chip caught fluorescent light like a bad star. "Trace the SIM messages—or choose me mid-war and break open. Ash already spoke. Cho's bones stay unnamed tonight either way." Phone grease still ghosted his cracked knuckles. [player_name] looked from the tray to his hunger-and-warning face and felt the choice land like a second lighter—careful, consequential, still capable of fire. Trace meant walking clerk-ghost grammar into Ellison's weather while her body still hummed from how close he stood. Break open meant spending the want the alley fire had not burned out of them, mid-war, while hope kept its impossible job beside dread. Renny's fate contested. Romance unfinished under lab light. Harborwick fog erased the bin where soft had tried to die, and neither verb would finish what his mouth was still refusing to take.`,
  textHot: `Phone ash smelled like melted plastic and Harborwick rain, and [player_name]'s body answered the evidence tray with a pulse she refused to call pure while Jake Akers set forensics down like a man laying out knives and foreplay on the same cloth.

Back-lab strip light. Solvent. Burnt coffee. Soft net's corpse talking from a sink trap: Owen Vale's kitchen grease yielding a nano-SIM fire had failed to erase, unit gloves loving dirt the way Jake's cracked knuckles loved a hunt. Mid-thirties. Scar nick pale. Notebook open to a timeline that still refused Renny's name on bone. Cho's unidentified remains still upriver—charm maybe, age range ugly with hope, ID pending—and none of that science stopped the thick idle threat Jake's cock made in jeans while ash became recoverable. Brutal charm banked for a room that smelled like melted board. His grey-green eyes dragged over [player_name]'s mouth, her throat, the rise of her breasts under her sweater, then forced themselves to the sterile dish as if professionalism were a cock ring he was choosing to keep on for the girl's sake and for Ellison's cameras.

"Sink trap," he said, voice low enough to drag along her spine. "Ash in the alley was theater. What he rinsed was insurance. Cho's tech pulled a chip from grease. Partially intact. Contacts maybe. We image. We do not invent your sister's funeral out of municipal after-midnight texts." His hand covered [player_name]'s on the tray rim—heat, calluses, whitened knuckle—and the contact shot straight between her thighs before either of them pretended it was only about steadying plastic. "Deny-and-dig put you here. Warehouse lead put you here. Burned phones and red doors rhyme in this city. Soft died. Forensics is how soft's corpse still fucks the timeline forward."

[player_name] tasted copper and solvent and want. "Will the messages name her?"

"They will name whoever he reached while I watched his porch light." Jake stepped behind her as a tech nodded from the doorway, chest to her back, mouth near her ear, gun oil and soap. Imaging spit fragments onto the screen—*call M if soft*—clerk stub half-redacted, bureaucracy throat that might have swallowed Renny's pointing finger. "Charm upriver stays maybe. Bones stay unnamed. You stay wet against my zipper while we pretend this is only a lab." His palm slid under her sweater onto bare ribs, thumb stroking the underside of her breast until her nipple peaked hard against his knuckles. "Ellison wants this bagged before lunch. I want my fingers in you before I forget I am supposed to brief a captain instead of finish what ash started in my blood."

She shuddered. He opened her jeans with detective efficiency under the counter line the doorway could not fully see, slid into panties where she was shamelessly slick from fallout and competence and the filthy mercy of a man who refused to christen remains with a sister's name. Two fingers pushed in slow; she clenched; he groaned like confession and pleasure were one sound. "There. That is not theory. That is wet for a detective holding phone ash and your waist at the same time. Grief and sex can share a body. Do not tidy it. Do not eroticize the bones—Cho's tray stays contested—but do not pretend grease and fire made you celibate."

The gown tech left. Jake walked the table perimeter and then boxed [player_name] gently against the counter edge with his hips—pressure, denim, the thick line of his cock a procedural problem neither of them filed. "Walk me through his rinse," he murmured, mouth on her jaw, not the center kiss, denial as craft. "You know how he cleans a story. Tell me how he cleans a chip while I keep my hand where honesty lives."

"Alley fire," she managed, cunt clenching around the fingers he had not fully withdrawn. "Then sink. Soap. Panic ritual. He snaps what he can. He washes what he thinks water erases." Her voice shook. Held. "I scrubbed his pier silhouette for seven years. I know the grammar of clean hands."

"Good." Jake's thumb circled her clit with stakeout patience, cruel and tender. "Ellison will smell family in this bag. Let her. You standing wet for the dig is not obstruction—tonight. Soft already burned. Remains still unnamed. Charm still maybe. I did not pull a trap because we buried Renny. Soft ran out. Grease talks. So do you when my fingers ask better questions than a captain's memo."

He turned her enough to see the screen's clerk stub over her shoulder, chest sealed to her back, free hand guiding hers to press against his cock through jeans. "When Solis and I—" He stopped against her throat, wound leaking, sealed file still sealed. "Raid weather. Hallway. Kid who should not have been there. I wear charm so nobody asks. You ask by soaking my wrist in a lab while ash cools. I will not dump the whole hallway on your dig. I will let it haunt the clerk thread beside your tip weather and my hard-on. Hope stays employed. Dread stays honest. You stay open on my hand until the verb is chosen."

On the screen, timestamps resolved in ugly fragments. Jake fucked the choice into her with stakeout patience turned filthy—curl, thumb on clit, forehead to her hair—while his other hand kept the notebook angled like a shield. "his ex-partner taught me what happens when I push early and call the smoke justice," he said into her throat, wound leaking through charm in pieces, sealed file still sealed. "This dig is not early. Soft already burned. Tracing messages is patience with a hard-on. Breaking open mid-war is admitting the romance is part of the case whether Ellison likes the optics or not."

He added a third finger until she cried out soft against her own wrist. "Two doors from this tray. Trace the SIM—every clerk ghost, every after-midnight reach—into warrants and gloves, and I keep tasting you between briefings because compromised is how I stay human after ashes. Or we choose each other mid-war—break open obstruction and tip weather and soft nets—before the clerk dig eats the last hour that still belongs to us, and I put you on this back-lab counter after hours when the gown tech is gone and finish what my fingers started with my mouth." He withdrew glistening fingers to paint her lower lip. "Not yet. Not until you pick."

He pressed her palm to his cock through jeans—thick, hot, brutal honesty—and rolled once into her fist. "Feel what ash forensics does to me. Soft dead. Hunt live. Want past professionalism. Trace the messages—or break open with me. Either way the chip already spoke. Either way Renny stays a question mark on Cho's table tonight."

Rain freckled the high window. A foghorn rolled inland. Jake's free hand cupped the back of her neck, grounding, thumb stroking her hairline while his other wrist shone with her slick under fluorescents he did not wipe. "sealed-ash and your tip weather and Owen's lighter all live in my sealed places," he murmured. "You get hints. You do not get the whole hallway while a SIM still holds clerk ghosts. You get this: I will dig with you either way. I will be angry either way. I will put my mouth on you either way if you ask with the same courage you used to stand in an alley while plastic died. Murder stays plot. This heat advances trust or it advances nothing."

She rocked once against his hand despite herself; he hissed and stopped her hip with exact control, unfinished climax held like evidence in a bag. "I could finish you against this tray," he whispered. "I will not. Not until the verb is chosen. Wanting you past professionalism does not make a false Renny funeral holy and it does not make obstruction cute. Bones stay unnamed. Charm stays maybe. Hope stays employed. You stay wet on my hand and still have to conjugate."

[player_name] tasted copper and herself and solvent ghosting off the dish. Festival fog lived behind her eyes: Renny's laugh, funnel-cake sugar, Owen's silhouette, a teenager's map with pencil Xs, seven years of protection that had become a different violence—and tonight's ash finishing one sentence so another could start in grease. Jake's scar nick brushed her temple when he leaned. His late smile arrived wrong, all weapon and wound, the brutal charm that had first made her want him under procedural pressure.

He zipped her halfway, adjusted her collar with cuff-tenderness the SIM dig had not required in steel, scar nick white under strip light. The screen glowed M and soft and clerk. Ellison's unread texts burned in his pocket like a second lighter.

"Clock," Jake said. "Verb. Trace the SIM messages—or choose me mid-war and break open. Pick the hurt that keeps truth reachable while I can still smell your cunt on my hand under lab fluorescents and phone ash cools into a thread that still will not name your sister without earning it."

Jake turned her from the tray with two fingers at her jaw—gentle, absolute—and the touch shot straight to her cunt. "Trace the SIM—or choose me mid-war and break open," he said. "Pick the hurt that keeps truth reachable while phone ash cools and I can still smell your wetness under these fluorescents." Grease and soap and her own scent lived on his cracked knuckles. [player_name] pressed her thighs together and felt how ruined she was from proximity and evidence alone. Missing charm. Unidentified bones. Sink-trap chip. Jake Akers with badge honest, charm scraped raw, cock still arguing against the patience the lab required. Trace meant clerk-ghost grammar with her body unfinished. Break open meant spending the want the alley fire had not burned out—mid-war, mid-need—while hope kept its impossible job beside dread. Neither verb would finish what his mouth was still refusing; both would leave her aching toward Layer Seven with Renny still unnamed.`,
  choices: [
    { id: "scene7k", text: "Trace the SIM messages", textHot: "Trace the SIM messages" },
    { id: "scene7l", text: "Choose Jake mid-war — break open", textHot: "Choose Jake mid-war — break open" }
  ]
};
