export default {
  id: "scene3b",
  layer: 3,
  title: "Pier Walkthrough",
  text: `Harborwick pier wore rain like a second skin. Boardwalk planks shone black under the festival ghosts—empty string-light hooks still screwed into warped beams, a shuttered funnel-cake stand with its menu board bleached to ghosts of prices, chain-link rattling where the wind came off the water in salt-cold fists. The foghorn called low and wrong, the same note [player_name] heard in bad dreams. William Akers walked half a step ahead of her, coat collar up, cracked notebook tucked away for once, as if paper could not hold what the place still remembered and he was done pretending it could.

They had left the precinct before Captain Mara Ellison could turn the formal interview into a stamped performance. From burnt coffee and bolted table to this: wet wood, diesel braided through fog, yellow-tape memory ghosting a stretch of rail where Renny—sixteen, restless, silver charm bracelet already missing its tiny anchor by dusk—had argued about staying out later and then become absence. The upriver remains were still unidentified. Dr. Lila Cho's lab had not named anyone. Age range broad. Charm probability not gospel. Hope and dread shared [player_name]'s ribs with every careful step, mid-twenties and suddenly aware that leaving with Will had been its own kind of confession.

Will stopped where the boardwalk widened into the old carnival throat. Mid-thirties. Sleep bruised under his eyes in colors the rain could not wash out. Drops beaded at his throat where the collar had loosened, a pulse point that looked too human for a man who used charm like a blade. That half-smile arrived without humor—brutal, practiced, meant to make a witness lean closer before she noticed the edge. Not clean-cut. Not the detective recruitment posters promised. Attraction to him tasted like touching wet live wire and calling the burn curiosity.

"Walk it with me," he said, voice soft enough to feel against the inside of a wrist. Soft was worse on the pier; soft made the black water sound closer. "Not for Ellison's report. For the night you keep replaying when the horn calls. Show me where Renny stood. Show me where you stopped looking. Show me the angle your old statement sanded smooth."

[player_name] pointed—funnel-cake stand first, then the rail where teenagers leaned to dare the drop, then the darker cut toward the warehouses where fog thickened into architecture that forgave nothing. She talked because silence here felt like agreeing Renny was already among the dead, and the remains were not confirmed Renny, would not be confirmed under rain and Will's attention no matter how badly rumor wanted a name. She talked about the borrowed hoodie, the missing charm, the crowd swallowing kids the way Harborwick always had. Will listened with his whole body angled toward her, rain darkening his shoulders, gaze tracking her mouth as carefully as her hands, as if lips were another kind of evidence.

A kid in a soaked hoodie cut through a gap in the chain-link—fourteen, maybe fifteen, laughing into a phone, sneakers slapping wet plank. Will's whole frame flinched. Not theatrical. Partner-flinch. Raid-flinch. Something sealed and ugly crossing his face before the detective mask snapped back into place. His mouth shaped a syllable that might have been a name—So— and killed it so cleanly the murder left a cold spot in the air. He watched the kid until fog took the laughter, and [player_name] understood without a briefing that somewhere there had been a hallway, a child who should not have been there, a partner-shaped absence, an IA folder stamped closed that William Akers would not open for a civilian sister standing in pier rain.

"You good?" she asked, because the almost-name had teeth and pretending otherwise felt like another omission.

Will's smile came back wrong and charming, weapon first, wound second. "Old building muscle. Ignore it." He did not offer Nina. He did not finish Solis. He offered the pier again with weaponized patience, the mid-thirties hunger of a man who collected other people's unfinished stories because his own were locked behind seals he enforced on himself. "Owen Vale's statement puts him across town that night. Your old statement agrees by omission—clever, loyal, corrosive. The pier disagrees with both if your eyes were telling a truth you never wrote down. I did not bring you here to trap you. I brought you here because traps work better in rooms with clocks. Out here, the water does half my job."

Rain thickened into sheets that silvered the rail. [player_name] tasted salt and the burnt-coffee ghost of the precinct cup still coating her tongue. Will stepped closer, close enough that his coat brushed her sleeve, close enough that want arrived braided with fear—wanting the man who could break her family with one accurate sentence, wanting him while Renny's absence pressed the fog like a third body that refused to resolve into either corpse or reunion.

He walked her to the stretch of water construction chatter had loosely linked to the upriver find. Not a proven dump site. Not a grave labeled sister. Debris paths. Currents. Maybes drawn in rain. "Cho will call when timing and age range tighten," Will said, tapping the rail once with that pale-lined thumb she had noticed under fluorescents. "Until then we do not bury Renny under a probability, and we do not pretend the charm in that evidence bag is sentimental junk. You left the precinct with me instead of waiting for Ellison's stamp. That means you still want truth more than clearance. Good." His voice dropped into something that was not only detective. "Truth on a Harborwick pier looks like this—wet, unfinished, close enough to kiss if you are reckless, close enough to ruin if you are honest."

The last words landed between them like a match on damp paper that somehow still caught.

[player_name] felt the almost before it wore a name: Will turning into her, rain bright on his mouth, eyes holding want and case in the same dark look. Brutal charm leaning toward something procedure could not bill as overtime. His hand rose toward her jaw—work-rough, careful, dangerous—and stopped short of skin, offering the last inch the way some men offered a loaded choice. Behind him the foghorn called again. Somewhere a chain-link panel slapped metal on metal. The hallway kid's laughter was gone. Only Harborwick weather, seven years of silence, and a detective who flinched at children in doorways he would not explain.

"We can finish this walk clean," Will murmured. Rain ran from his hair into the corner of that half-smile. "Or we can let the weather do something stupid before Cho's next drip lands on my phone and turns this into science again. I am not a soft place, [player_name]. Men who learn charm as an exit wound do not become soft because a sister went missing on their watch—or anyone's. But I am here. And you are looking at my mouth like the case can wait ten seconds without collapsing."

She could let the almost-kiss happen—tilt into rain and danger, taste whatever honesty lived under his soft voice, give the night a different unfinished sentence while the remains stayed unnamed. Or she could break the heat, demand Cho's update on the unidentified remains, put forensics between their bodies before want wrote a confession neither of them had earned on any record Ellison would accept.

She could still smell Renny's cheap festival perfume in memory—something peach and plastic that clung to the borrowed hoodie even after washes [player_name] had given up counting. The hoodie waited folded in a drawer inland; the pier kept the night. Will did not rush her through the geography. He let her stand too long at the rail, let rain soak the cuffs of her jeans, let the silence do detective work his notebook usually handled. When she finally said Owen's first name without attaching a location, Will's eyes sharpened—not triumph, something hungrier and sadder, as if every withheld coordinate cost him personally.

"You do not have to love me to use me," he said, almost gentle, which made it worse. "You only have to decide whether Renny gets the version of you that protects Owen, or the version that finally points at the pier." He tipped his head toward the warehouse cut. "I have chased worse ghosts through uglier doors. Some of those doors still show up in my sleep. That does not make me righteous. It makes me useful. Stay useful with me."

A freighter horn layered under the foghorn, deeper, farther. Harborwick stacked its noises like alibis. [player_name] wiped rain from her lashes and found Will already watching the gesture as if it were a tell. Maybe it was. Maybe everything was, around a man who had survived sealed consequences and still somehow stood in weather offering choices instead of cuffs.

"Cho's phone stays on," he added. "If you would rather hold forensics than my hand, say so before I mistake your breathing for an answer."

Will waited in the pier rain with his hand still hovering, partner-ghost and sealed IA shut behind his eyes, notebook forgotten against his ribs, mid-thirties and explicitly not safe. [player_name] felt the fork settle into wet wood and bone: heat or science, mouth or ME, the almost or the remains that still refused to wear Renny's name. The horn called once more. The rail under her palm was cold enough to hurt. Will did not drop his hand. He did not take the inch. He left the choice where brutal charm always left it—close enough to burn.`,
  textHot: `Rain found [player_name]'s skin before manners could intervene—cold rivulets racing under her collar, salt on her tongue, boardwalk slick beneath her boots—and then William Akers's heat found everything manners could not save. He walked half a step ahead in a coat gone black at the shoulders, mid-thirties danger with a half-smile that knew how to cut and how to make the cut feel like being chosen. Harborwick pier. Festival ghosts on empty string-light hooks. Funnel-cake stand shuttered. Chain-link rattling like loose teeth. Foghorn low enough to vibrate through her belly into the shameless pulse between her thighs.

They had left Ellison's fluorescents and the bolted interview table for this: wet wood, diesel in the fog, Renny's teenage absence pressed into every plank like a bruise you could walk on. Upriver remains still unidentified. Charm still only *like*. Hope and dread slicked through [player_name] alongside want, mid-twenties and furious that grief and arousal could share a nervous system. Will stopped in the old carnival throat and turned that soft voice on her—soft as a mouth at the ear, soft as a threat wearing patience.

"Walk it with me. Not for the report. For the night you keep replaying when the horn fucks your sleep. Show me where she stood. Show me where you stopped looking." A beat. Rain on his lashes. "And try not to stare at my mouth while you do it, or I stop pretending this walkthrough is only about Renny."

She pointed—stand, rail, warehouse cut—voice holding while her body sold her out: nipples tight from cold and from the way Will's gaze dragged her throat when she swallowed, heat pooling low as if the pier itself had fingers. He tracked her hands, her mouth, the rain disappearing into the V of her shirt. Brutal charm. Not clean-cut. Attraction like a live wire in standing water. She wanted, traitorously, to know what that pale line near his thumb would feel like drawn along her lower lip while the case waited.

A kid in a soaked hoodie slipped the chain-link gap—fourteen, laughing into a phone—and Will flinched hard enough that [player_name] felt the jolt in her own cunt, sympathetic and startled. Partner-flinch. Raid-flinch. His mouth almost shaped Solis—Nina's surname half-born—then murdered it so completely the air went hotter for the effort. Hallway ghost. Sealed IA. A child who should not have been in a doorway when a raid went wrong. He stared until fog ate the kid and rebuilt his smile like buttoning a coat over a gunshot.

"You good?" she asked, pulse shameless between her legs.

"Old building muscle. Ignore it." No IA bedtime story. Only the pier and his body angling closer until rain-on-skin and male heat filled her head, burnt-coffee memory from the precinct still on both their breaths. "Owen's statement puts him across town. Yours agrees by omission. The pier disagrees if your eyes told truth you never wrote. Say it out here where the water can hear—or keep withholding and let me want you anyway, which is a filthier interrogation than anything Ellison greenlights."

His coat brushed her breast through wet fabric when he shifted to the rail. Accidental only if she lied to herself. Heat spiked down her spine into slick wanting grief could not cancel and Renny's unresolved fate somehow made worse, sharper, more alive. Will showed her the water stretch loosely tied to the upriver find—currents, debris maybes, not a sister tagged and filed. "Cho calls when timing tightens. Until then we do not bury Renny under probability." Voice dropping into the register that lived behind her navel. "You left the precinct with me. Truth on a pier looks like this—wet, unfinished, close enough to kiss if you are reckless enough to put your mouth on a man who flinches at hallway kids and will not tell you why tonight."

The almost arrived as frank bodily honesty: Will turning into her, rain bright on his mouth, hand rising to her jaw and stopping short—the last inch a filthy question written in heat. [player_name] leaned a fraction without voting yes out loud, thighs slick, breath short, cunt clenched around nothing. She wanted that palm on her face, throat, waist; wanted it under the wet shirt, fingers cold then hot on bare skin; wanted his thigh notched between hers against the rail while the foghorn covered the sounds she would make. She also wanted Cho's unanswered science shoved between their bodies before want wrote a confession on her tongue that Ellison could smell through glass miles inland.

"We finish this walk clean," Will murmured, sharing breath, forehead nearly tipping to hers, "or we let the rain do something stupid before Cho's drip hits my phone and turns this back into bone timelines. I am not soft, [player_name]. Charm was an exit wound long before it was a badge trick—Solis—" He cut his own almost-name again, jaw tight, then pushed through on want instead of history. "Men like me do not become safe because your sister vanished. But I am hard in this rain looking at you, and you are staring at my mouth like ten seconds of stupid might unknot seven years of silence. Let the almost-kiss happen—taste rain and danger, let me learn the shape of your breath—or break the heat and demand Cho's update on the unidentified remains. Put forensics between my cock and your grief before we make a mess the file cannot hold."

Chain-link slapped. Foghorn called. The sealed raid stayed sealed. Peach-plastic ghost of Renny's festival perfume rose uninvited, sweet against the salt, and the sweetness made [player_name] ache harder—grief and want braided so tight she could not pull one thread without cutting the other. Will did not fill the silence with procedure. He let rain sheet between them until her jeans clung and her shirt mapped every shiver, until standing still became a kind of undressing. When Owen's name left her mouth without a map pin, Will's pupils blew wider, hunger and sorrow sharing a face she wanted to taste and flee.

"You do not have to love me to use me," he said, soft enough to lick. "Decide whether Renny gets the you that shields Owen—or the you that points at this rail while I am hard enough to be honest about it." His coat opened slightly in the wind; she caught the gun's disciplined shape and, under it, the human heat that made the gun irrelevant to what her body was negotiating. "I have gone through uglier doors. Some still visit. Sealed ones. That does not make me safe to kiss. It makes me a bad idea with excellent timing. Be a bad idea with me for ten seconds—or put Cho between us like cold glass."

A freighter horn rolled under the foghorn. The stacked sound vibrated through the rail into her palms and down into the slick heat she could no longer blame on rain alone. Will watched her wipe her lashes and looked like he wanted to do it with his mouth. Maybe he did. Men with sealed IA folders still wanted. That was the other terror.

"Phone stays on for Cho," he murmured, thumb hovering near his pocket without retreating from her jaw. "Hold forensics instead of my hand if that is the loyalty you can live with. Say it before I read your pulse as permission."

Will's hovering hand offered heat without demand, teeth under the offer, mid-thirties and explicitly unsafe, and [player_name]'s body pulsed once, hard, voting for mouth and rain even as loyalty reached for the ME's unfinished science and the hope that unnamed remains were not Renny. She imagined saying yes to the inch—his mouth crashing into hers, teeth and rain, his thigh forcing hers open against the rail while the foghorn covered the broken sound she would make into his coat. She imagined his hand finally leaving the hover to cup her through wet denim, pressure filthy and precise, while somewhere Cho's unanswered timeline waited like a conscience. The imagining left her dripping, furious, alive. Will's eyes said he could smell the decision forming. Brutal charm did not need to touch to finish the interrogation; it only needed to wait while her body wrote the report his notebook could not.

"Last breath before you choose," he whispered, lips nearly at hers, Solis-ghost sealed, partner-flinch already folded away into whatever men did with sealed guilt. "Kiss or Cho. Heat or the unidentified. I will hate neither answer. I will feel both in my cock either way—fair warning from a man who knows how badly soft voices can lie, and how badly you want this lie to be true for one wet, reckless, case-breaking minute on this cold Harborwick rail before either of us has the good sense or the strength to stop."

The fork was wet wood, cold rail, shameless ache: kiss or Cho, almost or evidence, Will's brutal charm or the drip that might yet spare or shatter what hope she had left.`,
  choices: [
    { id: "scene4c", text: "Let the almost-kiss happen in the pier rain", textHot: "Let the almost-kiss happen — taste rain and danger on his mouth" },
    { id: "scene4d", text: "Break the heat — demand Cho's update on the unidentified remains", textHot: "Break the heat — demand Cho's update before his mouth ruins the case" }
  ]
};
