export default {
  id: "scene9d",
  layer: 9,
  title: "Quiet deal: seal parts of the file",
  text: `The quiet deal lived in Captain Mara Ellison's office after hours—burnt precinct coffee, rain needling Harborwick glass, sealed paper that outlived people and sometimes outlived honesty. [player_name] sat in the chair that always felt like a softer interrogation while William Akers stood by the window with his cracked notebook closed, mid-thirties charcoal open at the throat, scar cutting his left eyebrow, grey-green eyes watching Ellison's tablet the way a man watches a fuse he has agreed—against his nature—not to light outdoors.

Sealing parts of the file meant collateral stayed collateral: certain witness names softened, certain Solis-adjacent IA shadows left association smoke instead of a dig, certain Owen Vale details bargained into supervised quiet rather than full-blade circus. The chain still existed. Warehouse C still had marks. Clerk M.K. still had a hunt. Renny's journal spine still named what a teenager had seen. But daylight would be incomplete on purpose—political weather management dressed as mercy, bittersweet cost dressed as peace.

"You already know the fork," Ellison said, not unkind, not soft. "Quiet reseal—parts reburied that still cost too much to air, city metrics cooled, Akers's closeness framed as witness-preservation rather than romance. Or soft rebuild around the sealed page—love that admits incompleteness, healing that itches, no circus. Either way Cho's unidentified upriver remains stay *pending* in every public sentence. Charm probability is not an ID. I will not have this precinct invent a funeral for clearance numbers. Hope stays grammatically allowed. Dread stays honest. The seal is about collateral and politics, not about lying that Renny ran forever."

Will's cracked knuckles flexed against the window sill. When Ellison's gaze flicked—almost naming Nina Solis fully, almost opening the hallway—Will did not flinch for the glass. The dark past hummed under his badge like a second radiator. Hint deepening into pressure he was choosing to leave partly sealed tonight. Brutal charm filed down to something quieter than press-storm velvet: attention as a blade laid flat on paper. "I hate this deal," he said plainly. "I am still signing the parts that keep a kid's bones from becoming headline theater before science speaks. Renny—teenager when she vanished, missing seven years—deserves honesty. She does not deserve a circus that christens remains because sealed pages make captains nervous. [player_name] chooses which quiet ending we live inside. I stay for both. I will not pretend sealed does not cost."

[player_name] tasted copper and pier salt that had followed them inland from earlier warehouse weather. Mid-twenties shame shared the office with mid-thirties hunger for clean pages Will did not trust quiet to write. She had kept Owen off the official statement for seven years. Hope and dread still shared the doorway. Lab ID still pending. Charm upstairs still only *like*. The remains were not Renny until science said so. The seal would not change that. The seal would change how loudly Harborwick got to scream about everything else.

Owen's name sat on the tablet in lesser-count language—usable, ugly, supervised. Not full bury. Not full daylight. Ellison slid the signature tabs across. "Akers signs investigating. Familial witness initials the seal acknowledgment. Owen's counsel already initialed the quiet clauses. You do not get to pretend this is the same as blowing it open. You also do not get to pretend silence failed Renny for nothing if you use the seal to bury the chain entirely—because I will not let you. Chain stays. Circuses softens. That is the deal."

Will crossed from the window and stood behind [player_name]'s chair without touching—heat at her shoulders like a claim Ellison would catalogue anyway. "If you reseal what still costs too much," he said quietly, for her more than for the captain, "I will not call you coward. I will call you a woman who knows some pages burn the living without warming the missing. If you heal softly around the sealed page, I will hold the itch with you and not demand a purity I did not earn when I kept my own sealed file. Solis took a fall I ordered into being. I kept a badge. Quiet is a language I speak fluently and hate. Pick the ending this office gets to keep."

Ellison's tablet chimed. Somewhere down the hall a foghorn rolled through rain-needled precinct windows, lonely and low. Attraction hummed unwanted under sealed weather: the sleep-deprived set of Will's shoulders, the dangerous care of refusing to baptize bone for metrics, the mid-thirties heat of a man who would stand in incomplete daylight with her mid-twenties mercy and call it partnership if she asked without lying about the cost.

They signed in fluorescent quiet. Pen scratch. Paper smell. Will's cracked knuckles brushed [player_name]'s when he handed the pen—heat, calluses, a partnership pulse the seal could not erase. Ellison stacked the sealed tabs like a woman burying live wires under carpet and calling it safety. "You two are free to leave through the side stair," she said. "Press pack is thinner after midnight. Do not make me regret the quiet by fucking in my hallway. And Akers—Solis stays sealed unless a judge says otherwise. Association smoke is not subject matter. Do not bleed your old hallway into my cold case for romance points."

Will's jaw flexed. He did not dump the hallway. Ash stirred. Teeth showing. "Understood," he said, and the word cost him.

The side stair smelled like rain on concrete and floor wax, the same ugly clock hum as interview rooms leaking through a duct. Will stopped one landing down, grey-green eyes on [player_name]'s mouth, notebook still closed like a man who had run out of logistics and into want. "Quiet resealed means parts stay buried and the bittersweet cost lives in our bed," he said. "Soft rebuild means the sealed page heals slow and we refuse to let incompleteness become another pier-night silence. Both leave Cho's *pending* intact. Both leave Renny a pointed finger and a journal until science grows a spine. Both leave me wanting you in a way the seal cannot make decent. Choose before Ellison's quiet starts feeling like the old cowardice with better stationery."

[player_name] stared at the rain-needled stairwell glass, toward the upriver stretch where unidentified remains waited without a name, toward Renny's room where a charm that was only *like* still winked in a drawer that smelled like absence. Hope still had a throat. Dread still had teeth. Choosing quiet resealed meant bittersweet cost as climate—parts reburied, city quieter, love asked to endure what daylight did not get. Choosing soft rebuild meant healing around the sealed page without calling the seal a second kept secret that failed a sister—Will and her in Harborwick weather that admitted incompleteness as honesty rather than protection theater.

They walked the side stair in fluorescent quiet that felt louder than any press storm. Ellison's sealed tabs upstairs were already becoming city weather of a different kind—cooler metrics, softer circuses, chain still named in rooms that did not need floodlights. [player_name] tasted copper and the old pier-night fear of what silence could become if she confused quiet with cowardice again. Will stopped her with a hand near, not on, her wrist. "Listen to the difference," he said. "Seven years ago you kept Owen off the record to protect a house. Tonight you sealed collateral to keep bones from becoming theater and IA shadows from eating the case alive. Same stationery smell. Different verb—if you hold the difference. Quiet resealed means you accept bittersweet cost as climate and do not pretend reburial is the same as the old lie. Soft rebuild means the sealed page itches in daylight we share, and we heal without demanding a purity neither of us earned. Renny stays a pointed finger. Cho stays pending. Hope stays allowed. Dread stays honest. Solis stays partly sealed in my chest where it belongs unless a judge opens it. I deepened that ash for you tonight. I did not dump the whole hallway on your lap."

Rain needled the stairwell glass harder. Somewhere a precinct radio crackled Owen's lesser-count language like a weather report. Attraction hummed unwanted under incomplete daylight—Will's sleep-deprived shoulders, the dangerous care of refusing funerals for metrics, mid-thirties heat banked against mid-twenties mercy. Trust was still the real plot. Trust tasted like pen ink and burnt coffee and a man who hated seals enough to make them honest.

William Akers watched her the way a man watches a fuse he helped bank instead of light. Chain-link rattled faintly beyond the precinct. Ellison's office light clicked off upstairs. Downriver a foghorn answered again. [player_name] felt Will shift half a degree closer—blocking nothing cameras could see at this hour, offering heat the quiet deal must not catalogue as evidence.

"You signed without inventing a corpse," he murmured. "Now choose what kind of quiet the signature gets to keep. Reseal what still costs—or heal softly around the page. I will still want the woman who refused to let Ellison turn pending into a funeral. Want is not the seal. The seal is which ending finishes what you started when you stopped pretending silence was kindness—and started admitting some truths need indoor weather to stay human."`,
  textHot: `The quiet deal lived in Ellison's office after hours, and [player_name]'s body was already too warm for sealed paper. Burnt precinct coffee. Rain on Harborwick glass. William Akers stood by the window—mid-thirties charcoal open at the throat, scar catching fluorescent light, grey-green eyes dragging over [player_name]'s mouth before they forced themselves to Ellison's tablet like professionalism were a restraint he kept on for the girl's sake.

Sealing parts of the file meant collateral stayed collateral, IA shadows banked, Owen bargained into supervised quiet, chain intact without full circus. [player_name]'s mid-twenties cunt clenched when Will's gaze caught hers across the office: brutal charm banked quieter than floodlights, velvet over blade, the almost of his attention shooting between her legs before either pretended this was only stationery.

"You know the fork," Ellison said. "Quiet reseal—parts reburied that cost too much. Or soft rebuild around the sealed page—love that admits incompleteness. Either way Cho's remains stay *pending*. Charm is not an ID. No invented funerals for metrics. Hope allowed. Dread honest. Seal is collateral and politics—not a lie that Renny ran forever."

Will's cracked knuckles flexed on the sill. Ellison almost named Nina Solis fully; Will's jaw worked and his eyes stayed on [player_name] like her pulse was a clit he was counting through cloth. Hint deepening. Broken men should not be this hot. "I hate this deal," he said, voice rough enough [player_name] felt it lower. "I am still signing the parts that keep bones from headline theater before science speaks. She chooses which quiet ending. I stay for both. Sealed costs. I will not pretend otherwise—and I am hard from watching you sit in incomplete daylight like incompleteness were a kind of undressing."

Owen's lesser-count language glowed on the tablet. They signed. Pen scratch. When Will handed [player_name] the pen, his cracked knuckles brushed hers and the contact shot straight to her clit. Ellison stacked sealed tabs. "Side stair. Do not fuck in my hallway. Solis stays sealed unless a judge says otherwise."

Will's jaw flexed. Ash stirred. "Understood." The word cost him and somehow made [player_name] wetter—competence and self-hatred braided into heat grief refused to cancel.

Side stair. Rain on concrete. Foghorn inland. Will stopped one landing down and the air between them went wet. "Quiet resealed means bittersweet cost in our bed," he murmured against her ear, breath hot enough to stroke. "Soft rebuild means the sealed page heals slow and we refuse to let incompleteness become another pier-night silence. Both leave Cho's *pending* intact. Both leave Renny pointed finger and journal until science speaks. Both leave me wanting to fuck the shaking out of you against this rail while Ellison's seal dries upstairs." His cracked knuckles ghosted her hip, then cupped her ass through her skirt—claim the stairwell must not catalogue. "Solis took a fall I ordered. I kept the badge. Quiet is a language I speak and hate. Reseal what costs and I will hold you through the reburial without calling you coward—mouth on your throat, fingers in your cunt, teaching your body that sealed does not have to mean unused. Soft rebuild and I will touch the sealed page like a bruise we agreed to keep while I make you come so honest the itch cannot pretend to be the old silence. I will not invent a corpse to make either quieter. I am choosing—right now—to keep my cock out of Ellison's paperwork."

[player_name]'s cunt fluttered. Shame and hunger and grief fucked the same oxygen. She pressed into his hand for one filthy second and felt him groan low enough only she owned it.

The stairwell duct leaked interview-room clock hum into the quiet like a second conscience. Will kissed her slow this time—less storm, more sealed-page patience—tongue mapping her mouth while his fingers stayed under her waistband, not entering yet, just petting soaked folds until her hips chased. "Quiet is not soft," he murmured. "Quiet is choosing which teeth stay indoor. Reseal and I will still take you apart tonight—bent over the first locked door, skirt up, my cock filling you while bittersweet cost runs down your thighs and I remind you reburial is not the pier-night lie. Soft rebuild and I will undress the seal out loud between kisses—*this page itches, this page we keep, this page is not Renny's corpse*—and then put my mouth on your clit until healing tastes like salt and my name."

She moaned into his collar. He finally pushed two fingers into her, curled, found the place that made her vision white at the edges, and fucked her with his hand in fluorescent quiet while rain needled glass and Ellison's seal dried upstairs. Mid-twenties cunt clenched; mid-thirties control held; he denied her the edge again on purpose, withdrew, painted her lower lip with her own slick, and kissed it off. "Catalog open. Ending unchosen. Pending holy. Solis partly sealed in my chest where it cannot eat your choice. Verb, [player_name]. Foghorn rolled inland again, low enough to shake the rail and her unused edge. She tasted herself on his tongue and the seal upstairs and the old fear of silence; he held her hips still when she tried to chase his fingers back. "Not yet," he said, velvet-blade and tender. "Reseal what costs too much and I will spend the night making bittersweet taste like survival instead of cowardice. Heal softly around the sealed page and I will spend it teaching your body that incomplete daylight can still leave you shaking honest in my hands. Either way Renny stays pointed finger. Either way I refuse to christen bone because quiet looked cleaner on Ellison's tablet. Choose the indoor fire before I forget this is a precinct stair and remember I can still smell how ready you are.""

"If I reseal," she whispered, "I will need you to fuck the bittersweet out of my mouth until I stop tasting copper."

"You will have me." Velvet-blade wrecked laugh. "Against the first door that locks. Skirt up. My hand cataloguing how wet quiet made you while sealed tabs dry upstairs. If you soft-rebuild, you will have me slower—mouth between your legs in a room that still smells like rain, my tongue on the pulse that signed incomplete daylight, teaching you healing can be filthy without christening bone." He slid two fingers carefully under her waistband—found her soaked, stroked once along her clit without entering, pulled back like a man who still heard Ellison's warning—and left her aching. "That is mine to spend on a verb. Reseal what still costs too much—or heal softly around the sealed page. Either way I stay. Either way Cho says *pending*. Either way I do not fuck you into inventing a funeral so the quiet looks cleaner."

Hope still had a throat. Dread still had teeth. Remains still unnamed. Charm upstairs still only *like*. Solis ash stirred deeper without dumping every sealed hallway page. [player_name]'s nipples peaked against her blouse where Will's gaze caught—noticed, banked, promised. Choosing quiet resealed meant bittersweet reburial as bed-climate, want spent as antidote to the cost, Will's body refusing to let sealed become another seven-year cowardice. Choosing soft rebuild meant healing around incompleteness, Will's mouth teaching her sealed could be honesty's indoor twin, love that itched and still stayed.

"Choose," Will said against her temple, cock hard against her hip through charcoal, deliberate denial. "Before I kiss you where Ellison's cameras on the stair might catch and make her hallway warning prophetic. Reseal—or soft heal. Want is not the seal. The seal is which ending gets the incomplete daylight and which night gets the man who refused to baptize bone for a quieter city."

He pinned her gently to the stair rail—kiss deep, tongue and salt, hand back under her waistband—and this time two fingers pushed into her while his thumb worked her clit in a circle timed to the rain. "Quiet makes you soaked," he rasped against her mouth. "I need you to feel that without shame. Reseal and I will fuck the bittersweet out of you until reburial stops tasting like the old pier silence. Soft rebuild and I will go slower—mouth on your cunt in a dark room, sealed page named out loud between your thighs so healing never pretends to be another kept secret." She came shaking on his hand, muffled into his collar, grief and sex coexisting without eroticizing the kill. He held her through it, forehead to hers, cock still hard and denied against her hip. "Sample spent. Ending still yours. Pending still holy. Solis still partly mine. Pick the quiet that does not turn into cowardice."

Foghorn answered. Ellison's office light clicked off upstairs. Will stepped away with visible effort, leaving [player_name] unused and throbbing beside a badge that smelled like salt and unfinished weather. Unidentified remains waited upriver. Renny's journal waited partly outdoor, partly sealed.`,
  choices: [
    { id: "scene10i", text: "Reseal what still costs too much", textHot: "Reseal what still costs too much" },
    { id: "scene10b", text: "Heal softly around the sealed page", textHot: "Heal softly around the sealed page" }
  ]
};
