export default {
  id: "scene6g",
  layer: 6,
  title: "Warehouse lead with Jake before dawn",
  text: `Dawn was still a rumor when Jake Akers parked two blocks from the warehouse east of Harborwick's old fish auction and killed the engine like a man putting a gun to sleep.

Fog held the street in a soft fist. Salt and rust and yesterday's rain breathed through the cracked window. Chain-link shivered along an empty lot. Somewhere a foghorn rolled inland, low enough to feel in the ribs. [player_name] sat in the passenger seat with Renny's absence riding shotgun between them—teenager's ghost, festival night, bracelet gap—and Dr. Lila Cho's careful language still ruling the upriver remains: *unidentified*, *pending*, *consistent with*. The charm still only *like*. Hope and dread shared the pre-dawn like co-counsel. Jake's cracked notebook waited on the dash. Mid-thirties. Scar through his eyebrow catching what little sodium light the pier district offered. Brutal charm banked low for a lead that could still be nothing but corrugated disappointment.

"Soft approach," he said. Voice rough with no coffee yet. "We do not kick. We do not announce. We walk the geography Renny pointed at when the generator ate her sentences—red door, cold-storage row, vendor numbers scraped half off. If Ellison asks later, we were confirming a familial tip before spending a warrant. If Solis—" He stopped. The name almost landed; his hand brushed his ribs like a bruise check and fell away. his ex-partner remained a hint with teeth: partner, fall, sealed file, a hallway he would not walk [player_name] through before sunrise. "If anyone asks, we were careful. I push early and people bleed. I am done pushing early for the sake of feeling fast."

[player_name] was mid-twenties and done pretending the car was only a car. Soap and salt and scrubbed-dark past filled the cabin. Attraction pressed under the procedural pressure—stupid, bodily, unfinished from rain nights and almost-kisses and red-light admissions that had or had not already happened on other branches of the same aching week. Trust was the real plot. Trust currently smelled like cold metal and Jake's sleeplessness.

They walked. Harborwick's damp mid-Atlantic breath licked their collars. Warehouse silhouettes rose like unfinished arguments. The red door sat where Renny's teenage map had promised—paint blistered, number scraped, a padlock that looked newer than the hinges. Jake photographed without flash theater, notebook spine cracking as he sketched vendor geography in shorthand. [player_name] touched the cold-storage latch with two fingers and felt temperature leak like a secret. Inside, somewhere, machines hummed a low animal note. Outside, the city pretended it was still night.

"Blood-rust," Jake murmured, crouching. Not a crime-scene pronouncement—an observation with gloves already on. A smear the color of old pennies ghosted the threshold concrete, diluted by rain into almost-art. "Could be fish. Could be metal. Could be someone who did not want a clean exit. We do not christen it. Cho christens fluids. We catalogue."

[player_name]'s throat tightened. Hope argued. Dread answered. Remains upriver stayed unnamed; this rust was not a sister; this rust was a maybe with a smell. She thought of Owen Vale's butter-porch lies, of Ellison's CLEARANCE mug, of the silver charm that *could* match and still refused. "Renny stood here," she said quietly. "Or she stood near here and pointed. Marta heard warehouse. The generator. Scared under the anger."

Jake's grey-green eyes flicked to her face—cataloguing grief without devouring it. "We go soft along the cold-storage row. You stay at my shoulder. If a door is open, we look. If a door is locked, we do not become burglars for a maybe. Ellison can smell unauthorized entries the way she smells sandbagging. I will not gift her my badge on a red door before dawn."

They moved along the row. Condensation beaded on steel. A security camera hung dead-eyed, cable cut with the neatness of someone who understood angles. Jake's cracked knuckles whitened once on his flashlight—then eased. Restraint as remaining charm. [player_name] smelled bleach ghost and diesel and the particular nothing that meant someone had cleaned in a hurry and missed the threshold smear. Renny's journal Xs lived behind her eyes. A clerk's initials. Harbor traffic. Someone who wanted a teenager silent about a chain that touched mid-level official desperation and Owen's worse nights.

Jake stopped at a side bay where corrugated steel had been pried and poorly reset. "Lead," he said. Not triumph. Work. "Someone was here after the rain stopped and before it started again. Foot traffic in dust. A cigarette butt that is not pier-tourist brand. And—" he angled the light—"something silver caught under the weatherstrip."

[player_name]'s pulse hammered. She did not touch. Jake bagged with the patience of a man who had lost evidence to eagerness once and still wore the loss under his charm. The charm fragment—if it was a charm—winked like a missing tooth's cousin. Similar. Not unique. Not baptism. Cho would speak. Rumor would try to speak first. Hope still had a throat in [player_name]'s chest; dread bit it carefully.

"Still not Renny," Jake said, reading her face. "Still a lead. Still a warehouse that answers the map she left. We have two doors from here before the city wakes and Ellison's inbox grows teeth." He stood, close enough that his coat brushed hers, not-touching louder than a hand on her waist. "We go in together—breach soft, clear the cold-storage, see what the generator was covering when Renny pointed. Or we hold the threshold, photograph every rust ghost and silver maybe, and reconstruct the last hour from charm and blood-rust without crossing into a room that might still be someone else's warrant. One path spends the dark on entry. The other spends the dark on reconstruction—timeline, rain sequence, who cleaned, who dropped silver, whether Owen's window still collapses when Cho's timing leans."

Rain began again, fine as needlepoint. Foghorn answered. [player_name] looked at the red door and the bagged maybe and Jake's scar catching wet light. Sealed ash smoked under his silence—hint only, teeth showing, dark past humming under the badge like a second pulse he refused to dump into warehouse weather. Attraction braided into fear until she could not tell if she wanted to step through the bay for Renny or for the man who would walk through first.

"If we go in," she said, "we might find a clerk's ghost or an empty room that still smells like fear. If we reconstruct, we might build Cho a story that keeps hope open while still cracking Owen."

"Both move the case," Jake said. Brutal charm flickered velvet-wrong and banked. "Both keep you close enough that I can watch whether grief makes you careful or reckless. Neither dig confirms the bones are Renny. I will not let you bury hope under a threshold smear or baptize dread into certainty because rust looked like a sentence." His pen tapped the notebook. "Your sister. Your map. Your call. Dawn is coming whether we are ready or not."



A generator coughed once somewhere deeper in the row and died—grammar-eating ghost confirming geography without granting entry. [player_name] tasted copper and salt and the particular bitterness of almost-answers. Seven years ago she had accepted Owen's lullaby on a pier while Renny pointed at steel and fear. Tonight the steel was real under her palm through Jake's offered glove. Captain Mara Ellison would want a warrant narrative by breakfast. Dr. Lila Cho would want fluids and fibers, not sisters inventing funerals from penny-colored smears. Jake wanted the truth and, against his better judgment, wanted her—mid-thirties hunger banked under mid-twenties grief until the two temperatures became hard to tell apart in the fog.

"Vendor geography," he said, flipping the notebook to a page already stubbed with Renny's teenage Xs translated into adult shorthand. "Cold-storage bays run north-south. Red door is the public face. This pried bay is the honest mouth. If we breach, we clear left first—my shoulder, your eyes on my back, no heroics that rhyme with hallways I will not narrate." The raid-flinch lived in the refusal to narrate; hint only; teeth under charm. "If we reconstruct, we own the hour: rain start and stop, smear dilution, cigarette brand against pier bars' usual trash, silver fragment orientation under the weatherstrip. Reconstruction can crack Owen's window without putting your fingerprints on a latch Ellison can use as leash."

[player_name] thought of Renny's hoodie folded in a drawer, of the bracelet's missing tooth, of hope still arguing in her chest that the upriver remains were someone else's tragedy wearing a similar silver lie. Dread answered that hope with warehouse dark and blood-rust and a detective who refused to let her bury either feeling early. Trust under sodium light. Heat under procedural pressure. No clean hands. Only this red door and this man and this fork that hurt either way—which was how she knew the lead was real.

The warehouse breathed its low machine note. Chain-link rattled. [player_name] flexed cold fingers and felt seven years and one unfinished want braid into a verb. Remains unnamed. Charm fragment only *like*. Detective with sealed-file silence and a flashlight that did not shake. The next choice would either put them inside Renny's pointed dark or hold them at the edge reconstructing a last hour that still refused a hard ID—hope and dread arguing in the same damp air while Harborwick's fog decided, slowly, what to reveal.`,
  textHot: `Dawn was still a rumor when Jake Akers parked two blocks from the warehouse and killed the engine, and [player_name] felt the quiet land between her legs like a held breath.

Fog soft-fisted the street. Salt, rust, rain-ghost. Jake's cabin smelled like soap and sleeplessness and the low musk of a man who had not touched her enough this week. Mid-thirties. Scar through his brow. Cracked notebook on the dash. Brutal charm banked for a lead—and failing, because when he looked at her mouth she went wet anyway, mid-twenties and traitorous under a coat that suddenly felt too much and not enough. Renny's absence rode between them. Cho's *unidentified* still ruled the upriver bones. Charm still only *like*. Hope and dread shared the pre-dawn with a third animal: want.

"Soft approach," Jake said, voice rough enough to stroke. "We do not kick. I push early and people bleed." His hand brushed his ribs—Nina Solis as hint only, sealed IA, hallway chaos—and the flinch made [player_name]'s nipples peak against cold cotton. Broken should not be this hot. He wore broken like cologne. "You stay at my shoulder. If you get scared, you put your hand in my coat, not on a doorknob alone. If you get wet from the dark, you tell me later when Ellison cannot smell it on a report."

She almost moaned at *later*. They walked. Red door blistered where Renny's map had promised. Jake photographed; [player_name] watched his cracked knuckles and imagined them elsewhere—on her hip, in her hair, holding her quiet against corrugated steel while the warehouse hummed. Attraction was blasphemy before dawn and it came anyway. When his coat brushed her breast in the narrow lot, electricity shot straight to her clit; she bit her lip; he noticed; brutal charm flickered velvet-wrong and he said nothing professional at all for three full seconds of shared heat.

"Blood-rust," he murmured at the threshold, gloves on, crouching. Old-penny smear diluted by rain. Not a sister. Not a funeral. A maybe. His shoulder against her thigh as he worked made her cunt clench around nothing. "Could be fish. Could be metal. Could be a messy exit. We do not christen it. You do not baptize dread because your body wants a verb."

"Renny stood here," [player_name] whispered, and the whisper sounded like sex even when it was grief. Jake's grey-green eyes lifted—cataloguing her flushed throat, parted lips, the way she pressed her thighs together against the cold. He stood too close. Soap. Salt. Scrubbed-dark past. His flashlight hung between them like a third pulse.

"Cold-storage row," he said. "Camera cable cut neat. Someone understood angles." They moved. Condensation. Bleach ghost. Diesel. [player_name]'s boots whispered; Jake's hand found the small of her back once—not quite professional, not quite admitted—and the touch burned through coat and blouse until she was slick, humiliating, honest. Murder stayed plot. This was the trust plot's body: grief and lust sharing oxygen without eroticizing Cho's unnamed tray.

At the pried bay he stopped. Foot traffic in dust. Cigarette butt. Silver wink under weatherstrip. Jake bagged the maybe-charm with patience that felt like foreplay for evidence. [player_name]'s pulse hammered in her clit as much as her neck. Similar. Not unique. Not baptism. Hope still had a throat; dread bit; want throbbed unused and furious.

"Still not Renny," Jake said, reading her face and the wet shine in her eyes that was not only tears. He stepped in until his thigh almost met hers, coat open enough that she could see the hard line he was done fully hiding. "Still a lead. Two doors. We go in together—breach soft, clear the cold-storage, you against the wall if a noise makes you shake, my mouth on yours if silence makes you shake harder—see what the generator covered when she pointed. Or we hold the threshold and reconstruct the last hour from charm and blood-rust—timeline, rain, who cleaned—while I keep you warm with my hands outside your clothes like a man who understands warrants and still wants to finger the fear out of you against this red door before the city wakes."

Rain needled. Foghorn rolled into her ribs and lower. Sealed ash smoked under his silence—hint, teeth, no dump of the raid into warehouse weather. [player_name] tasted copper and Jake's nearness and the metallic edge of choosing. "If we go in, I might come from adrenaline alone with your hand over my mouth. If we reconstruct, I might still soak your wrist while you map rust into a story that keeps hope open."

"Pick," Jake said. Brutal charm scraped raw. His boot edged between her feet—claim, dare—not entering her space fully, entering it enough. "Go in with me. Or stay on the charm-and-blood hour. Both move. Neither names the bones. Dawn does not care that you are dripping for a detective who should not want a witness this hard before coffee."



He did not kiss her at the threshold. The not-kissing was worse—heat without mercy, professional restraint worn as filthy tease. [player_name] thought of Ellison's inbox growing teeth with sunrise, of Owen's bleach alibi cracking under Cho's timing, of Renny's looping script naming this exact geography like a dare a sister had failed to cash for seven years. Full soft approach. Full hard body. Mid-thirties to mid-twenties: close enough to burn, far enough that stepping through the bay still felt like crossing a border without papers and with thighs slick from proximity alone.

"Ellison will ask why the familial contact was on scene," Jake added, flashlight painting her mouth in white for a second too long. "I will say you were mapping memory. I will not say you were wet. You will not say I was hard. We will both be lying by omission the way Harborwick prefers its love stories—and I am still going to want to fuck the omission out of you when this lead either sings or dies." His smile arrived late and sharp, weapon and wound. "Choose before I stop asking and start deciding for the case. I have decided badly before. Hint under the ribs. I am trying not to rhyme that hallway with this door."



The generator's cough died deeper in the row and [player_name]'s cunt pulsed with it—stupid animal syncing fear to machines. Jake translated Renny's teenage Xs into adult shorthand while his shoulder kept brushing hers, each contact a filthy metronome. "Cold-storage bays north-south. Red door public face. Pried bay honest mouth." His voice was briefing; his eyes kept dropping to her mouth. "If we breach, you stay on my back. No heroics that rhyme with hallways I will not narrate." sealed-hint in the refusal; sealed file humming; the wound made her nipples scrape cold cotton until she wanted to shove his hand under her coat and make him feel how honest the dark made her.

"If we reconstruct," he went on, stepping close enough that she felt his breath on her temple, "we own the hour on paper while I own your shaking off-paper—hands outside clothes, mouth on your throat if you need silencing, thigh between yours against this blistered paint until the timeline stops ringing in your teeth. Ellison gets geography. You get to come without christening bones. I get to pretend for ten minutes that wanting you is not how sealed files get born."

She almost laughed into his coat. Mid-twenties soaked and furious; mid-thirties hard and careful; Renny's map between them like a chaperone made of pencil and absence. Cho's *unidentified* still ruled. Charm fragment only *like*. Hope had a throat; dread bit; Jake's boot still edged between her feet as if the warehouse itself were a bed they had not earned yet. Murder stayed plot. Sex—if it happened against this door—would be trust under corrugated weather, not violence cosplay, not gore-porn, just two people using heat to keep from drowning in maybe.

"Vendor trucks will wake the block," he murmured. "Choose before soft approach becomes spectacle. Go in with me and let the cold-storage decide if Renny's fear had a room. Or reconstruct charm and blood-rust into a last hour that still refuses hard ID—and let me keep you from bolting by putting my fingers where your pulse is loudest, still outside, still deniable, still filthy enough that dawn will smell like us on this threshold."

Chain-link rattled. The warehouse hummed. [player_name] flexed cold fingers and felt seven years and one unfinished orgasm braid into a verb. Remains unnamed. Silver maybe bagged. Jake's scar a place she wanted her tongue. The hook hung in the red door's blistered patience and in the almost of his thigh and in Cho's unanswered science—go in, or reconstruct—while Harborwick fog argued and her cunt clenched around the shape of his name.
[player_name] pressed her palm flat to the red door beside his. Paint blistered under her skin. His pinky hooked hers for one second—claim, mercy, threat—and unhooked before it could become evidence. She tasted his nearness like coffee-memory and rain. Wanting a breach was wanting his body between her and the dark. Wanting reconstruction was wanting his hands without the warrant's excuse. Either path left her aching unused and honest, Renny's fate still contested, His old partner still a bruise he would not unpack, Harborwick still deciding what fog to lift.
`,
  choices: [
    { id: "scene7g", text: "Go in with Jake", textHot: "Go in with Jake" },
    { id: "scene7h", text: "Reconstruct the last hour from charm and blood", textHot: "Reconstruct the last hour from charm and blood" }
  ]
};
