export default {
  id: "scene7p",
  layer: 7,
  title: "Chase: reunion at the pier festival anniversary",
  text: `The pier festival anniversary smelled like fried sugar, wet rope, and seven years of unfinished weather.

Harborwick had hung the same cheap lanterns. The same funnel-cake smoke. The same sodium smear on boards that remembered a sixteen-year-old girl's bracelet better than any memo. Crowds moved in memorial soft and tourist loud. Missing-person posters of Renny fluttered on a chain-link stretch near the carnival lot—smile unfinished, age frozen, hope and dread sharing the tape with rain. Unidentified remains still waited in Dr. Lila Cho's patience upriver. A silver charm in evidence still only *like*. No confirmation. No funeral authorized by science. The city celebrated survival and spectacle anyway, because cities were like that.

[player_name] found the boards because Jake Akers had chased both the case and her into this night—or because she had walked and he had offered reunion like a soft verb with teeth. Mid-twenties sister of the missing in a crowd that thought anniversary meant closure. She tasted copper and pier salt and the metallic bright of standing where Renny had pointed east while a clean jacket held a wrist. Owen still unnamed on any official page. The kept secret pressed her tongue while festival music lied about safety the way it always had.

Jake found her by the piling where the fog thickened deepest, away from the loudest speakers. Mid-thirties. Dark stubble silvered wet. Scar nick catching lantern light. Whitened knuckles flexed once at his sides as if arguing with the urge to grab. He did not grab. He stopped close enough that she felt his heat through the damp. Notebook a dark rectangle in his jacket. Badge a weight under wool. Late smile attempted and then abandoned for something honester.

"You came," Jake said, voice low under the music. "I chased the warehouse scrap and your fog and Ellison's distrust and Internal's ash-smell, and somehow the chase ends on the boards where soft failed her first." His hazel gaze held hers—tired, hungry, dangerous. "Anniversary is a cruel word. It pretends time is a circle that comforts. Time is a knife that learned our names. Renny is still missing in the only way that matters until Cho or a confession says otherwise. I am still a detective with a sealed drawer humming. You are still the woman who kept something. And I still want you in a crowd that thinks this is memorial instead of unfinished kissing."

[player_name] almost laughed. Almost cried. Trust under interrogation lights had become trust under lanterns. "If I reunite here, I am choosing the place she vanished."

"You already chose it by walking these planks," Jake answered. "I chose it by chasing you here instead of inventing another lean or another memo." He flinched—small, real—when a kid ran past shouting *partner* at a parent in a silly costume; Nina Solis lived in the flinch as hint only: early push, kid in a hallway, sealed file, charm for a face afterward. Pressure deepened in the proximity of festival noise that rhymed wrong with raid memory. He did not dump the hallway. Ash-smell lived under carnival sugar; the sealed file stayed shut. "his old partner stays sealed. Ellison stays weather. Cho stays patient. Owen stays your private storm until you put him on a page—and this crowd digs softer than cameras but digs anyway if you feed it names."

Want lived under the procedural dread—dangerous, unfinished, the pull of a man who could chase her through fog and still offer her a night that was not a raid. [player_name] touched the whitened knuckle at his side. His pulse jumped once under her fingers. Jake turned his hand and laced them hard enough to hurt a little, claim and apology, soft net in public that Internal would photograph if it were watching. Maybe it was. Harborwick leaked.

"Fork," Jake murmured, nodding past the posters toward the open pier and then toward the city lights inland. "Propose truth at the pier anniversary—not marriage, not a ring, not a tidy ending. Truth: what you kept, what I won't dump yet, what we refuse to let the machine write while hope and dread still share Renny's flyer. We stand here and say the hard sentences to each other like a vow the law does not recognize." His thumb brushed her knuckles. "Or name the chain in public instead—Renny's journal geography, smuggling throat, clerk-shaped shadows, the harbor's mid-level rot loud enough that anniversary becomes indictment and Jake Akers becomes the detective standing beside the sister who blew the windows out on purpose."

[player_name] tasted fried sugar and copper. Thought of Renny's hoodie folded in a drawer. Thought of a locked box and cream envelopes and a red door east. Thought of Jake's cracked knuckles and the way he dreamed raid noise when soft failed. "Proposing truth means choosing us as the first audience."

"Naming the chain in public means choosing the city as the first jury," Jake said. "Both move the case. Both hurt. Both leave bones unnamed until science earns a name—and both leave the sealed past sealed for now even if public noise sniffs harder at ash." He scrubbed rain from his face with his free hand. "I will not pretend I do not want the truth-proposal between us first. Wanting that makes me selfish. Offering the public naming anyway makes me slightly less. Slightly. You walked. I chased. Soft returned as lantern light. Do not waste soft on hesitation while the boards remember her better than we deserve."

Festival speakers crackled through a ballad that had been popular the year Renny vanished. Someone laughed too loud near the funnel-cake stall Marta had once worked—or a stall like it, geography rhyming. A Harborwick PD cruiser idled at the lot edge without lights, Ellison's caution wearing a unit number. Jake noticed and did not turn his head. "We're seen," he said. "Good. Means the chase was real. Means reunion is a record whether we want it or not."

[player_name] leaned into his shoulder despite the cruiser. "If we propose truth here—"

"Then I ask you to put Owen on a sentence between us before you put him on a press page," Jake said softly. "I ask myself to give you more his old partner than hints when the case earns it—not tonight's dump, not a sealed-file striptease for anniversary romance, but a promise that ash will not stay forever private while I demand your pier night. Softest hard. Reciprocal teeth." His late smile arrived wrong and fond. "If you name the chain in public instead, we walk to the steps or the mics or the flyer wall and you read what Renny pointed at into the city's mouth. I stand with you. I cannot control the match. I can hold your hand while it burns."

Rain thickened into mist that made lanterns into bruises. Another fog horn spoke across the water like a warning that had learned their names. [player_name] looked at Renny's poster, at Jake's mouth, at the boards under her boots. The romance was whether she could love a badge after the system failed Renny—and whether he could love the woman who walked when his mouth went hard—and whether tonight's reunion was memorial, confession booth, or the start of a louder war.

"Cho will not name the remains because we kissed under lanterns," Jake added. "Charm stays *like*. Hope and dread do not retire for anniversary branding. What changes is whether dawn finds us having told each other the truth on these planks, or having told Harborwick the chain while the festival still smelled like sugar and grief."

His phone buzzed in his pocket—precinct, Ellison, unknown, the machine that hated soft reunions. He ignored it. He watched [player_name] instead, mid-want, mid-war, chasing ended for one night into a choice that would start the next chase either inward or outward.

"Propose truth at the pier anniversary," Jake murmured, almost a plea under the grit. "Or name the chain in public instead. The walk is done. The chase found you. The hook is which hunger you feed while soft is still possible—private vow without a ring, or public indictment with Renny's finger still pointing east through every sentence."

[player_name] stood between festival noise and harbor fog, fingers laced with Jake Akers's cracked knuckles, remains unnamed, charm probable, sister still missing in the only way that mattered—and the choice sitting between them like unfinished weather: truth as proposal on the boards where she vanished, or the chain named loud enough to make anniversary into reckoning.

Festival lanterns stitched gold through pier fog on the anniversary night Renny had vanished into. Jake had chased [player_name] here instead of inventing another memo; a kid's shout of *partner* had put a flinch through him he did not unpack—sealed wound under carnival sugar. Proposing truth between them on these boards meant honesty as vow without a ring. Naming the smuggling chain in public instead meant turning anniversary sugar into reckoning while cameras could still invent what Cho refused to. Lantern light caught the scar nick at his thumb. [player_name] felt both verbs hurt to leave—and that was the point of a chase that still refused false funerals.`,
  textHot: `The pier festival anniversary smelled like fried sugar, wet rope, and the filthy unfinished want that reunion always woke in [player_name] when Jake Akers found her in fog.

Lanterns. Posters of Renny—smile unfinished, bones still unnamed upriver, charm still only *like*. Hope and dread on the tape. Crowds memorial-soft and tourist-loud. [player_name]'s pulse lived in her throat and lower; jeans already a problem from the walk through festival air and the knowledge that Jake had chased case and woman both to these boards. Mid-twenties. Sister of the missing. Wet for a mid-thirties detective with a sealed drawer and brutal charm banked under anniversary weather.

He found her by the deepest piling—scar nick catching lanterns, whitened knuckles arguing with the urge to grab. He did not grab in the open. He boxed her into the piling's shadow where fog and a stack of unused carnival crates made a pocket, mouth at her ear, thigh shoving between hers until she gasped at the thick pressure on her clit through denim. "You came," Jake growled. "I chased warehouse scrap and your fog and Ellison and Internal ash-smell, and the chase ends with my cock hard against the woman who walked when I went instrument." Rain beaded on his shoulders. His hand slid under her coat, under her shirt, palm on bare waist, thumb stroking the underside of her breast until her nipple peaked. "Anniversary is a cruel word. Soft is still possible. Feel how soft I am not."

"Jake—crowd—"

"Fog and crates," he muttered, working her jeans open enough to shove two fingers into slick heat without preamble. She bit his shoulder through wool to stay quiet for the pier path. "Propose truth at the pier anniversary—not marriage, not a ring. Truth between us: what you kept, what I won't dump tonight, reciprocal teeth—and after the sentences I fuck you against this piling until honesty sounds like a moan, until the boards stop lying about safety, until you come with my palm over your mouth and Renny's maybe still sacred." He pumped deep, curling, thumb on her clit in tight circles. "Or name the chain in public instead—journal geography, smuggling throat, clerk-shaped rot loud enough anniversary becomes indictment—and after the shouting I take you somewhere the mics can't follow and eat you until public courage tastes like sweat, until you clench around my tongue for every sentence you gave the city."

[player_name] rocked on his hand, Renny's poster fluttering somewhere beyond the crates and Owen's unnamed pier night braided into heat that felt like loyalty's filthy twin. Jake flinched when a kid shouted *partner* nearby—Solis ash, hints only, sealed file, kid in a hallway not dumped—and then kissed her harder for the flinch, copper and sugar and rain. "his old partner stays sealed tonight," he snarled softly against her mouth. "Ellison's cruiser is watching the lot. Cho will not name bones because you drip on my fingers under lanterns. Charm stays *like*. Owen stays off your paper until you put him there—and public naming digs harder than a truth-proposal between us. Pick while you soak a detective who chased you to the place she vanished."

He freed his cock enough to smear the head through her folds without entering—hot, blunt, cruel, painting her clit until she jerked, festival music lying about safety ten meters away. Discipline as filthy as any thrust. "I will not fuck you full in open anniversary air. I will make you choose while you drip on Harborwick's memorial for a missing girl who is still not confirmed among the dead." His forehead pressed hers. "Truth-proposal means I ask for Owen between us before press—and I promise more the sealed past when the case earns it, not a sealed-file striptease for romance. Public chain means we burn the match together. Both leave me aching. Both leave you shaking. Both move the case."

She came quiet against the piling—shaking, fist in his jacket, biting wool—while Jake eased back without chasing his own finish, cock jumping against her thigh, restraint a third wound beside pride and chase-fatigue. He tucked himself away with shaking hands, fastened her jeans with mock courtesy that did not reach his eyes, and pressed his forehead to hers. Pulse hammered. Fried sugar and sex and fog. Want unfinished and loud.

"Propose truth at the pier anniversary," he whispered, voice wrecked. "Or name the chain in public instead. You walked. I chased. Soft returned as lantern light and my fingers in your cunt. Do not waste it." His late smile cut wrong—weapon and wound and vow without a ring. "I dream raid noise when soft fails. Soft is here. You get private truth or public chain. I get to want both with my cock aching and Renny's flyer watching like a conscience with glitter ink."

He walked her deeper along the boards where the crowd thinned toward the water, boxed her again between a life-ring station and his body, and put her hand on his cock through his pants. "Feel what reunion did," Jake muttered. "You let me find you and I got harder for the finding. That should scare you. It scares me."

She stroked him, slow, feeling thick heat jump against her palm. He groaned and shoved his hand back into her jeans, fucking her with two fingers in time with the ballad from the year Renny vanished. "Truth means sentences between us on these planks and then my mouth between your thighs until the vow is wet. Chain means you read Renny's geography into the city's mouth and then I fuck the adrenaline out of you in the car until fog knows both our names." His thumb circled her clit. "Both leave bones unnamed. Both leave his old partner sealed for now. Both leave your kept secret pressing until you choose which audience hears it first—me, or Harborwick."

[player_name] whimpered, hips rolling, conscience loud about Owen and posters and the cruiser's idle at the lot edge. Jake curled his fingers deep and kissed her hard enough to bruise, then eased his hand free and painted her lower lip once before sucking his knuckles clean. "Verb. Now. Propose truth at the pier anniversary. Or name the chain in public instead. Ellison's machine is watching soft reunion like a threat. Give me a better story with your mouth."

She stood between festival lanterns and harbor fog, wet jeans, remains unnamed, charm probable, sister still a pointed finger—and the choice sitting between them like unfinished wanting: truth as proposal on the boards where Renny vanished, or the smuggling chain named loud enough to turn anniversary sugar into reckoning while Jake Akers chased her answers with his body and his badge and his unfinished want.

Rain needled the life-ring. Jake scrubbed a hand over his face, then cupped her jaw with cracked knuckles that still smelled like her. "I chased you because walking relocated the pressure onto us. Reunion relocates it again—onto which hunger you feed while soft is still possible." His thumb brushed her lower lip where he had painted her. "Truth between us or chain for the city. My cock votes both. Your mouth has to pick one before the ballad ends and the cruiser decides soft looks like liability."

[player_name] tasted salt and herself and unfinished justice. Warehouse silhouettes lived behind her eyelids even here. Renny's hoodie waited in a drawer. The red door waited in rumor. Jake's pulse hammered under her palm where she still touched his wrist. Trust under lanterns. Want under murder-plot pressure that refused to become gore-porn—bodies yes, corpses no, heat advancing the chase instead of cosplaying the kill. the sealed past ash stirred, sealed file not dumped. Owen unnamed. Remains unconfirmed. Her pulse answered low and shameless; Jake's nearness made the unfinished want feel like a third warrant neither of them could ignore. Her pulse answered low and shameless; Jake's nearness made the unfinished want feel like a third warrant neither of them could ignore.

Lantern light caught the open collar of his shirt and the scar nick at his thumb when he braced beside her on the piling. Carnival sugar rode the fog; underneath it she smelled his soap and the clean sweat of a man who had run to find her instead of drafting another lean. [player_name] pressed her thighs together against the unfinished stroke of his fingers and felt want climb her throat like a second foghorn—low, insistent, impossible to file under *case only*. A vendor laughed too loud. A kid's balloon string snapped. Jake did not look away from her mouth.

Jake found her in lantern fog and pinned her lightly to a piling out of the crowd's sightline, mouth hungry, center kiss still denied. "Truth between us on these planks," he said, "or you name the chain loud enough to turn sugar into reckoning." His fingers slid under her waistband just far enough to feel how wet anniversary dread had made her, then withdrew like a promise with teeth. Bones unnamed. Charm probable. Sealed past sealed for tonight. She had to feed him honesty or volume before festival noise finished swallowing the unfinished want they kept parking behind warrants, reviews, and now behind lantern light.`,
  choices: [
    { id: "scene8p", text: "Propose truth at the pier anniversary", textHot: "Propose truth at the pier anniversary" },
    { id: "scene8a", text: "Name the chain in public instead", textHot: "Name the chain in public instead" }
  ],
};
