export default {
  id: "scene9e",
  layer: 9,
  title: "Clerk caught: Renny's killer named",
  text: `The interview room smelled like burnt precinct coffee and wet wool and the metallic patience of a clock that had watched too many familial contacts invent softer weather. Marcus Hale sat cuffed to the bolted table—municipal-small, cigarette brand from the fish-auction kiosk still ghosting his lower lip, licensing-desk eyes that had learned how to look past teenagers who pointed at red doors. Captain Mara Ellison watched through the glass. Dr. Lila Cho's latest memo sat in Jake Akers's cracked notebook without a baptism: remains unidentified, charm probability elevated, age range ugly with hope. Science still careful. Hope still employed. Dread still armed.

Jake stood with his scar nick pale under fluorescents, mid-thirties, brutal charm locked to inventory. Grey-green attention pinned Hale like a warrant that had finally found a throat. [player_name] stood beside him—mid-twenties, Renny's living link, the woman who had kept a pier silhouette off a statement for seven years and was done sanding nouns for other people's safety. Attraction pressed stupidly under procedural pressure: soap-and-salt nearness, unfinished almost-kisses from rain nights that had no business surviving into a room where a clerk was about to conjugate a killer into grammar.

"Name who quieted the girl," Jake said. Not soft. Soft had died in warehouses and wires and tip-calls. "Not the lullaby. Not the maybe. The living fact. Who needed Renny silent the night she pointed east at Warehouse C."

Hale's laugh was thin as shredder weather. "You want a mid-level throat on a recording while Cho still says pending. Cute. Ambition photographs better than caution."

Ellison's voice came through the intercom, soft and final. "Akers. Clean lean. Gloves. No Solis theater. The city wants a name that holds under daylight. The sister stays a question mark on a lab tray until science earns otherwise."

Jake did not look at the glass. He looked at [player_name] once—partner-shaped attention that was also hunger he refused to tidy—and then back at Hale. "Michael Kade," he said, testing the initials Renny had scratched as *M.K.* long before Harborwick learned to hunt desks. "Port Authority routing. Mid-level title that moves paper into crates. You moved permits. He moved quiet. Speak it like a man who still wants a deal shape that keeps him breathing."

Hale's eyes flicked to [player_name]—stepdaughter weather, festival fog memory, the sister who had become a map. Something cracked that was not steel. "Kade said if the girl kept pointing, the pier would get quiet. I moved the paper. Owen Vale sanded the silhouette. Kade—" Hale swallowed cigarette ghost and fear. "Kade put hands on the problem. Festival night. East dock. Generator cover. I did not watch the water. I watched the routing stamp. That is the name. Michael Kade. Harborwick Port Authority. He quieted her."

The room did not become a funeral. Jake's pen stopped against the cracked notebook spine the way it always stopped when a fact arrived that hope and dread would fight over. [player_name] tasted copper where she had bitten her cheek. Renny's killer named—living fact, municipal mouth, mid-level throat—while Cho's tray still refused to print a sister on bone. Ambiguity lock held. Charm stayed *like*. Remains stayed unidentified. The naming was justice's grammar, not baptism.

"Alive enough to charge," Jake said quietly, for [player_name], inventory and ache braided. "Kade becomes a warrant before municipal paper rinses. Hale becomes a cooperating throat with Ellison's leash on it. Owen's partial stops being weather and becomes corroboration. You do not get to invent Renny on the upriver silt because a clerk finally spoke. You get to stand in a room where the chain has a name above the desk."

Ellison entered without ceremony. Soft voice. Final weather. She set a thinner file beside Hale's cuffs: draft charging language, Port Authority org chart, Kade's desk code scraped into daylight. "Akers will live with the catch. He has lived with worse." Her gaze cut to Jake's ribs and away—Nina Solis ash as hint, not unpacking: sealed IA, a teenager in the wrong hallway, charm armor over a night he still would not dump. "Internal will call proximity if you keep standing that close to the familial contact. Cho will not rush baptism because you earned a killer's name. Decide how the naming spends: speak Renny's fate honestly together—daylight, partnership, the hard sentences without early funerals—or carry the naming into sister's reckoning—public story, her voice leading, the city learning what a kept detail cost."

[player_name] looked at Jake until he looked back. Mid-thirties to mid-twenties—close enough to burn, far enough that the badge still felt like a different country. Trust under interrogation lights had become trust under a named killer and an unnamed tray. The romance was whether he could love the woman who had obstructed her own sister's case—and whether she could trust a badge after the system failed Renny once and still refused to christen bone for comfort.

"If we speak it together," Jake murmured, late smile wrong—weapon and wound—scar nick white, "we walk daylight as partners who will not let press invent a corpse before Cho finishes speaking. Case closed enough for warrants. Renny's fate spoken honestly as contested science plus a living killer named. Hope stays legal. Dread stays honest. I stay compromised in ways Solis would recognize if she walked these corridors again—and I stay anyway."

His cracked knuckles brushed her wrist behind the notebook—pulse, claim, unfinished—and fell away as if Ellison's glass were a second recorder. "If you carry the naming into sister's reckoning, you lead the public story for Renny. Microphones. Rain. Purple leather if the journal still travels. I stand beside you or behind you as the city requires. You become the throat that will not sand. Both verbs spend Hale's mouth. Both leave Cho careful. Both leave me wanting to put you somewhere soft after bleach and burnt coffee and a name that finally stuck."

Hale stared at the bolted table as if routing stamps might still save him. They would not. Outside, Harborwick fog pressed the precinct glass. Fog horns spoke from the pier where a teenager had pointed east seven years ago. Renny's old hoodie still folded in a drawer inland. A silver charm bracelet missing one charm ached like a tooth in [player_name]'s memory. The upriver remains stayed a maybe. Michael Kade became a hunt with a face.

Jake paced the choice with his voice the way he walked interview rooms—counting exits, counting lies, counting what soft nets had cost when they became tip-calls and then cuffs. "Together in truth means we conjugate the night without inventing funerals—Kade charged, Hale cooperating, Owen's sanding on record, your kept detail finally outdoors as protection that failed into honesty. Sister's reckoning means you take the naming to the steps and make Harborwick say her name as a living absence until science or a courtroom earns more. Both hurt. Both keep the map breathing. Neither prints Renny on silt before Cho earns it."

[player_name] almost laughed. Almost cried. Attraction hummed unwanted under procedural dread: his competence, the dangerous care of refusing baptism theater, the way his scar nick caught fluorescent light when he refused comfort. She wanted his steadiness and hated that she wanted it while a killer's name cooled on the air and her sister stayed contested silt.

"Renny kept a map," she said quietly. "I kept a lie. Owen kept a clerk on speed dial. Hale kept permits. Kade kept quiet by force. You kept a sealed hallway. Ellison keeps an inbox. Cho keeps bones without a name. Everybody keeps something. The question is which keeping still protects a living hope and which keeping only protects the people who quieted a teenager for pointing."

Jake's pen stopped. Respect moved through his face like weather changing. He almost kissed her then—stopped a breath short on purpose—all weapon and wound, the brutal charm that had first made her want him under procedural pressure. The denial hung as hook. Soft was dead. The clerk was caught. Renny's killer was named. Science stayed careful. The next verb would hurt to leave while Harborwick fog pressed the glass and hope kept its impossible job beside dread on a lab tray that still refused to say her sister's name.

"Clock," Jake said softly. "Speak Renny's fate honestly together—or carry the naming into sister's reckoning. Either way Hale spoke. Either way Kade becomes daylight. Either way Cho's pending stays a leash we do not cut for comfort. Conjugate, [player_name]."

Ellison's tablet light painted the glass from below like a second, uglier dawn. Somewhere on a different floor, warrants for Michael Kade were already growing feet. Owen Vale's lawyers would call grief coercion. Press would smell a sister cracking into honesty. Internal would catalogue a detective who stood too close. Nina Solis stayed sealed—pressure deepened by association, full story saved for layers that earned ash dumps. Jake wore the worse like cologne and still offered [player_name] a partnership verb disguised as logistics.

[player_name] stood between burnt coffee and named steel, fingers near Jake's cracked knuckles without quite taking them, remains unnamed, charm probable, sister still missing in the only way that mattered—and the choice sitting between them like unfinished weather: together in truth at the table where a killer had finally been spoken, or sister's reckoning on steps where Harborwick would learn what the sister kept and what it cost to stop keeping it.

"Pick the verb," Jake whispered. "Daylight partnership without baptism—or public story with your throat leading. Hurt to leave either. Good. Means you understand Layer 9 does not do tidy exits after a municipal mouth earns a name—and neither does a detective who caught a clerk and still wants to finish the kiss we keep parking behind warrants, wires, raids, and now behind a killer named while science stays careful."

The corridor clock hummed. Hale's cuffs clicked once. Hope argued that Renny might still walk out of rooms like this. Dread answered that Michael Kade had not wanted her to. Choosing together meant speaking contested fate as honesty with Jake at her shoulder. Choosing reckoning meant carrying the naming into a public story Renny's map had dared without a funeral first. Either verb spent the catch. Neither spent Renny early. Jake waited with the patience of a man who had waited out worse rooms—rooms his dark past still stained—if Ellison's radio silence meant anything. He did not fill the dark with comfort. Attention as a blade laid flat, edge available. [player_name] drew a breath that tasted like rust and soap and unfinished trust, and felt the next ending arrive on the sound of a named killer and a choice that still refused to christen bone.`,
  textHot: `The interview room smelled like burnt precinct coffee and wet wool and the filthy patience of a clock that had watched [player_name] get wet for Jake Akers under worse lights than these. Marcus Hale sat cuffed—municipal-small, cigarette ghost on his lip, licensing-desk eyes that had looked past teenagers. Ellison watched through glass. Cho's memo lived in Jake's cracked notebook without baptism: remains unidentified, charm maybe, age range ugly with hope. Science careful. Hope employed. Dread armed. [player_name]'s cunt throbbed stupidly anyway because Jake's scar nick was pale under fluorescents and his brutal charm was locked to inventory and she had been unfinished since the wire, the warehouse, the rain.

Jake stood mid-thirties, grey-green attention pinning Hale like a warrant with a pulse. [player_name] stood mid-twenties beside him, Renny's living link, thighs tight from every almost-kiss they had parked behind procedure. Attraction was a stupid animal after a catch. It came anyway. Soap-and-salt. Cracked knuckles. The hard line of restraint that was its own stroke.

"Name who quieted the girl," Jake said, voice sex-rough under detective flat. "Not the lullaby. The living fact. Who needed Renny silent the night she pointed east."

Hale laughed thin. "You want a mid-level throat while Cho says pending."

Ellison through the intercom: soft, final. "Clean lean. No Solis theater. Sister stays a question mark until science earns otherwise."

Jake looked at [player_name] once—hunger he refused to tidy—and tested the initials Renny scratched as *M.K.* "Michael Kade. Port Authority. You moved permits. He moved quiet. Speak."

Hale cracked. Eyes on [player_name]—festival fog, sister as map. "Kade said if the girl kept pointing, the pier would get quiet. I moved paper. Owen sanded silhouette. Kade put hands on the problem. Festival night. East dock. Generator cover. I watched the routing stamp. Michael Kade. He quieted her."

The room did not become a funeral and [player_name]'s body did not become pure. Jake's pen stopped. She tasted copper and want. Killer named—living fact—while Cho's tray refused to print a sister on bone. Ambiguity held. Charm stayed *like*. Naming was justice's grammar, not baptism, and Jake's nearness still dragged along her wet seam through denim like a second warrant.

"Alive enough to charge," Jake said quietly for her, inventory and ache braided, hand finding the small of her back professional to Ellison's glass and filthy to her nervous system. "Kade becomes a warrant. Hale cooperates. Owen corroborates. You do not invent Renny on silt because a clerk spoke. You stand where the chain has a name above the desk—and after this brief I put you against a locked-room wall and finish what catch weather started until you come quiet enough for corridor clocks."

Ellison entered. Soft. Final. Charging language. Org chart. Kade's desk code in daylight. "Akers will live with the catch. He has lived with worse." Gaze to his ribs—Solis ash as hint, sealed IA, hallway kid, charm armor—not a dump. "Internal will call proximity. Cho will not rush baptism. Decide: speak Renny's fate honestly together—or carry the naming into sister's reckoning."

Jake steered [player_name] half a step so Hale could not read her face, mouth near her ear, breath hitting the shell until her pussy clenched empty and furious. "Together means daylight partners who will not let press invent a corpse before Cho speaks—and I fuck the leftover adrenaline out of you with my palm over your mouth so Internal does not learn how justice sounds when it comes. Reckoning means you lead the public story for Renny—mics, rain, your throat—and I eat you quiet afterward until sister's daylight tastes like sweat and you clench around my tongue for every noun Hale finally cracked. Both spend his mouth. Both leave Cho careful. Both leave me hard."

His cracked knuckles brushed her wrist, then slid once—stakeout second—under the hem of her shirt onto bare ribs because alive was also sex and he refused to tidy it. Ellison's tablet painted glass. Hale stared at bolted steel. Outside, fog horns spoke from the pier where Renny pointed east. [player_name] pictured Jake's fingers in her against interview-room cold after the warrants walked. Pictured microphones and then a supply closet where reckoning leftover became his mouth on her clit until vision whited. Either fantasy made her wetter. Either path kept Renny from a named corpse too early.

"If we speak it together," Jake murmured, late smile wrong—weapon and wound—scar nick white, cock hard under wool he did not apologize for, "we conjugate contested fate as honesty. Kade charged. Hope legal. Dread honest. I stay compromised in ways Solis would recognize—and I stay anyway with your cunt still remembering my unfinished hand." Thumb at her pulse. "If you carry naming into sister's reckoning, you become the throat that will not sand. I stand beside or behind as the city requires. After the steps I repay you until your public voice breaks on my name in private. Pick the hurt that keeps truth reachable while I can still smell how wet a named killer makes you."

Hale's cuffs clicked. [player_name] almost laughed, almost cried, soaked, furious with a body that answered Jake's nearness like a vow. Trust under interrogation lights had become trust under a killer named and an unnamed tray. Mid-thirties to mid-twenties—close enough to burn. She wanted his steadiness between her legs and hated that she wanted it while Michael Kade cooled on the air and Cho stayed careful.

"Renny kept a map," she managed, cunt aching. "I kept a lie. Owen kept a clerk. Hale kept permits. Kade kept quiet by force. You kept a sealed hallway. Everybody keeps something." She pressed his palm flat to her stomach under the shirt—claiming, demanding, conjugating with her body—then lower for one filthy stolen second over denim heat so he felt exactly how unfinished catch weather left her. "Together—I speak contested fate with you and you finish me after the brief. Reckoning—I hate every camera and still soak for the record if it keeps the map breathing. I am not inventing purity. I am not inventing a funeral. I am asking which hurt leaves Renny reachable while you can still feel me through jeans."

Jake's pen stopped. Respect like weather changing. He almost kissed her—stopped a breath short on purpose—then, with Ellison's back half-turned to the charging draft, shoved his hand into her jeans under cotton for three precise strokes. She was dripping. He cursed soft, curled once against her clit, withdrew glistening to paint her lower lip. "Not yet. Not until you pick." Grief and sex sharing a body. No gore-porn. Bones unnamed. Killer named. Science careful.

"Clock," he said. "Speak Renny's fate honestly together—or carry the naming into sister's reckoning. Either way Hale spoke. Either way Kade becomes daylight. Either way Cho's pending stays a leash. Conjugate while I can still smell your cunt on my hand under fluorescents and Harborwick fog erases the curb."

Warrants for Michael Kade grew feet on another floor. Owen's lawyers would scream coercion. Press would smell honesty. Internal would catalogue proximity. Nina Solis stayed sealed. Jake wore the worse like cologne and still offered partnership verbs disguised as logistics with his cock aching and his notebook drinking burnt-coffee air.

He boxed her against the file cabinet out of Hale's sightline for one last stolen breath, put her hand on his cock through his pants once, and let her feel the unfinished claim. "Together means I get your mouth on my throat after the naming and my fingers back in this exact slick while corridor clocks hum. Reckoning means you save the soft for after the steps and I repay you with my tongue until sister's story and Solis ash are just noise under how hard you clench." Thumb on her lower lip over her own wet. "Verb. Now. Speak Renny's fate honestly together. Or carry the naming into sister's reckoning. Hurt to leave either. Layer 9. Teeth. Consequence. No baptism—just us, a clerk caught, a killer named, science still careful, and a choice that might still save what Harborwick failed once."

[player_name] stood between burnt coffee and named steel, wet jeans, remains unnamed, charm probable—and the choice sitting between them like unfinished fucking: together in truth at the table where Michael Kade had finally been spoken, or sister's reckoning on steps with Jake's method still on her tongue and Cho's pending still refusing to soothe anyone.

Before Ellison fully turned back, Jake walked [player_name] into the alcove off the interview corridor and shut the door with his heel. He dropped to a crouch despite Solis ash humming in the building's politics, despite Kade warrants growing feet, despite Cho's careful pending, and yanked her jeans down far enough to put his mouth on her—tongue flat, then pointed, sucking her clit with warrant precision. She clapped a hand over her own mouth. His whitened knuckles braced her thighs open against cold tile. "Together means I do this after every honest sentence we speak about contested fate," he growled against her, voice vibrating through wet heat. "Reckoning means I do this after every mic—blinds of this alcove, news muted, my tongue writing a better story than any press chyron that tries to baptize bone." He slid two fingers into her while he licked, pumping in time with the corridor clock, and she came shaking, vision white at the edges. Jake stood, wiped his mouth like a man finishing a statement, pressed his forehead to hers. His cock still strained, unfinished, deliberate denial. "Solis stays sealed. Bones stay unnamed. Kade stays named. What does not stay unfinished is the verb."

"Pick," Jake whispered, late smile cutting wrong. "Daylight partnership without a funeral—or public story with your throat leading. I am still tasting you. That is not in any memo yet. Keep it that way until you choose which ending gets our next hour—truth spoken honestly together, or reckoning carried into Renny's public weather while hope keeps its impossible job beside dread."`,
  choices: [
    { id: "scene10a", text: "Speak Renny's fate honestly together", textHot: "Speak Renny's fate honestly together" },
    { id: "scene10e", text: "Carry the naming into sister's reckoning", textHot: "Carry the naming into sister's reckoning" }
  ]
};
