export default {
  id: "scene3d",
  layer: 3,
  title: "Witnesses First",
  text: `Harborwick's festival strip still smelled like burnt sugar and river fog, the kind of sweetness that clung to clothes long after the rides shut down and the calliope finally gave up. Neon stuttered pink and gold along the midway; funnel-cake smoke braided with diesel from a generator coughing behind the popcorn cart. [player_name] kept to the shadow of that cart while William Akers—mid-thirties, that brutal charm already cocked like a loaded smile—worked the edge of the crowd the way some men worked a blade: casually, accurately, as if the cut were inevitable and manners were only the sheath.

She chose witnesses first. That was the 2b bargain written in Renny's room under peach-perfume ghost and a bracelet missing its anchor: hide Owen, push festival witnesses, let the carnival talk before anyone kicked a door that could not be unkicked. Owen stayed where she put him—off the page for one more night, off Will's notebook, off Captain Ellison's clearance hunger. Renny stayed a missing teen with a name and no body the morgue would claim. The unidentified remains upriver still wore no sister's label; Dr. Cho's lab still refused the hard ID; hope and dread still shared the sticky fairway boards under her shoes. That gap was the only soft ground left, and she meant to walk it carefully while Will's charm did the harder walking for her.

The carnival vendor looked like a man who had already rehearsed a denial. His booth lights stuttered across Will's jaw as he leaned in, voice low and pleasant enough to make people forget how hard his hands could get. Grease shone on the change tray. A hand-lettered sign promised funnel cakes and truth in the same font, which felt like Harborwick's idea of a joke. Teenagers streamed past with glow sticks and half-eaten corn dogs; somewhere a dunk-tank barker shouted into river wind that smelled of salt and rusted chain-link. [player_name] pushed the angle soft and steady because soft was how she kept Owen hidden without looking like she was hiding him: festival night, seven years back, who saw the sister, who saw the van idling past the funnel-cake smoke, who heard something that did not belong to fireworks or the calliope. She did not need a speech. She needed a detail that stuck—a face, a shout, a man who was not supposed to be near the pier generators when Renny, then a teenager, peeled off toward the water and never peeled back.

"Irene," Will said, laying a grainy flyer on the sticky counter as if it were a tip and not a wound. "Kids called her Renny. Festival night. You worked this strip then. What did you see that never made a tip sheet?"

The vendor's eyes flicked to the flyer, then to Will's badge where the coat had shifted, then to [player_name]—mid-twenties sister still standing in the shadow of sugar smoke like grief had learned to buy tickets. "Lots of kids that night," he muttered. "Lots of nights. I sell dough. I don't sell missing persons."

Will's half-smile arrived on schedule: easy, practiced, the kind that made people lean closer before they noticed the edge. Charm as weapon. Charm as wound. Not clean-cut. Never the detective posters put on recruitment flyers. "I'm not asking you to sell her," he said softly. Soft was worse. Soft meant he had learned how to make danger wear manners. "I'm asking you to remember a shout that wasn't part of the show. A man near the Ferris generator. A girl arguing. Fog rolling in off the water like Harborwick's favorite lie. You were here. Your booth was here. Memory likes grease and fear—it sticks to both."

[player_name] watched the vendor's throat work once. His knuckles whitened on the change tray. Behind him, a rack of paper boats waited for batter that would never make Renny come home. She kept Owen's name out of her mouth entirely. That was the point of this path: witnesses first meant festival talk before stepfather talk, carnival pressure before family detonation, Renny's absence treated as a living investigation rather than a closed grief Ellison could stamp. Missing posters still curled on lampposts along the strip; a mother's voice still looped through local radio on slow news hours; teenagers glanced at empty spaces in the crowd as if a friend might reappear between the Tilt-A-Whirl and the ring-toss. The unidentified remains sat downtown like a dare she refused to answer wrong—claim them Renny too early and she buried hope under rumor; ignore the charm that *could* match her missing bracelet piece and she let someone else write the ending in Ellison's voice.

No one said Solis out loud. No one should. [player_name] only had hints—a raid that left Harborwick quieter than it should have been, a name that traveled in half-whispers between bar stools and pier railings, a silence that felt arranged the way Will's jokes sometimes felt arranged when they died mid-breath. Mentioning it now would turn this booth into a stage and this vendor into a corpse of a lead. Still, the teeth of that sealed past showed when a kid shrieked near the dunk tank and Will's smile flickered, partner-flinch crossing his face like weather he refused to name. Hallway weather. Kid-in-the-wrong-place weather. He blinked it away and was only detective again, mid-thirties and dangerous in the neon, leaning on a counter that smelled like sugar and old oil.

"Talk to me about the generator," Will said, conversational as a man asking for ketchup. "Eleven-forty to twelve-fifteen. Pier security gap. Van idling. Argument that wasn't fireworks. You don't have to like cops. You just have to decide whether you want me polite at your booth or curious about your books."

The vendor's eyes flicked toward the midway exit like a man measuring distance. Will caught the look and dialed the charm up a notch—shoulder angling closer, voice dropping into something velvet with a promise underneath. [player_name] felt the temperature of the pressure change the way she felt river fog change: sudden, bodily, hard to argue with. She could let Will press until the man's denial cracked and festival night finally spilled a usable detail—Renny arguing, a man's silhouette, something that might or might not rhyme with the kept thing about Owen she was still hiding. Or she could catch Will's wrist before the lean turned into a shove and the vendor bolted into the fairway dark, taking every soft lead with him into the river fog.

Will glanced at her across the sticky counter. The look was not permission exactly. It was collaboration with teeth: *this is the path you asked for—witnesses, not Owen—so own the heat of it.* Rain that was not quite rain misted the strip; Harborwick weather never fully committed until it drowned you. A foghorn called inland, low and rude, reminding the carnival that the water still owned the night. She tasted burnt sugar on her tongue and under it the sharper taste of seven years of edited statements, of Renny's hoodie still folded at home, of a silver charm bracelet gap loud as a shout, of remains that Cho would not name and a stepfather she had parked in silence like a car with a cracked windshield she was not ready to drive.

"I don't know about any argument," the vendor said, too fast. "Generator noise. Kids yell. Men leave. Posters went up. Cops asked. I said the same thing then."

"Then say something different now," Will murmured, and the murmur was somehow louder than the calliope. His scarred knuckles rested near the napkin stack—not a fist, not yet, just the shape of consequence. "Those remains upriver are still unidentified. I'm not here to bury a teenager to make a captain's spreadsheet prettier. I'm here because a charm *might* match what her sister kept, and because somebody on this strip saw a night that paperwork sanded smooth. You can be the somebody who remembers, or the somebody who runs. Running looks guilty even when it isn't. Remembering looks brave even when it shakes."

[player_name] stepped half out of the popcorn-cart shadow so the vendor could see her clearly—mid-twenties, not a badge, not a threat, just the sister who had lived inside the missing-person shape for seven years. "Please," she said, and hated how small the word felt against neon and grease. "She was sixteen. Festival night. If you saw her argue with anyone near the rides, if you saw a van, if you heard a shout that didn't belong—I need that more than I need another polite denial. The science still won't say if the upriver bones are hers. I am trying to live in that maybe without letting the maybe go soft."

Will's mouth tilted—approval or hunger, hard to separate on a man who wore charm like a second badge. He did not take over her plea. He let it sit on the counter beside the flyer like a second piece of evidence. The vendor swallowed. A teenager laughed too loudly near the ring-toss. Somewhere a security radio crackled Harborwick codes that meant nothing and everything. Ellison's pressure lived even here, miles from the precinct: clearance language, cooperative family, no hard ID, a revived cold case that made captains hungry and detectives reckless.

"You asked me to chase witnesses," Will said to her, quiet enough that the vendor might have mistaken it for intimacy—and maybe it was. "This is what chasing looks like when the witness prefers dough to truth. I can keep smiling until he talks. Or you can put a hand on me and haul the smile back before he decides the midway exit is safer than my manners."

His shoulder angled another inch. The pink bulb-light cut his cheekbones sharp. Brutal charm fully cocked now, mid-thirties danger dressed as patience, sealed past sitting behind his eyes where Solis almost lived and hallway kids almost joked themselves into existence. [player_name] felt the fork settle into sticky boards and bone: press or pull, lean or catch, let Will's weapon do what she invited it to do or decide the vendor's fear mattered more than the detail she came for.

The vendor's gaze darted again—exit, Will, her, flyer, exit. His hand twitched toward the cash box as if money could buy a different night. Renny's grainy smile waited on the paper, forever sixteen, forever festival-lit, forever not confirmed among Cho's partial remains. Owen stayed hidden by her choice. The remains stayed unnamed by science. Harborwick kept listening whether it wanted to or not.

Will's hand settled nearer the napkin stack, closer to the vendor's white-knuckled grip on the change tray. Too close. Too sure. The calliope hit a sour note and recovered. Fog thickened at the strip's edge where the pier began. [player_name] could still taste peach-plastic memory from Renny's room and rain from the stoop where this path started—hide Owen, push witnesses, own the consequences of asking a man with buried teeth to smile at a carnival booth until the night cracked open.

The choice was how hard Will got to lean—and whether she stopped him in time—while the vendor's breath shortened and the midway exit waited like a third option neither of them could afford to watch him take.`,
  textHot: `Harborwick's festival strip hit [player_name]'s body before it hit her manners: sticky heat under her shirt, neon pulse against her eyelids, burnt sugar clinging to her tongue like a kiss she hadn't asked for. Funnel-cake smoke greased the air; a generator coughed diesel into the river fog; her skin pebbled where the popcorn-cart shadow failed to cool her. She felt William Akers—mid-thirties, brutal charm running hot under the skin—before she saw him fully: that smile that made her nipples tighten even when the work was grief, coat open enough that rain-damp wool and male heat reached her when he passed close, scarred knuckles flexing as if remembering doors that hadn't wanted to learn.

She had chosen witnesses first. That was the 2b bargain written in Renny's room under peach-perfume ghost and a bracelet screaming its missing anchor: hide Owen, push festival mouths, keep Will's hands busy with carnival pressure instead of her stepfather's throat. Owen stayed off the page, off the notebook, off Ellison's clearance hunger—for one more night. Renny stayed a missing teen. Cho's unidentified remains still wore no sister's name. Hope and dread shared the sticky boards under [player_name]'s shoes and, traitorously, shared the low ache between her legs every time Will's shoulder brushed hers in the crowd.

The carnival vendor had already rehearsed denial. Booth lights stuttered across Will's jaw as he leaned in—voice low enough to feel, pleasant enough to make people forget how hard those scarred hands could get. Grease shone on the change tray. Teenagers streamed past with glow sticks; a dunk-tank barker shouted into salt-and-rust wind. [player_name] stayed half in shadow and felt her cunt answer Will's nearness anyway: soft pressure on a hard night, grief and want braided so tight she couldn't tell which made her breath short.

"Irene," Will said, laying a grainy flyer on the sticky counter like a tip and a wound. "Kids called her Renny. Festival night. What did you see that never made a tip sheet?"

The vendor's eyes flicked flyer, badge, then [player_name]—mid-twenties sister standing in sugar smoke like grief that had learned to buy tickets and still get wet for the detective working the booth. "Lots of kids. Lots of nights. I sell dough. I don't sell missing persons."

Will's half-smile arrived on schedule—easy, practiced, the kind that made throats and legs open before people noticed the edge. Charm as weapon. Charm as wound. Not clean. Never clean. "I'm not asking you to sell her," he said softly. Soft was worse. Soft meant danger wearing manners—and [player_name] felt that soft in her clit like a fingertip. "A shout that wasn't part of the show. A man near the Ferris generator. A girl arguing. Fog like Harborwick's favorite lie. Memory sticks to grease and fear."

She watched the vendor's throat work. She kept Owen's name out of her mouth entirely—witnesses first meant festival talk before family detonation, Renny's absence treated as living investigation rather than stamped grief. Missing posters curled on lampposts. The charm that *could* match Renny's missing piece haunted her jewelry box across town. Claim the upriver bones too early and she buried hope; ignore them and Ellison wrote the ending. Hope and dread shared her pulse. So did Will's cologne when he shifted and his coat sleeve brushed her forearm—heat running straight to the base of her spine.

No one said Solis out loud. Hints only: a raid that left Harborwick too quiet, a name in half-whispers, a silence arranged the way Will's jokes died mid-breath. When a kid shrieked near the dunk tank, his smile flickered—partner-flinch, hallway weather, kid-in-the-wrong-place weather—and [player_name]'s stomach dropped even as her body stayed shamelessly aware of him. He blinked it away. Detective again. Dangerous in neon. Sugar and old oil.

"Talk to me about the generator," Will said, conversational as ketchup, lethal as a hand between her legs. "Eleven-forty to twelve-fifteen. Pier security gap. Van idling. Argument that wasn't fireworks. Polite at your booth—or curious about your books."

The vendor's eyes flicked toward the midway exit. Will dialed the charm up—shoulder closer, voice velvet with a promise underneath—and [player_name] felt the pressure change bodily, the way river fog changed: sudden, hard to argue with, wetting her. She could let him press until denial cracked and festival night spilled a usable detail—Renny arguing, a man's silhouette, something that might rhyme with the Owen-shape she was still hiding. Or she could catch Will's wrist before the lean turned shove and the vendor bolted into fairway dark with every soft lead.

Will glanced at her across the sticky counter. Collaboration with teeth: *this is the path you asked for—witnesses, not Owen—own the heat.* Mist beaded on her collarbones. A foghorn called inland. She tasted burnt sugar and under it seven years of edited statements, Renny's folded hoodie, a charm gap loud as a shout, remains Cho would not name, a stepfather parked in silence.

"I don't know about any argument," the vendor said, too fast.

"Then say something different now," Will murmured, louder than the calliope. Scarred knuckles near the napkin stack—not a fist yet, the shape of consequence—and [player_name] imagined those knuckles on her hip, her waist, the inside of her thigh if they survived this booth. "Remains upriver still unidentified. I'm not burying a teenager for a spreadsheet. A charm *might* match what her sister kept. Somebody on this strip saw a night paperwork sanded smooth. Remember—or run."

She stepped half out of shadow so the vendor could see her—not a badge, just the sister inside the missing-person shape for seven years, pulse hammering low and shameless. "Please," she said. "She was sixteen. If you saw her argue near the rides, a van, a shout that didn't belong—I need that more than polite denial. Science still won't say if the upriver bones are hers. I am trying to live in that maybe."

Will's mouth tilted—approval or hunger, hard to separate, and she wanted that mouth on her throat even here. He let her plea sit beside the flyer. Ellison's pressure lived miles away and still pressed her nipples tight under cotton: clearance, cooperative family, no hard ID, reckless detectives.

"You asked me to chase witnesses," Will said to her, quiet enough to be intimacy—and it was. His hip nearly brushed hers behind the counter angle; she felt how hard the chase had made him and bit her tongue. "This is what chasing looks like when the witness prefers dough to truth. I can keep smiling until he talks." His fingers found the small of her back under her coat—claiming, steadying, a brand that shot heat straight between her legs. "Or you can put a hand on me and haul the smile back before he decides the midway exit is safer than my manners."

Brutal charm fully cocked. Mid-thirties danger dressed as patience. Solis almost living behind his eyes. [player_name] felt the fork in sticky boards and bone and cunt: press or pull, lean or catch, let his weapon do what she invited or decide the vendor's fear mattered more than the detail—and more than the unfinished ache Will's hand at her back was feeding on purpose.

The vendor's gaze darted—exit, Will, her, flyer, exit. Renny's grainy smile waited, forever sixteen, forever not confirmed among Cho's partials. Owen stayed hidden. Remains stayed unnamed. Harborwick listened.

Will's hand settled nearer the change tray—too close, too sure—while his other hand stayed warm at the small of her back, thumb stroking once above her waistband like a promise he would collect later with his mouth. Calliope sour note. Fog at the pier edge. Peach-plastic memory. Rain from the stoop. Hide Owen. Push witnesses. Own asking a man with buried teeth to smile until the night cracked.

"Easy," she breathed, not sure if she meant him or herself. Will's eyes flicked to her mouth. Mid-want lived there, open, ugly, earned by seven years of silence sharing air with a detective who collected secrets like scars. The vendor shifted toward the exit half an inch. Will shifted with him, predator-smooth, charm still velvet, body language saying *I will be polite until politeness fails*—and [player_name] felt the choice arrive as pressure in her wrist and ache between her legs.

Harborwick was listening whether it wanted to or not. Owen stayed hidden. Renny stayed missing. The remains stayed unnamed. The choice was how hard Will got to lean—and whether she stopped him in time—while sticky heat and neon and burnt-sugar want braided down her spine and the midway exit waited like a third mouth neither of them could afford to watch him disappear into.

She could still feel his thumb's ghost above her waistband, still taste sugar and the almost of Solis unsaid. Press until the vendor talked—or catch Will's wrist before the lean turned ugly. Both left her wet with consequence. Both left Renny a living question Cho had not answered. Both hurt to leave, which meant both mattered—and [player_name] stood in funnel-cake smoke with her pulse shameless and the tab wide open.

Will waited. The vendor shook. She chose.`,
  choices: [
    { id: "scene4g", text: "Press the carnival vendor until he talks", textHot: "Pin him with Will's charm until the denial breaks and he talks" },
    { id: "scene4h", text: "Stop Will from leaning too hard — vendor will bolt", textHot: "Catch Will's wrist before the lean turns ugly — if the vendor bolts, you lose him" }
  ]
};
