export default {
  id: "scene6a",
  layer: 6,
  title: "Full coop: she opens Renny's locked box with Will",
  text: `Rain had softened to a mist by the time William Akers followed [player_name] up the narrow stairs to the room that still smelled like a teenager who had not come home. Harborwick's foghorn rolled inland from the pier district—low, lonely, the river clearing a throat that had no name yet. The hallway light buzzed. Renny's door stuck the way it always had, paint swollen from seven years of damp winters and no one who needed it opened every morning.

Inside: the hoodie folded in the top drawer like a prayer that refused to become laundry. A silver charm bracelet on the desk, missing one charm. Posters curled at the corners. A lockbox under the bed, black metal, scratched, the kind of cheap strongbox a girl buys with festival money and a secret she is not ready to trust to a sister's open face.

Will stood in the doorway with his cracked notebook closed against his thigh. Mid-thirties, rain still darkening his hair, scar cutting his left eyebrow, charcoal shirt smelling of precinct coffee and salt. Brutal charm banked low—velvet over a blade, sheathed for a dead girl's room—but his grey-green eyes tracked everything: the hoodie, the bracelet gap, the box, [player_name]'s mid-twenties hands shaking as she knelt and dragged the metal into the light.

"Ellison gets the pier night," he said quietly. Not a question. Full cooperation had bought them this hour under Captain Mara Ellison's reluctant seal—Owen Vale named near the festival pier, the omission confessed under fluorescent honesty, access kept on a leash. "This is what she does not get until we know what it is. You open it with me. We decide what becomes evidence and what becomes grief she will weaponize for clearance."

[player_name]'s throat worked. Renny had been a teenager when she vanished—seven years of absence folded into cotton and silver and this locked scrap of trust. Upriver, unidentified partial remains waited in Dr. Lila Cho's careful language: age range that *could* fit; a charm that *could* match the missing bracelet piece; lab ID pending. Hope and dread shared the bedroom air like co-counsel who refused to leave. The remains were not Renny until science said so. Rumor had already tried to bury her. [player_name] would not help.

"She left the key in the hoodie pocket," [player_name] said. Her voice held. Barely. "I found it three years ago and put it back. I told myself opening it alone would be stealing the last private thing she had. That was a lie. I was afraid of what she kept."

Will knelt opposite her—not touching, close enough that soap and scrubbed-dark past filled the space between their knees. When Ellison had almost named Nina Solis upstairs, Will had touched his ribs like checking a bruise that never yellowed. He did not explain now. Dark past hummed under his badge: a partner's fall, a sealed IA file, a hallway he would not narrate in a missing girl's bedroom. Teeth showing. He offered [player_name] his attention instead—the dangerous kind, the kind that opened people.

"Afraid she was in trouble," he said. "Or afraid she was trying to tell you, and you already knew enough to burn the house down."

"Both." [player_name] slid her hand into the hoodie's pocket. The fabric still held a faint ghost of Renny's cheap vanilla perfume and river wind. The key was small, warm from being held against cotton for years of cowardice. Attraction was a stupid animal to bring into this room, and it came anyway: Will's scar catching the desk lamp, the sleep-deprived set of his shoulders, the way he watched her like the lock was also a kind of confession between them. Mid-thirties to her mid-twenties—close enough to burn, far enough that the badge still felt like a different country. She wanted his steadiness and hated that she wanted it while Renny's fate stayed contested bone and rumor.

The key turned. The lid stuck, then gave with a soft metallic complaint that sounded too loud in a room built of silence.

Inside: a thin journal bound in cracked purple leather. A folded Harborwick pier map with pencil Xs that did not match any tourist brochure. A USB drive wrapped in electrical tape. And, tucked beneath the journal, the edge of an envelope—cream paper, Renny's handwriting on the front: *For [player_name] — only if.*

Will did not reach first. He waited. Brutal charm's quieter twin: patience as a blade laid flat. "Cho still has no hard ID," he said, as if the reminder could cushion whatever lived in paper. "Whatever this is, it does not make those remains your sister. It makes her a girl who was looking at something Harborwick did not want looked at. Smuggling. Tampering. A chain. We read carefully. We do not invent a body because a journal is dramatic."

[player_name] lifted the journal. The first page smelled like dust and teenage certainty. Renny's looping script named warehouses, a clerk's initials, Owen's late nights, a fear that sounded older than seventeen. Not a confession of death. A map of trouble. The kind of trouble that made unidentified remains upriver feel like a threat with a pulse—and also like a maybe that still had room for breath somewhere else.

Will's notebook opened at last. Pen scratched. Rain freckled the window. Somewhere downstairs a radiator knocked like a second interrogation clock. [player_name] read passages aloud when her voice worked and passed the book when it did not. Will translated Renny's teenage shorthand into cold-case grammar without stripping the girl out of it. Once his knuckle brushed [player_name]'s wrist as they both reached for the map. Heat jumped. Neither named it. The room was already too full of Renny to hold a kiss without turning grief into something uglier—and yet the almost of his nearness lived under [player_name]'s ribs like unfinished weather.

"Ellison will want the USB tonight," Will said. "The journal on record. The map photographed. She will also want to know if Owen's name in here matches the pier sighting you finally put on paper." His mouth twitched—almost the velvet-blade smile, almost a joke about family dinners and evidence tags—and died mid-breath when his eyes found the envelope still half-buried. "That letter stays face-down until you say otherwise. Full coop does not mean I steal the last private page from a sister. It means I ask you to choose whether private is still protection or just another way of leaving her alone with what she knew."

[player_name] stared at Renny's handwriting on the cream paper. *Only if.* Only if what—if [player_name] was brave enough, if Owen lied, if the river gave something back that science could not yet name? The charm bracelet on the desk winked under the lamp, gap like a missing tooth. Cho's lab still said *pending*. Hope still had a throat. Dread still had teeth.

Will sat back on his heels. Cracked knuckles pale against his thighs. "Two doors from here," he said softly. "We open the journal all the way—every warehouse mark, every initial, the smuggling chain Renny was tracking. Or you keep that letter hidden still—slide it into your pocket before I catalogue the rest—and we pretend full cooperation has a soft edge. I will feel the lie. I always feel the lie. But I will also understand why a sister might need one scrap that is not yet evidence."

Fog pressed the glass. The pier district breathed salt through the cracked window. [player_name] tasted burnt coffee on Will's breath from across the small distance, tasted fear, tasted the sharper taste of almost-trust climbing her throat. Renny's hoodie lay open on the floor like a body that was not a body. The lockbox lid yawned. The USB waited like a held breath. The letter waited like a second spine.

The desk lamp threw a yellow circle that made the missing charm on Renny's bracelet look like a deliberate wound. [player_name] thought of Owen Vale's too-calm morning voice seven years ago, of Ellison's tablet casting cold light under a captain's chin, of Cho's careful refusal to christen bone with a sister's name before the lab finished speaking. Full cooperation had felt like cutting a rope and finding it was also a noose; kneeling here with Will made the noose into something that could also be a handhold. She wanted both truths at once: Renny might be among the upriver dead, and Renny might still be breathing somewhere Harborwick refused to look. The journal's teenage certainty argued for danger without arguing for a corpse. That ambiguity was sacred. Will treated it as sacred too, which was one of the reasons attraction kept climbing the stairs with them even when grief tried to shut the door.

Outside, a truck hissed past on wet asphalt. Harborwick remembered everything except the official story. Inside, William Akers—detective with a sealed silence and a smile that opened people—watched [player_name] the way a man watches a fuse he is not sure he should light. Attraction hummed unwanted and undeniable: his scar, his competence, the dangerous care of refusing to christen remains with a name Cho had not given. [player_name]'s palms were damp against purple leather. Choosing the journal fully meant handing Renny's investigation to the badge and to the man who might love the woman who had obstructed it. Choosing the hidden letter meant keeping one warm secret between her ribs while the case map bloomed around a silence Will would eventually find anyway.

The key cooled in her fist. Renny's fate stayed contested: not named, not buried, not safe. The foghorn answered from the river, low enough to feel in the bones. Whatever [player_name] did next would either open the sister's kept truth under partnership light—or teach a cold-case detective that some locks still belonged to family even when family had already failed the girl who trusted a black box under a bed.`,
  textHot: `Rain had softened to mist by the time William Akers followed [player_name] up the narrow stairs, and the air between their bodies was already too warm for a dead girl's hallway. Harborwick's foghorn rolled inland—low, lonely—vibrating in [player_name]'s ribs like a second heartbeat she wanted to press against his chest. Renny's door stuck. Will's hand covered [player_name]'s on the knob for a second—heat, calluses, cracked knuckles—and the contact shot straight between her thighs before either of them pretended it was only about the lock.

Inside: hoodie folded like a prayer. Charm bracelet missing one piece. Lockbox under the bed. Will shut the door with his heel and the click sounded like consent and like blasphemy. Mid-thirties, rain-dark hair, scar through his left eyebrow, charcoal shirt clinging where Harborwick damp had found him. Brutal charm banked for the room—but his grey-green eyes dragged over [player_name]'s mouth, her throat, the rise of her breasts under her blouse, then forced themselves to the box as if professionalism were a cock ring he was choosing to keep on for the girl's sake.

"Ellison gets the pier night," he said, voice low enough to stroke. Full coop had bought this hour: Owen named, omission spent, Captain Mara Ellison's seal reluctant on their access. "This we open together. We decide what becomes evidence and what becomes something she will fuck your grief with for clearance metrics."

[player_name] knelt. Mid-twenties. Pulse hammering in her throat and lower. Renny—teenager then, missing seven years—still unnamed among Dr. Lila Cho's upriver remains. Charm that *could* match. Lab pending. Hope and dread fucking the same oxygen while Will knelt opposite her close enough that soap, salt, and scrubbed-dark past filled her nose until she had to part her lips to breathe him. When Ellison had almost said Nina Solis, Will had touched his ribs—and the flinch still lived in his shoulders. Broken men should not be this hot. William Akers wore broken like cologne [player_name] wanted to lick off his pulse point.

She slid her hand into the hoodie's pocket. Vanilla ghost, river wind, key warm from years of cowardice. Will watched her fingers the way he might watch them on his belt. "Afraid of what she kept," [player_name] admitted, and her voice came out rough, as if he had already been kissing her throat.

"Afraid she was trying to tell you." His knee brushed hers. Deliberate. Electricity. Wet heat gathered in [player_name]'s cunt; she felt it and burned with shame and hunger both in a room that smelled like absence. "Open it. I am right here. I will not let the box become a second burial."

The key turned. Lid gave. Journal. Pier map with pencil Xs. USB in tape. Cream envelope: *For [player_name] — only if.*

Will did not grab. He waited with the patience of a man who knew how to make waiting feel like fingers on a clit—attention as pressure, as promise. "Cho has no hard ID," he murmured. "This does not make those bones Renny. It makes her a girl who was looking at Harborwick's throat. We read. We do not invent a corpse because paper is dramatic. And if you need my hands steady while you do it—" He held them out, cracked knuckles pale, and [player_name] put the journal into his palms so their fingers had to tangle.

They read. Her voice broke on warehouses and Owen's late nights and a clerk's initials. His pen scratched. Once, when she leaned to point at an X on the map, her breast brushed his upper arm and both of them went still as held breath. Will's jaw flexed. [player_name] felt her nipples tighten traitorously against cotton; she shifted and wet fabric clung to her clit like a filthy secret Renny's posters must not witness. Will's gaze flicked down—caught the flush at her throat, the parted lips—and the brutal charm flickered, velvet-blade hunger banked hard because fucking in this room would be a desecration and also because he wanted it anyway.

"Ellison will want the USB tonight," he said, mouth close enough that coffee-breath warmed [player_name]'s cheek. "Journal on record. Map photographed. That letter—" His eyes found the cream edge still half-buried, and his voice dropped into the register that made her cunt clench around nothing. "—stays face-down until you say. Full coop does not mean I steal the last private page. It means I ask whether private is protection or just another way you leave yourself aching and alone with what she knew."

[player_name] stared at Renny's handwriting while her body throbbed absurdly, heartbeat in her clit, thighs pressed slick. Will sat back on his heels; the movement pulled his shirt taut across his chest, and she could map where her mouth wanted to land—scarred brow, throat, the hard line she had not seen and somehow already ached for. Mid-thirties detective. Mid-twenties sister of the missing. Close enough to burn. His hand settled over hers on the journal, heavy, warm, a claim that was not yet sex and already felt like the start of being opened.

"Two doors," he said softly. Thumb stroking the inside of her wrist—once, filthy metronome. "We open the journal all the way—every mark, every initial, the smuggling chain—and we walk it into the next layer with Ellison's seal and my notebook and whatever courage you have left after locking this under a bed while I watch you strip truths I want to taste off your tongue. Or you keep that letter hidden still—slide it into your pocket against your thigh where I will know it's warm—and we pretend full cooperation has a soft edge. I will feel the lie. I always feel the lie. It will make me hard and angry and careful with you in ways I should not catalogue. But I will also understand why a sister needs one scrap that is not yet evidence—and why your body is shaking from more than grief."

She almost said his name like a prayer and swallowed it. Saying *Will* in this room felt like inviting him into Renny's last private weather, and she was not sure she had the right—only the need. He smelled like rain that had failed to wash a worse year off his skin. When he leaned to photograph the map with his phone for a controlled copy Ellison could not yet demand, his shoulder pressed [player_name]'s, solid and warm, and her cunt clenched so hard she had to breathe through her nose to keep from making a sound the posters would remember. "Steady," he murmured, not looking at her face, which somehow made it filthier—care aimed at her body while his eyes stayed on evidence. His free hand found the small of her back, palm flat, holding her upright over the open box as if she might tip into it and drown. The touch burned through her blouse. She wanted that hand lower. She wanted it nowhere. She stayed trembling under it while the phone camera clicked and Renny's Xs became pixels that could become a warrant.

"You are shaking," Will said. Not accusation. Inventory. The detective in him catalogued; the man in him sounded wrecked by what the catalogue included. "Grief. Want. Both. I can feel both through your shirt. That is a problem for my badge and a fact for my cock, and I am choosing—right now—to keep my mouth on the case instead of on yours. Do not mistake the choice for lack of hunger. I could put you on this floor beside the map and fuck the seven-year lock out of you until you forgot Ellison's name. I will not. Not on Renny's carpet. Not while Cho still says *pending*. But later is a word with teeth, [player_name], and I am already biting it."

The honesty landed between her legs like a stroke. Wetness slicked further; she pressed her thighs together and felt how ruined she was from proximity and truth alone. Will's hand left her back as if the leaving cost him. He sat back. The hard line in his trousers was no longer almost—visible, denied, reciprocal. [player_name] stared at the cream envelope until the handwriting blurred, then forced her eyes to his scar, to the wound he wore as armor, to the raid-bruise silence he still would not open. Dark past under the badge. Secrets clenched. She wanted to unzip him and also wanted to hand him every page Renny had trusted to metal. The two wants were not opposites tonight. They were the same fever wearing different clothes.

Fog pressed the glass. Pier salt leaked through the cracked window. [player_name] tasted copper where she had bitten her lip, tasted him, tasted the unfinished almost of his mouth an inch from hers over purple leather and a USB that might name the chain that wanted Renny silent. Renny's hoodie lay open on the floor. The lockbox yawned. Hope still had a throat. Dread still had teeth. Remains still unnamed. Charm still only *like*.

Outside, Harborwick's rain whispered on warehouse glass somewhere beyond the block. Inside, [player_name]'s cunt ached unused and honest, want braided into cooperation until she could not tell if she was opening Renny's locks or opening herself for a detective with a past he would not speak and a hunger that made Ellison's word *liability* taste like foreshadowing. Choosing the journal fully meant handing the sister's investigation to the badge while Will's nearness promised that later—after evidence tags, after Cho's careful *pending*—there might be a bed that was not this one, a night where grief and sex could coexist without eroticizing the river. Choosing the hidden letter meant keeping one warm secret against her body while his eyes tracked the pocket, while want cooled into a bruise she would press, while the case map bloomed around a silence that still smelled like her arousal and his restraint.

The key cooled in her fist. The foghorn groaned again. [player_name] almost moaned with it. Will did not kiss her—not yet, not over Renny's map—but the refusal lived in the air like unfinished sex, and the choice hung between the cream envelope and his mouth like a fuse neither of them could stop watching.`,
  choices: [
    { id: "scene7a", text: "Open the journal with Will", textHot: "Open the journal with Will" },
    { id: "scene7b", text: "Keep one letter hidden still", textHot: "Keep one letter hidden still" }
  ]
};
