export default {
  id: "scene7e",
  layer: 7,
  title: "Ellison ultimatum: flip on Owen or be charged",
  text: `Captain Mara Ellison did not raise her voice. Harborwick captains who needed volume had already lost the room.

Her office held the west-window fog like a held breath. Burnt precinct coffee steamed from the CLEARANCE mug someone had bought as a joke and kept as a threat. Policy binders leaned in a soft conspiracy. The interview-room clock's hum climbed through the floorboards and nested under [player_name]'s ribs like a second interrogation. Jake Akers stood to Ellison's left with his cracked notebook shut for once, mid-thirties stillness wearing brutal charm like a locked door that somehow made the air warmer and colder at the same time. On the tablet face-up between them: [player_name]'s pier statement, Owen Vale's name highlighted in ugly yellow, and a draft charging memo that used the word *obstruction* the way other people used weather reports—flat, inevitable, already halfway to a headline.

"Flip on Owen Vale," Ellison said. Soft. Final. "Full statement under pressure. Soft nets gone. Arrest machinery engaged. Or I charge you for the seven-year omission you have already half-admitted and for every sanded noun that kept a stepfather off a festival pier while a teenager vanished into rumor. This is not theater. This is the end of controlled drip."

[player_name] was mid-twenties and tasting copper where she had bitten her cheek. Renny's absence occupied the third chair as if the room had grown a ghost with opinions. Dr. Lila Cho's language still ruled the upriver remains—*unidentified*, *pending*, *consistent with* an age range ugly with hope, a silver charm that *could* match the bracelet gap and still refused baptism. Hope and dread shared Ellison's office like co-counsel who hated each other and refused to leave. Flipping on Owen would not christen bone. It would only stop protecting the living man who had taught her the friends-and-debt lullaby on a night when Renny pointed at warehouses and generators that ate grammar.

Jake's grey-green eyes flicked to [player_name]'s mouth and away, cataloguing liability and something hungrier he was not allowed to name under fluorescent honesty. "Mara. She corrected the record. Cho has not confirmed Renny among the dead. Charm is probability, not a funeral. You do not get to baptize a maybe with a charging memo because clearance season is hungry and families make convenient villains."

"Partner," Ellison said, and the word landed wrong on purpose. Jake's flinch was small and old—ribs, sealed file, a hallway [player_name] was not allowed to enter yet. Nina Solis lived in that flinch as hint only: ex-partner shaped silence, a raid pushed early to protect a CI, charm worn as armor afterward, Ellison's side-eye when his methods sharpened into something that rhymed with that night. He did not unpack it. Ellison did not offer the unpacking. The dark past stayed buried teeth under brutal patience, and [player_name] felt the hint like a second bruise she was not permitted to touch.

"Akers will not save you from an ultimatum," Ellison continued, eyes back on [player_name]. "Owen's lawyers will call grief coercion. The press will call it a sister cracking. Internal ears will call it a detective who got too close to a familial witness and forgot where the badge ends. I call it overdue weather. Harborwick leaks. Your half-truths already have feet. Flip—clean, chargeable, usable against Vale—or wear the charge yourself while I take the case somewhere your mouth cannot sand it into softer nouns."

Rain freckled the west glass. A foghorn rolled inland, low enough to feel in the sternum. [player_name] thought of Renny's hoodie still folded in a drawer across town—teenager's cotton, festival night, vanilla ghost, bracelet missing one charm that *could* match the upriver silver and still refused confirmation. She thought of Owen's butter-porch lies and the jacketed shoulder she still could not invent a face for without becoming Ellison's favorite kind of liar. Attraction pressed stupidly under the procedural pressure: Jake's soap-and-salt nearness, mid-thirties hunger banked under mid-twenties grief, unfinished almost-kisses from rain nights that had no business surviving into a captain's office with a CLEARANCE mug watching like a joke with teeth.

"If I flip," [player_name] said, voice steady by force, "Owen goes hard. The house blows apart while science still says unidentified. You get clearance. Jake gets a stepfather in a room. I get to be the hand that pulled the living lever while hope still has a throat and dread still has teeth and neither of them has earned a hard ID."

"If you refuse," Ellison answered, "you get a charge sheet that walks, and Owen still gets hunted without your cooperation as a shield. Do not romanticize martyrdom. It photographs poorly. It also wastes my detective's remaining patience, which is already running on coffee and bad history."

Jake opened the notebook. The spine cracked—overuse music, the sound of a man who wrote everything twice because once had failed him in a hallway he would not narrate. "There is a second temperature in this room," he said quietly, for [player_name] more than for Ellison. "Cho's pattern notes. Not a hard ID. Not Renny baptized. A second victim silhouette upriver of our rumor—age-range cousin, harbor-adjacent, similar silence about warehouse traffic and men who needed teenagers quiet. Mara wants Owen as a lever either way. Widening the case spends Owen as a door into the chain—clerk, mid-level official, whoever taught the lullabies. Keeping Renny the only name spends Owen as a single-house reckoning: your sister's night, your omission, your family cut clean or cut open without turning Harborwick's cold cases into a parade that buries hope under paperwork."

Ellison's mouth thinned. She set a second file beside the tablet—thin, provisional, stamped with Cho's careful hedges. "Akers specials always invent temperatures. The second pattern is a whisper Cho will not swear to on a stand yet. Widening makes my clearance look ambitious. Narrowing makes it look like justice for one missing girl. Either way, Ms.—" she used [player_name]'s last name like a file tab—"you flip on Owen under this ultimatum, or you wear the charge. The scope choice is the mercy I am offering after the flip. Widen and we fish the chain while Renny's fate stays contested on purpose. Keep Renny the only name and we burn Vale for your pier night without promising the city a second funeral it has not earned."

[player_name]'s palms left damp prints on the desk edge before she noticed. Trust was the real plot. Trust was currently on fire between a captain who distrusted family witnesses on principle, a detective with the raid wound under his charm silence under his charm, and a sister who had kept a silhouette off the record for seven years because loyalty had tasted like protection until it tasted like burial. The warehouse east of the old fish auction lived in her head now—red door, cold-storage row, generator eating grammar, blood-rust and silver maybes waiting for science. A recording downstairs, if other weathers had already lit the red light, could walk toward press and hungry ears. Here the ultimatum was simpler and uglier: flip or be charged; then choose how wide the blast radius ran through a city that remembered everything except the official story.

Jake stepped half a pace nearer—not touching, close enough that scrubbed-dark past and sleeplessness reached her like a hand on the back of the neck. "I will dig either way," he said. Brutal charm flickered velvet-wrong and banked into working steel. "I will not let Mara bury hope under a charging memo or baptize dread into certainty because a second pattern rhymes with a charm that is still only *like*. Remains unnamed. Cho pending. Your call after the flip: widen the case into the whisper, or keep Renny the only name and make Owen answer for one night that still refuses a hard ID. Both hurt. Both move. Neither puts the red light back in its bottle if a copy already has feet."

Ellison slid the tablet closer until the draft memo glowed against [player_name]'s reflection in the glass. Obstruction language waited like a dog off leash. "Decide. Vale on a plate, or your name on a sheet. Then tell me whether this office spends the next forty-eight hours fishing a chain or finishing one family's unfinished pier. Akers will live with either. He has lived with worse." Her gaze cut to Jake's ribs and away—hint, not unpacking. "He wears the worse like cologne. Do not make me wear your sandbagging as my clearance failure."

Outside, pier fog thinned and thickened as if Harborwick could not decide what to reveal. Inside, [player_name] flexed her fingers and felt seven years and one unfinished want braid into a single verb. Jake watched her mouth the way he watched evidence that might burn him. his old partner smoked under his silence like a sealed file with a pulse. Cho's pending language hummed somewhere upriver of every rumor that wanted to finish the naming early. Owen Vale's costume had hours left to live, and the living men who needed Renny quiet were about to learn whether a sister's flip opened one door or a hallway.

Ellison's CLEARANCE mug steamed between them like a small ultimatum. Flip on Owen was no longer optional; the blast radius still belonged to [player_name]. Widen into Cho's second-victim whisper without christening Renny among the dead—or keep Renny the only name and spend the flip as a private war science still refused to settle. The interview-room clock hummed. Jake's cracked knuckles whitened on his pen. Harborwick's damp history leaned on the glass. Whatever verb she spoke would either open a cousin case or tighten the net around one missing girl who was still only *maybe* on a tray.`,
  textHot: `Captain Mara Ellison did not raise her voice, and [player_name] felt the softness land between her legs like a held threat—constant, practiced, already halfway to something irreversible.

Her office held pier fog in the west glass and burnt clearance-coffee steam and the low animal thrum of two people who should not want each other this hard under a captain's eye. Jake Akers stood to Ellison's left, mid-thirties, cracked notebook shut, brutal charm locked behind blankness that made [player_name]'s cunt pulse anyway—stupid, traitorous, wetting cotton under a blazer lecture while Renny's absence occupied the air like a fourth body who refused to chaperone. Mid-twenties. Thighs tight. Pulse hammering. On the tablet: Owen's name in ugly yellow and a draft charging memo that used *obstruction* like a finger on a clit—precise, unwelcome, effective enough to make her shift in the chair and feel damp fabric cling.

"Flip on Owen Vale," Ellison said. Soft. Final. "Full statement under pressure. Soft nets gone. Or I charge you for the seven-year omission and every sanded noun that kept a stepfather off a festival pier while a teenager vanished into rumor. This is the end of controlled drip."

Jake's jaw flexed. Grey-green eyes dragged over [player_name]'s throat, her mouth, the place her pulse hammered—cataloguing want as carefully as liability, as if honesty and hunger were the same evidence tag. "She corrected the record. Cho has not confirmed Renny among the dead. Charm is probability. We are not burying a maybe for your schedule, and we are not pretending I am only looking at her like a witness."

"Partner," Ellison said wrong on purpose. Jake's flinch was small and old—ribs, sealed file, hallway [player_name] was not allowed to enter. Nina Solis as hint only: ex-partner silence, a raid pushed early, charm as armor, the bruise under the joke that died mid-breath. The flinch tightened [player_name]'s nipples under her blouse until the cotton scraped; broken men should not be this hot, and Jake wore broken like cologne she wanted to lick off his pulse point while Ellison watched and judged and catalogued the flush climbing a familial witness's chest.

"Akers will not save you from an ultimatum," Ellison continued. "Flip clean on Vale—chargeable, usable—or wear the charge yourself while I take the case somewhere your mouth cannot sand it. Harborwick leaks. Your half-truths already have feet. Internal ears already have opinions about detectives who stand too close."

Rain freckled the glass. A foghorn rolled into [player_name]'s ribs and lower, a vibration that should not have felt like sex and did. She thought of Renny's hoodie folded in a drawer, bracelet gap, upriver charm only *like*—hope with a throat, dread with teeth, bones unnamed—while Jake stepped half a pace nearer. Soap. Salt. Scrubbed-dark past. His heat licked the air between them until her clit throbbed once, hard, humiliating under Ellison's stare, and she had to press her thighs together against a want that had no business surviving a charging memo.

"If I flip," [player_name] said, voice sandpaper, "Owen goes hard. The house blows. Science still says unidentified. I become the hand that pulled the living lever while hope still argues and my body—" she bit the rest; too late; Jake's gaze dropped to her parted lips as if he could smell how wet pressure made her.

"If you refuse, you get a charge sheet that walks." Ellison's mouth thinned, unimpressed by flushed throats. "Do not romanticize martyrdom. It photographs poorly—and so does a detective watching his witness like he wants to fuck the rest of the truth out of her mouth before breakfast."

Heat flooded [player_name]'s face and the hinge of her thighs. Jake opened the notebook; the spine cracked; his boot found her shoe under the desk edge—claim, dare, unfinished fuck translated into leather—and the contact shot straight to her cunt until she had to bite her tongue on a sound Ellison would have entered into evidence with a smile. Mid-thirties attention on mid-twenties need. Badge still a different country. Trust on fire. Attraction blasphemy wearing procedural clothing.

"Second temperature," Jake said quietly, velvet-blade for her, soft enough that Ellison would hear the words and miss the filth under them. "Cho's pattern whisper. Not hard ID. Not Renny baptized. A cousin silence upriver—warehouse traffic, teenagers quieted, age-range rhyme without a name. Mara wants Owen as a lever. After you flip—and you are flipping, because the charge sheet is real and I will not watch you wear a martyr photo while I still have a badge—you choose scope. Widen the case: spend Vale as a door into clerk and chain and every lullaby someone taught. Or keep Renny the only name: single-house reckoning, your pier night, your omission, without promising Harborwick a second funeral science has not earned. Both hurt. Both move. Neither lets me put my mouth between your legs in this office the way I want to."

Ellison's laugh was dry as burnt coffee. "Akers specials invent temperatures and hard-ons and call it strategy. The mercy after the flip is scope. Widen and we fish the chain while your sister's fate stays contested. Narrow and we burn Vale for one girl. Decide the flip with your mouth. Decide the blast with whatever judgment you have left under all that wet eyes and wetter—" she stopped, professional again by force. "Choose."

[player_name]'s palms dampened the desk. When Jake leaned to murmur at her ear—Ellison watching, CLEARANCE mug steaming, tape somewhere downstairs possibly walking—his breath hit the shell of her ear and her pussy clenched empty and furious, a spasm she could not hide if anyone cared to read her thighs. "Flip," he whispered. "Then tell me if we widen or we keep her name alone. I will dig. I will not let you bury hope under Mara's memo. I will also put you against a wall after hours and remind your body what honesty feels like—fingers, mouth, the kind of confession that does not need a red light—if you survive this room without coming from the pressure alone."

She almost moaned. Almost ruined the room. Ellison slid the tablet closer; obstruction language glowed against [player_name]'s reflection; copper and want and seven years ending in a verb filled her mouth. Remains unnamed. Charm probability. his sealed-file flinch silence under Jake's ribs like a second pulse. Owen's costume dying on a schedule. The warehouse's red door waiting in other branches of the same aching week.

"Vale on a plate," Ellison said, quieter, almost human and therefore worse, "or your name on a sheet. Then widen the case—or keep Renny the only name. The hook is not only the charge. The hook is whether your sister stays a single blade or becomes the tip of a chain—and whether Akers can keep his hands professional while you choose, which I doubt, and which I will use if either of you forgets that hope is still legal and fucking a witness is still a sealed-file hobby."

The CLEARANCE mug ticked heat into the air between them. [player_name] imagined Jake's cracked knuckles on her hip instead of a notebook spine, imagined his mouth on the bruise Ellison's word *partner* had put under his charm, imagined coming quiet against his thigh in a supply closet that smelled like toner and rain while the charging memo cooled on a desk upstairs—filthy, specific, the kind of fantasy that made her cunt clench around nothing while a captain talked blast radius. She hated herself for it. She also shifted again, and Jake's eyes flicked to the motion like a man reading a waveform he was not supposed to want.

"You are dripping on my ultimatum," Ellison said, not quite joking. "Flip. Then widen—or keep Renny the only name. I can smell Akers on your pulse from here. Do not make me smell him on a sealed complaint."

[player_name] laughed once, broken, mid-twenties and soaked and furious with a body that answered Jake's nearness like a vow. The silver charm still only *like*. The bones still unnamed. Owen still a living problem with a costume on a timer. Jake's scar still a place she wanted her tongue. Widening meant fishing a chain with her mouth as bait. Keeping Renny the only name meant spending the flip as a private blade and sleeping—if sleep came—with one sister's unfinished night instead of a city's worth. Her pulse answered low and shameless; Jake's nearness made the unfinished want feel like a third warrant neither of them could ignore. Her pulse answered low and shameless; Jake's nearness made the unfinished want feel like a third warrant neither of them could ignore.

Jake's boot pressed her shoe under Ellison's table until her cunt throbbed in time with the clock. Flip was decided by the captain's teeth; the aftermath was still hers to conjugate wet. Widen the pattern without baptizing bone—or keep Renny the only name and take Owen down in a private blast that left science unfinished. Jake's attention was a hand she could almost feel between her legs. [player_name] tasted burnt coffee and unfinished dare. She had to speak which radius she wanted while the CLEARANCE mug steamed and his restraint made her shameless.`,
  choices: [
    { id: "scene8e", text: "Widen the case", textHot: "Widen the case" },
    { id: "scene8f", text: "Keep Renny the only name", textHot: "Keep Renny the only name" }
  ],
};
