export default {
  id: "scene6o",
  layer: 6,
  title: "She shields Will from Ellison's politics",
  text: `She shields Will from Ellison's politics smelled like burnt precinct coffee and practiced smiles.

Captain Mara Ellison's office was glass and judgment. Harborwick rain streaked the window behind her desk. A fog horn spoke faintly from the harbor beyond brick, as if the city wanted a seat at the table. William Akers stood at parade-rest that did not fool anyone—mid-thirties, scar nick pale under fluorescents, late smile banked into something almost polite, whitened knuckles flexed once behind his back where Ellison could not see. [player_name] sat in the familial-contact chair with Renny's absence pressed under her ribs and the shield role still warm in her palms from Marta's trailer: soft voice, sister mesh, the choice to stand between Will and the machine that wanted him managed.

"Detective Akers used a civilian to soften a reluctant vendor," Ellison said without preamble. "Then he brought that civilian into planning weather and off-procedure proximity that Internal has already sniffed. Explain why I should not pull him off the cold-case revival and hand your sister's file to someone who does not look at you like a liability with a pulse."

Will opened his mouth. [player_name] spoke first—shield, private loyalty, politics as a room she had chosen to enter. "Because he is the only detective treating the upriver remains as unidentified instead of a closed grief," she said carefully. "Dr. Lila Cho has not named them. The charm is still only *like* Renny's missing piece. Hope and dread are still sharing my ribcage. Will has not invented a funeral to clear your calendar. That is method, not romance—even if romance is also true."

Ellison's gaze flicked between them. Distrust lived there like a permanent fixture. "Romance is exactly the word Internal used. Soft nets. Sister-shaped interviews. Conference rooms after hours." She tapped a folder that looked thick enough to bruise. "Nina Solis is not on today's agenda. Sealed stays sealed. But ash has a smell, Akers, and you reek of old smoke when you get sharp around this woman. I want clearance language. I want a detective who can still take an order. I want a familial witness who understands that shielding a badge can look like obstruction if she is not careful."

Will's jaw worked. The flinch at the old partner-name was small and real—not a confession dumped on Ellison's blotter. "She translated a carnival scrap I would have burned into blankness," he said, voice soft and precise. "Red door. East. Numbers spit like *you people*. That is Renny pointing. That is living geography. Pulling me now is politics wearing caution's coat."

"Politics is my job," Ellison said. "Yours is not to need a sister as a soft toy."

[player_name] tasted copper and pier salt memory. Festival fog. A silver bracelet missing one charm. Renny at sixteen pointing east while a clean jacket held her wrist. Owen still unnamed on any official page—her kept pier sighting still pressing her tongue while she sat here lying pretty enough to keep Will's rope intact. The irony was salt. Seven years of silence had taught her how to sit still in rooms that wanted her broken open. She used the lesson now for him instead of against the truth. "I am not a soft toy," she said. "I am cooperative family who prefers soft nets because hard nets make pier people forget. You can write that in a memo. You can write that I asked Detective Akers to keep the vendor's lease out of his teeth. You can write that I will sit in briefings, drink your burnt coffee, and look manageable while he hunts. What you cannot write—yet—is that the remains are Renny. They are not confirmed. Do not clear hope just to clear a column."

Silence stretched. The clock hummed. Somewhere down the hall a printer spat forms that would outlive mercy. Will looked at [player_name] then—hazel, tired, hungry for a break that would not eat them—and the brutal charm he usually wore like armor softened into something that might have been gratitude if gratitude came with teeth.

Ellison exhaled through her nose. "Forty-eight hours of rope. Controlled access. No more civilian-led interviews without my stamp. Akers stays lead unless Internal upgrades shadow to storm. You—" a nod at [player_name] "—stay visible as cooperative. Soft. Useful. If I smell sandbagging, I cut the rope and I cut him. Clear?"

"Clear," Will said.

"Clear," [player_name] echoed, shield humming under her sternum like a second heartbeat.

They left Ellison's glass for the bullpen's fluorescent weather. Detectives glanced and glanced away. Will did not touch her until the stairwell—then his hand found the small of her back, claiming, steadying, professional enough to deny if a camera blinked. Rain-dark glass. Harborwick's warehouse lights smeared beyond like unfinished maps. "You lied pretty," he murmured. "You also told a truth that saved my badge for two days. That is politics. That is you standing between me and a captain who prefers numbers to names." His late smile arrived wrong and fond. "His ex-partner took a fall I should have shared. You just refused to let Ellison make you my next shared fall. I do not know how to thank you without sounding like a bastard who likes soft nets."

[player_name] leaned into his hand despite herself. Trust under interrogation lights. Attraction that tasted dangerous. "Thank me by not becoming the lean that makes witnesses blank. Thank me by keeping Cho's *pending* sacred. Thank me by remembering Renny is still a pointed finger and unidentified bones, not a clearance metric."

"Done," Will said. "Also not done. Because shielding me from Ellison bought rope—and rope has two ends. One end is the machine: memos, briefings, me smiling captains into patience while you sit in chairs looking soft enough to keep Internal bored. The other end is volume: cameras, sister-story, Renny's festival night loud enough that Internal cannot quietly bury closeness without looking like they buried a missing girl." He stopped on the landing, notebook spine cracked in his jacket pocket like a talisman. "You can speak to the cameras for me—public storm as protection, your voice as the shield instead of your chair. Or you can meet me at the pier anniversary—festival ghost returning in posters and crowds, Renny's night under sodium and fog, a place to finish what we keep interrupting without giving Ellison a press clipping yet."

Want lived under the procedural dread—dangerous, unfinished, the pull of a man who could survive a captain's office and still look at her mouth like evidence. [player_name] almost touched the whitened knuckle at his side. Did. His pulse jumped once under her fingers. Will did not pull away. He looked at her like the raid-wound under his badge and the want under her skin were the same weather.

"Both verbs hurt," he said quietly. "Cameras mean I cannot control the match. Pier anniversary means we stay inside the machine's weather a little longer while hope and dread share the boards where she vanished. Cho will not name remains for either stage. Charm stays *like*. Owen stays your private weather until you put him on a page—and public storms do not respect fed silences. I will not pretend I do not want the pier. Wanting that makes me selfish. Offering the cameras anyway makes me slightly less. Slightly."

[player_name] thought of Renny's hoodie folded in a drawer. Thought of Marta's red-door scrap living in Will's cracked notebook—*badge? 2xxx / 5xxx*, east cold-storage, generator noise chewing justice. Thought of Ellison's forty-eight hours ticking like a bomb with manners. Thought of festival music lying about safety seven years ago while she kept Owen near the pier off every official page. "If I speak to cameras, I am choosing volume over control."

"If you meet me at the pier," Will answered, "you are choosing the boards and my hand in a crowd that remembers posters—choosing unfinished want in public without yet lighting the match." He scrubbed a hand over his face. "I dream raid noise when soft fails. Politics was soft with teeth. You shielded me. Now the shield chooses whether to stay soft in the open air of an anniversary or go loud enough to scare Internal into blinking."

Rain thickened on the stairwell glass. Another fog horn spoke across Harborwick like a warning that had learned their names. Will released her hand only to slide his notebook into view—Marta's ink, geography waiting for a warrant that Ellison's rope might still allow. "Speak to the cameras for Will," he murmured, almost a plea under the grit. "Or meet him at the pier anniversary. The politics hour is survived. The hook is which hunger you feed with the rope you just bought—noise that protects, or a night on the boards that might finally let us breathe."

His phone buzzed once—Ellison's night desk confirming the forty-eight in bureaucratic kindness. He ignored it. He watched [player_name] instead, mid-thirties danger soft for a mid-twenties sister of the missing who had just lied pretty for his throat.

"Pick the verb," Will said. "Cameras or pier. Hurt to leave either. Good. Means you understand shielding me was not the end of the cost—it was the beginning of choosing how loud love gets to be while Renny's finger still points east and unidentified bones still refuse to name themselves."`,
  textHot: `She shields Will from Ellison's politics with her mouth first and her body after—burnt coffee, glass office, Captain Mara Ellison's distrust like a hand on both their throats.

William Akers stood parade-rest that fooled no one—mid-thirties, scar nick pale, late smile banked, cock a problem he was pretending not to have while Ellison catalogued proximity like a woman who could smell arousal through policy. [player_name] sat in the familial chair already wet from the car and the way he had looked at her before the door closed—hazel hunger banked under professionalism, whitened knuckles flexed behind his back. Renny's absence pressed under her ribs. Unidentified remains stayed unnamed upriver. Charm stayed *like*. Hope and dread shared the office with politics and the ridiculous truth that even Ellison's voice could not kill how much [player_name] wanted him.

Ellison wanted him pulled. Soft nets. Sister-shaped interviews. Internal sniffing. [player_name] spoke first—shield, private loyalty, soft nets as method. "He treats Cho's bones as maybe. The charm is probable, not a funeral. Pulling him is clearance theater." Will's jaw flexed; something behind his eyes flinched at sealed and stayed sealed. Ellison gave forty-eight hours of rope, no civilian-led interviews without stamp, Internal shadow still circling. They escaped into the stairwell before [player_name]'s knees failed. Her pulse lived in her throat and lower; her jeans were already a quiet crime from sitting soft in Ellison's chair while Will's parade-rest lied about calm. Politics had a taste—burnt coffee and copper—and under it, want roared like a generator behind a red door.

Will shoved her against the rain-dark glass the second the landing emptied, mouth claiming, thigh between hers, hand already under her blouse to palm bare waist and then the underside of her breast until her nipple peaked against his thumb. "You lied pretty," he growled against her lips. "You saved my badge for two days. Makes me hard when you shield me from captains and still taste like unfinished fucking." His cock pressed her hip through trousers, thick and insistent; she rocked on his thigh and felt how soaked she was through denim. "Forty-eight hours. Soft. Manageable. Useful. Ellison's words. Mine are: I want to fuck you for every memo you just bought me—desk, car, this stairwell if you keep looking at me like that."

"Will—someone—"

"Later," he muttered, working her jeans open with one hand while the other pinned her wrist above her head against cold glass. Harborwick blurred behind her shoulder blades. Cool air kissed wet cotton; she flushed; Will looked down and groaned like the sight hurt. Two fingers slid into slick heat without preamble; she gasped; he kissed the sound quiet, tongue claiming, teeth threat and tenderness. "Speak to the cameras for me and I will watch you put Renny's name on the city's tongue—then take you somewhere without windows and fuck the storm out of both of us until flashbulbs and fog are the same noise, until you come with my palm over your mouth and politics tastes like sweat." He pumped deep, curling, thumb on her clit in tight circles. "Meet me at the pier anniversary and I will walk those boards with my hand on your back like a man who still has rope—and after the crowd thins I will put you against a piling and eat you until festival ghosts know your moan, until hope and dread share the wet with how hard I get for your loyalty."

[player_name] rocked on his hand, forehead to his, Renny's pointed finger and Owen's unnamed pier night braided into want that felt like loyalty's filthy twin. Her cunt fluttered; orgasm gathered like a siren. "If I go loud—"

"Public storms dig," Will snarled softly, freeing his cock enough to smear the head through her folds without entering—hot, blunt, cruel, painting her clit until she jerked. "Owen stays off your paper until you put him there. Loud does not respect fed silences. Soft pier night keeps us inside the machine a little longer. I dream raid noise when soft fails. You just made soft work. Do not waste the rope on hesitation while you drip on my fingers in a stairwell Ellison would love to photograph." He pushed the tip in—just the tip—and held, trembling with restraint that felt like a third wound, then eased out and rubbed her again. "sealed is sealed. You get hints, not the whole hallway. You get this. Choose while you clench around nothing and everything."

She came on the tip and his thumb—quiet, shaking, fist in his collar—while rain streaked the glass and a fog horn groaned like it knew their names. Will eased out without chasing his own finish, cock jumping against her thigh, and tucked himself away with shaking hands. He fastened her jeans with mock courtesy that did not reach his eyes and pressed his forehead to hers. Pulse hammered against her wrist. Wet jeans. Politics survived. Want unfinished and loud.

"Speak to the cameras for Will," he whispered, voice wrecked. "Or meet him at the pier anniversary. The shield held. The hook is which hunger you feed with the rope—noise that protects, or boards where she vanished and my mouth finally stops pretending this is only a case." His late smile cut against her mouth. "I will sell either to Ellison's night desk with a smile that lies. I cannot sell hesitation while you leave a wet print on my stairwell hand."

He walked her down one more flight before the bullpen cameras could invent a story, into the parking garage's concrete chill where generator hum replaced fog horns and nobody asked about proximity. Will boxed her against a pillar between a Harborwick PD cruiser and his own unmarked, rain still beading on his shoulders, and put her hand on his cock through his pants. "Feel what the shield did," he muttered. "You stopped Ellison from cutting me and I got harder for the mercy. That should scare you. It scares me."

She stroked him, slow, feeling thick heat jump against her palm. He groaned and shoved his hand back into her jeans, fucking her with two fingers in time with nothing but want. "Cameras mean you in front of microphones putting Renny's festival night on a page the city cannot ignore—and after, I take you where there are no windows and make you come until your voice is hoarse from everything except press statements." His thumb circled her clit. "Pier anniversary means posters and crowds and my hand on your back like soft partnership—and after, I put you on the hood of this car in fog thick enough to hide us and fuck you slow until the boards stop lying about safety."

[player_name] whimpered, hips rolling, conscience loud about Owen still off paper and bones still unnamed. "Cho—"

"Will not name remains because you moan in a garage," Will snarled softly, curling his fingers. "Charm stays *like*. Hope and dread do not get a press pass or a pier pass. What changes is whether dawn finds us hiding from flashbulbs or walking festival ghosts with rope still around my badge." He kissed her hard enough to bruise, then eased his hand free and painted her lower lip once before sucking his knuckles clean. "Speak to the cameras for Will. Or meet him at the pier anniversary. Verb. Now. Ellison's forty-eight is already eating itself."

[player_name] stood between fluorescent judgment and harbor fog, remains unnamed, charm probable, sister still a pointed finger—and the choice sitting between them like unfinished fucking: cameras first, or the pier anniversary where hope and dread and William Akers all waited with teeth.

His phone buzzed—Ellison's forty-eight confirmed. He ignored it. He watched her mouth. "Pick," Will said. "I am still hard enough to mean both. Cameras or pier. Hurt to leave either. Good."

[player_name] tasted herself and rain and burnt-coffee ghosts. She thought of Renny's hoodie, of Marta's red door, of Ellison's glass eye still watching through bureaucracy. Will's cracked knuckles whitened on the pillar beside her head. His late smile returned wrong—weapon and wound—and he tucked a strand of hair behind her ear with a tenderness that felt like a threat. "If you speak to the cameras, I stand behind you like weather that learned your name. If you meet me at the pier, I stand beside you like a man who still believes soft can hunt. Either way I am yours to damn with a verb. Either way Renny stays a pointed finger until science or a confession says otherwise. Choose, [player_name], before the garage cameras invent a story Ellison can use—and before I forget how to wait for warrants and verbs and anything that is not the wet heat of you against this pillar while all of Harborwick watches through concrete and cold rain."`,
  choices: [
    { id: "scene7o", text: "Speak to the cameras for Will", textHot: "Speak to the cameras for Will" },
    { id: "scene7p", text: "Meet him at the pier anniversary", textHot: "Meet him at the pier anniversary" }
  ]
};
