export default {
  id: "scene5a",
  layer: 5,
  title: "Ellison's office: cooperate fully or lose access",
  text: `Captain Mara Ellison's office sat three floors above the interview rooms and smelled like policy ink, rain brought in on wool coats, and coffee reheated until it tasted like punishment. The west window looked toward Harborwick's pier district, where fog clung to warehouse roofs and the river ran the color of old steel. A framed commendation hung crooked behind her desk. The shelf clock ticked with the same merciless patience as the one downstairs. [player_name] stood because Ellison had not offered a chair. Jake Akers stood because sitting would have looked like surrender.

Ellison set her tablet face-down on the blotter. Mid-fifties, charcoal blazer, sleepless eyes that measured people the way Cho measured bone: for fit, for fracture, for liability. "Access is not a right," she said. "Family witnesses do not get to shop the file. You want updates on the upriver remains, the charm analysis, Cho's timeline—you give me everything you withheld seven years ago. Full cooperation. Or you walk out of Harborwick Precinct tonight and you hear about your sister through rumor like everyone else."

[player_name]'s mid-twenties felt thin under that sentence. Renny had been a teenager when she vanished from the pier festival—seven years of absence folded into a hoodie still waiting in a drawer at home, a silver charm bracelet missing one charm, a name that still refused to settle among the dead. The remains were unidentified. Age range that could fit Renny. A charm that *could* match. Lab ID pending. Hope and dread shared the office air like co-counsel who hated each other and refused to leave.

Jake's cracked notebook stayed closed against his thigh. Mid-thirties, dark hair still damp from hallway fluorescent heat, scar cutting his left eyebrow like a private argument he had never finished. Brutal charm banked low now—velvet over a blade, sheathed for his captain—but the wound underneath showed in the flex of his jaw. When Ellison said *full cooperation*, his grey-green eyes flicked to [player_name] once: warning, want, a silent promise that he would not let the captain hang her if he could help it—and also a harder truth: do not make me choose between you and the badge in a room where the badge already owns the walls.

"Define everything," [player_name] said. Her voice held. Barely.

Ellison's smile was not Jake's kind of smile. No velvet. "Owen Vale's real timeline. Who you saw on the pier. What you left out of the statement you signed at twenty. The detail you told yourself was protection." She tapped the tablet. "Akers already has you halfway there. I interrupted because I will not have another family soft-spot turning my detective into a liability. Not after—" She stopped. Not after a name that still bruised the hallway. Nina Solis lived in the pause like a draft under a door. Jake's hand twitched toward his ribs and aborted. He did not speak. Ellison's eyes said she had not needed him to. Whatever had happened in that other raid, whatever sealed file still sat unopened in Jake's past, it was a hint with teeth—not a confession he would give tonight.

Rain freckled the west glass. Somewhere below, a foghorn rolled inland, low and lonely. [player_name] tasted burnt coffee and fear and the sharper taste of almost-confession still stuck from the interview room: Owen near the pier with someone who was not supposed to be there; the run-off-with-friends story she had accepted because the house needed standing; the omission that had become a seven-year currency she paid every time she said Renny's name out loud.

"If I cooperate," she said carefully, "I stay in the room. I see Cho's notes. I hear what the charm probability actually is before the Harborwick rumor mill buries hope or sells dread as fact. I will not let you clear a missing girl into a closed drawer because it looks tidy on a board."

"You stay as a cooperating witness under my rules," Ellison corrected. "Akers remains primary. You do not date the case. You do not sandbag. You do not protect Owen Vale because he used to carve the Thanksgiving turkey and because family still sounds like a reason when you are scared."

Jake's mouth twitched—almost the brutal charm, almost a joke about turkey and knives—and died mid-breath when Ellison looked at him. The humor left his face like a light switched off in a hallway. "Captain. She's mid-thread. Cutting her freezes the pier night colder than it already is. Cho still has no hard ID. Pressuring a family contact into a lawyered silence helps whoever wanted Renny quiet in the first place. Quiet is how this city loses teenagers and then argues about paperwork."

"Do not lecture me on quiet, Akers." Ellison's voice went flat as wet asphalt. "You know what quiet costs. You know what hallway chaos costs. You know why I watch how you lean across tables when a witness has a mouth you like listening to." The the sealed past bruise again—hint, not dump; a partner's name that had taken an official fall while Jake kept a badge and a sealed silence. He took it without flinching this time, which somehow looked like flinching anyway. Dark past hummed under his badge like a second pulse. He did not open it. He offered [player_name] a look instead: *I am still here. Choose. And know that choosing me is not soft.*

[player_name] thought of Renny's empty chair downstairs. Of the evidence photo of a silver charm that was only *like* the missing piece—close enough to gut hope, not close enough to bury it. Of Owen's bleach-clean alibi and the way his voice had sounded the morning after the festival, too calm, too practiced. Of Jake's knee under the interview table—accidental, devastating—and the way his voice had invited the truth like a hand on a locked door. Attraction was a stupid animal to bring into Ellison's office, and it came anyway: the sleep-deprived set of his shoulders, the scar catching light, the dangerous competence of a man who used charm as armor over something that still bled when named sideways. Mid-thirties to her mid-twenties—close enough to burn, far enough that the badge still felt like a different country. She wanted his attention and hated that she wanted it while Renny's fate stayed contested bone and rumor.

"Full cooperation means I put Owen at the pier," [player_name] said. The words tasted like cutting a rope and finding it was also a noose. "It means I admit I saw him with someone who should not have been there. It means I admit I lied by omission because I was twenty and scared and he made Renny's trouble sound like the kind you hide if you love her—drugs, debt, the soft crimes families bury so the hard ones never get a hearing."

Ellison's tablet woke under her palm, screen casting a cold light up her face. "Then say it on record. Tonight. Before Cho's next drip. Before Owen hears the charm rumor and burns whatever still links him to that festival. Before you decide again that protection is the same as love."

Jake stepped half a pace closer to [player_name]—not touching, not quite professional distance anymore. Soap and salt and that scrubbed-dark scent that never quite left him, as if he had washed a worse year off his skin and the soap had failed. "Or," he said softly, velvet returning because Ellison was watching the door more than his mouth, "you lean into me on this. You give the truth to the case through me. We open what Renny left locked—whatever box, letter, scrap she trusted you with that you still sit on like a second spine. We do it controlled. We do not let Ellison's clock turn your confession into a press stick. I will walk you through the ugly. I have walked uglier."

"Akers—" Ellison warned.

"She has a choice," Jake said, and the brutal charm flashed once—invitation and threat in the same smile, the kind of sharpness that felt like a weapon and a wound. "Cooperate as theater for the captain, or cooperate as partnership for the girl who is still not confirmed among the upriver dead. Hope still has a throat, Mara. Don't choke it for clearance metrics. Don't make me watch you bury a maybe because a maybe is easier to file than a sister who might still be breathing somewhere this city refuses to look."

Ellison's jaw tightened at her first name used like a dare. Rain thickened on the glass. "Partnership is not a police term in my office." She looked at [player_name] the way a storm looks at a shoreline. "You have sixty seconds to decide how this goes. Lean into Akers and the truth—open everything, including whatever Renny hid that you still keep warm in a drawer—and I keep your access under my seal. Or hold the line, protect the family ash-heap one more night, and lose the file. Tick."

The office hummed with fluorescent honesty and human heat. Renny's fate stayed contested: not named, not buried, not safe. [player_name]'s palms were damp against her thighs. Jake watched her like a man who had already decided she mattered more than was safe for either of them—and who would still dig if she walked, charm scraped raw, past unoffered, notebook ready. Ellison watched like a fuse waiting for a match.

One path meant leaning into Jake: truth as intimacy's cousin, Renny's locked secrets opened under his cracked notebook and Ellison's reluctant seal, the pier night finally spoken where it could become evidence instead of shame. The other meant holding the line—family first, one more night of protection that might already be poison—while access bled out of the room and rumor sprinted ahead of science toward a girl who might or might not be waiting in Cho's cold drawer with a charm that was only *like* hers.

[player_name] tasted rain and burnt coffee and the unfinished pier night climbing her throat. Jake's scar caught the desk lamp. Ellison's clock ticked like a second interrogation she had not agreed to and could not postpone. Harborwick's foghorn answered from the river, low enough to feel in the ribs. The kept secret pressed its whole weight into her mouth, and whatever she chose next would either hand Jake the key to what the sister kept—or teach Captain Ellison that some sisters still knew how to lock a door even while hope and dread fought for the same lungs in a damp port city that remembered everything except the official story.`,
  textHot: `Captain Mara Ellison's office smelled like policy ink, reheated coffee, rain on wool—and the low animal thrum of two people who should not want each other this hard under a captain's eye. The west window held Harborwick's pier fog like a held breath. [player_name] stood because no chair had been offered. Jake Akers stood close enough that she could feel the heat off his shoulder through the air, mid-thirties and dangerous in a charcoal shirt that remembered the shape of him too well—broad back, lean waist, the kind of body that made interview tables feel like foreplay when he leaned across them.

Ellison set her tablet down like a verdict. "Access is not a right. Full cooperation or you hear about your sister through rumor. Everything you withheld. Owen. The pier. The soft detail you called protection."

[player_name]'s mid-twenties felt naked under the sentence. Renny—teenager then, missing seven years—still unnamed among upriver remains that Cho would not christen without science. A charm that *could* match the missing bracelet piece. Lab pending. Hope and dread fucking the same oxygen while Ellison talked clearance like sex she refused to enjoy. Jake's cracked notebook pressed his thigh. Scar through his left eyebrow. Brutal charm banked for the room, wound showing for anyone who knew how to look. When Ellison said *everything*, his grey-green gaze dragged over [player_name]'s mouth like a thumb—and her cunt answered before her brain did, a low, treacherous pulse of want she hated and could not shut off.

"Define everything," she managed, and hated how rough her voice sounded, as if he had already been kissing her throat.

Ellison listed Owen's timeline, the pier sighting, the omission at twenty. She almost said a name—Nina Solis—and stopped. The pause bruised the room. Jake's hand twitched toward his ribs, aborted, a body remembering a raid and a hallway and a teenager who should not have been there—he would not narrate it. Dark past under the badge. Secrets clenched behind professional teeth. The flinch made [player_name]'s nipples tighten traitorously under her blouse; broken men should not be this hot, and Jake Akers wore broken like cologne she wanted to lick off his pulse point.

Rain freckled the glass. [player_name] still tasted the almost-confession from downstairs: Owen at the pier with someone wrong; the lie that kept the house standing; seven years of sleeping on a secret while her body now ached for the detective Ellison was trying to leash. Attraction was filthy timing. It flooded her anyway—thighs pressed hard together, clit throbbing once when Jake stepped half a pace nearer, soap and salt and scrubbed-dark past filling her nose until she had to part her lips to breathe him without looking like she was breathing him.

"If I cooperate, I stay in the room," [player_name] said. Voice sandpaper. "Cho's notes. Charm probability. Before rumor buries hope or sells dread as gospel."

"You stay under my rules," Ellison said. "Akers primary. You do not date the case."

Jake's mouth twitched—velvet-blade almost-joke about dating and case numbers—and died under Ellison's look. "Cutting her freezes the pier night. Cho has no hard ID. Quiet helps whoever wanted Renny silent." His voice stroked the inside of [player_name]'s wrist without touch. She imagined that voice between her legs, low and precise, and had to lock her knees so she would not sway. Wet heat gathered; she felt it and burned with shame and hunger both.

"Do not lecture me on quiet, Akers. You know what hallway chaos costs." the sealed past again—hint, not dump; partner, fall, sealed file, charm-as-armor. Jake took it. The wound showed in the set of his shoulders. [player_name] wanted to put her mouth on that scarred brow and also wanted to run before she came undone from proximity alone. Want pooled low and slick; when she shifted her weight, wet cotton clung to her clit like a filthy secret Ellison must not smell on the air.

"Full cooperation means I put Owen at the pier," she said, and saying it felt like orgasm's mean cousin—release edged with ruin, truth as a physical shove. "Means I admit the omission. Means I stop protecting ash because ash still looks like family if you squint."

Ellison's tablet woke, cold light under her chin. "On record. Tonight. Before Cho drips. Before Owen burns the link."

Jake closed the half-pace. Not touching. Worse than touching. Heat off his chest warmed the front of her blouse. She could map where his mouth would land if Ellison vanished—corner of her lips first, then deeper, then the confession pulled out of her with tongue and teeth while his hand found the damp between her thighs. "Or lean into me," he murmured, velvet for her, steel for the room. "Give the truth through me. Open what Renny left locked. Controlled. Not a press stick. I will walk you through the ugly." His eyes dropped to [player_name]'s throat, to the frantic pulse there, then lower for a fraction of a second that felt like fingers sliding under her waistband. Brutal charm as invitation. Hunger on a leash Ellison could see and despise. [player_name]'s cunt clenched around nothing; she bit the inside of her cheek and tasted copper.

"Akers—"

"She has a choice," Jake said, smile flashing like a weapon and a wound in the same breath. "Theater for the captain, or partnership for the girl still not confirmed among the dead. Hope still has a throat, Mara. Don't choke it for metrics."

Ellison's jaw flexed. Rain thickened. "Sixty seconds. Lean into Akers and the truth—open everything, every soft place, every locked scrap Renny trusted you with—or hold the line, protect family, lose the file. Tick."

The office hummed. [player_name]'s body hummed louder: lips parted, nipples aching against cotton, cunt clenched and slick while Jake watched her like he could already taste the confession and the kiss that should not follow it, like he knew how she would sound opening for him—mouth and legs and the seven-year lock alike. Renny's fate contested. Remains unnamed. Charm only *like*. One path meant leaning into him—truth stripped under his notebook, Ellison's seal reluctant, want braided into cooperation until [player_name] could not tell if she was opening Renny's locks or opening herself for a detective with a past he would not speak and a cock she had not seen and somehow already ached for. The other meant holding the line, family first, walking out with access bleeding and her thighs still slick from a man Ellison called liability, desire cooling into a bruise she would press for days.

Jake's scar caught the lamp. Ellison's clock ticked. [player_name] pressed her tongue to her teeth and tasted copper and rain and the filthy almost of his name. Harborwick's foghorn rolled up from the river and vibrated in her ribs like a second heartbeat. Choosing him meant handing over the pier night while her body still throbbed for the reward his eyes promised and his badge forbade—his hands on Renny's locked box beside hers, his mouth maybe later, his brutal honesty fucking her composure until she had nothing left but truth and wet heat. Choosing the line meant denying them both—case and cunt—and listening to rumor invent Renny's ending while Jake's want cooled into professional ice she was not sure she could survive without touching herself to the memory of this exact charged air.

She shifted; wet fabric kissed her clit; a small, humiliating jolt of pleasure flickered up her spine in Ellison's policy office. The kept secret pressed its whole weight into a mouth that wanted Jake Akers and the truth in the same ruinous breath. Ellison waited like a fuse. Jake waited like a man who would either catch her or ruin her if she fell forward. The unfinished pier night climbed [player_name]'s throat like a second pulse, and whichever door she opened next would either put his hands on what the sister kept—and on the sister who kept it—or teach her how cold Harborwick felt when she chose family ash over the detective whose brutal charm had already fucked her composure raw without laying a single finger on her skin.

She could still feel the ghost of his knee from the interview room like a brand on the inside of her thigh. Ellison talked access; [player_name]'s body talked Jake—scar, smile, the scrubbed-dark smell of a man who had survived something he would not name and wore charm so no one asked. If she leaned into him, she would walk out of this office with her cunt still aching and her mouth finally honest, Renny's locks clicking open under his hands while Ellison pretended not to see the heat. If she held the line, she would walk into Harborwick rain with access gone and desire unfinished, pressing her own fingers later to the memory of his voice saying *lean into me* like it was both case strategy and the filthiest thing anyone had ever asked of her in a room with a clock. The foghorn sounded again. She almost said his name out loud—Jake—just to feel it shape her mouth the way she wanted his mouth to shape her.`,
  choices: [
    { id: "scene6a", text: "Lean into Jake and the truth", textHot: "Lean into Jake and the truth" },
    { id: "scene6b", text: "Hold the line — protect family first", textHot: "Hold the line — protect family first" }
  ]
};
