export default {
  id: "scene6m",
  layer: 6,
  title: "Warehouse raid planning",
  text: `Warehouse raid planning smelled like burnt precinct coffee and marker ink.

William Akers had claimed a back conference room with a cracked whiteboard, a stack of Harborwick cold-storage maps, and a look that said sleep was a rumor other people believed. Mid-thirties. Dark stubble silvered by fluorescent light. Scar nick pale at the eyebrow. Whitened knuckles flexed around a dry-erase pen as he drew the east cold-storage row in hard black lines: loading docks, chain-link gate, red door with a number half scraped—fourteen or forty-one, Marta's geography still living between them like a dare.

[player_name] stood opposite him with Renny's absence pressed under her ribs. Seven years. Festival fog. A sister pointing east while a clean jacket held her wrist. Unidentified remains still waiting in Cho's patience upriver; a silver charm still only *like* Renny's missing piece. Hope and dread shared the whiteboard tray with magnets and a coffee cup gone cold.

"Ellison wants a memo that reads like clearance," Will said without looking up. "I want a warrant that reads like a door we can kick without becoming the chaos I already know how to make." His late smile arrived and died in the same breath. "Raid-plan means backup, angles, no early push for a CI or a guilt trip. Nina Solis taught me what early costs. I will not rhyme your sister's warehouse with that ash. Not if I can help it."

[player_name] watched the pen move. "And if Ellison smells me in the briefing?"

"She already smells you," Will said. "Familial witness. Romance optics. Soft nets that look like sandbagging. Captain Mara Ellison presses for numbers and distrusts last names that arrive with missing girls." He capped the marker, finally meeting her eyes—hazel, tired, hungry for a break that would not eat them. "You are in this room because Marta pointed and you steered me at carnival ghosts until geography paid. You are also in this room because I cannot pretend I plan better when you are not breathing the same burnt air. That is a problem. Problems get people reviewed."

The clock hummed. Somewhere down the hall a printer spat forms. Will pinned a satellite printout beside the whiteboard sketch and tapped the red-door zone with one cracked knuckle. "Entry A: dock side, quieter, fish-rot cover. Entry B: street gate, louder, better for vehicles. I want A if we get the warrant clean. I want eyes on fourteen and forty-one both until the scrape resolves. No solo hero runs. No you as a costume badge. If we go, we go as a team with radios that work and an exit that does not require prayer."

[player_name] tasted copper and pier salt memory. "Owen—"

"Stays off the warrant language until the building earns him," Will cut in, not gentle. "You still have not put him on paper. I am not baiting that confession out of a raid brief. Softest hard I can offer. The warehouse gets Renny's finger. Owen gets whatever the concrete says." He leaned both hands on the table, shoulders tight under a shirt that had seen too many three a.m.s. "Cho will not rush an ID to soothe a team. Bones stay unnamed. Charm stays probable. Write Renny on a red door until science or a confession earns the rest. That is still mercy. It will not feel like mercy when we are standing in generator dark asking a building to speak."

Want lived under the procedural dread—dangerous, unfinished, the pull of a man who could map a raid and name a sealed wound in the same paragraph. [player_name] almost touched the whitened knuckle braced on the table edge. Did. His pulse jumped once under her fingers. Will did not pull away. He looked at her mouth the way he looked at evidence that might burn him.

"Ellison texted," he said quietly. "She wants to know why a witness is in my planning room. She used the word *proximity*. That is Internal weather with manners. If we push the raid package tonight, we move before politics owns the hour. If we pause to face whatever IA shadow she is already drafting about my closeness to you, we might lose the door—or keep our badges long enough to find another one." His jaw worked. "Both verbs hurt. Entering the raid under pressure means we take Marta's geography into fish-rot air while Ellison's distrust rides shotgun. Facing IA over my closeness means we let the machine inspect what we have become before the warehouse gets a chance to answer Renny."

[player_name] thought of Renny's hoodie folded in a drawer. Thought of festival music lying about safety. Thought of a half-scraped number and a girl who knew a building. "If we raid and something goes sideways—"

"Then I own the entry," Will said. "Not you. Not Ellison's memo. Me. I have owned sideways before. The difference is I will not push early to protect a CI or your guilt. We wait for the warrant ink. We wait for backup. We do not invent urgency out of hope that the remains are her or dread that they are not." He turned his hand under hers, laced their fingers hard enough to hurt a little. "I dream raid noise when soft fails. Planning is how I argue with the dream. Having you here is how the dream learns your name. Ellison calling that a liability does not make it less true."

Rain ticked the high windows. Harborwick's warehouse district waited beyond glass and fog like a mouth. Will released her hand only to slide a printed roster across the table—names, call signs, a medic on standby, no ex-partner on any line because that name was ash and rumor and a sealed drawer. "These people trust me until they do not," he said. "Closeness to a witness is how trust dies in memos. You can walk into the raid pressure with me—vest, earpiece, behind the line, seeing what Renny pointed at when the door opens. Or you can walk with me into the IA shadow first and answer questions about whether Akers forgot how to keep a case from becoming a bed." The smile returned, late and sharp. "I will not pretend I do not want you at the red door. Wanting that makes me selfish. Offering the IA pause anyway makes me slightly less. Slightly."

[player_name] laughed once, broken. "You use charm like a briefing."

"Charm is how I ask," Will murmured. "Teeth are how I wait. You have been warned since the warrant on your porch." He tapped the whiteboard again. "Fourteen. Forty-one. East. Red. Marta gave us a living Renny pointing. That is more than bones have offered. Do not waste her finger on hesitation while politics drafts our obituaries."

The room felt smaller. [player_name] heard her own heartbeat louder than the clock. She thought of Ellison's side-eye, of sealed files, of the way Will flinched sometimes when someone said *partner* in the bullpen. Sealed past as wound, not confession. Hallway as rhyme. A detective allergic to lies whose career was built on one careful silence—and a sister who had kept Owen near the pier off every official page for seven years.

"If I enter the raid," she said carefully, "I am choosing the building over the machine for one night."

"If you face IA with me," Will answered, "you are choosing the machine's throat before the building's. Either way Renny stays a pointed finger and unidentified bones stay roommates with hope. Either way I still want to finish the kiss we keep parking behind case maps." He scrubbed a hand over his face. "Pick the verb. Enter the raid under pressure—backup, warrant, fish-rot, me between you and the dark. Or face IA over Will's closeness—questions, proximity language, Old raid-ash stirring because every review smells like old smoke. Hurt to leave either. Good."

He slid the warrant draft toward her—language clean of Owen, clean of romance, dirty with geography and a sister's seven-year silence pressing under every line. [player_name] read without seeing fully, pulse in her throat. Outside, a fog horn spoke across Harborwick like a warning that had learned their names. Inside, Will waited with cracked knuckles and a raid-wound humming, not clean-cut, brutal charm banked for the moment she chose which hard room to walk him into.

"Ellison's night desk wants an answer by two," he said. "Raid package or review posture. I can sell either with a smile that lies. I cannot sell hesitation while a red door listens." His voice dropped. "Cho will not name the remains to soothe this choice. The charm stays *like*. Your stepfather stays weather you have not put on paper. What changes is whether dawn finds us in cold-storage air or under fluorescent questions about how close a detective is allowed to stand to the woman who kept something."

[player_name] looked at the whiteboard's black lines, at the coffee ring on the roster, at Will's mouth. Want and dread braided. Trust under interrogation lights. The romance was whether she could love a badge after the system failed Renny—and whether he could love the woman who still fed a pier secret while planning a raid that might finally make concrete speak.

Will's phone buzzed once on the table—Ellison's name a small bright threat. He did not answer. He watched [player_name] instead, notebook spine cracked on the chair beside him like a small black altar.

"Enter the raid under pressure," he murmured, almost a plea under the grit. "Or face IA over my closeness. The planning is done enough to hurt. The hook is which hunger you feed first—Renny's door, or the machine that wants to know why I look at you like evidence I refuse to bag."

Rain thickened on the glass. Harborwick held its warehouse breath.`,
  textHot: `Warehouse raid planning smelled like burnt coffee and want.

William Akers had her in a back conference room with maps, a cracked whiteboard, and his mouth already a problem—mid-thirties danger, scar nick catching fluorescents, late smile banked while he drew the east cold-storage row in hard black lines. Red door. Fourteen or forty-one. Marta's geography as foreplay for a warrant. The dry-erase pen squeaked; his whitened knuckles flexed; [player_name] felt the sound in her teeth and lower, absurd and true, because even raid ink could turn her on when the man holding the marker looked at her like evidence he refused to bag.

[player_name] stood close enough to smell rain still drying in his hair, soap under salt, the scrubbed-dark past he wore like cologne. Renny pointed east behind her eyes—sixteen, bracelet flashing, clean jacket on a wrist—while unidentified remains stayed unnamed upriver and a charm stayed only *like*. Hope and dread soaked her the way Will's attention did: low, relentless, unfinished. Her nipples had gone tight under her blouse from nothing but proximity and the way he said *Entry A* like a filthy promise. She pressed her thighs together and felt how wet she already was. Planning rooms should not do this. William Akers did this without trying and with every deliberate glance.

"Ellison wants clearance language," Will said, voice rough, pinning her hip to the table edge with one hand while the other capped the marker. Heat bloomed where his palm claimed her. "I want a raid that does not rhyme with Nina Solis. Early pushes cost. I will not invent urgency out of your guilt or my cock." His thigh pressed between hers through jeans, thick and intentional, and she gasped at the pressure against her clit through denim. "You are in this room because geography paid and because I plan dirtier and better when you are breathing my air. That is proximity. That is IA weather. That is also why I am hard against your hip while I talk warrants."

She rolled once against his thigh without meaning to—then meaning to. Heat spiked. The clock hummed like a third voyeur. Somewhere down the hall a printer spat forms that would outlive this almost-fucking. "Will—"

"Raid-plan means backup, Entry A on the dock side, no you as costume badge, radios that work," he murmured against her temple, hand sliding up under her shirt to palm bare waist, then higher, thumb brushing the underside of her breast through thin cotton until her breath broke. "Owen stays off the warrant until concrete earns him. Cho's bones stay unnamed. Charm stays probable. Write Renny on a red door until science earns a funeral. Mercy. It will not feel like mercy when fish-rot hits and I still want to fuck the fear out of you afterward—slow in the car, or hard against a warehouse wall if we walk out breathing, my hand over your mouth so backup does not hear what the raid did to us."

He kissed her hard enough to bruise—tongue claiming, teeth threat and tenderness—and she opened for him like the softest confession she had left. Coffee and want. Rain memory. The sealed ash of Sealed ash living under his tongue as a flinch, not a dump. Will boosted her onto the table beside the roster. Papers slid. A magnet clicked to the floor. He shoved her knees apart and stepped in, cock thick behind his fly where she felt him through denim, grinding slow while his fingers worked her jeans open. The zipper sound was filthy in the quiet. Cool air kissed wet cotton; she flushed; Will looked down and groaned like the sight hurt.

"Ellison texted *proximity*," he growled, sliding two fingers into slick heat without preamble, thumb finding her clit like a man who studied evidence. She clenched around him, forehead to his, biting her lip for the hallway. "[player_name] soaking my hand in a planning room is exactly what she means. Enter the raid under pressure—vest, earpiece, behind the line, my body between you and generator dark—and we move before politics owns the hour. Face IA over my closeness and we let the machine ask whether Akers forgot how to keep a witness out of his bed before the warehouse answers Renny." He pumped deep, curling, watching her try not to moan. "Both leave you wet. Both cost. Pick while you clench around a detective with ash under his badge."

[player_name] rocked on his fingers, Renny's pointed finger and Owen's unnamed pier night braided into the same unbearable want. Her cunt fluttered; orgasm gathered like a siren she should not answer in a precinct conference room. "If the raid goes sideways—"

"I own the entry," Will snarled softly, freeing his cock enough that the head dragged against her inner thigh—hot, blunt, not inside yet, a promise with a pulse that smeared her wetness along his length until both of them shook. "Not you. I have owned sideways. Difference is I wait for ink. I wait for backup. I do not push early for a CI or for the way your cunt answers when I say red door." He rubbed the head through her folds without entering, cruel, teasing, raid-map at her back, and every slick pass made her hips chase. "sealed is sealed. You get hints, not the whole hallway, while I finger you against a warrant draft. Teeth. Charm. Choose."

Rain ticked the windows. Fog horns groaned over Harborwick. Will dragged her closer to the edge and kept rubbing—cock kissing clit, then entrance, then clit again—while his other hand stayed buried, three fingers now, stretching her for a fuck he would not finish here. "If you enter the raid, I put you behind me where I can feel your breath on my neck between radio checks—and after, if we walk out, I take you in the car until fog knows your name, until you come with my palm over your mouth and Renny's geography still on my tongue. If you face IA first, I walk into review smelling like you and lying with my mouth while my hands remember this exact slick—how you drip when I say *warrant*, how you shake when I say *closeness*." His smile cut against her mouth. "I dream raid noise when soft fails. Having you drip on my planning table is how the dream learns to beg."

She shook, close, conscience loud, body louder. Warehouse silhouettes lived behind her eyelids. Ellison's name glowed unread on his phone. Will's whitened knuckle braced beside her hip; his cock kissed her entrance and stayed out—discipline as filthy as any thrust—while his thumb worked tight circles that made her thighs tremble. "Please—" she started, and hated how it sounded, and meant it.

"Not yet," Will whispered, almost kind, entirely cruel. "Not inside. Not on Ellison's conference laminate. I will not fuck you into a raid mistake or an IA exhibit. I will make you choose while you are ruined enough to be honest." He pushed the tip in—just the tip—and held, trembling with restraint that felt like a third wound, then eased out again and rubbed her clit with the wet head until she jerked and bit his shoulder through his shirt. "Enter under pressure, or face IA over how close I am—how close *this* is. Hurt to leave either. Cho will not name bones to soothe you. Owen stays off paper until you put him there. What changes is whether dawn finds us in cold-storage air with my hand on your vest strap or under fluorescent questions while I still taste you."

[player_name] clenched around nothing and everything, kissing him like an argument. "You use charm like a blade."

"Teeth are how I wait," Will answered, fucking her with the head of his cock in shallow, maddening strokes that never became more, fingers still curling inside her until she came—quiet, shaking, fist in her mouth—while he watched like a man taking a statement he would never file. He groaned through her orgasm, forehead to hers, cock jumping against her thigh, and did not chase his own. "Red door or review. Renny's finger or the machine's throat. I will sell either to Ellison's night desk with a smile that lies. I cannot sell hesitation while you leave a wet print on my roster." He tucked himself away with shaking hands, fastened her jeans with mock courtesy that did not reach his eyes, and pressed his forehead to hers. His pulse hammered against her wrist where he held her. "Pick. Enter the raid under pressure. Or face IA over Will's closeness. The planning is done enough to hurt. The hook is which hunger you feed while I am still hard enough to mean both."

His phone buzzed—Ellison again. He ignored it. Outside, Harborwick's warehouses waited like teeth. Inside, [player_name] stood with raid ink on her fingers, Will's come-denial still throbbing between them, remains unnamed, charm probable, sister still a pointed finger—and the choice sitting between them like unfinished fucking: red door first, or the Internal weather that already knew their names.`,
  choices: [
    { id: "scene7m", text: "Enter the raid under pressure", textHot: "Enter the raid under pressure" },
    { id: "scene7n", text: "Face IA over Will's closeness", textHot: "Face IA over Will's closeness" }
  ]
};
