export default {
  id: "scene6b",
  layer: 6,
  title: "Full coop: she withholds one letter still",
  text: `The lockbox lid was already open when [player_name] made the small, private decision that would either save Renny's last scrap of mercy or teach Jake Akers that partnership still had a soft lie in it. Harborwick rain ticked the bedroom window in soft percussion. Precinct coffee—burnt, bitter, carried up in a paper cup Jake had pressed into her hands downstairs—cooled on Renny's desk beside the silver charm bracelet with its missing tooth. Fog pressed the glass in slow breaths. Somewhere toward the pier a foghorn rolled, low enough to feel in the ribs, the river clearing a throat that still had no sister's name attached.

Full cooperation had bought them the hour: Owen Vale named near the festival pier on record, the seven-year omission spent under Captain Mara Ellison's fluorescent honesty, access kept on a leash that could still choke if Ellison decided family witnesses were liabilities wearing grief like perfume. Jake knelt opposite [player_name] on the carpet that still held the ghost shape of a teenager's knees. Mid-thirties, scar cutting his left eyebrow, cracked notebook open, pen ready. Brutal charm banked low for a room that smelled like vanilla ghost and river wind and absence—velvet over a blade, sheathed because this was not a place for jokes that landed like threats. His grey-green eyes tracked everything: journal, map, USB, and the cream envelope still half-tucked under purple leather with Renny's handwriting across the front—*For [player_name] — only if.*

Dr. Lila Cho's language still ruled the upriver remains: *unidentified*, *pending*, *consistent with* an age range that could fit Renny and a charm that could match the bracelet's gap. Lab ID unfinished. Rumor faster than science. Hope and dread shared the bedroom air like co-counsel who hated each other and refused to leave. The remains were not Renny until science said so. [player_name] would not christen bone with a sister's name because cream paper felt heavy.

"Journal, map, USB," Jake said, cataloguing without reaching past what she offered. Voice precise. Off-duty quiet that was somehow more dangerous than precinct volume. "Ellison will have controlled copies by morning. Not a press stick. Not a clearance toy." His gaze flicked to the envelope. "And that?"

[player_name]'s mid-twenties hands did not tremble until she made them stop. She slid the letter into the kangaroo pocket of Renny's old hoodie—which she had pulled on against the damp without thinking—and felt paper warm against her stomach like a second spine. Cotton remembered a sister's shoulders. The key to the lockbox cooled on the desk beside the coffee. "Not yet," she said. Quiet. Not soft. "Full coop on everything that maps the chain. Not on the page that is only for me until I know whether those bones are hers. If the letter says goodbye, I will not let Ellison read goodbye before Cho finishes speaking. If it says run, I will not let Owen hear run through a captain's memo. If it says nothing but love, I still get to hold love without tagging it into evidence before dawn. Hope still has a throat, Jake. I am not cutting it for metrics."

Jake's jaw flexed. Cracked knuckles whitened on his pen—old scars across the ridges, the kind of hands that had hit doors and people and maybe a past he would not open in this room. When Ellison had almost named Nina Solis in the precinct hallway, Jake had touched his ribs like checking a bruise that never yellowed. Partner. Fall. Sealed IA file. Charm worn as armor over a hallway chaos he would not narrate beside Renny's posters. Hint only. Teeth showing. Dark past humming under the badge like a second pulse. He did not dump it. He let the silence bruise, then spoke with the allergy to lies that made his brutal charm feel like both weapon and wound.

"I felt that," he said. "The slide. The pocket. I always feel the holdback. It is how I keep a badge and how I lose sleep and how I know when a witness is still protecting something that might be love or might be fuel for whoever wanted Renny quiet." A flicker of velvet-blade smile, gone before it could become a joke about pockets and trust. "I am not Ellison. I will not tear the hoodie off you for a letter. I will also not pretend partnership means I stop being a detective the second you look at me like that." *Like that*—want and grief braided, mid-twenties heat under mid-thirties attention, close enough to burn, far enough that the badge still felt like a different country. "You keep one card. I catalogue the rest. When Cho drips, when the USB opens, when Owen's name in Renny's script matches the pier sighting you finally put on paper—we revisit the pocket. Tonight you get mercy. Mercy has an expiration date in Harborwick. So does my willingness to sandbag a captain for a face I want to keep looking at."

Rain thickened on the glass. Warehouse weather somewhere beyond the block whispered against the city's steel. [player_name] read the journal aloud in pieces while Jake translated teenage shorthand into cold-case grammar: warehouse marks along the waterfront, a city clerk's initials scrawled like a dare, Owen's late nights that did not match the bleach-clean alibi he had carved into family dinners, fear older than seventeen. Not a corpse named. A chain sketched in looping ink. The kind of trouble that made unidentified remains feel like a threat with a pulse—and also like a door that might still open on breath elsewhere if the chain had taken someone else or if Renny had run farther than the river's rumor. Jake photographed the pier map with pencil Xs that did not match any tourist brochure. He bagged the USB in an evidence sleeve he had brought because he was always partly on duty even when his voice went quiet for her. The notebook spine cracked from overuse every time he flexed it shut and open—habit, armor, a small prayer to order.

Attraction was a stupid animal in a room built of absence, and it came anyway. Soap and salt and scrubbed-dark past filled the space when he leaned near to align a photograph. [player_name] tasted burnt coffee and fear and the sharper taste of almost-trust climbing her throat. She wanted to hand him the letter and also wanted to keep one warm private thing against her body while the case bloomed around a silence he had agreed to feel without tearing. Mid-thirties detective with brutal charm and a sealed silence; mid-twenties sister who had obstructed her own sister's case and was now opening metal under his eyes while withholding cream paper like a heartbeat. Trust under interrogation light. Heat under procedural pressure. No second LI. No clean hands. Only this man and this maybe and this pocket.

"Ellison will smell the sandbag if this letter surfaces wrong," Jake said, sitting back on his heels. Rainlight silvered the scar through his brow. "If I find it later without you offering, it will look like obstruction with a pretty face and a detective who got soft. If you give it when the science hardens—one way or the other, Renny named among the dead or Renny still missing with a chain exposed—it will look like a witness who knew how to sequence grief. I am asking you to sequence. I am not asking you to be pure. Pure does not survive Harborwick winters or missing teenagers or captains who measure people for liability the way Cho measures bone for fracture."

[player_name] pressed her palm over the hoodie pocket. Renny's bracelet winked on the desk, gap like a missing tooth. Outside, chain-link rattled in the alley wind. She thought of Owen's too-calm morning voice seven years ago, of Ellison's sixty-second clock still ticking somewhere in fluorescent memory, of Cho's lab and the careful language that still refused to say the name that would either bury hope or baptize dread. Holding hope open hurt. Closing it early would hurt worse. Keeping the letter was a third hurt—private, sharp, maybe necessary, maybe cowardice wearing sisterhood's perfume.

Jake's phone buzzed once against his thigh—Ellison or Cho or the precinct's endless hunger—and he silenced it without looking, eyes still on [player_name]'s hand over the pocket. "Two doors from the holdback," he said softly. He did not touch her. The not-touching felt louder than a hand on her wrist would have. "You let me find the letter anyway—leave it where my catalogue will catch it before dawn, stop pretending the pocket is invisible, let the detective in me do what the man in me is trying not to rush because rushing you feels like another kind of raid I will not survive clean. Or we take what we already opened—journal, map, USB—and we spread the case on the floor at dawn like a second bed, mapping warehouses and clerk initials and Owen's cracks while the letter stays warm against you until Cho's next drip forces the envelope open. One path spends the last scrap tonight under my eyes. The other spends the night building the chain around a silence I can taste and have agreed, for now, not to tear out of your clothes."

Foghorn answered from the river, low and lonely. [player_name] looked at Jake's scarred brow, at the wound he wore as humor's opposite, at the way his gaze kept returning to the hoodie pocket as if paper had a pulse he refused to stop counting. Renny's fate stayed contested: not named, not buried, not safe. The charm still only *like*. Full coop with a soft edge. Partnership with a private ledger. The rain rewrote the window every second. Choosing to let him find the letter meant ending the mercy before morning—truth sequenced on his terms, Ellison fed, hope risked on cream paper that might say goodbye or run or love. Choosing the floor-map dawn meant keeping the scrap against her stomach while Jake's notebook and Renny's Xs became a constellation on carpet, while want and dread and unfinished honesty shared the same damp air until science or courage made *only if* into *now*.

Jake did not fill the silence with comfort. He sat on his heels with the cracked notebook closed against his thigh, grey-green eyes on the hoodie pocket the way a man watches a fuse he has agreed not to light—yet. Ellison's side-eye lived in the wet air as distant weather; the sealed past bruised his posture without needing a name spoken twice. Attention laid flat between them like a blade that had chosen, for one rain-thick night, not to cut the cotton. [player_name] tasted copper where she had bitten her cheek. The letter pressed warm against her belly. Downstairs the radiator knocked its borrowed interrogation rhythm. The USB waited in its sleeve. The journal lay open to a warehouse mark that smelled like pencil and teenage certainty. Choosing meant either ending mercy before dawn—cream paper in his hands, Ellison fed, hope risked on *only if*—or keeping the scrap against her skin while they mapped Renny's Xs on carpet until light found them too close, want and dread unfinished, remains still unnamed, the soft edge of full coop still soft enough to hurt.`,
  textHot: `The lockbox lid was already open when [player_name] made the small, filthy-private decision with Jake Akers's eyes on her mouth and her hands and the cream edge of Renny's letter like he could already taste the holdback. Harborwick rain ticked the glass. Burnt precinct coffee cooled on the desk beside the charm bracelet's missing tooth. Fog pressed like a held breath against warehouse weather beyond the block. Jake knelt opposite her—mid-thirties, scar through his brow, cracked notebook open—and the air between their knees smelled like soap, salt, scrubbed-dark past, and the low electric musk of two people who should not want each other this hard over a teenager's secrets.

Full coop had bought the hour: Owen Vale named on record, the seven-year omission spent under Captain Mara Ellison's fluorescent honesty, access kept on a leash that could still choke. Dr. Lila Cho still said *unidentified*, *pending*, *consistent with*. Remains not Renny until science fucked rumor into fact or mercy. Hope and dread shared [player_name]'s body with a third animal—want—while she slid the letter into the kangaroo pocket of Renny's old hoodie and felt paper warm against her bare stomach under soft cotton that smelled like vanilla ghost and river wind.

"Not yet," she said, voice rough as if he had already been kissing her throat. Mid-twenties pulse hammering in her clit as much as her neck. "Full coop on the chain. Not on the page that is only for me until I know if those bones are hers. If it is goodbye, Ellison does not get goodbye before Cho speaks. If it is run, Owen does not get run through a memo. Hope still has a throat. I am not cutting it so your captain can sleep."

Jake's jaw flexed. Cracked knuckles whitened on his pen. Nina Solis lived in the flinch he aborted toward his ribs—hint only, partner, fall, sealed IA file, charm-as-armor over hallway chaos—he did not dump the raid into Renny's bedroom. The wound showing made [player_name]'s nipples tighten under the hoodie until the cotton scraped; broken men should not be this hot, and Jake Akers wore broken like cologne she wanted to lick off his pulse point. "I felt that," he said, velvet-blade low enough to stroke the inside of her wrists without touch. "The slide. The pocket. I always feel the holdback. It is how I keep a badge and how I get hard when I should get careful." His grey-green gaze dropped to the hoodie pouch resting against her belly, then lower, to where her thighs pressed on carpet and wet heat was already gathering. "I will not tear the cotton off you for a letter. I will also not pretend I cannot smell how much keeping a secret turns you on—or how much watching me know turns you wetter. You are dripping for the lie as much as for me. That is going to fuck with my sleep and my judgment and the way I look at your mouth."

Heat flooded. She was slick already; when she shifted, damp fabric clung to her clit like a filthy confession Ellison must never catalogue. Rain on warehouse glass somewhere down the block clicked like a second clock, and the sound threaded under her skin until every syllable of Renny's teenage script felt like a stroke. They read the journal in pieces—her voice breaking on warehouses and Owen's late nights and a clerk's initials, his pen scratching, his knee brushing hers until electricity shot straight through her cunt and she had to bite her lip to keep from moaning over teenage ink. Yellow tape ghosted in memory when she said *pier*—festival night, chain-link, the silhouette she had refused to name for seven years—and Jake's free hand flattened on the carpet beside her thigh, fingers spread, not touching cotton, close enough that the heat of his palm made her hips tip forward before she caught herself.

"Easy," he murmured without looking up from the map, and the word was not easy at all: it was a hand on the back of her neck without the hand, a promise that if she asked he would stop being a detective for the length of one filthy breath. [player_name] tasted salt from her own lower lip where she had bitten it. When she leaned to point at a pencil X on the pier map, her breast dragged his upper arm through soft fabric and both of them went still as held breath. Jake exhaled like a man swallowing a groan. The notebook spine cracked. His cock shifted against his trousers hard enough that she felt the change in the air between their knees before she saw it. [player_name]'s cunt clenched around nothing—empty, aching, furious with how grief and want could share a pulse. She wanted his hand in the hoodie pocket—finding the letter, finding skin, finding how soaked she was from a soft lie inside a hard case. She wanted his mouth on the pocket's edge, tongue pressing paper and navel alike. She wanted later and now in the same ruined second, and the bracelet's missing tooth winked on the desk like a dare neither of them would take while Renny's fate stayed contested bone and rumor.

"Ellison will smell sandbag if this surfaces wrong," he murmured, mouth close enough that coffee-breath warmed her cheek and made her lips part. Notebook spine cracked as he flexed it—habit, armor, a sound like a belt considering. "If I find it later without you offering, obstruction with a pretty face and a detective who got soft for a witness's wet eyes. If you sequence it when science hardens—Renny named or Renny still missing, chain exposed either way—it looks like a woman who knew how to order grief. I am asking you to sequence. I am not asking you to be pure. Pure does not survive Harborwick—or the way you look at me when the letter is warm against your stomach and my cock is answering a problem my badge cannot solve on this carpet without turning grief into something we will both have to live with in the morning."

She pressed her palm over the pocket. Paper crackled. Jake watched the press like it was a stroke she was giving herself through cotton, and the hunger in his face was brutal charm scraped raw—invitation and threat in the same scarred-brow gravity. Attraction was blasphemy and gospel both. Mid-thirties to mid-twenties—close enough to burn. Far enough that trust still felt like crossing a border without papers and with thighs slick from proximity alone. His phone buzzed; he silenced it without looking, attention locked on her hand as if Ellison could wait while want could not.

"Two doors from the holdback," he said. Still not touching—worse than touching. The not-hand lived on her skin like heat. "You let me find the letter anyway—leave it where my catalogue catches it before dawn, stop pretending the pocket is invisible, let the detective strip the mercy while the man in me tries not to put you on your back beside the map and fuck the seven-year shake out of your voice until you forget which secret was paper and which was the way you say my name when you are close. Or we take journal, map, USB, and we spread the case on the floor at dawn like a second bed—warehouses, clerk initials, Owen's cracks—while the letter stays warm against your cunt-adjacent pocket until Cho's drip forces *only if* into *now*. One path spends the scrap tonight with my fingers in your clothes and maybe on your skin if you arch into the search. The other spends the night building a chain around a silence I can taste on your breath and have agreed, for now, not to tear open with my teeth—though my cock has not agreed to anything, and you can see that if you look."

She looked. The hard line in his trousers was no longer almost—visible, denied, reciprocal, a blunt honesty his mouth was still trying to keep professional. Foghorn rolled from the pier and vibrated in her ribs; she almost moaned with it. Renny's fate contested. Charm still only *like*. Full coop with a soft edge that made her ache unused and furious with her own body. Choosing to let him find the letter meant ending mercy before morning—his hand in her pocket, paper and maybe the bare skin of her stomach, Ellison fed, hope risked, want banked into ice that would still melt if she touched it. Choosing the floor-map dawn meant keeping the scrap against her belly while they knelt over Renny's Xs until light found them too close, until his restraint cracked mid-briefing or held like a cocked gun, until science or courage made the envelope into a third body on the carpet between their knees.

Jake waited without touching her—and the not-touching pressed on her clit like a thumb that knew exactly where she was ruined. Downstairs the radiator knocked; each knock made her thighs squeeze until a small sound escaped her throat. He heard it. His mouth parted. He still did not reach, because reaching would dissolve the letter, the chain, and Cho's *pending* into the wet heat between her legs, and he would hate the fluorescent morning for what it made of mercy. [player_name]'s heartbeat lived low and slick. Rain rewrote the glass. Pier salt mixed with the musk of her arousal until Harborwick itself seemed to be watching the pocket. The kept letter pressed like a filthy thumb against her belly. She could smell herself under vanilla and coffee and his scrubbed-dark past. Choosing meant either handing him Renny's last page with her wetness still scenting the air—or teaching a cold-case detective how to map a smuggling chain around a scrap he could feel, wanted to fuck open with honesty, and had promised, for one unfinished night of rain and burnt coffee and almost-sex, not to steal.`,
  choices: [
    { id: "scene7b", text: "Let Jake find the letter anyway", textHot: "Let Jake find the letter anyway" },
    { id: "scene7c", text: "Map the case on the floor at dawn", textHot: "Map the case on the floor at dawn" }
  ]
};
