export default {
  id: "scene2a",
  layer: 2,
  title: "Cold File Light",
  text: `The precinct smelled the way Harborwick justice always smelled after midnight shifts bled into morning: coffee burnt past forgiveness, floor wax fighting cigarette ghosts, rain tracked in from the pier district and never quite dried. [player_name] followed William Akers past the bullpen where a radio muttered about a warehouse break-in upriver, past a corkboard pinned with faces that had gone quiet, and into a conference room whose fluorescent tubes hummed like insects trapped in glass.

He did not offer her the soft chair. He pulled the hard one out for her himself—small courtesy, sharp edges still showing—and set a thick accordion folder on the table between them. The label read AKERS / COLD in block print rewritten once when the ink smeared. Will's notebook landed beside it, spine cracked. When he braced his hands on the table edge, she saw the knuckles again: white-scarred at the joints, a map of old impact he never mentioned.

"Captain Ellison cleared thirty minutes," he said, shrugging out of the damp coat. Underneath: white shirt gone soft at the collar, shoulder holster a dark line against his ribs. Mid-thirties looked like overtime on him—handsome the way a storm line is handsome. Through the wired glass, Ellison's office door stood half-open; her gaze flicked once toward Will as they passed and lingered a fraction too long—not greeting, appraisal. Will did not look back. "After that she wants a status note. Cooperate and I keep this conversational. Lawyer up and we get formal fast. Your call stays yours. The file doesn't."

[player_name] sat. The interview-room clock above the door jumped a second with a soft tick that felt personal. A clerk wheeled a cart past. Someone laughed too loud at a joke that did not belong in a building full of missing names. She thought of Renny at sixteen—festival fog, pier salt, the charm bracelet already missing its tiny anchor—and of the unidentified remains Cho was still cutting into numbers across town. Not Renny. Not yet. Not confirmed. The charm in Will's evidence bag could be coincidence wearing her sister's shape.

Will opened the folder. Photographs first: the pier the night of the festival, yellow tape ghosting in older crime-scene shots from a missing-persons unit that had handed the case off like a bad debt. Then Renny's school portrait—grin too wide, hair damp from rain even in the picture. Then the bracelet inventory from seven years ago, one charm listed as *absent / silver anchor approx. 1cm*. He slid the new evidence photo across last: the upriver charm beside a ruler, water-stained, hopeful and cruel.

"Dr. Cho's preliminary," Will said, tapping a sticky note in different handwriting. "Partial remains. Age range spans late teens into twenties. Trauma indicators inconclusive pending more work. No dental lock. No DNA hit yet—familial comparison is what I'm here to ask about, carefully, without promising you a name." His eyes lifted. Grey-green under the fluorescents, tired and precise. "I need you to walk me through festival night again. Not the statement you gave at nineteen. The one you almost gave."

Heat crawled up [player_name]'s neck. The statement at nineteen had been clean in the way lies are clean: Renny restless, friends mentioned, Owen at home with a game on, [player_name] searching the pier until dawn and finding only fog. What she had kept—Owen near the water with someone who should not have been there, his hand on a stranger's sleeve, his mouth shaping *she's run off, don't make this bigger*—sat behind her teeth like a coin she refused to spend.

Will watched her the way men who had learned distrust as a trade watched: not cruel, not soft. He leaned back; the chair complained. "I used to work a different kind of case," he said lightly, as if offering weather. "Before Harborwick decided cold ones suited me." The half-smile arrived—brutal charm, a joke that could bruise. "There are files in my desk I don't open on days I need to be kind. Sealed ones. Days like that used to include a—" He stopped. The word *partner* almost surfaced; something flinched behind his eyes and was put away like a weapon returned to a drawer. "Anyway. Today I need accuracy more than kindness. Tell me what the statement left out, and I won't make you bleed it in front of Ellison unless I have to."

"You talk like you've already decided I'm guilty of something," [player_name] said.

"I talk like a man who's been lied to by people who loved someone." He flexed his scarred knuckles once against the notebook, then flipped a page. Witness summaries. A carnival vendor who thought he saw Renny arguing near the fry booth. A pier security log with a gap between 11:40 and 12:15 that nobody had adequately explained. Owen Vale's alibi line highlighted in old yellow marker: *home / television / asleep by one*. Will's finger rested on Owen's name a half-second too long, then moved on. "Your stepfather still in town?"

"Estranged," she said. The word tasted like old metal. "He calls when he wants to remind me the family name still has weight. I don't invite him upstairs."

"Smart." Will made a note. The pen scratched. "Ellison thinks family witnesses contaminate. I think family witnesses are where the case actually lives. Difference of theology." He glanced at the clock. Twenty-two minutes left on Ellison's leash. Through the glass, Ellison crossed the hall and her attention snagged on Will again—side-eye sharp enough to taste—before she vanished into another doorway. Will's mouth flattened. "Walk the night with me. Pier entrance. Who you saw. Who you didn't want to see. What Renny was wearing. Whether she mentioned money, fear, a man, a boat. Whether anyone told you to keep a detail off the record for her own good."

The fluorescents buzzed louder. [player_name] could smell her own rain-damp coat and the burnt coffee on Will's breath when he leaned to turn a photograph. Up close, the pale line through his left eyebrow looked older than the overtime. She wondered, not for the first time, what kind of past put a detective into cold cases with a smile that sharp and knuckles that cracked when he made a fist under the table.

She talked. Carefully. Festival crowds, Renny peeling off toward the music, the missing charm joked about and then forgotten. Searching. Calling. The fog horn. Dawn. She did not say Owen's name in the pier sentence. Not yet. The omission sat between them like a third person at the table, and Will's pen paused exactly where a better liar would have kept writing.

"You're editing," he said quietly. Not accusation. Recognition. "I can hear the cut." He almost smiled. "Kids in hallways learn to edit fast, don't they—" The joke died mid-breath, gone ugly, gone somewhere she was not invited. He closed the notebook without looking away from her. "I'm going to ask you something off Ellison's clock. Do you want this to stay a conversation in a conference room, or do you want to put something on a recorded formal interview before Cho's lab finishes arguing with itself? Formal means protection and pressure. Informal means I keep walking with you—and I will walk you to the pier if that's where the truth is hiding."

Outside the wired glass, Ellison's yellow strip of office light widened again. Voices. Footsteps. The clock ticked like a metronome for decisions.

Will set the charm photograph face-up between them. Unidentified. Unconfirmed. A maybe that could gut her either way. His voice dropped into that soft register that felt like a hand at the back of the neck—steadying or steering, she could not tell.

"Your sister was a teenager who vanished into Harborwick fog," he said. "The remains upriver are still a question mark with a silver charm attached. I don't close question marks to make captains happy." A pause; cracked knuckles flexed once more. "I also don't let people I—" He stopped, recalibrated, and the charm of it turned briefly honest. "I don't let people I need as witnesses drown in what they kept. Choose how we do the next hour. Stay and go on record, or walk out with me to the water where she disappeared. Both cost. Both might give her back a name—or take the hope that she still has one."

The folder's edge dug into [player_name]'s palm where she had gripped it without noticing. Rain found the high windows. Somewhere in the building a phone rang and rang and nobody answered, and the silence after it stopped felt like the exact shape of seven years.

Somewhere in the bullpen a detective cursed at a printer. The ordinary noise made the conference room feel more like a throat closing. [player_name] stared at Renny's school portrait until the grin blurred, then at the upriver charm until the silver stopped looking like jewelry and started looking like a dare. Will did not rush her. He only turned one more page—festival vendor contact sheets, phone numbers half-crossed out, a note in Ellison's hand that read *clear or close*—and let the pressure do the talking. The scarred knuckles rested open. The sealed past stayed sealed. The choice, somehow, still felt like standing at the pier in fog with a sister who might still be breathing somewhere the river had not touched.

Will waited. The half-smile was gone. What remained was worse and better: a man who looked like he had buried things and dug them up again, offering her the shovel or the tape recorder, and refusing to pretend the choice was gentle.`,
  textHot: `The precinct hit her body before it hit her mind: burnt coffee in the sinuses, floor wax and old smoke, rain-salt still living in her coat from the stoop where William Akers had looked at her like a door he intended to open carefully and completely. [player_name] followed him through the bullpen with her pulse doing something undignified against her throat. Radios muttered. A corkboard of quiet faces watched them pass. Fluorescents in the conference room hummed against her skin as if the light itself had a temperature.

Will pulled the hard chair out for her. The courtesy was intimate in a building built to strip intimacy out of people. When he shrugged off the damp coat, the white shirt beneath clung faintly at his shoulders; the holster cut a dark line along his ribs. He set the accordion folder between them and the cracked notebook beside it. Scarred knuckles braced the table near her wrist—white at the joints, a history of impact—and when they nearly brushed her skin the near-touch traveled up her arm like a fuse. Mid-thirties, sleep-starved, mouth made for saying hard things softly.

Through the wired glass, Captain Ellison's gaze snagged on Will as they settled—not a greeting. A side-eye with teeth. Will did not return it. "Ellison gave us thirty," he said, voice low enough to live behind the sternum. "Conversational if you cooperate. Formal if you lawyer. Your call. The file stays hungry either way."

She sat. The clock ticked against her collarbone. Renny rose in her—sixteen, festival, hoodie, bracelet missing its tiny anchor—and with Renny came the other heat: unidentified remains under Cho's care, a charm that might be a sister's and might be a stranger's, hope and dread sharing the same seat in her gut. Will's eyes on her did not help. They looked like they knew how to undress a story.

Photographs first. Pier. Tape. Renny's grin. The old bracelet inventory. Then the upriver charm beside a ruler, and Will's fingertip resting on the edge of the photo as if steadying something that wanted to cut. "Cho's prelim," he murmured, close enough that burnt coffee and rain and clean soap reached her. "Partial. Age range wide. No dental lock. No DNA yet. I'm asking for familial comparison without promising you a corpse with your sister's name. I need festival night again. Not the statement from when you were nineteen. The one your mouth keeps swallowing."

Heat flared low in [player_name]'s belly—shame and want braided, inconvenient, alive. The old statement had been a clean lie: Renny restless, Owen home, searching till dawn. What she had kept—Owen on the pier with a stranger, his voice telling her not to make it bigger—pressed behind her teeth. Will leaned back, chair complaining, shirt pulling across his chest, and watched her like a man who had learned the taste of omission.

"I used to work uglier rooms," he said, almost idle, almost a caress of honesty. "Before cold cases. There are files in my desk I don't open when I need to be soft with someone. Sealed ones." The half-smile arrived, brutal and bright, a scar showing in the charm. He started to say something about a partner—the word shaped itself on his mouth—and then flinched so small she might have missed it if she had not been staring at his lips. Whatever name lived behind that flinch stayed buried. "Today I need the truth more than I need you comfortable. Give me what you cut, and I'll try not to make you bleed it for Ellison."

"You talk like you've decided I'm guilty."

"I talk like a man who's been lied to by people who loved hard and badly." His scarred knuckles flexed once against the notebook spine, a quiet crack of bone-habit, then his finger found Owen Vale's highlighted alibi and lingered—pressure, not accident. Up close she could see the pale cut through his left eyebrow and wonder what kind of past sharpened a detective into this particular weapon. He did not offer the story. He offered his attention, which felt more dangerous. "Your stepfather still around?"

"Estranged." The word scraped. "He calls to remind me the family still has weight. I don't let him upstairs."

"Good." Will's pen scratched. The sound went down her spine. "Ellison thinks family contaminates." Through the glass Ellison crossed again; the side-eye found Will's back and stayed a beat too long. Will's jaw tightened as if he felt it. "I think family is where the body heat of a case lives." He checked the clock. Minutes thinning. "Walk the night with me. Who you saw. Who you didn't want to see. Whether anyone put a hand on your shoulder and told you which detail to leave out for Renny's own good."

She talked. Festival. Music. Renny peeling away. The missing charm as a joke. Fog. Dawn. She did not put Owen in the pier sentence. The omission sat between them like shared breath. Will's pen stopped exactly where a lover's hand might have paused on a rib—knowing, waiting.

"You're editing," he said, quiet enough that she felt it more than heard it. "I know that sound." Almost a smile. "Kids in hallways learn to edit—" The joke died mid-cut, gone somewhere sealed and ugly; his eyes shuttered for a heartbeat, then opened on her again as if nothing had cracked. He closed the notebook. His knee under the table was close enough to hers that a shift would make contact; neither of them shifted; the almost was worse. "Off Ellison's clock: do you want this on a recorded formal interview before Cho finishes arguing with bone, or do you want to walk out of here with me to the pier where she vanished? Formal means the system puts its mouth on you. The pier means I put my attention on you without a red light. Both will cost. Both might give her back a name—or take the hope she's still breathing somewhere the river didn't reach."

Ellison's office light widened in the hall. Voices. The charm photograph lay face-up between them, unidentified, unconfirmed, a maybe that made [player_name]'s throat tight and her skin too awake. Will's voice dropped into that register that felt like fingers at the nape—steadying, claiming, not yet asking permission for more. Scarred knuckles rested open on the table, close enough to cover with her palm if she were reckless.

"Your sister was a teenager swallowed by Harborwick fog," he said. "Those remains are still a question with silver on it. I don't close questions to please captains." A flicker across his mouth—almost the smile, almost something hungrier. "I also don't watch a woman drown in what she kept while looking at me like that. Choose the next hour. Stay and go on record. Or leave with me to the water. I will not pretend either path keeps your hands clean—or mine off the parts of this that aren't only the case."

She realized she had been gripping the folder hard enough to bite her palm. Rain found the high windows. A phone rang unanswered somewhere in the building, and when it stopped the silence had the exact weight of seven years and one man who smelled like coffee and rain and unfinished violence sitting close enough to ruin her carefully built quiet.

The printer curse from the bullpen came through the glass like a reminder that other people's ordinary nights still existed. [player_name]'s thighs pressed together under the table without permission; want had no manners in fluorescent light. She looked at Renny's grin until her eyes stung, then at the charm until silver tasted like metal on her tongue. Will did not fill the silence with comfort. He filled it with presence—coat draped, holster dark, cracked knuckles open on the folder as if offering a hand without offering safety. When he spoke again his voice was lower still, intimate as a confession booth. "I won't name what I buried to keep this badge," he said, not quite looking at her, "and I won't ask you to name yours until you choose the room. But I will sit here until you decide whether truth gets a red light or salt air." The almost-touch of his knee under the table became a pulse. Ellison's light stayed wide in the hall. The remains stayed unidentified. Hope and dread shared [player_name]'s mouth like a kiss she had not agreed to yet.

Will waited. No smile now. Only the dangerous patience of someone who had buried a partner's name and a sealed file and still knew how to dig—with a badge, with a mouth, with the kind of attention that made truth and want feel like the same fever. [player_name] pressed her thighs together under the table edge and felt how unfinished the file had left her.

[player_name] felt the choice settle between her legs and behind her sternum at once: the red light of a formal room, or the pier fog and his coat open to the weather, and either way his eyes on her like a promise that cooperation would never be only paperwork again.`,
  choices: [
    { id: "scene3a", text: "Stay for the formal interview — put something on record", textHot: "Stay for the formal interview — put truth on record while he watches" },
    { id: "scene3b", text: "Pull him out — walk the pier where she vanished", textHot: "Pull him out — walk the pier where she vanished, close enough to touch" }
  ]
};
