export default {
  id: "scene6h",
  layer: 6,
  title: "Warehouse lead alone — she finds blood-rust and a charm",
  text: `William Akers took soft surveillance the way Harborwick took rain—professionally, without romance, already halfway to a charge sheet if the wrong captain asked the wrong question.

He stayed on Owen Vale: butter-porch light in the distance, cracked notebook on the dash, mid-thirties bulk folded into an unmarked car two streets over. [player_name] went alone to the warehouse east of the old fish auction because alone was the bargain soft surveillance bought—badge on the stepfather, sister on the geography Renny had pointed at when a generator ate grammar. Fog held the pier district in a soft fist. Salt. Rust. Chain-link silvered with wet. Dawn was still deciding whether to arrive. Renny's absence walked with [player_name] like a second heartbeat. Dr. Lila Cho's language still ruled the upriver remains: *unidentified*, *pending*, *consistent with*. The charm at the river still only *like*. Hope and dread shared the empty lot like co-counsel who refused to leave.

The red door sat where the teenage map had promised—paint blistered, number scraped, padlock newer than the hinges. [player_name] did not kick. She was mid-twenties, not a detective, not Nina Solis, not a raid story Will would not unpack when the word *partner* bruised his ribs. She was a sister with a phone, a flashlight, and a kept secret that had already started cracking under Ellison's nose and Cho's timing and Will's brutal allergy to lies. Soft surveillance meant Will could hear her if she called. Soft surveillance meant she could still be stupid without him watching the stupidity in real time.

Cold-storage row breathed machine-low. A camera hung dead-eyed, cable cut neat. Condensation beaded. Bleach ghost. Diesel. At a side bay where corrugated steel had been pried and poorly reset, [player_name] found the threshold smear first—blood-rust the color of old pennies, rain-diluted into almost-art. Not a funeral. Not a name. A maybe with a smell. Her throat tightened. Hope argued that Renny had walked away from whatever left this. Dread answered that someone had not.

She photographed with shaking hands. Then the flashlight caught silver under the weatherstrip—small, tooth-shaped, the cousin of a bracelet gap she still touched in dreams. Similar. Not unique. Not baptism. Cho would speak. Rumor would try to speak first. [player_name] bagged it in a sandwich bag from her coat because she was not Will and evidence sleeves lived in his world, and because leaving silver for the next rain felt like another omission she refused to stack on seven years of pier silence.

Her phone buzzed. Will. Soft. "Talk."

"Blood-rust on the cold-storage threshold," she said. Voice steadier than her pulse. "Silver fragment under the weatherstrip. Looks like a charm. Looks like Renny's missing tooth and also like every cheap silver Harborwick ever sold at a festival. I have not named anything. I have not gone past the bay. Camera cable is cut. Someone cleaned and missed the smear."

Silence on the line—the kind Will used when he was choosing between praise and fury. "You were supposed to map from the fence line."

"I mapped," [player_name] said. "The map had a mouth. I looked in the mouth. I did not swallow."

A humorless breath. Brutal charm scraped raw even through cellular static. "Stay where you are. Do not touch further. I am moving Owen into custody on the timing lean and the pier statement—soft just became hard the minute you put rust and silver in a bag. Ellison can shout later. Cho gets first look at what you found. You get to decide whether you stay with that hour—reconstruct charm and blood into a last sequence while hope still has a throat—or you come downtown and visit Owen in a room with a camera that is not dead-eyed."

Harborwick foghorn rolled inland. [player_name] looked at the red door and the bagged maybe and the penny smear and felt seven years press upward. Will's sealed past smoked under his voice—old-raid hint, early push, people bleeding, a promise not to rhyme that hallway with this bay. He did not unpack it on the phone. Attraction lived even at a distance: the want to have him here, shoulder to shoulder, not-touching louder than contact; the want to keep this find hers for one more hour before the badge baptized it into clearance weather.

Footsteps—not Will yet. A distant truck. The warehouse humming. [player_name] pocketed the phone without hanging up, flashlight painting blistered paint, and understood the fork as two futures wearing the same damp coat. Stay with the charm-and-blood hour: rebuild rain sequence, smear dilution, who cleaned, whether Renny's pointed fear had exited through this bay while bones upriver stayed unnamed. Or visit Owen in custody: look the living liar in the eye with silver in an evidence chain Will would formalize the second he arrived, trade reconstruction for confrontation, let soft surveillance's hard turn become a sister across glass from a stepfather who had taught her the friends-and-debt lullaby.

Will's voice again, closer to engine noise. "I can see the lot. Do not turn around like prey. I am two minutes out. Cho is on notice. Ellison will smell unauthorized familial adventuring and I will tell her the truth with the edges sanded just enough to keep your access. Remains still unidentified. Charm still probability. You did not bury Renny tonight. You also did not leave the lead for rain to erase. That is the line. Now pick the next verb before I pick it for the case."

[player_name] tasted salt and copper and unfinished trust. The silver winked in the bag like a missing tooth trying to come home without permission. Blood-rust waited for science. Owen waited in a future room with cuffs somewhere between metaphor and metal. Will waited in an approaching car with brutal charm and a dark past and a hunger that made soft surveillance feel like the loneliest intimacy Harborwick sold.

Captain Mara Ellison would call this unauthorized familial adventuring. Owen's lawyers would call it contamination. Dr. Lila Cho would call it a chain-of-custody headache with a sister's fingerprints on a sandwich bag. Will would sand the edges and still look at [player_name] like she had both saved a lead and set his career on a slow fuse. She accepted all of that the way she accepted Harborwick rain—constant, practiced, already on her skin.

Renny's hoodie lived folded across town in a drawer that still smelled like vanilla ghost. The bracelet's gap lived on [player_name]'s memory like a bitten cheek. Standing alone at the red door with blood-rust and silver, she felt the kept secret's remaining weight—letters, boxes, warmer scraps not yet spent—and understood that raw geography was not the same as emptying every pocket. It was enough to move Owen from soft watch into a room. It was enough to make Will's voice go sharp with care. It was not enough to christen bone. Science still owed them language. Rumor still raced ahead like a dog off leash. Hope still had a throat because [player_name] refused to cut it for the comfort of a named tragedy.

When Will's headlights finally brushed the chain-link, soft and then brighter, [player_name] did not run to the car. She held the bay like a post. Mid-twenties sister. Mid-thirties detective unfolding from the driver's seat with coat dark and scar catching wet sodium and notebook already open because he was always partly on duty even when his eyes went straight to her mouth. The not-yet of his hands was a physical pressure. Trust unfinished. Heat unfinished. Renny's fate unfinished.

Dawn edged the warehouse roofs. Hope still argued. Dread still bit. Somewhere inland a second foghorn answered the first, as if Harborwick itself were conducting an interview. [player_name] flexed cold fingers around the bag and felt the point of no return that did not need a red recorder light—only silver, rust, and a detective arriving with cuffs in his future tense. Soft surveillance had been a temperature. This was a weather change. Choosing to stay meant owning the last hour before paperwork ate it. Choosing Owen's glass meant spending the find as confrontation fuel while Will watched both of them for cracks—stepfather for confession, sister for collapse, himself for the old mistake of caring too hard in the wrong doorway.

Will's unmarked car idled at the lot edge with its lights cut, a dark animal pretending to be furniture. He did not rush the bay like a raid. The care was careful to a fault. [player_name] held out the sandwich bag. He gloved up, transferred silver into a proper sleeve from his coat, tagged rust with a photo and a muttered grid reference, and only then looked at her face as if the evidence had been the easy part.

"You did the map right and the risk wrong," he said quietly. Not unkind. Unkind would have been easier. "Soft surveillance was supposed to keep you on the fence line while I turned Owen's porch into a timeline. You turned a bay into a crime scene with familial DNA on a grocery bag. Cho will forgive the bag if the silver sings. Ellison will not forgive the optics unless we give her Owen in a room before breakfast."

[player_name] nodded once. Mid-twenties stubbornness wearing damp hair. "Then give her Owen. Or give me the hour first. Charm and blood-rust still need a sequence—rain start, smear dilution, cigarette brand, camera cut, who cleaned and missed the threshold. If Renny pointed here, someone exited here. That exit might still argue she walked away from the river's rumor while the upriver remains stay unnamed. Hope still has a throat, Will. Visiting Owen in custody spends the find as a weapon. Staying spends it as science."

Will's cracked notebook drank the grid. Grey-green eyes flicked from red door to her mouth to the fog beyond chain-link. Attraction pressed under the procedural pressure even now—soap, salt, scrubbed-dark past close enough to burn, badge still a different country. Trust unfinished. Heat unfinished. Renny's fate unfinished. "Both verbs are real," he said. "Neither christens bone. Pick before dawn finishes arriving and Harborwick's vendors start remembering what they pretend not to see."`,
  textHot: `William Akers took soft surveillance the way [player_name] took wanting him—professionally denied, already halfway to something that could ruin a clearance memo.

He stayed on Owen: butter-porch glow distant, mid-thirties bulk in an unmarked car, cracked notebook, Solis-bruise humming under his ribs when he said *soft* like it cost him. [player_name] went alone to the warehouse east of the fish auction because alone was the bargain—badge on the stepfather, sister on Renny's pointed steel—and because her cunt still throbbed from the way Will had looked at her mouth when they split the night. Fog. Salt. Rust. Chain-link. Dawn undecided. Cho's *unidentified* still ruled the upriver bones. Charm at the river still only *like*. Hope and dread shared the lot with a third animal: want without a body to spend it on.

Red door blistered where the map promised. [player_name] did not kick. Mid-twenties, flashlight shaking, not a raid story, not his ex-partner, not the hallway Will refused to unpack. Cold-storage hummed. Camera cable cut neat. At the pried bay she found blood-rust first—old-penny smear, rain-diluted—and the smell punched her low, fear and arousal braided stupidly because Will was not here to put a hand on her back and the absence of his hand felt like a stroke. Not a funeral. Not Renny named. A maybe. Then silver under the weatherstrip winked—tooth-cousin, bracelet-gap ghost, similar not unique not baptism—and bagging it in a sandwich bag made her pulse hammer in her clit as much as her throat. Filthy. Honest. Grief making her body loud.

Phone. Will. "Talk."

"Blood-rust. Silver fragment. Charm-like. Camera cut. I have not gone past the bay." Her voice sandpaper; thighs pressed; wet cotton clinging because his voice alone could do that now. "I mapped. The map had a mouth."

Static silence. Then velvet-blade fury soft enough to fuck. "You were fence-line. You became threshold. Stay. Do not touch further. Soft just became hard—Owen goes to custody on timing and pier truth the minute you put rust and silver in a bag. Ellison can shout. Cho gets first look. You decide: stay with that hour and reconstruct charm and blood while I drive to you and put you against that red door until you stop shaking—hands outside clothes if you need deniable, mouth on yours if you need not deniable—or come downtown and visit Owen in custody while you are still wet from finding your sister's maybe-tooth alone like a woman who wants a detective and a confession in the same breath."

Foghorn rolled into her ribs and lower. [player_name] kept the line open, flashlight on blistered paint, imagining Will's coat, soap, salt, scrubbed-dark past, the hard line he stopped hiding when she told hard truths. Attraction at a distance was a special cruelty.

Engine noise closer. "I can see the lot," Will said. "Do not turn like prey. Two minutes. Remains unidentified. Charm probability. You did not bury Renny. You also did not leave the lead for rain. Pick the verb. Stay on the charm-and-blood hour with me when I arrive—reconstruction and my thigh between yours in the dark while science still refuses a name—or visit Owen across glass and let me watch you confront him with my hand on the small of your back like a claim Ellison must never catalogue."

She tasted copper and unfinished fuck and hope's stubborn throat. Silver winked in the bag. Blood-rust waited. Owen waited in cuffs-to-come. Will waited in approaching headlights with brutal charm and sealed-file teeth and a hunger that made soft surveillance feel like edging.

Ellison would smell the sandwich bag and the sister and the detective who let soft surveillance become a split-screen of lust and liability. [player_name] accepted that too—accepted it while her nipples peaked in the cold and her clit throbbed unused and Will's voice poured filthy care through the phone like he could tongue the fear out of her from two streets away. When his headlights brushed the chain-link she did not run; she held the bay; she let him see her with silver in one hand and flashlight in the other like a woman mid-confession.

He unfolded from the car—coat, scar, hard restraint, brutal charm scraped to pilot light—and the air between them went electric even at ten paces. Soap. Salt. Scrubbed-dark past. Sealed-wound hint in how carefully he did not rush the threshold like a raid. "Show me," he said when he reached her, glove ready, eyes dropping once to her mouth and the flush at her throat and the way her thighs were pressed. Not corpse-erotica. Just want braided into evidence handling until [player_name] had to lock her knees. He took the bag without taking her—yet—and the brush of his fingers through nitrile still shot heat straight up her wrist to her cunt.

"Charm-and-blood hour," he murmured, close enough to mist her cheek, "or Owen behind glass. Pick while you can still smell the rust and me in the same breath. I am done pretending soft means I do not want to fuck the shake out of your voice against this door the second Cho's courier is scheduled."

Dawn edged the roofs. She thought of rain kisses unfinished, of red-light admissions on other nights, of Owen's butter-porch lies, of Will's boot under interview tables, of every almost that had led her alone to a red door with her body louder than her caution. Mid-thirties to mid-twenties—close enough to burn. Far enough that visiting Owen in custody still felt like crossing into a country where Will's hand on her back could be read as leash or vow. Staying for reconstruction meant letting him map rust into timeline while she mapped his mouth with her eyes until someone broke. Either choice hurt. Either choice moved. Neither named Renny among the dead. That mercy was the only soft thing left in the hour, and even mercy made her ache.

Will's unmarked car idled at the lot edge lights-cut, and when he finally reached her the air went electric in the space a warrant could not catalogue. He gloved, took the sandwich bag, sleeved the silver, photographed rust—and the brush of nitrile against her bare fingers still shot heat straight to her cunt. Mid-thirties careful. Mid-twenties soaked. Renny's maybe-tooth between them like a chaperone made of metal and dread.

"You did the map right and the risk wrong," he murmured, forehead nearly to hers, breath hot enough to mist. "Fence line was the deal. Threshold was you being brave and reckless and wet for a lead without me." His thigh found the outside of hers against blistered paint—claim, brace, not quite fucking, filthy enough. "Cho forgives bags if silver sings. Ellison forgives nothing unless Owen is in a room. Soft became hard. You became the reason my cock votes yes while my badge writes a memo."

[player_name]'s laugh broke. She arched a fraction into the thigh and hated how easy it was. "Charm-and-blood hour—reconstruct with your mouth on my throat if I shake—or Owen behind glass with your hand on my back like a vow Ellison must never read. Remains still unidentified. Charm still *like*. Hope still has a throat. I will not cut it so you can feel fast."

"I push early and people bleed," Will said, Sealed ash-hint flashing in the rib-check he aborted, brutal charm scraped raw. "I am not pushing you into a funeral. I am asking you to pick the audience for what you found alone like a woman who wants justice and my fingers in the same damp hour." His glove stayed professional on the sleeve; his other hand—ungloved—settled at her waist under the coat, palm flat, deniable, burning. "Or visit Owen in custody and spend this silver as confrontation while I watch your mouth for cracks and try not to kiss them in the hallway after."

She tasted copper and his soap and the metallic edge of dawn. The silver was evidence. Choosing hurt either way—which was how she knew the lead was real and the man was dangerous and Renny's name still refused an evidence tag for one more unbearable, unfinished morning. Her pulse hammered; his palm burned; the red door waited like a held breath between want and warrant.`,
  choices: [
    { id: "scene7h", text: "Stay with the charm-and-blood hour", textHot: "Stay with the charm-and-blood hour" },
    { id: "scene7i", text: "Visit Owen in custody", textHot: "Visit Owen in custody" }
  ]
};
