export default {
  id: "scene7k",
  layer: 7,
  title: "Sink-trap SIM: messages to a city clerk",
  text: `The SIM chain glowed on Jake Akers's laptop like a municipal throat clearing itself in fragments.

Back-lab strip light. Solvent ghost. Burnt precinct coffee. [player_name] sat shoulder-to-shoulder with him while Harborwick rain freckled the high window and Dr. Lila Cho's unidentified remains still waited upriver without Renny's name—timing lean, charm consistent-not-unique, hope and dread sharing the lab tray like co-workers who refused to quit. Soft net had burned. Sink trap had yielded. Phone ash had become recoverable. Now the nano-SIM's surviving messages threaded toward a city clerk: timestamps after midnight, stubs that resolved to a Harborwick directory entry half-redacted by politics, a repeating grammar—*soft*, *M*, *move the paper*, *sister pointed*, *quiet or loud*—that made [player_name]'s mouth taste copper and old festival fog.

Jake's mid-thirties bulk angled toward the screen: scar nick pale, cracked notebook open beside the keyboard, brutal charm locked into working patience that was not mercy. Whitened knuckles flexed when a particular string resolved. Captain Mara Ellison had texted three times. He showed [player_name] none of them. He showed her the chain instead.

"Clerk," Jake said without looking up. "Not a comic villain. A desk that moves permits for people who move crates. Owen reached him the night soft got close. Reached him again after the alley fire. Reached him in language that assumes a teenager's pointing finger was a problem to be managed—not a sister to be found." His late smile arrived and died in the same breath. "This is enough for a warrant lean. Enough for Ellison's clearance narrative if we sand it soft. Enough for a press conference if we decide quiet deals protect the wrong throats. What it is not: a baptism of Cho's bones. Charm probability stays elevated without confirmation. Age range stays ugly with hope. I will not let a text string print Renny on silt."

[player_name] tasted solvent and rain. Mid-twenties and done pretending ash was only Owen's problem. Renny's absence pressed under her ribs; the kept secret pressed harder—pier night, Owen, the stranger, seven years of scrubbed silhouette that messages could illuminate without resurrecting. "Will Ellison let us go public?"

"Ellison will let us go quiet if quiet clears her inbox." Jake finally met her eyes—grey-green, tired, hungry for a break that would not eat them. "Public makes politics. Quiet makes bargains. Press conference puts the clerk on a stage and the chain under lights the city cannot pretend not to see. Quiet deal trades partial immunity or sealed pages for a name and a map—soft justice with hard costs. Both leave your sister a question mark tonight. Both leave me compromised in ways Nina Solis would recognize if she walked these halls again." Hint only: sealed IA file smoking, raid weather, a teenager in the wrong hallway, Ellison's muttered fear that Akers pushed early and called the smoke care. Teeth showing. Wound not unpacking.

Attraction hummed under procedural dread—his competence, the dangerous care of refusing false funerals, the way his cracked knuckle brushed hers when they scrolled the same thread. Mid-thirties to her mid-twenties—close enough to burn, far enough that the badge still felt like a different country. She wanted his steadiness and hated that she wanted it while Renny's fate stayed contested.

A gown tech nodded from the doorway and left them alone with the glow. Jake walked the perimeter of the table the way he walked interview rooms—counting exits, counting lies, counting what soft nets cost when they became SIM ghosts. [player_name] watched his shoulders under charcoal that still held alley rain. Outside, warehouses hunched in fog. Inside, the clock hummed like every precinct clock that had ever watched a familial contact choose pages over protection.

"Walk me through what Renny would have seen," Jake said. Not a quiz. A partnership verb.

"Red doors," [player_name] said. Voice held. Barely. "Pencil Xs on a pier map. A man who was not supposed to stand with Owen. She half-understood crates and permits. She understood enough to point. I understood enough to scrub—and that scrubbing is why we are reading after-midnight texts instead of finding her alive in a kitchen that still smells like dryer sheets." She swallowed. "If we hold a press conference, rumor will try to bury her before Cho finishes. If we cut a quiet deal, someone seals a page that might be the only throat that still remembers her laugh."

Jake nodded once. Respecting the line even while his eyes said he wanted to put her somewhere soft after solvent. "Ellison wants this bagged and briefed. She distrusts family witnesses who arrive smelling like porch rain and guilt. She distrusts me when results leave fingerprints on more than evidence bags. Two doors from this screen. Hold a press conference—blow the SIM chain into daylight, name the clerk under lights, accept the storm. Or cut a quiet SIM-chain deal—bargain sealed pages and supervised truth for a map that still might lead to Renny's fate without feeding the city a false funeral. Press keeps the hunt loud. Quiet deal keeps the hunt alive in rooms without cameras. Both hurt. Both keep hope employed. Both keep dread honest."

He did not touch her mouth. The almost hung unfinished on purpose—hook as craft. Solvent stung [player_name]'s eyes. Jake's notebook spine cracked when he closed it, overuse showing like a second scar. Behind him the screen glowed with partial truths: M, soft, clerk, timestamps that refused to resurrect a girl and refused to bury her.

Rain thickened on the glass. A foghorn rolled inland like the river clearing a throat that still had no sister's name. [player_name] thought of Owen's clean hands, of the alley flare, of a silver bracelet gap like a missing tooth on a dresser across town, of Renny's hoodie folded inland. The SIM dish winked under strip light empty now—contents imaged, chain living in pixels Jake refused to christen with a corpse.

"When the sealed past and I—" Jake stopped. Charm armor sliding. Wound showing a tooth and then hiding. "When a raid goes sideways, people rinse what they can. Partners take weather. Kids in hallways pay for urgency dressed as care. I am not dumping that sealed file on your SIM dig. I am telling you why I will not rush an ID or a cuff-show for Ellison's inbox while this chain still has a throat we can aim at a stage or a sealed room." His grey-green eyes found hers. "Hope stays employed. Dread stays honest. You stay in the room."

Silence thickened with the rain. Jake paced once—boot soft on lab tile—then stopped with his back to the window so Harborwick fog framed him like a second interrogation light. "If we go press, I will still be angry in the elevator after—angry at Owen, at the clerk, at seven years of scrubbed silhouettes, at myself for floating soft until ash became the only map. Anger does not cancel the braid. If we go quiet, I will still want your mouth when the bargain ink dries. Want does not cancel the cost of sealed pages. I need you to hear both sentences without sanding either into comfort."

"Clock," Jake said softly. "Hold a press conference—or cut a quiet SIM-chain deal. Either way ash already spoke. Either way Cho's bones stay unnamed tonight. Pick the hurt that keeps truth reachable while Harborwick fog erases the alley where soft burned and a sink trap tried to finish the job water could not erase."

[player_name] looked from the glowing chain to Jake's hunger-and-warning face and felt the choice land like a second lighter—careful, consequential, still capable of fire. Press. Or quiet deal. Renny's fate still contested. Romance unfinished under lab fluorescents. The screen would not forgive a soft lie—and neither would the detective who had dug grease for a maybe and was asking her which temperature of aftermath she could live inside while phone ash cooled into municipal daylight or a sealed bargain and hope and dread still shared the same pulse.

He almost kissed her then—stopped a breath short on purpose—scar nick white under strip light, late smile wrong, all weapon and wound, the brutal charm that had first made her want him under procedural pressure. The denial hung as hook. Soft was dead. The SIM chain was breathing. The next verb would hurt to leave.

[player_name] scrolled the chain once more with Jake's pen tapping the table beside her—soft, soft, soft—Owen's panic wearing the same word Jake had used as costume. Soft net. Soft release. Soft manners. Soft had become a municipal password and a family failure and a detective's attempt not to become his sealed-file flinch. The irony tasted like bleach and burnt coffee.

"Renny kept a map," [player_name] said quietly. "I kept a lie. Owen kept a clerk on speed dial. You kept a sealed hallway. Ellison keeps an inbox. Cho keeps bones without a name. Everybody keeps something. The question is which keeping still protects a living hope and which keeping only protects the people who moved crates past a teenager's finger." She looked at Jake until he looked back. "If we press, I will stand beside you on the steps. If we deal quiet, I will hate every sealed page and still sign what keeps the map breathing. I am not inventing purity. I am not inventing a funeral. I am asking which hurt leaves Renny reachable."

The laptop glow painted clerk-throat messages across Jake's face. Press conference would put the SIM chain under microphones before Ellison could tidy it into a memo. A quiet deal would cut the chain in a room without cameras—and bind [player_name] to bargains that smelled like the sink grease they had dug from. Fog pressed the lab glass. Jake closed the lid halfway; the chain stayed alive underneath. Renny's name still refused to climb onto Cho's tray. [player_name] had to choose daylight volume or sealed leverage while the almost-kiss hung unfinished on purpose between them.`,
  textHot: `The SIM chain glowed on Jake Akers's laptop like a municipal throat clearing itself, and [player_name]'s body answered the glow with a filthy pulse she refused to call pure while Jake's thigh pressed hers under the back-lab table and soft's corpse fucked the timeline forward in pixels.

Strip light. Solvent. Burnt coffee. Cho's unidentified remains still upriver without Renny's name—timing lean, charm maybe, hope and dread sharing the tray—and none of that science stopped the thick idle threat Jake's cock made in jeans while messages threaded toward a city clerk: midnight timestamps, *soft*, *M*, *move the paper*, *sister pointed*. Soft net burned. Sink trap yielded. Nano-SIM imaged. Jake mid-thirties—scar nick pale, notebook open, brutal charm locked to patience that was not celibacy. Whitened knuckles. Ellison's unread texts in his pocket like a second lighter he refused to show.

"Clerk," Jake said, voice low enough to drag along [player_name]'s spine. "Desk that moves permits for crates. Owen reached him when soft got close. Language that treats a teenager's pointing finger like a problem to manage." His hand covered hers on the trackpad—heat, calluses—and the contact shot straight between her thighs. "Enough for warrant lean. Enough for press if we decide quiet protects the wrong throats. Enough for a quiet deal if we bargain sealed pages for a map. Not a baptism of Cho's bones. Charm stays maybe. I will not let a text string print Renny on silt while you soak for the dig."

[player_name] tasted solvent and want. "Will Ellison let us go public?"

"Quiet clears her inbox. Public makes politics." Jake turned her chair, boxed her gently against the counter edge with his hips—pressure, denim, cock a procedural problem neither filed—mouth near her ear, gun oil and soap. "Press puts the clerk on a stage. Quiet deal trades partial mercy for a name. Both leave Renny a question mark. Both leave me hard. Solis would call me compromised—Nina, raid, hallway kid, sealed file I still will not dump in your lap. Hints only. Teeth. She would not be wrong."

He opened her jeans under the table line the doorway could not fully see, slid into panties where she was shamelessly slick from competence and fallout and the filthy mercy of a man who refused false funerals. Two fingers pushed in slow; she clenched; he groaned like confession and pleasure were one sound. "There. Wet for a detective holding SIM ghosts and your waist. Grief and sex can share a body. Do not tidy it. Do not eroticize the bones—contested, unnamed—but do not pretend grease and municipal texts made you celibate."

Gown tech left. Jake walked the perimeter and came back, chest to her back, free hand guiding hers to press against his cock through jeans while his other kept fucking the choice into her with stakeout patience. "Walk me through what Renny saw," he murmured against her jaw, center kiss denied. "Red doors. Pencil Xs. You scrubbed. Scrubbing is why we read after-midnight instead of finding her in a dryer-sheet kitchen. If we press, rumor tries to bury her before Cho finishes—and I put you against a blind wall after the storm and finish what my fingers started with my mouth. If we cut a quiet deal, someone seals a page that might hold her laugh—and I take you apart in a locked room when the ink dries, tip weather and ash still on your tongue."

Thumb on her clit. Forehead to her hair. "Ellison wants this bagged. She distrusts family. She distrusts me when fingerprints leave evidence bags. Two doors. Press conference—blow the chain into daylight—or quiet SIM-chain deal—sealed pages, supervised truth, map without a false funeral on the steps. Press keeps the hunt loud. Quiet keeps it alive without cameras. Both hurt. Both leave me compromised. Both leave you open on my hand until you conjugate."

He added a third finger until she cried out soft against her wrist, then stopped—exact, cruel, tender as a threat—withdrew glistening to paint her lower lip. "Not yet. Not until you pick."

He pressed her palm to his cock—thick, hot, brutal honesty—rolled once into her fist. "Feel what SIM forensics does to me. Soft dead. Hunt live. Want past professionalism. Hold a press conference—or cut a quiet deal. Either way the chip spoke. Either way Renny stays unnamed on Cho's table tonight."

"When his old partner and I—" He stopped against her throat, wound leaking. "Raid weather. Hallway. Kid who should not have been there. I wear charm so nobody asks. You ask by soaking my wrist while ash becomes a clerk thread. I will not dump the whole hallway on your dig. I will let it haunt the press-or-quiet fork beside your tip weather and my hard-on. Hope stays employed. Dread stays honest. You stay open until the verb is chosen."

Rain freckled the window. Foghorn rolled inland. Jake's free hand cupped her nape, grounding, while his other wrist shone under fluorescents he did not wipe. "If we go press, I stay angry in the elevator and still choose your mouth. If we go quiet, I want you when bargain ink dries and still hate every sealed page. Anger does not cancel the braid. Want does not cancel cost. Hear both without sanding either into comfort."

She rocked once; he hissed and stopped her hip, unfinished climax held like evidence. "I could finish you against this tray. I will not. Not until the verb is chosen. Wanting you past professionalism does not make a false Renny funeral holy. Bones stay unnamed. Charm stays maybe. Hope stays employed. You stay wet on my hand and still have to conjugate."

[player_name] tasted copper and herself and solvent. Festival fog behind her eyes: Renny's laugh, funnel-cake sugar, Owen's silhouette, pencil Xs, seven years of protection that had become a different violence—and tonight's SIM chain finishing one sentence so another could start in daylight or a sealed room. Jake's scar nick brushed her temple. Late smile wrong—weapon and wound.

He zipped her halfway, adjusted her collar with cuff-tenderness the dig had not required in steel. Screen glowed M and soft and clerk. Ellison's texts burned unread.

"Clock," he said. "Hold a press conference—or cut a quiet SIM-chain deal. Pick the hurt that keeps truth reachable while I can still smell your cunt on my hand under strip light and Harborwick fog erases the alley where soft burned."

[player_name] braced on the lab counter and left her jeans half-honest where his hand had been. Missing charm. Unidentified bones. Clerk throat still glowing in pixels. Press conference, or quiet deal. Neither door would finish what his palm had started under fluorescent patience.

He guided her hand once more along the thick line of him, then set both their palms flat beside the laptop—his covering hers, cracked knuckle white, pulse jumping. "Press means the city hears. Quiet means the bargain hears. Either way Renny stays a question mark on Cho's tray tonight. Either way I leave this lab changed. Murder stays plot. This heat advances trust or it advances nothing. Conjugate, [player_name]. Blow the chain open—or seal the parts that keep a map alive without a false funeral on the steps."

The clock hummed. The screen glowed. Jake waited without softening, unfinished kiss still the sharpest hook in the room while SIM ghosts cooled into either daylight or a sealed vow she could still taste on her own lip.

[player_name] scrolled the chain once more while Jake's fingers stayed idle and shining on the table edge—her slick drying into evidence he refused to wipe, soft soft soft repeating on the screen like a password and a failure and a cock ring of patience he was choosing to keep on for her sake and for Ellison's cameras. Soft net. Soft release. Soft manners. Soft had become municipal and familial and detective and filthy all at once.

"Renny kept a map," she managed, cunt still aching on the edge he would not authorize. "I kept a lie. Owen kept a clerk. You kept a sealed hallway. Everybody keeps something." She pressed his palm back between her thighs—claiming, demanding, conjugating with her body. "Press—I stand on the steps with you and you finish me after the storm. Quiet—I hate the sealed pages and still soak for the bargain if it keeps the map breathing. I am not inventing purity. I am not inventing a funeral. I am asking which hurt leaves Renny reachable while you can still smell me on your hand." Her pulse answered low and shameless; Jake's nearness made the unfinished want feel like a third warrant neither of them could ignore.

Jake cupped her hard through her jeans once—exact, tender, stopped—then boxed her in against the lab counter with the laptop half-closed at her hip. "Press," he said into her throat, "or quiet deal." His cock argued against patience through denim she could feel; her clit throbbed where his palm had been. Clerk pixels still breathed on the dimmed screen. Fog wrote soft threats on the glass. She had to speak before denied climax and denied center-kiss finished conjugating the ash into someone else's story.`,
  choices: [
    { id: "scene8k", text: "Hold a press conference", textHot: "Hold a press conference" },
    { id: "scene8l", text: "Cut a quiet SIM-chain deal", textHot: "Cut a quiet SIM-chain deal" }
  ],
};
