export default {
  id: "scene9c",
  layer: 9,
  title: "Press path: blow it open",
  text: `Harborwick's press storm did not wait for courthouse manners—it took the pier district like weather with mics, rain silvering Warehouse C's chain-link while [player_name] stood under a borrowed canopy with Renny's journal copies, USB plate lists, and Jake Akers at her shoulder like a second set of floodlights that had decided to stay human. Mid-thirties. Charcoal jacket dark with rain. Scar cutting his left eyebrow. Grey-green eyes bloodshot and sharp. Brutal charm filed down to a public edge: velvet sheathed, blade showing in the way he watched the pack as if they were an interrogation room with worse lighting and no Miranda.

Blowing it open meant every warehouse mark Renny scratched, every midnight truck plate, clerk initials M.K. expanded into a hunt City Hall could not soft-pedal, Owen Vale's late nights spoken outdoors without Ellison's sealed drip. Captain Mara Ellison had wanted leash. Ellison was not getting leash. The SIM chain and journal spine were already city weather; this was the rest of the throat cleared under live lights.

"Last chance to let Ellison draft the softer version," Jake said quietly, mouth near [player_name]'s ear, not quite touching. Partnership verb disguised as logistics. "Once the USB hits those feeds, the clerk cannot hide behind initials. Owen's name stops being a family whisper even if he never sees a full-blade trial. The press will invent a corpse before Cho finishes speaking—do not let them. You blow the chain open. You do not christen bone."

[player_name] tasted pier salt and copper. Dr. Lila Cho's unidentified upriver remains still waited in careful language: age range that *could* fit; a charm that *could* match the missing bracelet piece still upstairs; lab ID pending. Hope and dread shared the canopy like co-counsel who refused to leave. The remains were not Renny until science said so. Rumor sharpened knives in real time. Renny—teenager when she vanished, missing seven years—had written *ask [player_name] about the pier night* into purple leather. [player_name] had kept Owen off the record. Daylight storm was the opposite of that softness. Daylight storm was a verb with teeth and no courthouse bailiff to call recess.

Ellison appeared at the canopy edge late, tablet tucked under one arm, mouth a line that could cut clearance metrics. She did not look at Jake first. She looked at [player_name], then at the USB, then at the pack like a woman calculating how much blood a precinct could lose before the evening news. "Akers," she said, pitched for the canopy and not the mics yet. "You are making my city into a circus with better rain."

"I am making your city honest," Jake answered, and the almost-smile that usually meant velvet-blade charm died mid-birth. When Ellison's gaze flicked—almost naming Nina Solis, almost saying sealed IA—Jake's cracked knuckles flexed against his notebook spine. He touched nothing. He did not flinch for the cameras. The dark past hummed under his badge: a partner's fall, a hallway, a silence that rhymed with a sister kept quiet. Hint deepening into pressure the press would smell if he bled it. "Familial contact is ready to release. I corroborate chain of custody. Cho's *pending* stays *pending* on every answer. Anyone who asks you to pronounce those remains Renny gets redirected to the lab like they asked for a miracle and got a protocol."

[player_name] stepped to the mic edge. Rain freckled the USB casing. Chain-link rattled like applause from a city that remembered everything except the official story. Attraction was a stupid animal to bring under floodlights, and it came anyway: the sleep-deprived set of Jake's shoulders, the dangerous care of refusing to invent a corpse for headline grammar, the mid-thirties heat of a man who would stand in public ruin with her mid-twenties shame and call it partnership. Trust was the real plot. Trust tasted like wet iron and purple ink and a captain's fury banked for later.

"My sister Renny kept a journal and a map," [player_name] said into the storm. Voice holding. Barely. "She was a teenager when she vanished seven years ago from a pier-side festival. I am releasing the rest of the chain in public—Warehouse C marks, truck plates, clerk identity beyond initials, my stepfather Owen Vale's late nights, the pier night I kept off the record because I was afraid. I am naming that chain so loudly the official story cannot swallow it again. I am not naming unidentified upriver remains as hers. Lab identification is pending. Hope is still allowed. Dread is still honest. Anyone who collapses those into one story for clicks is doing the chain's work for free."

Jake's cracked notebook opened at her elbow—witness, not puppeteer. He read chain-of-custody timestamps in a voice that made paperwork sound like a vow. Questions surged: Owen's whereabouts, the clerk's full name, whether Jake was sleeping with the witness, whether the charm meant Renny was dead. Jake shut the last one down with a look that could have stopped a truck. "Charm probability is not an ID," he said. "Ask Cho. Ask science. Do not ask grief to do your job."

A reporter near the front shoved closer. "If you are blowing it open, are you leading Renny's story from now on—or hiding behind the detective while the city eats the noise?" The question landed like a hand on [player_name]'s sternum. She felt Jake go still beside her—not intervening, not stealing the answer, offering the space the way he offered coffee and refusal to invent corpses. Mid-thirties patience as a kind of heat. Mid-twenties shame as a kind of fuel.

"I kept quiet for seven years," [player_name] said, and the honesty scraped. "I am done letting Renny be right alone about what I saw. Leading her public story means I stay in the weather—press, hearings, the clerk hunt—until her name is held without the old lie. Enduring the open secret with Detective Akers means we refuse to let the noise invent a funeral or erase hope while Cho still says pending. Both are outdoor verbs. Neither is silence."

Ellison angled in as the first wave broke, close enough that burnt coffee and captain's starch cut the pier salt. Soft for only them: "You blew the leash. Now the city owns the narrative whether you like the grammar. Two doors left that matter for endings—you lead Renny's reckoning yourself, sister as public spine, or you endure the open secret with Akers while Harborwick screams and you refuse to break. IA-shaped shadow on him deepens either way. Solis-shaped questions come back around the second someone smells a detective soft for a witness in floodlights. Choose carefully. Public heroes make pretty targets."

Jake's jaw flexed. He did not dump the hallway. He let Solis pressure deepen into the rain like ash stirred, not a full sealed-file dump. "She chooses," he said. "I stay. That is the whole of my politics under these lights."

Foghorn rolled inland, low enough to feel in the bones. Rain needled the USB. [player_name] tasted Jake's nearness and Renny's ink and the unfinished almost of a kiss they could not finish under floodlights while cameras ate their profiles. Choosing to lead Renny's public story meant walking sisterhood into every mic and holding the reckoning as her own weather—Jake present, not puppeteering—while unidentified remains still waited for science and hope still had a throat. Choosing to endure the open secret together meant city noise as shared climate, love that refused to break under headlines, Renny's name held without inventing a corpse for narrative neatness.

The second wave of questions tried to collapse hope into a headline funeral; Jake redirected every corpse-hunt to Cho with a voice that made protocol sound like devotion. [player_name] released the plate list into outstretched phones and felt Renny's teenage certainty go fully outdoor—Warehouse C marks, midnight trucks, clerk identity beyond initials—while rain freckled her wrists and pier salt filled her mouth. A local anchor asked whether she was ready to lead Renny's story as sister rather than as witness. Another asked whether enduring the open secret with Detective Akers meant hiding. She answered both without looking away from the storm: leading meant staying in every mic until Renny's name was held without the old lie; enduring meant refusing to break under noise while pending stayed pending. Jake's cracked notebook stayed open at her elbow like a spine she did not have to carry alone.

Ellison's soft warning about Solis-shaped questions lingered after the pack reshuffled. Jake did not dump the hallway under floodlights. He let ash stir in the rain and told [player_name], quiet under the noise, that five years ago a teenager in the wrong hallway had caught chaos he ordered—Nina Solis took the fall; he kept the badge—and that rhyme was why he would not invent a corpse for drama and why he would stand in either ending she chose. Mid-thirties confession deepened without becoming a sealed-file dump. Mid-twenties trust climbed her throat like unfinished weather. Attraction banked for a room without lenses. Grief stayed holy.

Down the block chain-link rattled. Somewhere a foghorn answered the river again. The USB's last copy left her hand into a trusted reporter's case with chain-of-custody notes Jake had initialed. Daylight storm was no longer theoretical. It was Harborwick's throat cleared. The only verb left was which ending got to keep the noise—sister's reckoning led by her spine, or open secret endured in the same bed as a detective who refused to christen bone.

Jake Akers watched [player_name] the way a man watches a fuse he has already helped light outdoors. Chain-link rattled. Ellison's tablet chimed. A reporter shouted Renny's name like a verdict. Downriver a foghorn answered again, lonely and low. [player_name] closed her hand around the USB and felt Jake shift half a degree closer—blocking one more lens from her throat without touching her, a claim that was not yet marriage and already felt like weather.

"You blew it open," Jake murmured under the noise, grey-green eyes on her mouth. "Chain is throat-clear. Now you decide whether daylight is a sister's reckoning you lead—or an open secret we endure together while Cho's *pending* stays the only honest word about those remains. Either way I walk it. Either way I will not let Harborwick christen bone because paper is dramatic. Pick the ending the storm gets to keep before Ellison drafts it for you."

Hope still had a throat. Dread still had teeth. Charm upstairs still only *like*. Solis ash stirred under IA shadow without dumping every sealed page. Attraction and grief shared the canopy. The hook sat unfinished: a kiss banked for a room without mics, a public story that could become reckoning or endurance, and Renny's fate still contested in careful language while the city finally learned what the sister had kept.`,
  textHot: `Harborwick's press storm took the pier district like weather with mics, and the air between [player_name]'s body and Jake Akers's was already too warm for floodlights. Rain silvered Warehouse C's chain-link. Foghorns argued. [player_name] clutched the USB and journal copies against her mid-twenties ribs hard enough to feel her heartbeat—and lower, traitorously, where want had no manners and the case had teeth. Jake stood at her shoulder close enough that soap, salt, and scrubbed-dark past filled every inhale. Mid-thirties. Scar catching wet light. Grey-green eyes that dragged over her mouth before they forced themselves to the pack like professionalism were a restraint he kept on for the girl's sake.

Brutal charm banked for cameras—velvet over blade—but his thigh almost brushed hers when he shifted, and the almost shot straight between [player_name]'s legs before either pretended this was only about plates and clerks.

"Last chance to let Ellison draft softer," Jake murmured against her ear, breath hot enough to stroke. "USB hits those feeds and the clerk cannot hide. Owen stops being a whisper. Press will invent a corpse—do not let them. Blow the chain. Do not christen bone. And try—" his cracked knuckles ghosted the small of her back, claim the lenses must not catalogue "—not to look like you want me to fuck the shaking out of you under this canopy. I can feel it from here."

[player_name]'s cunt clenched around nothing. Shame and hunger and grief fucked the same oxygen. Cho's unidentified remains still waited: charm that *could* match, lab pending, hope and dread sharing her pulse. Not Renny until science said so. Jake treated that distinction like sacrament, which made her wetter. Renny—teenager then, missing seven years—had written the pier night; [player_name] had kept Owen off the record; the storm was about to strip both silences while Jake's nearness promised that later—after mics, after Ellison's fury—there might be a room that was not these floodlights.

Ellison appeared at the canopy edge. "Circus."

"Honest," Jake said, and when Ellison almost named Nina Solis, Jake's jaw flexed and his hand stayed on [player_name]'s back like a brand. Hint deepening. Broken men should not be this hot. He wore broken like cologne she wanted to lick off his throat between soundbites. "She releases. I corroborate. Cho's *pending* stays *pending*."

[player_name] stepped to the mic edge with Jake's heat still ghosting her spine. She blew Renny's chain into Harborwick's weather—Warehouse C marks, truck plates, clerk beyond initials, Owen's late nights, the pier night finally outdoors—and every warehouse mark felt like a stroke behind her navel because Jake watched her mouth shape her sister's certainty the way a man watches a body he has not opened yet. "I am not naming unidentified remains as hers," she said, voice ruined and holding. "Lab pending. Hope allowed. Dread honest."

Jake read chain-of-custody like a vow, voice rough enough [player_name] felt it in her clit. Questions surged—Owen, clerk, whether the detective was fucking the witness. Jake shut the corpse-question down with a look that made her nipples tighten against wet cotton. "Charm probability is not an ID. Ask Cho." His free hand found the inside of her wrist behind the USB—pulse, claim, filthy metronome—and squeezed once. Reciprocal hunger denied for cameras. The hard line of his restraint was its own stroke.

A reporter shoved closer. "Leading Renny's story—or hiding behind the detective while the city eats the noise?" [player_name] tasted copper and Jake's nearness and answered with thighs pressed slick under rain-dark fabric. "I kept quiet seven years. Leading her public story means I stay in the weather until her name is held without the old lie. Enduring the open secret with him means we refuse to let noise invent a funeral while Cho still says pending. Both outdoor. Neither silence." Jake's thumb stroked once behind her wrist-bone as if honesty were a clit he was learning. She almost made a sound the mics must not own.

Ellison stepped close after the first wave. Soft for only them: "You blew the leash. Two doors—lead Renny's reckoning yourself, or endure the open secret with Akers while Harborwick screams. IA shadow deepens. Solis-shaped questions come back. Public heroes make pretty targets."

Jake's mouth almost touched [player_name]'s temple. "She chooses. I stay." Grey-green on her lips. Mid-thirties hunger banked for mid-twenties shaking. "I am hard from watching you strip truths for a city that does not deserve your voice, and I am choosing—right now—to keep my cock out of the live shot. Lead the reckoning and I will stand behind every mic wanting to put my mouth on the pulse in your throat every time you say Warehouse C for Renny. Endure the open secret with me and I will hold you upright while Harborwick eats every mark—and afterward I will take you somewhere without lenses and finish what these floodlights cannot. Either way Cho still says *pending*. Either way I do not fuck you into christening bone."

[player_name] pressed her thighs harder. Slick fabric dragged her clit like a filthy secret the rain must not catalogue. A whimper almost escaped. She gripped the USB until plastic creaked and felt Jake's cracked knuckles cover hers—heat, calluses, partnership that was also a claim. Attraction was not garnish on the storm; the storm was the stage and want was the underplot humming in her cunt while grief stayed holy enough that she would not eroticize the river even while she imagined Jake's mouth between her legs after the last camera left.

A camera flash stuttered at the canopy edge; Jake turned his body into a shield and used the turn to drag his knuckles once—filthy, deliberate—along the front of her rain-dark skirt where she was soaked, a secret stroke the floodlights must not own. [player_name]'s breath broke. He did not smile for lenses. He spoke into her hair: "Sister's reckoning means I watch you lead and go home hard enough to hurt. Open secret means I hold you through the scream and spend it into you until noise becomes bedding. Either way my mouth learns your pulse after. Either way Renny's chain stays outdoor without becoming corpse theater." The almost-kiss hovered and died for politics; the denied kiss was somehow hotter than contact. Her nipples ached against wet cotton. Her cunt ached unused. Trust and lust shared the canopy like co-counsel who refused to leave.



Foghorn rolled, low enough to feel in her clit and her bones. Chain-link rattled. Ellison's tablet chimed. A reporter shouted Renny's name like a verdict. Jake angled his body to block one more lens from [player_name]'s throat, thigh brushing hers deliberately now—denim heat, denied fuck, reciprocal ache—and whispered, "Verb. Sister's reckoning you lead—or open secret we endure. I will still want you after. Want is not the vote. The vote is whether Renny's certainty gets your public spine or our shared noise while hope stays alive under pending. Tell me before I forget these are floodlights and remember I can smell how ready you are under this rain."

[player_name]'s pulse hammered in her wrist under his thumb and lower, unused and honest. Hope still had a throat. Dread still had teeth. Charm upstairs still only *like*. Remains still unnamed. Solis ash stirred under IA without dumping every sealed hallway page. Choosing to lead meant sister as public reckoning, Jake present and hard and sworn not to invent corpses, her body throbbing through every outdoor sentence. Choosing open-secret endurance meant city noise as shared bed-climate, want cooled into a bruise she would press later—wall, rain-dark sheets, a detective who would not invent a funeral because paper was dramatic.

She pressed the USB against her breasts and felt her nipples peak against plastic and Jake's gaze catch it—noticed, banked, promised. "If I lead," she whispered, "I will need you in every green room like a filthy sacrament."

"You will have me," Jake said. "Not on live shot. In the hallway. In the car. In whatever room still smells like rain when you are done saying Renny's chain outdoors. If you endure with me, you will have me against a wall with your skirt around your hips the second the last live feed dies—because I am done pretending partnership does not include the way you soak for competence and the way I get hard for honesty under floodlights." His laugh was velvet-blade and wrecked. "Ellison can put IA on my badge. She cannot put IA on how wet you are. That is mine to catalogue and yours to spend on a verb."

He used a reshuffle of cameras like cover and pressed her into the canopy's deeper shadow—still public enough for Ellison's politics, private enough that his thigh slotted between hers and ground once, filthy and deliberate, cock hard through charcoal against her soaked heat. "Lead the reckoning," he breathed against her mouth without quite kissing where lenses could feast, "and I will eat you out in every green room until your public spine tastes like my name. Endure the open secret and I will fuck you through the city's scream until noise becomes a metronome for how many times I can make you come without inventing a funeral for drama." She rocked on his thigh once—ruined, rain-dark, mid-twenties cunt aching unused for the longer catalog—and he groaned like restraint was a wound. Solis ash stirred in his voice when he added, "I ordered a hallway once. I will not order your ending. Verb. Please." The please cracked the armor and went straight between her legs.

[player_name] nodded once, ruined. Foghorn answered. Hope and dread still shared the doorway of her pulse. Remains still unnamed. Jake's thumb found her pulse again and counted like he was timing an orgasm he refused to give her on pier concrete. "Choose," he said. "Before I kiss you where they can see and make Ellison's shadow into a headline we did not earn."`,
  choices: [
    { id: "scene10e", text: "Lead Renny's public story — sister's reckoning", textHot: "Lead Renny's public story — sister's reckoning" },
    { id: "scene10h", text: "Endure the open secret with Jake", textHot: "Endure the open secret with Jake" }
  ]
};
