export default {
  id: "scene6p",
  layer: 6,
  title: "She walks — Jake has to chase both case and her",
  text: `She walked—and Jake Akers had to chase both the case and her.

Harborwick fog took [player_name] like a second skin. Pier boards wet under her boots. Chain-link rattled somewhere in the dark. Fog horns groaned across the water as if the city were clearing its throat to say her sister's name and then thought better of it. She had left the trailer lean, or the precinct politics, or both—left the shape of Jake's late smile when it went from charm to instrument—and the leaving tasted like copper and necessary mercy and a cowardice she refused to name yet.

Renny had been sixteen. Festival lights. A bracelet missing one charm. Unidentified remains still waited in Dr. Lila Cho's patience upriver; the silver charm in evidence still only *like* Renny's missing piece. Hope and dread shared the fog with a third guest: the knowledge that walking away from Jake's hardness did not retire the hunt. It relocated the pressure onto her spine and his pride.

He found her at the edge of the pier lot where sodium light smeared the rain into gold bruises. Mid-thirties. Dark stubble silvered wet. Scar nick catching streetlight. Whitened knuckles flexed once at his sides as if he were arguing with the urge to grab. He did not grab. He matched her pace when she started walking again, notebook a dark rectangle in his jacket, badge a weight she could feel without seeing.

"You walked," Jake said, voice low. "I am angry. I am also the man who knows soft nets fail and still hated watching you look at me like I was about to become a clean jacket with a wrist-grab." The late smile flickered off, then on wrong. "Marta will remember nothing useful if the lean was the last weather she felt. Ellison will smell romance and obstruction if politics was the room you fled. Either way I am chasing you and Renny's scrap in the same breath. That is the cost. The gain is you still looking at me like I might be worth the chase."

[player_name] kept moving toward the warehouse district's silhouette, pier salt on her tongue. Festival ghosts lived in the wet boards. Owen still unnamed on any official page—her kept pier sighting still pressing her tongue while the detective chased her through fog she had chosen. "If leaning was the only way to hear Renny's last argument, then the system that failed her is wearing your mouth. If politics was the only way to keep your badge, then the machine is wearing mine. I needed air that did not taste like warrants."

Jake flinched—small, real. Nina Solis lived in the flinch as hint only: early push, kid in a hallway, sealed file, charm for a face afterward. He did not dump the hallway. Layer 6 got ash-smell, not full confession. "That landed," he admitted. "Walking out does not retire the case. It relocates the pressure onto us. I will still hunt the red door. I will still want the badge spit half-heard. I will still want you. Do not mistake my self-awareness for softness. I am not nice. I am Akers. I dream raid noise when soft fails—and soft just failed into fog."

They reached the chain-link that bordered a cold-storage row Marta had pointed toward without quite swearing. Generator hum lived somewhere beyond rust and rain. A red door waited in rumor—fourteen or forty-one, scrape unresolved. Jake stopped. [player_name] stopped. Rain stitched the space between their mouths like unfinished sentences.

"Ellison will ask why the interview ended or why the briefing chair went empty," Jake said. "I will say the sister left. She will hear liability. She will not be wrong about the want." His hazel gaze held hers—tired, hungry, dangerous. "You get two verbs now that the walk is real. Reunite with me at the pier festival—anniversary ghosts, posters, crowds, Renny's night returning in public where hope and dread share the boards and I can finish what we keep interrupting without crushing another witness. Or circle back to Renny's locked box—her room, her hoodie, the metal she trusted under a bed—open what she kept while I chase the warehouse scrap without you as soft shield or soft target."

Want lived under the procedural dread—dangerous, unfinished, the pull of a man who could chase her through fog and still offer her a locked-box hour alone. [player_name] almost laughed. Almost cried. Trust under interrogation lights had become trust under rain. "Reuniting at the festival means choosing the place she vanished."

"Circling to the box means choosing the place she left you instructions," Jake answered. "Both hurt. Both move the case. Both leave me chasing something—either your body in a crowd or the geography alone while you dig through purple leather and cream envelopes." He scrubbed rain from his face. Whitened knuckles pale. "Cho will not name the remains because you walked into fog. Charm stays *like*. Owen stays your private weather until you put him on a page. Walking did not free you from the kept secret. It only freed you from watching me become weather you could not love."

[player_name] thought of Renny's hoodie folded in a drawer. Thought of festival music lying about safety seven years ago. Thought of Jake's cracked knuckles and the way he flinched when someone said *partner* in the bullpen. Thought of the pier sighting she still had not put on paper—Owen near the water with someone who was not supposed to be there—and how walking had not made that truth lighter. Captain Mara Ellison's distrust lived somewhere behind the rain like a weather system with a badge. Internal ash stirred only as rumor. sealed stayed sealed.

"If I reunite at the pier festival—" she started.

"Then I meet you under sodium and posters like a man who can still be soft in public," Jake said. "Hand on your back. Eyes on the crowd. Mouth pretending this is memorial instead of unfinished kissing." His voice dropped. "If you circle back to the locked box, I give you the key-hour alone or with me—your call—and I take the warehouse lead while you decide what Renny's paper does to hope. Either way I chase. Either way you walked first. Hurt to leave either verb. Good. Means the fog did not make you numb."

Rain thickened. Another fog horn spoke across Harborwick like a warning that had learned their names. Warehouse lights smeared in the wet distance. Jake stepped closer without touching, brutal charm banked, mid-want humming under mid-war. Notebook spine cracked in his jacket pocket like a small black altar. "I will not pretend I do not want the festival reunion. Wanting that makes me selfish. Offering the box path anyway makes me slightly less. Slightly."

[player_name] tasted salt and copper and the metallic bright of a choice that would not let her pretend walking was the end. Remains unnamed. Sister still missing in the only way that mattered until science or a confession said otherwise. Jake Akers waiting like a sealed file humming under charm he could not currently afford—chasing case and woman both, sealed ash still sealed, Ellison's distrust a distant gavel practicing.

"Reunite at the pier festival," he murmured, almost a plea under the grit. "Or circle back to Renny's locked box. The walk is done enough to hurt. The hook is which hunger you feed while I am still angry enough to mean both and still soft enough not to grab."

His phone buzzed in his pocket—precinct, Ellison, Internal, some machine that hated fog. He ignored it. He watched [player_name] instead, mid-thirties danger soft for a mid-twenties sister of the missing who had chosen air over lean and now had to choose again.

[player_name] stood between pier fog and warehouse dark, Layer 6's unfinished want steaming off both of them. The romance was whether she could love a badge after the system failed Renny—and whether he could love the woman who walked when his mouth went hard—and whether Renny's finger still pointed east through locked metal or through anniversary crowds.

Rain needled the chain-link. Somewhere a Harbor Authority truck idled and moved on, leaving diesel ghost. [player_name] thought of Marta's funnel-cake trailer and the scrap that had cost a lean and a walk: red door east, tall office muscle, numbers spit like *you people*. Living geography. Not a corpse named. Not yet. Jake's notebook held that ink; her ribs held Renny's absence; the fog held both of them like a third interrogation room without fluorescents.

"I kept something," she said carefully, not naming Owen, not dumping the pier night whole. "Walking does not make me ready to put it on paper. Festival or box—neither is a confession booth."

"I know," Jake said. "I feel the lie the way I feel rain. I will not bait it out of a reunion or a lockbox hour. Softest hard I can offer after you fled my teeth." He almost smiled. Failed. "You walked because I went instrument. Fair. Now instrument learns to wait while still hunting. That is new for me. His old partner would not recognize it. Ellison will not trust it. You get to test it."

"Pick the verb," Jake said. "Festival or box. I will chase either. I will not chase hesitation while a red door listens and unidentified bones wait and your kept secret presses your tongue. Choose, [player_name]. You walked. Now decide where the walking leads—back to the boards where she vanished, or back to the box where she tried to tell you what Harborwick's throat looked like before the fog took her."`,
  textHot: `She walked—and Jake Akers had to chase both the case and her, hard and wet and furious in Harborwick fog.

[player_name] left the lean or the politics or both—left the shape of his late smile when charm became instrument—and the leaving soaked her jeans with rain and the ridiculous unfinished want that walking could not kill. Pulse in her throat. Pulse lower. Renny pointed east behind her eyes—sixteen, bracelet flashing, clean jacket on a wrist—while unidentified remains stayed unnamed upriver and a charm stayed only *like*. Hope and dread shared the fog with her cunt's stupid loyalty to a detective she had just fled.

He found her at the pier lot's edge, mid-thirties danger silvered wet, scar nick catching sodium, whitened knuckles arguing with the urge to grab. He did not grab. He boxed her against chain-link when she tried to pass, mouth at her ear, thigh shoving between hers until she gasped at the thick pressure against her clit through denim. Rain sheeted off the fence. Generator hum lived somewhere beyond. "You walked," Jake growled. "I am angry. I am also hard. Do not confuse the two—or do. Both are true." His cock pressed her hip through wet trousers, blunt and insistent. "Marta blanks if the lean was the last weather. Ellison smells if politics was the room you fled. I chase you and Renny's scrap in the same breath. Soft failed into fog. Now fog gets honest."

"Jake—air—"

"Air that does not taste like warrants," he finished for her, hand already under her coat, under her shirt, palm on bare waist, thumb stroking the underside of her breast until her nipple peaked traitorously against cold wet cotton. "I heard you. I flinched. Solis—hints only, sealed file, kid in a hallway, charm for a face. I will not dump the ash while I finger you against fence." He shoved his hand into her jeans under soaked cotton; she was dripping from rain and fear and fury and him. Two fingers slid into slick heat without preamble; she bit his shoulder through his jacket to stay quiet for the pier path. "I will hunt the red door. I will want the badge spit. I will want you. Walking relocated the pressure onto your cunt and my pride. Feel it."

[player_name] rocked on his hand, forehead to wet collar, Renny's absence and Owen's unnamed pier night braided into heat that felt like loyalty's filthy twin. His thumb found her clit in tight circles. A third finger stretched her. Chain-link rattled at her shoulder blades. "If I reunite—"

"Pier festival," Jake snarled, pumping slow, filthy, precise. "Posters. Crowds. My hand on your back like soft partnership—and after I put you against a piling and fuck the walk out of you until fog knows your moan, until anniversary ghosts share the wet with how hard I get for a woman who fled my lean and still soaks my hand." He freed his cock enough to smear the head through her folds without entering—hot, blunt, cruel, painting her clit until she jerked. "Or circle back to Renny's locked box—her room, her hoodie, cream envelopes—while I take the warehouse alone and come back smelling like fish-rot and unfinished want to find you shaking over paper. After, I fuck you on a floor that is not hers if you ask—grief and sex can share oxygen. Gore does not get a vote. Cho's bones stay unnamed. Charm stays *like*."

She clenched around nothing when he pulled his fingers free and rubbed her with the wet head of his cock instead—shallow, maddening, never fully inside. Discipline as filthy as any thrust. "Owen stays off your paper," Jake muttered against her mouth. "Walking did not free your secret. Public storms dig. Locked boxes dig quieter. Pick while you drip on Harborwick's fence for a detective with ash under his badge."

[player_name] came quiet against the chain-link, shaking, fist in his jacket, while fog horns groaned and Jake eased back without chasing his own finish—cock jumping against her thigh, restraint a third wound. He tucked himself away with shaking hands, fastened her jeans with mock courtesy that did not reach his eyes, and pressed his forehead to hers. Pulse hammered. Rain thickened. Want unfinished and loud.

"Reunite at the pier festival," he whispered, voice wrecked. "Or circle back to Renny's locked box. You walked. I chase. Both verbs hurt. Good." His late smile cut wrong—weapon and wound. "I dream raid noise when soft fails. Soft failed. You get festival soft in public or box quiet in private. I get to chase either with my cock still aching and my notebook still cracked. Cho will not name remains for your orgasm against this fence. Ellison will not forgive fog. sealed stays sealed. Decide."

He walked her deeper into the warehouse fog before the pier cameras could invent a story, boxed her again between a rusted gate and his unmarked car, and put her hand on his cock through his pants. "Feel what the walk did," Jake muttered. "You left and I got harder for the leaving. That should scare you. It scares me."

She stroked him, slow, feeling thick heat jump against her palm. He groaned and shoved his hand back into her jeans, fucking her with two fingers in time with the rain on the roof of the car. "Festival means I meet you under sodium and posters and then take you somewhere the crowd cannot see until you come with my name in your teeth. Box means you dig Renny's metal while I chase fourteen-or-forty-one alone—and when I find you after, I put you on the hood in this fog and finish what the fence started." His thumb circled her clit. "Both leave you shaking. Both move the case. Both leave me chasing case and woman until one of us breaks open."

[player_name] whimpered, hips rolling, conscience loud about Owen still off paper and bones still unnamed. Jake curled his fingers deep and kissed her hard enough to bruise, then eased his hand free and painted her lower lip once before sucking his knuckles clean. "Verb. Now. Reunite at the pier festival. Or circle back to Renny's locked box. Ellison's machine is already inventing why the sister fled. Give me a better story with your mouth."

She stood between pier fog and warehouse dark, wet jeans, remains unnamed, charm probable, sister still a pointed finger—and the choice sitting between them like unfinished fucking: anniversary crowds where hope and dread shared the boards, or the locked box that might finally speak while Jake chased red doors without her as soft shield.

Rain needled the hood. Jake scrubbed a hand over his face, then cupped her jaw with cracked knuckles that still smelled like her. "I kept a badge by letting a partner take a fall I should have shared—hints only. You kept a pier night off paper. We are both fluent in expensive quiet. Walking does not make either of us clean. It makes us honest about how much quiet costs." His thumb brushed her lower lip where he had painted her. "Festival soft or box quiet. My cock votes both. Your mouth has to pick one before Ellison invents a third option called *liability removed*."

[player_name] tasted salt and herself and unfinished justice. Warehouse silhouettes lived behind her eyelids. Renny's hoodie waited in a drawer. The red door waited in rumor. Jake's pulse hammered under her palm where she still touched his wrist. Trust under rain. Want under murder-plot pressure that refused to become gore-porn—bodies yes, corpses no, heat advancing the chase instead of cosplaying the kill.

His phone buzzed—precinct weather. He ignored it. He watched her mouth, mid-want, mid-war, mid-thirties danger soft for the woman who walked. He lifted her onto the hood of the unmarked anyway—metal cold through wet jeans—and stepped between her knees, grinding slow while his mouth found her throat. "One more honesty before the verb," Jake muttered. "If you reunite at the festival I will be soft in the crowd and filth in the first alley we find. If you circle to the box I will leave you the key-hour and still come back hard enough to make paper shake. Either way Renny stays a pointed finger. Either way Cho's tray stays unnamed. Either way I chase." His hand cupped her through denim, one firm press against soaked seam, and she arched. "You walked. I followed. That is the romance under the murder. Not gore. Not clean-cut. Teeth and want and a sister still missing."

"Pick, [player_name]," Jake said. "Festival or box. I am still hard enough to mean both. Hurt to leave either. You walked first. Now decide where the walking leads while Harborwick holds its breath and unidentified bones wait and I refuse to grab—only chase. Festival crowds or locked metal. Renny's finger still points east through both. Pick before the fog makes the choice for us and I have to invent a hard warrant out of raw want and cold harbor rain and unfinished hunger alone."`,
  choices: [
    { id: "scene7p", text: "Reunite at the pier festival", textHot: "Reunite at the pier festival" },
    { id: "scene7a", text: "Circle back to Renny's locked box", textHot: "Circle back to Renny's locked box" }
  ]
};
