export default {
  id: "scene6c",
  layer: 6,
  title: "Off-record night: intimacy + case map on the floor",
  text: `Off-record meant the badge stayed in William Akers's pocket and the case still climbed the stairs with him into [player_name]'s apartment like a third guest who refused to take off its shoes. Harborwick rain wrote soft code on warehouse glass across the alley. Pier salt ghosted through the cracked kitchen window and mixed with the burnt leftover of precinct coffee he had carried up in a paper cup that had already gone lukewarm. Yellow tape lived only in memory tonight—festival pier, seven years ago, a silhouette she had refused to put in her statement—but the ghost of it still marked the air between their bodies whenever either of them said *chain* or *Owen* or *unidentified*.

Will knelt on her living-room carpet and emptied his cracked notebook into a constellation: photocopied pier maps, Cho's careful pending language printed and underlined, festival vendor scraps, a timeline that still refused to baptize the upriver remains with Renny's name. Mid-thirties, scar cutting his left eyebrow, charcoal shirt open at the throat where Harborwick damp had found him. Brutal charm banked low—velvet over a blade, sheathed because this was not Ellison's fluorescent theater and not a raid hallway he would not narrate. Grey-green eyes tracked [player_name] as she dropped to her knees opposite him and spread Renny's teenage Xs beside his professional ones until the floor looked like a second bed made of paper and almost-trust.

"Ellison does not get this layout," Will said. Voice quiet enough that the rain almost ate it. "Not yet. Off-record means we build the picture before she decides which pieces become clearance toys. Cho still says *unidentified*. Age range that could fit. Charm that could match. Lab ID unfinished. We do not invent a sister because the floor looks dramatic."

[player_name]'s mid-twenties hands smoothed a crease in the pier map. Renny had been a teenager when she vanished—seven years of absence folded into cotton still waiting in a drawer down the hall, into a silver bracelet missing one charm, into the kept detail about Owen Vale near the festival pier that she had finally begun to spend. Hope and dread shared the carpet like co-counsel who hated each other and refused to leave. The remains were not Renny until science said so. Rumor had already tried to bury her. Kneeling here with Will felt like the opposite of burial: an insistence that breath might still exist somewhere Harborwick refused to look, and that a chain of warehouses and clerk initials might explain silence without requiring a corpse.

"Then we stay off-record until dawn," she said. "Map it. Name the warehouses Renny marked. Match Owen's late nights against the bleach-clean alibi he carved into family dinners. If Cho drips harder, we recalibrate. If Ellison smells the sandbag—"

"She will smell something," Will said. A flicker of velvet-blade smile, gone before it could become a joke about captains and perfume. "Sandbagging or partnership. Same scent to her until the science hardens. I am choosing partnership tonight. That is not free. It costs me a soft spot where my badge should be hard, and it costs you the comfort of pretending I am only a detective in your living room."

Attraction had been climbing the stairs with them since the car—since off-record honesty after Ellison, since the decision to keep one card warm between them instead of feeding every scrap to fluorescent metrics. Close enough to burn: mid-thirties to mid-twenties, badge-country and sister-country sharing carpet fiber. Far enough that trust still felt like crossing a border without papers. [player_name] tasted lukewarm coffee and rain and the sharper taste of almost. When Will leaned to align a photograph of the waterfront warehouses, soap and salt and scrubbed-dark past filled the space between their shoulders. His knuckle brushed her wrist. Heat jumped. Neither pretended it was only paper static.

Nina Solis lived in the small flinch he aborted when [player_name]'s phone buzzed and the screen showed a precinct prefix—partner-shaped silence, sealed IA file, a hallway chaos he wore under brutal charm like armor that sometimes slipped. He silenced nothing on her phone; she did. He touched his ribs once, absently, as if checking a bruise that never yellowed, then forced his attention back to Renny's pencil marks. Teeth showing. He did not dump the raid into her living room. Dark past hummed under the off-record quiet like a second pulse she wanted to press her ear against and also feared hearing whole.

"Here," [player_name] said, pointing to a clerk's initials Renny had scrawled like a dare. "She was tracking harbor traffic someone did not want tracked. Owen's desperation sits next to it in her script—money, debt, late nights that smell like someone else's problem becoming family weather. The upriver find could be the chain eating its witnesses. It could also be rumor wearing my sister's bracelet size. I will not christen bone because the map is tidy."

"Good," Will said. Soft. Dangerous in a different key than Ellison. "Tidy gets people buried early. Messy keeps hope's throat open." His gaze lifted from the paper to her mouth, then to her eyes, then deliberately back to the map as if professionalism were a door he was holding shut with both hands. "I did not come upstairs only for the map. You know that. Off-record night has two rooms in it. One is this floor. The other is whatever we do with the air between us when the timeline stops needing our hands."

Rain thickened on the warehouse glass. Chain-link rattled in the alley like loose teeth. [player_name] looked at the constellation they had built: warehouse marks, Owen's cracks, Cho's pending language, the charm probability that still only said *like*. She looked at Will's scarred brow, at the sleep-deprived set of his shoulders, at the way his cracked knuckles rested on his own thigh as if to keep from reaching. Want was a stupid animal to bring into a room built of absence, and it came anyway—warm, insistent, braided with grief so tightly that separating them felt like another kind of lie.

She closed the distance first. Not a collapse. A choice. Her mouth found his with the careful violence of someone who had spent seven years choosing silence and was done choosing only that. Will made a sound low in his throat—surprise and hunger and the particular relief of a man who had been holding a door shut and was finally allowed to open it. His hand found the back of her neck, calluses and heat, and the kiss deepened until the case map rustled under their knees and a photocopied pier edge crumpled under her palm. He tasted like coffee and rain and scrubbed-dark past. She tasted like fear turning into something that could also be trust.

They did not make it to the bedroom. Intimacy happened on the floor beside the timeline—clothes half-shifted, mouths learning, hands careful of the papers even while bodies stopped being careful. Will's shirt opened under her fingers. [player_name]'s blouse loosened under his. Skin to skin where damp Harborwick air had already made them honest. He kissed the hinge of her jaw, the pulse under her ear, the place where her throat worked when she said Renny's name like a prayer that refused to become an epitaph. She mapped the scar through his eyebrow with her thumb and felt him shiver as if the scar were still a live wire. When his palm settled at her waist, under cotton, the heat of it was a second confession: off-record meant more than withheld statements. It meant the badge could wait while two people who should not want each other this hard chose to want each other anyway.

They stopped short of losing the map entirely—stopped at the edge where case and body still shared the same carpet, where finishing would have turned grief into something they might not forgive in fluorescent light. Breath ragged. Foreheads touching. Will's laugh was quiet and wrecked, brutal charm scraped soft. "That," he said against her mouth, "is going to fuck with my judgment in the morning. Worth it."

[player_name] pressed her forehead harder to his. Renny's fate stayed contested: not named, not buried, not safe. The charm still only *like*. Cho's language still ruled the remains. Owen still sat on the map like a bruise. "We keep building," she whispered. "Chain first. Science second. Ellison when we have something she cannot sand into clearance."

Will's phone buzzed against his hip—ignored once, twice—then the screen lit with Dr. Lila Cho's name in the dim. He did not answer immediately. His grey-green eyes held [player_name]'s, asking without asking. Outside, pier salt thickened. The radiator knocked like a distant interview-room clock that had followed them home. The map rustled when [player_name] shifted, thigh still warm against his, blouse still open at the collar, mouth still tasting like unfinished honesty.

"Two doors from the floor," Will said softly. He tucked a strand of hair behind her ear with a gentleness that felt more dangerous than his jokes. "We stay and take Cho's call—second-victim pattern or whatever drip she has that widens the case without naming Renny yet—and we let science walk into the intimacy we just built. Or we let want break whatever case-only streak we try to put back on after this—stop pretending we can brief like strangers while your mouth still looks kissed and my hands still know your waist—and we finish what the carpet started before dawn makes us detectives again. One path keeps the night hinged to forensics. The other keeps it hinged to us. Both leave the remains unnamed. Both leave Owen's name still sharp on the paper. Neither is free."

[player_name] looked at Cho's name glowing, at the warehouse Xs, at Will's scarred brow and the open collar of his shirt and the way his pulse jumped in his throat when she breathed. Hope still had a throat. Dread still had teeth. Want had a new address on her living-room floor. Choosing Cho meant letting a second-victim pattern—or whatever almost-ID the ME was ready to speak—walk into the warmth they had made, forcing the chain wider while their bodies still remembered each other. Choosing want meant admitting the case-only mask would not hold past another kiss, that mid-briefing restraint was already a fiction, that off-record night could still deepen before Harborwick's rain stopped rewriting the warehouse glass.

Will did not rush the phone. He stayed on the map with his hand warm at her waist, pulse jumping under the open collar of his shirt, brutal charm banked into patience that felt like a held breath against her mouth. The sealed past smoked under his silence without another unpacking; Ellison's distrust was tomorrow's weather. [player_name] tasted copper from the kiss, coffee, paper dust from the Xs. Choosing Cho meant letting a second-victim almost walk into the warmth they had made while her body still remembered his. Choosing want meant admitting the case-only mask was already fiction—that mid-briefing restraint would not survive another minute on this carpet while unidentified remains waited upriver and a sister's fate stayed contested between a kiss and a call.`,
  textHot: `Off-record meant William Akers's badge stayed in his pocket and his cock was already half-interested by the time [player_name] unlocked her apartment, which was a filthy problem neither of them named in the stairwell. Harborwick rain wrote wet code on warehouse glass across the alley. Pier salt ghosted through the kitchen window and mixed with lukewarm precinct coffee and the low electric musk of two people who had been starving for this since the car. Yellow tape lived only in memory—festival pier, Owen's silhouette, seven years of a kept detail—but the ghost of it made every brush of Will's shoulder against hers feel like crossing a line into a crime scene made of want.

He knelt on her carpet and emptied the cracked notebook into a constellation: pier maps, Cho's *unidentified* / *pending* / *consistent with* language, vendor scraps, timelines that still refused to baptize the upriver remains as Renny. Mid-thirties, scar through his brow, charcoal shirt damp at the spine. Brutal charm banked—then not banked at all when [player_name] dropped opposite him and her knees opened just enough that his gaze dropped, caught, and dragged back up like a man hauling a chain. Grey-green eyes dark. Mouth soft. "Ellison does not get this layout," he said, voice rough. "Cho still has no hard ID. We do not invent your sister because the floor looks like a bed. We also do not pretend I came upstairs only for paper."

[player_name]'s mid-twenties pulse hammered in her clit as much as her throat. Hope and dread shared her body with a third animal—want—while she spread Renny's teenage Xs beside his professional ones until warehouse marks and clerk initials and Owen's late-night cracks made a second mattress of evidence. When Will leaned to align a photo, soap and salt and scrubbed-dark past filled her nose; his knuckle brushed her wrist and electricity shot straight between her thighs until damp fabric clung to her like a confession. She was already slick. Off-record night had a scent, and it was her.

Nina Solis lived in the flinch he aborted toward his ribs when a precinct buzz lit her phone—he did not dump the raid onto her carpet. The wound showing made [player_name]'s nipples tighten until her blouse scraped; broken men should not be this hot, and Will wore broken like cologne she wanted to lick off his pulse point. "Sandbagging or partnership," he murmured, velvet-blade low enough to stroke the inside of her wrists without touch. "Same scent to Ellison. I am choosing partnership. That means the map. It also means I am done pretending your mouth is not a problem my badge cannot solve."

She closed the distance. Kiss first—careful violence, seven years of silence cracking. Will groaned into her mouth like a man released from a warrant he had been serving on himself. His hand found the back of her neck, then her waist under cotton, then the underside of her breast through her bra until she arched and a photocopied pier edge crumpled under her palm. Chain-link rattled in the alley; the sound vibrated in her ribs and somehow in her clit, absurd and perfect. He tasted like coffee and rain and the scrubbed-dark past she wanted to fuck the silence out of. She pushed his shirt open and dragged her mouth down the column of his throat, felt his pulse jump against her tongue, felt the scar-adjacent tension in his jaw when she bit lightly. He pushed her blouse loose. Skin to skin on the case map: her thigh over his lap, his hard cock pressing through trousers against the wet heat of her through two layers of fabric, both of them grinding once—twice—before he swore softly and tried to remember which paper was Cho's language and which was Renny's dare.

"Floor," he managed against her throat, kissing the pulse there until she whimpered, then lower, mouth open on the upper slope of her breast where the bra had slipped. "We keep the chain. We also—" His palm slid under her waistband, found her soaked, and both of them went still as held breath. The heat of his fingers made her hips jerk; a sound escaped her that Ellison must never hear. "[player_name]." Her name like a filthy prayer. Two fingers stroked through her slick without entering, a question asked in friction, spreading her open just enough that cool apartment air kissed where she was wettest. "Tell me this is off-record for the right reasons. Tell me you are not fucking me to forget bone. I will not be a burial. I will be a man who wants you wet on a map while your sister's fate stays contested—hope open, dread open, cunt open—if that is what you are offering. Say it while you are dripping on my hand so I know the words are not a performance."

"Not a burial," she gasped, hips tipping into his hand, thighs shaking. "A choice. Science unfinished. Remains unnamed. You—now. Will—" His name broke on a moan when he finally gave her his fingers, slow and deep enough that her cunt clenched and paper rustled under her knees. Thumb on her clit in a filthy circle that matched the rain on warehouse glass. Mouth on her breast through the half-open bra, then skin, tongue, teeth careful. The notebook spine cracked somewhere under his knee—habit, armor, a small prayer to order that order had already abandoned. She rode his hand without shame, grief and want braided so tight she could not tell which made her eyes wet. She came hard and quiet against his fingers with pier salt in her nose and paper dust on her lip and William Akers's scarred brow pressed to her sternum like he was listening to her heart for lies. Aftershocks fluttered. He did not fuck her fully—not yet—held himself back with a discipline that made her furious and grateful, cock still hard against her hip, trousers damp where she had ground against him, while he kissed her through the shaking and wiped his fingers on his own shirt like evidence he refused to bag and refused to stop smelling.

Breath ragged. Foreheads touching. Map ruined in places and sacred in others—Owen's name smudged under her palm print, a warehouse X curled where her knee had pinned it, Cho's pending language still readable if either of them could still read. "That," Will said, wrecked-laugh soft against her mouth, "is going to destroy my morning judgment. Worth every soft spot. Worth every look Ellison will give me when I walk in smelling like your living room and lying about how much of the night was paper."

His phone lit with Dr. Lila Cho's name. He did not answer. [player_name] could still feel her own wetness cooling on her thighs; could see the hard line of him unanswered; could taste the unfinished sex that was still almost-more. Rain rewrote the warehouse glass. The radiator knocked like an interview-room clock that had followed them home to watch.

"Two doors from the floor," he said. Still not answering Cho. Hand still warm at her waist under open cotton. "We stay and take the call—second-victim pattern, drip that widens the chain without naming Renny—and we let science walk into the intimacy while my cock is still aching and your cunt is still fluttering from my fingers. Or we let want break the case-only streak we have not even put back on yet—stop pretending we can brief like strangers while you smell like come-close and my mouth still knows your nipple—and we finish what the carpet started before dawn makes me a detective who has to look Ellison in the eye. One path hinges the night to forensics with your taste still on my hand. The other hinges it to us: you on your back beside the clerk initials, me inside you until the seven-year shake leaves your voice, remains still unnamed, Owen still sharp on the paper, neither of us free."

She looked at Cho's glow, at the wet shine on Will's knuckles, at the way his pulse jumped when she shifted and her thigh brushed his cock. Hope still had a throat. Dread still had teeth. Want had soaked the map. Choosing Cho meant opening the phone with her body still open, letting a second-victim almost walk into afterglow. Choosing want meant admitting case-only was already a joke, that mid-briefing restraint would shatter if they stayed on this carpet another minute, that off-record could still mean his cock and her name moaned into Harborwick rain.

Will's attention returned to her body like a second set of fingers she could not see—pressure on her clit without contact, worse now that she knew what his hands could do. Blade flat. Edge available. The sealed past stayed unnamed in his ribs; Renny's absence still occupied the hallway. [player_name] shifted and her thigh brushed the hard line of his cock through jeans; both of them hissed. Choosing Cho meant opening the phone with her cunt still aching open, letting a second-victim almost walk into afterglow while his knuckles still shone wet from her. Choosing want meant admitting case-only was already a joke—that if they stayed on this carpet another minute he would fuck the briefing out of existence while unidentified remains waited upriver and a sister's fate stayed contested in the damp, filthy, hopeful air between a kiss and a call.`,
  choices: [
    { id: "scene7c", text: "Stay for Cho's second-victim call", textHot: "Stay for Cho's second-victim call" },
    { id: "scene7d", text: "Let want break the case-only streak", textHot: "Let want break the case-only streak" }
  ]
};
