export default {
  id: "scene5b",
  layer: 5,
  title: "Will's car: off-record honesty after Ellison",
  text: `William Akers's unmarked car smelled like rain on vinyl, gun oil, and the burnt-coffee ghost that clung to every Harborwick detective who lived too long on precinct sludge. The lot behind the station was a slick black mirror. Fog pressed the chain-link. A foghorn rolled up from the pier district as if the river itself were clearing its throat to speak a name it did not have. [player_name] sat in the passenger seat with her hands clenched in her lap. Mid-twenties. Pulse loud. The unfinished sentence from the interview room still lived in her mouth like a second tongue.

Will shut his door softer than Ellison would have believed him capable of. Mid-thirties, dark hair rain-darkened, scar cutting his left eyebrow, jaw set in the particular way that meant the brutal charm was offline and the wound was driving. He did not start the engine. He put both hands on the wheel and stared at the wet windshield as if it might confess first.

"Off-record," he said. Quiet. Not gentle—precise. "What you almost said upstairs before Mara hauled me into the hallway like I was a rookie with a hard-on for a witness. Which, for the record, I am not supposed to be." A flicker of the velvet-blade smile, gone. "Talk to me like I am not wearing the badge. Then we decide what Ellison gets."

[player_name] watched a raindrop crawl down the glass. Renny's absence filled the back seat without needing a body. Seven years. Festival pier. Unidentified partial remains upriver. A silver charm that *could* match the missing piece of a bracelet Renny never took off. Lab ID pending. Hope and dread fogging the cabin together, breath and weather the same temperature.

"You heard Ellison," [player_name] said. "Full cooperation or I lose access. She wants Owen on the pier. She wants the omission. She wants everything I kept because I thought keeping it was love."

"I heard her." Will's knuckles whitened on the wheel—cracked, old scars across the ridges, the kind of hands that had hit doors and people and maybe a past he would not open. When Ellison had almost said Nina Solis in the hallway, Will had touched his ribs like a man checking a bruise that never yellowed. He did not explain. He never explained. The hint sat between them like a third passenger: a partner who had taken a fall, a sealed file, a detective who used charm as armor because the truth under it still cut. "I also heard you almost trust me. That is rarer than access, and more dangerous."

Heat crawled [player_name]'s throat—not only fear. Attraction had climbed into the car with them: the smell of him, the nearness of his shoulder, the way his voice dropped when the badge loosened. Dangerous. She wanted to lean across the console and also wanted to open the door and run into Harborwick rain until the kept secret washed off. It would not wash off. Secrets like this grew roots in the ribs.

"The night Renny vanished," she began, and stopped. Rain thickened. Will waited with the patience of a man who had waited out worse rooms—rooms his dark past still stained, if Ellison's side-eye meant anything. He did not fill silence with comfort. Brutal charm's quieter twin: attention as a blade laid flat, edge available, not yet cutting.

"I saw Owen near the pier," [player_name] said. The words came out small and then larger, as if saying them grew them. "Not with Renny. With someone who was not supposed to be there—someone I still cannot name cleanly because I only saw a shoulder, a jacket, a way of standing that did not belong to festival kids. Owen saw me see him. Later he told me Renny ran off with friends. He made her trouble sound like drugs, debt, the soft shame families hide so the hard questions never get a hearing. I was twenty. I put none of it in the statement. I told myself I was protecting her. I was protecting the house. The house is ash. She is still missing or—" Her voice cracked. "Or she is among remains that still do not have her name. Cho has not said. Rumor has. I will not let rumor bury her before science speaks."

Will exhaled through his nose. The notebook stayed in his jacket. Off-record meant no pen, which somehow felt more intimate than any recorded interview—truth without a paper trail, trust without a warrant. "That is the card Ellison wants face-up on her blotter," he said. "Owen at the scene. Your omission. The unnamed shoulder. She will use it to freeze Vale, freeze you, freeze me if I look like I am shielding a family witness because I like the way she says my name."

[player_name]'s cheeks warmed. "I did not—"

"You did. Once. Downstairs. It slipped." The almost-smile returned, wounded and sharp. "I catalogued it. I catalogue everything. Including the way you look at me when you should be looking at the case. Including the way I look back when I should not." He turned his head. Grey-green eyes, sleep-deprived, hungry for truth and maybe for her. "Here is the fork, [player_name]. We can walk back upstairs and give Ellison everything she wants—full coop, pier sighting on record, Owen named, your kept night spent like currency she will not refund. Or we keep one card off the record tonight. Not forever. One card. Something Renny left, something Owen said, something about that jacketed shoulder that you are not ready to hang a man with until Cho's timing drips further. Off-record honesty is still honesty. It is also a kind of loyalty Ellison does not have a form for."

Rain hammered the roof in soft percussion. The foghorn answered. [player_name] thought of Renny's hoodie in the drawer, the bracelet gap, the charm in the evidence photo that was only *like*. Thought of Will's past humming unspoken—the sealed past as a bruise, not a biography. Thought of Ellison's sixty-second clock still ticking somewhere above them in fluorescent honesty. Mid-thirties detective, mid-twenties sister of the missing: close enough to burn. Far enough that trust still felt like crossing a border without papers.

"If I give her everything," [player_name] whispered, "do I still get to stand next to the file when Cho calls? Or does full cooperation mean I become a statement in a folder while you and Ellison decide whether those remains are Renny without me in the room?"

"If you give her everything, I fight to keep you in the room," Will said. No velvet now. Bone. "If you keep one card, I fight harder—and I also become the man who helped you sandbag a captain. My charm does not survive that kind of audit clean. Neither does whatever this is." He gestured between them—small motion, enormous claim. "I am not a clean-hands detective with a soft winter story. I am Harborwick cold case with a sealed silence and a smile that opens people. You should be afraid of me. You should also know I will not bury your sister for a rumor, and I will not bury you for loving her badly."

The cabin felt too small. Want and dread and hope shared the vinyl seats. [player_name]'s unfinished life with Renny pressed against her unfinished want for this man. Outside, a uniform walked past under an umbrella and did not look in—yet. Ellison's reach was long. Time was short.

One path meant walking back into the precinct to give Ellison everything: Owen, pier, omission, the soft shame spent in fluorescent light while Will stood witness to the spending. The other meant keeping one card off the record—intimate, dangerous, a private ledger between a detective with brutal charm and a woman who had kept too much—while the case map waited for a night that was not only about evidence.

[player_name] looked at Will's hands on the wheel, cracked knuckles pale, and at the rain rewriting the windshield every second. Renny's fate still unnamed among the upriver dead. The charm still only *like*. Hope still had a throat. Dread still had teeth. The off-record air between them tasted like confession and like the beginning of something Ellison would call a career wound and [player_name] might call the only honest hour she had stolen in seven years.

The station's upper windows glowed like indifferent stars. Ellison was up there somewhere with her tablet and her metrics and her bruise-named warnings about Akers specials. Down here in the lot, [player_name] had rain, Will, and a choice that would either feed the captain's blotter or feed a private ledger no form could capture. She thought of Renny at seventeen forever in photographs, of the festival lights on black water, of Owen's too-calm morning voice. She thought of Cho's lab and the careful language of *unidentified* and *pending* and *consistent with* that never yet said *Renny*. Holding hope open hurt. Closing it early would hurt worse. Will's silence asked her which hurt she could live with tonight.

A truck hissed past on wet asphalt beyond the chain-link. Will's profile in the dash-dark looked carved from sleeplessness and old decisions. "Whatever you pick," he added, quieter, "do not pick it to spare me. I have survived uglier audits than Mara Ellison's side-eye. I have not yet decided if I can survive watching you disappear behind a lawyered wall or a family lie again. That is my problem. The pier night is yours to spend or keep. Spend it with me upstairs, or keep one piece warm between us. Either way, Renny does not get erased by rumor on my watch. Either way, you walk out of this car knowing I see you—not only the witness file."`,
  textHot: `William Akers's unmarked car smelled like rain on vinyl, gun oil, burnt-coffee ghost—and the low electric musk of two people who had fled a captain's clock to sit too close in the dark. The lot was a slick black mirror. Fog pressed the chain-link. A foghorn rolled up from the pier like the river clearing its throat. [player_name] sat in the passenger seat with her thighs pressed tight, mid-twenties, pulse hammering in her throat and lower, the unfinished interview sentence still wet on her tongue.

Will shut his door soft. Mid-thirties, rain-dark hair, scar through his left eyebrow, jaw set because the brutal charm was offline and the wound was driving—and because wanting her in a parked car behind the precinct was the kind of stupid that got badges broken. He did not start the engine. Both hands on the wheel. She watched the tendons flex and imagined those hands elsewhere: on her jaw tipping her mouth open, on her hip dragging her across the console, between her legs where she was already slick from nothing but proximity and the almost of truth.

"Off-record," he said, voice low enough to stroke. "What you almost said before Mara hauled me out like I was a rookie with a hard-on for a witness. Which—fuck—I am not supposed to be." The velvet-blade smile flickered and died. "Talk like I am not wearing the badge. Then we decide what Ellison gets. And what I get."

The *what I get* landed in [player_name]'s cunt like a finger. She exhaled shakily. Renny's absence filled the back seat. Seven years. Festival pier. Unidentified remains upriver. Charm that *could* match. Lab pending. Hope and dread fogging the cabin with their breath. Will's knee was inches from hers. Heat jumped the gap.

"You heard Ellison," she said. Rough. "Full coop or lose access. Owen on the pier. The omission. Everything I kept."

"I heard her." His knuckles whitened—cracked ridges, old violence written in bone. In the hallway Ellison had almost named Nina Solis; Will had touched his ribs like checking a bruise that never yellowed. Partner. Fall. Sealed file. Charm as armor. He did not explain. The silence made [player_name]'s nipples tighten under her blouse; she wanted to put her mouth on that unnamed bruise and suck until he confessed or came. Filthy. Wrong. Present. "I also heard you almost trust me. Rarer than access. More dangerous. Makes me hard when it should make me careful."

She made a small sound she could not swallow. Attraction had climbed into the car naked: his smell—soap, salt, scrubbed-dark past—his shoulder near enough to bite, his voice dropping into the register that made her clit throb in time with the rain on the roof. She wanted to lean across the console and climb into his lap until the badge and the case and Ellison's clock dissolved into friction and honesty. She also wanted to run. She stayed. Wet cotton clung when she shifted.

"The night Renny vanished," she began, and his eyes locked on her mouth like he could fuck the rest of the sentence out of it. "I saw Owen near the pier. Not with Renny. With someone who should not have been there—shoulder, jacket, a stance that was not festival kids. He saw me see him. Told me she ran off with friends. Made her trouble sound like drugs and debt. I was twenty. I put none of it in the statement. Protected the house. The house is ash. She is still missing—or maybe among remains that still do not wear her name. Cho has not said. I will not let rumor bury her."

Will's exhale was almost a groan. Notebook stayed in his jacket. Off-record meant no pen—truth without paper, trust without warrant, intimacy without a name yet. "That is the card Ellison wants face-up," he said. "She will freeze Vale, freeze you, freeze me if I look like I am shielding you because I want my mouth on yours more than I want her clearance." He turned. Grey-green, sleep-starved, hungry. His gaze dropped to her throat, her breasts, the seam of her jeans where she was pressing her thighs together like a secret. "Here is the fork. Walk upstairs and give her everything—pier, Owen, omission, your kept night spent under fluorescent light while I watch you strip truths I want to taste off your tongue. Or keep one card off the record tonight. Not forever. One card. Something Renny left. Something about that jacket. Off-record honesty is still honesty. It is also the kind of loyalty that ends with my hand on your thigh while we pretend this is only a case."

As if the words summoned it, his right hand left the wheel and hovered—then settled, warm and heavy, just above her knee. Not higher. Not yet. The contact shot straight to her cunt; she bit her lip and tasted copper and want. Rain hammered. Foghorn answered. Mid-thirties detective, mid-twenties sister of the missing: close enough to burn. His thumb stroked once, deliberate, a question written on denim.

"If I give her everything," [player_name] whispered, voice wrecked, "do I stay in the room when Cho calls? Or do I become a folder while you decide if those bones are Renny without me?"

"If you give her everything, I fight to keep you in the room." Bone-honest. No velvet. "If you keep one card, I fight harder—and I become the man who helped you sandbag a captain. My charm does not survive that audit clean. Neither does this." He squeezed her knee. Claim. Warning. Promise. "I am not a clean-hands detective with a soft alibi. I am Harborwick cold case with a sealed silence and a smile that opens people. You should be afraid of me. You should also know I will not bury your sister for a rumor—and I will not bury how fucking badly I want you for a policy memo."

The cabin was too small. She could smell her own arousal under rain and vinyl. His hand stayed on her knee, heat soaking through. She imagined it sliding up, palm pressing the seam of her jeans, fingers finding how wet she was from confession alone. Imagined climbing him, grinding against the hard line she could almost see in his trousers when lightning flickered over the lot—want reciprocal, brutal, unfinished. Renny's fate still unnamed. Charm still only *like*. Hope and dread and lust sharing one fogged windshield.

One path: back upstairs, give Ellison everything, strip the night bare under policy light while Will watched with hunger banked and professional—her mouth honest, her body aching unused. The other: keep one card off the record, stay in this car smelling of gun oil and need, his hand maybe climbing, the case map waiting for a night that would braid intimacy and evidence until neither of them could pretend the heat was only procedural.

[player_name] looked at his cracked knuckles on her knee and at his mouth—scarred-brow gravity pulling her forward an inch before she stopped. Renny's hoodie still waited in a drawer. The upriver remains still refused a name. William Akers—brutal charm, the sealed past-bruise silence, cock hard from her trust. The off-record air tasted like confession and like the beginning of sex Ellison would call a career wound.

She could feel her heartbeat in her clit, absurd and undeniable, every rain-hit on the roof a metronome for how badly she wanted him to slide that hand higher. If she chose Ellison's everything, she would climb the stairs with wet jeans and an honest mouth, stripping for policy while Will's want stayed banked behind professional eyes—punishment and virtue in the same climb. If she kept one card, she might stay in this vinyl dark until his palm found how soaked she was from telling the truth, until off-record became a synonym for his fingers inside her while they argued over which scrap of Renny's life to hold back until Cho's next drip. The foghorn groaned again. [player_name] almost moaned with it.

Will's thumb stroked once more, a filthy metronome. "Clock's still ticking upstairs," he murmured. "But down here you get to choose with your body in the room—not just your statement. Give Mara the whole night and I will still want you. Keep one card and I will want you dangerously. Either way I am not clean-cut, not soft, not safe. I am the man who opens people with a smile and then has to live with what falls out. You should know that before you lean across this console or walk back into fluorescent light. You should also know that right now I can smell how much you want this—want me—and it is fucking with my badge in ways his sealed past's name only starts to explain." He did not explain further. The hint burned. [player_name]'s cunt clenched. The choice hung between his hand and her mouth like unfinished sex.

Outside, rain sheeted the lot lights into smear. [player_name] could still leave—open the door, climb toward Ellison with everything face-up—or cover his hand with hers and keep one card warm between their palms while the case and the want negotiated an off-record night neither badge nor rumor could quite name yet.`,
  choices: [
    { id: "scene6b", text: "Give Ellison everything she wants", textHot: "Give Ellison everything she wants" },
    { id: "scene6c", text: "Keep one card off the record", textHot: "Keep one card off the record" }
  ]
};
