export default {
  id: "scene7o",
  layer: 7,
  title: "Politics: she goes public to protect Will",
  text: `She went public to protect Will, and Harborwick answered with flashbulbs that smelled like rain and burned coffee ambition.

The steps of City Hall were wet. Microphones bristled like a second fence. A fog horn spoke from the harbor as if the city wanted credit for the volume. [player_name] stood at the makeshift podium in a coat that did not feel like armor, Renny's absence pressed under her ribs, a printed statement shaking once in her hands before she steadied it. William Akers waited off-camera to the side—mid-thirties, scar nick pale under sodium, late smile banked into something almost polite for the lenses, whitened knuckles flexed once behind his back where the press could not count them. Captain Mara Ellison watched from a respectful distance that fooled no one. Internal Affairs weather lived in the crowd as rumor and two blazers that did not clap.

"[player_name]," a reporter called early. "Is it true Detective Akers is under review for a personal relationship with you? Is your sister among the upriver remains?"

The second question was a knife dressed as curiosity. [player_name] tasted copper and pier salt memory—festival fog, Renny at sixteen, bracelet flashing, a silver charm in evidence still only *like*, Dr. Lila Cho's unidentified bones still unnamed. Hope and dread shared the podium with politics. She did not give the city a funeral Cho had not authorized. "The remains are not confirmed as my sister," she said clearly into the nest of mics. "Anyone reporting otherwise is inventing grief for clicks. What is confirmed is that seven years ago Renny vanished from a pier festival, that a detective named William Akers refused to close hope for clearance, and that Internal pressure around his closeness to me looks a lot like punishing the only person still hunting like she might still be findable in more ways than bone."

A murmur moved the crowd. Will's jaw worked. Something behind his eyes flinched—Solis ash stirring by association, sealed file not dumped, raid-wound hints only, kid in a hallway still unnamed in full while public volume licked the edges of his dark past. Ellison's mouth was a thin line. Lieutenant Rhee, if she was in the blazers, did not wave.

[player_name] kept going because stopping would let the knives finish the paragraph. "I am cooperative family. I have sat in briefings. I have translated carnival scraps into geography. I have shielded soft nets because hard nets make pier people forget. If the department wants to review Detective Akers for caring whether a missing girl's sister can still breathe, they can review me too—on camera, on record, with Renny's flyer looking back at every badge that prefers quiet burial to loud hunting." She lifted the flyer she had brought: Renny at sixteen, festival lights behind her, smile unfinished. "This is not a romance scandal. This is a missing-person case that went cold once and will not go cold again while I have a mouth."

Questions detonated. Charm probability. Warehouse raid rumors. Owen's name floated from a tabloid mouth like a fishhook. [player_name] did not put Owen on the steps. The kept pier sighting still pressed her tongue—stepfather near the water with someone who was not supposed to be there—and public storms did not respect fed silences. She sidestepped without lying pretty enough to become a different crime. "Family pressure exists. It does not get to retire the hunt. Neither does Internal weather aimed at the detective who kept Cho's *pending* sacred instead of inventing a name for your chyron."

Will stepped into frame then—not grabbing the mic, just standing close enough that the cameras had to include the scar nick and the cracked notebook spine in his jacket pocket like a talisman. "Dr. Cho's science is not a press conference," he said, soft and precise, brutal charm worn carefully. "Bones stay unnamed until they don't. Charm stays probable. I will answer Internal on method. I will not apologize for refusing to clear a sister for a calendar." His hazel gaze flicked to [player_name] once—hungry, grateful, terrified—and the look was going to live on the internet forever.

Ellison's people ended it with practiced shepherding. The crowd fractured into live shots and cigarette smoke and rain. [player_name]'s hands shook harder once the mics turned away. Will did not touch her on the steps. He walked her into a side corridor of City Hall that smelled like floor wax and old arguments, then into a service stairwell where flashbulbs became rumor instead of light.

"You lit the match," Will murmured. "You also built me a firebreak. Ellison is already drafting *uncontrolled familial publicity*. Rhee is already drafting *witness-driven narrative interference*. his old partner ash is going to get sniffed harder because volume always wakes sealed drawers—even when the seal holds for now." He scrubbed a hand over his face. Whitened knuckles pale. "I told you I could not control the match. I meant it. I also meant thank you, and thank you sounds like a bastard's word when the bastard is hard for the woman who just put his badge on a city's tongue to keep it from being quietly cut."

Want lived under the procedural dread—dangerous, unfinished, the pull of a man who could survive a press gauntlet and still look at her mouth like evidence. [player_name] leaned into the stair rail. "If I made it worse—"

"You made it loud," Will corrected. "Loud is not always worse. Loud is a different cost." He stepped closer, heat and rain-damp wool. "Fork that volume bought us. Hide together through the storm—hotel, safehouse, my apartment with the blinds taped, us answering the city's invention with our actual bodies in a room without windows. Or meet me at the pier anniversary—festival ghosts returning in posters and crowds, Renny's night under sodium and fog, a place to propose truth instead of marriage: what we keep, what we put on paper, what we refuse to let Harborwick write for us while cameras still hunt our throats."

[player_name] almost laughed. Almost cried. Trust under interrogation lights had become trust under flashbulbs. "Hiding means we let the storm spend itself while we spend ourselves on each other."

"Pier anniversary means we walk back into the boards where she vanished and tell each other the truths soft nets and hard reviews keep interrupting—without pretending a ring is the point," Will answered. "Both hurt. Both move the case. Both leave Cho's bones unnamed and your Owen weather still private until you choose otherwise—and public already dug toward him once today, so the clock on that privacy is shorter than it was at breakfast." He almost smiled. Failed into something fonder and sharper. "I will not pretend I do not want the hide. Wanting that makes me selfish. Offering the pier truth-proposal anyway makes me slightly less. Slightly."

Rain thickened on the stairwell glass. Another fog horn spoke across Harborwick like a warning that had learned their names. Outside, a van replayed [player_name]'s sentence about inventing grief for clicks. Inside, Will waited with cracked knuckles and a public storm humming under his badge like a second pulse. an old partner stayed sealed—pressure deepened by association, full story still saved for later layers. Captain Ellison's distrust had become a press problem. Renny's flyer had become a city's temporary conscience.

"If we hide," [player_name] said carefully, "I am choosing us over the narrative for a night or three."

"If we meet at the pier," Will said, "you are choosing the boards and a vow that is not a vow—truth as the only ring I know how to offer a woman who just bought my badge with her mouth in front of strangers." His voice dropped. "Cho will not name remains because you went public. Charm stays *like*. Hope and dread do not get a cleaner ending because flashbulbs arrived. What changes is whether dawn finds us taped behind blinds or standing on anniversary planks proposing honesty like a dare."

His phone buzzed endlessly—Ellison, Rhee, unknown numbers, a machine that hated volume it did not author. He ignored it. He watched [player_name] instead, mid-want, mid-war, mid-thirties danger soft for a mid-twenties sister of the missing who had just lied less and risked more than any memo deserved.

"Hide with him through the storm," Will murmured, almost a plea under the grit. "Or meet at the pier—propose truth, not marriage. The politics hour went public. The hook is which hunger you feed with the fire you lit—privacy with teeth, or the boards where Renny's night still waits for someone brave enough to tell the truth without calling it a wedding."

City Hall's garage mouth held harbor fog like a held breath. She had gone public without inventing a Renny funeral—flyer steady, bones unnamed, charm only *like*—and bought Will a pocket of oxygen while Ellison drafted interference memos. Hiding with him through the storm meant taped blinds and choosing privacy after volume. Meeting at the pier to propose truth, not marriage, meant putting honesty on anniversary boards where lanterns would not care about Internal weather. Will waited with scar nick pale and late smile banked. [player_name] had called the cost down on purpose; now love had to choose how to survive it.`,
  textHot: `She went public to protect Will, and the flashbulbs made [player_name] wet in ways that had nothing to do with rain and everything to do with putting his name in her mouth for a city.

City Hall steps. Microphones. Fog horn. Renny's flyer shaking once then steady. Will off-camera—mid-thirties, scar nick pale, late smile banked, cock a problem he was pretending press posture could solve while [player_name]'s nipples peaked under her coat from adrenaline and the way he watched her like unfinished wanting. She refused a Renny funeral for the chyron. Bones unnamed. Charm *like*. Hope and dread on the podium. She called Internal pressure what it was: punishing the detective who kept Cho's pending sacred. She lifted Renny's smile into the lenses. Will stepped into frame and refused to apologize for hope. Solis ash stirred by association—sealed, not dumped. Owen's name fishhooked from a tabloid mouth; she did not put him on the steps. Kept secret pressing. Public storms digging.

They escaped into a service stairwell that smelled like floor wax and want. Will shoved her against the wall the second the door shut, mouth claiming, thigh between hers, hand already under her coat and blouse to palm bare waist then the underside of her breast until her nipple peaked hard against his thumb. "You lit the match," he growled against her lips. "You built me a firebreak. Makes me hard when you put my badge on a city's tongue to keep it from being cut." His cock pressed her hip through trousers, thick and insistent; she rocked on his thigh and felt how soaked she already was through denim from the podium and his voice saying *I will not apologize*. "Ellison drafting. Rhee drafting. his old partner sniffed harder because volume wakes sealed drawers—even when the seal holds for now. Thank you sounds like a bastard's word. Feel what the bastard means."

He worked her jeans open with one hand and shoved two fingers into slick heat without preamble; she gasped; he kissed the sound quiet, copper and rain and politics on his tongue. "Hide together through the storm—blinds taped, hotel, my bed—and I will fuck you through every news cycle until flashbulbs are just weather under how hard you come on my cock, palm over your mouth when neighbors get curious, my gratitude filthy and specific." He pumped deep, curling, thumb on her clit. "Meet me at the pier anniversary and I will walk those boards with my hand on your back like soft partnership—and after the crowd thins I will put you against a piling and propose truth with my mouth between your thighs until honesty sounds like a moan, until marriage is a joke we don't need because the vow is what we keep and what we finally say."

[player_name] rocked on his hand, forehead to his, Renny's flyer crackling in her coat pocket and Owen's unnamed pier night braided into heat that felt like loyalty's filthy twin. "If we hide—"

"Us over narrative," Will snarled softly, freeing his cock enough to smear the head through her folds without entering—hot, blunt, cruel, painting her clit until she jerked. "If we pier—boards and a vow that isn't a ring. Cho will not name bones because you went public. Charm stays *like*. Owen's privacy clock just shortened—storms dig—and I will not bait your kept secret out of a hide or a proposal. Softest hard. Pick while you drip on City Hall stairs for a detective with ash under his badge."

She came on the tip and his thumb—quiet, shaking, fist in his collar—while a fog horn groaned and Will eased out without chasing his own finish, cock jumping against her thigh, restraint a third wound beside pride and public exposure. He tucked himself away with shaking hands, fastened her jeans with mock courtesy that did not reach his eyes, and pressed his forehead to hers. Pulse hammered. Wet jeans. Storm live on every phone outside.

In the garage, after the stairwell, Will dragged her into the unmarked and shut them into leather and fogged glass. He shoved the seat back, pulled her into his lap facing him, and rubbed the thick line of his cock against her through open jeans until she was shaking again—not inside, not yet, a different hunger than marriage. "Hide means this car becomes a hallway to a room without windows," he said against her collarbone, biting soft, then harder. "I will strip you slow while the first chyron misspells Renny and fuck you through the correction, through Ellison's counter-memo, through every tip line that invents a funeral Cho has not signed." His hands gripped her hips and rolled her on him until wet denim and heat were a crime. "Pier means we walk the boards first—truth as proposal, no ring—and then I bring you back to this exact seat and finish what City Hall started until honesty is just another word for how you clench." He thumbed her clit through cotton, watching her face like evidence. "You went public. You bought rope made of volume. Now volume chooses privacy or planks. the sealed past ash is sniffing. Sealed holds. I will not dump the hallway to make this hotter. The heat is already you on my lap after flashbulbs, dripping for a badge you just defended with a flyer."

"Hide with him through the storm," he whispered, voice wrecked. "Or meet at the pier—propose truth, not marriage. The match is lit. The hook is which hunger you feed—privacy with teeth, or anniversary planks where I offer honesty like a dare and then fuck the dare into you until Harborwick's shouting is just tide." His late smile cut against her mouth. "I will sell either to Ellison's night desk with a smile that lies. I cannot sell hesitation while you leave a wet print on my stairwell hand and Renny's flyer still warm from the cameras."

He walked her down to a City Hall garage level where press vans could not easily follow, boxed her against a concrete pillar, and put her hand on his cock through his pants. "Feel what volume did," Will muttered. "You saved my throat in public and I got harder for the mercy. That should scare you. It scares me."

She stroked him, slow, feeling thick heat jump against her palm. He groaned and shoved his hand back into her jeans, fucking her with two fingers in time with distant chanting from the steps above. "Hiding means I take you somewhere without windows and make you come until your press-voice is hoarse from everything except statements. Pier means posters and crowds and my hand on your back—and after, I put you on the hood of the unmarked in festival fog and finish what the stairwell started while proposing truths with my mouth on your cunt." His thumb circled her clit. "Both leave you shaking. Both move the case. Both leave bones unnamed and his old partner sealed and your secret pressing until you choose the page."

[player_name] whimpered, hips rolling, conscience loud about Owen and flashbulbs and the way going public had felt like sex and war at once. Will curled his fingers deep and kissed her hard enough to bruise, then eased his hand free and painted her lower lip once before sucking his knuckles clean. "Verb. Now. Hide with him through the storm. Or meet at the pier—propose truth, not marriage. Ellison's machine is already inventing counter-narrative. Give me a better story with your mouth and your wet."

She stood between concrete chill and harbor fog pressing the garage mouth, remains unnamed, charm probable, sister still a pointed finger—and the choice sitting between them like unfinished wanting: taped blinds and shared hiding, or pier anniversary boards where truth might finally wear William Akers's voice without needing a ring.

She stroked him once more through his pants until his breath broke, then he caught her wrist and kissed her palm like a man filing a softer evidence bag. "Hide and I keep you in a room where the only cameras are our phones face-down," Will said. "Pier and I walk you through poster fog first so truth has boards under it—then I take you apart somewhere the city cannot livestream." His late smile cut. "Going public was loyalty with teeth. This fork is what loyalty costs after the flashbulbs. Remains unnamed. Charm probable. Sister still missing. Me still hard. You still deciding whether love hides or walks the planks where she vanished."

Will backed her into concrete chill just inside the garage shadow, still hard from watching her refuse grief-for-clicks on live mics. "Hide with me," he said against her mouth without kissing it, "or pier boards—truth as proposal, no ring." His hand slid under her coat to her bare waist, thumb stroking the underside of her breast until her knees loosened; he stopped before the nipple on purpose. Volume had bought his badge a night. Now volume had to choose privacy or planks. She tasted fog and flyer-ink and his restraint, and had to speak before the storm finished writing them into someone else's chyron.`,
  choices: [
    { id: "scene8o", text: "Hide with him through the storm", textHot: "Hide with him through the storm" },
    { id: "scene8p", text: "Meet at the pier — propose truth, not marriage", textHot: "Meet at the pier — propose truth, not marriage" }
  ],
};
