export default {
  id: "scene6d",
  layer: 6,
  title: "Off-record night: intimacy refused; case only",
  text: `Off-record did not mean soft. It meant William Akers's badge stayed in his pocket while the case still claimed every inch of [player_name]'s living-room floor, and it meant the air between their bodies had a temperature Ellison's fluorescents never measured. Harborwick rain ticked rusted chain-link in the alley like loose teeth counting. Burnt precinct coffee—reheated once in her microwave, bitter enough to strip paint—steamed from two mismatched mugs on the coffee table. Will's cracked notebook lay open on the carpet beside photocopied pier maps and Dr. Lila Cho's pending language printed in careful ink: *unidentified*, *age range consistent with*, *charm probability*—never *Renny*. Lab ID unfinished. Hope and dread shared the floor like co-counsel who refused to adjourn.

Will knelt opposite [player_name] with his charcoal sleeves rolled, scar cutting his left eyebrow, mid-thirties sleeplessness carved into the set of his mouth. Brutal charm banked so low it was almost gone—velvet folded away from the blade because she had already said, downstairs in the damp vestibule, that tonight was case only. He had nodded once. He had not pretended the nod cost him nothing. Grey-green eyes tracked the papers and, when he thought she was not looking, the line of her throat where her pulse jumped every time their knees almost touched.

"Ellison thinks off-record is a euphemism for sandbagging," Will said. Voice precise. Off-duty quiet that was somehow sharper than precinct volume. "We prove her wrong by building something she cannot dismiss when we walk it in. Warehouses Renny marked. Clerk initials. Owen Vale's late nights against the alibi he bleached into family dinners. Festival vendor scraps. Timeline that keeps the upriver remains unnamed until science earns the right to speak a sister's name—or to say the bones belong to someone else's grief."

[player_name]'s mid-twenties hands smoothed a crease that would not stay smooth. Renny had been a teenager when she vanished—seven years folded into a hoodie still waiting in a drawer, into a silver charm bracelet missing one tooth that *could* match the upriver silver and still refused confirmation. The kept detail about Owen near the festival pier had finally begun to spend itself in statements and soft nets and raw admissions that led here: an apartment floor, a detective without his badge on the table, a woman who had invited him up for the map and refused him for everything else. Refusal was not cruelty. It was sequencing. Grief first. Want later—if later survived the morning.

"Case only," she said again, quieter, because his gaze had drifted to her mouth. "I mean it, Will. If we start—" She stopped. The unfinished sentence lived in the rain sound. If we start, I will not stop. If we start, Ellison will smell it on you. If we start, Renny's Xs will become a mattress and I will hate us both when Cho calls. "The map. The chain. That is the night."

Will's jaw flexed. Cracked knuckles whitened on his pen—old scars across the ridges. When a precinct prefix lit his phone and died unread, he touched his ribs absently, a bruise-check that never yellowed. He did not dump the raid onto her carpet. Dark past hummed under the off-record quiet. He let the silence bruise, then spoke with the allergy to lies that made his restraint feel like both weapon and wound.

"I heard you in the vestibule," he said. "I hear you now. Case only. I will not put my mouth on you because the coffee is bad and the rain is loud and you look like someone who has been holding a city up with her bare hands. I will also not pretend the refusal is invisible. It sits on the map with Owen's name. It sits in my chest like a second badge. Partnership tonight means I catalogue warehouses and I keep my hands on paper. It does not mean I stop wanting the other room in this night. Wanting is not touching. Touching is what you refused. I can live with the difference until dawn. After dawn is another audit."

Rain thickened. Pier salt ghosted through the cracked kitchen window and mixed with coffee steam and the faint vanilla that still clung to Renny's things down the hall—absence as perfume. [player_name] read aloud from the vendor scrap while Will translated teenage shorthand and cold-case grammar into a single language: a harbor warehouse with a loading door that did not match any tourist brochure, a city clerk's initials scrawled like a dare, Owen's phone records that did not match the story he had fed breakfast tables for seven years. Not a corpse named. A chain sketched across carpet fiber. The kind of trouble that made unidentified remains feel like a threat with a pulse—and also like a door that might still open on breath elsewhere if the river's rumor had worn the wrong sister's size.

Attraction was a stupid animal in a room built of refusal, and it came anyway. Soap and salt and scrubbed-dark past filled the space when Will leaned near to align a photograph. [player_name] tasted burnt coffee and fear and the sharper taste of almost-trust climbing her throat without permission to become a kiss. Mid-thirties detective with brutal charm and a sealed silence; mid-twenties sister who had obstructed her own sister's case and was now opening the chain under his eyes while closing the door on his mouth. Trust under living-room light. Heat under procedural pressure. No clean hands. Only this man and this maybe and this *not tonight* that hurt more than some yeses.

Once his knuckle brushed her wrist as they both reached for the same timeline page. Heat jumped. She pulled back first—not far, just enough. Will went still, then nodded once, a small brutal courtesy, and moved his hand to his own knee like a man holstering a weapon. The not-touching afterward felt louder than the brush. Yellow tape ghosted in memory when she said *pier*—festival night, chain-link, the silhouette she had protected until protection tasted like burial of the living. She said the silhouette's shape again for the map: Owen, jacketed shoulder, someone who was not supposed to be there. Will wrote it in the notebook with a spine cracked from overuse. Habit. Armor. A small prayer to order while want prayed in a different direction.

"Ellison will push by morning," Will said, sitting back on his heels. Rainlight silvered the scar through his brow. "Flip on Owen clean—full heat, soft net gone—or she starts talking charge sheets for obstruction and familial sandbagging. Off-record night buys us hours, not immunity. If we walk in with a chain that holds, she may stay her hand. If we walk in with heat she can smell and a map that still has soft edges, she will use both against us." His mouth twitched—almost the velvet-blade smile, almost a joke about captains and perfume—and died because jokes felt like touching. "You refused the other room. That is your right. It also means the only room left is this one: paper, dawn, and whatever Cho drips when the lab finishes pretending patience."

[player_name] pressed her palms flat on the carpet beside Renny's Xs to keep them from reaching. Outside, a foghorn rolled inland once—low, lonely—then the city swallowed it. She thought of Ellison's tablet casting cold light under a captain's chin, of Cho's careful refusal to christen bone, of Owen's too-calm morning voice seven years ago, of Will's mouth three feet away and closed because she had asked it to be. Holding hope open hurt. Closing it early would hurt worse. Refusing him while the map bloomed was a third hurt—private, sharp, maybe necessary, maybe cowardice wearing sisterhood's perfume and calling it strategy.

Will's phone buzzed again—Ellison or Cho or the precinct's endless hunger—and he silenced it without looking, eyes still on [player_name]'s hands flat on the floor as if paper had a pulse he refused to stop counting. "Two doors from the refusal," he said softly. He did not touch her. The not-touching was the whole weather system of the room. "You admit the want mid-briefing—say out loud what we are both swallowing while we pretend warehouse marks are the only heat in the apartment—and we let the case-only streak break on purpose before Ellison breaks us on her schedule. Or we face her flip-or-charge ultimatum with the map as our only soft weapon, walk into fluorescent honesty without having spent the night on each other, and see whether a captain prefers a chain to a spectacle. One path spends the honesty between us before dawn. The other spends it on Ellison's desk. Both leave the remains unnamed. Both leave Renny's fate contested. Neither lets me kiss you unless you rewrite the vestibule rule."

Interview-room clock hum lived in [player_name]'s memory and nested under her ribs even here, miles from the precinct, because refusal had a fluorescent quality all its own. She looked at Will's scarred brow, at the wound he wore as humor's opposite, at the way his gaze kept returning to her mouth as if lips had a statement number. Renny's fate stayed contested: not named, not buried, not safe. The charm still only *like*. Full off-record with a hard edge. Partnership with a closed door. The rain rewrote the chain-link glitter every second. Choosing to admit the want meant ending the case-only fiction before morning—truth sequenced on desire's terms, briefing cracked open, hope and dread still sharing the air with a third animal finally named. Choosing Ellison's ultimatum meant keeping the scrap of restraint against her ribs while Will's notebook and Renny's Xs became the only constellation allowed on the carpet, while unfinished honesty and banked heat shared the damp air until a captain forced *flip* or *charge* into *now*.

Will kept his hands on the photocopies. He did not reach for her mouth. The refusal had a fluorescent quality even here, miles from the precinct—attention as a blade laid flat, edge available, not yet cutting the almost into something uglier. His dark past stained the silence without a second naming; Ellison's ultimatum waited like a weather front with teeth. [player_name] tasted copper where she had bitten her cheek to keep from leaning. Chain-link rattled in the alley. The USB waited in its sleeve. Renny's warehouse mark smelled like pencil and teenage certainty under the lamp. Choosing meant either ending the case-only fiction before morning—want spoken, briefing cracked, hunger finally named—or walking the chain into Ellison's *flip-or-charge* with his hands still clean of her skin and both of them loud with a hunger they had agreed, for one Harborwick night of rain and burnt coffee, not to spend.`,
  textHot: `Off-record did not mean soft. It meant William Akers's badge stayed in his pocket while his cock still noticed every shift of [player_name]'s knees on the carpet, and it meant she had said *case only* in the vestibule with her mouth looking like a place he was not allowed to put his. Harborwick rain ticked rusted chain-link in the alley. Burnt precinct coffee steamed bitter from mismatched mugs. His cracked notebook spilled pier maps and Cho's careful fuck-you to rumor—*unidentified*, *pending*, *consistent with*—never Renny's name, never a baptism, lab ID unfinished while [player_name]'s pulse hammered in her clit from proximity alone and she hated how refusal made her wetter.

Will knelt opposite her, mid-thirties, scar through his brow, sleeves rolled, charcoal shirt open enough at the throat that she could see the place she wanted to lick and had forbidden herself. Brutal charm banked into something worse: restraint so visible it felt like a hand on the back of her neck. Grey-green eyes tracked papers and, when she breathed wrong, the hard line already starting in his trousers that he did not apologize for because honesty was the only intimacy she had left him. "Ellison thinks off-record is sandbagging," he said, velvet-blade low. "We build the chain. Warehouses. Clerk initials. Owen's late nights. Festival scraps. Timeline that keeps the upriver remains unnamed until science earns the right. And I keep my hands on paper because you asked. Do not ask me to keep my eyes polite. Polite is a lie, and I am allergic."

[player_name]'s mid-twenties thighs pressed together under her skirt until damp fabric clung—filthy confession Ellison must never catalogue. Hope and dread shared her body with a third animal she had leashed: want, straining, wet, furious at the vestibule rule she herself had written. Renny's teenage Xs bloomed beside Will's professional marks. Charm probability still only *like*. Remains not Renny until science said so. She could smell herself under coffee and pier salt and his scrubbed-dark past. Case only. The words tasted like a cock ring she had snapped on both of them.

"Case only," she repeated, voice rough as if he had already been kissing her throat. "If we start, I will not stop. If we start, the map becomes a bed and Cho's pending language becomes a soundtrack I will hate us for. Map. Chain. That is the night."

Will's jaw flexed. Cracked knuckles whitened on his pen. Nina Solis lived in the flinch he aborted toward his ribs when a precinct buzz died unread—he did not dump the raid onto her carpet. The wound showing made [player_name]'s nipples tighten until her blouse scraped; broken men should not be this hot, and Will wore broken like cologne she was refusing to taste. "I heard you," he said. "Case only. I will not put my mouth on you. I will not put my fingers where you are already soaked—and do not pretend you are not, I can see it in how you sit, how you swallow, how your pupils go dark when I say *warehouse* like it is a filthy word. Wanting is not touching. You refused touching. I can live with the difference until dawn even while my cock does not agree to anything and you can see that if you look."

She looked. The hard line in his trousers was no longer almost—visible, denied, reciprocal, a blunt honesty his mouth was keeping professional by force. Heat flooded her cunt until she had to shift, and the shift made wet fabric drag her clit like a thumb she would not allow him to be. Warehouse weather pressed the alley glass; the city's damp seemed to conspire with her body against the vestibule rule she was still gripping with both hands. They read. Her voice broke on Owen's late nights and a clerk's initials. His pen scratched. When she leaned to point at a pencil X, her breast nearly brushed his arm and both of them went still as held breath; she pulled back first, shaking, and Will exhaled like a man swallowing a groan that wanted to become her name moaned into the carpet.

Rain on the chain-link clicked like an interview-room clock. Yellow tape ghosted when she said *pier*—festival night, Owen's jacketed shoulder, seven years of a kept detail now spending itself in ink while her body spent itself on nothing. Will's knuckle brushed her wrist reaching for the timeline. Electricity shot straight through her; she jerked away; he holstered his hand on his own thigh hard enough that his fingers dented denim beside the obvious strain of his cock. The not-touching afterward lived on her skin like heat. She wanted his hand under her skirt. She wanted his mouth on the refusal until the refusal broke. She wanted later and now and neither, and the bracelet's missing tooth winked from a photo on the table like a dare neither of them would take while Renny's fate stayed contested bone and rumor.

"Ellison will push by morning," he murmured, mouth close enough that coffee-breath warmed her cheek and made her lips part against her will. Notebook spine cracked as he flexed it—habit, armor, a sound like a belt considering. "Flip on Owen clean or she talks charges. Off-record buys hours. If we walk in with a chain that holds, maybe she stays her hand. If we walk in with heat she can smell—" His gaze dropped to her mouth, her throat, the tight points of her nipples under cotton, the press of her thighs. "—she will use it. You refused the other room. That is your right. It means the only room left is paper, dawn, and whatever drip Cho sends while I sit here hard as a fucking secret and you sit there dripping for a man you will not let touch you. Pure does not survive Harborwick. Neither does pretending this is only a briefing."

She pressed her palms flat on the carpet to keep them from his belt. Foghorn rolled inland once and vibrated in her ribs; she almost moaned with it. Full off-record with a hard edge that made her ache unused and furious with her own rules. His phone buzzed; he silenced it without looking, attention locked on her hands as if Ellison could wait while want could not and still would, because she had asked.

"Two doors from the refusal," he said. Still not touching—worse than touching. The not-hand lived on her clit like pressure without friction. "You admit the want mid-briefing—say out loud that you are wet for me while we catalogue clerk initials, let the case-only streak break on purpose, let me hear the words even if you still will not let me put my mouth between your thighs before dawn—and we stop lying with our bodies while the map stays holy. Or we face Ellison's flip-or-charge ultimatum with the chain as our only soft weapon, walk into fluorescent honesty without having fucked or even kissed, my cock still aching, your cunt still empty, and see whether a captain prefers evidence to the spectacle of a detective who smells like a night he did not get to finish. One path spends the honesty between us in words that will make you clench. The other spends it on Ellison's desk. Both leave the remains unnamed. Both leave Renny contested. Neither puts my fingers in you unless you rewrite the vestibule while looking me in the eye."

[player_name]'s heartbeat lived low and slick, absurd and undeniable. Rain rewrote the chain-link. Pier salt mixed with the musk of her denied arousal until Harborwick itself seemed to be watching the refusal. She could smell herself. She could see him. She could taste copper where she had bitten her cheek to keep from leaning across Owen's name and taking his mouth like a warrant. Choosing to admit the want meant ending the case-only fiction before morning—truth sequenced on desire's terms, briefing cracked, hope and dread still sharing air with a third animal finally spoken while her thighs stayed pressed and unsatisfied. Choosing Ellison meant keeping restraint against her ribs like a second spine while Will's notebook and Renny's Xs remained the only constellation allowed, while unfinished sex that was still only almost shared the damp air until a captain forced *flip* or *charge* into *now*.

Will's gaze stayed on her mouth and then lower, inventory without permission, and the inventory alone made her cunt clench around nothing. Attention as a blade laid flat against her clit without a finger near it. Edge available. Sealed wound still unnamed in his ribs. Renny's absence still a fourth guest who would not bless a kiss. [player_name] could smell herself. She could see the hard denied line of him. Choosing meant either handing him the want she had refused to spend—wetness still scenting the air—or walking the chain into Ellison's ultimatum with his hands clean of her skin, his chest loud with hunger, and a promise kept, for one night of deliberate unfinished fucking that never started, not to steal.`,
  choices: [
    { id: "scene7d", text: "Admit the want mid-briefing", textHot: "Admit the want mid-briefing" },
    { id: "scene7e", text: "Face Ellison's flip-or-charge ultimatum", textHot: "Face Ellison's flip-or-charge ultimatum" }
  ]
};
