export default {
  id: "scene9h",
  layer: 9,
  title: "Pier dawn: leave Harborwick or stay",
  text: `Dawn on Harborwick Pier arrived like unfinished weather—fog horns, salt, rusted chain-link, festival lantern ghosts that had no right to still smell like funnel cake and grief.

[player_name] stood on the boards where Renny had pointed east seven years ago, mid-twenties, silver charm gap aching like a tooth, Renny's old hoodie ghost folded inland across town as if fabric could keep vigil. William Akers stood beside her, mid-thirties, scar nick pale under grey morning, cracked notebook drinking mist in his jacket, brutal charm banked for a truth-proposal that was not a ring and not a tidy ending. Grey-green eyes found the open water and then found her. Hope and dread shared the planks the way they had shared Cho's bag for weeks. Dr. Lila Cho's science stayed careful: remains unidentified, charm probability elevated, age range ugly with hope. Captain Mara Ellison's cruiser idled at the lot edge without lights—caution wearing a unit number. Soft had returned as pier fog. Soft was expensive.

"Answer the boards," Will said quietly. Not soft as comfort. Soft as honesty without jewelry. "Leave Harborwick free—I respect the freedom. Pack the kept detail into a suitcase and walk inland cities that do not know Warehouse C by smell. I stay with the case as far as the badge requires. I do not chase your freedom into a second obstruction. Or stay in the fog—bittersweet pier—anniversary unfinished promise, hard sentences on these planks, us conjugating what you kept and what I will not dump yet while Renny's poster weather watches like a third judge."

[player_name] tasted copper and salt. Leaving tasted like survival and also like sanding with prettier luggage. Staying tasted like loyalty and also like drowning on purpose in a city that had already failed her sister once. Attraction pressed under procedural dread: soap-and-salt nearness when his cracked knuckles brushed hers, unfinished almost-kisses from rain nights and hospital dawns and letter beds and festival crates that had no business surviving into this dawn.

"If I leave," she said carefully, "I am choosing air over the braid."

"Yes," Will said. Honest because comfort was a lie he refused. "You are choosing a life the pier does not get to own. I will hate it and respect it in the same breath. Respect is not the same as not wanting. Wanting you does not give me a warrant for your geography." His late smile arrived wrong and fond—weapon and wound learning how to let go without becoming abandonment theater. "If you stay in the fog, you are choosing bittersweet on purpose. Unfinished anniversary. Truth as proposal without a wedding. Boards that remember her better than we deserve. Softest hard. Reciprocal teeth."

Nina Solis stayed sealed in the way pier dawn allowed—hint deepened by association, Will's flinch when a partner-shaped word tried to form, Ellison's side-eye from the lot as if distance were a policy. He did not unpack the raid. He did not strip the sealed file for lantern romance. Teeth showed. Whole mouth saved for later layers that earned ash.

[player_name] looked at Renny's unfinished smile on a weathered flyer stapled to a post—teenager pointing at a future that had become absence. Owen Vale's silhouette still lived in festival fog memory. Clerk weather—Marcus Hale, M.K., mid-level throats. This dawn did not require a killer named to require a choice. This dawn required leave or stay while science stayed careful and romance asked whether freedom and love could share a body without becoming a different violence.

"Ellison will ask if a truth-proposal on the pier is just proximity with better fog," Will murmured, eyes on the water. "You standing here is not theater. It is cooperation that walked the boards instead of inventing a funeral for comfort. Remains still unidentified. Charm still only maybe. I did not bring you to dawn because we buried your sister. I brought you because soft returned as lantern light and then as this—honesty as the only jewelry—and because offering leave-free anyway makes me slightly less of a bastard who likes soft nets after hard rooms. Slightly."

Silence thickened with fog. A vendor's generator coughed somewhere like a festival ghost. Will paced the choice with his voice the way he walked interview rooms—counting exits, counting lies, counting what freedom cost when it wore a suitcase and what staying cost when it wore bittersweet. "If you leave free, I will still be angry on these planks after—angry at Owen, at the chain, at seven years of scrubbed silhouettes, at myself for wanting you to stay while offering the door. Anger does not cancel respect. If you stay in the fog, I will still want your mouth when the ballad dies. Want does not cancel unfinished. I need you to hear both sentences without sanding either into comfort while Cho's tray stays contested and your sister stays a pointed finger."

[player_name] almost laughed. Almost cried. Trust under interrogation lights had become trust under pier dawn. The romance was whether she could love a badge after the system failed Renny—and whether he could love the woman who might walk away from Harborwick with the kept detail finally outdoors and still unfinished. Mid-thirties to mid-twenties—close enough to burn, far enough that the badge still felt like a different country even on boards they shared.

"Renny kept a map," she said quietly. "I kept a lie. You kept a sealed hallway. Ellison keeps a cruiser without lights. Cho keeps bones without a name. Everybody keeps something. The question is which keeping still protects a living hope at dawn and which keeping only protects a city that already spent her once."

Will's pen—he had been writing nothing, only holding the cracked notebook like a talisman—stopped against his palm. Respect moved through his face like weather changing. He almost kissed her then—stopped a breath short on purpose—scar nick white under morning grey, all weapon and wound, the brutal charm that had first made her want him under procedural pressure. Soft was expensive. The pier dawn was walking. Science stayed careful.

"Clock," Will said softly. "Leave Harborwick free—I respect it—or stay in the fog—bittersweet pier. Either way the boards remember her. Either way Cho's pending stays a leash we do not cut for comfort. Conjugate, [player_name]."

Ellison's cruiser did not move. Somewhere inland, warrants and footnotes and Owen's lawyers continued without them for the length of a dawn. Internal would catalogue proximity or catalogue distance. Nina Solis stayed sealed. Will wore the worse like cologne and still offered freedom as a real door and staying as a real vow without a ring.

[player_name] stood between festival noise-memory and harbor fog, fingers laced with William Akers's cracked knuckles, remains unnamed, charm probable, sister still missing in the only way that mattered—and the choice sitting between them like unfinished weather: leave Harborwick free with Will's respect as the last gift, or stay in the fog for a bittersweet pier promise that refused to close because closing would invent comfort neither of them trusted.

The corridor of open air between lot and water hummed like every precinct clock that had ever watched a familial contact choose—only this one wore salt and still managed to sound like a warrant. Will drove a slow loop of words around the dawn: freedom as respect, staying as unfinished vow, soft partnership as the refusal to invent Renny on silt because fog had made the boards look honest. [player_name] peeled the night's fear from her shoulders the way she had peeled mic packs in other weathers and set it aside like evidence she would not sand. Dawn clean enough. Renny's fate still contested silt. That mattered more than pride and more than Ellison's quiet cruiser.

"If you leave free," Will added, almost gentle, "I will give you more Solis than hints by letter when the case earns it—not a sealed-file striptease for goodbye romance, but a promise that ash will not stay forever private while I demanded your pier honesty. Soft rebuild of a different kind—distance with teeth. If you stay bittersweet, ash still waits for earning. Both temperatures are love. Both temperatures are cost. Neither temperature baptizes bone."

"Pick the verb," Will whispered. "Leave free—or stay bittersweet. Hurt to leave either. Good."

Fog horns spoke. Salt stung. Renny's pointed finger still lived in the geography of the east dock. Choosing leave meant packing freedom Will would respect even while wanting. Choosing stay meant holding unfinished anniversary weather on purpose while science stayed careful and romance became a vow the law did not recognize. Neither spent Renny early. Will waited with the patience of a man who had waited out worse rooms—rooms his dark past still stained—if Ellison's quiet cruiser meant anything. He did not fill the fog with comfort. Attention as a blade laid flat, edge available as tenderness and as release. [player_name] drew a breath that tasted like rust and soap and unfinished trust, and felt the next ending arrive on the sound of a pier dawn and a choice that still refused to christen bone.`,
  textHot: `Dawn on Harborwick Pier arrived like unfinished fucking weather—fog horns, salt, rusted chain-link, festival lantern ghosts—and [player_name]'s cunt answered William Akers's truth-proposal with a filthy pulse she refused to tidy on the boards where Renny had pointed east.

Will stood mid-thirties, scar nick pale under grey morning, cracked notebook drinking mist, brutal charm banked for honesty that was not a ring. Grey-green found the water and then found her—mid-twenties, thighs tight, charm gap aching, Renny's living link. Cho careful: remains unidentified, charm maybe. Ellison's cruiser idled without lights. Science careful. Hope employed. Dread armed. Soft expensive as pier fog. Attraction pressed stupidly: soap-and-salt, unfinished almost-kisses from rain and hospital and festival crates, the hard line of his cock under wool he did not apologize for while offering her a door.

"Answer the boards," Will said, voice sex-rough under detective flat. "Leave Harborwick free—I respect the freedom. Pack the kept detail. Walk cities that do not know Warehouse C by smell. I stay with the case. I do not chase your freedom into obstruction—and before you go I fuck you against this piling until goodbye is just how hard you clench while fog horns speak." His cracked knuckles brushed hers, then shoved into her jeans under cotton without preamble; she was soaked; two fingers slid into slick heat. "Or stay in the fog—bittersweet pier—anniversary unfinished promise, hard sentences on these planks—and I finish you quiet enough for festival ghosts after every honest noun, truth as proposal without a wedding, my mouth writing jewelry the law does not recognize."

[player_name] gasped on his hand, forehead to his, copper and salt and want. Leaving tasted like survival and sanding with prettier luggage. Staying tasted like loyalty and drowning on purpose. Mid-thirties to mid-twenties—close enough to burn.

"If I leave," she managed, rocking, "I choose air over the braid."

"Yes." Honest. Comfort refused. He pumped slow, filthy, precise, thumb on clit. "Hate it and respect it in the same breath. Respect is not not-wanting. Wanting you is not a warrant for your geography." Late smile wrong and fond—weapon and wound learning how to let go without abandonment theater. "If you stay, you choose bittersweet on purpose. Unfinished. Softest hard. Reciprocal teeth—and I keep my cock aching through every hard sentence until you pick, because unfinished is how your body tells truth."

Nina Solis stayed sealed—hint, flinch, Ellison side-eye from the lot—not a sealed-file striptease for lantern romance. Teeth. Whole mouth later.

He walked her deeper into a crate pocket out of cruiser angles, dropped to a crouch despite Ellison's caution, despite Solis ash humming under carnival sugar memory, and yanked her jeans down far enough to put his mouth on her—tongue flat, then pointed, sucking her clit with warrant precision. She clapped a hand over her mouth. Whitened knuckles braced her thighs. "Leave free and I do this as goodbye that respects the door," he growled against wet heat. "Stay bittersweet and I do this after every hard sentence you give me on these boards—fog horns as cover, Renny's poster as third judge, my tongue writing a better story than any memo about proximity." He slid two fingers into her while he licked; she came shaking, vision white. Will stood, wiped his mouth like a statement, pressed his forehead to hers. Cock strained, unfinished, deliberate denial. "Solis sealed. Bones unnamed. What does not stay unfinished is the verb—leave or stay—before the ballad dies and soft gets more expensive."

[player_name] tasted herself on the air between them. "Renny kept a map," she said. "I kept a lie. You kept a sealed hallway. Everybody keeps something." She put his palm back between her thighs—claiming, demanding. "Leave—I take freedom you respect and still soak for the goodbye. Stay—I hold unfinished pier weather and you repay me until bittersweet tastes like sweat. I am not inventing purity. I am not inventing a funeral. I am asking which hurt leaves Renny reachable while you can still feel how wet dawn makes me."

Will cursed soft, curled once, stopped—exact, cruel, tender as a threat—withdrew to paint her lower lip. "Not yet. Not until you pick." Grief and sex sharing a body. Bones unnamed. Science careful.

"Clock," he said. "Leave Harborwick free—I respect it—or stay in the fog—bittersweet pier. Either way the boards remember her. Either way Cho's pending stays a leash. Conjugate while I can still smell your cunt on my hand under morning grey and Harborwick fog erases the curb."

He braced both hands on the crate beside her head and rolled his hips once against hers—slow, deliberate, promise with a pulse—so she felt exactly how unfinished dawn left him. "If you leave free, I will stand on these planks after smelling like your decision and respecting the door even while my cock aches," he said, voice raw. "If you stay bittersweet, I will spend every hard sentence aching and every after-minute inside this fog pocket making you invent new ways to stay quiet while Ellison's cruiser invents our posture." Cracked knuckles brushed her jaw. Rain ticked lantern ghosts. Fog horns spoke. "Either verb keeps Renny a pointed finger and Cho's bones unnamed. Either verb leaves Solis sealed tonight. Neither verb lets me pretend I am clean. Pick, [player_name]. The boards are waiting. So is my mouth. So is the inland free."

Rain thickened. Will paced once—counting exits, counting what freedom cost—and boxed her against plywood out of camera angles, put her hand on his cock through his pants once, let her feel the unfinished claim. "Leave means goodbye-shaped repayment and then a suitcase I do not chase. Stay means unfinished anniversary fucking braided into hard sentences until honesty is how hard you clench. Verb. Now. Leave Harborwick free—Will respects it. Or stay in the fog—bittersweet pier. Hurt to leave either. Teeth. Consequence. No baptism—just us, a vow that is not a wedding, boards that remember her, science still careful, and a choice that might still save what Harborwick failed once—or free you from the city that spent her."

[player_name] stood between festival noise-memory and harbor fog, wet jeans, remains unnamed, charm probable—and the choice sitting between them like unfinished fucking: leave Harborwick free with Will's respect as the last gift, or stay in the fog for a bittersweet pier promise while Solis ash stirred without a full dump and Cho's pending still refused to soothe anyone.

A vendor's generator coughed. Will laced their fingers hard enough to hurt and steered her one step back toward the posters—Renny's unfinished smile looking at them like a third judge. Before the cruiser's angle improved, he walked her into the deepest crate shadow and shut the plywood gap with his shoulder. He freed himself enough to smear the head of his cock through her folds without entering—hot, blunt, cruel, painting her while fog horns spoke and Ellison invented distance. Discipline as filthy as any thrust. "I will not fuck you full in open pier fog with a unit number watching," he said, voice wrecked. "I will make you choose while you drip on a detective who offered freedom instead of a cage and still wants inside you more than he wants Ellison's quiet to look like permission."

He pumped two fingers back into her in time with nothing but want, forehead to hers, scar nick white. "Leave free and this is the last slick I take with respect intact—suitcase weather, inland air, my taste as goodbye you are allowed to keep. Stay bittersweet and I do this after every hard sentence until unfinished anniversary is just how your cunt remembers honesty." He curled until her hips jerked, then stopped again—denial as vow. "Solis stays sealed. Bones stay unnamed. Your Owen weather stays yours until you choose a page. What does not stay unfinished is leave-or-stay before soft gets expensive enough to invent funerals."

Rain needled the lantern ghosts. [player_name] pictured packing with his come still imagined on her thighs—freedom Will would respect even while aching. She pictured staying on the boards with his mouth as jewelry—bittersweet, Renny's poster, science careful. Either fantasy made her wetter. Either path kept Cho from christening bone for the sake of a tidy dawn.

"If you leave," Will snarled soft, "I will still want your mouth in every warehouse after and I will not get to have it on demand—want does not cancel respect, and respect does not invent Renny on silt. If you stay, I will still be angry at every cooled trail and still fuck the leftover fog out of you—anger does not cancel the braid. I need both sentences without comfort while your thighs shine and Ellison's cruiser pretends not to invent our posture and Solis ash stays a tooth I will not dump for free."

"Pick," Will whispered, late smile cutting wrong. "Leave free—or stay bittersweet. I am still tasting you. That is not in any memo yet. Keep it that way until you choose which ending gets our next hour—freedom inland with respect as jewelry, or boards with honesty as the only ring while hope keeps its impossible job beside dread."`,
  choices: [
    { id: "scene10c", text: "Leave Harborwick free — Will respects it", textHot: "Leave Harborwick free — Will respects it" },
    { id: "scene10j", text: "Stay in the fog — bittersweet pier", textHot: "Stay in the fog — bittersweet pier" }
  ]
};
