export default {
  id: "scene7d",
  layer: 7,
  title: "Case-only streak breaks — want returns mid-briefing",
  text: `The precinct briefing room smelled like burnt coffee and dry-erase ghosts—Harborwick's official weather, fluorescent and unkind. [player_name] sat in the chair William Akers had angled toward the whiteboard instead of toward Captain Mara Ellison's empty head seat, a small rebellion of furniture that felt like a hand at the small of her back. Case-only had been their streak for days: maps, timestamps, Owen Vale's crackling alibi, Dr. Lila Cho's careful *pending* on unidentified upriver remains. No mouths. No almost-kisses finished. Want banked under procedural pressure like a coal they both pretended had gone cold.

It had not gone cold.

Will stood at the whiteboard with his cracked notebook open, charcoal sleeves rolled, scar through his left eyebrow catching the ugly light. Mid-thirties. Sleep-deprived. Brutal charm filed down to briefing grammar—velvet sheathed—while he walked [player_name] through Warehouse C's midnight window, clerk initials *M.K.*, Renny's journal marks, the second-victim pattern Cho had floated without christening anyone's sister. Renny—teenager when she vanished, missing seven years—was still not confirmed among the dead. Charm that *could* match. Lab pending. Hope and dread shared the briefing chairs. Will treated the ambiguity as sacred, which was one of the reasons attraction kept climbing [player_name]'s mid-twenties throat even while she tried to be only a familial contact with a kept secret and a pulse.

"Ellison wants a flip-or-charge posture on Owen by end of week," Will said, marker squeaking. "She also wants distance between me and you that looks like professionalism on paper." His grey-green eyes flicked to [player_name]'s mouth—too long—then back to the board. "I am giving her the board. I am not giving her the distance. That is already a problem. Say something case-shaped so I remember why we are here."

[player_name]'s throat worked. Rain freckled the high window. Somewhere down the hall a radiator knocked like a second interrogation clock. Pier fog pressed the glass as if the river had followed them indoors. She tasted copper where she had bitten her cheek to keep from saying his name like a prayer. Case-only had been her choice on an off-record night—intimacy refused, map on the floor, hands clean of each other's skin. The refusal had not killed the want. It had fermented it. Sitting in fluorescent light with Will's rolled sleeves and cracked knuckles and the Solis-bruise silence still living in his shoulders when Ellison almost named a partner, [player_name] felt the streak crack from the inside.

"Cho's pattern means the clerk is not optional," she said, voice holding. Case-shaped. Barely. "Renny's journal and the letter's second-girl line match the tool signature talk. Widening keeps hope from collapsing into one rumor corpse. Burning focus keeps Renny's name sharp enough to cut. Both doors still open. Both hurt." She stood without meaning to, closing half the distance to the whiteboard, and Will went still the way he went still at crime scenes—attention as a blade laid flat. Mid-thirties to her mid-twenties—close enough to burn. Soap, salt, scrubbed-dark past filled the small space between briefing table and board. "I cannot do case-only for another hour while you write *M.K.* like it is not also the shape of your mouth when you are trying not to look at me."

Will set the marker down carefully, as if it might bruise. "There it is," he said softly. Not triumph. Recognition. Velvet-blade hunger banked hard under fluorescents that did not deserve their heat. "Want returns mid-briefing. I felt it when you angled that chair. I felt it when Cho's name made you lean. I have been conducting myself like a man who can live on maps. I cannot. Not with you in the room smelling like rain and the hoodie you will not stop carrying folded in your bag like a prayer." He did not touch her yet. Permission lived in the air like fog. "Ellison could walk in. That is not a joke. That is a timer."

[player_name] laughed once—ruined, quiet—and the sound made Will's jaw flex. "Then talk faster. Or stop talking." Attraction hummed unwanted and undeniable: his scar, his competence, the dangerous care of refusing to christen upriver bone with Renny's name because science had not. Dark past hummed under his badge—partner's fall, sealed IA, hallway he would not narrate in a briefing room. She wanted his steadiness and his mouth and the end of the case-only lie they had told their bodies.

Will's hand found the edge of the table beside her hip—not her hip, not yet—cracked knuckles pale. "Two doors from this streak breaking," he said. "We burn what would break him—burn the letter's sharpest edge, burn the part of this that makes Ellison's circus inevitable, burn the soft evidence that turns my chest into a liability while I am still trying to keep your sister's fate contested on purpose. Mercy or cowardice; ash will not label itself. Or we widen the case to the second victim—Cho's packet, Renny's pattern notes, the clerk's throat opened under daylight—while want stays on the table between us like a third exhibit we refuse to tag." "Either way, case-only is dead. Either way, I am done pretending my hands are only for markers."

Foghorn rolled faintly from the pier district, low enough to feel through the precinct's bones. Yellow tape ghosted in [player_name]'s memory. Renny's charm bracelet gap winked in her mind's eye upstairs across town. Cho's *pending* still held. Hope still had a throat. Dread still had teeth. The whiteboard's warehouse sketch looked like a wound drawn in blue.

[player_name] covered Will's hand with hers on the table edge—heat, claim, confession. "I refused you on the floor map," she said. "I am not refusing the want anymore. I am asking what we do with it while Ellison's timer runs and Renny's name is still a question."

Will turned his hand under hers and laced their fingers, brief and devastating under fluorescent honesty. "We use it as fuel, not as erasure," he said. "Grief and sex can coexist. We do not eroticize the river. We do not let want christen bone. We pick burn or widen—focus or chorus—and we walk out of this room having admitted the streak broke because honesty is the only soft edge I will still allow myself with you." He squeezed once and released, professional again by force of will, eyes still ruined. "Choose before she walks in. Choose while your pulse is still in my thumb."

Outside, Harborwick rain whispered on the precinct's high glass. Inside, [player_name] tasted burnt coffee and unfinished weather. Choosing burn meant triage—letter edge to ash, Renny central, Will's liability cooled enough to keep him on the case. Choosing widen meant opening Cho's second coastline into the next layer while their joined heat still ghosted on the table like evidence of a different crime: trust under interrogation lights, want returned mid-briefing, a detective and a sister of the missing refusing to pretend maps were enough.

The hallway footsteps that might have been Ellison paused, then turned away. Timer extended by luck or politics. William Akers watched [player_name] the way a man watches a fuse he has already lit with his own mouth's almost. Whatever she did next would either put cream paper toward flame for focus—or teach a cold-case detective that a broken case-only streak could widen a murder pattern and a romance in the same breath while unidentified remains waited upriver and a charm that was only *like* Renny's still waited for science to speak.

She thought of the pier festival fog, of Owen's too-calm morning, of an old partner as a name Ellison almost said, of Will touching his ribs like a bruise that never yellowed. The briefing room clock hummed. The marker smelled like school and warrants. [player_name]'s palms were damp. Want had returned. The doors were open. Both hurt. Will did not pretend otherwise, and that honesty was why her chest ached with something that was not only grief and not only hunger—something like the beginning of a partnership that could survive daylight if they chose which knife to sharpen first.

The marker's solvent smell clung to [player_name]'s fingers where she had touched the table near Will's hand. She paced once—briefing room too small for pacing, too full of whiteboard blue and Ellison's empty chair—and stopped at the high window where Harborwick rain needled the glass like a second witness. Pier district roofs hunched in fog. Somewhere out there Warehouse C waited with its midnight window and its sealed crates and its foghorn cover. Somewhere upriver Cho's lab held bone that was not yet a name. The case-only streak had been a kindness they had worn like a borrowed coat; mid-briefing, the coat was on the floor.

Will stayed by the board, giving her the window the way he gave her permission—space as care, care as pressure. "When I ran warrant work with a partner I will not name in this room," he said carefully, his sealed-file flinch without the full dump, "I learned what happens when you rush an entry to protect someone and the hallway fills with the wrong kid. I wear charm over that night like armor. I am telling you this much because want without context is just another lie, and I am allergic. I am not telling you the rest until Renny's file stops rhyming with my sealed one—or until you ask in a room that is not fluorescent." His cracked knuckles flexed. "Burning what would break me might mean burning the letter edge that makes Ellison smell fraternization and pattern circus in the same breath. Widening might mean putting that circus on a leash and aiming it at the clerk instead of at us. I can survive either. I cannot survive another hour of pretending your mouth is only for case facts."

[player_name] turned from the rain. Mid-twenties face open. Attraction and dread braided. "Renny kept a letter that says silence is worse," she said. "Case-only was a kind of silence. Soft. Professional. Cowardly in a pretty way. I am done with pretty cowardice." She crossed back to him, stopping close enough that the almost of his nearness lived under her ribs like unfinished weather. "If we burn, we keep her name the sharpest knife and we accept ash on our hands. If we widen, we let Cho's second victim into the light and we accept that hope gets louder and so does the city. Pick with me. Not for me."

The briefing room clock hummed like a third witness. Case-only had cracked the moment Will's attention returned to her mouth mid-sentence about sink weights. Burning what would break him meant protecting a sealed wound he still would not unpack—mercy that might also be obstruction. Widening to Cho's second victim meant feeding Ellison a larger map while Renny stayed a question on a lab tray. Rain needled the glass. William Akers waited with notebook open and charm scraped thin. [player_name] had to choose which honesty left the room first: the one that spared him, or the one that named a cousin silence upriver.`,
  textHot: `The precinct briefing room smelled like burnt coffee and dry-erase ghosts, and the air between [player_name]'s body and William Akers's was already too warm for case-only fiction. Fluorescents hummed. Will had angled her chair toward the whiteboard—small rebellion, hand-at-the-back energy without the hand—and every time he wrote *M.K.* on the board, [player_name]'s mid-twenties cunt clenched around nothing like the initials were a filthy stroke.

Case-only had been their streak: maps, timestamps, Cho's careful *pending*, no mouths finished. Want had fermented under the refusal until it felt like a second pulse between her thighs. Will stood with sleeves rolled, scar catching ugly light, cracked notebook open, brutal charm filed to briefing grammar while his grey-green eyes kept dragging to her mouth too long. Mid-thirties. Sleep-deprived. Hard line in his trousers half-hidden by the table and not hidden enough. When Ellison almost named Nina Solis, he had touched his ribs. The flinch still lived in his shoulders. Broken men should not be this hot under precinct light.

"Ellison wants distance that looks like professionalism," he said, marker squeaking. Voice low enough to stroke even when he tried for board-voice. "I am giving her the board. Not the distance. Say something case-shaped so I remember why we are here instead of why I want you on this table."

[player_name] stood, closing half the distance, rain freckling the high window, pier fog pressing glass. Soap, salt, scrubbed-dark past filled her nose. "I cannot do case-only for another hour while you write *M.K.* like it is not also the shape of your mouth when you are trying not to look at me."

Will set the marker down as if it might bruise. "There it is." Recognition, wrecked. "Want returns mid-briefing. I felt it when you angled that chair. I felt it when Cho's name made you lean. I have been conducting myself like a man who can live on maps. I cannot. Not with you smelling like rain and that hoodie in your bag and your pulse doing that thing in your throat I want to put my tongue on." He did not touch her yet. Permission fogged the air. "Ellison could walk in. Timer."

[player_name]'s laugh came out ruined. Wet heat gathered; fabric clung to her clit under the fluorescent honesty. "Then stop talking."

His hand found the table edge beside her hip—cracked knuckles pale—not her hip, not yet, denial as filthy metronome. "Two doors from this streak breaking," he murmured, close enough that coffee-breath warmed her cheek. "Burn what would break him—letter's sharpest edge, Ellison's circus fuel, the soft evidence that makes my cock a liability while I am still trying to keep Renny's fate contested on purpose. Ash will not label mercy or cowardice for us. Or widen to the second victim—Cho's packet, pattern notes, clerk's throat in daylight—while want stays on this table like a third exhibit I refuse to tag because tagging it would mean fucking you against a whiteboard before Cho finishes saying *pending*." His free hand finally covered her hip, palm flat, heat shooting straight between her legs. "Either way, case-only is dead. Either way, I am done pretending my hands are only for markers."

She covered his hand and pressed it harder—claim, confession—and felt him hard against her through too many layers of precinct clothing when she shifted closer. Mid-twenties. Mid-thirties. Close enough to burn. Renny still unnamed among upriver remains. Charm still only *like*. Hope still had a throat. Dread still had teeth. Will's thumb stroked once at her hipbone under the table's sightline—filthy, brief.

"I refused you on the floor map," [player_name] whispered. "I am not refusing the want anymore. I am asking what we do with it while your captain's timer runs and my sister's name is still a question and I am this wet from watching you hold a marker."

Will's forehead touched hers—not a kiss, a brand of restraint that made her cunt clench. "We use it as fuel, not erasure," he said against her mouth without taking it. "Grief and sex can coexist. We do not eroticize the river. We do not let want christen bone. Burn or widen—focus or chorus—and we walk out having admitted the streak broke because honesty is the only soft edge I will allow myself while I can still smell how ready you are." He squeezed her hip and released by force of will, eyes ruined, cock visibly denied. "Choose before she walks in. Choose while your pulse is still in my thumb. I could put you on this briefing table and fuck the case-only lie out of you until you forgot Ellison's name. I will not. Not under these lights. Not while remains stay unnamed on purpose. Later has teeth. I am already biting it."

Hallway footsteps paused, turned away—timer extended. Foghorn rolled faintly from the pier. [player_name] tasted copper, tasted him, tasted unfinished weather. Choosing burn meant triage with ash and his hands in the smoke afterward. Choosing widen meant opening Cho's second coastline while their joined heat ghosted on the table like evidence of trust under interrogation lights. Both doors throbbed.

Outside, Harborwick rain whispered on high glass. Inside, [player_name]'s cunt ached unused and honest, want braided into briefing grammar until she could not tell if she was breaking a streak or opening a case and herself in the same breath for a detective with a past he would not speak and a hunger that made *liability* taste like foreshadowing. The whiteboard's Warehouse C sketch looked like a bruise drawn in blue. Renny's fate stayed contested. William Akers waited—badge and man and almost-mouth.

She almost said his name like a prayer and swallowed it into a choice instead, thighs pressed slick under fluorescents that did not deserve how ruined she was from proximity and truth alone, while unidentified remains waited upriver and a charm that was only *like* still waited for science, and Will's cracked knuckles rested empty on the table edge where her hand had been—waiting to be filled by a decision that would hurt and still leave her wanting him after.

The marker's solvent smell clung to [player_name]'s fingers like a cheap perfume she wanted Will to lick off. She paced to the high window—rain needling glass, pier roofs in fog, Warehouse C out there somewhere with its midnight sins—and felt Will's eyes on her ass, her throat, the place between her shoulder blades where want lived like a brand. Case-only coat on the floor. Mid-briefing heat climbing her spine.

"When I ran warrant work with a partner I will not name under these lights," Will said from the board, voice rough, his sealed-file flinch without the full dump, "I learned what rushing costs. I wear charm over that night. I am telling you this much because fucking you without context would be another lie, and I am allergic—also because hearing me say it makes you wetter, and I can see it in how you hold your shoulders." Brutal honesty as stroke. [player_name]'s cunt clenched; she pressed her thighs together and hated how right he was. "Burning what would break me might mean ash on the letter edge that makes Ellison smell my cock in your case file. Widening might aim the circus at the clerk while I still get to put my mouth on you after the packet lands. I can survive either. I cannot survive another hour of pretending your mouth is only for case facts when I want it open on my name."

She turned from the rain, crossed to him, stopped close enough that his hard-on brushed her hip through cloth—accident, not taken back, reciprocal ruin. Mid-twenties. Mid-thirties. Close enough to burn. "Renny wrote silence is worse," [player_name] whispered. "Case-only was pretty cowardice. I am done. If we burn, ash on our hands and your fingers in my hair after. If we widen, Cho's second victim in the light and your mouth on my throat in the stairwell because we will not make it to a bed before the want finishes what this briefing started."

Will's forehead dropped to hers again. "With you," he said against her lips without taking them. "Always the verb with you." Thumb at her hipbone under the table line, filthy metronome. "Burn what would break him—or widen the case. Focus or chorus. Ash or daylight. I will still be hard for you after. Want is not the vote. Renny's contested name is. Choose before Ellison's luck runs out and these fluorescents get a witness we cannot fuck our way past."

Hallway empty. Clock humming. Foghorn faint. [player_name]'s pulse in his thumb. Unidentified remains still unnamed. Charm still only *like*. Hope and dread and arousal sharing the briefing air like co-counsel who had finally stopped pretending the streak was alive. William Akers waited—scar, cracked knuckles, denied cock, sealed past humming.

Will's hand found the inside of her knee under the table once—promise, not payment—and withdrew before Ellison's hallway footsteps could catch them. "Burn the thing that would crack me," he said low, "or widen the board until Cho's whisper has company. Either way you are fucking the case-only lie dead." His boot stayed against hers. Her nipples tightened under the blouse she had buttoned for professionalism. Later still had teeth. She was already biting back.`,
  choices: [
    { id: "scene8d", text: "Burn what would break him", textHot: "Burn what would break him" },
    { id: "scene8e", text: "Widen the case to a second victim", textHot: "Widen the case to a second victim" }
  ],
};
