export default {
  id: "scene7b",
  layer: 7,
  title: "Withheld letter: Will finds it anyway",
  text: `Rain needled Harborwick's warehouse glass after midnight, a thin metallic hiss that made [player_name]'s apartment feel smaller than grief. The lockbox sat emptied on the coffee table—journal photocopied under William Akers's careful seal, USB imaged, pier map photographed—everything except the cream envelope she had slid into the kangaroo pocket of Renny's old hoodie three hours ago and told herself was still protection. *For [player_name] — only if.* The cotton held the letter against her hip like a second pulse. Precinct coffee had gone cold on the counter. Burnt bitterness. Will's cracked notebook lay open beside the map copies, pen uncapped, waiting for a truth she had promised full cooperation and then edited with her body.

Will stood in the kitchen doorway with rain still darkening his hair, charcoal shirt clinging where Harborwick damp had found him. Mid-thirties. Scar cutting his left eyebrow. Grey-green eyes that had tracked the pocket all evening without naming the theft. Brutal charm banked low—velvet over a blade sheathed for a sister's last private page—but his allergy to lies made the air taste sharp. Captain Mara Ellison expected the journal packet by morning. Dr. Lila Cho's unidentified upriver remains still waited in careful language: age range that *could* fit Renny; a charm that *could* match the missing bracelet piece upstairs; lab ID pending. Hope and dread shared the couch cushions. The remains were not Renny until science said so. The letter might not care about science.

"You kept one thing," Will said quietly. Not accusation yet. Inventory. "I felt it when you closed the box. Soft edge on full coop. I said I would understand. Understanding is not the same as pretending I cannot see the shape under that hoodie."

[player_name]'s mid-twenties throat worked. Renny had been a teenager when she vanished—seven years of absence folded into vanilla ghost, silver gap, and this envelope she had sworn was mercy. Attraction hummed unwanted under procedural pressure: Will's cracked knuckles pale against the doorframe, the sleep-deprived set of his shoulders, the way he watched her the way a man watches a fuse. Mid-thirties to her mid-twenties—close enough to burn, far enough that the badge still felt like a different country. She wanted his steadiness and hated that she wanted it while the letter warmed her thigh.

"Only if," [player_name] said. Her voice held. Barely. "Renny wrote *only if*. I do not know if the *if* has happened. If Cho confirms. If Owen burns. If the chain Renny named in the journal turns out to have already—" She stopped. She would not invent a corpse because paper was dramatic. Will had taught her that refusal like a sacrament. "I told myself one scrap that is not yet evidence. That was half a lie. I was afraid of what she kept for me."

Will crossed the room. Foghorn rolled inland from the pier district—low, lonely—vibrating in the floorboards. He did not grab the pocket. He sat on the coffee table edge, knees bracketing hers where she perched on the couch, close enough that soap, salt, and scrubbed-dark past filled the space between them. When Ellison had almost named Nina Solis, Will had touched his ribs like checking a bruise that never yellowed. He did not explain now. Dark past hummed under his badge: a partner's fall, a sealed IA file, a hallway he would not narrate while a missing girl's letter still had a chance to stay private. Hint only. Teeth showing.

"Afraid she forgave you," he said. "Or afraid she did not. Or afraid she named the thing that makes you choose between family and a badge you are starting to trust against your better judgment." His mouth twitched—almost the velvet-blade smile—and died. "I am going to ask you to take it out. If you will not, I am going to ask whether I have permission to find it anyway—because Ellison's morning will include questions about whether full cooperation had a soft edge, and I will not lie to her about a letter I can feel from here. Permission is the difference between partnership and the kind of search I do with a warrant."

[player_name] stared at him. Rain freckled the window. Somewhere downstairs a radiator knocked like a second interrogation clock. The hoodie pocket pressed warm. Choosing to hand him the letter meant ending the last private weather Renny had trusted to cream paper. Choosing silence meant teaching a cold-case detective that some locks still belonged to family—and watching him decide whether to break them anyway with her half-consent.

"Find it," she heard herself say, and hated the relief in her own voice. "Find it anyway. I cannot hand it to you. I can let you take what I am too cowardly to give."

Will's eyes closed once—brief, wrecked—then opened. He reached slowly, telegraphing every inch, and slid his hand into the hoodie pocket against her hip. Heat of his knuckles through cotton. The envelope whispered free. He did not open it immediately. He held it between them like evidence and like grief, Renny's handwriting facing up: *For [player_name] — only if.*

"Cho still has no hard ID," he said, as if the reminder could cushion paper. "Whatever this is, it does not make those remains your sister. It makes her a girl who left you a conditional truth. We read carefully."

He waited for her nod. Then he opened the envelope.

Inside: one page, Renny's looping script, dated three days before the festival night. *If you are reading this, something went wrong and Owen is still explaining.* The letter named the smuggling chain in plainer language than the journal—Warehouse C, clerk *M.K.*, sealed crates under foghorn cover—and then the sentence that made [player_name]'s vision tunnel: *I saw him move a girl once. Not me. Someone quieter. If I disappear, do not let him tell you I ran. Ask William Akers if he still works Harborwick. Badges can be wrong, but silence is worse.* Renny had written Will's name years before Will had knocked on [player_name]'s door with a charm that *might* be hers. The universe's cruel coincidence—or Renny's research into who still opened cold files—landed like a hand on [player_name]'s sternum.

Will went very still. Pen did not scratch yet. "Second victim pattern," he said finally, soft. "Renny thought she saw another girl moved. That is not an ID on our upriver bone. That is a sister hunting a chain while she still had breath. We do not collapse them." His cracked knuckles whitened on the page. "Ellison will want this. The press would eat it. You—" His grey-green eyes lifted to [player_name]'s face. "—get to decide whether this letter becomes leverage in a captain's sealed room, or truth you read aloud somewhere that is not an interrogation table."

Attraction sharpened around competence and ruin both. [player_name] tasted copper where she had bitten her cheek. The letter trembled in Will's hands; or her vision trembled. Pier salt leaked through the cracked window. Renny's hoodie lay open on the couch arm like a body that was not a body. Hope still had a throat. Dread still had teeth. Charm upstairs still only *like*.

"Two doors from here," Will said. Voice low. Partnership verb. "We take this letter to Ellison as leverage—bargain seals, controlled drip, keep Renny's conditional truth from becoming a rumor corpse before Cho speaks, use it to force the clerk's name into a room with teeth. Or you read it aloud to me somewhere softer than this coffee table—bed, honesty, no captain yet—and we decide what becomes evidence after you have heard your sister's voice in your own mouth without fluorescent light stealing the vowels." He did not smile. Brutal charm's quieter twin: attention as a blade laid flat. "Either way, the soft edge is gone. Either way, I found what you kept. I will not pretend I am sorry. I am sorry it hurt. Those are different."

Fog pressed the glass. Chain-link rattled in the alley. [player_name] looked at Renny's handwriting until the initials blurred, then at Will's scar, at the his sealed-file flinch silence in his shoulders, at the man who had asked permission before he stole what she could not give. Choosing Ellison's leverage meant spending the letter like currency in a precinct that had failed Renny once. Choosing the bed-read meant trusting Will with grief and want braided into the same breath while unidentified remains waited upriver and a second victim pattern opened like a second wound that was not yet a name.

The foghorn answered from the river, low enough to feel in the bones. William Akers watched [player_name] the way a man watches a fuse he has already lit and is waiting to see whether she runs or stays. The letter waited face-up. The journal packet waited for morning. Whatever she did next would either walk Renny's last private page into a captain's bargain—or teach a cold-case detective that some truths needed a bed, a sister's voice spoken aloud, and the almost-trust climbing her throat like unfinished weather while Harborwick remembered everything except the official story.

The desk lamp threw yellow across cream paper until Renny's loops looked carved. Will had asked permission before he found what she kept; that patience was its own kind of pressure now. Ellison would turn the letter into leverage before breakfast if [player_name] handed it up. Reading it aloud in a bed that smelled like rain and burnt coffee would put the *only if* into his mouth first—intimacy as chain-of-custody. Chain-link rattled in the alley. Will waited without reaching for the page again. [player_name] had to choose which remembering became daylight: captain's tablet, or a detective's sheets.`,
  textHot: `Rain needled Harborwick's warehouse glass after midnight, and the air between [player_name]'s body and William Akers's was already too warm for an apartment full of emptied locks. The coffee table held journal copies, imaged USB, pier map—everything except the cream envelope she had slid into Renny's hoodie pocket against her hip, cotton warming the paper like a filthy secret. Precinct coffee burnt bitter on the counter. Will stood in the kitchen doorway, rain-dark hair, scar through his left eyebrow, charcoal shirt clinging, cracked notebook closed against a thigh that [player_name]'s mid-twenties imagination had already mapped without permission.

Want had no manners. The case had teeth. Both lived in her cunt like a second pulse.

"You kept one thing," Will said, voice low enough to stroke. Grey-green eyes tracked the pocket all evening. Brutal charm banked—velvet over a blade—but his allergy to lies made her nipples tighten under her blouse as if honesty were a mouth. "I felt it when you closed the box. Soft edge. I said I would understand. Understanding is not pretending I cannot see the shape under that hoodie—or the way you are shaking because the letter and I are both too close to your skin."

[player_name] perched on the couch, thighs pressed slick. Renny—teenager then, missing seven years—still unnamed among Cho's upriver remains. Charm that *could* match. Lab pending. Hope and dread fucking the same oxygen. Will crossed the room and sat on the coffee table edge, knees bracketing hers, soap and salt and scrubbed-dark past filling her nose until she had to part her lips to breathe him. When Ellison had almost said Nina Solis, he had touched his ribs—hint only. Broken men should not be this hot. He wore broken like cologne she wanted to lick off his throat.

"Find it," she whispered, ruined already. "Find it anyway. I cannot hand it to you. I can let you take what I am too wet and too cowardly to give."

Will's eyes closed—wrecked—then opened. He reached slowly, telegraphing, and slid his hand into the hoodie pocket against her hip. Knuckles brushed the soft join of thigh and pelvis through cotton; heat shot straight to her clit; she made a sound she could not swallow. The envelope whispered free. He held it between them, Renny's handwriting facing up, while [player_name]'s cunt clenched around nothing and his jaw flexed like he was biting down on the urge to replace paper with his mouth.

"Cho has no hard ID," he murmured. "This does not make those bones Renny. We read carefully. And if you need my hands steady—" He waited for her nod, then opened the letter with fingers that had just been warm against her hip, and [player_name] watched his mouth shape Renny's words while her body throbbed absurdly through grief.

The letter named the chain in plainer language—Warehouse C, clerk *M.K.*, Owen's lies—and the second girl Renny had seen moved. *Ask William Akers if he still works Harborwick.* Will went still. [player_name] felt the stillness in her own pulse, in the wet fabric clinging to her clit, in the unfinished almost of his nearness. "Second victim pattern," he said finally, soft and filthy with competence. "Not an ID. Do not let dread fuck you into christening bone." His free hand found her knee—palm flat, claim not yet sex. "Ellison will want this as leverage. Or you read it aloud to me in a bed that is not an interrogation table—your sister's voice in your mouth while I hold you open enough to hear it without fluorescent light stealing the vowels."

The honesty landed between her legs like a stroke. Mid-thirties detective. Mid-twenties sister of the missing. Close enough to burn. The hard line in his trousers was visible, denied, reciprocal. [player_name] stared at Renny's handwriting until it blurred, then at Will's scar, at the his sealed-file flinch silence, at the man who had asked permission before he stole what she could not give—and whose knuckles still ghosted on her hip like a brand.

"Two doors," he said, thumb stroking once behind her knee—filthy metronome. "Leverage with Ellison—sealed room, controlled drip, your body still aching against my restraint while we spend this letter like currency that might keep hope breathing until Cho speaks. Or read it aloud to me in bed—honesty, grief, want braided—while I taste the shake in your voice and do not fuck you until the page is finished, because Renny's conditional truth deserves a full hearing before my cock gets a vote." His laugh was velvet-blade and wrecked. "I should not say it like that. I am saying it like that because I can smell how ready you are from finding and being found, and I am choosing—right now—to keep my mouth on the case instead of on yours. Later has teeth. I am already biting it."

Fog pressed the glass. Pier salt leaked in. [player_name] tasted copper, tasted him, tasted the unfinished almost of his mouth an inch from hers over cream paper that had lived against her thigh like a second pulse. Renny's fate stayed contested. Charm still only *like*. Hope still had a throat. Dread still had teeth. The letter waited face-up between partnership and hunger.

"You are shaking," Will inventoried, wrecked. "Grief. Want. Relief that I took it. Shame that you wanted me to. All of it. I can feel all of it through your jeans." He leaned, kissed her forehead—not her mouth—firm, almost angry with restraint. "Choose the verb. Ellison's knife or my bed. Leverage or aloud. I will still want you after. Want is not the vote. The vote is whether Renny's last private page becomes a captain's currency or a truth you speak into my skin before daylight and warrants."

Outside, Harborwick's rain whispered on warehouse glass. Inside, [player_name]'s cunt ached unused and honest, want braided into the found letter until she could not tell if she was opening Renny's conditional truth or opening herself for a detective with a past he would not speak and a hunger that made Ellison's word *liability* taste like foreshadowing. Choosing leverage meant walking cream paper into a sealed office while Will's nearness promised later—after seals, after Cho's *pending*—a night where grief and sex could coexist without eroticizing the river. Choosing the bed-read meant trusting him with her sister's voice and her own shaking thighs, with want cooling into a bruise she would press, with the case map blooming around a silence that still smelled like her arousal and his restraint and the hoodie pocket his hand had emptied like a kiss that was also a warrant.

The foghorn answered from the river, low enough to feel in her clit and her bones. Will's grey-green eyes asked for a verb while his thumb kept time on her pulse. Whatever [player_name] did next would either spend Renny's letter as Ellison's leverage under partnership light—or teach a cold-case detective that some truths needed a bed, a sister's handwriting spoken aloud against his chest, and the almost-trust climbing her throat like unfinished weather while unidentified remains waited upriver and her body throbbed beside a man who had found what she kept and refused to invent a corpse because paper was dramatic.

She almost laughed and almost cried; the sounds lived in the same ruined place. Will set the letter carefully on the map copies as if paper could bruise, then cupped [player_name]'s face with both hands—calluses, cracked knuckles, heat—and held her there without kissing her, forehead to forehead, breath shared like a dirty secret the radiator must not catalogue. "I found you keeping," he whispered. "You found me asking. That is the closest thing to trust either of us has earned tonight. Do not spend it on Owen's comfort. Spend it on Renny's *only if*—and on whether that *if* means Ellison's sealed knife or my sheets and your voice shaking through every warehouse mark while I keep my cock out of the vote until the page is done."

[player_name]'s thighs parted a fraction without permission; his knee slid into the space like it belonged there. Wet heat smeared. She gripped his wrists and felt his pulse hammer against her fingers—badge and hunger synchronized. Mid-twenties. Mid-thirties. Close enough to burn. "If I read it in bed," she managed, "I will want you inside me before the last sentence. If I take it to Ellison, I will want your hand on my back in that office like a claim I have not earned."

"Both true," Will said. "Neither is the choice. The choice is which room gets Renny's conditional truth first—the captain's, or ours. I can be professional in Ellison's seal. I can be careful in a bed. I cannot be both kinds of careful in the same breath while you are this wet and I am this hard and Cho still says *pending*." He kissed the corner of her mouth—not full, a brand of restraint—and pulled back. The letter waited. The foghorn rolled. Harborwick did not care which door burned hotter. [player_name]'s cunt did. Will's grey-green eyes did. Renny's handwriting did.

[player_name] pressed her forehead to Will's and felt her cunt ache unused while the letter waited face-up between their hips. "Ellison before dawn," he murmured, "or you read every line into my mouth in a bed that already knows your smell." His hand spanned her waist under her shirt—heat, not yet claiming—and stopped short of her nipples on purpose. Cream paper. Rain on glass. A detective who found what she kept without pretending the finding was not also a claiming. She could feed the captain leverage, or feed Will Renny's conditional truth with her thighs open and the case still unfinished between them.`,
  choices: [
    { id: "scene8b", text: "Use the letter as leverage with Ellison", textHot: "Use the letter as leverage with Ellison" },
    { id: "scene8c", text: "Read the letter aloud to Will in bed", textHot: "Read the letter aloud to Will in bed" }
  ],
};
