export default {
  id: "scene7a",
  layer: 7,
  title: "Locked box: Renny's journal names the smuggling chain",
  text: `Dawn came up Harborwick's river the color of old bruises—purple fading to iron, fog still clinging to the pier warehouses as if night had refused to clock out. [player_name] sat at her kitchen table with Renny's cracked purple journal open under a cheap desk lamp Jake Akers had dragged in from the hallway, pages spread beside the pier map and the USB still wrapped in electrical tape. Precinct coffee cooled in two mismatched mugs. Burnt bitterness. The radiator knocked downstairs like a second interrogation clock that had learned their names overnight.

Jake stood at the window with his cracked notebook closed against his thigh, charcoal shirt wrinkled from the hours they had already spent translating a teenager's looping script into cold-case grammar. Mid-thirties. Scar cutting his left eyebrow. Grey-green eyes bloodshot and sharp. Brutal charm banked low—velvet over a blade sheathed for paper that could hang people—but every time Renny named a warehouse mark or a late-night initial, his jaw flexed like he was biting down on a worse year he would not narrate yet. When Captain Mara Ellison had almost said Nina Solis two nights ago, Jake had touched his ribs. The flinch still lived in his shoulders. Hint only. Teeth showing. He did not open that file in a kitchen that smelled like Renny's vanilla ghost and river damp.

"Read it again," he said quietly. Not a command. A partnership verb. "From the clerk's initials. Out loud. I want to hear if your voice catches on the same places mine does."

[player_name]'s mid-twenties throat worked. Renny had been a teenager when she vanished—seven years of absence folded into cotton, silver, and this journal that had spent those years under a bed like a second spine. Upriver, Dr. Lila Cho's unidentified partial remains still waited in careful language: age range that *could* fit; a charm that *could* match the missing bracelet piece still winking on Renny's desk upstairs; lab ID pending. Hope and dread shared the kitchen chairs like co-counsel who refused to leave. The remains were not Renny until science said so. Rumor had already tried to bury her. The journal would not help the burial. It named a chain.

[player_name] read. Renny's certainty was teenage and terrible: Harborwick Pier Warehouse C, midnight trucks that did not match any shipping board, a city clerk's initials—*M.K.*—scratched beside Owen Vale's late nights, a fear that sounded older than seventeen. *They move sealed crates when the foghorn covers the dock noise. Owen says it's overtime. Owen lies with his whole mouth. If something happens to me, ask [player_name] about the pier night. She saw him. She knows she saw him.*

The sentence landed like a hand on [player_name]'s sternum. She had kept Owen off the official statement. Renny had known. Renny had written the kept secret into purple leather as if sisters could be subpoenaed by ink.

Jake did not look away. He sat opposite her—close enough that soap, salt, and scrubbed-dark past filled the space between their knees—and opened the notebook at last. Pen scratched. Rain freckled the glass. Somewhere in the pier district a foghorn rolled inland, low and lonely, vibrating in the table legs. Attraction was a stupid animal to bring into a kitchen full of smuggling grammar, and it came anyway: the sleep-deprived set of his shoulders, the way he watched her mouth shape Renny's words, the dangerous care of refusing to christen upriver bone with a sister's name because Cho had not.

"Smuggling chain," Jake said, translating without stripping the girl out of it. "Evidence-tampering touch. Mid-level official. Owen's desperation as grease. Renny was not running from drugs the way Owen sold it. She was looking at Harborwick's throat." His cracked knuckles went pale against the notebook spine. "Ellison will want this on record before lunch. The USB imaged. The map photographed under seal. She will also want to know whether you are ready to stop being the soft place Owen hides behind."

[player_name] tasted copper where she had bitten her cheek. "If we go public with the journal—every warehouse mark, every initial—the chain gets daylight. Press. IA shadows. Whoever wanted Renny silent gets a reason to finish whatever they started, and Cho still has not told us whether those remains are hers." Hope still had a throat. Dread still had teeth. "If we bargain it privately with Ellison—controlled drip, seals, no front-page circus—we might keep Renny's name from becoming a rumor corpse before the lab speaks. We might also give Ellison leverage to bury the parts that stain her precinct."

Jake's mouth twitched—almost the velvet-blade smile, almost a joke about captains and clearance metrics—and died mid-breath. "I have buried things," he said, voice flat enough to cut. "I am allergic to watching someone else bury a kid's handwriting for politics. That is not the same as saying public is always justice. Public can also be a slaughterhouse with better lighting." He did not say his old partner. He did not say hallway. The dark past hummed under his badge like a second radiator. "Your call is not only about Owen. It is about whether Renny's investigation becomes a city spectacle while her fate is still contested bone and rumor—or a sealed knife Ellison holds while we decide who bleeds first."

Outside, chain-link rattled in the alley wind. Harborwick remembered everything except the official story. Inside, the desk lamp threw a yellow circle that made the journal's pencil Xs look like deliberate wounds. [player_name] thought of Renny's hoodie still folded upstairs, of the cream envelope they had already catalogued face-down—*For [player_name] — only if*—of Cho's careful refusal to christen bone. Full cooperation had opened the lockbox. Layer Seven demanded a verb with consequences: name the chain in daylight, or bargain it in a captain's office where seals could become silence.

Jake leaned forward. His scar caught the lamp. Mid-thirties to her mid-twenties—close enough to burn, far enough that the badge still felt like a different country. Attraction hummed unwanted and undeniable under procedural pressure: trust was the real plot, and trust right now tasted like burnt coffee and purple leather and a man who would not invent a corpse because paper was dramatic.

"Two doors," he said softly. "Make the journal public—walk Renny's smuggling chain into the light with my notebook as witness and Ellison forced to pretend she wanted daylight all along. Or bargain it privately—my badge as cushion, her seal as leash, your sister's handwriting as currency we spend carefully so hope still has room to breathe while Cho finishes speaking." His grey-green eyes asked for a verb. "Either way, Owen's name stops being a family whisper. Either way, I stay in this kitchen until you choose. I will not steal the decision. I will feel whatever lie you try to tell yourself about mercy afterward."

Fog pressed the glass. Pier salt leaked through the cracked window. [player_name] stared at Renny's looping script until the initials blurred—*M.K.*, Warehouse C, Owen's late nights—and forced her eyes to Jake's cracked knuckles, to the wound he wore as armor, to the the raid wound under his charm silence he still would not open. The USB waited like a held breath. The map waited like a second spine. Renny's fate stayed contested: not named, not buried, not safe.

Downstairs the radiator knocked again. Somewhere a truck hissed past on wet asphalt. Jake Akers—detective with a sealed silence and a smile that opened people—watched [player_name] the way a man watches a fuse he is not sure he should light. Choosing public meant handing Harborwick Renny's teenage certainty and accepting that daylight might kill the last soft maybe about the upriver remains before science was ready. Choosing the private bargain meant trusting Ellison's politics with a knife Renny had sharpened for her sister—and trusting Jake to keep the blade from becoming a burial tool.

The foghorn answered from the river, low enough to feel in the bones. [player_name]'s palms were damp against purple leather. Whatever she did next would either open the sister's kept investigation under partnership light the whole city could see—or teach a cold-case detective that some truths still needed a captain's sealed room, a controlled drip, and the almost-trust climbing her throat like unfinished weather while unidentified remains waited upriver and a charm that was only *like* Renny's still winked upstairs in a room that smelled like absence.

The lamp hummed. [player_name] turned another page and found Renny's hand getting smaller, tighter, as if the girl had been writing in a hurry between festival shifts and fear. A list of plate numbers. A sketch of a dock latch that did not match any tourist brochure. A note in the margin: *Ask Cho about the other girl*—crossed out, rewritten, crossed out again. Jake's pen paused. "Other girl," he repeated, soft. "Renny thought the chain had already taken someone. That is not an ID on our upriver remains. That is a pattern she was hunting while she was still breathing. We do not collapse those into one body because dread wants a shortcut."

[player_name] nodded too hard. The distinction mattered more than sleep. She had spent seven years collapsing hope into dread and dread into silence; Jake's refusal to invent a corpse felt like a hand under her elbow on a pier that still tilted. Attraction sharpened around competence the way salt sharpened blood. She wanted to lean across the table and put her mouth on the scar through his eyebrow—not as seduction, as gratitude with teeth—and she did not. The journal still needed a verb.

"Ellison already smells sandbagging on the pier night," Jake went on. "If we walk this in public, she loses the option to soft-pedal the clerk. If we bargain private, she keeps the option and we keep a leash that might choke Renny's investigation the second clearance metrics matter more than a teenager's pencil. I have watched a precinct choose metrics." His eyes flicked—his sealed-file flinch, hallway-adjacent, gone. "I will not pretend I am clean enough to lecture you on courage. I am only clean enough to tell you which door burns hotter."

[player_name] closed the journal on the USB as if paper could keep a secret from daylight. Jake's notebook waited open on the table, cracked spine toward her like a dare that wanted a verb. Public naming would put Renny's smuggling chain under cameras before Cho finished arguing with bone. A private bargain with Ellison would keep the knife quiet—and bind [player_name] to a captain who already distrusted family witnesses. The foghorn rolled inland. Jake's grey-green eyes did not soften. He only tipped the cream envelope's empty space with two fingers where the withheld letter had not been, and let the almost-trust in her throat decide which door Renny's handwriting deserved first.`,
  textHot: `Dawn came up Harborwick's river the color of old bruises, and the air between [player_name]'s body and Jake Akers's was already too warm for a kitchen full of a dead girl's grammar. Fog clung to the pier warehouses. Precinct coffee burnt bitter in mismatched mugs. Jake had dragged the desk lamp in from the hallway; yellow light found the scar through his left eyebrow, the sleep-deprived set of his mouth, the charcoal shirt wrinkled from hours spent close enough that [player_name] could smell soap, salt, and scrubbed-dark past every time she breathed.

She sat with Renny's cracked purple journal open, thighs pressed together under the table because want had no manners and the case had teeth. Mid-twenties. Pulse hammering in her throat and lower. Jake stood at the window first, cracked notebook against his thigh, then sat opposite her—knees bracketing hers, deliberate almost—and the contact shot straight between her legs before either of them pretended it was only about the map.

"Read it again," he said, voice low enough to stroke. "From the clerk's initials. Out loud. I want to hear where your voice breaks so I know where to put my hands if you need steadying."

Brutal charm banked for paper that could hang people—but his grey-green eyes dragged over [player_name]'s mouth, her throat, the rise of her breasts under her blouse, then forced themselves to Renny's looping script as if professionalism were a restraint he was choosing to keep on for the girl's sake. When Ellison had almost named Nina Solis, Jake had touched his ribs—hint only, partner, fall, sealed file—and the flinch still lived in his shoulders. Broken men should not be this hot. Jake Akers wore broken like cologne [player_name] wanted to lick off his pulse point.

She read. Renny's teenage certainty named Warehouse C, midnight trucks, clerk initials *M.K.*, Owen Vale's late nights, the pier night [player_name] had kept off the record. *She saw him. She knows she saw him.* The sentence landed in [player_name]'s cunt as much as her chest—shame and hunger and grief fucking the same oxygen while Jake's knee pressed warmer against hers. Upriver, Cho's unidentified remains still waited: charm that *could* match, lab pending, hope and dread sharing the kitchen air. Not Renny until science said so. The journal named a chain, not a corpse. Jake treated that distinction like sacrament, which somehow made [player_name] wetter.

"Smuggling," he translated, pen scratching, voice rough. "Tampering. Mid-level official. Owen as grease. Renny was looking at Harborwick's throat." His cracked knuckles brushed [player_name]'s wrist as he turned a page—heat, calluses—and she felt her nipples tighten traitorously against cotton. Wet heat gathered; fabric clung to her clit like a filthy secret the radiator's knocking must not witness. Jake's gaze flicked down—caught the flush at her throat, the parted lips—and the velvet-blade hunger flickered, banked hard because fucking over a missing girl's journal would be a desecration and also because he wanted it anyway.

"Ellison will want this before lunch," he murmured, mouth close enough that coffee-breath warmed [player_name]'s cheek. "USB imaged. Map photographed. Your call is whether Renny's chain gets daylight or a sealed knife in a captain's office." His free hand found the inside of her knee under the table—palm flat, not climbing yet, a claim that was not yet sex and already felt like the start of being opened. "Public means the city watches while Cho still says *pending*. Private means Ellison holds the blade and I hold you steady while we spend your sister's handwriting like currency. Either way, Owen stops being a whisper. Either way, I can feel how wet you are from across this table, and I am choosing—right now—to keep my mouth on the case instead of on yours."

[player_name] almost said his name like a prayer and swallowed it. Saying *Jake* over Renny's initials felt like inviting him into the sister's last private weather with his cock instead of his notebook, and she was not sure she had the right—only the need. She shifted; slick fabric dragged; a sound almost escaped. Jake's thumb stroked once behind her knee—filthy metronome—and his jaw flexed.

"You are shaking," he said. Inventory and wreckage both. "Grief. Want. Both. I can feel both through your jeans. That is a problem for my badge and a fact for my cock." The hard line in his trousers was no longer almost—visible, denied, reciprocal. "I could put you on this table beside the map and fuck the seven-year lock out of you until you forgot Ellison's name. I will not. Not on Renny's grammar. Not while Cho still says *pending*. But later is a word with teeth, [player_name], and I am already biting it."

The honesty landed between her legs like a stroke. She pressed her thighs together around nothing and felt how ruined she was from proximity and truth alone. Jake's hand left her knee as if the leaving cost him. He sat back. Mid-thirties detective. Mid-twenties sister of the missing. Close enough to burn.

"Two doors," he said softly, eyes on her mouth. "Make the journal public—walk the smuggling chain into daylight with my notebook as witness while I watch you strip truths I want to taste off your tongue for a press that does not deserve your shaking. Or bargain it privately with Ellison—my badge as cushion, her seal as leash, your body still aching against my restraint while we drip Renny's certainty into a room that smells like politics and burnt coffee." Thumb on her pulse now, at her wrist, counting. "I will feel whatever lie you tell yourself about mercy. It will make me hard and angry and careful with you in ways I should not catalogue. Choose."

Fog pressed the glass. Pier salt leaked in. [player_name] tasted copper where she had bitten her lip, tasted him, tasted the unfinished almost of his mouth an inch from hers over purple leather and a USB that might name the chain that wanted Renny silent. Renny's fate stayed contested. Charm still only *like*. Hope still had a throat. Dread still had teeth.

Outside, Harborwick's rain whispered on warehouse glass somewhere beyond the block. Inside, [player_name]'s cunt ached unused and honest, want braided into cooperation until she could not tell if she was opening Renny's investigation or opening herself for a detective with a past he would not speak and a hunger that made Ellison's word *liability* taste like foreshadowing. Choosing public meant handing the city Renny's teenage certainty while Jake's nearness promised that later—after seals, after Cho's careful *pending*—there might be a bed that was not this kitchen table, a night where grief and sex could coexist without eroticizing the river. Choosing the private bargain meant keeping the knife in a captain's sealed room while Jake's eyes tracked her mouth, while want cooled into a bruise she would press, while the case map bloomed around a silence that still smelled like her arousal and his restraint.

The foghorn answered from the river, low enough to feel in her clit and her bones. Jake's grey-green eyes asked for a verb while his thumb kept time on her pulse. Whatever [player_name] did next would either strip the sister's kept chain under partnership light the whole harbor could see—or teach a cold-case detective that some truths still needed a sealed office, a controlled drip, and the almost-trust climbing her throat like unfinished weather while unidentified remains waited upriver and her body throbbed unused beside a man who would not invent a corpse because paper was dramatic and would not invent a fuck because grief was holy.

The lamp hummed like a third pulse. [player_name] turned a page and Renny's hand got tighter—plate numbers, a dock latch sketch, a margin note about *the other girl* crossed out twice. Jake's breath caught. "Pattern," he said, and his thigh pressed harder against hers under the table, heat blooming where denim met denim. "Not an ID. Do not let dread fuck you into christening bone. Stay with me. Stay wet for the living problem, not the rumor corpse."

The vulgar care undid her. She made a sound—small, helpless—and Jake's hand returned to her knee as if her noise were a warrant. Fingers spread. Still not climbing. The denial was its own filthy stroke. "Ellison smells sandbagging," he murmured against her temple now, close enough that his lips brushed hair. "Public burns the clerk's cover. Private keeps Ellison's leash and my mouth an inch from yours while we drip truth like edging—slow, controlled, until someone comes apart." His laugh was velvet-blade and wrecked. "I should not say it like that. I am saying it like that because your pulse is in my thumb and your sister's initials are in my notebook and I have not fucked anyone since this case scraped me raw, and you are shaking like you want to be the first honest thing I touch."

[player_name]'s cunt clenched. She gripped the journal until the leather squeaked. Mid-twenties body betraying mid-twenties grief under a mid-thirties detective's attention. "I keep imagining," she admitted, voice ruined, "that if I choose wrong, Cho calls tomorrow and the remains become Renny and I spent tonight bargaining your cock against my guilt instead of her name."

Jake kissed her forehead—not her mouth—hard enough to feel like a withheld orgasm. "Public circus or private knife," he said against her skin, voice gravel. "I will still want you wet after either. Want is not the vote." His thigh pressed hers under the table until her cunt clenched around nothing; the USB's tape peeled in the lamp heat like a second pulse. [player_name] tasted coffee and his restraint and Renny's loops burning through paper. Daylight would make the chain a headline. Ellison's seal would make it a weapon they could still aim. She had to speak before his mouth forgot the badge and remembered only how ready she smelled.`,
  choices: [
    { id: "scene8a", text: "Make the journal public — name the chain", textHot: "Make the journal public — name the chain" },
    { id: "scene8b", text: "Bargain the journal privately with Ellison", textHot: "Bargain the journal privately with Ellison" }
  ],
};
