export default {
  id: "scene3a",
  layer: 3,
  title: "On the Record",
  text: `The interview room at Harborwick Precinct smelled like burnt coffee and old metal—table bolted through the floor, clock humming a thin electric nerve along the wall, one-way glass pretending to be a mirror and failing at the edges where the silvering had worn. Fluorescent light flattened everything it touched: the manila cold-file folder splayed open like a patient, the empty second chair angled toward the door, the damp line still darkening Jake Akers's coat where fog had followed them in from the pier district and refused to leave.

[player_name] sat because standing would have looked like flight. Mid-twenties felt suddenly younger under that light, and somehow older too—seven years of unfinished festival night sitting in her throat like a swallowed coin. Renny had been a teenager the last time anyone reliable saw her: sixteen, restless, silver charm bracelet already missing its tiny anchor by dusk. The file on the table did not say Renny was dead. It said *unidentified remains, upriver, partial, ID pending*. Hope and dread shared the bolted chair with her, knees pressed together hard enough to ache.

Jake took the seat across from her without hurry. Mid-thirties. Sleep lived under his eyes in bruises that looked earned in places paperwork did not name. Notebook spine cracked open in his hand like a mouth that never quite closed. He set a recorder between them and did not start it yet. That half-smile of his arrived first—easy, practiced, the kind that made people lean closer before they noticed the edge. Charm as weapon. Charm as wound. Not clean-cut. Never the kind of detective posters put on recruitment flyers. Attraction to him tasted like touching a live wire and calling it warmth.

"Formal interview," he said, voice soft enough to feel like a hand at the back of the neck. Soft was worse. Soft meant he had learned how to make danger wear manners. "Captain Ellison wants something she can stamp before the press invents a name for those remains. Dr. Cho still won't rush—age range broad, nothing locked, charm probability not gospel. Me?" His gaze flicked to [player_name]'s mouth, then to the place her pulse jumped at her throat, then away, deliberate as a touch. "I want the page you tore out seven years ago. We can put it on record gentle, or we can wait until Ellison walks in and makes gentle impossible."

The clock hummed. Somewhere down the hall a phone rang twice and died. Rain freckled a high window that showed only a slice of Harborwick grey. [player_name] wrapped her fingers around the paper cup he had given her—coffee burnt to bitterness, precinct-honest—and tasted diesel memory underneath the caffeine: pier salt, Renny's borrowed hoodie folded even now in a drawer at home, Owen's silhouette near the festival lights with someone who was not supposed to be there. She had accepted Owen's story that Renny ran off with friends. She had never put her stepfather at the scene in any statement that mattered. Protection, she had called it. The word tasted like rust and old pier chain.

Jake opened the cold file with care that looked like tenderness and functioned like a scalpel. Festival maps with grease pencil circles. Old tip sheets gone soft at the folds. A photocopy of Renny's yearbook smile that made [player_name]'s ribs tighten until breath came thin. He tapped a margin note in someone else's handwriting—*familial contact withheld nonessential detail*—and looked up through his lashes in a way that should have been illegal in a room with cameras.

"I know what withheld looks like," he said. Almost conversational. Almost a confession of his own, offered like bait. "Used to be better at leaving pages out than putting them back. Learned charm in places that don't put it on resumes. Badge taught me the other direction." A beat. The smile tilted, not kind. "Mostly. You don't have to like me to tell the truth, [player_name]. You just have to decide whether Ellison hears it first—or whether we shape it while we still own the temperature of this room."

She watched his hands while he spoke. Knuckles faintly mismatched, as if they had learned rooms that did not issue case numbers. A thin pale line near his thumb that was not a kitchen burn and not recent. He noticed her noticing and did not hide it. If anything, he let the silence stretch until the noticing became a kind of intimacy neither of them had consented to on paper—until [player_name] understood that Jake Akers collected other people's secrets the way some men collected scars, and that he carried a few of his own under the coat and the badge and the soft voice.

"Walk me through the pier night again," Jake said. He turned a page. The paper whispered. "Not the statement version. The version you rehearse when the fog horn calls and you can't sleep. Who did you see. Who did you protect. What did you keep because you thought love meant silence."

[player_name] spoke carefully at first—festival fog rolling in off the water like a soft lie, Renny arguing about staying out later, the missing charm already gone by dusk, the crowd swallowing teenagers the way Harborwick always had, lights smeared gold and sickly on wet boardwalk. Jake listened like a man who had been lied to by experts and still somehow preferred the sound of a near-truth to a clean fiction. He asked small questions that opened large doors. What color was the hoodie under the lights. Did Renny seem scared or angry or both. When did Owen say she had run off with friends—before or after [player_name] saw him near the pier with that other person.

The last question landed like a palm flat on a bruise she had spent seven years pretending was healed.

She had not put Owen at the scene in the official statement. Jake had not accused her of that omission in so many words—not yet—but the half-smile said he already smelled the shape of it. He leaned back, chair complaining, and steepled his fingers in a parody of patience that somehow still made her pulse climb into her mouth. Behind him, the one-way glass held Ellison's possible attention like a held breath. He did not fully turn his back to the door when he glanced that way—old habit, wrong-room habit, the stance of a man who had survived places where doors meant more than exits. Something like a partner-flinch crossed his face and vanished—sealed history, not for this tape.

"Ellison's on the floor," he murmured. "I can hear her heels when the hall goes quiet. She'll want clearance language. Remains unidentified. Charm *like* Renny's. Case revived, family cooperative, no hard ID to bury a sister under." His eyes returned to [player_name], darker, hungrier in a way that was not only professional. "Or she'll want a witness who obstructed her own sister's file. Your call how close to confession we get before that door opens."

Rain thickened on the high glass. The recorder sat between them, still dark, a dare with a red light waiting. [player_name] felt Renny's absence like a third person in the room—not a corpse, not a confirmed name on Cho's slab, just a teenager who had walked into festival fog and never walked out. The upriver remains could be her. They could be someone else's missing child wearing a charm that wanted to be an anchor. Science had not spoken. Rumor had. Jake refused both extremes; he lived in the knife-cut middle and invited her there with him.

He did not plead. Jake Akers did not plead. He offered the dangerous kindness of a man who could make cooperation feel like desire and confession feel like the only way to stay in the room without drowning. The half-smile returned, softer and somehow crueler for the softness—brutal charm worn like a second badge.

"I won't hate you for protecting someone," he said. "I might hate you for making me dig it out of you while Ellison watches through glass. Lean toward the truth with me now—before the captain walks in—and we still own what goes on that tape. Call a lawyer mid-interview and shut the drip, and I do this the hard way. Both hurt. Only one leaves us something to build on after the fluorescents quit humming."

She could still taste festival sugar on the memory of that night—cheap, sticky, the kind Renny had loved—and under it the sharper taste of knowing she had chosen Owen's story over the silhouette her own eyes had kept. Jake did not rush the silence that followed her careful answers. He let it work. Men with clean pasts rushed; men who had survived uglier rooms knew what quiet could extract. [player_name] hated that she found the patience magnetic. Hated that brutal charm could look like care when it wanted something.

"Owen," Jake said once, just the name, soft as a bruise pressed for color, and waited to see whether she would flinch onto the record or away from it.

The clock's hum climbed. Footsteps approached down the corridor—heels, authority, Captain Mara Ellison's cadence like a verdict deciding whether to enter. Jake's hand hovered near the recorder without pressing record, giving [player_name] the last inch the way some men offered a kiss: heat without demand, choice with teeth under it, mid-thirties danger sitting very still across a bolted table.

Hope that the remains were not Renny still lived in her chest. Dread that they might be lived there too. Neither answered the question of what she had kept about Owen and the pier. Only her mouth could do that—and the door was almost open, and Jake was watching her like a man who already knew which way her body wanted to fall even if her loyalty had not caught up.`,
  textHot: `The interview room found [player_name]'s body before it found her manners—burnt coffee thick in the sinuses, metal table leaching cold through her sleeves until her skin pebbled, fluorescent light so flat and merciless it made her nipples tighten under her shirt for no decent reason the camera could cite. Clock humming like a second pulse against her collarbone. One-way glass pretending innocence while she felt watched anyway. Jake Akers across from her with rain still darkening his coat at the shoulders and that half-smile that was not clean-cut anything: charm as a blade he knew how to put against a throat and call a kindness.

She sat. Mid-twenties under lights that made confession feel like undressing one button at a time. Renny's teenage absence sat in her throat hot and unfinished. The file said unidentified remains, partial, ID pending—not Renny confirmed, not hope murdered on arrival. Jake set the recorder between them and left it dark on purpose. His soft voice did more damage than shouting; it lived low enough to feel against the inside of her wrist, against the seam of her jeans, against the place want was already gathering shameless.

"Formal interview." He said it like a filthy promise wrapped in procedure. Mid-thirties. Sleep bruised under his eyes. Notebook cracked open. Gaze dropping to her mouth, her throat, the jump of her pulse, the rise of her breath against her shirt, then climbing again as if he had already mapped where she would come apart if he asked the right way. "Ellison wants a stamp before the press names those bones. Cho won't rush—age range broad, charm not gospel. Me?" A pause that stroked. "I want the page you tore out. We put it on record gentle—or Ellison walks in and gentle dies screaming."

Coffee trembled in her paper cup. Pier memory rose through her cunt before it reached her head: salt on the tongue, Renny's hoodie, Owen's silhouette, the lie swallowed like a sacrament that left her wet with guilt years later for reasons she refused to examine under fluorescents. Jake opened the cold file with hands that had clearly known worse rooms than this—knuckles mismatched, a pale line near his thumb he did not bother to hide when her eyes caught it. When she stared, he let her look. Let the looking become heat. Intimacy without permission. Danger wearing a badge and a smile that had learned its work in places resumes never listed.

"I know what withheld looks like," he murmured. Almost a confession. Almost a come-on. Almost both, which was worse. "Used to leave pages out better than I put them back. Learned charm where charm was a weapon and a way out. Badge corrected some of that." The smile tilted—weapon and wound, brutal, not boyish. "Not all. You don't have to like me to tell the truth. You have to decide if Ellison hears it raw—or if we shape it while your mouth is still mine to listen to."

Walk-through questions became friction under his attention. Festival fog. Missing charm. Renny angry or scared. When Owen claimed she ran—before or after [player_name] saw him near the pier. Each careful answer left her thighs pressed tight under the bolted table, heat pooling shameless while grief sat in the same body and refused to leave. Jake leaned in until burnt coffee and rain-on-skin filled her head, until soft felt like fingers at the nape, until the interview chair might as well have been a bed she was refusing to name out loud. She wanted, traitorously, to know what that pale line on his thumb would feel like drawn along her lower lip. She wanted his cracked notebook closed and his mouth open. She wanted the recorder to stay dark forever and also to catch every dangerous syllable so she could replay the sound of him wanting the truth out of her.

"Ellison's on the floor." He glanced toward the door without fully turning his back—old wrong-room habit, the stance of a man who had survived before the badge taught him to pretend doors were safe. For half a second his eyes went somewhere else—a raid hallway, a kid who should not have been there, a name like Solis almost shaping his mouth before he killed it—and then the detective was back, sealed as any IA folder he would never open for her tonight. The habit made something low in [player_name] clench. Attraction that tasted like danger. Wanting the detective who could ruin her family with a sentence. Wanting to be ruined a little, if she was honest, by the way he looked at her omissions like a man undressing a locked drawer. "Clearance language—remains unidentified, charm *like* Renny's—or a witness who obstructed. Your call how close to confession we get before that door opens."

[player_name] felt wet heat that had nothing tidy to do with fear. Her pulse lived between her legs now, shameless, answering his soft voice like a filthy yes. He hovered a hand near the recorder's red light without pressing—offering the last inch like a kiss with teeth under it, mid-thirties hunger held in check by procedure and something darker that liked the check.

"I won't hate you for protecting someone," Jake said, voice low enough to fuck without touching. "I might hate digging it out while Ellison watches through glass. Lean toward confession with me now—before she walks in—and we still own this heat. Put Owen on the pier with your mouth while the tape can still be ours. Call a lawyer mid-interview, shut the drip, and I do it hard—and hard includes how I look at you after." Both options hurt. Only one left a path where his hands might eventually translate this interrogation into something that belonged in a bed instead of a bolted room. "Both hurt. Only one leaves us something to put honesty into later—mouth, hands, whatever you'll let me use when the fluorescents quit."

She thought of Renny's hoodie folded soft at home and hated that grief and arousal could share a ribcage. Jake turned another page; the whisper of paper sounded like sheets. "People who keep secrets recognize each other," he said, almost idle, and the recognition slid through her like a finger along wet skin. He did not dump his past on the table. He only let her feel the shape of it—doors, charm-as-exit, knuckles that had settled arguments badges later pretended to civilize—and the not-knowing made her want him more, which was its own kind of trap.

[player_name] crossed her legs harder. Useless. The pressure only named what the room had already done to her. When he asked again about Owen near the pier, her answer came half-voiced, breathy, and Jake's eyes went darker as if her tone were evidence he wanted to taste. He set his pen down. The click was filthy in its restraint. Outside the high window Harborwick rain kept time with the clock. Inside, the bolted table might as well have been the narrow width between two mouths deciding whether to break.

"Last chance to own the drip," he whispered, leaning close enough that she could have counted the sleep-bruises under his eyes, close enough that his breath warmed her lower lip. "Confession with me—or a lawyer's name between us like a locked door. Choose before Ellison takes the choice out of your mouth."

Footsteps in the corridor—Ellison's heels, verdict approaching like cold water. The remains still unnamed. The charm still only *like*. Hope and dread sharing [player_name]'s cunt-tight pulse with raw want for a man whose charm was a scar he smiled through. Jake's eyes held her as if the next word from her mouth would decide whether he ever touched her outside this room—and as if he already knew her body had voted, even if her loyalty was still catching up.

His knee bumped the table leg when he shifted—small contact, accidental only if she pretended—and the jolt traveled up her thigh into the ache she was done pretending was only grief. Seven years of silence had not prepared her for wanting a detective mid-confession. Jake Akers was not a safe harbor; he was Harborwick weather with a badge, fog and edge and a smile that knew how to cut. She imagined, unhelpfully, what that mouth would do if the recorder stayed off and Ellison stayed down the hall another ten minutes. The imagining left her slick and furious at herself.

"Choose," he said again, quieter, and the quiet was a hand between her legs she had not authorized and could not stop feeling.

The clock hummed harder. The door was almost open. The drip was hers to open or kill, and either choice would leave her wet with consequence. She could still refuse him. She could still summon a lawyer's name like a spell and watch that brutal charm frost over into pure procedure. Or she could lean—give him Owen on the pier in a voice that shook—and feel, for one dangerous second, what it was to be believed by a man who collected secrets like scars. The fluorescents buzzed. Her thighs ached. Jake waited with the patience of someone who had learned, somewhere darker than this precinct, that waiting was another way to touch without ever laying a single hand on her body—yet.`,
  choices: [
    { id: "scene4a", text: "Lean toward confession before Ellison walks in", textHot: "Lean toward confession — give him the truth before Ellison steals the heat" },
    { id: "scene4b", text: "Call a lawyer mid-interview — shut the drip", textHot: "Call a lawyer mid-interview — shut the drip before his mouth ruins you" }
  ]
};
