export default {
  id: "scene4e",
  layer: 4,
  title: "Softer Net",
  text: `The precinct's second-floor hallway smelled like burnt coffee and wet wool. Fluorescent tubes hummed a tired hymn over linoleum the color of old receipts. Through the wired glass of Interview Two, a mop bucket sat abandoned, yellow caution cone tipped on its side like a small surrender. [player_name] stood with her back to the wall and Owen Vale's name still warm in her mouth—fresh, irreversible, the word she had kept off every official page for seven years.

Jake Akers had not taken notes when she said it. He had gone still in a way that made the hallway feel smaller. Mid-thirties, dark hair cut short enough to look like discipline, jaw shadowed with the kind of stubble that never quite became a decision. The badge on his belt caught the light once and then hid again under his jacket. He looked like a man who could smile for a jury and mean something else entirely for the person on the other side of the table.

"Owen Vale," he repeated, soft as a blade laid flat. "Your stepfather. On the pier the night Renny vanished. You watched him with someone who wasn't supposed to be there, and then you let his story about friends and running off become the file's favorite fiction." His mouth tilted—not kindness, not cruelty. Charm with the safety off. "And you are telling me this now because the upriver remains put a charm in evidence that *might* be hers, and hope is starting to taste like dread, and you finally ran out of ways to call silence protection."

[player_name] tasted copper. "The remains are unidentified. Cho hasn't—"

"I know what Cho hasn't." Jake stepped closer. Not touching. The almost of him was worse. Pier salt clung faintly to his coat from whatever walkthrough he had done before dawn; notebook spine cracked in his inner pocket, a familiar bulge. "I also know Ellison wants a clearance narrative by Friday, and Owen Vale's name in a formal interview would give her one. Bring him in. Hard. Recorded. No soft landings."

"No." The word came out too fast. She pressed her palms to the cold plaster behind her. "If you take him hard, he lawyers up, he destroys whatever he still has, and Renny—whoever those bones belong to—*someone*—loses the thread. Please. A softer net. Surveillance. Quiet pressure. Let him think he still has room to breathe while you watch what he reaches for."

Jake's laugh was low and private, the sound of a man who had heard softer nets requested in rooms that ended badly. "You beg beautifully. Has anyone told you that? It almost works on people who haven't learned what begging costs." He braced one hand on the wall beside her head, forearm caging without trapping, and the hallway narrowed to coffee-burn and his cologne cut with rain. "I used to be the kind of detective who kicked doors because patience felt like complicity. Someone taught me—expensive lesson; a raid that still answers to the name Nina Solis in rooms I do not enter sober—that hard takes leave ashes where evidence used to live. So I can do soft. I can put a car on Owen's street and a mirror on his habits. But soft is not mercy, [player_name]. Soft is a different kind of hunt. And if you are asking me for it because you still love the man who taught you how to lie for him, I need that on the table before I spend department hours pretending restraint."

She swallowed. Renny's old hoodie lived folded in a drawer at home; the missing charm's twin still haunted the bracelet in her jewelry box. Festival fog. Pier lights. Owen's silhouette with a stranger whose face she had never quite committed to the record. "I am asking because if those remains turn out to be hers, I want the truth intact. If they are not, I still want Owen's night accounted for without him burning the map. Family loyalty got me seven years of quiet. I am trying not to let it get me another empty file."

Jake's eyes—hazel going nearly black under fluorescents—tracked her mouth, then her throat, then back up with a deliberateness that felt like a search warrant on her pulse. "Ellison will hate soft. She already distrusts family witnesses. She thinks Akers gets results by being charming enough to make people forget they have rights." The smile landed then, late and sharp, the weapon half of him. "She is not entirely wrong. Charm is how I survive rooms that want me stupid. It is also how I get close enough to see what people hide. You should remember that when you ask me to stand near Owen without cuffs."

A door slammed somewhere down the corridor. Voices. The building's night shift turning over. Jake did not move his arm. [player_name] felt the heat of him through the space between coat and sweater—dangerous attraction braided with the procedural cold of what she had unleashed. He was not the clean-cut badge from recruitment posters. There was a scar nick at the corner of his left eyebrow she had not noticed in daylight, a whitened knuckle on his right hand that looked like old breaks, a way he stood that said he had learned balance in places without linoleum.

"Softer net," he murmured, testing the phrase the way he tested alibis. "I put eyes on him. You stay available. You do not tip him. You do not call home with a weather report dressed as concern. If the soft net shows him reaching for a phone, a bag, a pier key—then we tighten. If it shows nothing, we still have your statement naming him at the scene, and Ellison will use that like a hammer whether I like it or not." His free hand lifted, almost touched her jaw, stopped a breath short. "You named him in a hallway that records nothing. Tomorrow you may have to name him where the clock hums and the red light blinks. Are you ready for that, or are you buying time for a man who stood on a pier while a teenage girl became a cold case?"

[player_name]'s voice roughened. "I am buying time for evidence. For Cho's lab. For the chance that the upriver bones are not my sister—and the chance that they are, and Owen knows which chance is true." She held his gaze. "Soft net. Please, Jake. I will stay available. I will not tip him. Just—do not let the first move be the kind that teaches him we are already at war."

Jake's almost-touch became a touch: two fingers under her chin, tipping her face up under the sick fluorescent weather. Not gentle. Not rough. Precise. The wound half of the charm showed in his eyes for a second—something older than the badge, some private ledger of doors kicked and ashes left—and then the smile returned, softer only in shape.

"All right," he said. "Soft. For now. Because you asked like someone who still has skin in the truth, not just in the family name." He released her chin. Stepped back. The hallway expanded again, mop bucket and caution cone reclaiming their small tragedy. "I will set the car tonight. You go home. You do not look at Owen's house like a guilty daughter making rounds. And if soft breaks—if he burns something, if he runs—you remember I warned you that restraint is a hunt with better manners."

She nodded. Pier fog seemed to lean against the wired glass without being there. Hope and dread shared the corridor the way they had shared her doorway the morning he arrived with a warrant and a charm that *might* belong to Renny. Jake turned toward the stairwell, then paused, looking back over his shoulder with that late smile that made wanting him feel like stepping onto a pier at night.

"One more thing," he said. "People who ask me for soft nets usually want me soft too. I am not. I can wait. I can watch. I cannot pretend I do not want to put my mouth on the woman who just handed me the name that cracks this file open—and I will not pretend that wanting her makes me gentle with the case. Soft for Owen. Not soft for the rest of this."

The hook hung between them: unfinished, bodily, procedural. His phone buzzed once in his pocket—Ellison, or the desk, or the first thread of the softer net already pulling taut. Jake did not answer it yet. He watched [player_name] instead, waiting on the next verb, on whether she would walk him toward surveillance with her hand almost in his, or whether soft would break before morning and leave Owen's name smoking in a precinct that already smelled like burnt coffee and old wool.

She thought of Captain Mara Ellison's distrust like a weather front already moving inland—family witnesses as sandbags, soft nets as delay tactics, Jake Akers as the detective who got results that left fingerprints on more than evidence bags. [player_name] had seen the way other cops watched him in the bullpen: respect laced with wariness, the particular caution reserved for men who smiled too well and slept too little. Whatever he had been before the badge, Harborwick only got rumors. Pier bars whispered. A clerk once went quiet when his name came up. Layer 4 did not owe her his whole past. It owed her the shape of the danger she was asking to stand beside.

"If soft finds nothing," she said, "you still have me. On record when you need it. I am not asking you to bury Owen. I am asking you not to scatter him before Cho finishes with bones that might not even be Renny."

Jake's gaze flicked to her mouth again—habit, hunger, interrogation technique braided until she could not tell which was which. "Cho's timing is a knife we do not hold. Ellison's calendar is another. Your soft net sits between them like a woman trying to catch both blades with bare hands." He almost smiled. "I have always liked dangerous women. That is not a compliment. That is a warning that sounds like one."

Rain needled the high windows. The interview-room clock hummed through the wall. Somewhere upriver, unidentified remains waited on Cho's schedule. Somewhere across Harborwick, Owen Vale slept or did not sleep, unaware that the sister who had protected him had finally spoken—and that Jake Akers had agreed, for now, to hunt him with patience that still felt like a blade laid carefully along the skin.`,
  textHot: `The precinct's second-floor hallway smelled like burnt coffee and wet wool, and [player_name] stood with her back to the plaster while Owen Vale's name left her mouth and Jake Akers' body answered before his badge did—stillness first, then that late smile that landed like a hand between her legs without touching her.

"Owen Vale," Jake repeated, soft as a blade laid flat. Mid-thirties, dark stubble, hazel eyes gone nearly black under fluorescents, badge half-hidden under his jacket, notebook cracked against his ribs like a second heart that only beat for unfinished cases. Not clean-cut. Not safe. The kind of man who could charm a confession out of a room and leave the witness wet and shaken and unsure which part had been the interrogation. Whitened knuckle on his right hand. Scar nick at the eyebrow. A stance learned somewhere linoleum never reached. "Your stepfather. Pier night. You kept him off the page for seven years while a teenage girl became weather and a city learned how to say cold case like a lullaby. And you are telling me now because a charm *might* be Renny's and your cunt and your conscience finally stopped agreeing that silence was love."

Heat punched low in her belly. She hated that grief could share a body with this. She did not step away. "The remains are unidentified. Cho hasn't—"

"I know what Cho hasn't." He stepped in. One hand braced beside her head, forearm a cage that was also an invitation. The other settled at her waist under her coat, thumb finding the soft give above her hipbone like he was checking for weapons and finding want instead. Pier salt on his coat from a dawn walkthrough. Rain still living in his hair. Burnt-coffee breath when he spoke close. "Ellison wants him hard. Recorded. Clearance by Friday if she can get it. I can do hard. I used to prefer it—kick the door, watch the ashes, call the smoke justice. Someone taught me ashes make poor evidence. Expensive lesson. A raid that still answers to Nina Solis when the whiskey is honest—teeth, not tidy; a wound I wear as charm so nobody asks the right question. Harborwick does not get the whole story, not at Layer 4, not while I still need you upright enough to beg. So you may ask me for a softer net, and I may say yes, because hearing you beg makes my cock thick against my zipper while we discuss your family's ruin."

He rolled his hips once against her, shameless, precise, and she felt him—hard already, brutal honesty in denim—while the fluorescent tubes hummed like a voyeur with a time card. [player_name]'s palms flattened on cold plaster. Her thighs pressed together and failed to hide anything. "Softer net," she managed, voice wrecked. "Surveillance. Quiet pressure. If you take him loud he burns what he still has. Please, Jake. Soft. Let him think he can breathe while you watch what he reaches for."

Jake's laugh was private filth, the sound of a man who had heard softer nets requested in rooms that ended with blood on better intentions. "You beg beautifully. Has anyone told you your mouth looks like it was built for softer asks and harder answers?" His thumb stroked under her sweater onto bare skin. Higher. The underside of her breast, not quite nipple, a promise with teeth that made her gasp. "Charm is a weapon I learned in rooms that were not precincts—hints only, darling—and I use it to get close. You asked me close. Feel how close." He nudged again, cock a thick ridge against her hip, and she rocked helplessly, denim dragging on denim, wetness already a shameful slick fact between her legs. "Soft for Owen means I put a car on his street and I do not kick his door tonight. It does not mean I go soft on you. Ellison thinks Akers gets results by being charming enough to make people forget they have rights. She is not entirely wrong. Remember that when you ask me to stand near your stepfather without cuffs while my hand is under your sweater in a hallway that records nothing."

She arched despite herself. Renny's hoodie folded in a drawer at home; the bracelet missing one charm; festival fog; Owen's silhouette with a stranger; unidentified bones upriver that might or might not be her sister. Hope and dread shared her doorway. Want and loyalty shared her cunt. "I am asking for evidence," she whispered against his jaw, lips brushing stubble that scraped sweetly. "Not for mercy dressed as family. Soft net. I will not tip him. I will stay available. Just—do not let the first move teach him we are already at war."

Jake tipped her chin up with two fingers—precise, not gentle—and kissed the corner of her mouth without giving her the center, a deliberate denial that made her clench around nothing. Then he dragged that kiss down to the hinge of her jaw, to the pulse under her ear, open-mouthed, teeth a threat he did not complete. "All right. Soft. For now. Because you asked like someone who still has skin in the truth, not just in the Vale name." His thigh pressed between hers. She rode it once, filthy and helpless, and he groaned soft into her throat like a man clocking a confession. "You go home wet for a detective who agreed to hunt your stepfather with manners. You do not look at Owen's house like a guilty daughter making rounds. You do not call with concern dressed as weather. If soft breaks—if he burns a phone, if he runs, if he reaches for the pier key—you remember I warned you that restraint is still a hunt. And if you dream about me tonight, dream about my mouth where your plea started, because soft for him is not soft for the rest of this."

His free hand slid from breast to the front of her jeans, palm cupping her through the seam, feeling the heat, the damp, the truth her body told without a red light blinking. He pressed once—firm, claiming, not entering—and held there while she shook. "This is what naming Owen does to you when I am the one listening," he murmured. "Do not tidy it. Do not pretend the softer net is only about evidence. You want me patient with him and impatient with you. I can do both. I have always been good at holding two knives."

A door slammed down the corridor. Voices. Night shift. Jake did not remove his hand. [player_name] could have stopped him. She curled her fingers in his jacket instead and breathed him—rain, coffee, the metallic edge of a man with secrets the badge did not cover. "If soft finds nothing," she said, wrecked, "you still have me. On record when you need it. I am not asking you to bury him. I am asking you not to scatter him before Cho finishes with bones that might not even be Renny."

"Cho's timing is a knife we do not hold." His fingers flexed once against her cunt through denim, a filthy punctuation. "Ellison's calendar is another. Your soft net sits between them like a woman trying to catch both blades barehanded." The late smile returned, weapon and wound. "I have always liked dangerous women. That is not a compliment. That is a warning that sounds like one—and it is the only kind of honesty I trust before morning."

His phone buzzed against her hip where their bodies met—Ellison, or the desk, or the first thread of the net pulling taut. Jake did not answer it. He dragged his thumb across her lower lip until she opened for him, then put that thumb in her mouth just long enough for her to taste salt and herself and the almost of his skin. He withdrew it slowly. Stepped back just enough that hallway air felt like punishment, cock still an obscene line in his jeans, eyes still hunting.

"Choose the next verb while you can still taste almost," he said. "Walk me toward the soft net with your hand in mine like you trust the hunter—or admit soft will break before morning and ask me what happens when Owen destroys the first thing he reaches for. Either way I am hard for you in a precinct that smells like burnt coffee and old wool. Either way Renny's name stays a question mark on Cho's table. Either way you named him, and I am not clean enough to pretend that does not make me want to fuck the confession deeper into both of us before the surveillance car even rolls."

Rain needled the high windows. The interview-room clock hummed through the wall. [player_name] stood shaking, cunt aching, lips wet, Owen's name still bright as a bruise on her tongue, while Jake Akers watched her with brutal charm and a wound behind his smile that promised darker ledgers ahead—hints only, for now—pressed into her body like a hand that knew exactly how to make her say please and mean soft and hard at the same time, Harborwick fog breathing against the glass as if the city itself were waiting on her next verb.`,
  choices: [
    { id: "scene5i", text: "Take the soft net — stay close while Jake surveils Owen", textHot: "Take the soft net — stay close while Jake surveils Owen, body still humming" },
    { id: "scene5j", text: "Brace for soft to break — Owen may destroy what he reaches for first", textHot: "Brace for soft to break — Owen destroys, and want turns to fallout" }
  ]
};
