export default {
  id: "scene6l",
  layer: 6,
  title: "Obstruction fight: break up / break open",
  text: `The obstruction fight did not start with raised voices. It started with William Akers setting his badge on [player_name]'s kitchen table like a dare and a breakup note sharing one piece of cheap metal.

Harborwick rain needled the window over the sink. Foghorns complained across the channel. Renny's old hoodie lay folded on a chair like a third party who refused to leave the argument. Somewhere upriver, Dr. Lila Cho's unidentified remains still waited without Renny's name—timing lean, charm consistent-not-unique, hope and dread sharing the lab tray—and none of that science softened the fact that [player_name] had tipped Owen Vale, or that Will had smelled the leak, or that Captain Mara Ellison's briefing clock was eating the hour while romance and case law tried to occupy the same linoleum.

Will stood mid-thirties and sleep-deprived, scar through the eyebrow, cracked notebook closed hard enough to protest, brutal charm scraped entirely to wound. Grey-green eyes tracked [player_name] the way he tracked interview-room clocks—counting what people thought was private. Soft net had burned. Phone ash lived in a unit bag. A tip lived in [player_name]'s throat like a second pulse. Shielding him from Ellison's politics had bought a corridor of burnt coffee and a longer leash; walking would have bought a chase. Either path put them here: obstruction named, trust under reconstruction, want unfinished.

"Say it plain," Will said. Voice flat enough to sand wood. "You obstructed a homicide revival to protect a stepfather who made breakfast with clean hands and a pier silhouette you scrubbed for seven years. You dialed. You warned. Soft failed partly because panic found a stairwell. I can work with guilt. I cannot work with a partner who pretends the tip was weather."

[player_name]'s mouth tasted copper and rain. Mid-twenties and done pretending alone was always bravery—and still not ready for the sound of a detective offering break-up and break-open as the same fork. "I was afraid you would push early. I was afraid Owen would burn the map. I was afraid Renny's maybe-bones would become a clearance narrative before Cho finished speaking. Fear is not a virtue. It is also not the same as wanting you gone."

"Wanting me gone would be cleaner." Will's late smile arrived wrong—weapon half, no velvet. "Cleaner than standing in your kitchen hard for the woman who leaked my soft net and asking whether we break up so Ellison gets a tidy witness file, or break open so the tip becomes a scar we both touch instead of a sealed silence I already know how to wear." His knuckles whitened on the chair back. When a hallway joke almost rose—*kids in hallways*—it died mid-breath, Solis-shaped—sealed past smoking without unpacking: raid, hallway, a teenager who should not have been there, Ellison's muttered fear that Akers would make the same ashes twice. Teeth showing. "I pushed early once. A partner took the official weather. I kept a badge. Soft for Owen was me spending that costume on your ask. You spent a tip on your fear. Ledger entries. Both of us. Now we conjugate aftermath."

The radiator knocked like a second interrogation clock. Chain-link rattled somewhere in the wet dark. [player_name] thought of festival fog, funnel-cake sugar, Renny pointing east, Owen's careful breath on a stairwell line—*William Akers is coming*—and the deleted call log that deleted nothing from her ribs. Attraction flickered anyway: dangerous, procedural, the heat of being seen in public while obstruction still wore her name. Mid-thirties to her mid-twenties—close enough to burn, far enough that the badge on the table still felt like a different country.

"Ellison wants proximity language in a memo," Will continued. "Internal weather with manners. If we break up—professionally, romantically, the whole messy braid—I brief her alone with a hole shaped like your empty chair and a tip I can sand into panic instead of partnership. If we break open, we walk upstairs together later and tell her the leak and the soft net and the ash dig in one ugly paragraph, and we keep choosing each other mid-war while Cho's bones stay unnamed and a warehouse raid still waits for warrant ink. Break-up protects optics. Break-open protects the only trust plot we have left."

[player_name] stepped closer despite herself. Dryer-sheet ghost from Owen's house still lived in her memory; here the air smelled like Will's wet wool and precinct bitterness and the peach-plastic perfume faint in Renny's hoodie. "If we break up, do you stop hunting with me?"

"I stop fucking my judgment with your mouth in stairwells," Will said, blunt, honest without porn diction. "I do not stop the case. Renny does not get abandoned because romance failed a stress test. Soft nets and sink traps and clerk ghosts still get dug. You become a familial contact with a lawyer and a distance I will hate and honor. Break-up is not surrender of the file. It is surrender of this—" he gestured at the narrow space between their bodies, at the unfinished kiss hanging like a hook "—before Ellison weaponizes it."

"And break open?"

"Means the tip stays on the table between us like a third lover we both have to look at." His voice frayed. "Means I stay angry and still choose you. Means you stop inventing purity and stop inventing funerals the lab has not authorized. Means when the raid call comes—we take it as people who already decided the war includes us. Choose each other mid-war, or take the raid pressure as the next verb if break-open feels too soft a word for what we are." He exhaled. "Both hurt. Both leave hope employed. Both leave dread honest. Neither prints Renny on bone tonight."

Silence thickened. Rain thickened with it. Will picked up the badge, set it down again, a man arguing with his own metal. [player_name] almost touched the scar nick; did; his pulse jumped once under her fingers. He did not pull away. He looked at her mouth the way he looked at evidence that might burn him.

"I dream raid noise when soft fails," he said quietly. "Obstruction fights are how soft fails in kitchens instead of alleys. Having you here is how the dream learns your name. Ellison calling that a liability does not make it less true. His old partner would call me compromised. She would not be wrong. Compromised is sometimes how I stay human after ashes."

[player_name] tasted copper and the sharper taste of almost-trust climbing her throat. The silver charm bracelet gap winked in her mind's eye from a dresser across town. Cho's careful language still said *pending*. Rumor had already tried to bury Renny. Neither break-up nor break-open would help rumor. Only science and courage and a detective who refused false funerals.

She thought of Ellison's tablet light under a captain's chin, of warehouse maps with half-scraped door numbers, of Will's refusal to christen silt with a sister's name before the lab earned it. Break-up would feel like putting Renny back in a drawer with the hoodie—protection dressed as distance. Break-open would feel like cutting a rope and finding it was also a handhold. [player_name] wanted both truths at once.

Will paced once—boot soft on linoleum, coat dripping a dark coin of rain onto the floorboards—then stopped with his back to the window so Harborwick fog framed him like a second interrogation light. "If we choose each other mid-war, I will still be angry in the elevator after. Anger does not cancel the braid. If we take the raid call first, I will still want your mouth when the radios go quiet. Want does not cancel consequence. I need you to hear both sentences without sanding either into comfort."

"Two doors from this table," Will murmured. "Choose each other mid-war. Or take the raid shoot-or-don't-shoot call as the pressure test—warehouse ink, backup, no early push for a CI or a guilt trip—and let consequence decide whether romance survives the entry. Mid-war choice keeps the heart in the hunt. Raid call keeps the badge honest when hallways get loud. Both leave your sister a question mark on a lab tray. Both leave me changed."

He did not kiss her. Badge metal cooled between them. Renny's hoodie waited on the chair like a held breath. Will's cracked knuckles flexed as if he might still convert the fight into steel on Owen by morning and was choosing, for one more hour, to spend the fight on them instead.

"Clock," Will said softly. "Choose each other mid-war—or take the raid shoot/don't-shoot call. Either way obstruction already spoke. Either way Cho's bones stay unnamed tonight. Pick the hurt that keeps truth reachable while Harborwick fog erases the curb outside and this kitchen finishes learning whether we break up into distance or break open into a war we fight side by side."

Will left the badge between them on the table like a breakup note that could still become a vow. "Choose each other mid-war—or take the raid shoot/don't-shoot call. Obstruction already spoke. Cho's bones stay unnamed tonight either way." Rain streaked the glass. Renny's hoodie waited in the other room like a third opinion. [player_name] looked from the metal to his hunger-and-warning face and felt the choice land like a second tip—capable of burning what it meant to save. Choose each other meant breaking open while still angry in the elevator afterward. Raid call meant earning the staying under fish-rot air and radio crackle. Romance unfinished. Sister still contested. The table would not forgive a soft lie—and neither would the detective who had set his badge down and was asking which temperature of aftermath she could live inside while obstruction cooled into distance or a deeper vow.`,
  textHot: `The obstruction fight did not start with raised voices—it started with William Akers setting his badge on [player_name]'s kitchen table hard enough to make the salt shaker jump, and the sound went through her like a slap and a caress at once. Metal on wood. Mid-thirties detective undressing his authority in her house. Her cunt clenched around the threat of being left and the filthier threat of being kept.

Harborwick rain. Foghorns. Renny's hoodie on a chair like a third party. Cho's unidentified remains still upriver without Renny's name—timing lean, charm maybe, hope and dread sharing the tray—and none of that science softened the tip in [player_name]'s throat or the thick idle argument Will's cock made in wet jeans while he stood mid-thirties, scar nick white, notebook closed hard, brutal charm scraped to wound. Soft net burned. Phone ash bagged. Ellison's briefing clock eating the hour. Shielding him had bought leash; walking would have bought chase. Either path put obstruction named and his grey-green eyes counting her like a clock.

"Say it plain," Will said, flat and sex-rough under detective manners. "You obstructed a homicide revival. You dialed Owen. Soft failed partly because panic found a stairwell and my hand found your cunt anyway. I can fuck through guilt. I cannot partner with a woman who pretends the tip was weather while she soaks for me."

[player_name] tasted copper and rain and the almost of his mouth. "I was afraid you would push early. Afraid he would burn the map. Afraid Renny's maybe-bones would become clearance before Cho finished. Fear is not virtue. It is also not wanting you gone."

"Wanting me gone would be cleaner." Late smile wrong—weapon, no velvet. He stepped into her space until his thigh slotted between hers against the counter, badge cold on the table beside her hip, cock a thick line against her belly through denim. "Cleaner than standing hard for the woman who leaked my soft net and asking whether we break up so Ellison gets a tidy witness file—or break open so the tip becomes a scar we both touch instead of a sealed silence." His hand opened her jeans with detective efficiency, slid into panties where she was shamelessly slick from fight-heat and shame. Two fingers pushed in slow; she clenched; he groaned like anger and pleasure were one sound. "Ledger entries. You tipped. I spent soft costume on your ask because Solis taught me what early ashes cost—hallway, kid, partner weather, sealed file I still will not dump in your lap. Now we conjugate."

He curled his fingers. Thumb on her clit. Forehead to hers, center kiss denied on purpose. "Break up—professionally, romantically—and I brief Ellison alone with a hole shaped like your empty chair. I sand the tip into panic. I stop putting my fingers in you in stairwells. I do not stop the case. Your sister does not become collateral because we failed a kitchen stress test. You get distance I will hate and honor while I stay hard for a woman I am not allowed to finish fucking." He fucked the choice into her with stakeout patience turned filthy. "Break open means the tip stays on the table between us like a third lover. Means I stay angry and still choose you. Means you stop inventing purity and false funerals. Means when the raid call comes—we take it as people who already decided the war includes us fucking and hunting in the same breath."

[player_name] rocked on his hand despite herself. He hissed and stopped her hip with exact control, sealed-ash behind his eyes. "I dream raid noise when soft fails. Obstruction fights are how soft fails in kitchens. Having you open on my wrist is how the dream learns your name. Ellison calling that liability does not make it less true. Compromised is sometimes how I stay human after ashes."

He withdrew glistening fingers to paint her lower lip, then pressed her palm to his cock through jeans—thick, hot, brutal honesty—and rolled once into her fist. "Feel what the fight does to me. Soft dead. Hunt live. Want past professionalism. Grief and sex can share a body. Do not tidy it. Do not eroticize the bones—unnamed, unconfirmed—but do not pretend a tip made you pure or a badge on the table made me celibate."

She thought of Ellison's tablet, warehouse maps, Will's refusal to christen silt—and of his fingers still shining with her. Break-up would put Renny back in a drawer with the hoodie and put Will's cock out of her reach on purpose. Break-open would cut a rope that was also a handhold and leave her aching on his hand while they admitted the tip out loud. [player_name] wanted both truths.

Will paced once, coat dripping, then boxed her against the counter again with his hips, badge cold beside them, mouth on her jaw. "If we choose each other mid-war, I will still be angry in the elevator after—and I will put you against a blind wall and finish what my fingers started with my mouth until you come quiet enough for fluorescent lights, tip still true, trust under reconstruction. If we take the raid call first, I will keep you aching through the briefing, zipper a tooth short, so consequence and want share your pulse when the radios crackle. Anger does not cancel the braid. Want does not cancel the entry. Hear both without sanding either into comfort."

His hand returned under her open jeans, not thrusting, just cupping heat, claiming, holding her on the edge of a climax he refused to authorize. "Feel that? That is fallout wearing a detective's palm. Soft died when you dialed Owen—or when he burned the phone—or both. What lives is this: I can still work the case with you if we break open. I can still want you if we break into raid pressure first—wanting is not the same as trusting. Trust is the real plot. You tipped a hole in it. Mid-war is triage tape. Raid call is proving the tape holds under fish-rot air."

Rain thickened on the glass. Will's free hand cupped the back of her neck, grounding, thumb stroking the soft hairline while his other wrist shone with her slick under the kitchen bulb he did not wipe. "Two doors," he murmured, voice frayed. "Choose each other mid-war—break open the tip, the soft failure, the want—and I take you apart in this kitchen until you come quiet enough for foghorns, then we walk into Ellison's weather as a braid. Or take the raid shoot-or-don't-shoot call as the pressure test—warehouse ink, backup, no early push—and let consequence decide whether romance survives the entry while I keep you aching through the briefing because unfinished is how I make sure you pick with your body telling the truth." He opened her wider, added a third finger until she cried out soft against his teeth, then stopped—exact, cruel, tender as a threat. "Not yet. Not until you pick."

She tasted copper and herself and wet wool. Festival fog lived behind her eyes: Renny's laugh, Owen's silhouette, stairwell tip, seven years of protection that had become a different violence—and tonight's fight finishing one sentence so another could start without a booking clang. Will's scar nick brushed her forehead when he leaned. His late smile arrived wrong, all weapon and wound.

"Clock," he said. "Verb. Choose each other mid-war—break open—or take the raid shoot/don't-shoot call. Pick the hurt that keeps truth reachable while I can still smell your cunt on my hand and my badge cools on your table like a note we have not finished writing."

[player_name] held his gaze with her pulse loud between her legs. Missing charm. Unidentified bones. Tip alive. William Akers with badge honest and charm scraped raw and cock still arguing against patience. Choose each other mid-war. Or take the raid call.

He guided her hand once more along the thick line of him, then set both their palms flat on either side of the badge—his covering hers, cracked knuckle white, pulse jumping. "Mid-war means I stay. Raid call means we earn staying under fish-rot air and radio crackle. Either way Renny stays a question mark on Cho's tray tonight. Either way I leave this kitchen changed. Murder stays plot. This heat advances trust or it advances nothing. Conjugate, [player_name]. Break open with me—or take the shot-call pressure and make the war prove what a tip tried to ruin."

He guided her palm once more along the thick line of his cock through jeans, then set both their hands flat on either side of the badge—his covering hers, cracked knuckle white, pulse jumping into her skin. "Mid-war means I stay," Will said, voice wrecked. "Raid call means we earn staying under fish-rot air and radio crackle. Murder stays plot. This heat advances trust or it advances nothing." The radiator knocked. Renny's hoodie waited. [player_name] felt her cunt ache around the shape of a decision. Badge bright between their hands. Unfinished kiss the sharpest hook in the room. Obstruction cooling into either distance or a deeper filthy vow she could still taste on her own lip—break open with him, or take the shot-call pressure and make the war prove what a tip had tried to ruin.`,
  choices: [
    { id: "scene7l", text: "Choose each other mid-war", textHot: "Choose each other mid-war" },
    { id: "scene7m", text: "Take the raid shoot/don't-shoot call", textHot: "Take the raid shoot/don't-shoot call" }
  ]
};
