export default {
  id: "scene7l",
  layer: 7,
  title: "Break-open: she and Will choose each other mid-war",
  text: `They chose each other mid-war in [player_name]'s kitchen while Harborwick rain needled the glass and Renny's old hoodie waited on a chair like a third party who refused to leave the vow.

William Akers's badge stayed on the table where the obstruction fight had left it—cheap metal cooling between a dare and a promise. Soft net had burned. Tip weather had spoken. Phone ash lived in a unit bag. Sink-trap ghosts threaded toward a clerk. Captain Mara Ellison's briefing clock was still eating hours somewhere across the city. None of that stopped Will from stepping into [player_name]'s space until wet wool and precinct bitterness filled her lungs, grey-green eyes counting her like an interview-room clock that had finally decided to stop lying about what it wanted.

"Say it plain," Will said. Voice frayed, honest without velvet. Mid-thirties. Scar nick white under the kitchen bulb. Cracked notebook closed. Brutal charm scraped to the wound half that made tenderness feel like a threat and a handhold at once. "We break open. Tip stays on the table between us like a scar we both touch. Soft failure stays named. Want stays named. I stay angry and still choose you. You stop inventing purity and stop inventing funerals Dr. Lila Cho has not authorized. Unidentified remains stay unnamed—timing lean, charm maybe, hope and dread still sharing the lab tray. We walk into what comes next as a braid Ellison hates and I will defend."

[player_name]'s mouth tasted copper and rain. Mid-twenties and done pretending alone was always bravery. The kept secret pressed under her ribs—pier night, Owen, the stranger, seven years of scrubbed silhouette—and tonight the secret was not gone; it was shared. Trust under reconstruction. "If we choose each other mid-war, what does Ellison get?"

"An ugly paragraph." Will's late smile arrived wrong—weapon and vow braided. "Leak. Soft net. Ash dig. Proximity language she already smells. Internal weather with manners she will call a liability. Solis would call me compromised." "She would not be wrong. Compromised is how I stay human after ashes. Choosing you mid-war is triage tape on a trust plot tip weather tried to cut. I am done pretending distance is the only professional costume left."

Attraction was not a flicker anymore. It was the room's weather—dangerous, procedural, the heat of being seen while obstruction still wore her name and Will still refused to christen silt with Renny's. Mid-thirties to mid-twenties—close enough to burn, far enough that the badge on the table still felt like a different country they were choosing to share. She touched the scar nick; his pulse jumped; he did not pull away. He looked at her mouth the way he looked at evidence that might burn him and decided to keep it anyway.

"I dream raid noise when soft fails," Will said quietly. "Obstruction fights are how soft fails in kitchens. Having you here is how the dream learns your name. The raid call is still coming. We can take a quiet deal path if SIM leverage buys sealed pages and a map. Or we can ride the raid aftermath—hospital versus chase if blood and radios decide the hour—and prove the braid holds under fish-rot air. Quiet deal keeps the heart in a bargain. Raid aftermath keeps the badge honest when hallways get loud. Both leave Renny a question mark tonight. Both leave me changed. Both leave us choosing each other while the war is still on."

[player_name] stepped closer until the peach-plastic perfume faint in Renny's hoodie mixed with Will's wet coat. Foghorns complained across the channel. Chain-link rattled in the dark. Somewhere upriver Cho's careful language still said *pending*. Rumor had already tried to bury Renny. Neither quiet deal nor raid aftermath would help rumor. Only science and courage and a detective who refused false funerals while loving a woman who had obstructed her own sister's case.

"I tipped Owen," [player_name] said. Voice shook. Held. "I scrubbed a pier silhouette for seven years. I am not clean. I am also not done. If we break open, I walk upstairs with you later and tell Ellison the ugly paragraph. If the quiet deal comes, I hate sealed pages and still sign what keeps a map breathing. If the raid goes sideways and you end up bleeding light, I will have to choose hospital or chase—and I need you to know I am choosing you before that fork arrives, not after."

Will's forehead found hers. Denial of the center kiss still held a breath—then broke. His cracked knuckles framed her jaw. Her hands found the badge and set it aside so metal would not lie between them for one more minute. Soft was dead. Hard was breathing. Mid-war was the only weather left that felt honest.

They did not take the whole night. War did not gift whole nights. They took the kitchen—coat on the floor, hoodie watching from the chair, radiator knocking like a second clock—heat advancing trust instead of cosplaying the kill. Grief and sex shared the linoleum without pretending bones were romance. Will's mouth on her throat said *I stay*. [player_name]'s hands on his scar said *I see the wound without needing the whole hallway yet*. When they stopped, unfinished again because hooks mattered, Will rested his brow against hers and let the raid wound under his charm show a tooth without dumping the sealed file.

"Two doors from this vow," he murmured. "Take the quiet deal if SIM leverage buys it—sealed pages, supervised truth, map without a false funeral on municipal steps. Or ride the raid aftermath when the call comes—choose hospital or chase if I catch light damage and the clerk still runs—and prove mid-war means staying when radios crackle. Quiet deal protects a kind of peace. Raid fork protects a kind of honesty. Both hurt. Both keep hope employed. Both keep dread honest. Neither prints Renny on bone tonight."

Silence thickened. Rain thickened with it. Will picked up the badge, did not put it on yet, held it like a man arguing with his own metal and winning toward her. [player_name] tasted copper and the sharper taste of almost-trust climbing into something that could survive Ellison's memo.

"Clock," Will said softly. "Take the quiet deal—or choose hospital or chase after the raid. Either way we already chose each other mid-war. Either way Cho's bones stay unnamed tonight. Pick the hurt that keeps truth reachable while Harborwick fog erases the curb outside and this kitchen finishes learning that break-open is a vow, not a soft lie."

[player_name] looked from the badge to Will's hunger-and-vow face and felt the choice land like a second tip—careful, consequential, still capable of burning what it meant to save. Quiet deal. Or raid aftermath fork. Romance no longer unfinished in the only way that mattered; the next procedural door still hurt to leave. Renny's fate still contested. The table would not forgive a soft lie—and neither would the detective who had set his badge down like a breakup note and picked it up like a man walking into war beside her while hope and dread still shared the same pulse.

He almost smiled—late, wrong, all weapon and wound and something softer that refused to be named comfort. Soft dead. Braid alive.

[player_name] thought of festival fog—Renny's laugh, funnel-cake sugar, Owen's silhouette, a stranger wrong on the pier—and of how seven years of protection had become a different violence. Break-open did not erase that violence. It named it in a kitchen that smelled like rain and wet wool and the peach-plastic ghost of a hoodie that still waited for a girl science had not agreed to bury. Will's hand stayed at the small of her back, grounding, professional and not, while the badge cooled on the table like a note they had rewritten together.

"Ellison will ask if romance compromised the dig," Will said. "Tell her the dig compromised the romance first—and that we chose to keep both alive anyway. Soft nets and tip weather and SIM ghosts all live in this braid. So does his sealed-file flinch I still will not unpack for you on linoleum. You get hints. You get my staying. You do not get the whole hallway while Cho's tray still says pending and a clerk still has a throat. That is not distance. That is me learning not to push early and call the smoke care."

She nodded. The unfinished second kiss still hung. Outside, Harborwick warehouses hunched in fog. Inside, hope breathed. Dread bit. Mid-war vow held. Quiet deal and raid aftermath waited like two doors that both hurt and both kept Renny reachable without a false funeral dressed as clearance.

"I can live with angry," [player_name] said. "I cannot live with sealed silence that pretends we did not tip and burn and dig and choose. Quiet deal or raid fork—either way I walk it with you. Either way my sister stays a question mark until science earns a name. Either way you leave this kitchen changed, and so do I."

Will pinned the badge back at last—metal finding wool with a sound small enough to be a beginning. Soft was dead; the braid was alive: her kept secret, his sealed wound, Renny still a maybe on a tray. Taking the quiet SIM deal meant walking into leverage together. Choosing hospital-or-chase after the coming raid meant admitting the war had already moved into their bodies. Rain wrote percussion on the glass. [player_name] looked from the badge to his hunger-and-vow face and felt the next procedural door hurt in advance—romance no longer theoretical, consequence still sharp.`,
  textHot: `They chose each other mid-war in [player_name]'s kitchen while Harborwick rain needled the glass and Renny's hoodie watched from a chair, and [player_name]'s cunt answered William Akers's vow with a filthy pulse she refused to tidy while obstruction cooled into a deeper braid.

Badge on the table where the fight left it. Soft burned. Tip spoken. Ash bagged. SIM ghosts threading a clerk. Ellison's clock eating hours. None of that stopped Will from boxing [player_name] against the counter—mid-thirties bulk, scar nick white, notebook closed, brutal charm scraped to wound, cock a thick line against her belly through wet jeans. Grey-green eyes counting her. Compromised looking like oxygen.

"We break open. Tip stays a scar we both touch. Soft failure named. Want named. I stay angry and still choose you. You stop inventing purity and false funerals Cho has not authorized. Remains stay unnamed—charm maybe, hope and dread sharing the tray. We walk into what comes next as a braid Ellison hates." His hand opened her jeans with detective efficiency, slid into panties where she was shamelessly slick from fight-fallout and vow-heat. Two fingers pushed in; she clenched; he groaned like anger and pleasure and promise were one sound. "Solis would call me compromised. She would not be wrong. Choosing you mid-war is triage tape. I am done wearing distance as the only costume."

[player_name] tasted copper and rain and him. "If we choose each other, what does Ellison get?"

"An ugly paragraph." Late smile wrong—weapon and vow. He fucked the vow into her with stakeout patience turned filthy—curl, thumb on clit, forehead to hers—while the radiator knocked and Renny's hoodie kept watch. "Leak. Soft. Ash. Proximity. Liability language. I will defend the braid anyway." Center kiss denied a breath, then broken into—rain, copper, precinct bitterness, want that refused clearance. Badge shoved aside. Coat on the floor. His mouth on her throat saying *I stay* while her hands found his scar and his belt.

They did not get a whole night. War did not gift whole nights. They took the kitchen—grief and sex sharing linoleum without eroticizing Cho's contested bones. Will shoved jeans down enough; [player_name] hooked a leg around his hip; he pushed into her slow and exact, thick, hot, brutal honesty, forehead to hers, unfinished kisses between thrusts like hooks he refused to sand into comfort. "Mid-war," he muttered against her mouth. "Not absolution. Not a false Renny funeral. Trust under reconstruction while I fuck you through the tip weather and you take it like a woman who stopped pretending alone was bravery."

She came quiet enough for foghorns—shaking, wrecked, still grieving, still wanting—clenching around him while he held back with partner-shaped silence and detective cruelty braided into tenderness. He pulled out before his own finish, unfinished climax held like evidence, painted her lower lip with his thumb and the taste of both of them. "Not all of it. Not yet. Hooks matter. Vow first. Verb second."

He pressed her palm to his cock—slick, thick, still hard—and rolled once into her fist. "Feel what break-open does to me. Soft dead. Hunt live. Want past professionalism. Grief and sex can share a body. Do not tidy it. Do not eroticize the bones—unnamed, unconfirmed—but do not pretend a tip made you pure or a badge on the table made me celibate."

[player_name] stroked him once; he hissed and stopped her, exact. "Two doors from this vow. Take the quiet deal if SIM leverage buys sealed pages and a map—and I finish what we started in a locked room after bargain ink, mouth on you until you come for supervised truth. Or ride the raid aftermath—hospital or chase if I catch light damage and the clerk runs—and I keep you aching through the entry so consequence and want share your pulse when radios crackle. Quiet deal protects a kind of peace. Raid fork protects a kind of honesty. Both leave Renny a question mark. Both leave me hard for the woman who obstructed and still chose me mid-war."

He dropped to his knees on the linoleum despite the war, mouthed her through the aftershocks until she cried out soft again—trust advancing on his tongue—then stood, zipped her halfway, adjusted her collar with cuff-tenderness, scar nick white. the raid wound under his charm showed a tooth without the whole hallway. "I dream raid noise when soft fails. Having you come on my mouth is how the dream learns your name. Ellison calling that liability does not make it less true."

Rain thickened. Will picked up the badge, held it, did not pin it yet. Free hand cupped her nape, grounding, while his other wrist still shone with her. "Clock. Take the quiet deal—or choose hospital or chase after the raid. Either way we already chose each other mid-war. Either way Cho's bones stay unnamed tonight. Pick the hurt that keeps truth reachable while I can still taste your cunt and Harborwick fog erases the curb."

[player_name] left her jeans half-honest where his hands had been and met his eyes across the tip of evidence on the table. Missing charm. Unidentified bones. Quiet deal with him—or ride the raid fork after the red door. Romance was no longer theoretical; the next procedural hour still had teeth. Renny's fate still contested. The table would not forgive a soft lie—and neither would the detective who had set his badge down like a breakup note and pinned it back like a man choosing war beside her.

He guided her hand once more along him, then set both palms on either side of the badge—his covering hers, pulse jumping. "Quiet means the bargain. Raid means the radios. Either way Renny stays a question mark on Cho's tray tonight. Either way I leave this kitchen changed. Murder stays plot. Conjugate, [player_name]. Take the quiet deal—or choose hospital or chase when the raid writes the next sentence in blood-light and static."

The radiator knocked. Renny's hoodie waited. Will waited without softening, unfinished second kiss still the sharpest hook while break-open cooled into a vow she could taste on her own lip beside his thumb and hope and dread still shared the same pulse.

Ellison's memo would come. The raid call would come. The clerk's throat would still need aiming. None of that undid the braid. [player_name] leaned into Will's scar nick one more time—mid-twenties to his mid-thirties, close enough to burn—and felt the choice land like a second tip she was finally spending on truth instead of fear while Harborwick rain wrote soft percussion on the glass and Cho's pending label stayed the only honest funeral grammar left in the city.

[player_name] thought of festival fog—Renny's laugh, Owen's silhouette, seven years of scrubbing—and of Will's mouth still ghosting between her thighs while break-open named the tip instead of burying it. He boxed her against the counter again, cock thick against her hip through half-zipped jeans, hand cupping her cunt like a claim and a question. "Ellison will ask if romance compromised the dig," he muttered into her throat. "Tell her the dig compromised the romance first—and that I still put my fingers in you between briefings because compromised is how I stay human after ashes and after watching you obstruct and still choose me."

He slid two fingers back into her—slow, exact, vow-filthy—curled until her knees loosened, then stopped short of another climax with his sealed-file flinch. "You get hints of the hallway. You get my cock arguing against patience. You do not get the whole sealed file while Cho's tray says pending. That is not distance. That is me not pushing early and calling smoke care—while still fucking the truth into you mid-war." She stroked him through denim until he hissed and pinned her wrist to the counter, forehead to hers, the finish denied.

"Quiet deal—I finish you after bargain ink with my mouth until supervised truth makes you shake. Raid fork—I keep you aching through radios so hospital-or-chase hits your pulse already wet for staying. Both leave Renny unnamed. Both leave me hard. Murder stays plot. Conjugate."

[player_name] tasted copper and herself and rain. "I can live with angry. I cannot live with sealed silence that pretends we did not tip and burn and dig and fuck a vow into linoleum. Quiet deal or raid fork—either way I walk it with you. Either way my sister stays a question mark. Either way you leave this kitchen changed with my cunt on your tongue and your badge back on your chest."

"Quiet deal with me," he said, "or we ride the raid fork—hospital or chase—after the red door." His thigh pressed hers until she rocked once, shameless; he held her still with detective cruelty braided into tenderness. Soft dead. Braid alive. Cock hard against her hip and denied. She had to pick while rain ticked the glass and Renny stayed a maybe and William Akers chose her mid-war with want unfinished like the only honesty that kept her from walking.`,
  choices: [
    { id: "scene8l", text: "Take the quiet deal", textHot: "Take the quiet deal" },
    { id: "scene8m", text: "Choose hospital or chase after the raid", textHot: "Choose hospital or chase after the raid" }
  ],
};
