export default {
  id: "scene7g",
  layer: 7,
  title: "Warehouse breach with Jake",
  text: `The red door gave on the third shove—not kicked, not cinematic, just Jake Akers putting his shoulder where Harborwick's padlock had pretended to be permanent.

Pre-dawn still held the warehouse east of the old fish auction in a soft fist of fog. Salt. Rust. Chain-link silvered with wet. A foghorn rolled inland low enough to feel in the ribs. [player_name] stayed at Jake's shoulder the way he had ordered—mid-twenties sister, not a raid story, flashlight low, breath controlled by force. Mid-thirties detective ahead of her with cracked notebook jammed in a coat pocket, scar through his eyebrow catching what little sodium light leaked through corrugated gaps. Brutal charm banked into working steel. Soft approach had become breach the minute the lock's shackle showed fresh tool marks and the camera cable hung cut-neat like someone who understood angles.

"Clear left," Jake murmured. Not for theater. For the part of him that still flinched when hallways went wrong. Nina Solis lived in that murmur as hint only—ex-partner, early push, sealed IA file, a teenager in the wrong hallway years ago who still smoked under his charm like cologne with teeth. He did not unpack it into the cold-storage dark. He cleared the bay with the patience of a man who had pushed early once and still wore the bruise under his badge.

Cold-storage row breathed machine-low. Condensation beaded on steel. Bleach ghost. Diesel. Blood-rust on a threshold deeper in—old-penny smear, rain-diluted into almost-art, already photographed on softer weathers if other branches had found it first. Tonight they were inside the mouth Renny had pointed at when a generator ate grammar. Dr. Lila Cho's language still ruled the upriver remains: *unidentified*, *pending*, *consistent with*. The silver charm still only *like*. Hope and dread shared the breach like co-counsel. Entry did not christen bone. Entry only asked what the dark still held.

[player_name] tasted copper and salt. Attraction pressed under the procedural pressure even here—soap and sleeplessness when Jake's coat brushed hers in the narrow bay, unfinished heat from rain nights and red lights and stairwells that had no business surviving into warehouse weather. Trust was the real plot. Trust currently smelled like cold metal and Jake's refusal to let her walk first.

They found the clerk's ghost before they found the clerk: a folding table with harbor invoices half-shredded, a city routing stamp that did not match Owen Vale's butter-porch story, initials Renny had carried like a dare scratched into the wood as if someone had been nervous enough to doodle confession. A cigarette butt—not pier-tourist brand. Foot traffic in dust after the last rain. A side office with a dead monitor and a live shredder basket still warm to [player_name]'s gloved knuckle.

"Someone left in a hurry and planned to come back," Jake said. Pen out. Notebook spine cracking. "Or someone is still here."

A sound deeper in the row—metal on metal, not machine. Jake's hand found [player_name]'s coat and moved her behind him without asking. The touch was brief, professional, and somehow louder than a kiss. Captain Mara Ellison's warrant language lived in [player_name]'s memory from planning hours: authorized entry, familial tip confirmed, soft-to-hard. Ellison would smell cowboy if they invented heroics. Jake refused to gift her a hallway rhyme.

They moved. Flashlight painting blistered paint. Generator carcass in a corner—grammar-eating ghost confirming Renny's map. On a shelf: zip ties, a cheap silver display tray missing teeth, a ledger page with Owen's late-night dates overlapping festival week in a handwriting that was not Owen's. [player_name]'s throat tightened. Hope argued that Renny had walked out of this room. Dread answered that someone had not wanted her to. The bones upriver stayed unnamed. This room was not a funeral. It was a chain with fingerprints.

Jake stopped at a frost-latched door. Breath ghosted. "Two verbs from here," he said quietly, for her. "We catch the clerk in the warehouse—live link, routing stamp, shredder warm, the man Renny's initials dared. Endgame the body that still has a pulse and a shredder schedule. Or we press Owen with what this room already proves until he confesses partially—dates, companions, who taught the lullaby—without waiting for a clerk who might already be reading tip-sheets and burning the rest. Catch living steel. Or squeeze the stepfather with steel as lever. Both move. Neither confirms Renny among the dead. Cho still gets to speak first on bone."

Rain began again on the roof like needlepoint. [player_name] looked at the warm shredder basket and the ledger page and Jake's cracked knuckles whitening on the flashlight. the sealed past smoked under his silence—hint, teeth, dark past humming under the badge like a second pulse he refused to dump into breach weather. Attraction braided into fear until she could not tell if she wanted to chase the clerk for Renny or for the man who would walk through frost-latch first.

"If we catch the clerk," she said, "we spend the breach on the living link Renny mapped. If we press Owen, we spend the breach as proof and put Vale in a room before the clerk finishes erasing."

"Both hurt the people who needed her quiet," Jake said. Brutal charm flickered velvet-wrong and banked. "Both keep you close enough that I can watch whether grief makes you careful or reckless. I push early and people bleed. I am done pushing early for the sake of feeling fast—but I am not done catching what this room is offering. Your sister's map. Your call. Dawn is coming whether the clerk is or not."

A radio crackle on Jake's hip—Ellison's channel, clipped, asking for status without saying *do not rhyme his old partner*. Jake answered in shorthand: inside, warm shredder, routing stamp, no hard ID, remains still pending language. He did not say [player_name]'s name like a liability. He did not say want. The radio went quiet. Harborwick's damp history leaned on the corrugated steel.

[player_name] flexed cold fingers inside Jake's offered spare glove and felt seven years press upward. Renny's hoodie lived folded across town. The bracelet gap lived in memory. Soft surveillance and raw admissions and Ellison ultimatums had all poured into this bay. The kept secret's remaining scraps—letters, warmer mercies—still waited somewhere that was not a shredder basket. Breach was not emptying every pocket. It was standing in the geography a teenager had pointed at and choosing which living man to spend it on.

Footsteps—distant, then nearer. Not yet a face. Jake angled the light off, then on, signaling. His body blocked [player_name]'s without drama. Mid-thirties bulk as shield. Mid-twenties pulse as drum. Remains unnamed. Charm probability. Owen's costume and a clerk's initials sharing the same dust.

"Decide before the footsteps decide for us," Jake whispered. "Catch the clerk in the warehouse—or press Owen until he confesses partially on the strength of this room. I will dig either way. I will not let you bury hope under a frost-latch or baptize dread into certainty because a ledger rhymed with a pier night."

The warehouse hummed its low animal note. Chain-link rattled outside. [player_name] tasted the metallic edge of a point arriving. Catch the living clerk Renny had dared—or squeeze Owen with partial confession as the next weather. The hook hung in the warm shredder and in Jake's almost-touch and in the unanswered science still humming in Cho's careful lab while Harborwick's fog decided, slowly, what to reveal through a red door that had finally given.

Captain Mara Ellison would call this authorized if the paperwork held and cowboy if a familial witness caught a ricochet of bad luck. Owen's lawyers would call it contamination theater. Dr. Lila Cho would call the blood-rust a chain-of-custody question with a sister too close to the smear. Jake would sand the edges and still look at [player_name] like she had both saved a lead and set his career on a slow fuse by refusing to wait in the car. She accepted that the way she accepted Harborwick rain—constant, practiced, already on her skin. The silver display tray missing teeth winked under dust like a cousin of Renny's bracelet gap without permission to become baptism. [player_name] did not touch it. Jake bagged. Catalogue over eagerness. Soft lessons from hard history. Harborwick's foghorn answered from the river again—low enough to feel in the ribs—while [player_name] held the choice like something that could still cut either way. Harborwick's foghorn answered from the river again—low enough to feel in the ribs—while [player_name] held the choice like something that could still cut either way.

Corrugated steel held the fog like a throat. Inside: warm shredder smell, a routing stamp, ledger page waiting like a blade, and still no hard ID waiting to baptize anyone. Catching the clerk here meant ending the chain in motion. Pressing Owen for a partial meant dragging family confession into warehouse dust before the clerk bolted. Jake's flashlight painted rust and soap. A distant hinge complained. [player_name] drew a breath that tasted like unfinished trust and felt the next layer arrive on that sound—hope still arguing, dread still armed, Harborwick listening through metal.`,
  textHot: `The red door gave on the third shove, and [player_name] felt the give in her cunt as much as in her shoulders—breach as bodily fact, Jake Akers's weight translating into wet heat she had no business bringing into a crime scene.

Pre-dawn fog soft-fisted the warehouse. Salt. Rust. Chain-link. Foghorn in the ribs and lower. She stayed at his shoulder, mid-twenties, flashlight low, thighs already tight from the way he moved—mid-thirties, scar catching sodium, brutal charm banked into steel that somehow failed because when his coat brushed her breast in the narrow bay her nipples peaked and her clit throbbed once like a traitor with a badge kink. Renny's absence walked with them. Cho's *unidentified* still ruled the upriver bones. Charm still only *like*. Hope and dread shared the dark with a third animal: want.

"Clear left," Jake murmured, and the Solis-flinch lived under the words—hint only, early push, sealed file, hallway chaos, charm as armor. Broken should not be this hot. He wore broken like cologne she wanted to lick off his pulse while clearing cold-storage. Condensation. Bleach ghost. Diesel. Blood-rust as mystery texture, not gore-porn—old-penny smear, catalogue, no funeral. Entry did not christen bone. Entry made [player_name] wet with adrenaline and proximity.

They found the clerk's ghost first: invoices half-shredded, city routing stamp, Renny's dared initials scratched into wood, cigarette butt, warm shredder basket. Jake's pen scratched. Notebook spine cracked. When he moved [player_name] behind him at a metal-on-metal sound, his hand on her coat was brief and professional and shot straight to her pussy anyway—claim, shield, unfinished fuck translated into fabric.

"Someone left in a hurry," he said. Grey-green eyes flicked to her mouth in the dark. "Or someone is still here. Stay behind me. If you get scared, hand in my coat. If you get wet from the dark, tell me later when Ellison cannot smell it on a report."

She almost moaned at *later*. They moved. Generator carcass. Zip ties. Silver display tray missing teeth—cousin of a bracelet gap, probability not baptism. Ledger page with Owen's festival-week dates in someone else's hand. Hope argued. Dread answered. Bones unnamed. [player_name]'s throat tightened and her cunt clenched empty in the same breath; grief and want refused to queue separate rooms.

Jake stopped at a frost-latched door. Breath ghosted. His body heat licked her front when she nearly walked into his back. "Two verbs," he said, velvet-blade quiet. "Catch the clerk in the warehouse—live link, warm shredder, the pulse Renny mapped. Or press Owen with what this room proves until he confesses partially—dates, companions, lullaby teachers—while a perimeter team owns the footsteps. Catch living steel. Or squeeze the stepfather. Both move. Neither names Renny among the dead. Both leave me hard from watching you survive this dark like it is a kind of sex."

Rain needled the roof. Radio crackle—Ellison asking status, the raid wound under his charm caution without the name. Jake answered shorthand: inside, warm shredder, no hard ID. He did not say that [player_name]'s breath on his neck was a problem. He did not say sealed-file risk. His boot found her shoe in the dark—dare—and she had to bite her tongue on a sound the warehouse would have loved.

"If we catch the clerk," she whispered, sandpaper, "we spend the breach on the living link." Her breast brushed his back; both went still; electricity. "If we press Owen, we spend this room as a blade across glass."

"Both hurt the quiet-makers," Jake said. Brutal charm failing into hunger. "Both keep you close enough to feel whether grief makes you careful or soaked and reckless. I push early and people bleed. I will not rhyme that hallway with this bay—but I will put my mouth on yours for one second if we live through the next five minutes and you ask with your eyes. Your map. Your call. Dawn is coming. So is whoever owns those footsteps."

[player_name] flexed fingers in his spare glove and felt seven years and one unfinished fuck braid into a verb. Soft surveillance and raw admissions and leaks had poured into this bay. The kept scraps still waited elsewhere. Breach was not emptying every pocket. It was choosing which living man to spend Renny's geography on while Jake's heat made her thighs slick and Cho still refused a hard ID.

Footsteps nearer. Jake's flashlight low. Mid-thirties bulk as shield. Mid-twenties pulse as drum between her legs. Remains unnamed. Charm probability. Owen's costume and a clerk's initials sharing dust with her want.

"Decide before the footsteps decide," he whispered against her ear, breath a filthy kindness. "Catch the clerk—or press Owen for partial confession. I dig either way. I do not let you bury hope. I also do not pretend my cock is professional when you shake like that against my back."

The cold found the gap at her collar and somehow made the heat lower worse. [player_name] watched Jake's cracked knuckles on the flashlight and imagined them elsewhere—on her hip, in her hair, holding her quiet against corrugated steel while the warehouse hummed and footsteps owned the dark. Attraction was blasphemy before dawn and it came anyway, thick as diesel ghost, specific as the warm shredder basket under her glove. She hated how wet fear made her. She also shifted closer to his back until her belly touched his coat and both of them breathed like people who had forgotten Ellison's radio existed.

"You are shaking," Jake murmured without turning. Not unkind. Unkind would have been easier. "Tell me if it is the clerk or me."

"Both," [player_name] admitted, mid-twenties honesty wearing a flashlight beam. "Mostly you. That is the sealed-file part."

His laugh was silent and filthy. "Then choose a verb before I choose for us with my mouth. Catch the clerk and I will run you out of here afterward like a man who knows adrenaline needs a landing. Press Owen and I will put you in the observation booth where you can watch him crack while I stand behind your chair close enough that you feel what watching does to me. Either way you leave this bay knowing I wanted you through the whole clear-left. Neither way names Renny on a tag. Cho still speaks first. Hope still has a throat. I am trying to keep mine professional and failing where your breath hits my neck."

Blood-rust stayed mystery texture on the threshold of memory—penny color, catalogue, no eroticized corpse, no gore-porn, only the smell of hurry and the refusal to baptize. The silver tray missing teeth winked like a dare. The ledger page waited like a blade. his old partner smoked under Jake's silence when the radio had said nothing with teeth; hint only; [player_name] wanted to put her mouth on that bruise and knew she would, later, if later survived the footsteps.

She catalogued her own pulse: throat, wrists, clit—professional then personal then fused. Renny had been scared under anger here. Standing here now, bravery was fear that had chosen heat as well as justice. Catch living steel or squeeze Owen across glass. The unfinished fuck at her front was not separate from the map—it was what trusting Jake Akers cost in Harborwick dark when clean distances had already failed them both.

The warehouse hummed. [player_name]'s cunt throbbed in time with distant hinge complaint and Jake's cracked-knuckle patience. Catch the clerk in endgame steel—or squeeze Owen with this room as lever. The hook hung in the warm shredder and in his almost-mouth and in unanswered science while fog decided what to reveal through a red door that had given—and through a body that had given just as easily, traitorous and alive, hope still legal, dread still biting, Renny's fate still contested on purpose.

Captain Mara Ellison would smell want on a report if they were not careful. Owen's lawyers would call the sister a contaminating presence with damp eyes. Cho would want fluids from the smear, not sisters inventing funerals from penny color. Jake sanded edges and still looked at [player_name] like ruin and rescue might be the same verb if she would lean one inch closer. She did not lean. She chose with her mouth still tasting rust and soap. The silver tray missing teeth winked. The ledger page waited. The footsteps owned a future tense. Mid-twenties stubbornness wore damp hair and a coat that suddenly felt like too little armor against mid-thirties hunger banked under a badge. Trust unfinished. Heat unfinished. Hard ID unfinished. The next layer arrived on a hinge and a dare.

Jake's flashlight beam trembled once when her hip brushed his—want under tactical quiet. "Clerk in the act," he breathed against her ear, "or Owen pressed until he cracks a partial in this dust." His free hand found the small of her back inside her jacket, fingers spanning warm skin, then stilled like a safety on. She was wet from breach-adrenaline and the shape of him in the dark. Hard ID unfinished. Heat unfinished. She spoke the choice into the fog between his coat and her mouth before the hinge complained again and took the option from them.`,
  choices: [
    { id: "scene8g", text: "Catch the clerk in the warehouse", textHot: "Catch the clerk in the warehouse" },
    { id: "scene8h", text: "Press Owen until he confesses partially", textHot: "Press Owen until he confesses partially" }
  ],
};
