export default {
  id: "scene2b",
  layer: 2,
  title: "What the Drawer Kept",
  text: `She did not take him to the precinct. She kept Detective Jake Akers on the stoop long enough for the fog to lick the evidence bag in his hand, then stepped back and let the apartment swallow them both—rain-damp coats, burnt-coffee breath, the particular silence of a place that had been arranged around an absence for seven years.

"Upstairs," [player_name] said. "Her room. If you're going to dig, dig where I actually live with it."

Jake's half-smile flickered—approval or hunger, hard to separate on a man who wore charm like a blade left casually on the table. He wiped his boots on the mat without being asked. Mid-thirties, shoulder holster a dark suggestion under the coat, notebook already half-open as if the building itself were a statement. Scarred knuckles whitened once on the stair rail. "Lead the way. I'll try not to touch what you don't put in my hands."

The stairwell smelled of old carpet and pier salt that never fully left Harborwick drywall. Second floor. The door she almost never opened without bracing first. Renny's room: curtains drawn against the warehouse glare across the street, a twin bed made too neatly, posters faded at the corners, a desk with a dust line where a laptop used to sit. On the dresser, a silver charm bracelet in a shallow dish—every charm present except the tiny anchor. [player_name] had kept the bracelet the way some people kept vigil lights. Not as proof of death. As proof of unfinishedness.

Jake stood in the doorway a full three seconds before entering, as if crossing the threshold required a different warrant than the one in his pocket. When he did step in, he did it quietly. He set the evidence bag on the desk blotter so the upriver charm lay parallel to the empty link on Renny's bracelet. Side by side they looked like a question asked twice in different dialects. Unidentified remains. Lab pending. Age range broad. Cho's caution. Ellison's pressure. None of that lived in this room the way the missing charm did.

"Teenagers keep whole cities in drawers," Jake said. Not soft exactly—careful. The scar through his left eyebrow caught the weak lamp light when he tilted his head. "May I?"

[player_name] nodded. He opened the top drawer with two fingers—scarred knuckles gentle on painted wood. Folded hoodies. A tangle of festival wristbands. A composition notebook with Renny's looping hand on the cover—*DO NOT* underlined three times, then a heart drawn beside it as if secrecy and affection had always been roommates. Jake did not open the notebook. He set it on the desk beside the charms and looked at [player_name] instead.

"Your statement said she left the pier with friends," he said. "The friends we found said she peeled off alone toward the water. Somebody is wrong, or somebody is kind. Kindness gets people killed in my experience—or at least gets them missing." The charm in his voice turned briefly ugly, then smoothed. "I'm not accusing you of murder. I'm accusing the night of having more rooms than your paperwork showed."

She sat on the edge of Renny's bed. The mattress sighed. Outside, rain found the window in soft ticks. Somewhere downstairs a pipe knocked; Harborwick buildings always sounded like they were thinking. [player_name] looked at the bracelet, then at the bagged charm that might match and might not, and felt hope and dread braid so tightly she could not tell which strand was cutting her palm.

"I searched until dawn," she said. "Fog horn. Empty pier. Owen told me she'd run off—said she'd gotten into something with friends, money trouble he didn't want on a police report because it would follow her. I was nineteen. I wanted to believe the version that kept her alive and kept the family from detonating on a sidewalk."

Jake's pen appeared. He wrote without looking down, a trick of men who had taken statements in worse rooms than this. "Owen Vale. Stepfather. Estranged now?"

"He calls. I don't invite him up." She swallowed. The kept detail pressed at her teeth: Owen near the pier that night with someone who should not have been there—not a friend of Renny's, not a festival face, a man whose posture had said *business* while the music played. She had seen them. She had accepted Owen's story anyway. She had left him off the official page.

Jake circled the room once, slow. He stopped at a photo tacked above the desk: Renny and [player_name] on the pier the summer before the vanishing, wind in their hair, the bracelet catching sun. His finger hovered without touching the paper. "Captain Ellison thinks bringing me into a bedroom contaminates the chain. She'll side-eye this visit in the morning log—she side-eyes anything that smells like I got too close." A dry breath that wanted to be a laugh and failed. "Dr. Cho thinks silver charms are statistically promiscuous—half the teenagers in Harborwick lost jewelry to the river that decade. Me?" He glanced over his shoulder, and the smile he gave her was not clean-cut anything. It was the smile of a man who had secrets stacked in a desk drawer of his own and knew exactly how heavy they sat. "I think people tell the truth faster when they're standing inside what they lost. Also when they're standing next to someone who won't pretend the truth is gentle."

"You enjoy this," [player_name] said. Not quite a question.

"I enjoy finishing things." He turned fully. Coat open, rain-dark at the hem, eyes tired and bright at once. "I don't enjoy watching sisters vanish into fog while families edit the night into something livable. There's a difference, even if it uses the same mouth." A beat. Cracked knuckles flexed against his notebook. "I had a different life before cold cases. Days I don't open certain folders if I need to be decent to a witness. Sealed ones. There was a—" The word *partner* rose and he flinched from it as if it burned; whatever name belonged there stayed unspoken. "Anyway. Today I need accuracy. Tell me what you saw on the pier that you never wrote down."

The lamp buzzed. Renny's hoodie in the open drawer showed a frayed cuff [player_name] had meant to mend for seven years. The bagged charm gleamed like a held breath. She could put Owen on the record right here—name him at the water, hand Jake the kept thing like a live wire—or she could keep Owen off the page a little longer and push Jake toward festival witnesses first, buy time, protect whatever fragile architecture still held the family name together while Cho's lab argued with bone.

Jake waited with his notebook open and his body too present for a professional visit. He smelled like rain and precinct coffee and something metallic underneath, like a man who had stood too close to violence and never fully washed it off. Brutal charm. Sleep-deprived competence. A detective who looked at her as if cooperation and confession were neighboring doors and he intended to lean on both.

"Kids in hallways learn which doors not to open," he said suddenly, almost a joke—and then the joke died mid-air, gone hollow, gone somewhere sealed. He did not apologize for the silence that followed. He only tapped the evidence bag once, lightly. "Ellison wants a status note by morning. I can write that we reviewed personal effects and you're cooperative. Or I can write that a familial witness amended the festival timeline regarding Owen Vale. Or I can write that we're pivoting to carnival vendors and the pier security gap between 11:40 and 12:15, and leave your stepfather's name where you left it seven years ago—for now. Those remains are still unidentified. That charm *might* be hers. I will not stand in this room and call your sister dead to make a captain's spreadsheet prettier. I also will not let a maybe go soft while somebody who was on that pier sleeps easy."

[player_name] stood. The room felt smaller with both of them in it—grief and attraction and procedural dread sharing the same air. She thought of Renny's looping *DO NOT* on the notebook cover, of Owen's voice in the fog, of Jake's scarred eyebrow and the files he would not open on kind days and the partner-shaped flinch he would not explain. The choice was not between truth and silence exactly. It was between which door she opened first while hope and dread still both fit in her lungs.

Rain thickened on the glass. Across the street a warehouse window reflected their lamp like a second, colder room. Jake closed the distance by half a step—not touching, close enough that the rain on his coat was a weather system she could enter. Scarred knuckles held the notebook shut as if it might try to speak for him.

"Tell me about Owen on the pier," he said quietly, "or tell me to chase witnesses and keep his name off my page tonight. Either way, [player_name], I leave this room with more than I brought. That's the deal when you invite a man like me upstairs—badge, buried files, and a bad habit of hearing the cuts in a story."

The fog horn called from the water. The bracelet in the dish did not move. The bagged charm did not confess. And [player_name] understood that whatever she said next would rearrange the furniture of the next seven years—or the last ones.`,
  textHot: `She did not take him to the precinct. She kept Detective Jake Akers on the stoop until fog beaded on the evidence bag and on her own mouth, then stepped back and let the apartment take them—rain-damp wool, burnt coffee, the heat of a man who had looked at her in a doorway like unfinished business he intended to put his hands on carefully.

"Upstairs," [player_name] said, and felt the word land low in her belly. "Her room. If you're digging, dig where I sleep with it."

Jake's half-smile cut and warmed at once. Charm as weapon. Charm as wound. He wiped his boots, followed, notebook already hungry. Mid-thirties, holster a dark line under the coat, scarred knuckles whitening on the stair rail, the kind of body that made stairwells feel narrower. "Lead. I'll touch what you give me. I'm worse when I'm patient."

Second floor. The door she braced for. Renny's room opened around them like a held breath: drawn curtains, too-neat bed, faded posters, the silver bracelet in its dish missing the tiny anchor. [player_name] had kept it the way the body keeps a bruise—tender, informing every movement. Jake paused in the doorway long enough for her to feel his gaze travel the space and then, briefly, her: throat, mouth, the pulse she could not hide. He entered quiet. Set the bagged upriver charm on the blotter beside the empty bracelet link. Two silvers. One question. Remains still unidentified. Cho still cautious. Hope and dread sharing [player_name]'s ribs like hands.

"Teenagers keep cities in drawers," Jake murmured. The scar through his eyebrow caught lamp light. Up close he smelled like rain and coffee and a metallic undertone that made her think of other rooms, other years, a past he wore without confessing. "May I?"

She nodded. His fingers—careful, sure, knuckles mapped with old impact—opened the top drawer. Hoodies. Festival bands. A notebook that said *DO NOT* in Renny's loops with a heart beside the warning. He did not open it. He set it down and looked at [player_name] as if she were the document.

"Your statement said friends," he said, voice pitched for the space between collarbone and ear. "Friends said alone toward the water. Somebody edited. Kindness gets people missing." The ugliness in the charm smoothed into something almost gentle and somehow more dangerous. "I'm not calling you a killer. I'm saying the night had more rooms. And you're standing in one of them with me."

She sat on Renny's bed. Mattress sigh. Rain on glass. Her thighs registered the give of the mattress and the fact of him standing over the desk like a weather front. "I searched till dawn. Owen said she'd run—money, friends, don't put it on a report. I was nineteen. I wanted the version that kept her breathing and the family off the sidewalk."

Jake wrote without looking at the page, eyes on her mouth when she spoke Owen's name. "Estranged now?"

"He calls. I don't let him up." The kept thing surged: Owen on the pier with a stranger whose posture said business while the festival sang; [player_name] seeing; [player_name] swallowing; [player_name] leaving him off the page. Want and guilt tangled until she could not tell whether the heat under her skin was shame or the simple animal fact of Jake Akers in her sister's room looking at her like truth was a kind of undressing.

He circled once. Stopped at the photo of them on the pier—wind, sun, bracelet flashing. His finger hovered. "Ellison thinks a bedroom contaminates. She'll side-eye this in the morning—she always side-eyes when I get close to a witness." Dry. Almost bitter. "Cho thinks charms are promiscuous. Me?" He glanced back, smile not clean, smile like a man who kept sealed files for days he needed to be decent and today was not one of those days. "I think people tell the truth faster inside what they lost. And faster when someone refuses to pretend the truth won't put its mouth on them."

"You enjoy this."

"I enjoy finishing." He turned. Coat open, rain-dark hem, tired eyes bright. The room shrank. Scarred knuckles flexed once against the notebook—quiet crack of bone-habit. "I don't enjoy sisters vanishing while families sand the night smooth. Different appetites. Same mouth." A step closer—not touching, close enough that her skin mapped the heat of him. "I had another life before cold cases. Folders I don't open when I need to be soft. Sealed." He started to say *partner* and flinched from the word as if it had teeth; the name behind it—whatever name—stayed buried. "Today I need what you saw and never wrote. Pier. Owen. The detail that still lives under your tongue."

Lamp buzz. Frayed hoodie cuff. The bagged charm gleaming like something that could be pressed between teeth. She could hand him Owen now—live wire, name at the water—or keep Owen off the record and push him toward festival witnesses, buy hours, keep the family architecture from collapsing while her body betrayed her by noticing the way Jake's throat moved when he swallowed.

He waited with the notebook open and his attention on her like a hand at the waistband—present, not yet claiming. "Kids in hallways learn which doors not to open," he said, almost joking—and the joke died mid-air, hollowed out, sealed away. He did not explain. He only let the silence hurt for a second, then softened his voice into something intimate and sharp. "Ellison wants a morning note. I can write cooperative personal effects. I can write amended timeline: Owen Vale at the pier. Or I can write witness pivot—carnival vendors, the 11:40 to 12:15 security gap—and leave your stepfather where you buried him in the paperwork. For now." One fingertip tapped the evidence bag; the sound went through her. "Remains unidentified. Charm *might* be hers. I will not kill your sister with a maybe to please a captain. I also will not let a man who was on that pier sleep easy while you look at me like that in this room."

[player_name] stood. Grief and want and dread shared the air; her breath felt too loud. Renny's *DO NOT*. Owen in the fog. Jake's scarred eyebrow and partner-shaped flinch and sealed past and the particular brutality of a man who could make cooperation feel like being wanted. Rain thickened. Warehouse glass across the street threw their lamp back like a colder twin. He closed the half-step. Still not touching. Close enough that if she rose onto her toes she would taste rain on his mouth. The almost hurt. Scarred knuckles held the notebook shut hard enough that she imagined the paper creasing.

"Tell me about Owen on the pier," he murmured, and the words felt spoken against her pulse, "or tell me to chase witnesses and keep his name off my page tonight. Either way I leave with more than I brought. That's what happens when you invite a man like me upstairs—badge, bad history, sealed files I won't open even for you yet, and a bad habit of finding the heat people hide under loyalty."

Fog horn from the water. Bracelet still. Charm unconfessed. [player_name]'s body held the choice the way it held breath before a kiss: Owen named into Jake's hands, or Owen shielded while festival ghosts got the first interrogation—and either path ran through the narrow space between her and a detective who smelled like coffee, rain, and unfinished violence, looking at her as if the next sentence might finally let him touch what the case kept calling evidence.

His coat sleeve brushed her forearm when he shifted—accidental, or practiced enough to look accidental—and heat ran from the contact straight to the base of her spine. [player_name] did not step back. Neither did he. The notebook stayed closed in scarred hands; the evidence bag stayed face-up like an unfinished dare. She could smell the pier on him even here, as if Harborwick fog had followed them upstairs on purpose. "You don't have to trust me," Jake said, softer now, mouth close enough that the words warmed the air between them. "You only have to decide whether Owen gets tonight or the vendors do. I'll still be standing in this room either way—wanting the truth, wanting—" He cut himself off with that half-smile that was half wound. "Wanting more than Ellison would approve. Choose before I forget which hunger I'm supposed to feed first." The fog horn called again, lower, and her pulse answered it as if the water itself were listening for which lie she would keep.

She could feel Ellison's future side-eye like weather already moving inland. She could feel Cho's unidentified remains like a held breath across town. She could feel Jake waiting—not clean, not safe, charming in the way a blade is charming when you are the one who asked it upstairs—and understood that whatever she gave him next would not only move the case. It would move something in her that seven years of quiet had tried to keep still—something low and shameless that had woken the moment his coat sleeve brushed her forearm and refused to go back to sleep.`,
  choices: [
    { id: "scene3c", text: "Tell Jake you saw Owen on the pier that night", textHot: "Tell Jake you saw Owen on the pier — put the kept heat in his hands" },
    { id: "scene3d", text: "Keep Owen off the record — push festival witnesses first", textHot: "Keep Owen off the record — push witnesses while this tension holds" }
  ]
};
