export default {
  id: "scene3c",
  layer: 3,
  title: "What She Kept",
  text: `Renny's room still smelled faintly of peach-plastic perfume and closed windows—hoodie folded on the chair like a person who might return, silver charm bracelet in a dish on the dresser with its missing-anchor gap as loud as a shout. Harborwick rain freckled the glass. Downstairs the building settled. Upstairs, [player_name] had finally said the thing she kept: Owen near the pier that festival night, Owen with someone who was not supposed to be there, Owen's story that Renny had run off with friends accepted because the alternative would have blown the family apart.

Jake Akers stood just inside the doorway as if crossing the threshold fully would make him responsible for the ghost. Mid-thirties. Coat dripping onto Renny's old rug. Cracked notebook open, then shut, then open again—hands that did not know what to do with tenderness when evidence arrived wearing a sister's bedroom. Sleep bruised under his eyes. That half-smile tried to arrive and failed halfway, leaving something rawer: brutal charm with the blade turned inward for once.

"Say it again," he said softly. Soft was worse in a dead teenager's room—except Renny was not confirmed dead; the upriver remains were still unidentified, Cho still pending, hope still allowed to sit on the bedspread like a rude guest. "For me. Not for Ellison. Owen Vale was on the pier. You saw him. You left him out of every statement that mattered."

[player_name] said it again. Mid-twenties voice steady until it wasn't. She watched Jake absorb the kept detail the way men absorbed bullets when they had practice—jaw tight, eyes going somewhere sealed. For a flash she saw the partner-flinch again, the almost-name: So— cut short. Hallway kid weather. IA weather. He blinked it away and was only detective and something hungrier, standing among Renny's posters and the bracelet gap.

"That puts him in reach," Jake said. He did not celebrate. He paced once—three steps to the window, three back—like a man measuring a cell. "I can bring him in hard. Cuffs. Precinct light. Ellison smiling like a knife. Or—" He stopped in front of [player_name], close enough that rain-smell and burnt-coffee ghost filled the small room. "Or you ask me for something softer because he is still family-shaped in your head, and I decide whether softness is mercy or another obstruction dressed as love."

The hoodie on the chair seemed to listen. [player_name] thought of Owen's voice inventing friends Renny ran off with; thought of her own mouth agreeing; thought of seven years of protection that had protected the wrong silence. Jake's mismatched knuckles flexed at his side—rooms without case numbers living under the badge. He did not dump Nina Solis on Renny's carpet. He only let the sealed past sit behind his eyes while he offered [player_name] a fork made of loyalty and law.

"I am not clean," he said, almost conversational, which made the confession feel like a trapdoor. "Charm got me out of places resumes do not list. A raid went wrong in a hallway that still shows up when kids laugh at the wrong time. There is a folder with my name adjacent to a name I will not finish saying in your sister's room." His smile flickered—weapon, wound. "That is not an excuse. That is a warning. If you beg me for a soft net on Owen, understand you are asking a man with sealed consequences to choose restraint. If you warn Owen that I am coming, understand I will know the smell of a tip even if I cannot prove it tonight."

Rain thickened on the glass. Somewhere downstairs a neighbor's TV laughed. [player_name] sat on the edge of Renny's bed because her knees had opinions. Jake stayed standing, refusing the chair as if sitting would domesticate what she had just handed him. He looked at the bracelet dish, at the missing charm's absence, at her mouth.

"Cho still has not ID'd the remains," he reminded her, gentler, and the gentleness hurt. "We do not get to bury Renny to make Owen's arrest feel cleaner. We also do not get to pretend your silence was nothing. You told me. That matters. What you do in the next hour matters more."

He outlined the hard path without relish: pick Owen up, interview under fluorescents, let Ellison smell blood in the water, risk the family detonating while science still refused to name the upriver dead. Then he outlined the soft net: surveillance, patience, watching Owen's hands before cuffing them, giving [player_name] a chance to be wrong about how deep the rot went—or right without fireworks. Both paths led through Jake. Both paths could destroy what little she had left.

"I can be the badge that kicks the door," Jake said. "Or the shadow that waits outside it. What I cannot be is the man who pretends you did not just put Owen on that pier." He leaned a shoulder to the doorframe—old habit, sightlines, wrong-room muscle. "Beg me for the soft net if that is the loyalty you can live with. Or walk out of here and warn him I am coming, if protection still wears Owen's face for you. Either choice writes the next layer of what you kept."

[player_name] tasted peach ghost and rain and the metallic edge of a truth finally spoken. Jake waited with his notebook shut like a held breath, mid-thirties and dangerous even in mercy, brutal charm quiet for once into something that might have been respect. The hoodie did not move. The bracelet gap did not fill. The remains inland stayed unnamed. Only the choice moved—soft net or warning—while Harborwick weather pressed the glass and Renny's room held them both like unfinished evidence.

Ellison's name hung unspoken between them like another kind of weather. If Jake went hard, the captain would get a clearance narrative and a family scandal in the same afternoon; if he went soft, Ellison might smell sandbagging and punish them both. [player_name] understood politics suddenly as a bodily thing—the way her stomach dropped when she imagined Owen in cuffs in front of neighbors who had brought casseroles the first year and nothing after. Jake watched that understanding land and did not exploit it with jokes. Brutal charm could wait when the wound was useful.

"Soft does not mean safe," he clarified, voice still low, still soft, still worse. "Soft means I watch him burn a phone or move a box and I decide when to close my hand. Soft means you live with knowing you asked for that delay. Hard means we end the wondering faster and start a different grief." He glanced at Renny's hoodie again, then away, as if eye contact with absence required manners. "I have done both kinds of doors. The sealed ones taught me that speed and justice are not synonyms. Neither are delay and love."

[player_name] stood. The room felt smaller upright. She could cross to him, put her hand on his wet coat, beg. She could walk past him down the stairs, find Owen's number, speak a warning that would feel like sisterhood and function like obstruction. Jake did not block the doorway. He only occupied it—choice incarnate, mid-thirties, rain still finding new paths down his temple.

"Whatever you pick," he said, "do not pick it to make me like you. I already like you more than a witness should allow. Pick it for Renny—alive-or-not-yet-named Renny—and for the version of yourself that can sleep after." The notebook stayed shut. The recorder was not here. This was off-paper heat of a different kind: trust under domestic light, dangerous because it felt almost like care.

Outside, a foghorn called inland faintly. Harborwick refusing to let any room forget the water. [player_name] closed her fingers on the bracelet dish until the silver bit her skin, missing charm loud as ever, and met Jake's eyes across the teenage geography of posters and folded cotton and seven years of kept quiet finally broken. The quiet in Renny's room was not peace; it was a held breath waiting to see whether loyalty would choose cuffs delayed or a tip that could never be taken back once spoken into Owen's ear.

Jake waited in the doorway without crowding her toward either answer, which somehow made the pressure worse. Rain freckled Renny's glass. The hoodie on the chair held its empty shape. Somewhere downstairs a neighbor's television laughed at a joke neither of them could hear. Captain Ellison's clearance hunger sat outside this room like weather; Dr. Cho's unidentified remains sat across town refusing a sister's name; Owen Vale's porch light, if it was on, waited for a tip that would either buy time or burn the map.

"[player_name]," Jake said, and her name in his mouth still sounded like evidence—and like something softer he refused to admit under fluorescent memory. "Soft net means I watch him without cuffs first. Tip means you warn him I am coming. Both leave Renny unfinished. Both leave you responsible for what Harborwick does next."

She tasted peach-plastic and rain and the metallic edge of a choice that could not be walked back. Soft net kept hope breathing and Jake close enough to hurt. Tip kept family intact for one more night and turned her into the leak he would eventually smell. The bracelet dish bit her palm. The missing charm gap stayed loud.

Outside, a foghorn called once, low and unfinished. Inside, Renny's room held its breath, and [player_name] understood that whichever door she opened would still smell like loyalty—and still cost.`,
  textHot: `Renny's room hit [player_name] in the cunt and the throat at once—peach-plastic perfume ghost, closed-window heat, hoodie folded on the chair like a body that might sit up, bracelet in a dish screaming its missing anchor. Rain freckled the glass. She had finally said it: Owen on the pier, Owen with someone wrong, Owen's runaway-friends story swallowed because family meant silence. The confession left her wet-eyed and, traitorously, wet between her thighs from the way Jake Akers looked at her afterward.

He stood in the doorway dripping on Renny's rug, mid-thirties, coat dark, notebook opening and shutting like a nervous mouth. Sleep-bruised. Half-smile failing into raw hunger. Brutal charm with the blade turned in. Not clean. Never clean. "Say it again," he murmured, soft enough to fuck, soft enough to hurt in a room that still waited for a teenager who might not be among Cho's unidentified remains. "For me. Owen on the pier. You saw him. You erased him."

She said it again. Voice broke. Jake absorbed it like a man who had taken worse hits in hallways he would not name—partner-flinch flashing, Solis half-shaped then murdered on his tongue, sealed IA sitting behind his eyes while he stared at her mouth as if truth were a taste. He paced the small room, rain-smell and male heat filling the space until [player_name]'s nipples tightened under her shirt for reasons Renny's posters should have forbidden.

"That puts him in reach." Jake stopped close enough that she felt his warmth on her knees where she sat the bedspread. "Hard—cuffs, Ellison, fireworks. Or soft—you beg me for a net instead of a door kick, and I decide if restraint is mercy or you obstructing with prettier words." His hand flexed; mismatched knuckles; pale thumb-line. "I am not clean. Charm was exit. A raid went wrong. A kid in a hallway. A folder that does not open. I will not dump it on Renny's carpet. I will warn you: asking me for soft means asking sealed guilt to choose patience. Warning Owen means I will smell your tip on him even if I smile while I do."

She ached. Grief and want shared the bed. Jake leaned on the doorframe—sightline habit, wrong-room muscle—and looked at her like confession was foreplay he intended to finish carefully. "Cho has not ID'd anyone. We do not bury Renny to make Owen's arrest erotic. We also do not pretend your silence was nothing. You told me. Now choose how I touch the consequence—soft net on your stepfather, or you tip him that the badge is coming while your mouth still tastes like truth you gave me."

[player_name] wanted, absurdly, to pull him down onto Renny's bed and make the next confession with her body; wanted also to run to Owen and unmake the danger she had just spoken into being. Jake's soft voice made both urges worse. "Beg me soft," he said, gaze dropping to her throat, her breasts, the place her pulse lived between her legs, "or warn him. I will hate neither. I will want you through both—and that is my problem, not the case's." The hoodie listened. The bracelet gap waited. Rain wrote on the glass. The fork was mercy or betrayal, net or tip, Jake's dangerous patience or Owen's head start, while mid-want and mid-ruin shared [player_name]'s skin.

Ellison's politics slid through [player_name] as nausea and heat mixed—hard path meant spectacle; soft path meant Jake's eyes on Owen while [player_name]'s body stayed stupidly aware of Jake's mouth. He clarified soft without kindness: watching someone burn evidence, choosing when to close a hand, living with delay as a chosen sin. Hard meant ending wonder faster. His voice made both options sound like ways he could ruin her and hold her through it.

"I have done both kinds of doors," he said, and the word doors made her think of hallways, kids, Solis almost spoken, sealed folders, his cock hard from adrenaline that was not only about Owen. "Speed is not justice. Delay is not love. Wanting you while we argue about your stepfather's wrists is my private disaster." His gaze dropped frankly over her—throat, breasts, the join of her thighs under Renny's bedspread geography—and climbed again without apology. "Beg soft and I will try restraint with a body that does not prefer restraint. Warn him and I will still want to put you against this doorframe and fuck the guilt quiet for five minutes we do not have."

She stood because sitting had become an invitation she was not ready to speak. The room shrank. Crossing to him meant hands on wet coat, mouth on rain, begging for nets with her lips against his jaw. Passing him meant stairs, phone, Owen's ear, betrayal that would taste like protection. Jake filled the doorway without blocking—offering the shape of capture either way. [player_name]'s cunt ached with decision. Her eyes burned with Renny. Both true.

"Pick for her," Jake whispered, soft as fingers sliding under waistband, "not for whether I like you. I already like you past professional. Pick the soft net or the warning. I will carry either like a bruise I asked for." Foghorn inland. Bracelet biting her palm. Missing charm. Unidentified remains still refusing a sister's name. Mid-want and mid-ruin braided down her spine as she faced the only man who had made telling the truth feel as dangerous as keeping it. Her pulse hammered low and shameless while she weighed Jake's restraint against Owen's freedom, every option leaving her slick with consequence and furious that desire had followed truth into this bedroom like a second detective.

Jake did not move from the doorway. Rain dripped from his coat onto Renny's rug in a slow, filthy metronome. [player_name] felt every drip in her clit like a countdown. Soft net meant nights of watching Owen with Jake's thigh warm against hers in a dark car, his hand sometimes high on her leg when the surveillance went quiet, his mouth promising *later* while Cho's unidentified tray kept Renny from becoming a funeral. Tip meant walking to the hallway, phone hot against her ear, Owen's voice answering while Jake's cocky patience turned into something that would hunt her for the leak—and still, traitorously, make her wet when he finally caught her wrist and asked why family always tasted better than truth until it didn't.

"Come here," he said.

She shouldn't have. She did. Two steps across teenage geography until her breasts nearly brushed his wet wool and his scarred knuckles found her hip under her shirt, thumb stroking the soft skin above her waistband as if mapping where the confession still lived. Heat punched low. She clenched around nothing and hated how empty she felt without his fingers. He smelled like pier fog and burnt precinct coffee and the sealed hallway he would not name—Solis a flinch, partner a swallowed knife, kids-in-hallways a joke that died every time it rose.

"Soft," she whispered against his throat, lips grazing stubble, tasting salt. "Watch him. Don't cuff him yet. Stay close enough that I can feel you choosing me softer while we wait for Cho to refuse a name again."

Jake's laugh was quiet and ruined. His hand slid lower, cupping her through her jeans, pressing the seam into her soaked cunt with blunt, exact pressure until her knees threatened. "Soft net," he translated, grinding once so she felt how hard the case had made him. "Or you tip him—" another press, meaner "—and I smell the leak on your skin by morning, and I still fuck the guilt out of you before Ellison's spreadsheet learns our names."

She rocked into his palm despite Renny's posters watching. Peach-plastic perfume ghost. Missing charm screaming. Unidentified remains across town. Owen's freedom balanced on her tongue. Mid-want held her at the edge while Jake's mouth found the corner of hers—not a kiss finished, a kiss weaponized—and the foghorn called inland like Harborwick itself refusing to let either of them close the tab.

"Choose the verb," he murmured into her lips, fingers still working a slow circle that left her shaking and unfinished on purpose. "Soft net with my hand still remembering this. Or tip Owen and teach me how betrayal tastes when I finally put my mouth where my hand is. Both leave you dripping. Both move what she kept. Neither confirms Renny among the dead. Pick, [player_name]. The bedroom is listening."

She almost came from the unfinished circle alone—edge held by his cruelty and her own refusal to finish before the choice. He pulled his hand away gleaming and licked his thumb where she had marked him, eyes on hers, brutal charm backlit by Renny's string lights. The bracelet dish caught the motion like a witness. Desire and dread shared the small of her back. Soft net or tip: either door left her aching, either door left Jake Akers hard in a dead girl's doorway, either door refused to let science invent a funeral before morning.

Rain thickened on the glass. She pressed her forehead to his damp coat and felt his heart under wool—too fast for a man pretending this was only procedure. Soft net would keep that heart within reach while Owen walked free under surveillance. Tip would put distance and a betrayal between her mouth and his. Either way Renny's hoodie kept its empty vigil, and either way [player_name] left the doorway unfinished on purpose, cunt aching, truth spent, loyalty still choosing its next wound.`,
  choices: [
    { id: "scene4e", text: "Beg Jake for a soft net on Owen instead of cuffs", textHot: "Beg Jake for a soft net — keep Owen uncuffed a little longer" },
    { id: "scene4f", text: "Warn Owen that Jake is coming", textHot: "Warn Owen that Jake is coming — tip him before the badge arrives" }
  ]
};
