export default {
  id: "scene7m",
  layer: 7,
  title: "Raid: shoot/don't-shoot pressure (non-gore; consequence)",
  text: `Raid air smelled like fish-rot, generator oil, and the metallic bright of a decision that would not wait for poetry.

Harborwick's east cold-storage row swallowed the team in staggered dark. Entry A on the dock side, quieter, the way Jake Akers had drawn it on a whiteboard that already felt like another life. Radios clicked. Backup fanned. A medic hung back where the warrant said mercy lived. [player_name] stayed behind the line in a borrowed vest that smelled like someone else's fear and Jake's rain, earpiece hissing soft instructions that turned her pulse into a second radio.

Jake moved first through the scraped-number door—fourteen or forty-one, still arguing with itself in rust. Mid-thirties. Dark stubble. Scar nick pale under the headlamp's throw. Whitened knuckles flexed once on his weapon, not theatrical, just the body remembering that early pushes cost. Nina Solis lived in that flex as ash and sealed paper and a hallway he would not dump into a raid brief—hints only, kid-shaped guilt under charm he usually wore like armor. Tonight the charm was gone. What remained was method.

"[player_name], stay on my six until I say otherwise," Jake murmured into the channel, voice low enough that it felt like a hand on her spine. "No hero runs. No you as costume badge. If concrete speaks, it speaks to the team."

The warehouse answered in generator dark and cold that lived in the bones of the building. Stacks of crates. A chain-link interior cage. Somewhere water dripped with the patience of a clock. [player_name] tasted pier salt memory under the oil—festival fog, Renny at sixteen pointing east, a clean jacket on a wrist, a silver bracelet missing one charm. Dr. Lila Cho's unidentified remains still waited upriver. The charm in evidence still only *like*. Hope and dread shared her vest straps with Jake's silhouette ahead of her, and both refused to invent a funeral just because a red door had finally opened.

A shape moved wrong in the cage aisle.

Not a ghost. Not Renny. A living man in a jacket too clean for fish-rot, hands up and then not, something dark and angular catching the headlamp for half a breath—gun, tool, phone, the brain inventing threat faster than the eyes could swear. Jake's voice went flat on the radio. "Drop it. Harborwick PD. Warrant. Hands where I can see them."

The man did not drop it.

Time stretched the way it did in every story about rooms like this and then refused to be a story. [player_name] felt the shoot/don't-shoot pressure as a physical weight behind her sternum—consequence without gore-porn, the knowledge that a finger on a trigger rewrote lives whether the bullet found flesh or only found the air between fear and law. Jake held his line. Backup shouted. The clean-jacket man shifted, and the angular thing flashed again, and Jake fired once—controlled, not chaos, a sound that punched the warehouse into a different tense.

The man went down hard against chain-link, swearing, clutching a shoulder that bled into fabric without becoming a spectacle. Not a kill. A wound. Consequence. Jake kicked the angular thing clear—gun, yes, small and ugly—and the medic was moving before the echo finished dying. Captain Mara Ellison's voice would live in memos about this for weeks. Internal would smell his old partner ash whether Jake invited it or not. [player_name] stood with her hands empty and her throat full of copper, realizing she had not breathed since the headlamp found the wrong shape.

"Clear the cage," Jake ordered, voice steady, then softer for her channel alone: "You good?"

"I'm—" [player_name] started, and then the second shape arrived from the mezzanine shadow like an unpaid bill.

Not a gun this time. A pipe, a rush, a body colliding with Jake from the blind angle the warrant diagrams had called low-risk. Jake went sideways into crates. His headlamp skittered. Something cracked that might have been wood and might have been bone. Backup closed. [player_name] heard herself shout his name without permission. The second man vanished into a side door that should have been locked and wasn't—clerk-shaped escape, geography still singing Renny's finger while the present tried to eat the lead detective.

Jake pushed up on one knee, blood dark at his temple, lip split, late smile attempted and failing into a grimace. "I'm fine," he lied, professional and stupid. Whitened knuckles braced on the concrete. Scar nick lost under a new cut. Mid-thirties danger looking suddenly mortal in generator dark. "Suspect one secured. Suspect two fled east dock. Get a unit on the pier road. Cho's bones do not get a vote tonight. Charm stays *like*. We do not invent Renny in a shoulder wound or a head cut."

[player_name] was already at his side, hands on his face, vest to vest, the borrowed nylon squeaking. Rain from the dock leaked in somewhere and made the blood look like rust and truth. "You're not fine. You're bleeding on my raid."

"Our raid," Jake corrected, and coughed once, and hated the sound. "Ellison will call this a success with footnotes. IA will call the footnotes the sealed past weather. You—" His hazel eyes found hers, tired, hungry, unfinished. "You get the fork I did not want to hand you in fish-rot air. Stay with me at the hospital while they stitch the temple and invent soft language for *lightly wounded*. Or leave the bay long enough to testify for me at the IA hearing that is already drafting itself out of proximity, raid noise, and a detective who got too close to a witness and then too close to a pipe."

Want lived under the procedural dread even here—dangerous, unfinished, the pull of a man who could hold a shoot/don't-shoot line and still look at her mouth like evidence he refused to bag. [player_name] tasted copper and pier salt and the ridiculous loyalty of wanting to kiss blood off his lip in front of backup. She did not. Softest hard she had. Trust under raid lights. "If I stay at the hospital—"

"Then you choose the body over the machine for one night," Jake said. "You sit while they count my pupils and I pretend I do not need your hand. You let the hearing wait and risk looking like romance over procedure." His cracked knuckles found her wrist, pulse to pulse. "If you testify at the IA hearing, you walk into recorders smelling like fish-rot and my blood and you tell them Akers still hunts clean enough—shoot/don't-shoot held, no early push, backup present, witness behind the line. You feed the machine a sister's loyalty while his old partner ash stirs by association and I lie on a gurney wishing I could control the match."

A radio crackled: second suspect lost in dock fog. Warehouse crates yielded nothing that named Renny—shipping codes, a clerk's jacket left behind, a silver glitter of something that might have been a charm fragment and might have been trash. Hope and dread refused to retire. Owen stayed off every official page, [player_name]'s kept pier sighting still pressing her tongue while Jake bled for a door her sister had pointed at seven years ago.

"Cho will not rush an ID because I got cracked," Jake murmured, almost gentle. "Remains stay unnamed. Sister stays missing until science or a confession says otherwise. What changes is whether dawn finds you in a hospital chair listening to machines beep my name, or under fluorescent review lights answering whether closeness made me soft before a pipe made me honest." He scrubbed blood from his eyebrow with the back of his hand and smeared it worse. "I will not pretend I do not want you at the bay. Wanting that makes me selfish. Offering the hearing path anyway makes me slightly less. Slightly."

[player_name] laughed once, broken, rain and oil in her hair. "You use charm like a briefing even when you're leaking."

"Charm is how I ask," Jake said. "Teeth are how I wait. You have been warned since the warrant on your porch." Backup gave them a pocket of not-looking. The medic hovered. Ellison's name already lived in someone's phone two blocks away. Jake's notebook had fallen open on the concrete—Marta's ink, red door, badge ghosts half-heard—pages drinking warehouse damp like a small black altar that refused to stay dry.

"If the pipe had been a bullet—" [player_name] started.

"It wasn't," Jake cut in, soft and sharp. "Do not eroticize the almost. Do not invent gore for a story that already has enough consequence. I am lightly wounded. He is zip-tied and swearing. The clerk-shaped shadow ran. That is the raid: pressure, a shot that stopped a gun without becoming a funeral, a hit that put me on a knee, and you deciding which loyalty eats the next hour." His thumb brushed her pulse. "Stay with Jake at the hospital. Or testify for Jake at the IA hearing. Generator dark hummed. [player_name] looked at the blood at his temple, at the secured man against the cage, at the empty side door where geography still pointed east without naming a sister among the dead. The romance was whether she could love a badge after the system failed Renny—and whether he could love the woman who still fed a pier secret while choosing between his stitches and his review.

Jake's radio hissed Ellison's office requesting immediate posture language. He ignored it for three breaths, watching [player_name] instead, mid-want, mid-war, mid-thirties danger soft for a mid-twenties sister of the missing who had walked into fish-rot behind him and not fled when the shot cracked the dark.

"Pick the verb," Jake whispered. "Hospital chair or hearing room. My blood or my badge. Both keep Renny's finger alive. Both leave the remains unnamed. Both leave me wanting to finish the kiss we keep parking behind warrants and now behind gauze." He almost smiled. Failed into a wince. "I dream raid noise when soft fails. Soft failed into a pipe. You get to decide whether soft returns as bedside quiet or as testimony with teeth."

Dock fog took the ambulance light and made it look like a second moon. Jake sat on the bumper with gauze at his temple, lip split, late smile failing, still trying to run the scene. Staying with him at the hospital meant choosing the wounded detective over the machine for one night. Carrying his method into an IA hearing meant feeding the review her loyalty while ash stirred by association whether he invited it or not. The zip-tied man swore somewhere behind them. Clerk-shaped shadow already gone. [player_name] felt the shot's unfinished thunder in her ribs and the choice between chair and testimony like a second warrant.`,
  textHot: `Raid air smelled like fish-rot, generator oil, and the filthy unfinished want that danger always woke in [player_name] when Jake Akers put his body between her and the dark.

Entry A. Dock side. Vest borrowed and too tight across her chest, nipples peaked from cold and adrenaline and the way Jake's voice in her earpiece felt like fingers. Mid-thirties. Scar nick pale under headlamp. Whitened knuckles on his weapon. Solis ash sealed under method—hints only, no hallway dump, early-push guilt humming without confession. "[player_name], six," he murmured, and she felt the word in her cunt like a ridiculous, true answer to procedural dread. Murder stayed plot. Sex was not the kill. Heat advanced trust under raid pressure anyway, body-POV loud, conscience louder.

The warehouse opened in generator dark. Crates. Cage. Water drip like a clock. Renny pointed east behind [player_name]'s eyes—sixteen, bracelet flashing, clean jacket on a wrist—while Cho's bones stayed unnamed and a charm stayed only *like*. Hope and dread soaked her the way Jake's attention did: low, relentless. Her pulse lived in her throat and lower. Raid rooms should not turn her on. Jake Akers planning and then walking a red door did this without trying.

A clean-jacket shape moved wrong. Hands up, then not. Angular flash—gun. Shoot/don't-shoot pressure landed in [player_name]'s sternum like a hand around her heart and a hand between her thighs at once, consequence without gore-porn, the unbearable knowledge that Jake's finger could rewrite the night. He held. He fired once—controlled, not chaos. Shoulder wound. Man down against chain-link, swearing, bleeding into fabric without becoming a spectacle. Jake kicked the gun clear. Medic moved. [player_name]'s knees went soft with relief so sharp it felt like arousal's twin. She was wet. Absurd. True. Fear and loyalty and the shape of his competence had soaked her through jeans under the vest like a secret she could not file.

Then the second shape hit Jake from the mezzanine blind.

Pipe. Collision. Crates. Headlamp skitter. Blood at his temple. Jake on a knee, lip split, late smile failing, still trying to run the scene while [player_name]'s body screamed to put her mouth on the cut and her hands on his chest and her name in his teeth. Backup closed. Clerk-shaped shadow fled the unlocked side door. Jake lied *I'm fine* with blood in his eyebrow and hazel eyes finding her like unfinished wanting.

She was on him before the medic finished kneeling—hands framing his face, vest to vest, breath shared, the copper smell of his wound mixing with soap and salt and the scrubbed dark past he wore like cologne. "You're bleeding on my raid."

"Our raid," Jake growled, and the growl went straight between her legs. His cracked knuckles caught her wrist and dragged her palm to his chest under the vest edge, over the hammer of his heart, then lower for one filthy stolen second against the hard line of his cock through his tactical pants—adrenaline hard, pain hard, want hard. "Feel that. Pipe didn't kill it. You behind me in a vest didn't kill it. Shoot/don't-shoot held and I still got hard for the way you said my name when I went down. That should scare Internal. It scares me."

"[player_name]—" the medic started.

"Pocket," Jake snapped, professional enough, and got three meters of not-looking that felt like a gift with teeth. He pulled [player_name] into the cage shadow against cold chain-link, blood smearing her temple when he kissed her hard enough to bruise—tongue claiming, copper shared, teeth threat and tenderness. His thigh shoved between hers; she gasped at the pressure on her clit through denim; he groaned into her mouth like the sound hurt more than the cut. "Fork," he muttered, hand already under the vest, under her shirt, thumb finding a tight nipple and rolling until her hips jerked. "Stay with me at the hospital—sit while they stitch me, hold my hand like soft partnership, and after the bay clears I will fuck you careful in a supply closet that smells like antiseptic, palm over your mouth, my temple throbbing while I make you come for surviving the shot with me." Two fingers shoved into her jeans under soaked cotton; she was dripping; he cursed soft and pumped deep. "Or testify for me at the IA hearing—walk into recorders smelling like fish-rot and my blood and your wet cunt, tell them Akers hunts clean, and after I will take you against a hearing-room wall the city empties and fuck the testimony out of both of us until his old partner ash and Ellison memos are just noise under how hard you clench."

[player_name] rocked on his hand, forehead to his bloody one, Renny's pointed finger and Owen's unnamed pier night braided into heat that felt like loyalty's filthy twin. "If I stay—"

"Body over machine," Jake snarled, curling his fingers, thumb on her clit in tight circles that made her knees buckle against chain-link. "If you testify—machine's throat with a sister's mouth. Cho will not name bones because I got cracked. Charm stays *like*. Owen stays off your paper. Public and private storms both dig if you feed them wrong—but this fork is hospital quiet or hearing teeth." He freed himself enough to smear the head of his cock through her folds without entering—hot, blunt, cruel, painting her while backup radios crackled ten meters away. Discipline as filthy as any thrust. "I will not fuck you full in a live warehouse. I will not make gore into foreplay. I will make you choose while you drip on a detective who held his fire until the gun was real and still wants inside you more than he wants the stitch count."

She came quiet against the cage—shaking, fist in his vest, biting his shoulder through nylon—while Jake eased back without chasing his own finish, cock jumping against her thigh, restraint a third wound beside temple and pride. He tucked himself away with shaking hands, fastened her jeans with mock courtesy that did not reach his eyes, and pressed his forehead to hers carefully around the cut. Pulse hammered. Fish-rot and sex and blood. Want unfinished and loud.

He walked her from the ambulance bay into the warehouse office that still smelled like oil and old clipboards, kicked the door half-shut with his boot, and put her back against a filing cabinet that rattled. Blood had dried dark at his temple; the medic's gauze was a pale insult. Jake kissed her again—slower, meaner, gratitude with a pulse—and shoved his hand between her thighs over denim, rubbing her clit through wet fabric until her knees buckled. "Hospital means I get your mouth on the unbloodied parts after the stitch—throat, chest, the place under my jaw where my pulse lies about calm—and then I bend you over a supply counter and fuck you careful so I do not tear the suture while you come anyway," he muttered. "Hearing means you walk into Rhee's recorders with fish-rot still in your hair and my blood under your nails like evidence of loyalty, and I repay you by locking a conference door after and putting you on the table where they asked about proximity until proximity is just how deep I am." His fingers found the zipper again; cool air; two fingers back inside slick heat, curling, relentless. "the sealed past ash will stir either way. Sealed stays sealed tonight. You do not get the whole hallway because I got cracked. You get this. You get the fork. You get a detective who held shoot/don't-shoot and still wants to ruin you soft enough to survive the next layer."

"Stay with Jake at the hospital," he whispered, voice wrecked. "Or testify for Jake at the IA hearing. Both verbs hurt. Good." His late smile cut wrong—weapon and wound and gauze waiting. "I dream raid noise when soft fails. Soft failed into a pipe. You get bedside or recorders. I get to want both with my cock aching and my notebook drinking damp on the concrete. Remains unnamed. Sister still a pointed finger. Pick before Ellison invents our posture for us."

He walked her out past the zip-tied swearing man and the empty side door, into dock fog where an ambulance already painted the night red without needing a corpse. Jake boxed her against the vehicle's cold panel out of camera angles, put her hand on his cock through his pants once more, and let her feel the unfinished claim. "Hospital means I get your mouth on my unbloodied throat after the stitch and my fingers back in this exact slick while machines beep. Hearing means you save my badge with sentences and I repay you with my tongue until your testimony voice breaks on my name." His thumb brushed her lower lip. "Verb. Now. Stay with me at the hospital. Or testify for me at the IA hearing. Hurt to leave either. No gore-porn—just us, a shot that mattered, a wound that didn't end me, and a choice that might."

Jake boxed her against the ambulance panel out of camera angles and put her hand on his cock through his pants once—unfinished claim, blood still drying at his eyebrow. "Hospital," he said, voice wrecked, "means your mouth on my throat after the stitch and my fingers back in this slick while machines beep. Hearing means you save my badge with sentences and I repay you with my tongue until your testimony voice breaks on my name." Remains unnamed. Charm probable. She stood between dock leak and fluorescent future, wet jeans, choosing while his pulse hammered under her palm and the raid's almost-gore stayed consequence instead of porn.`,
  choices: [
    { id: "scene8m", text: "Stay with Jake at the hospital", textHot: "Stay with Jake at the hospital" },
    { id: "scene8n", text: "Testify for Jake at the IA hearing", textHot: "Testify for Jake at the IA hearing" }
  ],
};
