export default {
  id: "scene7h",
  layer: 7,
  title: "Charm + blood: a last hour reconstructed — still short of hard Renny ID",
  text: `Dawn arrived at the warehouse threshold like a reluctant witness, and William Akers rebuilt the last hour with blood-rust and silver instead of a confession.

They did not go deeper than the cold-storage bay. Soft reconstruction—Will's word, spoken like a vow against early pushes. Fog still held Harborwick's pier district in a soft fist. Salt. Rust. Chain-link silvered with wet. A foghorn rolled inland, low enough to feel under [player_name]'s ribs. Mid-thirties detective crouched at the penny-colored smear with gloves already on, cracked notebook open on his knee, scar through his eyebrow catching the first honest light. Brutal charm banked into catalogue patience. [player_name] stood mid-twenties beside him with Renny's absence occupying the air like a third technician, flashlight steady by force, sandwich-bag history already transferred into proper evidence sleeves because Will sanded familial adventuring into chain-of-custody before Captain Mara Ellison could smell it as cowboy.

"Rain started after midnight and stopped before three," Will said. Pen scratched. Notebook spine cracked—overuse music. "Smear dilution says the blood-rust—if it is blood; Cho christens fluids—hit concrete while the surface was wet, then someone tried bleach and missed the threshold lip. Camera cable cut neat between two and four by the oxidation on the copper ends. Cigarette butt is not pier-tourist brand; it is the pack the harbor clerks buy at the kiosk by the old fish auction. Silver fragment under the weatherstrip oriented point-in, as if it caught on exit, not entry. Charm-shaped. Festival-cheap. Cousin of Renny's missing tooth. Not unique. Not baptism."

[player_name] tasted copper where she had bitten her cheek. Dr. Lila Cho's language still ruled the upriver remains: *unidentified*, *pending*, *consistent with* an age range ugly with hope. The river charm still only *like*. This bay charm still only *like*. Hope and dread shared the reconstruction like co-counsel who refused to leave. A last hour built from rust and silver did not christen bone. It only argued that someone had exited this geography in a hurry while a teenager's map still burned behind [player_name]'s eyes.

"Still not Renny," Will said, reading her face before she could bury hope under a smear. "Still a sequence. Still enough to lean on Owen Vale without inventing a funeral. Soft surveillance turned hard on timing and pier statement. This hour turns harder—ledger overlap if we have it, cigarette brand, exit orientation, bleach miss. Owen's across-town alibi continues to costume itself. We do not need a hard ID to ask him what he knows about a warm shredder and a clerk's initials. We need him scared enough to talk partially—or wired enough to talk to the man who taught the lullaby."

Attraction pressed under the procedural pressure even at a crime-scene crouch—soap, salt, scrubbed-dark past rising when Will stood and his coat brushed hers. Mid-thirties hunger banked under mid-twenties grief. Unfinished almost-kisses from rain nights that had no business surviving into blood-rust weather. Trust was the real plot. Trust currently smelled like evidence tags and Will's refusal to let her name the dead early.

When he had almost said *partner* wrong in Ellison's weather, or when Ellison had said it at him, Will's hand had gone to his ribs like checking a bruise that never yellowed. Nina Solis lived in that flinch as hint only: ex-partner, raid pushed early, sealed IA, charm worn as armor over a hallway chaos he would not narrate beside Renny's name. He did not dump it onto the threshold. He let the silence bruise, then spoke with the allergy to lies that made his brutal charm feel like both weapon and wound. "I push early and people bleed. Reconstruction is me refusing to rhyme that night with this bay. We own the hour. We do not invent the body."

[player_name] looked at the bagged silver and the photographed smear and the dead-eyed camera. Renny's hoodie lived folded across town—teenager's cotton, festival night, vanilla ghost, bracelet gap. Seven years ago Owen had taught the friends-and-debt lullaby on a pier while Renny pointed at steel and fear. Today the steel was real under Will's grid references. Ellison would want a narrative by breakfast. Cho would want fibers and serology, not sisters inventing funerals from penny color. The kept secret's remaining scraps—letters, warmer mercies not yet spent—pressed under [player_name]'s sternum without asking to be emptied onto a threshold.

"Two verbs from a reconstructed hour," Will said quietly, for her. He flipped the notebook to a page already stubbed with rain start/stop, smear dilution, cigarette brand, silver orientation, Owen's window collapsing under Cho's timing lean without naming Renny among the dead. "Take Owen's partial confession—put this sequence in front of him until he gives dates, companions, who needed teenagers quiet about harbor traffic. Partial is ugly and usable. Or wire him against the clerk: send Vale back into the chain with a mic and a deal-shaped leash, let him incriminate the living link Renny dared while science still refuses a hard ID. Glass and pressure. Or wire and hunt. Both move. Neither baptizes the bones."

Rain began again, fine as needlepoint on corrugated roof somewhere deeper in the row they were not breaching today. Soft reconstruction held the line at the bay mouth. A generator coughed once and died—grammar-eating ghost confirming geography without granting a name. [player_name]'s palms left damp prints inside Will's spare gloves. Mid-twenties stubbornness wearing damp hair. Mid-thirties detective watching her mouth the way he watched evidence that might burn him.

"If I take the partial," [player_name] said, voice steady by force, "Owen cracks in a room. We spend the hour as a blade across glass. Hope stays legal because Cho has not spoken baptism. If I wire him, we spend the hour as bait—Owen as instrument against the clerk—and I live with using the man who taught me the lullaby as a microphone."

"Both hurt," Will said. Brutal charm flickered velvet-wrong and banked. "Both keep you close enough that I can watch whether grief makes you careful or reckless. Ellison will prefer the wire if she smells clearance ambition. Internal will prefer the partial if they smell me too close to a familial witness. I prefer the truth that does not bury hope under a tip-sheet funeral. Your sister's map built this hour. Your call spends it."

Harborwick fog thinned and thickened as if the city could not decide what to reveal. [player_name] thought of Marta the vendor's warehouse geography, of red doors and cold-storage rows, of jacketed shoulders she still could not invent a face for without becoming Ellison's favorite liar. Public weather, if recordings had walked on other branches, could flatten this sequence into cruelty. Here the sequence was still theirs—rust, silver, rain math, a detective who refused early certainty.

Will bagged a final photo angle. Grey-green eyes flicked from threshold to her throat to the fog beyond chain-link. "Remains unidentified. Charm probability twice over—river and bay—and still not a funeral. Owen's costume has hours left. The clerk has a shredder schedule somewhere that is not this bay. Partial confession spends Vale as a cracked man in a room. Wire spends him as a tool with teeth. I will dig either way. I will not let you cut hope's throat for the comfort of a named tragedy."

[player_name] flexed cold fingers and felt seven years and one unfinished want braid into a verb. Soft surveillance had become hard. Breach had been refused or deferred for reconstruction's sake. The last hour stood on blood-rust texture and silver maybe without earning Renny a hard ID—hope still arguing, dread still biting, science still owed language. Attraction unfinished. Trust unfinished. Renny's fate unfinished on purpose.

"Decide before Ellison's inbox grows teeth," Will said. He did not touch her. The not-touching felt louder than a hand on her waist. "Take Owen's partial confession—or wire him against the clerk. The hook is not only the smear. The hook is whether we spend this hour as glass-room pressure or as a living mic walking back into the chain—while Cho still refuses to finish the naming for us and Harborwick's fog keeps listening."

Captain Mara Ellison would call reconstruction authorized if the tags held and sentimental if a sister stood too close to the lip. Owen's lawyers would call it contamination theater built from festival silver and wishful dilution math. Dr. Lila Cho would call it a useful timeline with hedges she refused to sand off. Will would sand only the edges that kept [player_name]'s access, and still look at her as if the hour had cost him something his sealed-file flinch he would not unpack on wet concrete. [player_name] accepted that the way she accepted pier salt—constant, practiced, already on her skin.

She catalogued the sequence once more in her own mouth, testing it for funeral grammar and finding none: rain window, smear, bleach miss, cable cut, cigarette brand, silver on exit, Owen's alibi costume collapsing under timing lean, Renny's map confirmed as geography not as corpse. Hope still had a throat because the bay refused to say her sister's name. Dread still had teeth because someone had cleaned in a hurry and someone had dropped silver like a missing tooth trying to come home without permission. Choosing partial meant downtown glass and a stepfather's cracked voice. Choosing wire meant sending that voice back into clerk-dark with a mic under the shirt that had taught lullabies. Either verb spent the reconstructed hour. Neither spent Renny early.

Dawn finished arriving over blood-rust and a charm that was still only probability. Will had reconstructed a last hour that stopped short of hard Renny ID on purpose—sequence without funeral grammar. Taking Owen's partial meant sitting across glass with a man who had already lied in softer rooms. Wiring him against the clerk meant hunting with family as bait while science still owed a name. Vendors began pretending not to see. [player_name] stood in wet concrete truth and felt both doors hurt: confession under fluorescent honesty, or a wire that might finally make the harbor answer.`,
  textHot: `Dawn arrived at the warehouse threshold like a reluctant witness, and [player_name] felt William Akers rebuild the last hour in her body as much as in his notebook—blood-rust and silver becoming a pulse between her legs she had no business bringing to a smear.

Soft reconstruction. His word. Fog soft-fisted the pier district. Salt. Rust. Chain-link. Foghorn in the ribs and lower. Will crouched mid-thirties at the penny-colored threshold with gloves on, cracked notebook on his knee, scar catching first light, brutal charm banked into catalogue patience that failed the second his coat brushed her calf and her cunt clenched empty—stupid, traitorous, mid-twenties and damp under a coat while Renny's absence occupied the air like a ghost who refused to chaperone. Cho still said *unidentified*. River charm still only *like*. Bay silver still only *like*. Hope and dread shared the hour with a third animal: want.

"Rain after midnight, stop before three," Will said, pen scratching, spine cracking. "Smear dilution—Cho christens if it is blood. Bleach miss on the lip. Camera cable cut neat. Cigarette brand from the clerk kiosk. Silver under the weatherstrip point-in—exit catch, festival-cheap, cousin of Renny's missing tooth. Not unique. Not baptism. Still not Renny. Still a sequence. Still enough to lean on Owen without inventing a funeral."

Heat flooded [player_name]'s face and the hinge of her thighs. Reconstruction should not feel like foreplay. His voice soft enough to stroke; his refusal to baptize hope; the way he said *still not Renny* like a hand between her shoulder blades keeping her upright and somehow also keeping her wet. When Ellison's weather put *partner* wrong in his ribs, Nina Solis lived in the flinch as hint only—early push, sealed IA, hallway chaos, charm as armor. Broken should not be this hot. He wore broken like cologne. [player_name] wanted to lick the bruise under the catalogue and knew she would, later, if later survived Owen.

Will stood. Soap. Salt. Scrubbed-dark past. His heat licked the air until her clit throbbed once, hard, humiliating beside blood-rust that stayed mystery texture—penny color, no gore-porn, no eroticized corpse, only hurry-smell and science owed. "Two verbs from this hour," he said, velvet-blade for her, grey-green eyes dragging over her mouth. "Take Owen's partial confession—sequence in his face until he cracks dates, companions, lullaby teachers. Or wire him against the clerk: mic under the shirt that taught you quiet, Vale as instrument, living link Renny dared. Glass pressure. Or wire hunt. Both move. Neither names the bones. Both leave me hard from watching you survive silver without burying hope."

She almost moaned at *hard*. Rain needled a deeper roof. Generator coughed and died. [player_name]'s palms dampened inside his spare gloves; when he tugged the wrist cuff straight, his thumb brushed her pulse and her pussy fluttered like the smear had a second meaning. Trust on fire. Badge a different country. Attraction blasphemy wearing evidence tags.

"If I take the partial," she whispered, sandpaper, "Owen cracks in a room. We spend the hour as a blade. Hope stays legal." Her breast rose on the breath; Will watched; she watched him watch. "If I wire him, we spend the hour as bait—and I use the man who taught the lullaby as a microphone while my body—" she bit it; too late; his gaze dropped to the flush at her throat as if he could smell how wet reconstruction made her.

"While your body what?" Soft. Filthy. Professional dying mid-sentence. "Say the case out loud. Say the rest with your eyes. Ellison prefers wire for clearance ambition. Internal prefers partial if they smell me wanting to fuck the familial witness who found the silver. I prefer you choosing before I put my mouth on the place your pulse is hammering and call it a status check."

Blood-rust stayed catalogue. Silver stayed probability. Remains unnamed on purpose. [player_name] catalogued her own pulse—throat, wrists, clit—professional then personal then fused. Renny scared under anger near this geography. Standing here now, bravery was fear that had chosen heat as well as justice. Partial meant downtown glass and Will behind her chair close enough that watching Owen crack would feel like a hand on her thigh. Wire meant sending Owen into clerk-dark while Will wired the mic against [player_name]'s shaking fingers and the almost-touch became a promise for after.

"Both hurt," Will said. Brutal charm failing into hunger. Boot found her shoe—claim, dare. "Both keep you close. Your sister's map built this hour. Your call spends it. I dig either way. I do not cut hope's throat. I also do not pretend my cock is professional when you look at silver like you want to come from not naming her."

Fog argued with itself. [player_name] tasted rust and soap and unfinished fuck. Soft surveillance had become hard. Breach deferred for reconstruction. The last hour stood on charm and blood-rust without hard Renny ID—hope arguing, dread biting, science owed. She wanted his cracked knuckles on her hip instead of a notebook. She wanted dawn and a verb and his mouth. She wanted Cho to stay slower than rumor just long enough.

"Decide before Ellison's inbox grows teeth," Will murmured at her ear, breath a filthy kindness that made her cunt clench. "Partial confession—or wire against the clerk. The hook is the smear and the silver and the way you are shaking. Spend the hour as glass-room pressure or as a living mic. Neither baptizes bone. Both leave you soaked and choosing. I will be the landing afterward if you ask with more than your eyes."

Captain Mara Ellison would smell want on a report if they were not careful. Owen's lawyers would call the sister a contaminating presence with damp eyes and damper judgment. Cho would want serology, not sisters inventing funerals from penny color. Will sanded edges and still looked at [player_name] like ruin and rescue might be the same verb if she leaned one inch closer to the mouth that refused early certainty. She did not lean. She chose with her body already answering—mid-twenties stubbornness, mid-thirties hunger, Renny's fate still contested, Harborwick listening through chain-link while blood-rust and charm rebuilt an hour that stopped short of hard ID on purpose.

She pictured Owen across glass with the sequence as a blade while Will's heat stood behind her chair. She pictured wiring Vale with shaking fingers while Will's hands steadied the mic and then steadied her hips in a stairwell after. Either fantasy made her wetter. Either path kept Renny from becoming a named corpse too early. The unfinished pulse between her legs was not separate from the case; it was trust under dawn light, desire under dread, a detective with the raid wound under his charm silence and a sister who refused to cut hope for comfort. A vendor truck coughed diesel beyond the lot fence, and the vibration found [player_name]'s clit like Harborwick telling a filthy joke at the worst possible shrine. She hated herself for noticing. She also stepped half an inch closer to Will until her shoulder touched his arm and electricity wrote a second sequence under the rain math—want start, want stop, bleach miss on her self-control, exit orientation toward his mouth. He did not kiss her. The not-kissing was louder than contact, a professional cruelty that somehow made her wetter than kindness would have.

"You are dripping on my timeline," he murmured, almost kind, almost not. "Partial puts Vale in a room where I can stand behind you and let you feel what cracking a liar does to both of us. Wire puts my hands on your hands while we dress him in a mic—intimate in the wrong way, useful in the right one—and afterward I take you somewhere Ellison cannot smell and remind your body that hope is allowed to shake. Choose before the fog burns off and the bay stops belonging to us."

[player_name] laughed once, broken, mid-twenties and soaked and furious with a pulse that answered catalogue voice like a vow. his sealed-file flinch silence still smoked under Will's ribs; she wanted that story later, not as dump, as earned bruise under brutal charm. Owen still lived. The clerk still lived. Renny's fate still contested—unidentified remains, dual charms as probability, no hard ID, no funeral grammar. The reconstructed hour had bought them leverage without burial. Spending it as partial confession or as wire was the dare left on her tongue, copper and salt and unfinished fuck braided into one verb she could finally speak without cutting hope's throat.

Dawn finished arriving. Vendors began pretending not to see. [player_name] spoke the choice into the fog between Will's coat and her mouth—partial or wire—while silver winked probability and the smear kept its mystery texture and science still refused to finish the naming for them.

Will's nearness named everything her body already knew while the hour refused to name Renny. "Partial across glass," he said, mouth almost on hers, "or wire him at the clerk and hunt." His thumb swept the inside of her wrist where pulse and want shared a vein; she clenched around nothing and refused to make the corpse erotic—only survival heat, filthy and legal. Charm and blood-rust. Hope still wet. She had to pick before dawn finished turning probability into a crowd of eyes that would invent grief for them.`,
  choices: [
    { id: "scene8h", text: "Take Owen's partial confession", textHot: "Take Owen's partial confession" },
    { id: "scene8i", text: "Wire Owen against the clerk", textHot: "Wire Owen against the clerk" }
  ],
};
