export default {
  id: "scene9a",
  layer: 9,
  title: "Trial path: testify against Owen fully",
  text: `Harborwick Courthouse smelled like wet wool, floor wax, and the particular dread of fluorescent justice—rain needling the tall windows, foghorns answering the river like unpaid witnesses. [player_name] sat in the hard witness chair with Renny's journal logged as Exhibit C on the prosecutor's table and William Akers in the gallery two rows back, mid-thirties charcoal and cracked-notebook stillness, grey-green eyes fixed on her mouth as if her next sentence were a fuse he had already agreed to hold.

Owen Vale sat at the defense table in a suit that tried to look like remorse and mostly looked like money. Estranged stepfather. Family pressure node. The man she had kept off the official statement for seven years because admitting she had seen him near the pier the night Renny vanished—teenager then, missing now—would have blown what was left of the house apart. Full testify meant no soft edges. Full testify meant Warehouse C, clerk initials M.K., midnight trucks, and the pier night spoken under oath without mercy grammar.

Captain Mara Ellison occupied the aisle end of the prosecution row like a weather system in a blazer. She had wanted a sealed drip once. She had gotten a docket instead. Dr. Lila Cho's unidentified upriver remains still waited in careful language on a side table of exhibits nobody was allowed to baptize: age range that *could* fit; a charm that *could* match the missing bracelet piece still upstairs in Renny's room; lab ID pending. Hope and dread shared the gallery like co-counsel who refused to leave. The remains were not Renny until science said so. Rumor had already tried to invent a funeral for ratings. Will shut rumor down every time a reporter found him in the hallway—*pending* was still the only honest word.

The bailiff swore [player_name] in. Mid-twenties palm on a Bible that smelled like other people's lies. She gave her name. She gave the relationship. She looked at Owen once and felt the old porch-butter calm crack into something uglier and more useful.

"On the night of the pier-side festival," the prosecutor asked, "did you see Owen Vale near Harborwick Pier?"

"Yes," [player_name] said. The word scraped. "With someone who was not supposed to be there. I accepted his story afterward that Renny had run off with friends. I kept him off my official statement. Renny's journal names the smuggling and evidence-tampering chain. I am naming it under oath now. Warehouse C. Clerk initials M.K. Owen's late nights. I am not naming unidentified remains as my sister's. Lab identification is pending. Hope is still allowed. Dread is still honest."

Will's cracked knuckles flexed against his notebook spine in the gallery. When the defense attorney's gaze flicked toward the aisle—almost naming a sealed IA file, almost saying Nina Solis the way lawyers say warnings—Will did not flinch for the gallery. The dark past hummed under his badge anyway: a partner's fall, a hallway, a silence that rhymed too hard with a sister kept quiet. Hint deepening into pressure. Teeth showing. Brutal charm filed down to courtroom stillness—velvet sheathed, blade in the way he watched [player_name] like partnership were a vow and not a soft net Ellison could cut.

Cross-examination tried to make her a liar who slept with the detective. Will's jaw flexed; he did not stand; he let her own the answer. "Detective Akers asked me for truth," [player_name] said. "I gave him less than that for too long. Attraction does not invent Warehouse C. Grief does not invent Owen near the pier. The journal is Renny's hand. The USB and map copies are logged. Anyone who wants a funeral before Cho speaks can wait in the rain."

Recess smelled like burnt vending-machine coffee and rain on courthouse glass. Will found her in a narrow witness anteroom that hummed with the same ugly clock tone as interview rooms, notebook closed for once, scar cutting his left eyebrow catching fluorescent light. Pier salt still rode his coat from the walk over. Mid-thirties heat banked under procedural pressure. Mid-twenties shame still tasting like copper.

"You did not soften him," Will said quietly. Not praise exactly. Recognition. "Ellison wanted soft edges for political weather. You gave the chain teeth. Owen's counsel will try to sell you as a scorned stepdaughter with a badge in her bed. You already answered that. The question left is what kind of closing you want when the jury comes back—and what you want from me when the cameras finally leave."

[player_name] tasted rain and Renny's ink and the unfinished almost of a kiss they could not finish under fluorescent justice. "Cho still says pending."

"Cho still says pending," Will agreed. "Charm probability is not an ID. I will not let anyone christen bone for a verdict's convenience—not the press, not Ellison's metrics, not my own hunger for a clean page. Renny stays a pointed finger and a journal until science grows a spine. That is the only honest weather I can offer you in this building."

He almost said Solis then—almost opened the hallway fully—and stopped. The sealed file pressed against the room like a second radiator. "Five years ago I ordered an entry early to protect a CI," he said, voice stripped of briefing grammar. "A teenager in the wrong hallway caught a bullet that was not from my gun and was still from the chaos I chose. Nina Solis took the official fall. I kept a badge and a silence. Your sister's case rhymes. That is why I will not invent a corpse for you, and why I will not ask you to invent mercy for Owen that is really cowardice with better lighting. Full justice cuts clean. Daylight together keeps us in the same weather after. Both hurt. Both are true."

Ellison's heels clicked past the anteroom door—warning without entering. Somewhere down the hall Owen's attorney laughed too loudly. Foghorn rolled inland through the rain-needled windows. [player_name] felt Will shift half a degree closer—blocking nothing cameras could see, offering heat the courthouse must not catalogue—attraction humming unwanted under oath weather: trust climbing her throat like unfinished rain, want banked for a room without bailiffs, grief still holy enough that she would not eroticize the river even in the privacy of her own pulse.

"When this lands," Will murmured, grey-green eyes on her mouth, "you get the next verb before Ellison decides the headline for you. Close the case in daylight with me—together in truth, Renny's fate spoken as honestly as Cho will finally allow, Owen under the weight of what he did without turning your body into the only exhibit that matters. Or cut the family clean—Owen buried in justice so deep the porch-butter calm never gets a second draft, even if the cut leaves you bleeding where a last name used to live. Either way I walk it. Either way I stay. Either way *pending* stays pending until the lab earns a harder word."

[player_name] stared at the anteroom's ugly clock, at Will's cracked knuckles, at the memory of a festival pier that had eaten a sister and a charm upstairs that was still only *like*. Hope still had a throat. Dread still had teeth. Full testify had put Owen under oath with the journal as spine. The verdict weather was coming. Choosing daylight-together meant walking Renny's certainty into a shared life that might still refuse to christen bone until science spoke—and might still ask her to hold Will's Solis ash without making it her job to absolve him. Choosing the clean cut meant family severed at the root, Owen's name finished as justice rather than forgiveness, and a love that had to survive the emptiness where porch lights used to mean safety.

The prosecutor's second round after recess tried to map Owen's money trails onto festival night geography, and [player_name] answered without looking at the defense table—Warehouse C invoices that did not match shipping boards, late-night texts Renny had copied into purple loops, the pier sighting spoken again because repetition under oath was a kind of penance that still refused to invent a corpse. A juror flinched at Renny's age. Another wrote something that looked like a prayer. Will's grey-green eyes never left [player_name]'s profile; mid-thirties stillness as a vow; mid-twenties voice holding while pier salt memory filled her mouth.

Outside the anteroom window rain thickened into Harborwick's evening grammar—foghorns, chain-link, the distant smear of warehouse roofs where a clerk hunt was already moving without needing a funeral first. Ellison passed once more with her tablet and a look that said IA shadows were lengthening whether Will smiled or not. He did not smile. He offered [player_name] water from a paper cup that tasted like precinct bitterness and almost-care. Their fingers touched on the cup rim. Heat. Calluses. A partnership pulse the gallery must not own yet.

"When Cho calls," Will said, low, "you do not owe the jury a softer science or a harder one for Owen's sake. You owe Renny the sentence you can live with after the lights dim. Daylight-together means we take whatever Cho finally says in the same weather—named or still pending longer—and we do not let the city turn your body into the only exhibit that mattered. The clean cut means Owen's name finishes as justice in a file that never gets a porch-light rewrite, and we learn how to love in the empty place where family used to mean safety. I have carried a sealed hallway for five years. I know what clean costs. I know what shared daylight costs. I am still asking you to pick while I can still stand in this anteroom without putting my mouth on yours in front of a bailiff."

William Akers—detective with a dark past humming under brutal charm—watched [player_name] the way a man watches a fuse he has already helped light in a courtroom. Chain-link rattled faintly somewhere beyond the windows. Ellison's tablet chimed in the hallway. A bailiff called for parties to return. Downriver a foghorn answered again, lonely and low.

"You put him under the lights without inventing a corpse," Will said, almost a vow. "Now choose what kind of ending the lights get to keep. Daylight with me—or the cut that buries Owen so clean the city cannot pretend the pier night was weather. I will still want the woman who said Warehouse C under oath. Want is not the verdict. The verdict is which fire finishes what you started when you stopped protecting him."

[player_name] closed her eyes once, felt Renny's journal weight even though the exhibit was downstairs, and opened them on Will's scar and the rain. Unidentified remains still waited upriver. Charm still only *like*. Solis pressure deepened into almost-confession and still not the whole sealed hallway. Attraction and grief shared the anteroom like co-counsel.`,
  textHot: `Harborwick Courthouse smelled like wet wool and floor wax, and the air between [player_name]'s thighs was already too warm for fluorescent justice. Rain needled the tall windows. Foghorns answered the river. She sat in the hard witness chair with Renny's journal logged as Exhibit C and William Akers in the gallery two rows back—mid-thirties charcoal, scar through his left eyebrow, grey-green eyes dragging over her mouth before they forced themselves to Owen Vale at the defense table like professionalism were a restraint he was choosing to keep on for the girl's sake.

Owen wore remorse like a suit that did not fit. Full testify. No soft edges. Warehouse C. Clerk M.K. Pier night under oath. [player_name]'s mid-twenties cunt clenched around nothing when Will's gaze caught hers across the gallery—brutal charm banked for judges, velvet over a blade, the almost of his attention shooting straight between her legs before either of them pretended this was only about a docket.

Captain Mara Ellison sat aisle-end like weather in a blazer. Dr. Lila Cho's unidentified upriver remains still waited unnamed on the side table: charm that *could* match, lab pending, hope and dread sharing [player_name]'s pulse. Not Renny until science said so. Will treated that distinction like sacrament, which somehow made her wetter under courthouse polyester.

She swore in. Palm on a Bible. Name. Relationship. "Yes," she said when the prosecutor asked about Owen near the pier. The word scraped her throat and stroked lower. "Someone who was not supposed to be there. I kept him off the statement. Renny's journal names the chain. I name it under oath. I am not naming unidentified remains as hers. Lab pending. Hope allowed. Dread honest."

Will's cracked knuckles flexed on his notebook. When defense counsel's gaze flicked—almost Nina Solis, almost sealed IA, almost hallway—Will's jaw worked and his eyes stayed on [player_name]'s mouth like her sentences were a clit he was learning through cloth. Hint deepening. Broken men should not be this hot. He wore broken like cologne she wanted to lick off his throat between objections.

Cross tried to make her a whore with a badge. Will did not stand. He let her own it while [player_name] felt slick fabric drag against her clit every time she said Warehouse C. "Detective Akers asked for truth. Attraction does not invent the chain. Grief does not invent Owen at the pier." Will's free hand—visible only to her when he shifted—pressed once against his own thigh hard enough she knew he was hard and choosing not to show it. Reciprocal hunger denied for the record. The hard line of his restraint was its own stroke.

Recess. Narrow anteroom. Ugly clock hum. Will closed the door with his shoulder and the space filled with soap, salt, scrubbed-dark past. Mid-thirties heat. Mid-twenties shaking. "You did not soften him," he murmured, mouth near her ear, breath hot enough to stroke. "Ellison wanted soft edges. You gave teeth. Now the question is what closing you want—and how you want me to fuck the shaking out of you when the cameras leave."

[player_name]'s cunt fluttered. Shame and hunger and grief fucked the same oxygen. "Cho still says pending."

"Cho still says pending." His cracked knuckles ghosted the small of her back, then lower, cupping the curve of her ass through the skirt like a claim the bailiff must not catalogue. "I will not christen bone for a verdict. Renny stays pointed finger and journal until science speaks. That is the only honest weather in this building—and I am hard from watching you strip truths under oath like you were stripping for me."

He almost said Solis fully and then did, voice stripped: "Five years ago I pushed an entry early. A teenager in the wrong hallway caught a bullet from chaos I ordered. Nina Solis took the fall. I kept the badge and the silence. Your sister's case rhymes. That is why I will not invent a corpse, and why I will not ask you to invent mercy for Owen that is really cowardice. Full justice cuts clean. Daylight together keeps us in the same bed after. Both hurt. Both true." His thigh pressed hers. Denim heat. Denied fuck. "I can feel how ready you are. Courthouse carpet is not where I spend that. Choose the ending first."

Ellison's heels clicked past. Foghorn rolled, low enough to feel in [player_name]'s clit and her bones. Will angled her into the anteroom's deeper shadow—still decent enough for politics, private enough that his next words could land between her legs. "Listen," he said, wrecked velvet. "Close the case in daylight with me—together in truth, Renny's fate spoken as honestly as Cho finally allows, Owen under weight, and afterward my mouth on the pulse in your throat every time you remember saying Warehouse C. Or cut the family clean—Owen buried in justice so deep the porch never gets a second draft—and I will take you against the first door that locks and make you come so hard the cut cannot eat the part of you that still wants to be held. Either way I stay. Either way *pending* stays pending. Either way I do not fuck you into christening bone."

[player_name] pressed her thighs together. Slick dragged. A whimper almost escaped. Will's thumb found the inside of her wrist and counted like he was timing an orgasm he refused to give her on courthouse linoleum. "If I take daylight," she whispered, "I will need you in every hallway outside every recess like a filthy sacrament."

"You will have me." His laugh was blade and wreck. "Not inside the courtroom. In the hallway. In the car. In whatever room still smells like rain when you are done putting Owen under lights. If you cut clean, you will have me with your skirt around your hips the second the last camera dies—because I am done pretending partnership does not include the way you soak for competence and the way I get hard for honesty under oath." He shoved his hand carefully under her waistband for one filthy second—two fingers finding her soaked, not entering, just cataloguing—and pulled back like a man who still remembered bailiffs. "Ellison can put IA on my badge. She cannot put IA on how wet you are for full justice. That is mine to spend on a verb."

Hope still had a throat. Dread still had teeth. Charm upstairs still only *like*. Remains still unnamed. Solis ash stirred into almost-full confession and still not every sealed page. [player_name]'s nipples peaked against her blouse where Will's gaze caught them—noticed, banked, promised. Choosing daylight-together meant shared weather and Will's eyes on her mouth through every warehouse mark while her body throbbed through every sentence and Cho's pending still refused to soothe. Choosing the clean cut meant Owen finished as justice, family severed, and a detective who would hold her through the emptiness without asking her to soften the blade.

"Choose," Will said against her temple, cock hard against her hip through charcoal wool, deliberate denial. "Before I kiss you where the bailiff can see and make Ellison's shadow into a headline we did not earn. Daylight with me—or Owen buried clean. Want is not the verdict. The verdict is which fire finishes what you started when you stopped protecting him with your silence."

After the second round she came back to the anteroom shaking—not from fear of Owen's stare but from the filthy metronome of Will's eyes on her mouth through every Warehouse C. He shut the door with his shoulder again, crowded her against the ugly clock wall, and kissed her once—hard, brief, tongue and salt and denied longer fuck—then broke it like a man who still remembered fluorescent justice. "[player_name]," he rasped against her lips. "You say the chain like you are coming on the word. I felt it from the gallery. My cock has been useless and sworn through every pier-night sentence, and I am not sorry. Daylight-together and I will spend the night teaching your cunt what shared weather feels like when the verdict is still drying. Clean cut and I will fuck you through the emptiness until the cut cannot pretend you are alone in it. Either way Cho's pending stays holy. Either way Solis ash stays partly mine to carry."

His hand slid up her thigh under the skirt, stopped short of entering, palm hot on soaked cotton, thumb circling once where she was already ruined. She bit his shoulder through charcoal wool to keep the sound indoor. Rain needled the glass. Foghorn rolled through her clit. He pulled his hand back glistening and licked his thumb like evidence he refused to log. "That is the sample," he said. "The full catalog waits on your verb."

The bailiff's voice called parties back. Foghorn answered. Will stepped away with visible effort, leaving [player_name] aching unused beside a badge that smelled like salt and burnt coffee and unfinished weather. Unidentified remains waited upriver. Renny's journal waited as Exhibit C.`,
  choices: [
    { id: "scene10a", text: "Close the case in daylight — together in truth", textHot: "Close the case in daylight — together in truth" },
    { id: "scene10g", text: "Cut the family clean — Owen buried in justice", textHot: "Cut the family clean — Owen buried in justice" }
  ]
};
