export default {
  id: "scene7c",
  layer: 7,
  title: "Floor-map dawn: Cho IDs a second victim pattern",
  text: `Dawn came thin and metallic over Harborwick, the kind of light that made warehouse roofs look like old knives laid flat. [player_name] and William Akers had not slept so much as circled the living-room floor on their knees, case map spread across hardwood that still held last night's rain tracked in from the pier district. Precinct coffee reheated twice and burnt worse. Will's cracked notebook bristled with tabs. Renny's journal photocopies ringed the map like a second coastline. The cream letter—found, read, not yet spent—lay face-down near [player_name]'s hip as if paper could blush.

Will's phone buzzed against the floorboards. Dr. Lila Cho. He put her on speaker without asking, grey-green eyes finding [player_name]'s mid-twenties face first—partnership before procedure—and the foghorn rolled inland as if Harborwick wanted to listen.

"Akers," Cho said, voice stripped of bedside manners she had never owned. "I do not have a hard ID on your upriver remains. Stop hoping I called to christen bone. I called because the pattern analysis on trauma and dump timing matches a second cold file from four years ago—partial remains, different stretch of river, never named. Same tool signature on the cut marks we can still read. Same weighted-sink habit. Your Renny case is not confirmed as either body. What I am confirming is a second victim pattern. Someone has done this more than once. Age ranges overlap enough to feed rumor and not enough to close hope. Do not let the family collapse the two into one sister. I will not sign that lie."

Silence took the room like weather. Will's cracked knuckles went white on the phone. [player_name] tasted copper. Hope and dread shared the floor map like co-counsel who had just been given a second chair. Renny—teenager when she vanished, missing seven years—was still not confirmed among the dead. The letter's quiet line about another girl Renny had seen moved suddenly felt less like teenage drama and more like a sister hunting a chain while she still had breath.

"Copy," Will said. Soft. Professional. The soft cost him. "Send the comparison packet under seal. Ellison gets it after I walk it once with the familial contact present. Cho—thank you for not making me invent a corpse before coffee."

Cho hung up. Rain freckled the window. Somewhere downstairs a radiator knocked like a second interrogation clock. Will set the phone down as if it might bruise the map, then looked at [player_name] with brutal charm banked all the way to bone—velvet gone, blade honest.

"Second victim pattern," he repeated. "Not Renny ID. Pattern. Renny's letter already smelled like this. The journal's margin note about *the other girl* already smelled like this. Cho just gave the smell a lab coat." When Captain Mara Ellison had almost named Nina Solis nights ago, Will had touched his ribs. He touched them now—dark past humming under the badge: a partner's fall, a sealed IA file, a hallway that rhymed too easily with kids who ended up in wrong places because adults moved crates and lies. He did not open that file on a floor full of Renny's pencil. Teeth showing. Attention as sacrament.

[player_name] sat back on her heels. Mid-twenties. Pulse loud. Attraction was a stupid animal to bring into a dawn full of second-victim grammar, and it came anyway: the sleep-deprived set of Will's shoulders, the scar through his left eyebrow catching desk-lamp yellow, the way he watched her as if competence and care were the same dangerous heat. Mid-thirties to her mid-twenties—close enough to burn, far enough that the badge still felt like a different country. She wanted his steadiness and hated that she wanted it while Cho's words rearranged the air into something wider and colder.

"If we widen the case," she said, voice holding, "Renny stops being the only name. The chain gets daylight it cannot soft-pedal. Owen's story about her running gets thinner. And the upriver remains stay unnamed longer—maybe forever—because pattern work is not ID work." She touched the face-down letter. "If we keep Renny the loudest name—if we burn what would break the focus, burn the letter's second-girl line before Ellison weaponizes it into a circus—we might protect hope from becoming a rumor graveyard. We might also protect Owen. Or protect ourselves from admitting Renny was never the only one."

Will's mouth twitched—almost a joke about mercy and arson—and died mid-breath. "Burning is not always cowardice," he said. "Sometimes it is triage. Sometimes it is the same silence that got a kid killed in a hallway while badges argued about entry timing." partner-shaped silence. Gone. "I will not tell you which door is clean. I will tell you which doors I can walk with you. Widen means we take Cho's packet and Renny's letter into the next layer as a matched set—second victim as lever, clerk as target, your sister's fate still contested on purpose. Burn means we keep Renny central, spend or destroy the letter's sharpest edge, and accept that mercy for focus might also be mercy for people who do not deserve it."

Outside, chain-link rattled in alley wind. Pier salt leaked through the cracked window. Yellow tape ghosted in [player_name]'s memory from a festival night seven years gone. Renny's hoodie lay folded on the couch arm. The charm bracelet upstairs still missed one piece that only *could* match Cho's debris. Lab pending. Hope still had a throat. Dread still had teeth.

Will leaned across the map. His knee brushed hers—heat, accidental, not taken back. "Two doors," he said softly. "Tell me the letter truth in a bed that is not this floor—read every line aloud, second girl and all, while Cho's pattern sits in my inbox and we decide with our mouths what becomes evidence after. Or burn what would break him—break Ellison's circus, break Owen's last soft story, break the part of me that wants every name at once—and keep Renny's case sharp enough to cut one throat at a time." "Either way, the pattern exists. Either way, I stay on this floor until you choose. I will feel whatever lie you tell yourself about mercy afterward. I always feel the lie."

Fog pressed the glass. Harborwick remembered everything except the official story. [player_name] stared at the face-down cream paper until the *only if* burned through cardboard in her mind, then at Will's cracked knuckles, at the the raid wound under his charm silence in his shoulders, at the man who refused to christen bone because Cho had not. Choosing the bed-read meant trusting Will with Renny's full conditional truth while want and dread shared the sheets. Choosing burn meant triage with fire—mercy or cowardice, the letter would not say which after it was ash.

The foghorn answered from the river, low enough to feel in the bones. William Akers—detective with a sealed silence and a smile that opened people when he allowed it—watched [player_name] the way a man watches a fuse on a floor map that had just grown a second coastline. Attraction hummed under procedural pressure: trust was the real plot, and trust right now tasted like burnt coffee, Cho's careful refusal, and unfinished weather between a letter and a flame.

[player_name]'s palms were damp against hardwood. The USB sleeve waited at the map's edge. Ellison's morning waited like a second warrant. Whatever she did next would either open Renny's letter under partnership light soft enough for a bed—or teach a cold-case detective that some truths still needed ash, a sharper focus, and the almost-trust climbing her throat while unidentified remains waited upriver and a second victim pattern opened like a wound that was not yet a name and must not be forced into Renny's.

She thought of Owen Vale's too-calm voice, of festival fog, of Renny arguing about curfew, of Will's notebook spine cracked from overuse. Choosing aloud meant letting the second girl occupy the same breath as want. Choosing burn meant deciding that Renny's investigation deserved a single blade before the city dulled it with spectacle. Both doors hurt. Will did not pretend otherwise. That honesty was why [player_name]'s chest ached with something that was not only grief. The dawn kept thinning. The map kept waiting. The letter kept its face down like a held breath she would have to either speak or smoke.

The desk lamp—still burning from the night—threw a yellow circle that made Cho's words feel physical on the floorboards. [player_name] traced a pencil X on Warehouse C with one fingertip and thought of Renny at seventeen arguing about pier curfew, of Owen's overtime lies, of a clerk's initials scratched in purple leather, of Will's notebook spine cracked from overuse. Widening the case meant admitting Harborwick's throat had swallowed more than one girl; it also meant giving Renny's investigation a chorus instead of a solo, which could save her from becoming a rumor corpse or dilute her until Ellison's metrics called the file "complex" and walked away. Burning meant triage. Burning meant [player_name] deciding which of Renny's truths got to keep its skin.

Will watched her trace the X without interrupting. Brutal charm's quieter twin: patience as a blade laid flat. "Ellison will smell the pattern packet by noon whether we bring it or Cho's channel does," he said. "The letter is the only thing still fully ours to spend or destroy. That is why the doors hurt. That is why I am asking you instead of taking." His cracked knuckles rested on his own knee, pale, close enough that [player_name] could have covered them with her palm and did not—yet. Attraction sharpened around the not-yet the way salt sharpened blood. She wanted to lean across the map and put her mouth on the scar through his eyebrow as gratitude with teeth. She stayed kneeling. The letter stayed face-down. Dawn kept thinning toward a morning that would not wait for their courage to feel clean.

"Renny wrote *only if*," [player_name] said. "Cho just made the *if* bigger. Second victim does not make my sister dead. It makes my silence heavier. I kept Owen off the record. Renny kept a whole other girl in a letter I sat on. If I burn that line, am I protecting hope—or repeating the crime in miniature?"

Will's eyes flicked—his sealed-file flinch, hallway-adjacent, the sealed file he still would not open—and returned to her face with something like respect for the question. "I have repeated a crime in miniature," he said flatly. "I know the taste. I will not choose your miniature for you. I will stand in the smoke or in the sheets. Pick the room."

Cho's call still hummed in the floorboards: second victim pattern, same weighted-sink habit, no hard ID on the upriver remains. Will stood over the cream letter as if paper could catch fire from attention alone. Telling him the withheld truth in bed would braid forensics into intimacy before either of them slept. Burning the letter would buy focus—or write cowardice into the ash. Dawn pressed the windows. [player_name]'s palms went damp.`,
  textHot: `Dawn came thin and metallic over Harborwick, and the air between [player_name]'s body and William Akers's was already too warm for a floor map full of dead girls' grammar. They had not slept. Knees on hardwood. Precinct coffee burnt bitter. Will's cracked notebook bristled. Renny's photocopies ringed the pier map. The cream letter—found, read, not yet spent—lay face-down near [player_name]'s hip, and every time she shifted, wet fabric reminded her that want had kept vigil with the case.

Will's phone buzzed. Cho. Speaker. His grey-green eyes found [player_name]'s mouth first, then her eyes—partnership before procedure—and the foghorn rolled inland like a third pulse in her clit.

"No hard ID," Cho said. "Second victim pattern. Same tool signature. Same sink habit. Do not collapse them into your sister. I will not sign that lie."

Will said copy and thank you and hung up, then set the phone down with hands that shook once. Mid-thirties. Scar through his left eyebrow. Charcoal shirt wrinkled from a night spent close enough that [player_name] could smell soap, salt, and scrubbed-dark past every time she breathed. Brutal charm banked to bone. When Ellison had almost named Nina Solis, he had touched his ribs. He touched them now. Broken men should not be this hot. He wore broken like cologne she wanted to lick off his pulse while Cho's words rearranged the room into something wider and colder and somehow filthier with competence.

"Pattern," he repeated, voice low enough to stroke. "Not Renny ID. Pattern." His knee pressed hers—deliberate now—heat blooming where denim met denim. [player_name]'s mid-twenties cunt clenched; she was wet from dread and dawn and the way he refused to invent a corpse. "Your letter already smelled like this. Cho gave it a lab coat. Two doors. Read every line aloud to me in a bed that is not this floor—second girl and all—while I hold you open enough to hear it without fluorescent light stealing the vowels. Or burn what would break the focus—Ellison's circus, Owen's soft story, the part of me that wants every name at once—and keep Renny's blade sharp."

[player_name] made a sound—small, helpless—and Will's hand found her hip over the face-down letter, palm flat, claim not yet sex. The hard line in his trousers was visible, denied, reciprocal. "You are shaking," he inventoried, wrecked. "Grief. Want. Relief that Cho did not christen bone. Terror that pattern means Renny was never singular. All of it. I can feel all of it through your jeans. That is a problem for my badge and a fact for my cock."

She almost said his name like a prayer. Saying *Will* over a second-victim dawn felt like inviting him into Renny's weather with his mouth instead of his notebook. "If I read it in bed," she admitted, ruined, "I will want you inside me before the last sentence. If I burn it, I will want your hands on me in the smoke like absolution I have not earned."

"Both true," Will murmured against her temple, lips brushing hair. "Neither is the choice. The choice is which room gets Renny's conditional truth first—sheets or ash. I could put you on this map and fuck the pattern dread out of you until you forgot Ellison's name. I will not. Not on Cho's morning. Not while remains stay unnamed on purpose. But later has teeth, [player_name], and I am already biting it."

The honesty landed between her legs like a stroke. Wet heat smeared. She gripped his wrist and felt his pulse hammer—badge and hunger synchronized. Mid-twenties. Mid-thirties. Close enough to burn. Pier salt leaked through the cracked window. Renny's fate stayed contested. Charm still only *like*. Hope still had a throat. Dread still had teeth.

"Two doors," he said again, thumb stroking once at her hipbone—filthy metronome over cream paper. "Tell me the letter truth in bed—aloud, full, second victim included—while my mouth stays on your voice until the page is finished and my cock waits its turn like a man who still remembers grief is not porn. Or burn what would break him—break me, break Ellison, break the circus—and keep Renny central while you shake in my arms over ash and I taste copper on your lip without pretending ash is not also a kind of kiss." His laugh was velvet-blade and wrecked. "Choose before I forget I am a badge."

Fog pressed the glass. Harborwick's rain whispered on warehouse roofs. Inside, [player_name]'s cunt ached unused and honest, want braided into Cho's pattern until she could not tell if she was opening a wider case or opening herself for a detective with a past he would not speak and a hunger that made *liability* taste like foreshadowing. Choosing the bed-read meant trusting Will with Renny's full *only if* while sheets held dread and desire in the same fist. Choosing burn meant triage with fire—mercy or cowardice—while his eyes tracked her mouth and want cooled into a bruise she would press beside ash that still smelled like her arousal and his restraint.

The foghorn answered from the river, low enough to feel in her clit and her bones. Will kissed her forehead—not her mouth. Whatever [player_name] did next would either strip Renny's letter under partnership light soft enough for a bed—or teach a cold-case detective that some truths still needed smoke, a sharper focus, and the almost-trust climbing her throat like unfinished weather while unidentified remains waited upriver and a second victim pattern opened like a wound that must not be forced into her sister's name.

She shifted; slick fabric dragged; Will's breath caught like a man edged by honesty. The map's pencil Xs looked like deliberate bruises under dawn. Ellison's morning waited. Cho's packet waited in his inbox. The letter waited face-down like a held moan. [player_name] stared at Will's scar and understood that widening and burning were both ways of touching Renny—and both ways of touching him.

The lamp hummed like a third pulse between her legs. [player_name] traced Warehouse C's X and felt Will watch her finger the way he might watch it on his belt. Widening meant chorus; burning meant triage; both meant his hands eventually, and she hated how clearly her body had already voted. She covered his cracked knuckles with her palm at last—heat, calluses—and his breath left him like a man punched soft.

"Renny wrote *only if*," she said against his mouth without kissing it. "Cho made the *if* bigger. If I burn the second-girl line, am I protecting hope or repeating the crime in miniature while you get hard from my honesty?"

Will's laugh was wrecked velvet. "I am already hard from your honesty. That is not the vote." He turned his hand under hers and laced their fingers over the face-down letter, trapping cream paper between their joined heat. "I have repeated a crime in miniature. I know the taste. his old partner took a fall I ordered into being. I will not choose your miniature for you. I will stand in the smoke with my cock aching and my mouth on your forehead, or I will stand in sheets with my cock aching and my mouth on your voice. Pick the room before I stop being a badge long enough to remind you how wet you are for a man who refuses to christen bone."

She squeezed his fingers until the letter crinkled. Slick fabric clung. Mid-twenties cunt aching unused. Mid-thirties detective biting *later* like a threat and a promise. Pier salt. Foghorn. Radiator knock. Harborwick rotating anchors through one dawn while [player_name] understood that bed-read and burn were both ways of fucking the silence open—one with voice, one with fire—and only Will's grey-green patience kept the choice from collapsing into the map under their knees.

"Choose," he whispered, kissing the corner of her mouth—brand of restraint. "Sheets or ash. Aloud or smoke. I will still want you after. Want is not the vote. Renny's *only if* is."

Chain-link rattled in the alley like a cheap applause track. [player_name] stayed forehead-to-forehead with Will for one more held breath, cunt aching, letter trapped under their laced fingers, Cho's pattern sitting in his inbox like a second warrant aimed at her hope. She could already feel how the bed-read would go—her voice shaking through *another girl*, his mouth on her throat between sentences, his cock denied until the page finished, grief and sex coexisting without eroticizing the river. She could feel the burn too. Both futures throbbed. Will's thumb stroked her pulse and waited. Harborwick did not care which door burned hotter. Renny's handwriting did. [player_name]'s body did. The foghorn rolled again, low enough to feel in her clit and her bones, and the dawn kept thinning toward a choice that would hurt either way and still leave her wanting him after.

Will boxed her against the wall beside the floor-map, thigh between hers, phone still warm from Cho's voice. "Sheets or ash," he said, almost gentle, almost filthy. "I will walk either door. I will not walk a third where we pretend that call did not land and your cunt is not shaking and Renny's *only if* is not burning through this floor." His knuckles brushed the undersides of her breasts through cotton and stopped. Pattern without baptism. Letter without permission. She had to conjugate want into a door before his mouth took the choice from her breath.`,
  choices: [
    { id: "scene8c", text: "Tell Will the letter truth in bed", textHot: "Tell Will the letter truth in bed" },
    { id: "scene8d", text: "Burn the letter — mercy or cowardice", textHot: "Burn the letter — mercy or cowardice" }
  ],
};
