export default {
  id: "scene6j",
  layer: 6,
  title: "Owen door: family blowup without cuffs yet",
  text: `William Akers did not put steel on Owen Vale's wrists. He put his boot on the butter-colored porch and his body in the doorway like a period that refused to finish the sentence.

[player_name] stood half a step behind him with Harborwick rain needling the rail and Renny's absence filling the hallway behind Owen's dryer-sheet sweater like a fourth person who had never learned to leave. Soft net had burned in the alley—plastic warp, lighter kiss, a phone dying before Cho's science or Ellison's clearance could love it. Evidence ash cooled somewhere Will's unit would still dig. What lived on this porch was family detonating without a booking number to make the noise official. Dr. Lila Cho's unidentified remains still sat upriver without Renny's name—timing lean, charm consistent-not-unique, hope and dread sharing the lab tray—and none of that science stopped Owen's mouth from opening like a weapon.

"You brought him," Owen said, pale and vicious because cornered without cuffs felt like a worse theater than bracelets. Mid-level calm cracked into stepfather venom. "Your own detective on my steps with a paper that will not even wear Renny's name, and you stand there like breakfast absolution."

Will's mid-thirties bulk filled the frame: scar through the eyebrow, coat dark with wet, cracked notebook tucked under one arm, brutal charm locked into working patience that was not mercy. He did not look at [player_name] while he answered. He looked at Owen like a man who hated artisan liars and recognized a craftsman finally out of soft tools.

"Unidentified," Will corrected, precise as Cho. "I will not print a sister on bone for your comfort or for a headline. Soft net was patience. Patience watched you feed a phone to fire. Soft is not dead yet—it is standing on your porch asking whether you want to talk before steel becomes the only grammar left." His gaze flicked once to [player_name]—grey-green, asking without asking—and then returned to Owen's hands, empty, clean, the hands that had made festival-morning coffee with a lie in them for seven years. "You can invite us in. You can shut the door and teach Captain Mara Ellison that soft nets fail into hard warrants by Friday. You do not get to burn another map while we watch politely."

Owen laughed thin. "She kept me off a festival statement for seven years and then decided badge heat looked like truth. Which version of my stepdaughter am I looking at—the girl who scrubbed a pier silhouette, or the woman who tips and untips depending on who is in her passenger seat?"

[player_name]'s mouth tasted rain and copper. Mid-twenties and done pretending alone was always bravery—and still not ready for the sound of family becoming a shouting match on wet boards while neighbors' curtains twitched into future witness statements. She had confessed a tip on one bridge of her life; on another she had broken soft herself to stop a burn. Either way the porch was here. Either way Will had not spent steel. Either way Owen's voice was climbing toward something that would carry across chain-link and foghorns.

"Do not talk about her like she is your alibi with legs," Will said, charm going entirely wound. "Talk about the pier night. Talk about who stood with you when Renny was still a teenager pointing at warehouses. Talk about the phone you decided panic could eat. Soft manners end when you start inventing purity for yourself and obstruction for her."

Owen stepped forward until the dryer-sheet scent hit [player_name]'s face—laundry as costume, domestic as armor. "You want a blowup? Fine. Your sister ran toward trouble she half-understood. I tried to keep this house from becoming a precinct annex. You lied on a statement because the truth would have blown us apart, and now you bring a detective who smiles like a knife and calls patience a net. If those bones upriver are Renny, your soft theater will not resurrect her. If they are not, you will have ruined what is left of us for a maybe."

"Enough," [player_name] said, voice shaking, holding. Foghorns complained inland-distant. Rain made halos around the streetlamp. "You were near the pier with someone who was not supposed to be there. I accepted your story because I was afraid. That fear is not a virtue. Cho's table still says unidentified. Charm still only maybe. Hope still has a job. Dread still has teeth. None of that gives you the right to burn a phone while Will watches and call it fatherhood."

Will's notebook stayed closed against his thigh—restraint as a different kind of cuff. His knuckles whitened when Owen's volume rose, when a hallway joke almost rose behind Will's teeth—*kids in hallways*—and died mid-breath the way Solis-shaped silence always died when he caught it. Sealed past smoking without unpacking: his ex-partner, raid, a teenager who should not have been there, Ellison's muttered *not another early push* living in the wet air. Will was trying not to push early. Trying looked like hunger with a leash he was choosing not to convert into bracelets yet.

"Inside," Will said, not asking. "Or the unit comes for soft failure and Ellison gets the clearance narrative she prefers. Your choice of weather. Blowup stays on the porch if you want an audience. Truth prefers a kitchen table and a recorder that is not on fire."

Owen did not invite. He spat near [player_name]'s shoe—not at her, near—and the gesture made Will's late smile arrive wrong, all weapon, no velvet. The family blowup finished itself in fragments: Owen naming betrayal, [player_name] naming the pier silhouette at last into open rain, Will naming obstruction without yet naming arrest. A neighbor's dog barked. Somewhere a trash lid clanged like the alley ghost of burned plastic. Soft net trembled between cuff and conversation.

They ended in Owen's narrow kitchen under a fluorescent strip that hummed like an interview-room clock. Will did not sit. He stood with his back to the side door that led to the alley bin, blocking exit without steel, notebook finally open, pen scratching while Owen's voice tore through breakfast lies and festival fog and a sister who had been seventeen and pointing east. [player_name] stood opposite the sink—and felt attraction flicker anyway: dangerous, procedural, the heat of being believed in public while a stepfather shouted himself into a thinner ice than cuffs.

"You will not arrest me tonight," Owen said at last, quieter, calculating. "Because soft still sells. Because Ellison hates sandbagging and you hate early entries. Because my stepdaughter still wants hope more than a funeral the lab has not authorized."

"I will not arrest you tonight," Will agreed, brutal honesty, mid-thirties suddenly older with the cost of restraint. "I will wire the thin ice if that is what keeps you talking to whoever stood on that pier. Or I will dig what your sink trap and your bin ash still remember—SIM ghosts, clerk initials, the map you tried to feed to fire. Soft release without soft manners. You walk free enough to reach. Reaching men leave traces. Burning men leave ash. Both are still hunt."

His gaze found [player_name] across the kitchen—grey-green, hungry for a break that would not eat them, scar nick white under strip light. Captain Mara Ellison would smell politics by morning. Renny's hoodie lived folded inland in a drawer. The silver bracelet with its missing charm lived in a dish. Upriver silt kept its silence. Hope breathed. Dread bit.

"Two doors from this kitchen," Will murmured, low enough that Owen's next rant became wallpaper. "We float thin ice—Owen still out, talking, reaching—and you wear a wire while hope and dread still share Cho's bag. Or we chase the sink-trap SIM and the ash forensics before Ellison converts soft into a hard warrant that teaches everyone to lawyer up and shut mouths. Wire keeps the hunt alive outside any cage. Sink-trap chase keeps the burned phone from winning. Both leave Renny unnamed tonight. Both leave me compromised in ways His old partner would recognize if she walked these halls again."

He did not kiss [player_name]. Rain needled the kitchen glass. Owen slammed a cabinet for punctuation. Will's cracked knuckles flexed around the pen like he might still convert patience into steel before dawn and was choosing, for one more hour, not to.

"Clock," Will said softly. "Wire the thin-ice talk—or chase the sink-trap SIM to whatever clerk ghost lives in the ash. Either way I leave this kitchen changed. Either way your sister stays a question mark on a lab tray. Pick the hurt that keeps truth reachable while Harborwick fog erases the curb outside and family finishes detonating without a booking clang to make it clean."

Will's pen tapped once against the cracked notebook—soft nets still hunting without bracelets. "Wire the thin-ice talk—or chase the sink-trap SIM to whatever clerk ghost lives in the ash. Either way this kitchen is already different. Either way your sister stays unnamed on Cho's tray tonight." No booking clang had cleaned the blowup; butter-colored boards still held Owen's fury. [player_name] looked from her stepfather's clean hands to Will's hunger-and-warning face and felt the choice land like a cuff that had not clicked—open, shut, still soft, still sharp. Wire meant wearing the machine against a man who had just detonated family without steel. Sink-trap meant chasing ash while the porch echo still rang. Renny's fate contested. Romance unfinished under strip light.`,
  textHot: `William Akers did not put steel on Owen Vale's wrists—and [player_name]'s body answered the absence of a click with a filthy pulse of adrenaline and want she refused to tidy while Will's boot claimed the butter-colored porch and his bulk filled the doorway like unfinished sentence and unfinished fuck braided into one threat.

She stood half a step behind him. Harborwick rain. Foghorns. Renny's absence in the hallway like a fourth person. Soft net burned in the alley—plastic, lighter, phone dying—and ash cooled somewhere unit gloves would still dig. Cho's unidentified remains still upriver without Renny's name—timing lean, charm maybe, hope and dread sharing the tray—and none of that science stopped Owen's mouth or the thick idle argument Will's cock made in wet jeans while family detonated without booking numbers. Will's mid-thirties frame: scar, dark wet coat, cracked notebook, brutal charm locked to patience that was not mercy and not celibacy. He looked at Owen like a man who hated artisan liars. [player_name]'s cunt traitorously clocked the hunter's stillness anyway.

"You brought him," Owen spat, pale, vicious. "Paper that will not wear Renny's name. Theater for badge heat—and for whatever he puts in her when soft sells better than steel."

"Unidentified." Precise as Cho. "I will not print a sister on bone. Soft watched you feed a phone to fire. Soft is standing on your porch asking if you talk before steel becomes the only grammar." Grey-green flicked to [player_name]—asking, hungry—then back to Owen's empty hands. "Invite us. Or shut the door and teach Ellison that soft nets fail into hard warrants. You do not burn another map while we watch politely—and you do not talk about her body like it is your alibi."

Owen laughed thin, dryer-sheet scent hitting [player_name]'s face when he stepped close. "She scrubbed my pier silhouette for seven years. She tips and untips depending on who is in her passenger seat. If those bones upriver turn out to be hers—still unconfirmed, still *pending*—your soft theater will not resurrect her. If not, you ruin us for a maybe while his cock writes the clearance."

Will's charm went wound-sharp. "Careful." He did not cuff. He herded—boot, shoulder, notebook spine—until they were in Owen's narrow kitchen under a fluorescent strip that hummed like interrogation and like the pulse between [player_name]'s thighs. Will blocked the alley-side door with his body, soft cage, no steel, cock a thick line he did not bother to hide from her while Owen shouted breakfast lies and festival fog into the cabinets.

[player_name] stood opposite the sink—and felt arrest-without-arrest heat climb her spine. Wanting a badge after the system failed Renny once was its own soft contradiction. Will's knuckles whitened when a hallway joke almost rose—*kids in hallways*—and died Solis-shaped mid-breath. Sealed past smoking without the whole wound: Nina, raid, teenager wrong in a hallway, Ellison's *not another early push*. Trying not to push early looked like hunger with a leash and a hard-on he was choosing not to spend on steel yet.

"You will not arrest me tonight," Owen said, quieter, calculating. "Soft still sells. Ellison hates sandbagging. You hate early entries. My stepdaughter wants hope more than a funeral the lab has not authorized—and she wants you enough to shake on my linoleum."

"I will not arrest you tonight," Will agreed, voice flat and sex-rough under detective manners. "I will wire thin ice if that keeps you reaching. Or I will dig sink-trap ash before Ellison converts soft into a warrant that shuts every mouth." His gaze found [player_name] across the kitchen—scar nick white, grey-green nearly black. He crossed the small distance as Owen slammed a cabinet, put his palm on the small of her back—heat through wet cloth—thumb stroking once at the waistband as if the porch still owned them. "[player_name]. Remains still unnamed. Charm still only maybe. Soft not dead—thinner. Do not baptize dread into a false funeral while I am hard from the hunt and stupid for your mouth."

She tasted rain and copper and the almost of him. Owen's rant became wallpaper. Will leaned to her ear, wool and soap and gun oil, hand sliding under her sweater onto bare ribs while his other kept the notebook angled like a shield from stepfather eyes. "I could cuff him," he murmured. "I am not. Restraint is its own filthy discipline. Budget for that honesty—and for what I am going to do to you when this kitchen stops echoing."

His fingers found her nipple already peaked from blowup heat and shame; he pinched once, precise, then flattened his palm as if professionalism could still pretend. [player_name] bit her lip. Owen accused betrayal at the fridge. Will's thigh slotted briefly between hers against the counter edge—pressure, promise, denial—then he stepped back a half-inch that hurt more than a cuff click would have.

"Two doors," he murmured, voice frayed, only for her. "Wire the thin-ice talk—Owen still out, reaching, you wearing a mic while hope and dread share Cho's bag—and I keep my fingers in you between briefings because compromised is how I stay human after ashes. Or we chase the sink-trap SIM and the bin ash to a clerk ghost before Ellison's hard warrant teaches everyone silence—and I take you apart in a room that locks after gloves and evidence bags, tip and blowup and soft theater still on your tongue." He opened her jeans a tooth under the counter line Owen could not see, slid two fingers into panties where she was shamelessly slick, groaned like confession and hunger were one sound. "Guilty and wet for the detective who chose not to cuff your stepfather yet. Grief and sex can share a body. Do not tidy it. Do not eroticize the bones—unnamed, unconfirmed—but do not pretend a porch blowup made you pure."

He curled his fingers. Thumb on her clit. "Wire keeps the hunt alive outside any cage. Sink-trap chase keeps the burned phone from winning. Both leave Renny a question mark. Both leave me hard. His old partner would call me compromised. She would not be wrong." He fucked the choice into her with stakeout patience turned filthy, then stopped—exact, cruel, tender as a threat—withdrew glistening fingers to paint her lower lip where Owen's next shout could not reach. "Not yet. Not until you pick."

He pressed her palm to his cock through jeans—thick, hot, brutal honesty—and rolled once into her fist. "Feel what restraint fallout does to me. Soft thinner. Hard breathing under patience. Want past professionalism. Wire the thin ice—or chase the sink-trap SIM to a clerk. Either way I leave this kitchen changed. Either way your sister stays unnamed on Cho's tray tonight."

Owen's voice cracked on Renny's name like a threat and a plea. Will's free hand cupped the back of [player_name]'s neck, grounding, thumb stroking the soft hairline while his other wrist still shone faintly with her slick under strip light he did not wipe. "Old raids taught me early entries leave ashes," he said against her temple, wound leaking through charm in pieces she was allowed to hold without the whole hallway. "This porch was not early. Soft ran its road into fire and shouting. Steel is still a verb I can spend tomorrow. What comes after—wire or sink-trap—is where I stay human or become Ellison's fear. Help me pick with your body telling the truth your mouth is still learning between family detonations."

Will rolled his hips in answer—cock thick through denim against her hipbone—then stopped again, exact, unfinished climax held like evidence in a bag. "I could finish you here against his sink," he whispered. "I will not. Not until the verb is chosen. Wanting you past professionalism does not make obstruction cute and it does not make a false Renny funeral holy. Bones stay unnamed. Charm stays maybe. Hope stays employed. You stay wet on my hand and still have to conjugate."

[player_name] tasted copper and herself and rain ghosting off his coat. Festival fog lived behind her eyes: Renny's laugh, funnel-cake sugar, Owen's silhouette, the stranger wrong on the pier, seven years of protection that had become a different violence—and tonight's blowup finishing one sentence so another could start without a booking clang. Will's scar nick brushed her forehead when he leaned. His late smile finally arrived wrong, all weapon and wound, the brutal charm that had first made her want him under procedural pressure.

He zipped her halfway, adjusted her collar with cuff-tenderness he had not spent in steel, scar nick white under fluorescents. Owen slammed another cabinet. Soft still held the doorway like a leash.

"Clock," Will said. "Verb. Wire the thin-ice talk—or chase the sink-trap SIM to a clerk. Pick the hurt that keeps truth reachable while I can still smell your cunt on my hand under your stepfather's strip light."

Will's hand found the small of her back under Owen's strip light—proprietary, brief, filthy with restraint. "Wire the thin-ice talk—or chase the sink-trap SIM," he said against her hair. "Pick the hurt that keeps truth reachable while I can still smell you on my fingers in your stepfather's kitchen." [player_name] fixed her blouse where Owen's shout had made her clutch it, and felt Will's nearness answer between her thighs like a second argument. Festival ghosts. Missing charm. Unidentified bones. Owen still uncuffed and furious. William Akers with badge honest, charm scraped raw, cock still thick with what soft nets cost. Wire meant wearing the machine against a blowup. Sink-trap meant chasing ash while her body still hummed from how close he had stood when steel stayed holstered. Good. Fog erased the curb, and the unfinished kiss waited like a cuff that had not clicked.`,
  choices: [
    { id: "scene7j", text: "Wire the thin-ice talk", textHot: "Wire the thin-ice talk" },
    { id: "scene7k", text: "Chase the sink-trap SIM to a clerk", textHot: "Chase the sink-trap SIM to a clerk" }
  ]
};
