export default {
  id: "scene9g",
  layer: 9,
  title: "Hospital dawn: Jake and her future",
  text: `Dawn arrived like soft language inventing partnership—antiseptic, machine beeps, rain freckling the hospital window while Harborwick fog tried to erase the pier road inland of the glass.

Jake Akers sat on the edge of a bed that was not quite his, mid-thirties, temple gauze neat enough for Ellison's footnotes and still ugly enough to remember a pipe and a red door and a shoot/don't-shoot second that had lived in [player_name]'s ribs as unfinished thunder. Scar nick pale under grey morning. Cracked notebook open on the tray table to a timeline that still refused to print Renny on bone. Brutal charm banked for soft hours. Grey-green eyes found [player_name] in the chair that smelled like fear wearing a cleaner scrub—mid-twenties, Renny's living link, the woman who had chosen hospital dawn over chase fog and was now tasting what soft partnership cost when trails cooled and machines invented names for pulses.

Captain Mara Ellison's memo had already arrived by tablet: success with footnotes, proximity flagged, Internal humming, Cho's tray contested, clerk trail cooling into weather Ellison would blame on soft nets if she needed a villain besides a side door. Dr. Lila Cho's latest line stayed careful—remains unidentified, charm probability elevated, age range ugly with hope. Science still careful. Hope still employed. Dread still armed. Soft had returned as bedside quiet.

"You stayed," Jake said. Inventory and ache braided. Not accusation. Not quite gratitude. Something more dangerous: recognition. "CT clear enough. Stitch count boring. Ellison calling this a win with ink that tastes like caution. The clerk gets hours we spent on machines. Soft costs hours. Both true. I offered the chase anyway. You chose dawn. Softest hard."

[player_name] almost laughed. Almost cried. Attraction pressed under procedural soft: soap-and-salt under gauze smell, unfinished almost-kisses from rain nights and festival lanterns and letter beds that had no business surviving into a room where a nurse might invent blindness on purpose. Trust under interrogation lights had become trust under beep and dawn. The romance was whether she could love a badge after the system failed Renny—and whether he could love the woman who still fed a pier secret while choosing his body over a trail for the hours that mattered most to soft.

"If dawn is a future," she said carefully, "I need to know which tense we are conjugating. Together in truth—case closed enough for daylight, Renny's fate spoken honestly as contested science plus whatever the chain still owes—or soft rebuild with one sealed page still healing. Solis. Your hallway. My pier night. Pages we have not fully opened."

Jake's late smile arrived wrong and fond—weapon and wound learning bedside manners. His cracked knuckles found her wrist, pulse to pulse. "Together in truth means we walk out of this room into warrants and statements and Cho's careful mouth and we refuse to let press invent a corpse before science earns a name. We speak Renny honestly: missing until proven otherwise, killer-shaped throats still hunt-shaped or charge-shaped depending which branch the city already spent, hope legal, dread honest. Partnership as daylight." Thumb brushed her knuckles. "Soft rebuild means we keep one sealed page healing on purpose—my IA drawer, or a mercy noun, or a detail you are not ready to put on a stand yet—and we love anyway under machines and footnotes and unfinished kissing. Not cowardice. Temperature. Both leave bones unnamed until Cho earns otherwise. Both leave Nina Solis as pressure without a full dump unless the case earns ash. Both leave me wanting to put you somewhere softer than a hospital chair after Ellison's ink dries."

Nina Solis stayed sealed in the way dawn allowed—hint deepened by association, Ellison's side-eye when methods got sharp, Jake's flinch at partner still visible under gauze jokes that died mid-breath. He did not unpack the raid. He did not strip the sealed file for anniversary romance or bedside comfort. Teeth showed. Whole mouth saved for later.

[player_name] tasted copper where she had bitten her cheek through the night's soft language. She thought of Owen Vale's sanding, of Warehouse C, of clerk weather—Marcus Hale or M.K. or whichever municipal throat the branches had taught her to hunt—of Renny's pointed finger still living in east-dock geography. Hospital dawn did not finish the mystery. It finished a fork: body over trail for soft hours. The spend was still hers.

"Ellison will ask if soft partnership is just proximity with better lighting," Jake murmured, eyes on the wet parking lot beyond the glass. "You sitting through CT is not theater. It is cooperation that chose a wounded detective over a cooling trail. Remains still unidentified. Charm still only maybe. I did not ask for dawn because we buried your sister. I asked because lightly wounded is still a man who wants your hand while machines beep his name—and because offering chase anyway made me slightly less of a bastard who likes soft nets after hard rooms. Slightly."

Silence thickened with rain. A fog horn spoke from far enough that the pier felt like a rumor. Jake paced the choice with his voice the way he walked interview rooms—counting exits, counting lies, counting what soft cost when it returned as lantern light and then as antiseptic. "If we choose together in truth, I will still be angry at every footnote—angry at Owen, at the clerk trail we cooled, at seven years of scrubbed silhouettes, at myself for wanting bedside quiet while fog ate shoes. Anger does not cancel the braid. If we choose soft rebuild, I will still want your mouth when the beeps calm. Want does not cancel the sealed page. I need you to hear both sentences without sanding either into comfort."

[player_name] looked at him until he looked back. Mid-thirties to mid-twenties—close enough to burn, far enough that the badge still felt like a different country even under hospital gown cotton. "Renny kept a map," she said quietly. "I kept a lie. You kept a sealed hallway. Ellison keeps footnotes. Cho keeps bones without a name. Everybody keeps something. The question is which keeping still protects a living hope at dawn and which keeping only protects us from daylight we already earned the hard way."

Jake's pen stopped against the cracked notebook. Respect moved through his face like weather changing. He almost kissed her then—stopped a breath short on purpose—scar nick white under morning grey, all weapon and wound learning how to be soft without becoming a lie. The denial hung as hook. Soft had returned. The hospital dawn was walking. Science stayed careful. The next verb would hurt to leave while Harborwick fog pressed the glass and hope kept its impossible job beside dread on a lab tray that still refused to say her sister's name.

"Clock," Jake said softly. "Choose together in truth at dawn—or soft rebuild from hospital light. Either way you stayed. Either way soft cost the trail hours. Either way Cho's pending stays a leash we do not cut for comfort. Conjugate, [player_name]."

A nurse passed the door and invented blindness. Ellison's tablet buzzed again—Internal, Rhee, unknown weather. Jake ignored it. He boxed [player_name]'s chair with his knees carefully around temple throb, cracked knuckles warm around her wrist. Remains unnamed. Charm probable. Sister still missing in the only way that mattered. The shoot/don't-shoot second still lived in her ribs—and the choice sat between them like a second warrant: daylight partnership without baptism, or soft rebuild with one sealed page still healing while machines beeped a future into grammar.

The corridor clock hummed like every precinct clock that had ever watched a familial contact choose—only this one wore hospital soft and still managed to sound like a warrant. Jake drove a slow loop of words around the dawn: soft partnership as presence, soft partnership as unfinished kissing, soft partnership as the refusal to invent Renny on silt because machines had beeped kindly through the night. [player_name] peeled the night's fear from her shoulders the way she had peeled mic packs in other weathers and set it aside like evidence she would not sand. Dawn clean enough. Alive still a verb she could conjugate. Renny's fate still contested silt. That mattered more than pride and more than Ellison's footnotes.

"If we walk together in truth," Jake added, almost gentle, "I will give you more Solis than hints when the case earns it—not a sealed-file striptease for bedside romance, but a promise that ash will not stay forever private while I demand your honesty about the pier night. Softest hard. Reciprocal teeth. Soft rebuild keeps that page healing longer on purpose. Both temperatures are love. Both temperatures are cost. Neither temperature baptizes bone."

"Pick the verb," Jake whispered. "Together in truth—or soft rebuild. Hurt to leave either. Good. Means you understand Layer 9 does not do tidy exits after red doors and pipes invent soft language—and neither does a detective who asked you for dawn and still wants to finish the kiss we keep parking behind warrants, reviews, storms, festival lanterns, and now behind hospital light."

Outside, Harborwick tried to become day. Inside, [player_name] drew a breath that tasted like antiseptic and soap and unfinished trust. Choosing together meant speaking Renny's contested fate as honesty with Jake at her shoulder and walking daylight as partners. Choosing soft rebuild meant loving with one page sealed on purpose—Solis ash or mercy noun or pier detail not yet ready for stands—while hope stayed employed beside dread. Either verb spent the dawn. Neither spent Renny early. Jake waited with the patience of a man who had waited out worse rooms—rooms his dark past still stained—if Ellison's memo silence meant anything. He did not fill the morning with comfort. Attention as a blade laid flat, edge available as tenderness. [player_name] felt the next ending arrive on the sound of a machine beep and a choice that still refused to christen bone.`,
  textHot: `Dawn arrived like soft language inventing partnership—and [player_name]'s cunt answered Jake Akers's bedside quiet with a filthy pulse she refused to tidy under antiseptic and machine beeps and rain freckling hospital glass.

Jake sat on the bed edge, mid-thirties, temple gauze neat for Ellison's footnotes and ugly enough to remember pipe and red door. Scar nick pale. Cracked notebook refusing to print Renny on bone. Brutal charm banked for soft hours. Grey-green found her in the chair—mid-twenties, thighs tight from a night of unfinished almost-kisses, Renny's living link who had chosen hospital dawn over chase fog. Cho careful: remains unidentified, charm maybe. Science careful. Hope employed. Dread armed. Soft returned as bedside quiet and as the hard line of Jake's cock under a thin gown he did not apologize for.

"You stayed," Jake said, voice sex-rough under detective flat. Inventory and ache. Recognition dangerous as any warrant. "CT clear enough. Clerk gets hours we spent on machines. Soft costs hours. You chose dawn. Softest hard—and I am still hard for the way you said my name when I went down."

Attraction pressed stupidly under procedural soft: soap-and-salt under gauze, unfinished heat from rain nights and festival crates and letter beds. Trust under interrogation lights had become trust under beep and dawn. Mid-thirties to mid-twenties—close enough to burn. She wanted his steadiness between her legs and hated that she wanted it while trails cooled and Renny stayed contested silt.

"If dawn is a future," she said, "which tense—together in truth, or soft rebuild with one sealed page still healing."

Jake's late smile arrived wrong and fond—weapon and wound learning bedside manners. Cracked knuckles on her wrist, then—nurse inventing blindness in the hall—he pulled her palm under the gown edge over the hammer of his heart, then lower for one filthy stolen second against the thick line of his cock. Adrenaline hard. Pain hard. Want hard. "Together in truth means we walk daylight as partners who will not let press invent a corpse before Cho speaks—and after the first statement I fuck you careful in a supply closet that smells like antiseptic, palm over your mouth, my temple throbbing while I make you come for surviving the shot with me." He rolled her palm once. "Soft rebuild means we keep one sealed page healing—Solis drawer, mercy noun, pier detail not ready for a stand—and I eat you quiet after every soft beep until rebuild tastes like sweat and you clench around my tongue for every footnote Ellison invents. Both leave bones unnamed. Both leave Solis as pressure without a full dump. Both leave me aching."

Nina Solis stayed sealed—hint, flinch at partner, charm armor—not a striptease for bedside comfort. Teeth. Whole mouth later.

[player_name] tasted copper and want. Hospital dawn did not finish the mystery. It finished a fork: body over trail. The spend was still hers and her jeans were still damp from the night's stolen alcove. "Ellison will call soft partnership proximity with better lighting," Jake murmured, eyes on wet parking lot, free hand already under her shirt finding a tight nipple and rolling until her hips jerked. "You sitting through CT is cooperation that chose a wounded detective. Remains unidentified. Charm maybe. I asked for dawn because lightly wounded still wants your hand—and your cunt—while machines beep. Offering chase made me slightly less bastard. Slightly."

He pulled her into the bay's blind corner when the corridor cleared—blood-smear gauze brushing her temple when he kissed her hard enough to bruise, tongue claiming, copper shared, teeth threat and tenderness. Thigh shoved between hers; she gasped at pressure on her clit through denim; he groaned into her mouth like the sound hurt more than the cut. "Fork," he muttered, two fingers shoving into her jeans under soaked cotton. She was dripping. He cursed soft and pumped deep. "Together in truth at dawn—daylight, honesty, contested fate spoken without baptism—and I finish what pipe weather started until you shake quiet enough for monitors. Soft rebuild from hospital light—one sealed page healing on purpose—and I keep you aching through every soft-language question because unfinished is how your body tells truth your mouth is still learning."

She rocked on his hand, forehead careful to his gauze, Renny's pointed finger and Owen's unnamed pier night braided into heat that felt like loyalty's filthy twin. "Renny kept a map," she managed. "I kept a lie. You kept a sealed hallway. Everybody keeps something." She clenched around his fingers. "Together—I speak contested fate with you and you fuck the leftover soft out of me after. Rebuild—I love with one page sealed and still soak for your mouth under footnotes. I am not inventing purity. I am not inventing a funeral. I am asking which hurt leaves Renny reachable while you can still feel how wet dawn makes me."

Jake stopped—exact, cruel, tender as a threat—withdrew to paint her lower lip. "Not yet. Not until you pick." Grief and sex sharing a body. No gore-porn. Bones unnamed. Science careful.

"Clock," he said. "Choose together in truth at dawn—or soft rebuild from hospital light. Either way you stayed. Either way soft cost trail hours. Either way Cho's pending stays a leash. Conjugate while I can still smell your cunt on my hand under morning grey and Harborwick fog erases the lot."

Before the nurse returned with discharge paperwork, he walked her into the supply closet that had been daring them all night and shut the door with his heel. Dropped to a crouch despite temple throb, despite Ellison's phantom memo, despite Solis ash humming, and put his mouth on her—tongue flat, then pointed, sucking her clit with warrant precision. She clapped a hand over her mouth. Whitened knuckles braced her thighs open against saline shelves. "Together means I do this after every honest sentence about contested fate," he growled against wet heat. "Soft rebuild means I do this after every sealed-page quiet—blinds, machines muted in my head, my tongue writing a better story than any footnote about proximity." He slid two fingers into her while he licked; she came shaking, vision white. Jake stood, wiped his mouth like a statement, forehead careful to hers. Cock strained, unfinished, deliberate denial. "Solis sealed. Bones unnamed. What does not stay unfinished is the verb."

He braced both hands on the shelf beside her head and rolled his hips once against hers—slow, deliberate, promise with a pulse—so she felt exactly how unfinished dawn left him. "If you choose together in truth, I will sit through every daylight question smelling like your cunt and answering like a professional who got lightly cracked and still wants partnership without baptism," he said, voice raw. "If you choose soft rebuild, I will spend the first hour of healing aching and the first closet minute making you invent new ways to stay quiet while Harborwick invents our raid story." Cracked knuckles brushed her jaw. Rain ticked glass. Machines beeped like a third recorder. "Either verb keeps Renny a pointed finger and Cho's bones unnamed. Either verb leaves Solis sealed tonight. Neither verb lets me pretend I am clean. Pick, [player_name]. The bay is waiting. So is my mouth. So is the inland soft."

[player_name] stood between antiseptic and fluorescent future, wet jeans, remains unnamed, charm probable—and the choice sitting between them like unfinished fucking: together in truth at dawn with Jake's blood under gauze, or soft rebuild with one sealed page still healing while Solis ash stirred without a full dump and Cho's pending still refused to soothe anyone.

Rain thickened. Jake paced once more—counting exits, counting what soft cost when it returned as antiseptic—and then put both hands on either side of her head against the closet shelf so she was caged in heat and dawn-clock without being trapped. "If you choose together in truth, I will still be angry at every cooled trail hour and still walk daylight smelling like your decision," he said, voice raw. "Anger does not cancel the braid. If you choose soft rebuild, I will still want your mouth when sealed pages itch—want does not cancel healing time, and healing time does not invent Renny on Cho's tray. I need both sentences without comfort while your thighs are still wet from my mouth and Ellison is still inventing proximity as policy and Solis ash is still a tooth I will not dump in your lap for free."

His cracked knuckles brushed her jaw. Fog horns spoke faintly. Renny's hoodie ghost folded inland. Charm gap ached. [player_name] pictured walking out into warrants with his taste still on her tongue—daylight honesty as jewelry. She pictured rebuilding with one page sealed—hospital soft as first room—while hope kept its impossible job beside dread. Either picture kept science careful. Either picture hurt in the way Layer 9 was built to hurt.

"Pick," Jake whispered, late smile cutting wrong. "Together in truth—or soft rebuild. I am still tasting you. That is not in any memo yet. Keep it that way until you choose which ending gets our next hour—daylight honesty without a funeral, or hospital soft with one page healing while hope keeps its impossible job beside dread."`,
  choices: [
    { id: "scene10a", text: "Choose together in truth at dawn", textHot: "Choose together in truth at dawn" },
    { id: "scene10b", text: "Soft rebuild from hospital light", textHot: "Soft rebuild from hospital light" }
  ]
};
