export default {
  id: "scene8k",
  layer: 8,
  title: "Town Cost",
  text: `Market Street had already begun to chew.

[player_name] stood under the hardware awning with Jake's shoulder warm against hers and rain stitching the slate roofs into one long argument while Mae's gold lettering fogged two doors down like a mouth that had decided to speak. Coffee steam ghosted from the diner vent. The blue door stuck in its frame as if even the building understood that opening now meant inviting eggs and questions in the same breath. Someone—Mrs. Pell from the bakery, or the man who delivered cream, or a voice wearing both—had already said Shaw and ice and left and debt in an order that was not Henry's weather. Gossip was not registered mail. It did not return to sender.

Jake's burn scar whitened on the thumb hooked in [player_name]'s coat pocket. "Cost of truth," he said quietly. Not accusation. Inventory. "Whether you poured it into Mae's lamp on purpose or sent copies out of county where lawyers sharpen quieter knives, Market Street has a taste now. Tomorrow the pie case will ask whether my father died on ice or on a lie. We can face that together—walk in, open the blue door, let the regulars see us refuse to sand—or we can leave town for a week while the talk burns itself down to ash and rumor. Both are verbs. Neither is a soft landing dressed as strategy."

[player_name] tasted copper and rain and the metallic bright of a public knife she had chosen to feed. Wet boxwood still lived in her sleeves from Willow. Woodsmoke clung to Jake's collar. Clara's charcoal arrows lived under glass and in phone photos and in the margins of a town that had practiced belief for fifteen years. Voss's name sat under her tongue like a coin already spent into circulation. Henry sat somewhere with an empty mug and a quieter house, listening for freight that would not save him.

"Facing Market Street together tomorrow means owning the chorus as audience," she said. "It means eggs go cold while someone asks whether I left for ambition or for Henry's arrangement. It means your diner becomes a stage before it becomes a livelihood again. Leaving for a week means we take our bodies out of the chewing—Willow, the station, somewhere rain is only weather—and let talk burn without our faces as fuel. It also means coming back to whatever story the town invents in our absence, and absence has always been Henry's favorite tool."

Jake huffed a laugh that was almost a wound. "I rebuilt this place around a wound. I can survive cold eggs. What I cannot survive is watching you invent a third road where we hide in the apartment and call the hiding mercy while Mae's slots fill with versions we never authorized. Face it with me—blue door, cracked stool, coffee steam, the half-degree lean of a counter that has heard worse—or leave with me for seven days and trust that love can outwalk gossip long enough to breathe. I will not love you less for either mud. I will only ask that you choose while the awning still drips and not in the shower later when fear gets eloquent."

Sensory first: rain on slate, fryer oil ticking, hardware-rust smell under the awning, Jake's coffee breath, the stick of the blue door in muscle memory, wet boxwood, woodsmoke, the particular curiosity of Somerton leaning in at gutters. Emotion: fury braided to tenderness braided to the fear of becoming entertainment before justice finished landing. Plot: town cost already arriving; lawyer copies or Mae's stamp already working; tomorrow as a blade; a week away as another blade; Clara waking into a chorus; Henry shrinking; trust asking whether presence or retreat was loyalty.

A delivery truck hissed past toward the freight yard. Inside the diner glass, the cracked counter stool leaned left like a witness waiting for a verdict. [player_name] watched her own reflection fog and clear beside Jake's—two people who had almost loved at twenty and were now deciding whether almost survived noon.

"If we face Market Street tomorrow," she said, "I need you angry and present, not polite. Polite is how the cover lasted. If we leave for a week, I need the leaving to be oxygen, not exile—tickets with return dates, hands that do not let go on the platform, no ambition story reinvented for the women who sort mail."

"Return dates," Jake agreed, thumb stroking her pulse through the coat pocket. "Or tomorrow's open sign flipped by my hand with yours on the latch. Soft landings are how we got the lie. Facing the noise together is not spectacle for sport—it is refusing to let Henry's weather be the last dialect this street speaks. Leaving while talk burns out is not cowardice if the burn would eat Clara before she finishes her own arrows. Sequence still matters. Loyalty still has tempo."

[player_name] thought of Clara upstairs on Willow with graphite on her fingers. She thought of Mae's stamp hovering over ink. She thought of fifteen years of practiced belief and how Market Street had helped the practice become nearly civic virtue. Ending the quiet meant feeding the town something true. Surviving the feed was the remaining blade.

Jake turned her gently until her back met the brick under the awning and his forehead met hers—not kissing yet, holding the fork bright between mouths. "I stayed," he murmured. "I raised Clara beside these lights. I listened for a train. Now the train is here and the town is chewing and I am asking whether you want to stand in the chew with me at dawn or take my hand to the station and let the week teach Somerton how to talk without our throats as instruments. Either exit moves. Either exit hurts on purpose."

Rain thickened. Coffee steam ghosted. The blue door stuck. Gold lettering fogged. Henry's unfinished name trembled in woodsmoke memory. Voss's shadow owned a corner of every ledger the town would suddenly remember. [player_name]'s pulse argued under Jake's thumb. Desire and dread shared a bloodstream with public noise. The morning refused to land soft.

Clara texted once—three words, no punctuation, the kind of honesty that refused etiquette: *theyre already talking*. [player_name] showed Jake the screen under the awning drip. His mouth flattened, then softened into something like pride braided to dread. "She found the papers," he said. "She drew the arrows. She does not get to wake into a chorus alone while we invent prettier logistics under hardware rust. If we face tomorrow, we bring her into the diner before the regulars—coffee first, truth second, eggs if anyone still has an appetite. If we leave for a week, we tell her the dates to her face on Willow, not in a message she can sand into abandonment."

[player_name] nodded, rain cold at her collar. "Henry will hear the talk whether we stay or go. Facing noon means he hears it with us in the room—no empty-mug solitude inventing softer mornings while Market Street does his work for him. Leaving means he hears it without our bodies as shield or blade, and I am no longer sure which kindness he has earned."

"He has earned the truth," Jake said. "Kindness is a separate ledger. Voss is a separate ledger. You and I are the ledger I care about balancing before the pie case turns us into sport with a moral." He squeezed her pocketed hand. "I can flip the open sign at dawn. I can also buy two tickets and a week of rain that is only rain. What I cannot do is stand here inventing a third option where gossip is real and we pretend it is not because wanting each other feels safer than being seen."

Wanting each other was not safer. It was the plot under the plot—trust wearing heat, heat wearing consequence. [player_name] let the awning drip count time on her sleeve and refused to look away from his eyes.

The hook set without soft landing: town cost already on the tongue of Market Street, Jake's unfinished question hanging in rain, the particular hurt of a woman who had bought a ticket home and was now deciding whether presence tomorrow or absence for a week was the loyalty that kept tenderness alive inside the chew. [player_name] drew a breath that tasted like wet brick and old coins and coffee and the man who had rebuilt a diner around a wound. The quiet of Somerton leaned in at the gutter to hear which hunger she would feed first—the courage of facing noon together, or the oxygen of leaving while talk burned, or the body that still wanted both and could not have a third sanded road.

Face Market Street together tomorrow. Or leave town for a week while talk burns out. The awning dripped. The blue door waited. The night-morning refused to land soft.

Freight complained again, longer, as if the yard itself wanted a vote on whether Shaw quiet died in public tomorrow or in a week of elsewhere rain. [player_name] kept her boots planted and her hand in Jake's pocket and let the unfinished question hurt exactly as much as craft demanded.`,
  textHot: `Market Street had already begun to chew, and [player_name]'s body had already begun to answer Jake under the hardware awning like gossip and want shared a bloodstream.

Rain stitched the slate. Mae's gold lettering fogged. Coffee steam ghosted from the diner vent. The blue door stuck. Jake had her backed to wet brick, coat open, thigh slotted between hers, cock a thick insistent line against her hip while Mrs. Pell's voice carried from the bakery corner—Shaw, ice, left, debt—in an order that was not Henry's weather. Gossip was not registered mail. Neither was the way [player_name]'s cunt clenched when Jake's mouth found the rain at her throat.

"Cost of truth," he rasped against her pulse, burn scar catching on her collar as his thumb stroked bare skin above her waistband. "Mae's lamp or a lawyer's inbox—does not matter now. The street has a taste. Tomorrow we can face it together—open the blue door hard for me, let the regulars see you wet-eyed and unashamed while I keep my hand on you under the counter like a vow—or we leave town for a week, fuck the chew out of our systems somewhere rain is only rain, and come back when talk has burned down to ash. Both keep me hard. Both keep you from inventing a softer hide."

[player_name] gripped his belt. Her nipples peaked against lace when a delivery truck hissed past and Jake rolled his hips once—helpless, then locked still—branding her through denim. "Facing Market Street tomorrow means eggs go cold while someone asks whether I left for ambition or for Henry's arrangement," she said, voice rough. "It means your diner becomes a stage. Leaving a week means oxygen—return dates, my mouth on you in a rented bed, no ambition story for Mae's trays—and it means coming back to whatever lie the town invents without our faces as fuel."

Jake shoved two fingers past her waistband, found cotton soaked through, and pressed her clit with public cruelty timed to the bakery gossip. "Feel the cost," he muttered. "That is what honesty does in a body. Soft landings are how we got the lie. I stayed. I raised Clara beside these lights. I listened for a train. Now I am asking whether you want to stand in the chew at dawn with my hand in your jeans under the pie case, or take my cock and my tickets to the station and let seven days teach Somerton how to talk without your cunt as their instrument."

Sensory through-line: wet brick on her shoulder blades, rain cold on her open throat, coffee steam, fryer tick, his fingers circling slow, cock hard at her hip, wet boxwood in her sleeves, woodsmoke in his hair. Emotion: fury and want and civic dread. Plot: town already chewing; Clara texting; choice as verb.

Clara's three-word text lit [player_name]'s pocket—*theyre already talking*—and Jake read it over her shoulder without removing his hand from her jeans. "She does not wake into a chorus alone," he said. "Face tomorrow and we bring her to the diner before regulars—truth with coffee, my mouth on yours in front of God and eggs if that is what courage looks like. Leave a week and we tell her dates on Willow to her face, then I take you apart in a room with no slate roof listening."

[player_name] laughed—wrecked, filthy—and rolled her hips onto his fingers because stillness had become another Shaw lie. "If we face noon, you stay angry and hard and mine while the pie case turns us into sport. No polite. Polite lasted fifteen years. If we leave, the leaving is oxygen not exile—and you fuck me on the first night like the quiet already broke and we are what grew in the crack."

"Return dates," Jake promised, withdrawing his fingers, painting her lower lip with her own wet. "Or dawn's open sign with your hand on the latch and my cock still remembering this awning. Choose. While Pell is still talking and your cunt is still shaking. Inventing a third road where we hide upstairs and call it mercy while Mae's slots fill is the only cowardice left on Market Street."

She tasted herself and rain and him. Voss's coin. Henry's empty mug. Clara's arrows. The cracked stool leaning behind glass. Freight complaining. Desire and dread arguing in one pulse. Trust was the real plot, and trust was asking whether presence tomorrow or absence for a week kept tenderness alive inside the chew.

Jake kissed her once—deep, public enough that anyone looking would file it under memory—then made space for the verb like a man who understood civic light and private heat could share a street without apologizing. "I can flip the open sign," he said. "I can buy tickets. What I cannot do is stand here with your taste on my mouth while you sand the choice into prettier logistics. Face Market Street together tomorrow—walk into the noise with me. Or leave town for a week while talk burns out—take my hand to the platform and let the burn happen without our throats."

[player_name] wiped rain from her mouth with a sticky thumb and kept her boots planted. The blue door stuck in muscle memory. Gold lettering fogged. Woodsmoke. Wet boxwood. The unfinished ache between her legs timed to gossip she had chosen to feed.

Under the awning the rain thickened into a curtain that almost made privacy, and Jake used it—palm spanning her ribs under the sweater, thumb brushing the underside of her breast until her knees threatened the kind of buckle Market Street would notice. "I am not performing heat for the chorus," [player_name] whispered. "I am refusing to let the chorus go celibate of consequence while my body pretends it can wait politely for dawn." She caught his wrist and held him there, calibrating, not stopping. "Tomorrow's open sign means I walk in still aching from this. A week away means I take this ache onto a train and let you finish what your fingers started in a bed that does not smell like fryer oil and old cover stories."

Jake's laugh shook against her sternum. "Fryer oil is my religion," he said. "Cover stories are my heresy. If we face noon, I want you in the cracked stool's eyeline—visible, claimed, done with ambition costumes. If we leave, I want your legs around me before the first station whistle dies, because watching you own town cost while soaked for me is going to live in my cock longer than any rumor Pell can bake." He nipped her earlobe, then sobered. "Clara's text is not ambient noise. Henry's mug is not ambient. Voss's shadow is not ambient. Choose a verb that moves those ledgers. Heat without a verb is just another prettier quiet."

[player_name] thought of the ticket she had bought at twenty and the ticket home and the tickets they might buy again for seven days of elsewhere. She thought of flipping the open sign with Jake's hand over hers. She thought of Mae's stamp and lawyer PDFs traveling out of county and how both roads had poured truth into mouths that did not love them. Surviving the pour was the blade left in her palm.

"I can be seen," she said. "I can also breathe elsewhere and return sharper. What I will not do is sand this awning into a maybe while your thigh is still between mine and the bakery is still chewing our names." She rolled once against him—honest, unfinished—then locked still. "Face tomorrow with me, or leave a week with me. Both muddy. Both mine. Both yours."

Jake pressed his forehead to hers until rain ran between their noses like a shared vow. "Then spend the verb before the regulars rattle the latch. My diner does not care about your cunt or my vow except insofar as both show up when the quiet finishes breaking. Speak."

The hook held: town cost on every tongue, Jake's unfinished question hanging in rain, body still humming, morning refusing soft landing. Face Market Street together tomorrow—or leave for a week while talk burns. [player_name] drew a breath that tasted like wet brick and coffee and old coins and the man who had rebuilt a diner around a wound. The quiet leaned in at the gutter to hear which hunger she would feed—the courage of noon, the oxygen of elsewhere, or the heat that had turned public chewing into a reckoning she could feel in her pulse and her cunt and the place where apology used to live.

Choose. The awning. The blue door. His hand still wet. Somerton tracked mud either way and the night-morning refused to land soft.

Freight complained through the curtain of rain. Wet boxwood breathed from her coat. Woodsmoke lived in his collar. [player_name] kept her boots planted and her taste on her lip and let the unfinished ache between her legs argue strategy until the only cowardice left was delay. Delay was Henry's weather. She refused to wear it now.`,
  choices: [
    { id: "scene9f", text: "Face Market Street together tomorrow", textHot: "Face Market Street tomorrow — open the blue door still aching" },
    { id: "scene9h", text: "Leave town for a week while talk burns out", textHot: "Leave a week — take his cock and tickets while talk burns" }
  ]
};
