export default {
  id: "scene8m",
  layer: 8,
  title: "Fragile Hope",
  text: `The diner's blue door stuck the way it always stuck, and for once [player_name] did not mind fighting it open. Rain sheeted Market Street behind her. Coffee steam ghosted the CLOSED sign. Inside, John had lit only the pie-case lamps and the strip above the cracked counter stool that leaned its half-degree left like a witness with a limp. Fryer hymn slept. The booths held shadow instead of regulars. Fragile hope smelled like lemon oil on wiped Formica and the particular bravery of people who had closed a ledger and did not yet trust the quiet that followed.

Clara sat on a stool with charcoal under her nails and a sketchbook closed for once. Henry was not present—Willow Lane held him with woodsmoke and a mantel clock that had learned to tick without lying for whole minutes at a stretch. The debt thread that had worn Voss's name like a bruise had been paid, burned, or otherwise forced into a past tense that still felt too new to celebrate. [player_name] stood dripping on the mat and felt the room try on happiness the way a coat tries on a body that has lost weight: hopeful, loose, ready to slip.

John wiped his hands on a towel that had seen fifteen years of his staying. Burn scar pale on the thumb. Coffee on his breath when he crossed to her. "You promised Clara you would not abandon the family again," he said, not accusing, inventorying. "She believed you enough to put the sketchbook down. That is rarer than a paid creditor. We can throw a quiet reopen tonight—family only, no Market Street chorus, just eggs and the blue door and the stool that knows our names. Or we can skip the celebration and walk to the station while hope is still thin enough to test against platform hiss. Both are verbs. Soft would be pretending the ledger's close means the story is finished."

[player_name] tasted copper and rain and coffee steam. Sensory first: wet slate outside, blue paint under her palm, fryer oil sleeping in the vents, wet boxwood still ghosting her coat from Willow. Emotion: tenderness sharp enough to cut, fear of jinxing a fragile morning, want for John that had nothing polite left in it and everything unfinished. Plot: debt closed or nearly; vow spoken to a sister; celebration or station as the next fork; Henry's silence a third guest at every empty booth.

"Fragile hope is a dangerous dish," she said. "Serve it too hot and it scalds. Serve it cold and it tastes like another cover. If we reopen for the family only, we are practicing a future with salt and plates—Clara watching us not leave, you cooking like the diner belongs to daylight again, me learning how to sit without packing a ticket under my thigh. If we skip celebration and go to the station, we are stress-testing the vow against the place I once used as an exit wound. Both keep the ledger honest. Neither lets Henry narrate our joy into weather."

Clara spun once on the stool, charcoal-dark eyes bright. "I did not ask for a party," she said. "I asked not to be abandoned mid-sentence. A quiet reopen is not a parade. It is proof. Station is also proof—just colder, and it smells like the night you left. I will sketch either ending. I will not sketch you inventing a third road where nobody eats and nobody decides."

John's hand found [player_name]'s wrist under the counter edge, thumb on her pulse the way he had in Mae's light and under hardware awnings and in rain that refused soft landings. "I rebuilt this place around a wound," he murmured. "I can light the pie case for three people and call it a reopen. I can also walk you to the platform and stand in the hiss until you tell me whether the ticket in your coat is habit or plan. What I cannot do is watch fragile hope become another Shaw silence because we were too afraid to choose a verb while the coffee was still hot."

Outside, freight complained toward the yard. Rain needled the glass. The cracked stool listened. Wet boxwood waited on Willow with papers under a glass weight that finally looked less like tidy guilt and more like archive. Clara's restless honesty waited on the charcoal-smudged stool. Voss's shadow had thinned to a ledger line. Henry's name sat unfinished in woodsmoke memory, not forgiven, not erased—simply not invited to carve the first toast.

[player_name] thought of fifteen years of practiced belief—the girl who wanted more—and of the letter that had cracked the quiet open. She thought of John raising Clara beside diner lights, of a winter accident sanded into weather, of a debt paid with someone's sacrifice she still did not fully map. Fragile hope was not innocence. It was the decision to feed something true before fear starved it.

"If we reopen," she said, voice carrying station platform memory and brighter rooms she no longer owed, "I want the blue door stuck and fought and owned. I want Clara's plate first. I want your hands on the grill like a claim, not a penance. I want Henry's absence named without turning the booth into a courtroom. If we go to the station, I want no sanded speech on the platform—only the hiss and the question of whether I am staying because I swore it or because my body finally stopped packing exits."

John laughed once, wrecked and fond. "Either exit keeps me here," he said. "Reopen means I cook while hope shakes. Station means I stand in rain while you decide if the vow survives freight. Both hurt in useful ways. Standing here inventing a softer third dish while Clara's sketchbook stays closed out of mercy is the only cowardice left on Market Street."

Mae's gold lettering fogged two storefronts away in memory. Coffee steam thickened. [player_name] catalogued the room like evidence: pie case glow, CLOSED sign, John's towel, Clara's charcoal, the stool's lean, rain on slate, the particular electricity of a night that could become family ritual or another ticket purchase. She covered John's hand on her wrist—not stopping him, calibrating—and faced the fork bright behind her teeth.

"Throwing a quiet diner reopen for the family only is not pretending the wound never existed," she said. "It is refusing to let the wound be the only guest. Skipping celebration to go to the station and decide is not abandoning Clara's vow—it is stress-testing it where leaving used to live. Both are loyalty. Soft is the lie that hope needs no verb."

Clara slid off the stool, sketchbook hugged to her chest. "Then pick before the coffee dies," she said, almost gentle, which from Clara was sharper than shouting. "I can set three plates. I can also walk you both to the platform and refuse to cry if the hiss wins for an hour. What I cannot do is watch you rehearse tenderness until morning invents your choice for you."

John's thumb stroked once at [player_name]'s pulse—consequence, not comfort. Fryer oil slept. Freight complained. The blue door stuck in its frame like a held breath. Wet boxwood. Woodsmoke. Papers under glass. Clara's graphite waiting. Henry's unfinished forgiveness. The hook set without soft landing: fragile hope poured into a closed diner, celebration or station undecided, John's hand on [player_name]'s wrist like a vow that still smelled like rain, the particular hurt of a woman who had closed a ledger and was now deciding whether joy got to practice before fear finished its speech.

[player_name] drew a breath that tasted like coffee and old coins and lemon oil and the courage of ending a quiet without demanding the ending be pretty. The pie-case lamps held steady. Market Street leaned in at the gutter to hear which hunger she would feed first—the family's need for a plate in the light, or the station's need to test a vow against the place tickets are bought.

John poured two mugs without asking and set Clara's first, then [player_name]'s, then his own—the choreography of a man who had fed a town through winters and still measured love in who got steam first. "Hope is not a parade," he said. "It is showing up with plates when the ledger finally stops screaming. If we reopen quiet, we are not erasing Henry or Voss or the ice. We are refusing to let them own the only light left in this room. If we walk to the station, we are not breaking your vow to Clara—we are taking the vow somewhere it used to die and asking it to breathe under freight. I need the verb while the coffee is honest. I need you to stop rehearsing both futures in your mouth like they are the same sentence."

[player_name] wrapped her hands around the mug. Heat climbed her palms. Outside, rain wrote long sentences on Market Street glass. She thought of the letter that had brought her home, of Clara's charcoal circles, of Henry's hands shaking around a cover story at twenty, of John's burn scar whitening whenever courage got close enough to touch. Fragile hope was not forgetting. It was choosing which hunger to feed before midnight invented another quieter lie.

"I can taste both roads," she admitted. "Reopen tastes like salt and belonging and the terror of being watched kindly. Station tastes like platform hiss and the old exit and the chance to prove I am not buying tickets in secret anymore. Neither tastes like Henry's weather. That is how I know they are real."

Clara tapped the closed sketchbook once. "Real is good. Soft is not. Pick."

Throw a quiet reopen. Or skip celebration and go decide. The diner refused to land soft. The night waited with rain on slate and a blue door that would stick either way.`,
  textHot: `The diner's blue door stuck, and [player_name] shoved it with her hip because John's hand was already under her coat at the small of her back, possessive, rain-wet, hard enough against her that fragile hope arrived in her body before it arrived in the room. Coffee steam. CLOSED sign. Pie-case lamps only. The cracked counter stool leaned its half-degree left like it had opinions about fucking in empty booths. Fryer hymn slept. Clara sat with charcoal under her nails and the sketchbook closed, which was its own kind of permission and its own kind of knife.

John kicked the door shut behind them. Burn scar pale on the thumb that slid to [player_name]'s hipbone under her sweater. His cock pressed a thick line against her ass through denim whenever he breathed, and he breathed like a man who had closed a debt and refused to let celebration go celibate. "You swore to Clara you would not abandon us," he said into her hair, loud enough for the sister, filthy enough for the pulse under his palm. "She believed you. That buys us a quiet reopen—family only, eggs, this stool, my hands on the grill and then on you once Clara goes upstairs. Or we skip the soft plates and walk to the station wet, and you tell me against the timetable whether the vow survives platform hiss. Both keep me hard. Soft would be pretending paid paper means your cunt stopped packing exits."

[player_name]'s nipples peaked against lace at the word exits. Her cunt ached from hours of unfinished wanting—Willow woodsmoke, Clara's vow, ledger close, John's nearness—useful ache, braided to hope that felt like standing on ice that might hold. "Fragile hope is a dangerous dish," she said, steadier than the clench of her thighs. "If we reopen for family only, I sit on that cracked stool and let you feed me while Clara watches us not leave, and afterward you take me upstairs above the fryer and fuck the ticket-habit out of my body like a claim. If we go to the station, I want your hand in my coat the whole walk, thumb on my clit through cotton if you need to keep me honest, and no sanded speech—only hiss and the question of whether I am staying because I swore it or because I am soaked for the man who stayed."

Clara spun on the stool, eyes bright, mercifully looking at the pie case instead of John's hand. "I did not ask for a parade," she said. "I asked not to be abandoned mid-sentence. Reopen is proof. Station is proof that smells like the night she left. Pick a verb. I will not sketch you inventing a third road where nobody eats and nobody comes."

John laughed once against [player_name]'s neck—open-mouthed, a suck Mae would have filed under memory—and shoved two fingers past her waistband just enough to find cotton already soaked. Humiliating under pie-case glow. Honest as freight. He pressed once against her clit through the fabric, a brand aimed at decision not orgasm. "Reopen," he rasped, "and I cook shaking, then I bend you over that stool after Clara's door closes and make fragile hope mean my cock and your cunt agreeing on Somerton. Station—and I walk you through rain hard enough to ache, keep my fingers where they are under your coat until the platform forces a sentence out of you. Standing here inventing a softer dish while you drip on my hand is the only cowardice left on Market Street."

Outside, rain sheeted. Freight complained. Wet boxwood waited. Woodsmoke. Voss's thinned shadow. Henry's absence like a third booth. [player_name] rolled her hips a fraction against John's fingers because stillness had become another Shaw lie, then forced stillness back because Clara deserved a vow spoken with a clear throat.

"If we reopen," [player_name] breathed, gripping the counter edge, "you do not soften the night into manners. You stay angry and hard and mine while we practice plates. If we skip celebration for the station, you do not waste the hiss on Henry's weather—you make me say stay or go with your mouth on my pulse and your hand owning the question."

"Either exit," John promised, withdrawing slowly enough that rain almost covered the wet sound, catching her wrist instead with a sticky thumb on her pulse. His cock still pressed her. "Throw a quiet diner reopen for the family only—then take me upstairs after. Or skip celebration, go to the station, and decide while I keep you shaking. I will not love you less. I will only need inside you after—booth, stool, wet platform shadow—because watching you feed fragile hope into a verb while wet for me is going to live in my body longer than any ledger Henry ever sanded."

Clara cleared her throat. "Coffee is dying. Spine is the question."

[player_name] planted both palms on Formica, leaned into John's heat until coffee and rain and want braided into one breath. She catalogued her body like evidence: nipples aching, jeans seam rude, mouth tasting copper and lemon oil and the ghost of his kiss. Reopen-vow would bind her to booth light and Clara's morning questions and John fucking the stay into her above the diner. Station-vow would bind her to saying the date or the refusal where tickets are sold, even if saying it made his hands pause on her hips mid-claim. She wanted those hands either way.

Mae's trays lived two doors down in memory. The blue door stuck. Pie-case lamps held. John's thumb stroked once—consequence. "[player_name] is picking," she said, and the words felt like stepping onto ice. Hook tight: unanswered celebration, unanswered platform, unanswered heat thick enough to change the air pressure in the empty diner.

Throw the quiet reopen—family only, then the claim upstairs. Or skip celebration and go to the station to decide with his hand still sticky on her pulse. The CLOSED sign fogged. Market Street leaned in at the gutter. The quiet of Somerton refused to land soft.

John poured coffee one-handed because the other stayed branded at [player_name]'s hip, sticky thumb still tasting of her through memory. "Hope is not celibate," he murmured against her ear, loud enough that Clara snorted and looked hard at the pie case. "If we reopen, I feed you first, then I take you upstairs and fuck the fragile into something that holds—slow if you need it, hard if you ask, either way with your legs around me and the fryer oil ghosting through the floorboards like a hymn that finally learned dirty words. If we go to the station, I keep you wet under your coat the whole walk so the platform cannot pretend this is only philosophy. Say the verb. Stop letting your cunt and your courage argue in two different languages."

[player_name] laughed once, wrecked, fogging the CLOSED sign. Her nipples ached. Her pulse argued strategy in sticky thumbprints. She wanted plates and she wanted hiss and she wanted John's cock answering whichever road she named. "Reopen means belonging with an audience of one sister and a stool that leans. Station means stress-testing the stay where leaving used to live. Both keep you hard. Both keep me from sanding. Both hurt useful."

Clara tapped the sketchbook. "Pick before I sketch you mid-hesitation with little devil horns."

John rolled his hips once—helpless, then locked still—and breathed hard enough that the empty booths seemed to lean in. "I rebuilt this diner around a wound," he said. "I can survive a quiet reopen shaking. I can survive platform rain with my hand in your jeans. What I cannot survive is watching you invent a third stamp because you still think my name is too fragile for joy and tickets in the same hour."

Choose. John's cock. Clara's closed sketchbook. Plates or platform hiss. Fragile hope waited to be fucked into a future or stress-tested in the rain, and either way the blue door would stick like a held breath that finally learned how to moan.

Rain thickened until Market Street became a wet mirror for everything her body already knew: John hard behind her, cotton ruined, hope filthy with wanting, Clara's patience a timer, the ledger closed enough to let fucking mean future instead of escape. [player_name] tasted copper and coffee and the particular courage of women who refused to let celebration or station go soft just because fear asked politely.

She catalogued the empty diner like a body: booth shadows as open mouths, pie-case glow as heat on skin, cracked stool as the place John would bend her if reopen won, platform hiss as the place he would finger her honesty if station won. Wanting was not the fork. The fork was which sentence got to own the night before Henry's weather tried to sand it again.

She catalogued the empty diner like a body: booth shadows as open mouths, pie-case glow as heat on skin, cracked stool as the place John would bend her if reopen won, platform hiss as the place he would finger her honesty if station won. Wanting was not the fork. The fork was which sentence got to own the night before Henry's weather tried to sand it again.`,
  choices: [
    { id: "scene9g", text: "Throw a quiet diner reopen for the family only", textHot: "Throw a quiet reopen — then take him upstairs after Clara" },
    { id: "scene9h", text: "Skip celebration — go to the station and decide", textHot: "Skip celebration — station hiss with his hand still on you" }
  ]
};
