export default {
  id: "scene3d",
  layer: 3,
  title: "Back to the Blue Door",
  art: "/art/until-the-quiet-breaks/scene3d.png",
  text: `[player_name] left Willow before Henry could finish sanding the edges off his guilt. The letter stayed in her pocket unread aloud; she would not let him narrate her reunion with his careful eyes and his late courage and his tea going cold on a saucer that had clicked once with nerves. Rain slicked her hair to her cheek as she cut back toward Market Street, shoes darkening, breath visible in the cooling air. Behind her, wet boxwood dripped onto porch boards. Woodsmoke clung to her coat like a second opinion she had refused to hear in full. Henry had started—debts, a winter road, a cover story cast as ambition—and she had walked out while the confession was still half-shaped, because some truths needed John's face in the room before an uncle's voice filled it.

The road shone black. Slate roofs dripped in slow patient rhythms. Somerton did not look surprised to see her descending the hill she had climbed an hour before; it looked as if it had been practicing the face it would wear when she chose the diner over the mantel, the blue door over the paperweight, the man who stayed over the man who wrote. A truck hissed past and threw water against the curb. She tasted rain and metal and the old ache of almost. Henry's hints sat in her chest like stones she had not yet decided whether to set down in John's hands or keep pocketed until she understood their weight.

Market Street took the rain the way it always had—into the gutters, into the cracks between the bricks, into the smell of fryer oil that rose even before she reached the diner. The blue door stuck. She put her shoulder to the wood and felt the familiar give. The bell cried thin and true. Inside: coffee steam ghosting the windows, the tick of the pie case, rain freckling the front glass, the cracked counter stool nearest the register still leaning its half-degree left. The dinner rush was alive—wet coats, overlapping voices, the fryer's hot metal hymn through the pass. Specials board listing beef stew and apple crumb. Ordinary hunger continuing an inch away from history.

John looked up mid-order, saw her face, and handed the plate off without glancing at the customer. Something moved behind his grey eyes—relief, dread, the weather of a man who had hoped Henry would write and feared what the writing would bring. "Clara," he called, voice steady for the room and not steady at all for her. "You have the floor."

Clara's eyes flicked between them, sharp with questions she filed for later, charcoal already smudged along her apron string as if she had been sketching between tickets. Sixteen going on forty. She nodded once and took the ticket spike like a sword. "Don't vanish between the bell and the rain," she murmured as [player_name] passed, soft enough for only them. "He practiced losing you. He's done rehearsing." Then she was plating stew and fielding a laugh from the back booth, restless honesty deferred but not abandoned.

John steered [player_name] through the swing door into the narrow back hall by the dish pit. Steam and soap closed around them. The kitchen fan roared. A tray of cups rattled somewhere like distant bells. Grease shone faintly on his forearm; a flour ghost whitened his wrist; the burn scar at the base of his thumb caught the fluorescent light when he braced a hand on the shelf above her shoulder—close, careful, shaking once. Rain still beaded in his hair from some earlier trip to the alley bins. He smelled of coffee and fryer oil and the mint he kept in the register drawer, braided now with her woodsmoke, as if Willow and Market Street had agreed to argue on his skin.

"You saw him," John said. Not accusation. Weather report. His throat worked. The fan roared on. Through the swing door, a customer laughed; ordinary life continued an inch away while their private weather held.

"He started," [player_name] answered. Voice even. Fifteen years of practice, and still the words wanted to catch. "I stopped him. Debts. A winter road. A cover that cast me as ambition so you would not have to see the whole of your father's ending. He was sanding as he spoke. I wanted your voice in the room before his filled it. I have lived too long inside speeches written for someone else's sake."

John closed his eyes for a breath. When he opened them, the grey held the Somerton sky the way it always had—steadier now, practiced at weather, still capable of breaking. "Clara found papers," he said quietly. "I told you that. Henry went pale. I knew he had mailed something. I did not know you would walk into my diner smelling of his woodsmoke with half a confession in your pocket and rain on your face like you'd run from a fire before it finished burning." His hand on the shelf flexed; the scar whitened. "Then tell me what you will of what he hinted. Or ask me what I remember of the night you left, and we build from my scraps instead of his speech. I will not hate either answer. I will feel both."

Through the swing door, Clara's voice rose—correcting an order, deflecting a question about the woman who had just walked through, protecting the back hall with the same stubborn loyalty she brought to charcoal and unlocked desks. [player_name] heard the blue door stick and yield again. The rush pressed on. John did not look away from her. He had built a life from plate, napkin, refill—small motions that kept the lights on while the real conversation waited under the steam—and now the real conversation had nowhere left to hide.

"I remember you crying on the station steps and pretending you weren't," he went on, softer, as if the dish-pit steam could keep the words from traveling upstairs into whatever room Clara claimed when the night went quiet. "I remember Henry's hand on your suitcase like a benediction and a shove. I remember being told you wanted more—brighter rooms, a longer map, a life that did not end at Market Street. I remember not believing it—and believing it anyway, because belief was the only way to keep the diner open and Clara fed and my hands from breaking things. I remember the winter my father died and the way the town's story never matched the weather in my chest. I remember trying to make the pieces fit for fifteen years and failing in private while I succeeded at coffee and stew and not asking Henry the questions that would have cracked his careful face."

[player_name] felt both futures settle into her bones. The one where Henry's hints spilled first—debts named, cover story opened, the uncle's version laid on the shelf between them like a plate still hot—and cracked John open fast, trust splintering on the speed of another man's narrative. The one where shared memory came before the full ledger: her questions, his scraps, the night on the station steps rebuilt between them without Henry's sanding tools in the room. Neither was painless. Both were more honest than the fifteen years behind them. Rain hammered the alley door. The kitchen fan roared. A cup shattered somewhere in the pit and Clara swore softly, ordinary damage interrupting extraordinary weather.

John waited. Grey eyes steady. Offering her the kind of choice Henry had never offered—the last inch without demand, heat without a script. "If you tell me everything he hinted," John said, "I will listen. I will be angry. I will probably walk up Willow before close and make him say it again to my face. If you shield me from his version and ask only what I remember, I will give you every scrap I have, and we will decide together how much of my uncle's voice we invite back into the story. Either way, do not vanish between this hall and the rain. I have practiced losing you. I am done rehearsing it."

[player_name] tasted soap steam and coffee and the mineral cold still clinging to her coat from Willow Lane. She thought of Henry's hand hovering near her sleeve an hour ago, the same almost-gesture from years before when he had asked her to leave for John's sake and called it love. She thought of Clara's charcoal sketches, of papers under glass, of a letter that never said come home. She thought of the cracked stool beyond the swing door, of the blue door's stubborn stick, of a boy with rain in his hair grown into this man with a burn scar and flour on his wrist and fear held like a plate still hot. The fork was not at the station anymore. It was here, in the narrow back hall, with the rush continuing an inch away and redemption smelling like dish soap and rain.

She could spill Henry's hints and watch trust crack on impact—honest, fast, possibly cruel. Or she could shield him from the uncle's version and ask only what he remembered of the night she left, building the truth from shared scraps before any ledger finished the picture. John's hand stayed on the shelf above her shoulder. Close enough to feel like a question. Close enough to see the scar again. The quiet between them was not empty. It was waiting to break, and this time the break would be hers to aim.`,
  textHot: `Rain took [player_name] out of Willow like a theft she chose—Henry still mid-sentence, guilt only half-sanded into something swallowable—while her body ran ahead of her conscience downhill toward John, half a confession and a full night's unfinished wanting riding under her coat. Letter stayed pocketed, unread aloud; she would not let careful uncle-eyes narrate the reunion, late courage and cold tea clicking once on a nervous saucer. Rain slicked hair to her cheek. Shoes darkened. Breath showed in cooling air. Behind: boxwood dripping porch boards, woodsmoke clinging like a second opinion refused in full. Henry had started—debts, winter road, cover cast as ambition—and she walked while confession was half-shaped because some truths needed John's face before an uncle's voice filled the room, and because some hungers needed John's mouth more than neat sentences. Her cunt agreed. Shameless. Already.

Road black. Slate dripping patient. Somerton unsurprised to see her descend the hill she climbed an hour before—practicing the face for diner over mantel, blue door over paperweight, man who stayed over man who wrote. Truck hissed, threw curb water. She tasted rain, metal, the old ache of almost—hotter now, adult, living between ribs and lower where polite stories did not go. Henry's hints sat in her chest like stones for John's hands or her pocket. Her palms, traitors, already shaped his jaw. Her thighs remembered how narrow a dish-pit hall could be.

Market Street took rain into gutters, brick cracks, fryer-oil smell rising before she reached the diner. Blue door stuck. Shoulder to wood: loyalty awkward, damp resisting, then yielding the way a body yields when it has been waiting. Bell thin and true. Inside: coffee steam ghosting windows, pie-case tick, rain freckling glass, cracked stool leaning half-degree left. Dinner rush alive—wet coats, overlapping voices, fryer hymn through the pass. Stew and apple crumb. Ordinary hunger an inch from history. And John—sleeves rolled, shoulders broad, burn scar catching light—looked like the hunger history could not tidy. Looking at him soaked her. Instant. Undignified. Earned.

He looked up mid-order, saw her face, handed the plate off without glancing at the customer. Behind grey eyes: relief, dread, weather of a man who hoped Henry would write and feared the writing—and under it, unmistakable across a crowded room: wanting, banked, adult. Her mouth went dry. Thighs pressed under wet coat. "Clara," he called, steady for the room, not steady for her. "You have the floor."

Clara's eyes flicked between them, questions filed, charcoal on apron string. Sixteen going on forty. Ticket spike like a sword. "Don't vanish between the bell and the rain," she murmured as [player_name] passed. "He practiced losing you. He's done rehearsing." Dry as chalk: "Also he's been staring at that door like it owes him a kiss. Go before I start drawing it—and for God's sake, if you're going to wreck each other in my dish pit, keep it quieter than the fan." Then stew and back-booth laughter, honesty deferred not abandoned.

John steered [player_name] through the swing door into the narrow back hall by the dish pit. Steam and soap closed. Kitchen fan roared. Cups rattled like distant bells. The hall was too narrow for politeness: his chest nearly brushed her breasts when he turned; her back found the shelf; air went tight and hot. Grease on his forearm; flour ghost on his wrist; burn scar fluorescent when he braced a hand on the shelf above her shoulder—close, careful, shaking once. Rain beading his hair from alley bins. Coffee, fryer oil, register mint, braided with her woodsmoke—Willow and Market Street arguing on his skin. She wanted her mouth on that scar. Wanted mint and salt and grill-heat. Wanted to drop her hand to the hard line she could already feel warming the space between them. She kept hands at her sides by theatrical will. Her cunt did not get the memo; it pulsed once, hard, when his hips stayed close enough that denim heat bled through damp wool.

"You saw him," John said. Not accusation. Weather report. Throat working. Fan roaring. Through the swing door a customer laughed; ordinary life an inch away while private weather held—and while his body stayed unfinished against the almost of hers. Eyes dropped to her mouth. Looked away like the glance was confession. She saw the truth anyway: he was hard, or close, and furious at himself for it, and done hiding it from her.

"He started," [player_name] answered. Voice even. Fifteen years of practice, words still wanting to catch—wanting to become come closer, kiss me before the ledger, put your hands under this coat and remind me I am not only a story Henry wrote. "I stopped him. Debts. A winter road. A cover that cast me as ambition so you would not see the whole of your father's ending. He was sanding as he spoke. I wanted your voice in the room before his filled it. I have lived too long inside speeches written for someone else's sake." Swallow. "I also wanted your face. Not his. Yours. I wanted to walk in here wet from rain and wet from thinking about your mouth and put the unfinished truth in your hands while I still had the courage to stand this close without climbing you. That is not tidy. It is true."

John closed his eyes a breath. Opened them: Somerton sky, practiced weather, capable of breaking, dark with hunger dish-pit steam could not hide. "Clara found papers. I told you. Henry went pale. I knew he mailed something. I did not know you would walk into my diner smelling of his woodsmoke with half a confession in your pocket and rain on your face like you ran from a fire before it finished—looking at me like you might let me finish something else entirely." Shelf-hand flexed; scar whitened. Other hand hovered near her waist and did not land—last inch, heat without script. "Tell me what you will of what he hinted. Or ask what I remember of the night you left, and we build from my scraps instead of his speech. I will not hate either answer. I will feel both. God help me, [player_name], standing this close I feel more than answers. I feel my cock voting while my mouth tries to be careful. I'm done pretending those are separate rooms."

Clara's voice rose beyond the swing—correcting an order, deflecting questions about the woman who walked through, protecting the back hall with charcoal loyalty. Blue door stuck and yielded again. Rush pressed. John did not look away. Life of plate, napkin, refill—lights on while real conversation waited under steam—and now conversation and wanting had nowhere left to hide. Nipples tightened against wet fabric when his breath touched her cheek. She shifted; hip brushed his; neither apologized. Contact lingered past accident. She felt him—thick, insistent, honest—and her own slick answer made standing still a kind of fucking without moving.

"I remember you crying on the station steps and pretending you weren't," he went on, softer, steam conspiring to keep words from Clara's upstairs—softness failing to hide how unfinished his body still was with her. "Henry's hand on your suitcase like benediction and shove. Told you wanted more—brighter rooms, longer map, life not ending at Market Street. Not believing it. Believing it anyway, because belief kept the diner open and Clara fed and my hands from breaking things. Winter my father died. Town story never matching the weather in my chest. Fifteen years failing in private while succeeding at coffee and stew and not asking Henry the questions that would crack his careful face." Voice dropped. "I remember wanting you on those steps. Wanting you every year after. That part never got sanded. I remember imagining your cunt when I shouldn't have. I remember getting hard in this hall on worse nights than this and hating myself for it. I don't hate it tonight. You're here. I'm done rehearsing hate."

[player_name] felt both futures settle into bone—and felt her body vote, shameless, for whichever future included his mouth somewhere in the reckoning. Spill Henry's hints first—debts named, cover opened, uncle's version on the shelf like a hot plate—crack John fast on another man's narrative while she stood close enough to catch him, forehead to forehead, maybe hand on the hard heat of him as comfort and claim. Or shared memory before the full ledger: her questions, his scraps, station steps rebuilt without Henry's sanding tools—memory that might turn into hands on waists and mouths remembering almost, into her palm down his jeans if truth and wanting finally stopped pretending they were different plots. Neither painless. Both more honest than fifteen years behind them. Rain hammered the alley door. Fan roared. Cup shattered in the pit; Clara swore softly—ordinary damage interrupting extraordinary weather. John's thigh brushed hers again. Heat flared low and bright. She did not step back. She rolled her hips a fraction, deliberate, felt him suck a breath through his teeth, and held the line of contact like a vow.

John waited. Grey steady. Choice Henry never offered—last inch without demand, body braced over hers like a question in muscle and mint and rain. "If you tell me everything he hinted, I listen. I get angry. I probably walk Willow before close and make him say it to my face. If you shield me from his version and ask only what I remember, I give every scrap, and we decide together how much of my uncle's voice we invite back." Gaze to her mouth, then eyes. "Either way, do not vanish between this hall and the rain. I practiced losing you. I am done rehearsing it. And either way—after the words—if you still want my hands, they are yours. If you want my cock, say it and I will fuck the carefulness out of this night against this shelf with the rush one inch away. I am done pretending that part is separate from the truth."

[player_name] tasted soap steam, coffee, mineral cold from Willow on her coat—and under it John's clean heat, close enough to kiss if she rose on her toes, close enough to taste herself on the future of his mouth. Henry's hand hovering near her sleeve an hour ago: the same almost from years before when he asked her to leave for John's sake and called it love. Clara's charcoal. Papers under glass. Letter that never said come home. Cracked stool beyond the swing. Blue door's stubborn stick. Boy with rain in his hair grown into this man—burn scar, flour wrist, fear held like a hot plate, desire held the same way, shaking once, honest, cock pressed near her hip like a second confession. Fork not at the station. Here. Narrow back hall. Rush continuing. Redemption smelling like dish soap and rain and the salt-sweet promise of a mouth not yet claimed—and a cunt already deciding the claiming was inevitable.

Spill Henry's hints and watch trust crack on impact—honest, fast, possibly cruel—while standing close enough that cracking might end with his forehead on hers and her hand wrapped around him through denim as the only mercy left. Or shield him from the uncle's version, ask only what he remembered of the night she left, build truth from shared scraps before any ledger finished—scraps that included wanting, station steps, unfinished almost, adult hunger humming now with her nipples tight and his cock hard and Clara's fan roaring cover for whatever came next. John's hand on the shelf above her shoulder. Close enough to question. Close enough to see the scar. Close enough that turning her face would brush lips to the inside of his wrist—and if she parted them, taste salt and flour and the future. The quiet between them was not empty. It waited to break, and this time the break was hers to aim: spill or shield, truth-fast or memory-first, both paths through the same steam toward a man whose body had already voted to keep her—hook set on mouth, cock, and the ugly honest choice that would decide how the quiet broke.`,
  choices: [
    { id: "scene4g", text: "Tell John everything Henry hinted at", textHot: "Spill Henry's hints — crack trust open while you still want his mouth" },
    { id: "scene4h", text: "Shield John from Henry's version — ask only what he remembers of the night you left", textHot: "Shield him — rebuild the night from shared scraps before any ledger" }
  ]
};
