export default {
  id: "scene7j",
  layer: 7,
  title: "Secret a Little Longer",
  text: `Jake had chosen her in a voice that still smelled like coffee and rain, and [player_name] had accepted the choosing with a yes that left the secret unfinished between their teeth.

Now the diner's upstairs flat held them like a held breath. Rain needled the slate roof above Market Street. The blue door stuck two floors below, CLOSED sign crooked, fryer hymn gone quiet for the night. Through the small window over Jake's bed she could see Mae's post office lamp still burning—a gold rectangle on wet walk—and beyond it the dark that led toward Willow Lane where Henry's woodsmoke would be inventing patience and Clara's charcoal would be inventing questions neither of them had answered yet.

[player_name] sat on the edge of the mattress in one of Jake's flannel shirts, cuffs swallowed past her wrists, and watched him pace the narrow strip of floorboards between the dresser and the sink that doubled as a coffee station. His burn scar whitened whenever he gripped the back of the chair. Grey eyes bright. Mouth wrecked from kissing her after the claim and then stopping short of the whole truth because she had asked—quietly, selfishly, lovingly—for a little longer.

"A little longer is not a plan," Jake said. Not cruel. Accurate. "A little longer is how Henry sanded winter into fifteen years. I chose you in front of my own fear. I will not unchoose you. But if we keep the secret warm between us like leftover pie, it will start tasting like the cover story again, and I did not rebuild this diner to live inside another softer lie."

"I know," [player_name] said. Her throat tasted like copper and rain and the particular shame of asking for delay from the man she had once left to protect. "I am not asking for forever silence. I am asking for a pocket of air before Clara's papers become the only narrator of what I did at twenty. Before Henry gets to watch us fracture in his kitchen and call the fracture justice. You chose me. Let me choose the tempo of the telling without turning tempo into another escape ticket."

Jake stopped pacing. Rain found a harder sheet against the glass. Coffee steam ghosted from the mug he had poured and forgotten on the dresser—black, no sugar, the way he drank when the night refused to land soft. Wet boxwood lived in memory at the edge of town. Station platform hiss lived further out. The cracked counter stool leaned its half-degree left downstairs in the dark, listening through floorboards to a negotiation that had nothing to do with eggs and everything to do with whether love could survive a scheduled honesty.

"Then give the pocket edges," he said. "A deadline. Not a fog. One week and we put the whole thing on the table—ice, debt, Voss's shadow, the yes you spoke while Henry's hands shook, the brighter rooms that were never the real reason. Or—" He swallowed. The unfinished almost of his mouth made her ribs answer. "Or you admit you are afraid and you hand me the deadline. You let me decide when the secret stops being mercy and starts being another kind of leaving. I can carry that weight. I have carried worse. What I cannot carry is watching you invent 'a little longer' every morning until Somerton's quiet teaches us both how to sand again."

[player_name] stood. The flannel smelled like him—coffee, clean work-sweat, a trace of woodsmoke from Willow. She crossed the floorboards and put her palm on his chest where his pulse argued with strategy. Fifteen years ago she had believed silence would protect him. Tonight silence was a tool she was asking to borrow for a measured span, and the asking felt like standing on the station platform again with a ticket she might not deserve.

"If I set one week," she said, "I am promising you a date on the calendar when my mouth stops protecting anyone, including myself. Clara hears. Henry faces what he arranged. You get the raw version without me softening the syllables that would destroy a softer man. I am not sure I am brave enough to love you that loudly on a schedule."

"If you hand me the deadline," Jake answered, voice low enough that Market Street would not steal it through rain, "you are trusting me not to use fear as a weapon. You are admitting the secret still scares you more than noon light. That admission is not weakness. It is the first honest sentence we have spoken since you asked for longer. I will not love you less for fear. I will only ask that the fear stop pretending it is strategy."

A freight horn complained toward the yard, ordinary Somerton continuing without permission. [player_name] thought of Clara waking to charcoal under her nails and a house that smelled like unfinished confession. She thought of Henry's glass paperweight and the pages under it that looked like someone had tried to tidy guilt into innocence. She thought of Mae sorting other people's lives into slots and of how quickly a week could become another fifteen years if nobody named the edge.

Jake's hand covered hers on his chest. Thumb at her pulse where it jumped in her wrist. "I chose you," he said again, rough enough to hurt. "That sentence survives spectacle and it survives delay. What it does not survive is delay without a shape. Soft landings are how we got the lie. So pick the shape, [player_name]. Set the week yourself—own the calendar like a woman who came back on purpose—or put the calendar in my hands and admit you are afraid enough to let me hold the match. Both keep me here. Both cost. Standing in this flannel inventing prettier fogs while Willow Lane waits is the only cowardice left upstairs, and you did not buy a ticket for almost."

The flat was small enough that honesty had nowhere to hide. A single bed. A chair with a cracked vinyl seat that matched the diner stool's lean in spirit if not in angle. Clara's early charcoal sketches pinned above the dresser—Somerton roofs, a blue door, a man's hands around a coffee pot—proof that the girl downstairs had been watching long before papers surfaced under glass. [player_name] touched one sketch with a fingertip and felt the grit of old charcoal like a warning.

"I left at twenty believing silence was love," she said. "I came back because Henry's letter refused to say come home and somehow that was worse. If I schedule the telling, I am trying to become someone who does not vanish when the wound opens. If I hand you the schedule, I am admitting I still do not trust my own mouth not to sand the edges when I see your face break."

Jake poured the cold coffee into the sink, rinsed the mug, set it upside down with the care of a man who had rebuilt a life one washed dish at a time. "Either way I am looking at your face when it happens," he said. "That is the point of choosing you. Not spectacle. Not Henry's kitchen as theater. Us, upstairs or down, with a clock that rings whether we are ready or not. Fear gets a seat at the table. Fear does not get to erase the table."

She almost smiled. It hurt. Outside, rain softened for a breath and then returned harder, needle-fine against slate. Somerton's quiet leaned on the glass as if curious whether this particular almost would finally learn how to end. [player_name] thought of the ticket in her bag downstairs, of freight that never quite left the yard, of how a week could be a bridge or a trap depending on who held the planks.

"Promise me you will not use a deadline to punish Henry through me," she said.

"I promise I will use a deadline to stop the quiet from eating what we just chose," Jake said. "Henry can face what he arranged on his own legs. You are not his penance and you are not my instrument. You are the woman in my shirt asking for time with her whole trembling mouth, and I am the man who needs that time to have a shape sharp enough to cut fog."

The radiator clicked. Fryer oil still ticked faintly through the floorboards like a distant metronome. [player_name] tasted the fork bright and dangerous behind her teeth: name seven days, write the disclosure into her own voice like a vow with a date—or open her hands, admit the fear without costume, and let Jake Shaw decide when the quiet finally broke for good. Either exit moved them out of fog. Either exit hurt on purpose.

Jake's thumb stroked once at her wrist—consequence, not comfort. Rain needled the roof. Henry's name sat half-spoken in her mouth beside the secret she was still holding like a live coal. Desire and dread shared a bloodstream. Trust was the real plot, and trust was asking her whether tempo belonged to her fear or to their shared noon. The night above the diner refused to land soft.`,
  textHot: `Jake had chosen her with his mouth still wet from her cunt and his voice still ruined from saying her name like a claim, and [player_name] had accepted the choosing with a yes that left the secret unfinished between their teeth while her thighs were still shaking.

Now the diner's upstairs flat held them like a held breath that smelled like sex and coffee and rain on slate. The blue door stuck two floors below. Through the window Mae's post office lamp threw gold on wet walk. [player_name] sat on the edge of the mattress in his flannel, bare underneath, cunt still aching from his tongue, and watched Jake pace hard—literally hard, cock thick against the soft pants he had pulled on and not bothered to tie, burn scar white, grey eyes bright with the particular fury of a man who had just fucked honesty into a woman and then been asked to wait.

"A little longer is not a plan," he said, stopping in front of her, hands braced on the mattress either side of her hips. "A little longer is how Henry sanded winter into fifteen years. I chose you with my mouth on you and my cock aching to follow. I will not unchoose you. But if we keep the secret warm between us like leftover heat, it will start tasting like the cover story again, and I did not rebuild this diner to come inside another softer lie."

"I know." Her throat worked. Copper. Rain. Shame that still made her wet when he looked at her like that. "I am not asking for forever silence. I am asking for a pocket of air before Clara's papers become the only narrator. Before Henry watches us fracture and calls it justice. You chose me. Let me choose the tempo without turning tempo into another escape."

Jake shoved the flannel open with one hand and cupped her bare breast, thumb rough on her nipple until she gasped. "Then give the pocket edges," he rasped. "A deadline. Not a fog. One week and we put the whole thing on the table—ice, debt, Voss, the yes you spoke at twenty, every syllable that would destroy a softer man." His other hand slid between her thighs, found her still slick, two fingers pressing in slow as punctuation. "Or you admit you are afraid and you hand me the deadline. You let me decide when the secret stops being mercy. I can carry that. What I cannot carry is watching you invent 'a little longer' every morning while I wake up hard for a woman who is still packing silence in her suitcase."

[player_name] tipped her forehead to his. Rain needled the glass. Coffee steam ghosted from the forgotten mug. Wet boxwood waited with Henry's paperweight. Clara's charcoal lived like a dare. Station platform hiss lived only as memory. And here, upstairs above the pie case, Jake fucked her open on his fingers while negotiating calendars, heat advancing the plot instead of decorating it. "If I set one week," she managed, hips rolling, "I am promising you a date when my mouth stops protecting anyone. Clara hears. Henry faces it. You get the raw version."

"If you hand me the deadline," he answered, curling his fingers against the place that whitened her vision, "you are trusting me not to use fear as a weapon. You are admitting the secret still scares you more than noon light." He kissed her hard—coffee-bitter, teeth—then dropped to his knees between her legs as if the argument required a body. "That admission is not weakness. It is the first honest sentence since you asked for longer." His mouth found her cunt again, tongue flat, greedy, and she cried out into the flannel collar while Market Street pretended it slept.

A freight horn complained toward the yard. [player_name] tangled her hands in his hair and tried to think through the throb. Mae's gold light. Henry's sanded mercy. Clara waking to fear dressed as patience. A week that could become fifteen years if nobody named the edge. The cracked stool leaned downstairs in the dark. Jake sucked her clit with intent that felt like a verdict and pulled off just long enough to speak against her wet heat: "I chose you. That sentence survives spectacle and delay. What it does not survive is delay without a shape. Soft landings are how we got the lie. So pick. Set the week yourself—own the calendar while I fuck the fear out of your voice—or put the calendar in my hands and admit you are afraid enough to let me hold the match. Both keep me here. Both cost. Standing upstairs inventing prettier fogs while your cunt drips on my tongue is the only almost left, and you did not buy a ticket for almost."

He stood, shoved the soft pants down, and the thick line of his cock sprang free—flushed, wet at the tip, earnest as rain. [player_name] reached for him without deciding yet, stroked once, felt him jerk in her fist. "Clara will hate whichever clock we pick if she feels excluded," she whispered.

"Clara hates secrets more than clocks." Jake caught her wrist, sticky from her own slick, and pinned it beside her hip as he nudged her thighs wider. "She can survive a week if the week is named." He pushed into her in one slow, filthy glide—cock stretching, filling, claiming the delay as something that still had a body—and held deep while she shook. "She cannot survive watching us smile through fryer steam while Henry sands another morning and I pretend I am not waking up buried in you and still hungry for the truth."

He fucked her in measured strokes that matched rain on slate—not rushed, not gentle, each thrust a question with weight. Coffee went cold. The radiator clicked. Clara's early charcoal sketches watched from above the dresser while Jake held himself still inside [player_name], jaw tight, denying the finish they both wanted until the calendar had a shape. She clenched around him on purpose—cruel mercy returned—and he cursed softly into her hair, cock twitching, hips stuttering once before he locked them down again.

"I left at twenty believing silence was love," she gasped. "If I schedule the telling, I am trying not to vanish when your face breaks. If I hand you the schedule, I am admitting I still do not trust my own mouth not to sand when I see you hurt—and I am asking you to fuck the trust into me anyway."

"Either way I am looking at your face when it happens," he rasped, grinding deep enough that her vision went white at the edges. "That is the point of choosing you. Not Henry's kitchen as theater. Us. A clock that rings. Fear gets a seat. Fear does not get to erase the table or my cock or the way you drip when I say deadline like a filthy word."

Rain needled slate. Mae's gold light held. [player_name] raked her nails down his back and felt him shudder. Somerton's quiet leaned on the glass. A week could be a bridge or a trap. She thought of the ticket in her bag, of freight that never left, of Henry's woodsmoke inventing morning, and of how Jake's burn scar whitened whenever he chose not to come yet because the plot still needed her voice.

"Promise you will not use a deadline to punish Henry through me," she whispered against his mouth.

"I promise I will use it to stop the quiet from eating what we just chose," he said, and kissed her like a seal and a threat. "You are not his penance. You are not my instrument. You are the woman clenching around my cock asking for time with her whole trembling cunt, and I am the man who needs that time sharp enough to cut fog before I let either of us finish." He ground deep and stilled, throbbing, denying them both on purpose. Fryer oil ticked faintly through the floorboards. Coffee steam ghosted from the vent downstairs. "Choose while I can still feel you clench around me like a vow. Soft landings are how we got fifteen years of almost. Your week with your mouth owning the calendar—or my hands on the deadline while your cunt tells the truth your fear keeps sanding. Both keep me buried here. Both move us. Fog is the only exit I will not fuck you through."

Outside, freight complained. Inside her ribs, want and dread shared a bloodstream. Henry's name sat half-spoken beside the secret. Jake's mouth found hers, unfinished, waiting. Her nipples ached. Her cunt fluttered around the thick still length of him. Mae's window light held steady across the wet walk. Willow Lane waited with woodsmoke and an uncle running out of silence.

[player_name] drew a breath that tasted like rain and coffee and Jake and the particular courage of women who had once said yes for love and were learning how to schedule the breaking. His cock twitched inside her. The deadline waited unnamed. The night above the diner refused to land soft.`,
  choices: [
    { id: "scene8j", text: "Set a deadline: one week, then full disclosure", textHot: "Set the week yourself — own the calendar with him still inside" },
    { id: "scene8c", text: "Admit you're afraid and ask Jake to decide the deadline", textHot: "Admit the fear — put the deadline in his hands while you shake" }
  ]
};
