export default {
  id: "scene2b",
  layer: 2,
  title: "Willow Lane",
  art: "/art/until-the-quiet-breaks/scene2b.png",
  text: `Willow Lane smelled of wet boxwood and woodsmoke. The rain had softened the road into a dark ribbon; slate roofs dripped in slow, patient rhythms; and the Shaw house sat back from the street the way it always had—eaves heavy, porch boards dark, windows holding a low amber that looked like someone had been expecting company without admitting it. [player_name] climbed the steps with Henry's letter a damp weight in her pocket, suitcase bumping her calf, the station's hiss still faintly in her ears as if Somerton had followed her up the hill. She had not knocked yet when the door opened.

Henry stood in the frame as if he had been listening for her step since the envelope left his desk. Older. Thinner through the face, the skin at his temples mapped with fine lines that weather and worry had drawn together. Grey hair combed with the same careful discipline he brought to every secret. The same eyes that could hold a truth without blinking, and had done so for fifteen years.

"You came," he said—not surprise, not triumph. Something quieter, almost relieved to be caught. He stepped aside. Warm air met her: wood heat, old books, the faint lemon of polish applied to furniture that had outlived more honest conversations.

Inside, the front room held the tick of a mantel clock and a fire that had been fed recently enough to speak of nerves. A single photograph of John as a boy rested among newer frames: elbows on the diner counter, grin half-hidden, grey eyes already learning stillness. Beside it, a sketch of the same diner in charcoal—Clara's hand, sure and restless, the blue door suggested with a few hard strokes that somehow captured how it stuck. Papers were stacked under a glass paperweight like evidence someone had tried to tidy into innocence. A corner of a ledger peeked out. A date written in pencil. The ghost of charcoal on the edge of a bank statement.

"Sit," Henry said. "Or don't. I have rehearsed this conversation long enough to know rehearsal does not help."

[player_name] remained standing. Rain ticked against the windows. She set her suitcase down but kept her coat on, as if readiness were a kind of armor. "Your letter did not say the thing. It only opened a door. Weather. The diner. Clara's sketches. And a silence large enough to walk into. I walked. Now say what you meant."

Henry's mouth twitched—almost a smile, almost a flinch. He moved to the mantel and rested his fingertips on the paperweight without lifting it. "Clara found what I hid. She is John's sister in every way that matters—stubborn, loyal, allergic to unfinished stories. She was looking for scrap paper for her charcoal and found my desk instead. Dates in the corners of her own old schoolbooks, names she did not recognize at first, a winter that did not match the story we told her brother when he was still half a boy. She brought the whole mess into this room and laid it on that table as if she were serving tea. She asked why your name disappeared from Somerton the same season her father died, and why the answers she had been given sounded like wallpaper over a crack." He rubbed his thumb along the glass. "I wrote you because the quiet is breaking whether I consent or not. I thought you should know before Somerton invents a louder version—and before John invents one that ruins him."

"What version did you invent the first time?" Her voice stayed even. Fifteen years of practice. The letter crackled faintly when she shifted her weight; she did not take it out. She did not need the pages. She needed his mouth to finally do the work his handwriting had refused.

Henry looked at the photograph of John. The fire popped. Outside, boxwood dripped onto the porch boards in a soft, relentless applause. "His father died in that winter accident. You know that. What you were asked to carry—what I asked you to carry—was a cleaner shape of the mess underneath: debts that had climbed higher than anyone in this house would admit, a promise I made to keep the diner and the family solvent and then failed, a night that would have wrecked the boy if he had seen it whole. There were choices made in panic. There was money owed to people who did not wait politely. There was a road, and ice, and a father who should not have been driving with that weight on him. You were there for parts of it. You saw enough. I told you silence would protect John. You left. We told him you wanted more than Somerton—a bigger life, brighter rooms, a map that did not end at Market Street. It was almost true. It was also a kindness that calcified into a lie."

Rain sheeted the windows harder, turning the yard into a blur of dark green and slate. From the kitchen came the soft scrape of a chair—Clara, perhaps, close enough to hear, far enough to pretend she was not. A cupboard door clicked. Charcoal, [player_name] thought absurdly: the girl would have smudges on her fingers even now, as if drawing were how she metabolized the truth.

Henry glanced toward that sound and lowered his voice. "She will come in if we pretend she cannot hear. She has earned that. She found the papers. She forced my hand. Without her, I might have kept rehearsing until I died of carefulness."

"John is at the diner," Henry continued, turning back. "He does not know I mailed the letter, not for certain, though he suspects. He has always suspected something did not fit—your face on the station steps, my hand on your shoulder, the way the town's story never matched the weather in his chest. You can press me for every ugly line now. Every name. Every debt. Every hour of that winter I have spent trying to forget while polishing the furniture. Or you can go to him first and let him decide how much of my voice he wants in the room when the truth arrives. I will not stop you either way. That is part of what I owe."

[player_name] felt the old pull—the desire to finish what Henry started, to pin the secret to the mantel like another photograph, and the stronger desire to see John's face before another man narrated her life for her. The blue door on Market Street rose in her mind: sticking, faithful, unwilling to swing easy. Coffee steam. The cracked stool. Grey eyes that had practiced holding weather. She had come to Willow first because Henry's letter had been a summons disguised as courtesy, and because some part of her still believed the keeper of the lie should be the first to open it. Standing here, woodsmoke in her lungs, she was less sure.

Henry's hand hovered near her sleeve and did not quite touch, the same almost-gesture from years ago when he had asked her to leave for John's sake and called it love. "Some silences are kinder broken. I am learning that late. Clara will not forgive a half-measure. Neither should you."

He moved along the mantel and touched the frame of John's boyhood photograph as if checking that the glass still held. "He looks like his father when he is angry," Henry said softly. "He looks like me when he is kind. I have used both against him without meaning to—the father's temper as a warning, my own caution as a cage. I told myself I was sparing him. What I spared him was the chance to forgive us properly." He glanced again toward the kitchen, where Clara's chair had gone quiet in the particular way of someone listening with her whole body. "She sketched the night differently in the margins. Not the facts—she did not have all of those—but the feeling. Rain. A car. Your silhouette on the station steps. John waiting. Me standing between. She drew the gap before she found the papers that named it."

[player_name] felt fifteen years of practiced silence try to climb her throat and stop her questions. She swallowed it down. The house creaked in the rain the way old houses confess—slowly, in joints, whether anyone asks or not. A log settled in the grate. The clock ticked through another minute of courage deferred. Outside, Willow Lane shone black. Toward town, through the wet dark, a faint square of amber might have been the diner's window, John moving through his evening unaware that the letter had finally grown legs and climbed his uncle's porch.

She walked to the table and looked at the papers under glass without lifting the weight. Dates. A name she remembered from that winter. Clara's charcoal along one edge, a quick study of hands—Henry's hands, perhaps, or her father's, or John's—fingers open as if dropping something too heavy to hold. "You asked me to leave so he would not have to see the whole of it," she said. "I did. I practiced being the girl who wanted more until the practice became a life. Now Clara has made practice impossible. So have you, by writing."

Henry's smile was tired and almost proud. "Then choose which room you enter first—the one with my answers, or the one with his face. If you press me now, I will not tidy. I will give you the debts, the failed promise, the cover we built around your leaving, and the reason I thought casting you as ambition was gentler than casting you as witness. If you leave for the diner, I will still be here when you return. That is the least of what I owe. Tell John I am done rehearsing, if you get there before I do."

From the kitchen, soft footsteps. Clara did not appear in the doorway, but her presence pressed against the air like a held breath. The paperweight caught the firelight. Rain found every seam of the eaves. [player_name] touched the letter through her coat one last time and felt the fork settle again—not at the station this time, but here, in the house where the quiet had been built and where it was finally, irrevocably, beginning to break.

"I am not here to absolve you," she said. "I am here because you opened a door and then stood behind it. If I stay, you finish. If I go to John, you wait—and you do not call the diner to warn him into another careful face."

Henry inclined his head. The mantel clock struck a shallow hour. Woodsmoke curled. Wet boxwood breathed through the door he had not fully closed. "Choose," he said. "I have taken enough of your choosing already."`,
  textHot: `Willow Lane hit [player_name]'s body before it hit her mind—wet boxwood, woodsmoke, rain needling the open collar of her coat—and underneath the weather a second weather she had carried from the station: John Shaw's name pulsing low between her thighs like a bruise she pressed when she needed to feel alive.

The road was a dark ribbon. Slate roofs dripped. The Shaw house sat back with eaves heavy and windows holding low amber, expecting company without admitting it. She climbed the steps with Henry's letter a damp weight against her breastbone, suitcase bumping her calf, station hiss still in her ears. Rain soaked through coat to blouse; fabric clung to her breasts and the line of her waist. She was absurdly aware of her own skin even here—on Henry's porch, about to open a wound—because Somerton still smelled like the man she had almost fucked behind a diner fifteen winters ago and never stopped wanting. She had not knocked when the door opened.

Henry stood in the frame as if he had been listening since the envelope left his desk. Older. Thinner through the face. Grey hair combed with the discipline he brought to every secret. Eyes that could hold a truth without blinking. Looking at him, she felt no heat—only the old gravity of the man who had asked her to leave. The heat lived elsewhere: Market Street, a blue door that stuck, a mouth she had almost claimed, a cock she had felt hard against her hip through denim and never taken into her body because silence got there first.

"You came," he said—not surprise, not triumph. Something quieter, almost relieved to be caught. He stepped aside. Warm air met her: wood heat, old books, lemon polish on furniture that had outlived honest conversations. She stepped in dripping. Warmth found the cold places rain had claimed, and for a treacherous second she wished it were John's hands doing the warming—palms rough, mouth at her throat, undressing the journey off her before any uncle got to speak.

The front room held a mantel clock's tick and a fire fed recently enough to speak of nerves. A photograph of John as a boy rested among newer frames: elbows on the diner counter, grin half-hidden, grey eyes already learning stillness. The sight of him—even young, even framed—pulled a low private heat through her. She remembered the grown man he had become in her imagination on nights when loneliness made her reckless with her own hands, fingers slick between her legs while she pictured his work-rough palms, his burn-scarred thumb, his cock pushing into her cunt until the cover story broke. She woke ashamed and unfinished. The unfinished had followed her up Willow Lane like a second suitcase.

Beside the photo, Clara's charcoal sketch of the diner—blue door suggested in a few hard strokes that somehow captured how it stuck. Papers stacked under a glass paperweight like evidence tidied into innocence. A ledger corner. A pencil date. Charcoal ghosting the edge of a bank statement.

"Sit," Henry said. "Or don't. I have rehearsed this conversation long enough to know rehearsal does not help."

[player_name] remained standing. Rain ticked the windows. She set her suitcase down but kept her coat on—armor, and a way to hide how her body still leaned traitorously toward Market Street and the man she had not touched in fifteen years. Under wool her skin felt too awake: damp blouse chafe, wet seams, a pulse in her cunt that had nothing to do with Henry and everything to do with the boy in the photograph grown into a man who still owned a corner of her wanting. "Your letter did not say the thing. It only opened a door. Weather. The diner. Clara's sketches. A silence large enough to walk into. I walked. Now say what you meant."

Henry's mouth twitched—almost smile, almost flinch. He rested fingertips on the paperweight without lifting it. "Clara found what I hid. She is John's sister in every way that matters—stubborn, loyal, allergic to unfinished stories. She was looking for scrap paper for her charcoal and found my desk instead. Dates in old schoolbooks, names she did not recognize, a winter that did not match the story we told her brother when he was still half a boy. She laid the mess on that table as if serving tea. She asked why your name disappeared from Somerton the same season her father died, and why the answers sounded like wallpaper over a crack." He rubbed his thumb along the glass. "I wrote you because the quiet is breaking whether I consent or not. I thought you should know before Somerton invents a louder version—and before John invents one that ruins him."

"What version did you invent the first time?" Her voice stayed even. Fifteen years of practice. The letter crackled when she shifted; wet fabric whispered against her thighs. She did not take the pages out. She needed his mouth to finally do the work his handwriting had refused—while her own mouth privately remembered a different Shaw entirely: John behind the diner, hands sliding under her sweater, gasping into his neck, his thigh pressing up until she rocked against him shameless, almost coming from friction and fear, Henry's careful plan already waiting in the dark like a knife between their hips.

Henry looked at the photograph. The fire popped. Boxwood dripped onto porch boards in soft relentless applause. "His father died in that winter accident. You know that. What I asked you to carry was a cleaner shape of the mess underneath: debts higher than this house would admit, a promise I made to keep the diner and the family solvent and then failed, a night that would have wrecked the boy if he had seen it whole. Choices made in panic. Money owed to people who did not wait politely. A road, ice, a father who should not have been driving with that weight. You were there for parts of it. You saw enough. I told you silence would protect John. You left."

His gaze flicked to her, then away. "We told him you wanted more than Somerton—a bigger life, brighter rooms, a map that did not end at Market Street. It was almost true. It was also a kindness that calcified into a lie."

And she thought, bitter and aroused in the same breath: I wanted John. I wanted his mouth and his future and the unfinished heat of him. I wanted to fuck him honest and stay. You called that a bigger life so he would not know I was witness and sacrifice both—so my cunt and my conscience would leave town together and call it ambition.

Rain sheeted the windows, yard into blur of dark green and slate. From the kitchen came the soft scrape of a chair—Clara, close enough to hear, far enough to pretend. A cupboard clicked. Charcoal, [player_name] thought: the girl would have smudges on her fingers even now, metabolizing truth through drawing. [player_name] kept her coat closed. Under it her body hummed with leftover station longing—John's name like a bruise, John's imagined mouth on her breast, John's cock a private ache while Henry polished guilt into sentences.

Henry glanced toward the kitchen sound and lowered his voice. "She will come in if we pretend she cannot hear. She has earned that. She found the papers. She forced my hand. Without her, I might have kept rehearsing until I died of carefulness."

"John is at the diner," he continued, turning back. "He does not know I mailed the letter, not for certain, though he suspects. He has always suspected something did not fit—your face on the station steps, my hand on your shoulder, the way the town's story never matched the weather in his chest."

At John's name, heat licked through her again: the imagined press of him against the cracked stool, how he might look if she walked through the blue door soaked and furious and wanting, how he might lock it and put his hands under her wet clothes before any uncle finished narrating. How he might say fuck Henry's careful face and then fuck her until the secret had to share the room with pleasure.

"You can press me for every ugly line now," Henry said. "Every name. Every debt. Every hour of that winter I have spent trying to forget while polishing the furniture. Or you can go to him first and let him decide how much of my voice he wants in the room when the truth arrives. I will not stop you either way. That is part of what I owe."

[player_name] felt the old pull—finish what Henry started, pin the secret to the mantel—and the stronger pull to see John's face before another man narrated her life. Desire of two kinds: for truth, and for him. The blue door rose in her mind: sticking, faithful. Coffee steam. Cracked stool. Grey eyes holding weather. Work-rough hands she had once guided to her waist, to the soft skin under her shirt, to the soaked place between her legs where almost became a moan she still heard on lonely nights when her own fingers were a poor substitute for John Shaw's cock. She had come to Willow first because the letter was a summons disguised as courtesy, because some part of her still believed the keeper of the lie should open it first. Standing here, woodsmoke in her lungs, thighs damp from rain and memory, cunt aching with a vote that had nothing to do with paperweights, she was less sure. Her body voted for the diner. Her conscience voted for the mantel. Both votes burned.

Henry's hand hovered near her sleeve and did not quite touch—the same almost-gesture from years ago when he had asked her to leave for John's sake and called it love. The near-touch made her flinch—not with attraction, with recognition of how carefully he had redirected her hunger into exile. He had stolen more than a witness. He had stolen the night she might have stayed and let John finish what they started, might have woken in a bed above Market Street instead of a life practiced into hollowness.

"Some silences are kinder broken," Henry said. "I am learning that late. Clara will not forgive a half-measure. Neither should you."

He touched the frame of John's boyhood photograph. "He looks like his father when he is angry. He looks like me when he is kind. I have used both against him without meaning to—the father's temper as warning, my own caution as cage. I told myself I was sparing him. What I spared him was the chance to forgive us properly." He glanced toward the kitchen, where Clara's chair had gone quiet in the way of someone listening with her whole body. "She sketched the night differently in the margins. Not the facts—she did not have all of those—but the feeling. Rain. A car. Your silhouette on the station steps. John waiting. Me standing between. She drew the gap before she found the papers that named it."

[player_name] looked at the photograph and felt fifteen years of practiced silence try to climb her throat—and underneath it, the hotter silence of nights she had spent imagining John's mouth on hers, his weight, his cock sinking into her cunt until unfinished almost became finished in a bed that was never this house and never far from it. She swallowed both down. The house creaked in the rain the way old houses confess—slowly, in joints. A log settled. The clock ticked through another minute of courage deferred. Outside, Willow Lane shone black. Toward town, through the wet dark, a faint square of amber might have been the diner's window—John moving through his evening unaware that the letter had grown legs and climbed his uncle's porch, unaware that she stood here wet and wanting and furious, body remembering him while her mind braced for Henry's truth, nipples tight under damp cloth from memory alone.

She walked to the table and looked at the papers under glass without lifting the weight. Dates. A name from that winter. Clara's charcoal along one edge—a quick study of hands open as if dropping something too heavy. She thought of John's hands specifically: burn scar, flour dust, the way they had trembled once against her ribs, the way they might tremble now if she put them between her legs and said the silence is done, touch me like you mean the truth. "You asked me to leave so he would not have to see the whole of it," she said. "I did. I practiced being the girl who wanted more until the practice became a life." Wanted more—cities, rooms, maps—when what she had wanted was him, naked of story, honest in the dark, fucking her through the fear instead of sending her away with a kinder lie. "Now Clara has made practice impossible. So have you, by writing."

Henry's smile was tired and almost proud. "Then choose which room you enter first—the one with my answers, or the one with his face. If you press me now, I will not tidy. I will give you the debts, the failed promise, the cover we built around your leaving, and the reason I thought casting you as ambition was gentler than casting you as witness. If you leave for the diner, I will still be here when you return. That is the least of what I owe. Tell John I am done rehearsing, if you get there before I do."

From the kitchen, soft footsteps. Clara did not appear, but her presence pressed the air like a held breath. The paperweight caught firelight. Rain found every seam of the eaves. [player_name] touched the letter through her coat—fingers brushing her own breastbone, an accidental intimacy that made her think of John's mouth there, sucking, claiming, undoing Henry's careful exile with heat—and felt the fork settle again: not at the station this time, but here, in the house where the quiet had been built and where it was finally, irrevocably, beginning to break. Desire for truth and desire for John braided so tight she could not tell which pulse was which. Both would have to be answered. She only had to choose which door first—and her cunt already knew which walk would leave her shaking.

"I am not here to absolve you," she said. "I am here because you opened a door and then stood behind it. If I stay, you finish. If I go to John—" she let his name land with the heat it carried, felt it in her throat and lower "—you wait, and you do not call the diner to warn him into another careful face. He deserves my mouth telling him the truth before you sand it soft again." She heard her own phrasing—my mouth—and did not correct it. Let Henry hear the subtext: mouth for confession, mouth for John, mouth that had been silenced and was done. Henry's eyes flickered; he understood more than she had said.

Henry inclined his head. The mantel clock struck a shallow hour. Woodsmoke curled. Wet boxwood breathed through the door he had not fully closed. Somewhere under her coat, her body still leaned toward Market Street—toward coffee and scarred hands and the unfinished hunger of a woman who had been asked to leave and had come back wet, adult, and done pretending she only wanted answers. She wanted John's cock and Clara's papers and Henry's ugly lines in the same night if the night would hold.

"Choose," Henry said. "I have taken enough of your choosing already."`,
  choices: [
    { id: "scene3c", text: "Press Henry for the whole truth now", textHot: "Press Henry for every ugly line now — before John's pull makes your body soft" },
    { id: "scene3d", text: "Leave for the diner — hear John's side before Henry finishes", textHot: "Leave for the diner — go to John wet and unfinished before Henry sands the truth" }
  ]
};
