export default {
  id: "scene6h",
  layer: 6,
  title: "Market Street Threat",
  text: `Market Street after the threat still smelled like fryer oil and wet slate, as if Somerton had not yet decided whether to take her seriously.

[player_name] walked the cracked sidewalk with Jake half a pace behind her left shoulder, not leading, not hanging back—close enough that his coat brushed hers when the wind funneled between the diner's blue door and the hardware awning that had outlived three owners and one winter nobody named. Rain needled the gutters. Coffee steam ghosted from the diner's vent even though the CLOSED sign still hung crooked; Jake had restarted the pot before they left Willow Lane because empty hands invited trembling, and trembling invited Henry's sanded mercy to invent a softer morning than the one she had just threatened into existence.

She had said it in Henry's kitchen with woodsmoke in her lungs and Clara's charcoal circles still living upstairs like a second conscience: that she would tell the Market Street regulars everything. The ice. The cover. The debt that had worn Voss's shadow. The girl cast as ambition so the Shaw name could keep its polite edges. Henry's face had gone the color of old paper under the glass weight. Jake had not flinched. He had only looked at her the way a man looks at a fuse already lit and decides, without romance, to stand in the same room as the burn.

Now the fuse was Market Street itself.

Mae's post office waited two storefronts past the pie case, its small window lit even at this grey hour—Mae sorted mail before the town finished pretending it slept, stamped other people's lives into slots, and remembered who had written whom with an accuracy that made confession feel almost redundant. [player_name] could see the gold lettering on the glass from here: POST OFFICE, slightly fogged, a lamp behind it throwing a rectangle onto the wet walk like an invitation or a trap. Beside her, Jake's burn scar went white at the thumb where he worried the seam of his pocket.

"You do not have to say it to Mae to make Henry believe you meant it," Jake said, voice low enough that the street would not steal it. Grey eyes bright. Coffee on his breath. "Threats work because the person threatened imagines the telling. You already put the imagination in his kitchen. You can stop here and turn the blade inward—Henry only, family shaped, no Mae, no eggs-and-gossip chorus. Or you can walk into that light and make the quiet learn it has neighbors who will not sand what they hear."

[player_name] tasted copper and rain and the metallic bright of a choice that would not stay private either way. Fifteen years ago she had left this street believing silence would protect him. Now silence was the thing that needed killing, and the question was how public the knife should be. The cracked counter stool leaned its half-degree left behind the diner glass, listening through rain. Wet boxwood lived back on Willow with Henry's unfinished word still hanging over the grate. Clara would wake soon to charcoal under her nails and a house that smelled like fear trying to dress as patience.

A freight horn complained toward the yard, ordinary Somerton continuing without permission. Regulars would start arriving within the hour—men who still called her the girl who wanted more, women who had practiced believing the cleaner story until practice nearly became civic virtue. Mae would know first if [player_name] chose the window light. Mae always knew first. That was the point of a post office in a town that mailed its shame in envelopes and called the stamps mercy.

Jake stopped her under the hardware awning with a hand at her elbow—not gripping, asking. Rain sheeted past them into the gutter. His coat smelled like coffee and clean work-sweat and the woodsmoke they had carried out of Henry's doorway like a second skin. "If you tell Mae," he said carefully, "you are not only telling Mae. You are telling the town through the person who sorts its paper. Clara will hear it before noon. The diner will fill with eyes. I will stand with you. I will not sand what you say. But I need you to know the cost is not abstract. It is eggs gone cold while someone asks whether my father died on ice or on a lie. It is Henry's name spoken like a verdict in rooms that used to pour him free coffee."

"I know the cost," [player_name] said. Her throat worked around burnt roast and old coins. "I paid a different cost for fifteen years. Brighter rooms. Longer maps. A story that cast leaving as hunger instead of a yes spoken at twenty while fear shook in Henry's hands around whiskey he claimed was tea. If I stop at Henry alone, I keep the town's practiced belief intact while I break only the man who arranged the cover. That may be justice. It may also be another quieter kind of protection—me deciding again what Jake Shaw can survive hearing in public."

Jake's mouth tilted, wrecked and almost smiling. "Do not protect me with my own surname. I rebuilt a diner around a wound and called it maturity. I raised Clara beside fluorescent lights and fryer hymn. I can survive Mae. What I cannot survive is watching you invent a softer blade because you still think my love is fragile enough to shatter on gossip."

The unfinished almost of his mouth lived at the edge of her attention like a second conversation. Rain found a harder sheet against the awning. Across the street, the post office lamp threw its rectangle brighter as someone—Mae, surely—moved behind the glass, a silhouette sorting early. [player_name]'s pulse hammered once, hard. She could walk into that light and put the whole truth into Mae's tidy stamps: winter, creditor, cover, the girl who left so the Shaw quiet could keep breathing. Or she could turn back toward Willow Lane and use the threat only on Henry—withdraw the public bluff, keep the reckoning family-shaped, make him unsand winter without feeding Market Street a story it would chew into entertainment before noon.

Jake's hand slid from her elbow to her wrist, thumb finding the place where her pulse argued with strategy. "Either way moves us," he murmured. "Tell Mae and own the town's noise as the price of ending the quiet—or pull the bluff back and put every ounce of that threat on Henry's throat alone before Clara comes downstairs and finds us negotiating her childhood in the rain. Both hurt. Both keep me here. Standing under this awning inventing prettier reasons while Mae's window waits is the only cowardice left on Market Street, and you did not buy a ticket for almost."

[player_name] looked past him at the blue door that stuck, at the CLOSED sign, at the pie case humming its cheap hymn behind rain-streaked glass. She looked at Mae's gold lettering fogging and clearing with each breath of warm air from inside the post office. She thought of Henry's paperweight and the pages under it that looked like someone had tried to tidy guilt into innocence. She thought of Clara's restless honesty and Voss's shadow and the way Jake's burn scar whitened whenever he gripped anything that mattered.

"If I walk in there," she said, "I am not performing penance for Mae. I am refusing to let Henry be the only audience for a truth that damaged a whole town's memory of what winter cost. If I do not walk in—if I take this back to Willow and use the threat only on him—I am choosing family fracture over civic theater, and I need you to want that for reasons that are not fear of eggs gone cold."

"I want whatever keeps you from leaving again with a prettier lie in your suitcase," Jake said, rough enough that her ribs answered. "Mae or Henry. Public knife or private. I will not love you less for the cut you choose. I will only ask that you choose while I can still feel your pulse under my thumb and not invent your decision in the shower later like a man rewriting grief into romance."

Rain needled the slate roofs. Station platform hiss lived only as memory at the edge of town. Coffee steam ghosted. The cracked stool leaned. Wet boxwood waited. Woodsmoke would already be inventing Henry's next soft sentence if they gave him time. [player_name] tasted the fork bright and dangerous behind her teeth: follow through into Mae's window light and let the post office become the first honest mailing Somerton had received in fifteen years—or withdraw the Market Street bluff, keep the blade for Henry alone, and walk back into woodsmoke with Jake's hand still on her wrist like a vow that had not found its full sentence yet.

Outside the awning, a delivery truck hissed past toward the freight yard, ordinary as ever. Inside the post office, Mae's silhouette paused at the glass as if she had felt eyes on the lettering. Jake's thumb stroked once at [player_name]'s pulse—consequence, not comfort. Henry's name sat half-spoken in her mouth, a syllable she could still swallow or spit into Mae's waiting stamps. The quiet of Somerton leaned in at the gutter's edge to hear which hunger she would feed first—the town's appetite for a true story, or the family's need to break without an audience.

Mae's window light held steady. Henry's name trembled unfinished on her tongue. Jake's hand stayed on her wrist, warm through rain-damp sleeve, refusing to steer, refusing to leave, waiting for the cut that would make Market Street either a witness or a rumor left unfed.

[player_name] drew a breath that tasted like rain and old coins and coffee and the particular courage of women who had once said yes for love and were learning, too late and exactly on time, how to say something sharper. The choice sat bright behind her teeth. The morning refused to land soft.`,
  textHot: `Market Street after the threat still smelled like fryer oil and wet slate, and [player_name]'s body still hummed from Henry's kitchen as if wanting had hitched a ride in the passenger seat beside the fuse she had lit.

She had said it with woodsmoke in her lungs and Jake's thigh pressed to hers under the table—that she would tell the Market Street regulars everything. Ice. Cover. Voss. The girl cast as ambition. Henry had gone paper-pale. Jake had gone hard against denim at the wrong confession again, debt and desire sharing a bloodstream, and now they stood under the hardware awning with rain needling the gutter and Mae's post office lamp throwing a gold rectangle onto the wet walk two storefronts past the diner's blue door. [player_name]'s bra seam rubbed when she breathed too deep. Her cunt still ached with the unfinished heat of a morning that had braided creditor ghosts to public knives and refused to untangle them for anyone's politeness, including her own.

Jake crowded her back against the brick between the awning posts—not hiding them, claiming the strip of dry as if Market Street owed them one honest inch. Coat open. Chest to her chest. Already half-hard from proximity and danger and the simple fact of her walking toward a wound with both hands. "You do not have to say it to Mae to make Henry believe you meant it," he said into her hair, and his hand slid under her sweater at the same time, palm flat on her stomach, contradicting every soft off-ramp with skin. "Threats work on imagination. You already put the imagination in his kitchen. You can stop here and turn the blade inward—Henry only—or you can walk into that light and make the quiet learn it has neighbors while I keep my hand where it is until you decide."

[player_name] tasted copper and rain and the metallic bright of a choice that had a body. Fifteen years of brighter rooms had not taught her how to negotiate justice with Jake Shaw's cock pressed thick against her hip and Mae's silhouette moving behind fogged gold lettering. "If I tell Mae," she managed, voice steadier than the clench of her thighs, "I am not only telling Mae. I am telling the town through the woman who sorts its paper. Clara hears before noon. The diner fills with eyes. Eggs go cold while someone asks whether your father died on ice or on a lie."

"I know." Jake's mouth found the side of her neck—open, hot—and sucked hard enough to mark while rain sheeted past them into the gutter. His free hand spanned her ribs, thumb brushing the underside of her breast through the bra until her nipple peaked against lace like it had opinions about civic virtue. "I rebuilt that diner around a wound. I can survive Mae. What I cannot survive is watching you invent a softer blade because you still think my cock and my name are too fragile for gossip in the same hour."

She laughed once, wrecked, and the sound fogged between their mouths. Coffee on his breath. Clean work-sweat. Woodsmoke still clinging to both of them like a second skin carried out of Willow Lane. The cracked counter stool leaned its half-degree left behind the diner glass, listening through rain. Fryer oil ticked in the cooling vat. Wet boxwood waited back with Henry's unfinished word. Clara's charcoal lived upstairs like a dare. And here, under the awning, Jake shoved past her waistband and the cotton already betraying her—damp, humiliating, honest—two fingers finding her cunt with accuracy that had nothing to do with post office hours and everything to do with a man who refused to let fear go celibate.

"Jake—" Not a stop. A warning aimed at the street.

"Then decide with my fingers in you," he rasped, slow stroke through slick, not fucking her open yet, just proving the negotiation had a body and the body was already past pretending. "Follow through. Walk into Mae's light and put the whole truth in her stamps—winter, creditor, cover, the yes you spoke at twenty—while your pulse is still on my hand. Or withdraw the bluff. Use the threat only on Henry. Walk us back to woodsmoke and make him unsand winter without feeding Market Street a story it will chew into entertainment before I get you upstairs above the pie case." His cock pressed a thick line against her belly; he rolled once, helpless, and held still, breathing hard enough that she felt it in her teeth. "Both are honest. Both keep me hard enough to hurt. Standing here inventing prettier reasons while Mae sorts mail is the only lie left, and I am done swallowing lies with my coffee."

[player_name] bit her lip to keep the sound off the street. A delivery truck hissed past toward the freight yard. Mae's silhouette paused at the glass as if she had felt eyes on the lettering. Jake's fingers pressed exactly on the syllable of her swallowed moan like punctuation with intent. Her hips jerked. He held her upright with the arm across her ribs, apron strings still half-tied under his coat from a morning that had refused sleep, burn scar white where his thumb worried her waistband.

"I am not performing penance with your hand in my jeans," she whispered, turning her face enough that her lip brushed his. "I am deciding whether the town gets to hear what Henry bought with my leaving—or whether Henry alone gets the blade while I still have the taste of you on my mouth. If you stop touching me I will walk into that post office shaking for the wrong reasons and hate us both by noon."

"Then I will not stop." He kissed her once—hard, coffee-bitter, teeth scraping—then tore back so she could still see Mae's window light over his shoulder. His thumb found her clit again, a brand. He curled his fingers inside her—thick, sure, crooking against the place that whitened the edges of the awning's shadow—and the heel of his palm ground slow while rain needled slate and the quiet of Somerton leaned in at the gutter to listen. "Pick. Tell Mae—own the town's noise as the cost of ending the quiet, walk in there wet for me and speak anyway—or pull the bluff back and put every ounce of that threat on Henry's throat alone before Clara comes downstairs. Before I fuck you against this brick with a post office lamp for a witness. Before Henry invents morning with sanded mercy and we lose the hour when your cunt and your courage are still answering the same question."

She could have come from the sentence alone. Instead she fought it, thighs shaking, because coming under Mae's window light felt like letting the town into the room before she had chosen what the town was allowed to know. Jake felt the fight and eased—cruel mercy—fingers still buried, strokes gentled to a throb that matched the rain. "Good," he murmured against her temple. "Hold it. Use it. Anger and want in the same fist. That is how we survive Market Street without becoming Henry."

Coffee steam ghosted from the diner vent. The blue door stuck like a promise that needed force. POST OFFICE glowed gold and fogged. [player_name] thought of Mae's tidy stamps and untidy curiosity, of regulars who had practiced believing she wanted more, of Henry's paperweight and pages that tried to tidy guilt into innocence, of Clara waking to a house that smelled like fear dressed as patience. She thought of Jake's cock twitching against her and refused to let wanting choose the knife alone—strategy sharp as heat, heat advancing the threat instead of decorating it.

"If I walk into that light," she breathed, "you keep your hand off me until I am through Mae's door—I will not give the post office a show and a confession in the same breath. If I turn us back to Henry, you do not sand the walk. You stay hard and angry and mine while I put the public bluff away and use every ounce of it on him alone."

Jake's answer was a nod she felt against her neck and a slow, filthy grind of his palm that promised both roads would be paid for in heat. He withdrew his fingers with a wet sound the rain almost covered, brought them to his mouth without shame, tasted her like evidence, and then caught her wrist—sticky thumb finding her pulse, hand closing there instead of lower, consequence relocated to the place where her blood argued with strategy. "Either exit," he said, voice ruined. "Mae's window—or Henry's name spoken like a blade with no audience but family. I am here for either cut. I will not love you less. I will only need you after, upstairs or in the wet boxwood or against the pie case, because watching you threaten a town with the truth while your cunt clenched around me is going to live in my body longer than any cover story Henry ever sanded."

Mae's window light held steady across the wet walk. Henry's name sat half-spoken in [player_name]'s mouth—a syllable she could still swallow back into a private reckoning or spit into Mae's waiting stamps with Jake's taste still on her tongue. His hand stayed on her wrist, warm, marked, refusing to steer, refusing to leave. Her nipples ached against lace. Her cunt throbbed with the unfinished circle of his thumb. The blue door waited. The post office lamp waited. Willow Lane waited with woodsmoke and a paperweight and an uncle running out of silence.

Outside the awning, freight complained toward the yard, ordinary as ever. Inside her ribs, the fork brightened: follow through into Mae's gold light and let Market Street become witness—or withdraw the bluff, keep the threat for Henry alone, and walk back into woodsmoke with Jake's hand on her wrist like a vow that still smelled like her. Either exit hurt. Either exit moved. The quiet of Somerton leaned in to hear which hunger she would feed first—the town's appetite, or the family's fracture, or the man whose body had turned a public knife into a reckoning she could feel in her cunt and her pulse and the place where apology used to live.

[player_name] drew a breath that tasted like rain and old coins and coffee and Jake. Mae's window. Henry's unfinished name. His hand on her wrist. The morning refused to land soft.`,
  choices: [
    { id: "scene7h", text: "Walk Mae's light — stamp the whole truth into town", textHot: "Walk Mae's light wet for him — stamp the truth anyway" },
    { id: "scene7f", text: "Withdraw the bluff — put the blade on Henry alone", textHot: "Withdraw the bluff — threaten Henry only, still aching for Jake" }
  ]
};
