export default {
  id: "scene8g",
  layer: 8,
  title: "Papers on the Bed",
  text: `The papers arrived on the quilt like a third body—photocopies still warm from Clara's folder, charcoal circles staring up from dates, Voss's ledger lines crawling through Henry's careful weather as if ink could apologize for ice.

[player_name] sat cross-legged on Jake's bed above the diner with grey late-morning light through the curtain and the blue door stuck downstairs in a draft that smelled like rain and coffee grounds. Jake stood at the foot of the mattress, burn scar whitened on the thumb hooked in his jeans pocket, watching the pages the way a man watched a freight that might jump the rails. Wet boxwood waited on Willow Lane. Woodsmoke would be climbing Henry's stairwell by now. Clara's restless honesty had put copies in [player_name]'s hands at dawn and said, soft as a blade, put them between you if you are done sanding. So [player_name] had. The secret was no longer only in her throat. It was face-up on cotton that still smelled like sleep and vow.

"Read them," Jake said. Not unkind. Not soft. "Or stop when the pages turn into Henry's alone. Both are verbs. Neither lets the quiet climb back into the quilt like furniture."

[player_name] tasted copper and toner and the metallic bright of a winter that had waited fifteen years for an audience of two. Sensory first: paper rasp, rain on slate beyond the window, fryer hymn starting below, cracked counter stool leaning its half-degree left through floorboards, coffee steam ghosting the stairwell, woodsmoke memory from Willow, charcoal grit transferred from Clara's fingers to the margins. Emotion: love still warm from the morning braided to terror braided to the particular shame of watching Jake's face meet the ledger without a softer corridor. Plot: aloud or midway; Henry's confession reserved or refused; Clara waiting across town with graphite under her nails; Mae's trays rearranging memory whether anyone stamped them yet.

She picked up the first page. Henry's handwriting tried to tidy guilt into innocence—dates of payments, a creditor named Voss, notes about ice thickness that read like weather and meant whiskey tea. Clara's charcoal had circled the lie until the circle looked like a bruise that refused to fade. "Your father went through the ice," [player_name] said, voice carrying station platform memory and brighter rooms. "Henry had been drinking what he called tea. Voss was already circling the Shaw name with debt. Henry asked me, at twenty, to leave so Somerton could invent ambition for my exit and keep your grief polite. I said yes. I left. The cover held until Clara found these and Henry's letter cracked what was left."

Jake did not sit. He listened like a man holding a diner together with both hands. Rain needled the glass. Freight complained toward the yard. "Keep going," he said. "Or tell me which pages are his to speak and which are ours to finish. I raised Clara beside lights that forgave too much. I can hear every line. I can also watch you stop when the paper turns into an uncle's mouth that should have to open in person."

[player_name] sorted the stack. Some pages were pure ledger—Voss, amounts, threats sanded into polite demand. Some were Henry's letters to himself, drafts of the story he had sold Market Street: the girl who wanted more, the accident that was only winter, the nephew who needed a cleaner grief than whiskey and debt. Some were Clara's sketches in margins of old schoolbooks, restless honesty drawn over silence until the drawing became evidence. The glass-weight ghost of Willow Lane lived in every crease.

"If I read them aloud until nothing is left unsaid," [player_name] said carefully, "I am not asking the bed to be kind. I am asking it to hold the whole burn—ice, tea, Voss, my yes, ambition as cover, your grief as sanded season—without leaving Henry a single softer page to narrate later. If I stop midway because some pages are Henry's alone to confess, I am sequencing his mouth into the reckoning—loyalty to the idea that certain words should cost him breath in a kitchen, not only toner on a quilt. Both hurt. Both move."

Jake finally sat on the edge of the mattress, close enough that his coat brushed her knee, coffee on his breath, clean work-sweat under woodsmoke. "Reading everything means we walk into Willow or into Clara's room or into Mae's light already finished with private discovery—no corridor where Henry gets to pretend we still need his weather. Stopping midway means we carry what is ours and drag him into the rest—make him say the drafts he wrote about my father while looking at my face. I will stand with either cut. I will not love you less for the whole burn or for the reserved pages. I will only ask that you choose while the papers are still face-up and not invent the decision after we fold them like laundry."

Outside, Market Street woke fully. A delivery truck hissed. Mae's gold lettering fogged and cleared. The blue door stuck when someone tried it too gently and then yielded with the familiar shove. Wet boxwood tapped Willow glass across town. Henry's mantel clock kept guilty time. Clara waited with charcoal under her nails and a stage already built in her mouth. Voss's name sat under every photocopy like a coin waiting for a stamp.

[player_name] watched Jake's hands—scarred, steady, the hands that had rebuilt a fryer hymn around a wound. She thought of fifteen years of practiced belief—the girl who wanted more—and how putting papers on a bed could become another quieter cover if she stopped too early out of mercy that tasted like fear. She thought of Henry alone with an empty mug, sanding nothing because the pages had already left the house. Ending the quiet meant feeding someone a true story. How much of the feed belonged to a quilt and how much belonged to an uncle's living mouth was the remaining blade.

"Your father deserved better than weather," she said. "You deserved better than my exit dressed as ambition. Clara deserved better than finding proof in charcoal. Henry deserves to speak some of this with his own breath if the speaking is going to mean redemption instead of only exposure. Or he deserves to hear every line already spoken so he cannot sand the edges when we walk downstairs. I am done pretending the order is manners."

Jake's thumb found her wrist, pulse under scar. "Then stop explaining and choose," he said, almost gentle, which above the diner was sharper than shouting. "Read them aloud until nothing is left unsaid—pour every circle and every ledger line into this room while rain holds. Or stop midway—some pages are Henry's alone to confess—and accept that stopping has edges, and Clara will ask why ink got mercy, and I will still hold you while we decide which kitchen becomes the stage. Either way, the papers stay face-up until you speak the verb. Either way, I am yours in this bed with the secret no longer only throat-deep."

She lifted another page. Henry's draft described the ice as accident and [player_name]'s ticket as hunger for a bigger life. Clara had drawn a storm over the sentence until the storm looked like accusation. [player_name] felt the fork bright behind her teeth. Sensory returned: paper, rain, coffee steam, fryer oil, woodsmoke memory, charcoal grit, the particular hurt of a woman who had loved before the ledger and was now deciding whether love required every word aloud or required leaving some words for the man who arranged the quiet.

"If I read everything," [player_name] said, "you do not soften the walk to Willow. You stay angry and tender and mine while Henry learns the quilt already finished his weather. If I stop midway, you do not waste the reserved pages on sympathy—you help me put his mouth inside the truth before Mae's trays do it for us."

Jake nodded once. Rain sheeted harder. Freight complained. The cracked stool listened. Gold lettering fogged. Wet boxwood waited. Woodsmoke waited. Clara's graphite waited. Henry's unfinished name trembled in the woodsmoke of memory and in the toner on the quilt. The hook set without soft landing: papers face-up, aloud or reserved undecided, morning refusing to invent a third road where nobody got muddy.

Read them aloud until nothing is left unsaid—or stop midway because some pages are Henry's alone to confess. [player_name] drew a breath that tasted like toner and coffee and rain and the man whose pulse beat under her fingers. The diner held steady above Market Street. The quiet of Somerton leaned in at the gutter to hear which hunger she would feed first—the whole burn on cotton, or the uncle's living breath reserved like a cost he still had to pay in person.

Jake waited. The blue door stuck. The papers stared. The secret had become a stack that refused to tidy itself back into innocence.

Clara's charcoal circles watched from every margin like eyes that had already chosen honesty. Henry's mantel clock kept time across town as if time could still sand ink. Mae's trays remembered flowers and casseroles and the girl who bought a ticket with rain in her hair. [player_name] held the next page between finger and thumb and felt the weight of Willow Lane's glass paperweight even here above the fryer hymn. Reading everything meant finishing private discovery before Henry could invent another cup of tea. Stopping midway meant dragging his mouth into the reckoning so certain words cost him breath. Both were loyalty. Neither was manners. The rain on slate kept civic time. The vow from dawn still lived in her mouth beside the copper of old habit. Jake's scarred thumb stayed on her pulse. The quilt refused to become a softer desk. The morning refused to land soft.`,
  textHot: `The papers arrived on the quilt like a third body—photocopies warm from Clara's folder, charcoal circles staring, Voss's lines crawling through Henry's weather—and [player_name] was already wet from the vow and the grey light and Jake Shaw standing at the foot of the bed with his cock half-hard from watching her put truth on cotton.

She sat cross-legged in his shirt, pages fanned across the mattress, rain ticking slate, blue door stuck downstairs in a draft that smelled like coffee and the unfinished fuck of dawn. Jake's burn scar whitened on the thumb hooked in his pocket, then unhooked, then settled on her ankle as if pulse could outrank toner. Wet boxwood waited on Willow. Woodsmoke would climb. Clara had said put them between you. So [player_name] had. The secret was face-up. Her cunt ached. Her nipples peaked against stolen cotton whenever Jake's gaze flicked from ledger to mouth.

"Read them," Jake rasped. "Or stop when the pages turn into Henry's alone. Both keep me hard. Neither lets the quiet climb back into this bed like furniture we fuck around instead of through."

[player_name] tasted copper and toner and the metallic bright of winter hitchhiking in her body. "Your father went through the ice," she said, steadier than the clench of her thighs. "Henry drank whiskey tea. Voss circled. Henry asked me to leave. I said yes. Ambition as cover. Your grief as sanded season. Clara found papers. I am done. Now I choose whether every line leaves my mouth until nothing is unsaid—or whether I stop midway and reserve the drafts for Henry's living confession."

Jake climbed onto the bed without moving the pages carefully—knees bracketing her hips, cock a thick line against her stomach through denim whenever he breathed, hand sliding under the shirt to span her ribs. "Keep going," he said into her hair, filthy enough for the pulse under his thumb, loud enough for the papers. "Read the whole burn while I stay hard against you, or stop when the ink becomes his to speak and I will still fuck the decision into you after, because delaying his mouth does not delay what your cunt decided when you laid ledger on my quilt."

She sorted stacks with shaking hands—Voss, amounts, Henry's drafts of the girl who wanted more, Clara's charcoal storms over ice-as-accident. Jake's palm found her breast, thumb brushing nipple until she bit her lip to keep the sound off the photocopies. Not a show for the pages. A claim for the choice. "If I read aloud until nothing is left unsaid," [player_name] breathed, "you stay angry and hard and mine while Henry learns the quilt finished his weather. If I stop midway—some pages his alone—you help me drag his mouth into the kitchen before Mae's trays chew us. Both hurt. Both move."

Jake shoved past her waistband and found cotton soaked through—humiliating under charcoal honesty, honest as freight—and pressed two fingers against her clit through the fabric, a brand aimed at decision not orgasm. "Pick," he whispered. "While the papers can still see you refuse to tidy. Read every circle and every Voss line into this room with my fingers on your cunt and the vow still shaking your mouth. Or stop midway—reserve Henry's drafts—and keep shaking for me while we walk him into the rest. Standing here inventing a third stack while you drip on my hand is the only cowardice left above Market Street."

Freight hissed toward the yard. Coffee steam ghosted the stair. The cracked stool leaned. Wet boxwood tapped Willow glass. Henry's empty mug. Clara's graphite. [player_name] rolled her hips a fraction against Jake's hand because stillness had become another Shaw lie, then forced stillness back because the next page deserved a clear throat.

She read another line aloud—ice thickness, tea, a payment to Voss sanded into weather—and Jake sucked a mark into her neck that the ledger could not outrank. "If I read everything," she said, wrecked, "you do not soften the walk to Willow. If I stop, you do not waste reserved pages on sympathy."

"Either exit," Jake promised, withdrawing slowly enough that rain almost covered the wet sound, catching her wrist with a sticky thumb on her pulse. His cock still pressed her. His mouth found her breast through the shirt—one open suck—and then he made space for the choice like a man who understood paper and private heat could share a quilt without apologizing. "Read them aloud until nothing is left unsaid. Or stop midway—some pages are Henry's alone to confess. I will not love you less. I will only need inside you after—pages shoved aside, window, downstairs after burners—because watching you threaten a secret with honesty while wet for me is going to live in my body longer than any cover Henry ever sanded."

[player_name] tasted copper and toner and herself and Jake. Rain sheeted Market Street. The blue door stuck. Freight complained. Her nipples ached. Her cunt throbbed. Henry's name trembled unfinished in woodsmoke memory and in the drafts under her knee. Jake's hand stayed on her wrist, warm, marked, refusing to steer, refusing to leave.

Jake rolled his hips once—helpless, then locked still—and breathed hard enough that the cracked stool below might have learned a new lean. "I rebuilt this diner around a wound," he murmured against her sternum. "I can survive every line aloud. What I cannot survive is watching you invent a softer stack because you still think my cock and my name are too fragile for the whole ledger in the same hour as wanting. Read it loud, or reserve his mouth timed. Do not invent a third road where nobody gets muddy."

She laughed once, wrecked, fogging the curtain. Wet boxwood lived in yesterday's coat. Woodsmoke. Clara's graphite. Voss's shadow. Henry's mantel clock. Fryer oil ticking downstairs like a second timer. She covered Jake's hand—not stopping him, calibrating—and faced the pages with her pulse arguing strategy in sticky thumbprints. "Stopping is not sanding," she said. "It is sequencing his breath into the cost. Reading everything is not cruelty for sport—it is refusing another decade of practiced belief. Both hurt. Both move. Both keep your cock against me until the blue door sticks open for whatever comes after the toner."

Jake kissed the words off her mouth, filthy and tender. "Then spend the verb before the regulars rattle the latch. This quilt does not care about Henry's tea. It cares about what leaves your mouth in which order. Speak."

The hook held: papers face-up, aloud or reserved undecided, body humming, late morning refusing soft landing. Read them aloud until nothing is left unsaid—or stop midway because some pages are Henry's alone to confess. [player_name] drew a breath that tasted like rain and coffee and toner and the man whose cock still pressed her like a second vow. The diner held steady. The quiet leaned in at the gutter to hear which hunger she would feed first—the whole burn on cotton, or the uncle's living breath, or the heat that had turned a quilt into a reckoning she could feel in her pulse and her cunt and the place where apology used to live.

Choose. Jake's thumb. The stack or the reserve. Somerton tracked mud either way and the morning refused to land soft.

Freight complained again, metallic and useless against the throb between her thighs. Clara's charcoal eyes watched from every margin. Henry's drafts waited like a mouth that had not yet paid in breath. Mae's trays remembered tickets and flowers. [player_name] held the next page and felt Willow's glass weight even here. Reading everything meant finishing discovery before tea could reinvent weather. Stopping midway meant dragging Henry's confession into a kitchen where his voice had to crack. Both were loyalty. Rain on slate kept filthy time. The vow from dawn still lived on her tongue beside the taste of herself. Jake's scarred sticky thumb stayed on her pulse. The quilt refused a softer desk. Jake shoved the top pages aside just enough to drag her into his lap without burying Voss, cock hard against her soaked cotton, mouth at her ear. "I listened for a train for fifteen years," he said, voice wrecked. "I can listen to every line while you grind on me, or I can walk Henry into the drafts with your taste still on my fingers. What I will not do is let you tidy this into manners because you think heat and honesty cannot share a quilt. Read it all—make the toner finish him—or reserve his mouth and keep your cunt honest about the cost either way. Clara drew storms for a reason. Henry sanded seasons for a reason. You came home for a reason that is not soft landing." She rocked once against him, helpless, then locked still, papers crinkling under her knee like a third pulse. Rain needled harder. Coffee steam thickened in the stair. The blue door took a shove from below and stuck, then yielded—Market Street continuing without permission. [player_name] tasted toner and Jake and the vow from dawn and felt the fork bright enough to cut. The ledger waited. Henry's drafts waited. Her body waited on a decision that would not go celibate for fear.

The papers stared. The night-morning refused a softer room.`,
  choices: [
    { id: "scene9d", text: "Read them aloud until nothing is left unsaid", textHot: "Read every line aloud — ledger while he stays hard against you" },
    { id: "scene9a", text: "Stop midway — some pages are Henry's alone to confess", textHot: "Stop midway — reserve Henry's drafts, then take Jake through the rest" }
  ]
};
