export default {
  id: "scene5b",
  layer: 5,
  title: "Kiss Then Evidence",
  text: `The kiss he gave her after Clara's interruption was not the first of the night. It was the one that insisted the first had not been a mistake.

Rain still sheeted Market Street into a dark river of slate and lampshine. Henry's umbrella tilted under the light like a dark moth that refused to learn a locked door. Inside, fluorescent pools lay soft on the laminate. Coffee steam ghosted the windows in thin ribbons that smelled of the last rush and the first honesty. The cracked stool by the register leaned its half-degree left as if eavesdropping had become its vocation. The blue door held the night with its familiar stubborn seal—the same damp catch that had marked every winter [player_name] could remember—and John Shaw put both hands on her face as if the papers on the counter were weather he would walk into only after he had anchored himself to her mouth.

"Once more," he said. Soft. Unyielding. Not asking permission so much as naming the choice she had already made by staying when the old pattern wanted a train. "Then you and Clara take the stack. I will hold the door against my uncle until you say I can listen. I will not pretend I do not want to hear every line. I also will not pretend I can kiss you cleanly with his shadow on the glass."

[player_name] rose onto her toes.

His mouth tasted of the coffee he preferred burnt and honest. She fisted her fingers in his shirt and felt him answer with a sound soft enough to undo her, fierce enough to mean restraint had been a long apprenticeship. She smelled rain on cotton, fryer oil ghosting the seams, and underneath it the clean heat of his skin. His palm spanned her jaw; the burn scar at the base of his thumb brushed the hinge like a private signature. His other hand found the small of her back and pulled her flush until the counter edge pressed her hip and the years pressed everywhere else. For a handful of heartbeats Somerton fell away: no letter folded soft in a coat pocket, no uncle rehearsing kindness into a lie, no ledger pages hunted like prey. Only the locked blue door, the tick of the pie case cooling, and the heat of him choosing her in the thin quiet before the quiet finished breaking.

When he drew back, his forehead rested against hers. Grey eyes open. Searching. Bright with something that was not only desire—trust mid-construction, anger held in abeyance, gladness sharp as glass.

"Go," he murmured. "Be braver than I am for ten minutes. I will keep Henry on the porch if he knocks himself raw. If he speaks through the wood, I will answer without sanding. You read. Clara guides. Then you call me in—or you don't. I am done deciding the order of truth alone."

Clara was already gathering the papers, charcoal thumbprint dark on her jaw, sixteen going on forty and unwilling to waste the courage she had carried down the complaining stairs. She glanced once at her brother's kiss-bruised mouth and did not smirk. She only nodded toward the back booth as if the vinyl seats were a courtroom she had prepared with margins and circles and the particular ruthlessness of someone who loved her family too much to keep lying for it.

[player_name] followed. Her mouth still hummed. Her pulse still remembered the counter. She sat.

They took the booth while John moved to the front—shoulders set, one hand on the blue door's inner latch, a sentry made of diner light and stubborn love. Rain hammered the glass beside him in a continuous hush that made Market Street sound like a distant shore. Henry's next knock arrived polite, then less polite, then shaped like a name. John did not open. His voice carried just enough for the booth to hear, low and even, the tone he used when a customer was wrong and he would not make a scene until the room emptied—except the room tonight was family, and emptying it was no longer the point.

"Not yet, Uncle," John said. "You had fifteen years of yet. She gets a turn with the truth you filed under false bottoms. Stand in the rain you helped invent. I am not opening until they say so."

Clara exhaled through her nose. "He hates being spoken to like that," she whispered, almost fond, almost fierce. "Good. He has been the door long enough."

She spread the pages the way she spread sketches—edges aligned, chaos given a geometry that could be survived. Bank paper with soft corners. A winter date fifteen years old, pencil grooved deep enough to scar the sheet below. [player_name]'s name underlined twice beside the line that still landed like cold water: she agreed to go—for him. Drafts of a letter Henry had sanded softer with each attempt, ambition replacing ice, trains replacing blood, a bigger life replacing a debt. Receipts carrying a surname that made [player_name]'s stomach drop as if the booth had tilted: Voss. An old exchange number written on the back of one slip in a hand that might have been Henry's or might have been a ghost's. Clara's blue ballpoint circles bloomed in the margins like bruises that had decided to become maps. Charcoal studies rode between them—station steps, suitcase, Henry standing between two younger figures like a door that had learned to smile.

"I found these because I stopped believing the neat version," Clara said. Her voice cracked toward adult and then steadied, the way floorboards steadied under a deliberate descent. "Uncle Henry keeps a desk that looks empty if you open it like a guest. I opened it like a sister who has been drawing the gaps for years. False bottom. Photocopy of a glove-box ledger. A draft that still had the accident in the first paragraph before he erased winter into weatherlessness." She tapped the sketch of the station. "I drew this before I had language. The papers gave me language. You gave me a body in the room so I would not have to carry the language alone to John like a sentence without a witness."

[player_name] listened the way rain listened to slate—continuous, unwilling to miss a pitch. Sensory first: the vinyl cool and faintly sticky with old polish under her palms; charcoal dust sweet and dry in the fluorescent air; the distant murmur of John's refusal at the door; coffee gone cold and metallic on her tongue where the kiss still lived; the soft metal smell of the grill cooling in the kitchen pass. Then emotion: shame like a swallowed coin, old and rounded by years; gratitude sharp enough to hurt; the ache of being seen as exit wound and shield at once; a fierce protectiveness toward the girl across from her who had hunted truth with a pencil and a stubborn heart. Then the turn, quiet as a page turned in a draft.

"There is a red circle," Clara said. She did not flip that page fully into the light. She let its edge show—enough to prove courage, not enough to decide the order of wounding. "I can narrate around it. Or through it. I circled everything that did not fit in blue: dates that skip, numbers that refuse to add, a name that appears three times and then never again like someone decided erasing was kinder than explaining. Red is different. Red is the page that names what Voss threatened if the debt went public. Red is what Henry traded besides money. Red has a signature on a line that should not exist if the story we were told about that winter road was clean." She swallowed. Charcoal crescent under her nail caught the light. "I can speak first when you call him over. I have practiced. I would rather interrupt another kiss than let either of you build a night on half a ledger. Or—" her gaze flicked toward John's silhouette, then back, measuring "—I walk upstairs with headphones and leave you the booth. You ask my brother what he wants from you tonight while the truth sits here cooling. He is going to look at you like the kiss was a promise and the papers are the fine print. Both paths are honest. They are not the same honesty."

Outside, Henry's umbrella dipped and lifted as if even patience had weather. John's shoulders blocked the lamp. The blue door shivered in its frame and held. Somewhere above them a draft worried a sketchbook page. Wet boxwood waited on Willow Lane with woodsmoke and a mantel clock and the originals under a glass weight, tidy as guilt pretending to be innocence. Freight muttered in the yard the way it always had—never quite leaving, never quite arriving.

[player_name] tasted John on her mouth and metal on the air. She looked at Clara's charcoal hands, at the papers that had cracked Somerton's quiet open, at the man holding the door with his body because he had decided love meant sentry duty as much as kissing. The night narrowed to stance and risk: sister as narrator of the wound, or sister excused so desire and dread could speak without a witness. Rain silvered the glass until Market Street became a rumor. The pie case ticked. Henry knocked once more, softer, as if he finally understood the room had changed owners for the evening.

John did not look back—trusting them, or bracing, or both. Clara waited, red ink bright under fluorescent light, ready to narrate every circled line or to climb the stairs and grant the booth its thinner privacy. The unfinished kiss still hummed in [player_name]'s blood. The evidence waited like a second pulse. And the choice, for once, was not Henry's to sand soft—only hers to make while the quiet finished breaking in a diner that smelled of coffee, rain, and the courage of a girl with charcoal on her jaw.`,
  textHot: `The kiss he gave her after Clara's interruption was not the first of the night. It was the one that insisted the first had not been a mistake—and that stopping had nearly undone him.

Rain sheeted Market Street into slate and lampshine. Henry's umbrella tilted under the light. Inside, fluorescent pools lay soft on laminate. Coffee steam ghosted the windows. The cracked stool leaned its half-degree left. The blue door held with its damp stubborn seal. And John Shaw put both hands on [player_name]'s face as if he meant to memorize her with his mouth before the papers could steal the heat from under his skin.

"Once more," he said, voice rough from the earlier kiss, from wanting, from the particular strain of loving a woman while his uncle's shadow stained the glass. "Deep enough that I feel it when I am standing at that door pretending I am only angry. Then you and Clara take the stack. I hold Henry off. I will not pretend I do not want every line. I also will not pretend I can taste you cleanly with his patience on the porch—so give me something filthy and true to carry while I play sentry."

[player_name] rose onto her toes and gave him exactly that.

She felt him hard against her, unmistakable, unashamed, a fact the fluorescent light could not make polite. His mouth tasted of burnt-honest coffee. She smelled rain on cotton, fryer oil ghosting the seams, the clean heat of his throat when she tipped her head and let him kiss down to the place beneath her ear that made her shiver. His palm spanned her jaw; the burn scar brushed like a signature. His other hand slid under the back of her shirt just far enough to find bare skin at her waist, fingers splayed, possessive without being rough. She made a sound into his mouth that would have embarrassed her in daylight and only made him press closer until the counter edge bit her hip and she felt every unfinished inch of him. For a handful of heartbeats Somerton fell away: no letter, no ledger, no man under a lamp. Only locked blue door, cooling pie case, and John claiming her with a hunger fifteen winters had sharpened into something almost gentle and almost feral at once.

When he drew back, he was breathing like he had run. Forehead to hers. Grey eyes nearly black. His thumb brushed her lower lip, wet from him, and she tasted salt and coffee and the promise of more.

"Go," he murmured. "Be braver than I am for ten minutes. If I follow you into that booth right now I will not read. I will put you against the vinyl and finish what the stairs interrupted—mouth, hands, the way you said my name without saying it—and Clara does not need to see that." A wrecked almost-smile. "Yet. Call me when the paper has had its turn. Or send her up and call me sooner. I will know what you mean either way."

Clara gathered the papers with charcoal on her jaw and the grace of someone who understood heat without needing its inventory. She glanced once at how closely they still stood, at the flush on [player_name]'s throat, and only nodded toward the back booth. [player_name] followed on legs that remembered his hips. Her mouth was sensitive. Her body hummed. The taste of him was a live wire under every thought the evidence would try to claim.

They sat with the stack between them while John took the front—shoulders set, hand on the latch, sentry and barely-leashed man. Rain made a continuous hush. Henry knocked. John's voice carried, low and even and edged: "Not yet, Uncle. You had fifteen years of yet. She gets a turn with the truth you filed under false bottoms. Stand in the rain. I am not opening until they say so."

Clara exhaled. "He hates that. Good."

She spread the pages: bank paper soft at the corners; a winter date; [player_name]'s name underlined twice beside she agreed to go—for him; drafts sanded from ice into ambition; receipts stamped with the surname Voss; an old exchange number grooved in pencil hard enough to scar. Blue circles bloomed in the margins. Charcoal studies rode between—station, suitcase, Henry as door. [player_name] tried to focus through the throb of her pulse and the ghost of John's hand under her shirt, through the ache between her legs that grief and wanting refused to untangle.

"I found these because I stopped believing the neat version," Clara said. Voice cracking toward adult, steadying. "False bottom. Glove-box ledger photocopy. A draft that still had the accident before he erased winter into a prettier exile." She tapped her sketch. "I drew the gap before I could name it. The papers named it. You walked into the diner, kissed my brother like you meant to stay, and made the naming worth the risk."

Sensory first: vinyl under palms; charcoal sweet-dust; John's refusal murmuring at the door; coffee cold and metallic; her mouth still swollen-soft; heat coiled low; the faint musk of interrupted sex that still clung to the air near the counter like a secret the fluorescent light had failed to bleach. Emotion: shame, gratitude, ache, a fierce want to walk back to that door and put her hands on him again until paper became tomorrow's problem. Plot turn: Clara's finger stopping on a page not yet fully shown, red ink a warning and a dare.

"There is a red circle," Clara said. She let the edge show—courage without deciding the order of wounding. "Blue is what did not fit: skipped dates, numbers that refuse to add, a name that appears and vanishes. Red is what Voss threatened. What Henry traded besides money. A signature on a line that should not exist if that winter road was clean." She swallowed. "I can narrate every circled line when you call him over. I have practiced. I would rather interrupt another kiss than let you build heat on half a ledger." Her gaze flicked to John's silhouette, then back, knowing and kind. "Or I walk upstairs with headphones like I promised when the storm trapped you. You ask my brother what he wants from you tonight—from your mouth, your hands, your honesty—while this stack sits here cooling. He already told you with his body at the counter. He might need to say it with his mouth while he can still taste you. Both paths are honest. They are not the same honesty."

Outside, the umbrella dipped. John's shoulders blocked the lamp. The blue door shivered. Upstairs a draft worried paper. Willow waited with woodsmoke and tidy guilt under glass. In the booth [player_name] tasted John and metal. She felt the counter kiss in her thighs, the press of him, the unfinished promise humming under her skin like a second heartbeat. Clara's charcoal hands waited. The man at the door trusted them—or braced—or burned with the particular patience of someone who had been hard and grieving and still chosen sentry duty over taking.

"He is going to look at you like the kiss was a vow and the papers are the fine print," Clara added softly. "I can speak the fine print first so the vow has somewhere solid to land. Or I can leave you alone with him and let wanting decide whether truth or touch comes next. Your call, [player_name]."

John's voice came again from the front, quieter, meant for Henry and overheard anyway: "If you came to confess, you can wait until she is finished deciding how much of you she still owes the rain." Something in [player_name] loosened at that—desire braided with loyalty, heat braided with the relief of being defended without being handled. Clara watched her face and, for a moment, looked younger and older at once.

"For what it is worth," Clara said, almost a whisper, "I did not bring the papers downstairs to stop you from wanting him. I brought them so the wanting would have ground under it. If you send me up, I will not listen at the floorboards. If you keep me here to narrate, I will not flinch from the red circle. Either way, do not sand anything soft just because his mouth made you dizzy. Dizzy is allowed. Softening the ledger is how we got the lie."

[player_name] nodded. The booth held charcoal and cold coffee and the ghost of John's hands. Outside the rain kept its vow. Inside, the choice kept its teeth.

Rain silvered the glass until Market Street became a rumor. The pie case ticked. Henry knocked softer, resigned. John did not look back. [player_name]'s blood still carried the deep unfinished kiss; her skin still remembered bare fingers at her waist; her body still held the shape of his hunger. The evidence waited like a second pulse beside a choice that was finally hers without Henry sanding it: sister as narrator of the wound—or sister excused so she could ask John, while her mouth still tasted like him, what he wanted from her body and her truth before dawn found the blue door and the rain forgot how to be merciful.`,
  choices: [
    { id: "scene6b", text: "Let Clara narrate what she found", textHot: "Let Clara narrate what she found while your mouth still tastes like him" },
    { id: "scene6c", text: "Send Clara out — ask John what he wants from you tonight", textHot: "Send Clara out — ask John what he wants from your body tonight" }
  ]
};
