export default {
  id: "scene8f",
  layer: 8,
  title: "Love Before Secret",
  text: `Dawn above the diner smelled like coffee grounds left overnight, rain drying on the blue door downstairs, and the particular courage of a woman who had decided to say love before she said the rest of the winter.

[player_name] woke in John's narrow bed with grey light through the curtain and his arm heavy across her waist. Market Street hissed faintly—early freight, a delivery truck, Mae's gold lettering two storefronts over fogging with civic breath. The cracked counter stool leaned its half-degree left below them as if listening through floorboards. Wet boxwood waited on Willow Lane with Henry's mantel clock and papers under glass. Woodsmoke would rise there soon. Here, above fryer hymn and stuck blue door, [player_name] tasted copper and sleep and the unfinished heat of a night that had claimed without finishing the confession.

John's eyes opened before his mouth did. Burn scar whitened on the thumb that stroked her ribs—not steering, present. "You are awake like someone who brought a verb to bed," he said, voice rough with coffee-memory and wanting. "Say it before the secret if that is what the morning is. Or put the papers between us if that is the other hunger. I rebuilt this place around a wound. I can hold either cut. I will not love you less for the order."

[player_name] watched the freckle at the corner of his mouth she had known at twenty and somehow still. Sensory first: cotton sheets, rain-damp air through the cracked window, coffee ghost from downstairs, fryer oil not yet lit, the blue door's stubborn seal in the stairwell draft. Emotion: tenderness braided to terror braided to the bright fear of naming love while Voss's shadow and Henry's whiskey tea still lived unspoken between their bodies. Plot: vow undecided in timing against truth; Clara waking toward graphite across town; Henry alone with an empty mug; Mae's trays rearranging whether anyone stamped them yet.

"I love you," [player_name] said. Not soft. Not sanded. The words landed in the grey like freight finding rails. "I loved you when I left. I loved you in brighter rooms that never smelled like this diner. I love you now with the secret still in my throat and Clara's charcoal circles waiting and Henry's letter cracked open in my coat downstairs. I am saying it before the ice and the creditor and the yes I gave at twenty, because if I say the secret first I might never get to the love without making it sound like apology."

John went still in the way of a man who had listened for a train for fifteen years and finally heard brakes. His hand flattened on her sternum, pulse under his palm. "Say it again," he murmured. "Not because I doubt it. Because the town practiced a cleaner grief than the one we earned, and I need your mouth to outrank the practice."

"I love you," she repeated, and the rain on slate outside answered like a second civic timer. "John Shaw. Diner. Blue door that sticks. Cracked stool. The boy who stayed. The man who raised Clara beside the lights. I am not leaving this time as a cover. I am here with a vow that still has the secret attached like a second pulse, and I need you to hear the vow first so the secret does not get to narrate what we are."

He kissed her—slow, coffee-bitter, unfinished—and rested his forehead against hers. Wet boxwood lived faintly in her hair from yesterday's Willow. Woodsmoke clung to both their coats on the chair. Clara's restless honesty waited across town. Voss's name sat under [player_name]'s tongue like a coin she had not yet spent into this bed.

"Then the morning forks," John said. "Tell me the secret the same morning—ice, whiskey tea, Voss, Henry's ask, your yes, ambition as cover, my grief as sanded season—while the vow is still warm on your mouth and mine. Or keep the secret one more day after the vow—give us twenty-four hours of loving without the ledger between us, and accept that the pause has edges and Clara's clock and Mae's trays will not wait forever for our softer courage. Both are loyalty. Neither is sanding. Both hurt."

[player_name] tasted the fork bright behind her teeth. She thought of fifteen years of practiced belief—the girl who wanted more—and how love spoken aloud could become another quieter cover if the secret stayed buried under tenderness. She thought of John under diner lights rebuilding a life around a wound Henry arranged into weather. Ending the quiet meant feeding someone a true story. Timing the feed against the vow was the remaining blade.

"If I tell you the same morning," she said carefully, "I am not asking the vow to be kind. I am asking it to survive the ledger in the same breath. If I keep the secret one more day after the vow, I am not protecting Henry. I am sequencing love before paper—time that might save us or spare the wound one more soft hour before it has to learn its real name."

John's thumb stroked her pulse at the throat. "Same morning means we walk into Willow or into Clara's room or into Henry's kitchen with love already spoken and the ugly words right behind it—no corridor where I get to pretend the vow erased the winter. One more day means I get to hold you through a full turn of Market Street light while the secret waits in your coat, and I will take that day if you offer it, but I will not pretend the day is mercy forever. Clara found papers. Henry's letter cracked what was left. My body knows you are here. My name still needs the truth."

Outside, early rain sheeted Market Street. The blue door stuck in the draft. Coffee steam would rise soon when John lit the burners. Freight complained toward the yard. Station platform hiss lived in memory. Gold lettering on Mae's window fogged. Wet boxwood waited. Woodsmoke waited. Clara's charcoal waited. Henry's unfinished name trembled in the woodsmoke of memory.

[player_name] pressed her palm over John's heart—consequence, not comfort. "I rebuilt nothing," she said. "You did. You stayed. You listened. I bought a ticket home with rain in my hair and a letter that was not come home, only I thought you should know. Loving you before the secret is the only order that does not turn the vow into penance. Timing the secret against that love is the only question left that still has a blade."

"Then stop explaining and choose," John said, almost gentle, which from John above the diner was sharper than shouting. "Tell the secret the same morning—pour ice and Voss into the vow while grey light holds. Or keep the secret one more day after the vow—and accept that holding has edges, and I will ask again at tomorrow's dawn, and I will not love you less for the pause or for the burn. Either way, the blue door sticks. Either way, I am yours in this bed with the secret still deciding whether it sleeps between us or wakes with us."

She watched his mouth. She watched the scar. She watched the grey brighten toward a day that would not land soft. Sensory returned: cotton, rain, coffee ghost, fryer not yet lit, woodsmoke memory, charcoal memory, the particular hurt of a woman who had said love and still had winter in her throat.

"If I tell you now," [player_name] said, "you do not soften the walk downstairs. You stay angry and tender and mine while the ledger learns it cannot outrank the vow. If I keep one more day, you do not waste the pause on Henry's sanded tea—you help me love you in daylight without inventing another cover out of tenderness."

John nodded once. Rain needled the window. The cracked stool listened through floorboards. Mae's trays waited. Clara's graphite waited. Henry's mantel clock kept guilty time across town.

Tell the secret the same morning—or keep the secret one more day after the vow. [player_name] drew a breath that tasted like coffee grounds and rain and the man whose heart beat under her palm. The diner held steady above Market Street. The quiet of Somerton leaned in at the gutter to hear which hunger she would feed first—the ledger in the same breath as love, or the one-day corridor that could save them or teach the wound a softer name for twenty-four hours too long.

Clara would wake soon across town with graphite under her nails and a folder that smelled like rain. Henry would pour tea that was never only tea. Mae would sort slots that remembered who sent flowers when John's father died. [player_name] held the vow in her mouth like a live wire and the secret behind it like a second train. Same morning meant letting both arrive before Market Street finished waking. One more day meant teaching the wound a softer name for twenty-four hours and hoping tenderness did not become weather. The cracked stool listened. The blue door stuck. John's heart beat under her palm like a clock that was not Henry's mantel and somehow kinder—and somehow sharper for being kind.

John waited. The blue door stuck. The vow stayed warm. The secret waited in her throat like a second train.`,
  textHot: `Dawn above the diner smelled like coffee grounds, rain on the blue door, and the particular heat of a woman who had woken wet against John Shaw's thigh and decided to say love before she said ice.

[player_name] woke straddling the line between sleep and wanting with John already hard against her hip, grey light through the curtain, his hand possessive under the sheet at the small of her back. Market Street hissed. The cracked stool leaned below. Wet boxwood waited on Willow. Woodsmoke would rise. Here, above fryer hymn and stuck door, her cunt ached from the unfinished night—claimed, not finished—and her mouth tasted copper and sleep and the courage of a vow that still had Voss attached like a filthy second pulse.

John's eyes opened. Burn scar whitened on the thumb that stroked the underside of her breast through the thin shirt she had stolen from his chair. "You are awake like someone who brought a verb and a cunt to the same morning," he rasped. "Say you love me before the secret if that is the hunger. Or put the papers between us after. I can fuck you through either order. I will not love you less for the timing."

"I love you," [player_name] said, and rolled her hips once against the thick line of his cock because stillness had become another Shaw lie. Not soft. Not sanded. "I loved you when I left. I loved you in brighter rooms. I love you now with the secret in my throat and your cock against me and Clara's charcoal waiting. I am saying the vow before the ledger so the ice cannot narrate what we are."

John groaned into her neck—open, wet, a suck Mae would have filed under memory if Mae could see upstairs—and shoved the shirt up until both palms spanned her ribs. "Say it again while I am hard for you," he demanded. "Not doubt. Outrank the practice. The town sanded my grief into weather. Your mouth gets to outrank the sand."

"I love you, John Shaw," she repeated, voice rough as his thumb found her nipple and pinched once, deliberate. "Diner. Blue door. Cracked stool. The man who stayed. I am not leaving as cover. I am here with a vow and a secret braided, and I need the vow first so when I tell you about ice and whiskey tea and Voss and Henry's ask and my yes at twenty, you hear it as a woman who already claimed you—not as apology wearing desire."

He kissed her filthy—tongue, coffee-bitter, teeth—and pressed his cock against her cunt through cotton until she gasped. "Then the morning forks," he said against her mouth. "Tell the secret the same morning—pour the ledger into this bed while the vow is still wet on your tongue and I am still inside the sound of it. Or keep the secret one more day after the vow—give us twenty-four hours of fucking and coffee and Market Street light without the pages between us—and accept that the pause has edges and Clara's clock will not wait forever. Both keep me hard. Both keep you from inventing a prettier lie in the shower."

[player_name]'s nipples peaked hard. Her cunt soaked the cotton. She gripped his shoulder, rain-smell and coffee-ghost and woodsmoke-memory braided into one bright fork. "If I tell you the same morning," she breathed, "you do not soften. You stay angry and hard and mine while the vow survives the ledger in the same breath. If I keep one more day, you do not waste the pause on Henry's tea—you fuck me through daylight without turning tenderness into another cover."

John shoved past her waistband and found her soaked—two fingers sliding through her folds, pressing her clit once, a brand aimed at decision not orgasm yet. "Pick," he whispered. "While grey light can still see you refuse to sand. Tell me ice and Voss this morning with my fingers in you and the vow still shaking your mouth. Or keep the secret one more day—and I will still bury my cock in you now, because delaying the ledger does not delay what your cunt has already decided about coming home. Standing here inventing a third dawn while you drip on my hand is the only cowardice left above Market Street."

Freight hissed toward the yard. Mae's gold lettering fogged in memory. Wet boxwood tapped Willow glass across town. Henry's empty mug. Clara's graphite. [player_name] rolled her hips against his fingers because the vow deserved a body, then forced a fraction of stillness because the choice deserved a clear throat.

"If I tell you now," she said, wrecked, "you walk me through the ugly words without letting go of my cunt or my vow. If I keep one day, you spend it making sure love does not become weather."

"Either exit," John promised, withdrawing his fingers slowly enough that rain almost covered the wet sound, painting her lower lip with her own slick before she could think to be ashamed. His cock still pressed her. His mouth found her breast—one open suck through the shirt—and then he made space for the choice like a man who understood vows and private heat could share a grey morning without apologizing. "Tell the secret the same morning. Or keep it one more day after the vow. I will not love you less. I will only need inside you after—now, against the window, downstairs after the burners light—because watching you speak love while wet for me is going to live in my body longer than any cover Henry ever sanded."

She tasted herself and copper and coffee and John. Rain sheeted Market Street. The blue door stuck. Freight complained. Her nipples ached. Her cunt throbbed. Henry's name trembled unfinished in woodsmoke memory. John's hand stayed on her hip, warm, marked, refusing to steer, refusing to leave.

John rolled his hips once—helpless, then locked still—and breathed hard enough that the cracked stool below might have learned a new lean. "I rebuilt this diner around a wound," he murmured into her sternum. "I can survive the ledger in the same hour as your vow. What I cannot survive is watching you invent a softer morning because you still think my cock and my name are too fragile for truth and love in the same grey light. Same morning loud, or one day timed. Do not invent a third road where nobody gets muddy."

[player_name] laughed once, wrecked, fogging the curtain. Wet boxwood lived in yesterday's coat. Woodsmoke. Clara's graphite waiting. Voss's shadow. Henry's mantel clock. Fryer oil about to tick downstairs like a second timer. She covered John's hand—not stopping him, calibrating—and faced the dawn with her pulse arguing strategy against his thigh. "One day is not sanding," she said. "It is sequencing. Same morning is not cruelty for sport—it is refusing another decade of practiced belief. Both hurt. Both move. Both keep your cock against me until the blue door sticks open for whatever comes after the vow."

John kissed the words off her mouth, filthy and tender. "Then spend the verb before the regulars rattle the latch. This bed does not care about Henry's tea. It cares about what leaves your mouth in which order. Speak."

Tell the secret the same morning—or keep the secret one more day after the vow. [player_name] drew a breath that tasted like rain and coffee and the man whose cock still pressed her like a second vow. The diner held steady. The quiet leaned in at the gutter to hear which hunger she would feed first—the ledger in the same breath, or the one-day corridor, or the heat that had turned grey light into a reckoning she could feel in her pulse and her cunt and the place where apology used to live.

Choose. John's thumb. The vow or the pause. Somerton tracked mud either way and the dawn refused to land soft.

Freight complained again, metallic and useless against the throb between her thighs. She thought of the station platform, of tickets bought with rain in her hair, of every unfinished fuck that had braided wanting to courage until neither would go celibate for Henry's weather. Same morning meant pouring ice into the vow while John's fingers still shone with her. One more day meant buying a corridor—then taking that corridor with her cunt still aching and his mouth on her breast until tomorrow's dawn asked again. Rain on slate kept filthy time. The blue door stuck. Woodsmoke and coffee and John's sticky thumb made the bed into a reckoning. Clara would wake soon with graphite under her nails. Henry would pour tea. Mae would sort slots. [player_name] held the vow on her tongue beside the taste of herself and the secret like a second train. Same morning meant pouring ice into the vow while John's cock still pressed her soaked cotton. One more day meant teaching the wound a softer name for twenty-four hours of fucking and coffee—and hoping tenderness did not become another Shaw cover. The cracked stool listened through floorboards. The blue door stuck. John's pulse against her cunt was a clock that was not Henry's mantel and somehow filthier for being kind. The dawn refused to invent manners.

The secret waited in her throat. The night-morning refused a softer room.`,
  choices: [
    { id: "scene9c", text: "Tell the secret the same morning", textHot: "Tell the secret the same morning — ledger while he is still inside the vow" },
    { id: "scene9e", text: "Keep the secret one more day after the vow", textHot: "Keep the secret one more day — fuck first, ledger at tomorrow's dawn" }
  ]
};
