export default {
  id: "scene3c",
  layer: 3,
  title: "Henry Pressed",
  art: "/art/until-the-quiet-breaks/scene3c.png",
  text: `[player_name] did not sit. She kept her coat on like armor and let the wood heat of Henry's front room work against her without winning. Rain ticked the windows in patient rhythms. The mantel clock kept its shallow time. Wet boxwood breathed through the door Henry had not fully closed, braided with woodsmoke from a fire fed recently enough to speak of nerves. Under the glass paperweight, papers waited like evidence someone had tried to tidy into innocence. She looked at Henry—older, thinner through the face, grey hair combed with careful discipline—and refused the chair he gestured toward.

"Whole truth," she said. "Not the kindness. Not the shape you carved for Jake. The winter. The debts. The ask. You wrote a letter that opened a door and then stood behind it. I walked through. Now you finish."

Henry poured tea he did not drink. The cup clicked against the saucer once—betrayal of nerves—and then his voice found its rail, the careful cadence of a man who had rehearsed confession long enough to know rehearsal did not help and was doing it anyway. He spoke of money Jake's father had hidden behind jokes and overtime, debts that climbed higher than anyone in the Shaw house would admit, people who did not wait politely when winter made collection cruel. He spoke of a promise he made at a hospital bedside—keep the diner solvent, keep the family intact, keep the boy from seeing how close ruin had come—and failed before the snow melted. He spoke of a winter road black with ice, of a car that should not have been on it with that weight of panic and owed money in the driver's chest, of a father's ending that Somerton still refused to say aloud except as accident, as weather, as something nobody could have prevented.

"You were there for parts of it," Henry said. His fingertips rested on the paperweight without lifting it. Firelight caught the glass and threw a pale coin across the stacked pages. "You saw enough. Enough to know the cover we needed. Enough to know why I sat a twenty-year-old girl down in this room and asked her to become an exit wound so the boy would not learn how close the Shaw name had come to swallowing itself whole. I told you silence would protect Jake. You left. We told him you wanted more than Somerton—a bigger life, brighter rooms, a map that did not end at Market Street. It was almost true. You were bright and restless and worthy of trains. It was also a lie with a purpose. The purpose calcified. I mistook silence for love."

[player_name] tasted metal and old anger and something like pity she did not yet trust. The letter crackled faintly in her pocket when she shifted her weight. She did not take it out. She did not need the pages. She needed his mouth to keep doing the work his handwriting had refused for fifteen years. Outside, rain sheeted the yard into a blur of dark green and slate. The house creaked in its joints the way old houses confess—slowly, whether anyone asks or not.

"Jake has lived with a version of that night that never fit," Henry continued, eyes on the boyhood photograph on the mantel—Jake at the diner counter, grin half-hidden, grey eyes already learning stillness. "Your face on the station steps. My hand on your shoulder. The way you said sorry like someone carrying a weight that was not ambition. He tried to make the pieces fit while he ran the diner and raised Clara after their mother stopped being a person we could reach. I watched him practice believing the tidy sentence. I watched him fail at night and succeed in public. I told myself I was sparing him. What I spared him was the chance to forgive us properly."

Soft footsteps. Clara appeared in the kitchen doorway, sketchbook hugged to her chest, charcoal crescent dark on her knuckle, sixteen going on forty and allergic to unfinished stories. She did not apologize for listening. She had earned the right the night she found Henry's desk and refused to put the wrong kind of paper back. "I found the ledger pages," she said to [player_name], voice steady, eyes sharp. "I found the note where he practiced what to tell Jake—drafts of the ambition story, crossed-out lines that almost told the truth and then didn't. I found dates in the margins of my own old schoolbooks where I'd been sketching without knowing I was mapping a wound. I did not find you. He did that with a stamp." She lifted the sketchbook slightly. "I drew the gap before I found the papers that named it. Rain. A car. Your silhouette on the station steps. Jake waiting. Henry standing between. Charcoal doesn't lie as easily as uncles."

Henry's mouth twitched—almost a smile, almost a flinch. "She forced my hand. Without her, I might have kept rehearsing until I died of carefulness. The letter was late courage. This—" he gestured at the room, at the papers, at the tea going cold—"is what late courage sounds like when it finally runs out of euphemism."

The confession left the room thinner, as if language had used up the oxygen. Rain softened against the glass. [player_name] walked to the table and looked at the papers under glass without lifting the weight: dates, a name she remembered from that winter, Clara's charcoal along one edge—a quick study of hands, fingers open as if dropping something too heavy to hold. She felt fifteen years of practiced silence try to climb her throat and stop her next questions. She swallowed it down. The clock ticked. A log settled in the grate. Woodsmoke curled.

"You asked me to leave so he would not have to see the whole of it," she said. "I did. I practiced being the girl who wanted more until the practice became a life. Cities rewarded the practice. Trains smelled like proof. Standing here, I am not sure who the silence protected—Jake, or you, or the neatness of Somerton's story about itself."

Henry inclined his head. The admission sat between them like another piece of furniture too heavy to polish away. "Then take what you will of this. You can carry it to Jake as proof I finally spoke—debts, failed promise, cover story, the reason I cast you as ambition instead of witness. He is at the diner. He does not know I mailed the letter, not for certain, though he suspects. He has always suspected. Go to him with open hands and let him decide whether my voice belongs in the room when the truth arrives. Or—" his gaze moved to Clara, who lifted her chin, ready, afraid, brave in the way of people who prefer charcoal to silence—"doubt every word. God knows you have earned doubt. Look for yourself. Clara will show you where the rest was hidden. The glove-box pages. The ones I still flinch naming. The drafts I did not put under glass because even late courage has corners it prefers dark."

Clara stepped fully into the room. Charcoal dust ghosted her sleeve. The sketchbook's edges were soft with handling, margins crowded with studies of the blue door, of rain, of hands, of a winter she had only half inherited and was determined to finish knowing. "I know where he tucked the rest," she said. "Behind the false panel in the desk. In the envelope taped under the bottom drawer. In the schoolbook he thought was only mine. If you want the map instead of his speech, I'll give it. If you want Jake first, I'll wait. I've waited this long. Another hour won't kill me. It might kill the tidy version, though. Good."

From far off, as if Somerton itself were keeping time, [player_name] felt the diner's closing hour live in her bones like a second clock. Jake would be wiping counters, listening for a step that might be hers, grey eyes holding weather without flinching, burn scar catching the light when he flexed his hand against laminate he had already cleaned. Coffee steam. The cracked stool. The blue door sticking in the damp the way loyalty sticks—awkward, faithful, unwilling to swing easy. Henry waited. Clara waited. The papers under the glass paperweight waited like a held breath. Wet boxwood dripped on the porch. The fire popped.

[player_name] looked from uncle to sister to the mantel and felt the fork settle—not at the station this time, not on Market Street, but here in the house where the quiet had been built. She could believe Henry enough to go find Jake with open hands, carrying the confession as a gift and a wound, trusting that late truth was still truth even when it arrived smelling of woodsmoke and fear. Or she could doubt him—search the house with Clara's sketches as a map, refuse to let another Shaw man narrate the ending of her leaving, put her own hands on the glove-box pages and the flinching corners before she offered Jake anything at all. Neither path was soft. Both led through rain toward a man who had practiced losing her and a secret that was finally, irrevocably, done hiding under glass.

Henry's careful eyes held hers. Clara's charcoal-smudged fingers tightened on the sketchbook. The letter in [player_name]'s pocket felt suddenly small—three pages of weather and silence that had only ever been a door, never the room beyond it. She breathed woodsmoke and lemon polish and the mineral cold of rain at the threshold. The quiet around her was not empty. It was waiting for her to choose how it broke.`,
  textHot: `Wood heat found [player_name]'s skin like a hand she refused to lean into. She stayed on her feet—coat still on, rain still dampening her blouse so every breath made fabric cling to her breasts—because sitting would have turned Henry's front room into surrender, and because Jake's name already landed between her legs as much as behind her ribs. Rain ticked windows. Mantel clock shallow. Wet boxwood through the half-closed door, braided with woodsmoke from a fire fed for nerves. Under glass, papers waited like guilt tidied into innocence. She looked at Henry—older, thinner, grey combed careful—and refused his chair. Standing kept her from softening into furniture the way Somerton liked women to soften when men told long stories. Standing kept her cunt honest: braced, awake, done pretending this confession was only paper.

"Whole truth," she said. Voice flat. Body loud. "Not the kindness. Not the shape you carved for Jake. The winter. The debts. The ask. You wrote a letter that opened a door and stood behind it. I walked through. Now you finish."

Henry poured tea he did not drink. Cup clicked saucer—nerves betraying—then his voice found its rail, rehearsed confession that knew rehearsal did not help. Money Jake's father hid behind jokes and overtime. Debts higher than Shaw pride admitted. Collectors who did not wait politely when winter made cruelty efficient. Hospital-bedside promise: keep the diner solvent, keep the family intact, keep the boy from seeing ruin—failed before snowmelt. Winter road black with ice. Car that should not have been on it with panic and owed money in the driver's chest. Father's ending Somerton still would not say except as accident, weather, nobody's fault. [player_name] listened with her whole body locked: jaw tight, coat buttoned, thighs pressed as if stance could hold the past out of her bones. Every Jake landed lower than grief allowed—hot unfinished wanting for a man she had almost claimed at twenty and had not yet touched again, cock and mouth and counter-steam ghosts riding Henry's careful sentences like contraband.

"You were there for parts of it," Henry said. Fingertips on the paperweight, firelight throwing a pale coin across pages. "Enough to know the cover. Enough to know why I sat a twenty-year-old girl in this room and asked her to become an exit wound so the boy would not learn how close the Shaw name came to swallowing itself. I told you silence would protect Jake. You left. We told him you wanted more than Somerton—bigger life, brighter rooms, a map that did not end at Market Street. Almost true. You were bright, restless, worthy of trains. Also a lie with a purpose. Purpose calcified. I mistook silence for love."

[player_name] tasted metal, old anger, pity she did not trust—and under it, shameless, body-memory of Jake at twenty: mouth, hands, the almost Henry's ask had interrupted before it became a claiming. She had practiced wanting more for fifteen years. In this room she practiced wanting Jake specifically—grown, scarred at the thumb, still hers in ways Henry's story never owned. Letter crackled in her pocket when she shifted; she did not take it out. She needed his mouth to do the work handwriting refused. Outside, rain sheeted yard into dark green and slate. House creaked confession-slow. Desire did not belong here. It lived anyway—second fire under the grate—because Jake kept walking through Henry's sentences like a man crossing a diner floor toward her cunt, and her body kept answering yes before her ethics finished the ledger.

"Jake has lived with a version of that night that never fit," Henry continued, eyes on the boyhood photograph—counter, half-hidden grin, grey eyes learning stillness. Looking at it dried [player_name]'s mouth: the boy she left, the man she would find at the blue door, the body she wanted before the night sanded her obedient again. "Your face on the station steps. My hand on your shoulder. Sorry that wasn't ambition. He tried to make pieces fit while he ran the diner and raised Clara after their mother stopped being reachable. I watched him practice the tidy sentence. Fail at night. Succeed in public. I told myself I was sparing him. What I spared was proper forgiveness—and the chance to know why the woman he wanted looked at him like a door he wasn't allowed to open. He wanted you. God help me, I knew. I sent you away anyway."

Soft footsteps. Clara in the kitchen doorway, sketchbook hugged, charcoal crescent on her knuckle, sixteen going on forty, allergic to unfinished stories. No apology for listening. She had earned the right the night she found the desk and refused to put the wrong paper back. Gaze flick over [player_name]'s rain-dark coat, flush at throat, refusal to sit—reading the room the way she read margins, including the heat [player_name] was failing to hide. "I found the ledger pages," Clara said, steady, sharp. "I found the note where he practiced what to tell Jake—ambition drafts, crossed-out almost-truths. Dates in my schoolbook margins where I sketched without knowing I was mapping a wound. I did not find you. He did that with a stamp." Sketchbook lifted. "I drew the gap before the papers named it. Rain. A car. Your silhouette on the station steps. Jake waiting—looking at you the way he still looks when he thinks no one is scoring him. Henry standing between. Charcoal doesn't lie as easy as uncles. Neither does a body. You came back smelling like you already know where you're going next—and it isn't only paper."

Henry's mouth twitched—smile, flinch. "She forced my hand. Without her I might have rehearsed until I died of carefulness. The letter was late courage. This—" room, papers, cold tea—"is late courage out of euphemism."

Confession thinned the air. Rain softened on glass. [player_name] walked to the table, looked under glass without lifting: dates, a winter name, Clara's charcoal edge—hands open as if dropping too much weight. She thought of Jake's hands: burn scar, register mint, how they would feel on her waist if she walked into the diner with open hands and let wanting finish what truth started; how his cock would feel if open hands became under his shirt, if Henry's speech bought her the right to be filthy and honest in the same night. Fifteen years of silence tried to climb her throat. She swallowed it. Clock. Log settling. Woodsmoke. Between her ribs—and lower—something hotter than anger kept time, slick and adult and done apologizing for arriving in a confession room.

"You asked me to leave so he would not see the whole of it," she said. "I did. I practiced wanting more until practice became a life. Cities rewarded it. Trains smelled like proof. Standing here, I am not sure who silence protected—Jake, you, or Somerton's neat story about itself. What I am sure of: I left a man I wanted, and the wanting did not die politely because you called it ambition. My body did not get the cover story memo. It still votes for him. It is voting now."

Henry inclined his head. Admission like furniture too heavy to polish—and for a flicker, something human: recognition that the girl he sent away had grown into a woman whose cunt still chose his nephew. "Then take what you will. Carry it to Jake as proof I finally spoke—debts, failed promise, cover, why I cast you as ambition instead of witness. He is at the diner. He does not know I mailed the letter for certain, though he suspects—always has. Go with open hands and let him decide whether my voice belongs when truth arrives. Open hands, [player_name], are not empty hands." Gaze to Clara, chin lifted, charcoal-brave. "Or doubt every word. God knows you've earned it. Look yourself. Clara will show the rest. Glove-box pages. The ones I still flinch naming. Drafts I kept off glass because even late courage has dark corners."

Clara stepped fully in. Charcoal dust on sleeve. Sketchbook soft-edged, margins crowded with blue door, rain, hands, half-inherited winter—and, private jolt, Jake's mouth in profile more than once, hunger drawn before Clara had a word for it. "I know where he tucked the rest. False panel in the desk. Envelope taped under the bottom drawer. Schoolbook he thought was only mine. Map instead of his speech, I'll give it. Jake first, I'll wait. I've waited. Another hour won't kill me. It might kill the tidy version. Good. And if you go to him—" ghost smile, not unkind—"go knowing he has wiped the same stretch of counter since dusk like a man waiting for a woman, not a rumor. Like a man who will get hard when you walk in smelling of our woodsmoke and finally tell him why."

Far off, diner closing-hour lived in [player_name]'s bones like a second clock—and second heat. Jake wiping counters, listening for her step, grey eyes holding weather, burn scar on cleaned laminate. Coffee steam. Cracked stool. Blue door sticking damp as loyalty—awkward, faithful, unwilling to swing easy. She pictured walking into that steam with Henry's confession warm on her tongue and her body already half-undone: open hands on Jake's chest, or open hands offering paper, either way close enough to smell his skin, close enough that truth might end with her back against the pie case and his mouth on her throat before Clara came downstairs. Henry waited. Clara waited. Papers held breath under glass. Boxwood dripped. Fire popped. Between [player_name]'s legs, traitorous and alive, the night voted Jake even while her mind still weighed the ledger—cunt shameless, wine-dark, adult.

Fork settled—not station, not Market Street, here where quiet was built. Believe Henry enough to find Jake with open hands: confession as gift and wound, late truth smelling of woodsmoke and fear, hands open meaning touch as much as paper, mouths finishing what the letter started. Or doubt him—Clara's sketches as map, refuse another Shaw man narrating her leaving, own hands on glove-box pages and flinching corners before offering Jake anything, even if delaying the diner meant another hour with desire banked and unanswered, thighs slick with unfinished wanting while charcoal led her through dark drawers. Neither soft. Both through rain toward a man who practiced losing her and a secret done hiding under glass—and toward a body she had not stopped wanting since the station steps at twenty, cock and cunt and trust braided into the same plot.

Henry's careful eyes. Clara's charcoal fingers tight on the sketchbook. Letter suddenly small in her pocket—three pages of weather that had only ever been a door. She breathed woodsmoke, lemon polish, mineral rain at the threshold, and under it imagined Jake's diner heat: her name in his mouth, hands stilling on the counter when she walked in, blue door sealing them into whatever came next—truth-telling that might turn into fucking if they earned it, or hunting paper that might turn into the same if she let herself go to him after. The quiet was not empty. It waited for her to choose how it broke: belief and open hands toward Market Street with her pulse already between her thighs, or doubt and Clara's map through the house's dark corners—desire humming either way, done pretending the story was only paper, hook set on the man and the hunger both.`,
  choices: [
    { id: "scene4e", text: "Believe Henry enough to go find Jake with open hands", textHot: "Believe him — find Jake with open hands and unfinished wanting" },
    { id: "scene4f", text: "Doubt him — search the house with Clara's sketches as a map", textHot: "Doubt him — hunt the house with Clara's map before you go to Jake" }
  ]
};
