export default {
  id: "scene8e",
  layer: 8,
  title: "Clara Chooses Audience",
  text: `Clara's room on Willow Lane smelled like charcoal dust, wet wool drying on the radiator, and the particular electricity of a younger sister who had decided the Shaw quiet would not outlive her twentieth birthday without a fight.

[player_name] stood just inside the doorway with John at her shoulder and rain still ticking the slate roof above them. Outside, wet boxwood pressed the kitchen windows downstairs where Henry's mantel clock kept a guilty, even time. Woodsmoke climbed the stairwell. Clara sat cross-legged on the unmade bed with photocopies fanned across the quilt—Voss's ledger lines, Henry's careful handwriting sanded into weather, her own charcoal circles drawn over dates like bruises that refused to fade. The glass weight from downstairs sat beside her knee like a borrowed gavel.

"I am not asking permission," Clara said. Her voice carried restless honesty and the graphite under her nails. "I am telling you who hears first. You brought me copies. You stood in Mae's light and Henry's kitchen and the diner with the blue door that sticks. Now I choose the audience, because I found the papers and I have been living inside this house while the quiet practiced itself into furniture."

John's burn scar whitened on the thumb that rested against the doorframe—not steering, present. Coffee still ghosted his coat from Market Street. "She means it," he told [player_name], low. "Clara does not invent stages for sport. She invents them because someone has to stop treating our father's death like a season instead of a decision Henry made with whiskey tea and a creditor's shadow."

[player_name] tasted rain and woodsmoke and the metallic bright of a secret that had traveled fifteen years in her chest and was now about to leave Clara's mouth into whatever room Clara named. Sensory first: charcoal grit on the quilt, radiator tick, rain on slate, boxwood wet against glass downstairs, the cracked counter stool leaning its half-degree left two streets away behind diner glass as if listening through weather. Emotion: pride in Clara braided to fear for John braided to the old copper habit of protecting him by disappearing. Plot: audience undecided; Henry alone with an empty mug; Mae's trays already rearranging memory; Voss's name under every photocopy like a coin waiting for a stamp.

"Who," [player_name] asked carefully, "and how loud?"

Clara sorted three stacks with charcoal-smudged fingers. "Option one: I take these to Mae and let the slots fill before lunch—Market Street hears winter was never only ice. Option two: I put John and Henry in the same kitchen and make Henry say it while I hold the pages so he cannot sand. Option three: I call the lawyer outside Somerton who already has the photographs and I let paper travel before gossip does. I have already chosen. I am telling you because you came home and because John deserves to watch me choose instead of finding out from eggs gone cold."

John stepped fully into the room. The floorboard that had always complained under his weight complained again, ordinary and devastating. "Say the name of the room," he said to his sister. Not unkind. Not soft. "Then let [player_name] decide whether she stands behind your verb or asks you to delay it for my sake. Both are loyalty. Neither is sanding. I will not love either of you less for the order of the burn."

Clara's eyes flicked to [player_name]—young, furious, tender in the way of someone who had drawn over guilt until the drawing became evidence. "I am taking John and Henry into the kitchen tonight," she said. "Not Mae yet. Not the lawyer's courier yet. Family first, but family without sand—pages on the table, woodsmoke in our lungs, mantel clock listening. I want Henry to look at John while he says ice and whiskey and Voss and the girl who left so the town could invent ambition. I want you there. And I want it now, before another midnight teaches this house that silence is furniture again."

Rain sheeted harder against Willow Lane. Downstairs, Henry coughed once—an old man sound that tried to be ordinary and failed. Coffee steam did not reach this far from Market Street, but [player_name] could smell the ghost of it on John's coat anyway, fryer hymn and blue door and the life he had rebuilt around a wound. Wet boxwood. Woodsmoke. Clara's charcoal. The particular hurt of watching a sister claim the stage you once abandoned.

"If you support her," John murmured for [player_name] alone, close enough that his breath warmed her temple, "you are accepting that Clara's timing becomes the family's timing—kitchen tonight, no pause for my softer courage, no inventing a delay that looks like care and tastes like another cover. If you ask her to delay for my sake, you are asking for hours or a day so I can stand inside the story before Henry's face finishes rearranging—time that might save me or spare Henry one more sanded morning. I can survive either. What I cannot survive is watching you pretend the choice is about manners."

[player_name] watched Clara's hands—steady, graphite-stained, the hands that had found papers under a glass weight and refused to tidy them back into innocence. "Supporting you scares me," [player_name] said aloud, honest. "Not because you are wrong. Because once Henry speaks in that kitchen with you holding the pages, there is no registered return. Asking you to delay for John is not protecting Henry. It is sequencing John's breath before the confrontation finishes landing. Both hurt. Both move."

Clara stood. The photocopies slid. One charcoal circle stared up like an eye. "Then stop explaining and choose," she said, almost gentle, which from Clara was sharper than shouting. "Support my choice even if it scares you—walk downstairs with me and put your body in the doorway so Henry cannot pretend this is still weather. Or ask me to delay for John's sake—and accept that delay has edges, and I will not hold forever, and I will not lie to Mae if she asks me a direct question tomorrow over stamps. Holding is not perjury. It is a pause with a sister's clock."

John's hand found [player_name]'s wrist, thumb on her pulse. "I rebuilt the diner," he said. "I raised Clara beside the lights. I listened for a train that might bring you back. I can hear Henry say the ugly words tonight with you beside me, or I can take one more day to put my hands flat on the truth before the kitchen becomes a stage. Do not invent a third road where Clara's courage goes soft because you still think my name is too fragile for his confession in the same hour."

Outside, freight complained toward the yard. Station platform hiss lived in memory. The blue door stuck two streets away. Gold lettering on Mae's window fogged and cleared with civic breath. Voss's shadow owned a corner of every page on the quilt. Henry's unfinished name trembled in the woodsmoke climbing the stair.

[player_name] tasted the fork bright behind her teeth. She thought of fifteen years of practiced belief—the girl who wanted more—and how Clara had drawn over that practice until the drawing became a blade. She thought of John under rain and under diner lights and under the particular weight of a nephew who had loved an uncle's weather too long. Ending the quiet meant feeding someone a true story. Timing the feed was the remaining hunger.

"If I support you," [player_name] told Clara, "I am not asking the kitchen to be kind. I am asking it to stop rehearsing Henry's season. If I ask you to delay for John, I am not sanding the pages. I am putting his pulse inside the order before the mantel clock hears the whole burn."

"Then choose," Clara said. She gathered the stacks into a folder that smelled like graphite and rain. "My lamp is on. His hand is on your wrist. Henry is downstairs pretending tea. The only question left is whether we walk into that kitchen while the fear is still honest, or whether we give John one more corridor of breath and accept what that corridor costs my patience."

John stroked once at [player_name]'s pulse—consequence, not comfort. Woodsmoke thickened. Wet boxwood tapped glass in the wind. Clara waited with charcoal under her nails and a stage already built in her mouth.

Freight complained again toward the yard, a long metallic complaint that made the radiator tick seem small. [player_name] thought of the station platform hiss from the night she left, of John's blue door sticking like a vow that needed force, of Clara at twelve asleep above diner lights while Henry sanded seasons into tea. Supporting Clara meant walking into that kitchen with the folder and letting the mantel clock hear ice without weather. Asking for delay meant buying John one corridor of breath that could save him or spare Henry another sanded morning—and Clara's clock would not pretend mercy forever. The rain on slate kept time like a second civic timer. Wet boxwood tapped the glass downstairs. Woodsmoke thickened until [player_name] could taste ash on her tongue beside the copper of old habit. John's thumb stayed on her pulse. Clara's folder waited. The doorway refused to become a softer room.

Support Clara's choice even if it scares you—or ask her to delay for John's sake. Willow Lane held its rain. The quiet of Somerton leaned in at the gutter to hear which loyalty she would feed first—the sister's stage, or the man's need for one more hour before the kitchen learned how loud truth could be when a girl with graphite fingers refused to tidy guilt into innocence again.`,
  textHot: `Clara's room on Willow Lane smelled like charcoal dust, wet wool, and the particular heat of a confession that had hitchhiked in [player_name]'s body from every unfinished night with John and was now about to leave a younger sister's mouth into a kitchen that still believed in tea.

[player_name] stood in the doorway with John crowded close behind her—coat open, chest to her back, already half-hard from the climb and the danger and the simple fact of Clara fanning photocopies across the quilt while his hand stayed possessive at [player_name]'s hip under her sweater. Rain ticked slate. Woodsmoke climbed. Clara looked up with graphite under her nails and eyes that missed nothing, including the way John's thumb stroked the bare skin above [player_name]'s waistband like a metronome timed to courage.

"I am not asking permission," Clara said. "I am telling you who hears first. Kitchen tonight—John, Henry, pages on the table, no Mae yet, no lawyer's courier yet. Family without sand. You brought me copies. Now you choose whether you stand behind my verb or ask me to delay it for John's sake while his hand finishes answering a question you have not spoken aloud."

John did not step back. His cock pressed a thick line against [player_name]'s ass through denim whenever he breathed, and he breathed like a man who refused to let family reckoning go celibate. "She means the kitchen," he said into [player_name]'s hair, loud enough for Clara, filthy enough for the pulse under his thumb. "Ice. Whiskey tea. Voss. Your yes at twenty. My grief as sanded season. Clara wants Henry to say it while she holds the pages. Support her even if it scares you—walk downstairs wet for me and put your body in the doorway. Or ask her to delay for my sake—and I will still fuck you against this doorframe after, because delaying the confrontation does not delay what your cunt has already decided about coming home."

[player_name]'s cunt ached from every unfinished Market Street almost—useful, braided to the threat. Her nipples peaked against lace when Clara's gaze flicked to John's hand and back without comment, only a raised brow that said she had drawn over worse heat with the ledgers. "I hear you," [player_name] said, steadier than the clench of her thighs. "Support your choice—full volume kitchen, full cost, no sand. Or ask you to delay for John—sequence his breath before Henry's face rearranges, loyalty not cover."

Clara stood, photocopies sliding, one charcoal circle staring up like an eye. "Holding is a pause with my clock," she said. "I will not hold forever. I will not lie to Mae tomorrow if she asks direct. Speak the verb."

John's hand slid fully under [player_name]'s sweater at the front then—palm spanning her ribs, thumb brushing the underside of her breast through the bra until she had to bite her lip to keep the sound off Clara's tidy stacks. Not a show for Clara. A claim for the choice. "Support her," he rasped against [player_name]'s ear, "and walk into that kitchen knowing I will keep my hand where it is until Henry's voice breaks. Or ask her to delay—hours, a day—and I will still take you upstairs after we put the pages away, because your loyalty to my softer courage does not make me soft. Both keep me hard. Both keep you from inventing a prettier lie in the shower."

[player_name] gripped the doorframe, charcoal-smell and radiator heat and John's cock and Clara's waiting folder braided into one bright fork. "I am not performing penance with his hand on my breast," she told Clara, voice rough. "I am deciding whether Henry hears us tonight while the fear is honest or whether John gets one corridor of breath before the mantel clock learns the whole burn. Support you scared—doorway, body, pages. Or delay for him—timed, edged, not sanded."

Clara's mouth tilted. "Sympathy is not my job. Stages are. Memory is. I remember finding papers under glass while this house pretended woodsmoke was enough. Choose loud. My lamp is on. His hand is already answering."

John shoved past [player_name]'s waistband just enough for two fingers to find cotton soaked through—humiliating under Clara's graphite honesty, honest as freight—and pressed once against her clit through the fabric, a brand aimed at decision not orgasm. "Pick," he whispered. "While Clara can still see you refuse to tidy. Support her choice even if it scares you—speak it and let me walk you downstairs shaking. Or ask her to delay for my sake—and keep shaking for me in private while her clock runs down. Standing here inventing a third audience while your cunt soaks my fingers is the only cowardice left on Willow Lane."

Freight hissed toward the yard. Coffee steam ghosted in memory from the diner. The cracked stool leaned. Wet boxwood tapped glass. Voss's coin. Henry's empty mug.

"If I support you," she breathed, "you do not soften the walk to the kitchen. You stay angry and hard and mine while Henry learns winter was never only weather. If I ask for delay, you do not waste the pause on his sanded tea—you help me put John inside the truth before your clock ends."

"Either exit," John promised, withdrawing his fingers slowly enough that rain almost covered the wet sound, catching her wrist instead with a sticky thumb on her pulse. His cock still pressed her. His mouth found the side of her neck—one open suck Clara absolutely saw and absolutely filed under restless honesty—and then he made space for the choice like a man who understood sister-stages and private heat could share a doorway without apologizing. "Support Clara even if it scares you. Or ask her to delay for my sake. I will not love you less. I will only need inside you after—against this frame, upstairs, wet boxwood in our coats—because watching you threaten a kitchen with honesty while wet for me is going to live in my body longer than any cover Henry ever sanded."

Clara inked nothing; she only hugged the folder like a held kiss with evidence in it. "Verb," she said. "Now. Boots muddy either direction."

[player_name] tasted copper and charcoal and woodsmoke and John. Rain sheeted Willow Lane. The blue door stuck two streets away. Freight complained. Her nipples ached. Her cunt throbbed with unfinished claim. Henry's name trembled unfinished downstairs. Clara waited. John's hand stayed on her wrist, warm, marked, refusing to steer, refusing to leave.

John rolled his hips once against her—helpless, then locked still—and breathed hard enough that Clara filed the sound under memory without lifting the folder. "I raised you beside diner lights," he told his sister, then softer into [player_name]'s neck, "and I can survive Henry's mouth tonight. What I cannot survive is watching [player_name] invent a softer stage because she still thinks my cock and my name are too fragile for confession in the same hour. Support you loud, or delay me timed. Do not invent a third road where nobody gets muddy."

[player_name] laughed once, wrecked, fogging nothing but her own courage. Wet boxwood lived in her coat. Woodsmoke. Clara's graphite. Voss's shadow. Henry's mantel clock. Fryer oil ticking in memory like a second timer. She covered John's hand through her sweater—not stopping him, calibrating—and faced Clara with her pulse arguing strategy in sticky thumbprints. "Delay is not sanding," she said. "It is sequencing. Supporting you now is not cruelty for sport—it is refusing another decade of practiced belief. Both hurt. Both move. Both keep his hand on me until the kitchen door sticks open for whatever comes after your pages."

Clara shifted the folder once, a paper whisper like punctuation. "Then spend the verb before Henry invents another cup of tea. My quilt does not care about your cunt or his vow. It cares about what leaves this room in which order. Speak."

Support Clara's choice even if it scares you—or ask her to delay for John's sake. [player_name] drew a breath that tasted like rain and graphite and the man behind her. Willow Lane held steady. The quiet leaned in at the gutter to hear which hunger she would feed first—the sister's stage, or the timed pause, or the heat that had turned a doorway into a reckoning she could feel in her pulse and her cunt and the place where apology used to live.

Freight complained again toward the yard, metallic and useless against the throb between [player_name]'s thighs. She thought of the station platform, of the blue door sticking, of every unfinished fuck that had braided wanting to courage until neither would go celibate for Henry's tea. Supporting Clara meant walking downstairs with John's cock still hard against her and the folder between them like a third pulse. Asking for delay meant buying him a corridor—then taking that corridor with her cunt still aching and his mouth on her neck until the clock Clara named ran down. Rain on slate kept filthy time. Wet boxwood tapped glass. Woodsmoke and charcoal and John's sticky thumb on her pulse made the doorway into a reckoning she could feel in her nipples and her throat and the place where apology used to live soft. Clara's folder waited. The night refused a softer room.

Choose. Clara's folder. John's thumb. The kitchen or the corridor. Somerton tracked mud either way and the night refused to land soft.`,
  choices: [
    { id: "scene9d", text: "Support her choice even if it scares you", textHot: "Support her choice scared — walk downstairs wet for him" },
    { id: "scene9b", text: "Ask her to delay for John's sake", textHot: "Ask her to delay for John — then take him against the doorframe" }
  ]
};
