export default {
  id: "scene5c",
  layer: 5,
  title: "Debt Before Dawn",
  text: `Thunder had moved off toward the ridge and then circled back, as if Somerton were not done listening. Rain still sealed Market Street into impassability; the blue door remained locked, the CLOSED sign crooked on its suction cup, the cracked stool by the register a witness excused from the booth and still somehow attentive. Fluorescent half-light pooled on laminate scarred by a generation of elbows and wet receipts. Coffee had gone cold hours ago in the mugs they had cradled through the first tellings. Tea Clara had left—blessing and boundary—had steeled itself into bitterness in two unmatched cups. Blankets waited in a soft heap on the vinyl, smelling faintly of the upstairs closet and of a sister who understood storms. Outside, slate roofs dripped without mercy. Inside, [player_name] and John sat in the back booth with Henry's letter between them like a map with half the streets still unnamed—and the demand she had made at the start of the dark still living in the air like heat: truth first. No kiss on a hollow floor. No softness stolen from a lie.

Dawn was only a rumor at the windows, a thinning of black into bruised blue that made the rain look silver and then steel. The storm had not finished its work. The roads toward the ridge and Willow Lane were still a river by Clara's last radio report, flash-flood warnings cycling through the tinny speaker like a hymn nobody had asked for. Henry had called the landline once, voice careful even through static, and Clara had told him the diner was closed and the hill was water. He could wait until morning like the rest of them. Waiting, [player_name] understood now, was ending. Morning was arriving whether anyone was ready to greet it with clean hands.

She set her palm flat on the softened pages of the letter—train-smell, rain-smell, the heat of her own pocket—and then moved the letter aside. Paper was not enough. The night required a number and a name spoken aloud before first light could sand anything soft. Sensory first, always, the way this town taught its stories: the continuous hush of rain on the roof; the soft metal smell of the grill as it ticked toward cold; the particular quiet of a diner emptied by weather; the faint ghost of fryer oil that lived in the walls like a second paint. Then emotion, rising through the senses: shame metallic as a swallowed coin; resolve hot enough to steady her voice; tenderness for the man across from her who had agreed to lose the soft hour rather than wake still guessing. Then the plot turn, spoken into fluorescent honesty without theater.

"The winter debt," [player_name] said. Her voice did not shake. She had practiced shaking in quieter rooms for fifteen years; tonight she practiced the opposite. "Not the town version. Not Henry's kindness version. The one that lived in the glove box and in my leaving—and in the letter he wrote around the wound."

John's grey eyes held hers across the smaller distance of a booth that had learned the shape of their knees and the patience of their hands. He did not reach for her. He had learned, through the long rain, that reaching was a question she answered when truth had room to sit between them. The burn scar at the base of his thumb caught the half-light when he flexed his fingers against the laminate and waited, diner-owner calm cracked along a true fault, boy and man both listening.

"Forty-eight thousand first," she said. "Your father owed a man named Voss. Not a bank with polite letters and late fees that arrived in windowed envelopes. Voss. Loans that climbed behind jokes and overtime and the kind of pride that thinks a handshake can outrun winter. The night of the ice—he should not have been driving with that weight on him. Henry told anyone who asked that it was weather. Weather was the stage. The debt was the script. I was in the room when Henry said the quiet part: if the story went wide, Voss would not stop at money. Reputations. The diner. Clara still small enough to be used as leverage in sentences that made Henry's hands shake around a whiskey he did not finish."

John's jaw tightened until she saw the muscle jump. He did not look away. Rain hammered harder for a stretch, as if the roof itself were applauding the ugliness of accuracy. "Clara found a name," he said carefully, voice low—the tone he used when a ticket was wrong and he would not shame anyone until the rush ended. "She would not say it until you were real and not a rumor on Market Street. Voss. She said there were receipts. An exchange number. I told myself I would wait for morning to ask. Morning is here early."

"Voss," [player_name] repeated, and the name tasted like old coins and station cold and the particular fear of a twenty-year-old girl being asked to become a story. "Henry paid what he could from what was left after the funeral costs and the silence costs. Settled in kindness—that phrase is his handwriting and his religion. Kindness meant my suitcase on the boards and a speech about wanting more than Somerton, brighter rooms, longer maps, a life big enough to explain an absence. Kindness meant you standing in the rain after the train left, practicing belief because belief was the only way to keep this diner open and Clara fed and your hands from breaking things that could not be mended with a wrench. Kindness meant I said yes when he asked me to become absence so the Shaw name would not have to wear ruin in public while you were still learning how to be the man who stayed." She swallowed. Coffee-ghost and tea-bitter on her tongue. The blue door shivered in a gust and held. "There was more after the forty-eight. Twelve thousand more, counted in a ledger Clara has seen and I once glimpsed. Terms that were not only money. Threats if the truth went wider than Willow's kitchen. Henry kept an exchange number on the back of a receipt like a relic and a weapon. Clara has circled it. I saw it in his desk the week I left, when he thought I was already halfway to the platform with my lines memorized. I memorized the number too—because I was terrified and stupidly thorough, and because some part of me knew I might need to dial a ghost someday. I still know it."

John exhaled as if he had been underwater with her since the letter first arrived in her distant mail. He dragged both hands down his face and let them fall. "Say the number," he said. Not cruel. Necessary. The demand answering her demand, honesty for honesty. "If it lives in your mouth, let it live in this room. Then we decide whether we wake Henry with it while the hill is still wet—or whether we dial the ghost ourselves from the diner phone before dawn finishes making cowards of people who have already been brave for one night."

[player_name] recited it. Digits old as a bruise, shaped like an exchange that might be dead, rerouted, sold, or still answering with a voice that remembered the Shaw name the way creditors remembered blood. Saying them felt like opening a door that stuck in damp weather—awkward, faithful to a past that did not deserve fidelity, necessary anyway. John closed his eyes once. Opened them. Something in his face settled into the particular calm he wore when the grill flared and the ticket rail filled: work ahead, no time for theater, hands ready.

"I am angry," he said, and the words were familiar from earlier in the storm, worn smoother now by hours of shared weather and withheld kisses. "At Henry for the shape of his mercy. At Voss for existing. At my father for carrying silence like a second passenger on a road that wanted one. At myself for swallowing the town's neat sentence because it kept the lights on over Clara's homework." He looked at her—really looked, as if the confession had changed the light on her face and he intended to learn the new topography. "Not at you for saying it. You demanded truth before any closeness. You are delivering before dawn. Glad is still not soft. It is still true. I would rather hear this from you in a locked booth than find it sanded in Henry's desk after another fifteen years."

Lightning did not come. The storm had spent its white hours ago. What remained was rain and the slow bruise of almost-dawn and two people deciding what to do with a number that could wake an uncle or a creditor before the hill remembered how to be a road. Somewhere upstairs a floorboard creaked—Clara turning in sleep, or listening despite headphones, or simply the old building agreeing that night was ending. Wet boxwood waited on Willow Lane. Woodsmoke would be rising from Henry's chimney even now, habit of a man who could not sleep while the quiet broke elsewhere. The mantel clock would be counting toward a morning he had tried to postpone with careful ink.

John rose, joints stiff from the long sit, and checked the front latch out of habit older than the secret. The blue door held. Market Street was a dark river of slate and drowned leaves. He came back and stood at the booth's edge rather than sitting, as if standing made the next choice clearer, as if height could turn dread into a plan. "Willow will still be wet. The ridge warning may lift with first light enough for the truck if we take it slow. We could drive up and wake Henry with the number on our tongues—make him hear it in his own hallway smelling of polish and boxwood and woodsmoke, where he cannot pretend the diner's weather diluted the digits." His voice dropped, steady as a poured coffee. "Or we use the landline here. Old diner phone by the pie case. Call the exchange. See who answers when the Shaws stop running. Clara said not to sand anything soft just because the storm made us feel temporary. Temporary is how we got the lie. This—" he tapped the air where the digits still seemed to hang between them like wire "—is the opposite of temporary. So is the fact that you stayed through the rain to say it."

[player_name] felt the old fork in the road settle differently again: not station versus Willow, not spark versus silence, but debt spoken before dawn and the stance of what to do with its echo. She smelled rain and cold tea and the fryer hymn that never fully left the walls. She thought of Henry waiting behind his glass paperweight, of Clara's charcoal hands upstairs, of John's burn scar and his refusal to steal softness on a hollow floor. The quiet of Somerton had cracked in a booth overnight. Now it asked whether the next break belonged to an uncle's sleep or a ghost on the line—and whether [player_name] had the courage to choose the instrument of the breaking while first light bruised the glass and the blue door held like loyalty: awkward, faithful, unwilling to swing easy until someone decided it must.`,
  textHot: `Thunder had moved off toward the ridge and then circled back, as if Somerton were not done listening. Rain still sealed Market Street; the blue door remained locked; the CLOSED sign hung crooked; the cracked stool waited like a witness excused and still somehow flushed with what it had overheard. Fluorescent half-light pooled on laminate. Coffee cold. Clara's tea bitter in unmatched mugs. Blankets in a soft heap that had warmed their shoulders, then their hips, when talk ran long and wanting refused to leave the room simply because truth had been invited to sit first. Outside, slate dripped. Inside, [player_name] and John sat close enough that his thigh pressed hers—deliberate, electric, a vow written in heat under the demand that had started the dark: truth first. No kiss on a hollow floor. No taking what her eyes still offered while her mouth said not yet.

Dawn was a rumor, bruised blue at the windows that made the rain look like wire. The storm had not finished. Willow roads were still river. Henry had been told to wait. Waiting was ending—and so was the particular sweet torture of overnight honesty with a man whose body had stayed hard and patient while his mouth stayed clean, whose hand on her knee had traced slow circles through denim for hours without climbing higher than she allowed, who had leaned in close enough to warm her cheek with his breath and still not stolen the kiss.

She set her palm on the letter, then moved it aside. Her other hand found John's knee above the joint where his palm had lived. She felt him tense, felt want leap under her fingers, and she did not pretend absence. Sensory first: rain's hush; grill-metal tick; the heat of his leg; the throb low in her belly where denial had become its own long foreplay; the smell of his skin when he shifted closer. Emotion: shame metallic; resolve hot; hunger shameless beside honesty; tenderness sharp enough to hurt. Plot turn, spoken rough.

"The winter debt," [player_name] said. Voice steady. Roughened by sleeplessness and by the nearness of the mouth she had refused and still wanted on her throat. "Not the town version. Not Henry's kindness. The one that lived in the glove box and in my leaving—spoken now, before dawn, before I let myself take what your hands have been offering all night like a man keeping a vow with his body."

John's grey eyes darkened until the fluorescent half-light could not find their bottoms. He did not pull her into his lap, though she saw the thought cross his face. He had learned that waiting was part of the claiming. The burn scar flexed. "Say it," he murmured. "All of it. I can want you and hear ruin in the same breath. I have been practicing both since you caught my wrist and said not yet like the filthiest kind of promise."

"Forty-eight thousand first." She kept her hand on his knee while she spoke, a tether. "Your father owed Voss. Not a polite bank. Voss. Loans behind jokes and overtime until the jokes died. The ice night—he should not have been driving with that weight. Henry called it weather for anyone who asked. Weather was the stage. Debt was the script. I heard the quiet part in Willow's kitchen: if the story went wide, Voss would not stop at money. The diner. Clara used as leverage in sentences that made Henry's hands shake around whiskey he did not drink."

John's jaw jumped. Under the table his hand covered hers and squeezed—grief, gratitude, want braided so tight she felt all three in her wrist. Rain hammered. "Clara found the name. She waited until you were real. Receipts. An exchange number. I told myself morning. Morning came early because you are brave and I am done being sanded."

"Voss." The name tasted like old coins and station cold and his pulse under her palm. "Henry paid what he could. Settled in kindness—his phrase, his religion. Kindness meant my suitcase and a speech about wanting more than Somerton. Kindness meant you believing in the rain so this diner stayed lit and Clara ate. Kindness meant I said yes to becoming absence so the Shaw name would not wear ruin while you learned how to stay." She swallowed. Felt his thumb stroke her knuckles in a rhythm that was not innocent and not hidden. "There was more. Twelve thousand. Terms not only money. Threats. Henry kept an exchange number like a relic and a weapon. Clara circled it. I saw it the week I left. I memorized it because I was twenty and terrified and thorough. I still know it. I am giving it to you before I give you my mouth. That order is the only way I can walk into wanting you without becoming the lie again."

John exhaled a sound that was half groan, half prayer, entirely adult. "Say the number." Necessary. Rough. Ruined-soft. "If it lives in your mouth, let it live in this room beside how badly I want that mouth on mine. Then we decide—wake Henry with it, or dial the ghost from the diner phone before dawn makes cowards of people who have already been brave. Either way, after the choice, I am going to ask whether truth has earned me the right to touch you the way I have ached to since you stopped my hand—under your shirt, between your legs, my name against your throat while the rain witnesses what honesty unlocked."

[player_name] recited the digits. Old as a bruise. Saying them felt like opening a stuck door while his hand burned on hers. John closed his eyes, opened them, calm settling over hunger without erasing it—if anything the calm made the hunger more precise. His hand slid an inch higher on her thigh, still over denim, still waiting on a fuller yes, thumb pressing a promise into muscle.

"I am angry," he said. "At Henry. At Voss. At my father. At myself for swallowing neat sentences to keep lights on." He looked at her as if confession had changed her face—and as if her courage had gone straight into his blood. "Not at you. You demanded truth before a kiss. You are delivering while I sit here hard and grateful and wrecked with wanting. Glad is not soft. Wanting you this much while you hand me a creditor's number is also not soft. Both are true. Both are staying in this booth until we choose the next break."

The storm had spent its lightning. Rain and almost-dawn remained. Two people and a live-wire number. Somewhere upstairs Clara turned—headphones, papers safe from drip, privacy granted like a blessing with teeth. Willow waited with boxwood and woodsmoke and Henry's sleepless chimney. John rose, stiff with more than sitting, checked the blue door's latch, returned to stand at the booth's edge. Gaze dropped to her mouth. Lifted. Honest.

"Willow will still be wet. We could take my truck at first passable light and wake Henry with the number still hot on our tongues—make him hear it in his hallway of polish and boxwood where diner weather cannot dilute it." Voice dropped, intimate as fingers under cotton. "Or we use the landline by the pie case. Call the exchange. See who answers when the Shaws stop running. Clara said not to sand soft because storms feel temporary. Temporary made the lie. This number is the opposite. You are the opposite." His knuckles brushed her cheek—permission earned by syllables, heat earned by restraint. "Tell me which ghost we dial. Then tell me if the truth you just spoke has unlocked the rest of what my body has been offering—or only the next hour of work before I get to put my mouth where my patience has been living."

[player_name] leaned into his knuckles. She smelled rain and cold tea and his skin and the musk of a night spent wanting without taking. She thought of Henry behind glass weights, Clara with charcoal and headphones, John's burn scar and the patient ache of his body through clean denial. The quiet had cracked in a booth. Now it asked whether the next break belonged to an uncle's sleep or a creditor's line—and whether her spoken debt had finally made room for his hands without betraying the demand that had started the dark. She turned her face and pressed a brief kiss to his knuckles—not the mouth he wanted, not yet, a brand of gratitude and delayed fire that made his breath hitch. "Work first," she whispered against his skin. "Then, if we survive what the number wakes, you can ask me again with fewer clothes between the question and the answer. I am done pretending I do not want that. I am also done letting want rearrange the order of the truth."

John nodded, eyes shut for a heartbeat as if praying to a god who ran diners and kept vows. "Work first," he agreed, wrecked and willing. "Dial or drive. Your stance. My truck or my phone. Either way I am beside you when the quiet finishes breaking."

Dawn pressed thinner blue against the glass. The number waited like wire. So did he—hard, grieving, ready to drive or dial, ready to kiss her senseless the moment she said the truth had done its work.`,
  choices: [
    { id: "scene6d", text: "Drive to Willow and wake Henry with the number", textHot: "Drive to Willow and wake Henry with the number still hot on your tongue" },
    { id: "scene6e", text: "Call the creditor's old exchange from the diner phone", textHot: "Call the creditor's old exchange from the diner phone — end the shadow aloud" }
  ]
};
