export default {
  id: "scene7h",
  layer: 7,
  title: "Tell Mae",
  text: `Mae's post office smelled like wet paper, ink pads, and the particular curiosity of a woman who had sorted Somerton's secrets into slots for thirty years and called the sorting civic duty.

[player_name] stood on the rain-dark mat with John half a pace behind her left shoulder and the gold lettering POST OFFICE fogging and clearing with each breath of warm air from the radiators. Outside, Market Street dripped. The diner's blue door stuck two storefronts back like a promise that needed force. Coffee steam ghosted from the vent even under the CLOSED sign. Inside Mae's rectangle of light, early stamps waited in tidy trays, and Mae herself—grey braid, cardigan the color of old receipts, eyes that missed nothing—looked up from a stack of forwarded mail as if she had been expecting this particular confession since the freight horn last complained toward the yard.

"Well," Mae said. Not unkind. Not soft. "The Shaw quiet walked in wearing rain. Wipe your boots. Then tell me whether you came to mail something or to make me an accomplice before breakfast."

John's burn scar whitened on the thumb that brushed [player_name]'s coat sleeve—not steering, present. Wet boxwood still clung faintly from Willow. Woodsmoke lived in both their coats. Clara's charcoal circles lived in the margins of papers under a glass weight across town. Voss's shadow owned a corner of a ledger Henry could no longer sand into innocence. And here, under Mae's lamp, [player_name] tasted copper and rain and the metallic bright of a public knife she had threatened in Henry's kitchen and was finally putting into a hand that stamped other people's lives for a living.

"I came to tell you the truth Henry arranged into weather," [player_name] said. Her voice carried station platform memory and fifteen years of brighter rooms. "John's father went through the ice. Henry had been drinking what he called tea. There was a creditor—Voss—already circling. Henry asked me, at twenty, to leave so the town could invent ambition for my exit and keep the Shaw name polite. I said yes. I left. The cover held until Clara found papers and Henry's letter cracked what was left. I am done letting Market Street practice a cleaner grief than the one it earned."

Mae set down her stamp without looking away. Rain needled the window glass behind the gold lettering. A delivery truck hissed past toward the freight yard, ordinary Somerton continuing without permission. "That is a heavy mailing," Mae said carefully. "If I put it in the slots—if I let it travel the way news travels here, through eggs and pie cases and the women who remember who wrote whom—you will not get it back. Gossip is not a registered letter. It does not return to sender. You understand I am not only Mae when I hear this. I am the town's first honest ear, and honest ears in Somerton have never been private."

John shifted closer, coat brushing [player_name]'s. Coffee on his breath. Clean work-sweat under woodsmoke. "She understands," he said, low. "We walked here under the hardware awning with the threat still hot. She can own the town's noise as the cost of ending the quiet—or she can ask you to hold it forty-eight hours while we finish Henry and Clara before the chorus starts chewing. Both are verbs. Neither is a stamp she gets to unstick later."

[player_name] watched Mae's hands—ink-stained, steady, the hands that had forwarded her first letters out of Somerton and never asked aloud why the girl who wanted more never wrote the boy at the diner. Sensory first: wet paper, radiator tick, rain on slate beyond the glass, fryer oil ghosting from next door. Emotion: fury braided to tenderness braided to the fear of becoming entertainment before justice finished landing. Plot: truth spoken into Mae's light; duration of Mae's silence undecided; Henry alone with an empty mug; Clara waking toward graphite; Market Street regulars an hour from eggs and questions.

"I am not performing penance for your trays," [player_name] said. "I am refusing to let Henry be the only audience for a truth that damaged a whole town's memory of what winter cost. If I ask you to hold it forty-eight hours, I am buying family time with civic delay—time to put John and Clara inside the story before the pie case turns it into sport. If I tell you to let it travel now, I am owning the gossip as the price of killing the quiet, and I need you to stamp that choice without sanding it into sympathy."

Mae's mouth tilted—not quite a smile. "Sympathy is not my job. Slots are my job. Memory is my job. I remember who sent flowers when John's father died and who sent casseroles and who asked whether the ice was really ice. I remember you buying a ticket with rain in your hair and Henry standing too still on the platform like a man holding a script. If you release this now, those memories rearrange by noon. If you ask me for forty-eight hours, I will hold—because I have held worse for less honest people—but I will not hold forever, and I will not lie if someone asks me a direct question over the counter. Holding is not perjury. It is a pause with a clock."

John's hand found [player_name]'s wrist under the counter edge, thumb on her pulse. "Forty-eight hours is enough to wake Clara into the truth before Mae's slots do it for us," he murmured for her alone. "It is also enough for Henry to invent another softer morning if we waste it. Owning the gossip now means eggs go cold while someone asks whether my father died on ice or on a lie—today, not after we have sanded our own courage into strategy. I will stand with either cut. I will not love you less for the town's noise or for the pause. I will only ask that you choose while Mae's lamp is still on us and not invent the decision in the shower later."

Outside, rain sheeted harder against Market Street. The cracked counter stool leaned its half-degree left behind diner glass, listening through weather. Wet boxwood waited on Willow with Henry's paperweight and pages that tried to tidy guilt into innocence. Clara's restless honesty waited upstairs in a house that smelled like fear dressed as patience. Voss's name sat under [player_name]'s tongue like a coin Mae could stamp into public circulation or hold in a drawer for two days like registered danger.

Mae leaned her elbows on the counter, braid sliding forward. "Speak the verb for me," she said. "Own the town gossip as the cost of truth—walk out of here knowing I will not stop the slots from filling with what you just poured into this room. Or ask me to hold it forty-eight hours—family first, chorus later—and accept that holding has edges and I will not pretend the edges are mercy forever. Either way, wipe your boots again on the way out. Somerton tracks mud either direction."

[player_name] tasted the fork bright behind her teeth. She thought of the threat spoken in Henry's kitchen with woodsmoke in her lungs. She thought of John under the hardware awning refusing to let fear go celibate of consequence. She thought of fifteen years of practiced belief—the girl who wanted more—and how Mae's trays had helped the practice become nearly civic virtue. Ending the quiet meant feeding the town something true. Timing the feed was the remaining blade.

"If I own the gossip," [player_name] said, "I am not asking the town to be kind. I am asking it to stop rehearsing Henry's weather. If I ask for forty-eight hours, I am not protecting Henry. I am sequencing Clara and John before the eggs, and I need that sequence to be loyalty rather than another quieter cover."

"Then stop explaining and choose," Mae said, almost gentle, which from Mae was sharper than shouting. "My lamp is warm. My stamp is ready. My memory is already rearranging whether you like it or not. The only question left is whether the town hears before lunch or after two midnights have taught the Shaw house what to do with unbroken silence."

John's thumb stroked once at [player_name]'s pulse—consequence, not comfort. Coffee steam ghosted through the shared wall. Freight complained toward the yard. The blue door stuck. Gold lettering fogged. Henry's unfinished name trembled in the woodsmoke of memory. Mae waited with ink on her fingers and a clock that was not Henry's mantel and somehow worse—civic time, public time, the kind that did not care who needed soft landings.

[player_name] drew a breath that tasted like wet paper and old coins and coffee and the courage of ending a quiet that had outlived its mercy. Mae's stamp hovered. The morning refused to land soft.

Own the gossip. Or ask her to hold. The post office lamp held steady. The quiet of Somerton leaned in at the gutter to hear which hunger she would feed first—the town's appetite for a true story, or the family's need for two midnights before the chorus learned their names.`,
  textHot: `Mae's post office smelled like wet paper, ink pads, and the particular heat of a confession that had hitchhiked in [player_name]'s body all the way from Henry's kitchen and the hardware awning where John's fingers had already taught her that public knives could live in the same bloodstream as wanting.

She stood on the rain-dark mat with John crowded close behind her—coat open, chest to her back, already half-hard from the walk and the danger and the simple fact of her putting truth into Mae's light while his hand stayed possessive at her hip under her sweater. Gold lettering fogged. Radiators ticked. Mae looked up from forwarded mail with eyes that missed nothing, including the way John's thumb stroked the bare skin above [player_name]'s waistband like a metronome timed to courage.

"Well," Mae said. "The Shaw quiet walked in wearing rain and something less polite. Wipe your boots. Then tell me whether you came to mail a secret or to make me an accomplice before your boy finishes marking you through your coat."

John did not step back. His cock pressed a thick line against [player_name]'s ass through denim whenever he breathed, and he breathed like a man who refused to let civic duty go celibate. "She came to tell you what Henry arranged into weather," he said into [player_name]'s hair, loud enough for Mae, filthy enough for the pulse under his thumb. "Ice. Whiskey tea. Voss. Her yes at twenty. Ambition as cover. My grief as sanded season. She is done. Now she chooses whether you let it travel the slots today or hold it forty-eight hours while we finish the family burn."

[player_name]'s cunt still ached from the awning—unfinished, useful, braided to the threat. Her nipples peaked against lace when Mae's gaze flicked to John's hand and back without comment, only a raised brow that said she had sorted worse heat with the mail. "I am telling you the truth," [player_name] said, steadier than the clench of her thighs. "John's father went through the ice. Henry drank. Voss circled. Henry asked me to leave. I said yes. Clara found papers. The quiet is cracking. If I own the town gossip as the cost of truth, you stamp this into circulation and eggs go cold by noon. If I ask you to hold forty-eight hours, you pause—not perjure—while we put Clara and John inside the story before the pie case turns us into sport."

Mae set her stamp down. Rain needled the glass. "Gossip is not registered mail," she said. "It does not return to sender. Holding is a pause with a clock. I will not lie if asked direct over the counter. Speak the verb."

John's hand slid fully under [player_name]'s sweater at the front then—palm spanning her ribs, thumb brushing the underside of her breast through the bra until she had to bite her lip to keep the sound off Mae's tidy trays. Not a show for Mae. A claim for the choice. "Own it," he rasped against her ear, "and walk out of here wet for me knowing the town will chew by lunch while I keep my hand where it is until we hit the blue door. Or ask her to hold—forty-eight hours, family first—and I will still fuck you against the pie case after we wake Clara, because delaying the chorus does not delay what your cunt has already decided about coming home."

[player_name] gripped the counter edge, ink-smell and radiator heat and John's cock and Mae's waiting stamp braided into one bright fork. "I am not performing penance with his hand on my breast," she told Mae, voice rough. "I am deciding whether Market Street hears before we finish Henry or after two midnights teach the Shaw house what unbroken silence costs. Own the gossip—full volume, full cost, no sand. Or hold forty-eight hours—sequence Clara and John before the eggs, loyalty not cover."

Mae's mouth tilted. "Sympathy is not my job. Slots are. Memory is. I remember your ticket and Henry's still platform face. Choose loud. My lamp is warm. His hand is already answering a question you have not finished asking."

John shoved past her waistband just enough for two fingers to find cotton soaked through—humiliating under gold lettering, honest as freight—and pressed once against her clit through the fabric, a brand aimed at decision not orgasm. "Pick," he whispered. "While Mae can still see you refuse to sand. Own the town's noise as the price of killing the quiet—speak it and let me walk you out shaking. Or ask her to hold forty-eight hours—and keep shaking for me in private while the clock she names runs down. Both keep me hard. Both keep you from leaving with a prettier lie. Standing here inventing a third stamp while your cunt soaks my fingers is the only cowardice left on Market Street."

A delivery truck hissed past. Coffee steam ghosted through the shared wall from the diner. The cracked stool leaned. Wet boxwood waited. Woodsmoke. Clara's charcoal. Voss's coin. Henry's empty mug.

"If I own it," she breathed, "you do not soften the walk to the blue door. You stay angry and hard and mine while the town learns winter was never only weather. If I ask for forty-eight hours, you do not waste the pause on Henry's sanded morning—you help me put Clara inside the truth before Mae's clock ends."

"Either exit," John promised, withdrawing his fingers slowly enough that rain almost covered the wet sound, catching her wrist instead with a sticky thumb on her pulse. His cock still pressed her. His mouth found the side of her neck—one open suck Mae absolutely saw and absolutely filed under memory—and then he made space for the choice like a man who understood civic light and private heat could share a room without apologizing. "Own the gossip as the cost of truth. Or ask Mae to hold it forty-eight hours. I will not love you less. I will only need inside you after—upstairs, pie case, wet boxwood—because watching you threaten a town with honesty while wet for me is going to live in my body longer than any cover Henry ever sanded."

Mae's stamp hovered over an ink pad like a held kiss with bureaucracy in it. "Verb," she said. "Now. Boots muddy either direction."

[player_name] tasted copper and wet paper and coffee and John. Rain sheeted Market Street. Gold lettering fogged. The blue door stuck. Freight complained. Her nipples ached. Her cunt throbbed with unfinished awning heat. Henry's name trembled unfinished in woodsmoke memory. Mae waited. John's hand stayed on her wrist, warm, marked, refusing to steer, refusing to leave.

John rolled his hips once against her—helpless, then locked still—and breathed hard enough that Mae filed the sound under memory without lifting her stamp. "I rebuilt that diner around a wound," he murmured into [player_name]'s neck, loud enough for the counter. "I can survive eggs gone cold. What I cannot survive is watching you invent a softer stamp because you still think my cock and my name are too fragile for gossip in the same hour. Own it loud, or hold it timed. Do not invent a third road where nobody gets muddy."

[player_name] laughed once, wrecked, fogging the gold lettering. Wet boxwood lived in her coat. Woodsmoke. Clara's graphite waiting. Voss's shadow. Henry's empty mug and mantel clock. Fryer oil ticking next door like a second civic timer. She covered John's hand through her sweater—not stopping him, calibrating—and faced Mae with her pulse arguing strategy in sticky thumbprints. "Forty-eight hours is not sanding," she said. "It is sequencing. Owning gossip now is not cruelty for sport—it is refusing another decade of practiced belief. Both hurt. Both move. Both keep his hand on me until the blue door sticks open for whatever comes after your stamp."

Mae inked the pad once, a wet click like punctuation. "Then spend the verb before the regulars start rattling the diner latch. My trays do not care about your cunt or his vow. They care about what leaves this counter in which order. Speak."

Own the town gossip as the cost of truth—or ask her to hold forty-eight hours while family burns first. [player_name] drew a breath that tasted like rain and old coins and ink and the man behind her. The post office lamp held steady. The quiet leaned in at the gutter to hear which hunger she would feed first—the town's appetite, or the two-midnight pause, or the heat that had turned a public stamp into a reckoning she could feel in her pulse and her cunt and the place where apology used to live.

Choose. Mae's stamp. John's thumb. The chorus or the clock. Somerton tracked mud either way and the night-morning refused to land soft.`,
  choices: [
    { id: "scene8k", text: "Own the town gossip as the cost of truth", textHot: "Own the gossip wet for him — let the town chew by noon" },
    { id: "scene8l", text: "Ask Mae to hold it forty-eight hours", textHot: "Ask Mae to hold forty-eight hours — then take him against the pie case" }
  ]
};
