export default {
  id: "scene5d",
  layer: 5,
  title: "Rain First",
  text: `The rain did not ask permission to keep them. It simply continued—slate roofs singing, Market Street drowned, the ridge road a rumor of water—until asking John to hold her through it felt less like postponement and more like the only honest weather left in Somerton.

[player_name] had demanded truth before closeness. She had meant it. She still meant it. But dawn was hours of thunder away, Clara had gone upstairs with headphones and a warning not to sand anything soft, and the blue door was locked against a town that had gone underwater for the night. Henry's letter lay between their coffee mugs like a third presence. The cracked stool leaned its half-degree left. Fluorescent half-light made everything look both tender and exposed. And [player_name], who had caught his wrist before his palm met her cheek, turned her hand in his and said the other true thing.

"Hold me through the rain first," she whispered. "Not as forgetting. As surviving until first light. At dawn I will ask for every unfinished room in the winter story. Tonight I am asking for your arms before my courage spends itself entirely on paper."

John's breath left him in a sound that was almost a laugh, almost a prayer. Grey eyes searched her face as if measuring whether the request undid the demand or completed it. "Truth at first light," he repeated, sealing the bargain. "No sanding. No Henry's careful weather. The whole cover story—or as much of it as either of us owns—when the windows go pale." His burn scar brushed her knuckles as he stood and drew her up with him. "Until then, I hold you. Properly. Not as a guest. As the woman who made honesty the price of my mouth and is still choosing to stay in the storm."

They left the booth without leaving the diner. John killed the front fluorescents until only the kitchen pass glow and the pie case's soft light remained, turning the room into something quieter than commerce. Rain became the loudest thing. He pulled the blankets Clara had brought into a nest on the long bench of the back booth—vinyl and wool and the smell of upstairs cedar—and then he sat and opened his arms with a simplicity that undid [player_name] more thoroughly than any speech.

She went into them.

Sensory first: the solid heat of his chest through his shirt; rain-cool cotton; the clean scent of his throat when she tucked her face there; the fryer hymn faint in the walls; his heartbeat under her ear, steady as a ticket rail. Then emotion: relief so sharp it stung; desire present and deliberately unfinished; the fierce gladness of being held by the man she had left to protect; fear of dawn braided with hunger for it. Then the plot turn, soft as a blanket pulled higher: overnight was no longer only talk. Overnight had become a body choosing another body as shelter while the secret waited like weather on the other side of glass.

John's hand moved slow circles on her back. Not climbing. Not demanding. Mapping. "Tell me something that is not the debt," he murmured into her hair. "Something from the years. A kitchen that did not smell like this one. A morning you almost bought a ticket home and did not. I will tell you about the lean years and the night Clara found the desk and the way the blue door sticks every November like it is trying to teach me patience."

So they traded small truths while the rain held the larger ones at bay. [player_name] told him about cities that never smelled like wet boxwood, about apartments where the quiet was empty instead of conspiratorial, about practicing ambition until the practice calcified and still waking with Somerton rain in her dreams. John told her about raising Clara beside diner lights, about learning to cook grief into specials, about standing in this same booth on anniversaries of the accident and rehearsing the neat sentence until his chest weather refused it. His thumb found the hinge of her jaw—the place he had almost cupped hours earlier—and rested there without pressing for the kiss she had postponed. She felt him want it. She felt him keep the vow. The restraint was its own intimacy, adult and aching.

Somewhere past midnight the thunder softened. Clara's floorboards creaked once and went quiet. The letter slipped from the table edge; John caught it without looking and set it on the far side of the booth as if distance could be temporary mercy. [player_name] shifted until she was half in his lap, blanket around both of them, his arms a closed circuit against the cold that leaked through glass. Market Street lamps smeared gold through rain. Freight muttered in the yard. Willow Lane waited in the dark with woodsmoke and a mantel clock and Henry sleepless behind paperweights—patient as debt, unknowing that the diner had become a different kind of courtroom: one where tenderness was entered into evidence before the indictment landed.

"I am still angry," John said once, soft enough that it did not break the hold. "I am still glad. Those can sleep in the same booth. So can wanting you and waiting for dawn." He tipped his forehead to hers in the dim. "If you fall asleep, I will wake you when the windows pale. If you cannot sleep, I will stay awake with you. Either way, when first light comes, we do not pretend this night erased the ledger. We use the holding as proof we can face it without running for a train."

[player_name] nodded against him. Sleep came in pieces—dozing to the rain's hand on the roof, waking to his breath, dozing again with her fingers curled in his shirt. Each time she woke, the blue door still held. Each time, the letter still waited. Each time, John was still there, practicing staying the way he had once practiced losing her in weather like this.

Time stretched the way rain stretches sound. An hour might have been three. John rose once to lock-check the back bolt Clara had thrown and to pour water that tasted faintly of pipes and night. When he returned, [player_name] pulled him down without ceremony, tucking herself along his side so that one of his legs slotted between hers—intimate without crossing the line she had redrawn for dawn. His hand settled at her hip, heavy and warm. Through the glass, Market Street lamps smeared and steadied. A lone car hissed somewhere and was gone, as if the town had decided their booth was private weather.

"I used to stand at the station on nights like this," John said quietly. "Not every week. Often enough that Mae at the post office started giving me looks. I told myself I was checking freight schedules. I was listening for a train that might bring you back before I had language for how much I needed it." He huffed a soft breath into her hair. "Then Clara got old enough to notice my absences and I stopped going. Started putting the listening into the grill and the ledger and the way I wiped the counter twice. You walking through the blue door undid years of that discipline in about ten seconds."

[player_name] smiled against his shirt, sad and fond. "I rehearsed not coming. Every autumn. Henry's letter was the first rehearsal that failed on purpose." She traced the burn scar with a fingertip, learning it like Braille. "I thought if I stayed away the debt would stay away from you. That was vanity dressed as sacrifice. The debt was already in your walls. I was only the story taped over the crack."

"Then we tear the tape at first light," John said. No drama. A plan. His fingers flexed at her hip, a squeeze that was comfort and claim both. "And if tearing it hurts, we hurt in the same room. I am done hurting in separate weathers."

They dozed again. Woke. Traded more fragments: the first special he had burned after the funeral; the first apartment she had painted a color Somerton did not own; Clara's charcoal phase that turned every margin into interrogation; the particular sticking sound of the blue door in November that John swore was a personality trait. Desire lived under the talk like a low current—acknowledged in the way their breathing synced, in the almost-kiss that hovered when she shifted and his mouth was suddenly close, in the mutual choice to let dawn keep its monopoly on the larger truth. The restraint did not feel like denial so much as craft: two adults shaping a night that could bear morning's weight.

First light arrived the way Somerton mornings always had: reluctant, wet, honest. The rain thinned to a fine silver. Bruised blue became pearl. The ridge warning on the forgotten radio clicked into a milder advisory. Coffee could be made again. Roads might remember how to be roads. Henry would be reachable. The cover story would no longer have overnight as an excuse.

John's arms tightened once as [player_name] stirred, a farewell to the dark's permission. He did not kiss her. He had saved that coin for daylight honesty, or for her to spend. Grey eyes met hers in the new pale. "First light," he said. Voice rough with sleeplessness and kept vows. "You asked me to hold you through the rain. I did. Now the bargain turns. What do you ask of the morning—and of me?"

Outside, wet boxwood would be shining on Willow. Inside, the cracked stool leaned, listening. The papers upstairs waited with Clara's charcoal circles. The letter on the far side of the booth looked smaller in daylight and somehow more dangerous. [player_name] sat up within the circle of his arms, blanket slipping, the demand of yesterday evening still living in her chest beside the warmth of having been held. Two paths opened like the blue door might when the damp eased: demand the full cover story now that light had come—or ask John to choose her over the Shaw quiet that had written her exit as mercy and his ignorance as kindness.

Rain still whispered on slate, softer. The quiet of Somerton had cracked in a locked diner overnight. At first light it waited to see whether tenderness would become courage—or whether courage would ask love to name its loyalty aloud before any uncle could sand the morning soft again.`,
  textHot: `The rain did not ask permission to keep them. It simply continued—slate singing, Market Street drowned, the ridge a rumor of water—until asking John to hold her through it felt less like postponement and more like the only honest weather left. And holding, [player_name] knew, would not stay innocent. Not after a night of knees touching and hands on thighs and not yet spoken like a vow with heat under it.

She had demanded truth before closeness. She had meant it. She still meant the dawn half. But Clara had gone upstairs with headphones and a knowing grin, the blue door was locked, Henry's letter lay between cold mugs, and [player_name] turned her hand in John's and said the other true thing with her pulse already loud.

"Hold me through the rain first," she whispered. "Bodies now—as much as we choose. Truth at first light. Not forgetting. Surviving. I want your arms. I want your mouth if you can give it without turning it into a way to avoid morning. At dawn I will ask for every unfinished room in the winter story. Tonight I am asking for you."

John's breath left him in a groan he did not bother to hide. Grey eyes went dark. "Truth at first light," he sealed. "No sanding. The whole cover story when the windows pale." His burn scar brushed her knuckles as he stood and drew her up, already close enough that she felt how hard waiting had made him. "Until then I hold you. Properly. Mouth, hands, whatever you open. Not as a guest. As the woman who priced my touch in honesty and is cashing part of the night early."

He killed the front fluorescents until only the kitchen pass and pie case glowed. Rain became the loudest thing besides their breathing. Blankets became a nest on the back booth bench. He sat and pulled her into his lap without preamble—straddling his thighs, blanket around their shoulders, her core pressed to the thick evidence of his wanting through denim. Sensory first: heat; rain-cool cotton; the clean scent of his throat; his heartbeat; the fryer ghost in the walls; the dizzy press of him where she ached. Emotion: relief sharp as pleasure; desire no longer theoretical; gladness fierce; fear of dawn braided with hunger. Plot turn: overnight had become bodies choosing shelter and fire while the secret waited beyond the glass.

John kissed her then—finally—deep and grateful and filthy with restraint finally spent. She opened for him. His tongue met hers. His hands slid under her shirt along bare skin, mapping ribs, the soft underside of her breasts, thumbs brushing nipples until she gasped into his mouth and rolled her hips against him. He answered with a broken sound and a grip on her waist that held her flush while he thrust up once, clothed and desperate, showing her exactly what first light would have to compete with.

"Tell me where," he murmured against her throat, kissing down, teeth grazing. "Tell me stop if the demand comes back early. Otherwise I am going to take the soft hour you refused and make it honest another way—your pleasure in my hands, my name in your mouth, no lies between your legs even if the ledger waits for dawn."

[player_name] guided his hand to the button of her jeans. Permission. He groaned like prayer. Fingers worked denim open, slid beneath cotton, found her already wet from hours of denial and the storm's long almost. He stroked her with work-rough patience—burn scar a secret against sensitive skin—until she trembled in his lap and bit his shoulder to stay quiet for Clara's sake. He coaxed her over the edge with his thumb and two careful fingers, mouth on hers to catch her cry, holding her through the shaking as rain held the town. When she slumped against him, wrecked-soft, he kissed her temple and did not push into her yet—still half-keeping a vow, still offering rather than taking everything.

"I can wait for more," he whispered, voice ruined, hips still aching up against her. "Or you can take me out and take what you need. Your stance. I have wanted this since you walked through the blue door. I will still want the truth at first light either way."

She chose him with her hands—opening his jeans, wrapping him, stroking until his forehead dropped to her shoulder and he muttered her name like a man losing and finding religion. She rose and sank onto him slow, both of them gasping at the fit, the years collapsing into heat and rain and vinyl. They moved together under the blanket: deep, unhurried, then harder when thunder covered the sounds; her nails in his shoulders; his mouth on her breast when he tugged her shirt higher; the booth creaking like another accomplice. She came again with him buried deep. He followed with a groan pressed to her throat, arms locked around her as if dawn might try to steal her and he had decided otherwise.

After, they stayed joined and then not, cleaned with napkins and tenderness, dressed enough for dignity if Clara appeared, tangled again under wool. Small truths returned between kisses: cities without boxwood; lean years; Clara and the desk; almost-tickets home. His thumb at her jaw. Her leg over his hip. Wanting and waiting for dawn sleeping in the same booth as anger and gladness. The letter waited on the far side like a chaperone they had successfully ignored without erasing.

"I am still angry," John murmured into her hair, spent and honest. "I am still glad. I am still going to ask for the whole cover story when light comes—and I am still going to remember how you felt around me when I ask." He tipped his forehead to hers. "Sleep if you can. I will wake you when the windows pale. We do not pretend sex erased the ledger. We use it as proof we can face the ledger without running."

Sleep came in pieces, body sore and sweet, rain a hand on the roof. Time stretched. Desire did not sleep simply because climax had visited once. John rose to lock-check the back and returned to find [player_name] watching him with open hunger in the pie-case glow. He stopped mid-step. She crooked a finger. He came. This time she pushed him onto the bench and straddled him again, already bare enough under the blanket, already slick from him, and sank down with a shared curse of pleasure that the rain kindly covered. They fucked slower the second time—foreheads together, eyes open, saying soft filthy truths between thrusts: how long; how much; how he had imagined her in this booth on empty close shifts; how she had touched herself in distant cities thinking of his hands. He came with her name bitten into her shoulder. She followed shaking, laughing once in disbelief at the sheer relief of being known by his body after being erased by a story.

Afterward he cleaned her with a damp kitchen towel warmed under the tap, a tenderness so careful it nearly undid her more than the sex. They dressed in pieces. Tangled again. His palm rested low on her belly under her shirt, possessive and gentle. "I used to stand at the station on nights like this," he murmured. "Listening for you. Mae noticed. Clara noticed. I stopped going and put the wanting into work and into nights alone above the diner that I will not describe if you prefer dignity—though dignity left this booth about an hour ago."

[player_name] laughed into his throat. "Describe enough. I spent years pretending ambition was the only heat I owned. Your letter from Henry cracked the quiet. Your mouth finished the job." She bit lightly at his jaw. "At first light I will still be the woman who demanded truth. I will also be the woman who took you inside her while the storm trapped us and called that survival. Both stand."

"Both stand," John agreed. His fingers stroked idle patterns on her skin, reigniting sparks without demanding a third round—yet. "We tear the tape at dawn. If it hurts, we hurt in the same room. Preferably after coffee. Preferably still smelling like each other so Henry understands the quiet did not break politely."

First light arrived reluctant and wet. Rain thinned to silver. Pearl replaced bruise. John's arms tightened in farewell to the dark's permission. He kissed her once—slow, daylight-soft, promise and reminder—then met her eyes.

"First light," he said. Rough. Loved. Unafraid of the bargain. "You asked me to hold you through the rain. I did. With my body. With everything you opened. Now what do you ask of the morning—and of me? The full cover story spoken clean—or my choice of you over the Shaw quiet that wrote your exit as mercy?"

Outside, wet boxwood would shine on Willow. Inside, the cracked stool listened. Papers waited upstairs with Clara's circles. The letter looked smaller and more dangerous in pearl light. [player_name] sat up within his arms, blanket slipping off skin that still remembered him, demand and afterglow living in the same chest. Two paths opened: demand the full cover story now that light had come—or ask John to choose her over the Shaw quiet, body and truth alike, before any uncle could sand the morning soft. Rain whispered on slate. The quiet had cracked overnight in sweat and vows. At first light it waited to see what love would name.`,
  choices: [
    { id: "scene6e", text: "At first light, demand the full cover story", textHot: "At first light, demand the full cover story after a night in his arms" },
    { id: "scene6f", text: "At first light, ask John to choose you over the Shaw quiet", textHot: "At first light, ask John to choose you over the Shaw quiet — body and truth" }
  ]
};
