export default {
  id: "scene7i",
  layer: 7,
  title: "No Callback",
  text: `The receiver went dead in [player_name]'s hand with a click soft enough to insult fifteen years of rehearsed courage.

Rain needled Market Street beyond the diner's blue door. The CLOSED sign still hung crooked against glass streaked with late-autumn wet. Fryer oil ticked in the cooling vat like a clock that had forgotten how to tell honest time. On the cracked counter stool that leaned its half-degree left, Jake sat with his elbows on Formica and his burn scar white where his thumb worried the seam of a napkin. The napkin held a number written in Mae's careful hand from an old exchange ledger Clara had circled in charcoal weeks ago—Voss's ghost, or whatever name the debt wore now that winter had learned to send invoices through living throats.

[player_name] set the receiver in its cradle hard enough that the cord jumped. No message left. No callback offered. The past had reached for her voice and she had hung up on it like a woman refusing to mail herself back into someone else's cover story. Station platform hiss lived only as memory at the edge of town. Coffee steam ghosted from the pot Jake had restarted because empty hands invited trembling, and trembling invited Henry's sanded mercy to invent a softer morning than the one she had just cut short with a hung-up click.

"You hung up," Jake said. Not accusation. Inventory. Grey eyes bright under the fluorescent strip that had outlived three owners and one winter nobody named. His coat still smelled like woodsmoke from Willow Lane and clean work-sweat from a morning that had refused sleep. Behind the pie case glass their doubled reflection looked almost ordinary—rain-damp hair, flour-dusted wrist, the particular quiet of a diner after hours when the town pretended it slept and the freight yard complained toward nothing.

"I refused them a return call," [player_name] said. Her throat tasted like copper and rain and old coins. "They do not get to hear me say Shaw like a plea. They do not get to log my name beside Henry's arrangement. The cover that cast me as brighter rooms is already cracking without me performing apology into a stranger's machine. Clara found enough paper to ask questions. Henry is out of sand. I will not give the ghost a polite goodbye on top of that."

Jake nodded once. Wet boxwood lived back on Willow with Henry's glass paperweight and pages that tried to tidy guilt into innocence. Clara's upstairs light would already be inventing questions in charcoal margins of old schoolbooks. And here, between the sticky blue door and the sink that had washed fifteen years of coffee grounds and almosts, the number on the napkin waited like a fuse that had not yet chosen its fire.

[player_name] picked the napkin up. Ink bled slightly where Jake's thumb had dampened the corner. Digits. An exchange that still answered. A living throat somewhere beyond Somerton's slate roofs that remembered ice and debt and a girl who said yes at twenty while fear shook in Henry's hands around whiskey he claimed was tea. She could still hear the professional cadence from the line—the way the voice had not cared who she was, only whether Shaw still owed and whether Shaw still ran.

"Burn it," she said, and heard the half of herself that wanted the past ash. "In the sink. Flame. Water. No leverage. No second conversation with a ghost that learned how to use phones. I hung up. Let the hang-up be the whole sentence."

Jake's mouth tilted, wrecked and almost smiling. "Or keep it. Not for them—for Henry. Leverage is an ugly word until you need it against the man who sanded winter into a cleaner story than winter earned. You hang up on Voss and still hold the number like a knife pointed at Uncle. That is not cowardice. That is strategy with a pulse. That is you refusing to leave empty-handed again."

She walked to the three-compartment sink behind the counter, rain still drying on her sleeves, and set the napkin on the stainless steel edge where bleach and lemon and old grease had fought for decades. The pilot light on the stove whispered orange. Matches lived in a tin beside the salt, the same tin Jake's father had once cursed over when the diner was still a younger wound. Jake watched her without steering, burn scar whitening, grey eyes refusing to invent her decision for her the way Henry had invented her leaving into ambition and brighter maps.

"If I burn it," [player_name] said, "I am choosing a kind of poverty. No callback. No proof I can wave when Henry starts sanding again with woodsmoke and soft sentences. Only the hang-up and whatever Clara found and whatever my mouth is willing to say in rooms that still call me the girl who wanted more. I will have to stand in noon light with nothing but memory and charcoal circles."

"If you keep it," Jake answered, voice low enough that Market Street would not steal it through the glass, "you are choosing a different poverty—the kind that sleeps with a number under the mattress and wakes every morning wondering whether today is the day you dial leverage into Henry's throat. Both keep the past from owning the line. Both cost sleep. Standing here inventing prettier reasons while the napkin dries is the only almost left on the menu, and you did not buy a ticket for almost."

A freight horn complained toward the yard. Ordinary Somerton continuing without permission. Regulars would start arriving within the hour—men who still used her leaving as a cautionary tale, women who had practiced believing the cleaner story until practice nearly became civic virtue. Mae would already be sorting mail two storefronts down, stamps clicking like small verdicts. [player_name] thought of Henry's kitchen and the woodsmoke that had hitchhiked into Jake's coat. She thought of how her hand had trembled when she hung up, not from fear of Voss, but from the sudden lightness of refusing to perform.

Jake stood. Came around the counter. Stopped close enough that his coat brushed hers when he breathed. Rain found a harder sheet against the awning outside. "I rebuilt this diner around a wound," he said carefully. "I raised Clara beside fluorescent lights and fryer hymn. I can survive a burned number. I can survive a kept one. What I cannot survive is watching you invent a softer exit because you still think my love is fragile enough to shatter on either ash or leverage. Do not protect me with my own surname. Not tonight."

[player_name] looked at the napkin. At the sink. At the pilot light. At Jake's mouth and the unfinished almost living at its edge like a second conversation. Fifteen years ago she had left this street believing silence would protect him. Tonight she had hung up on the past and discovered silence was not the only tool—fire was one, and so was a folded scrap of paper that could make Henry's sanded sentences catch in his throat before Clara came downstairs asking why the house smelled like fear dressed as patience.

"Clara will ask what I did with the exchange," she said.

"Clara asks everything," Jake said. "That is why we love her and why we fear her in equal measure. Tell her you hung up. Tell her the rest when you choose which poverty you can live inside without vanishing into uncle-protection again. I chose you in rooms that still smell like fryer oil. I will not unchoose you for ash or for a folded knife."

Coffee steam ghosted. The cracked stool listened through rain. Wet boxwood waited. Woodsmoke would already be inventing Henry's next soft sentence if they gave him time. [player_name] tasted the fork bright and dangerous behind her teeth: strike a match, watch the digits blacken, drown the ash under the faucet until the past was only wet paper and a hang-up—or fold the napkin into her pocket, keep the number warm against her hip like a second pulse, and walk back to Willow with leverage aimed at the uncle who had arranged her cleaner story while Jake's hand stayed on her wrist like a vow that had not found its full sentence yet.

Jake's hand found her wrist, thumb at the place where her pulse argued with strategy. "Either way moves us," he murmured. "Burn it in this sink and refuse the creditor even the dignity of surviving as a tool—or keep it and make Henry taste what it means that you can still dial the ghost he thought he buried under glass weights and polite coffee. Both hurt. Both keep me here. Soft landings are how we got the lie."

Outside, a delivery truck hissed past toward the freight yard. Inside, the quiet of Somerton leaned in at the gutter's edge to hear which hunger she would feed first—the hunger for a clean break with nothing left to dial, or the hungrier mercy of keeping a knife folded against her ribs for the man who had taught her how to leave. [player_name] drew a breath that tasted like rain and old coins and coffee and the particular courage of women who had once said yes for love and were learning how to say no without mailing themselves into someone else's machine.

The napkin waited. The pilot whispered. Henry's name sat half-spoken in her mouth, a syllable she could still swallow or spit into ash or into leverage. Jake's thumb stroked once—consequence, not comfort. The blue door stuck like a promise that needed force. The morning refused to land soft.`,
  textHot: `The receiver went dead in [player_name]'s hand, and the click went straight to her cunt like a second hung-up—sharp, final, unfinished heat with nowhere to dial.

Rain needled Market Street beyond the blue door. Fryer oil ticked in the cooling vat. On the cracked counter stool Jake sat hard already from watching her refuse the past a callback, burn scar white at the thumb, grey eyes bright, cock a thick line against denim he was not bothering to hide. The napkin with Voss's number lay between them like a fuse that smelled like Mae's ink and Clara's charcoal circles. [player_name] set the phone down hard enough that the cord jumped and her bra seam rubbed when she breathed too deep. Coffee steam ghosted. Woodsmoke still clung to both of them like a second skin carried out of Willow Lane.

"You hung up," Jake said, and stood, and crowded her back against the three-compartment sink before the sentence finished landing. Coat open. Chest to her chest. Already half-hard from proximity and danger and the simple fact of her cutting a creditor off mid-breath. "Good. They do not get your voice. They do not get Shaw like a plea. Now decide what the number gets—ash in this sink, or leverage warm in your pocket while I finish what the line started against this counter with your pulse under my mouth."

She tasted copper and rain and coffee and the metallic bright of a choice that had a body. Fifteen years of brighter rooms had not taught her how to negotiate ash versus leverage with Jake Shaw's thigh shoved between hers and his mouth already open against her neck, sucking hard enough to mark while Market Street pretended it slept. "If I burn it," she managed, voice steadier than the clench of her thighs, "I choose poverty. No proof when Henry sands again. Only the hang-up and Clara's papers and whatever noon will demand of my mouth."

"If you keep it," he rasped, hand under her sweater, palm flat on her stomach, thumb brushing the underside of her breast through the bra until her nipple peaked against lace like it had opinions about debt, "you choose a different poverty—the number under the mattress, mornings wondering whether today you dial Uncle into silence with a ghost's digits." His fingers shoved past her waistband and the cotton already betraying her—damp, humiliating, honest—two fingers finding her cunt with accuracy that had nothing to do with phone etiquette and everything to do with a man who refused to let a hang-up go celibate. "Both honest. Both keep me hard enough to hurt. Standing here inventing prettier reasons while the napkin dries is the only lie left, and I am done swallowing lies with my coffee."

[player_name] bit her lip to keep the sound off Market Street. A freight horn complained toward the yard. Jake's fingers pressed exactly on the syllable of her swallowed moan like punctuation with intent. His cock rolled once against her hip, thick, helpless, then held still, breathing hard enough that she felt it in her teeth. Wet boxwood waited with Henry's paperweight. Clara's charcoal lived upstairs like a dare. The cracked stool leaned its half-degree left, listening through rain.

"Burn it," he said into her hair, slow stroke through slick, not fucking her open yet, just proving the negotiation had a body, "and I will watch the digits blacken while my hand stays in your jeans—fire and water and you shaking on my fingers with nothing left to dial. Or keep it. Fold it against your wet cunt like a second pulse. Walk us back to Willow with leverage aimed at Henry and my taste still on your mouth. Either exit. Soft landings are how we got the cover story."

She laughed once, wrecked, and the sound fogged between their mouths. Coffee on his breath. Clean work-sweat. Apron strings still half-tied under his coat from a morning that had refused sleep. And here, against stainless steel that smelled like bleach and lemon and old grease, Jake curled his fingers inside her—thick, sure, crooking against the place that whitened the edges of the fluorescent strip—and the heel of his palm ground slow while rain needled slate roofs and the quiet of Somerton leaned in at the gutter to listen.

"I am not performing penance with your hand in my jeans," she whispered, turning enough that her lip brushed his. "I am deciding whether the past dies wet in this sink or lives folded as a knife for the man who cast me as ambition so the Shaw name could keep its polite edges. If you stop touching me I will burn or keep for the wrong reasons and hate us both by noon while Henry invents tea from whiskey again."

"Then I will not stop." He kissed her hard—coffee-bitter, teeth scraping—then tore back so she could still see the napkin on the steel edge over his shoulder. His thumb found her clit like a brand. He curled deeper, strokes sure, and her hips jerked; he held her upright with the arm across her ribs. "Pick. Strike the match while your cunt clenches around me and refuse the creditor even ash-dignity—or pocket the number and put every ounce of that hang-up on Henry's throat before Clara comes downstairs. Before I fuck you against this sink with a CLOSED sign for a witness. Before we lose the hour when your cunt and your courage are still answering the same question."

She could have come from the sentence alone. Instead she fought it, thighs shaking, because coming with Voss's digits still ink-wet felt like letting the ghost into the room before she had chosen what the ghost was allowed to become—tool or ash, knife or nothing. Jake felt the fight and eased—cruel mercy—fingers still buried, strokes gentled to a throb that matched the rain. "Good. Hold it. Use it. Anger and want in the same fist. That is how we survive Market Street without becoming Henry."

Coffee steam ghosted from the vent. The blue door stuck like a promise that needed force. [player_name] thought of Mae's tidy stamps and untidy curiosity, of regulars who had practiced believing she wanted more, of Henry's pages trying to tidy guilt into innocence, of Clara waking to a house that smelled like fear dressed as patience. She thought of Jake's cock twitching against her belly and refused to let wanting choose the knife alone—strategy sharp as heat, heat advancing the hang-up instead of decorating it.

"If I burn it," she breathed, "you keep your hand on me until the ash is wet—I will not give the past a clean fire and a soft landing in the same breath. If I keep it, you do not sand the walk to Willow. You stay hard and angry and mine while I put leverage in my pocket and the hang-up in Henry's unfinished word."

Jake's answer was a nod against her neck and a slow, filthy grind of his palm that promised both roads would be paid for in heat. He withdrew his fingers with a wet sound the rain almost covered, brought them to his mouth without shame, tasted her like evidence, then caught her wrist—sticky thumb finding her pulse, hand closing there instead of lower, consequence relocated to the place where her blood argued with strategy. "Either exit," he said, voice ruined. "Sink-fire—or number kept warm against your hip for Uncle. I am here for either cut. I will not love you less. I will only need you after, upstairs above the pie case or against the wet boxwood, because watching you hang up on a creditor while your cunt clenched around me is going to live in my body longer than any cover story Henry ever sanded."

The napkin waited on stainless steel. The pilot whispered orange. Matches waited in the tin. Henry's name sat half-spoken in [player_name]'s mouth—a syllable she could still swallow into ash or spit into leverage with Jake's taste still on her tongue. His hand stayed on her wrist, warm, marked, refusing to steer, refusing to leave. Her nipples ached against lace. Her cunt throbbed with the unfinished circle of his thumb. The blue door waited. Willow Lane waited with woodsmoke and a paperweight and an uncle running out of silence.

Outside, freight complained toward the yard, ordinary as ever. Inside her ribs, the fork brightened: burn the digits and refuse the past even tool-dignity—or keep the number and walk back into woodsmoke with Jake's hand on her wrist like a vow that still smelled like her. Either exit hurt. Either exit moved. The quiet of Somerton leaned in to hear which hunger she would feed first—the hunger for ash, or the hungrier mercy of a folded knife, or the man whose body had turned a hang-up into a reckoning she could feel in her cunt and her pulse and the place where apology used to live.

[player_name] drew a breath that tasted like rain and old coins and coffee and Jake. The napkin. The pilot. His hand on her wrist. The morning refused to land soft.`,
  choices: [
    { id: "scene8l", text: "Burn the creditor's number in the diner sink", textHot: "Burn the number in the sink — shaking, still wet for him" },
    { id: "scene8b", text: "Keep the number — leverage for Henry", textHot: "Keep the number warm — leverage for Henry, ache for Jake" }
  ]
};
