export default {
  id: "scene7g",
  layer: 7,
  title: "Relay Alone",
  text: `The diner above Market Street still smelled like coffee steam and fryer oil when [player_name] climbed the narrow stairs to John Shaw's flat with Henry's confession living in her mouth like a coin she had not yet spent.

Rain needled the slate roofs below. The blue door that stuck had closed hard behind her. Willow Lane's wet boxwood and woodsmoke clung to her coat like a second skin she could not shrug in the stairwell. She had taken Henry alone—confession without John in the room, mercy or strategy or both—and now the relay waited in a kitchenette that overlooked the freight yard and the town that still would not say her name the same way twice.

John opened before she knocked, as if he had been listening for her boots since she left. Grey eyes bright. Burn scar white on the thumb that gripped the doorframe. Apron gone. Shirt open at the throat. "You went alone," he said, not accusation yet—inventory. "You made him speak where I could not watch his mouth. Now you are here to decide how much of his breaking I get in your voice."

[player_name] stepped inside. The flat was small and honest: bed made with military care, a window that caught Market Street rain, a mug stained with old coffee, Clara's charcoal sketch of the diner taped crooked above the sink like a blessing that refused neatness. She tasted copper and rain and the particular courage of carrying someone else's uncle across a threshold. "He confessed," she said. "Ice. Whiskey called tea. Voss. My yes at twenty. The script that cast me as ambition. The sanding of your grief into weather. I have it. The question is not whether you hear—it is whether I hand you the blade with every edge intact."

John closed the door with a soft click that sounded louder than Henry's mantel clock. Coffee steamed from a pot on the hot plate. Outside, a freight horn complained toward the yard, ordinary Somerton continuing without permission. He did not touch her yet. He leaned against the sink and folded his arms as if holding himself in the room by force. "Softening is how Henry talks when he wants love to do restitution's work," John said. "If you sand what he said to protect me, you become him with better hair and a ticket stub. If you speak every ugliness, you risk watching me break in ways Clara's margins never drew. I am asking you to choose the shape of the relay—not whether I am strong enough. I already know I am not too fragile. I want to know whether you trust me with the full temperature."

[player_name] walked to the window. Rain sheeted the glass. Below, Mae's post office lamp threw a gold rectangle onto the wet walk. The cracked counter stool leaned its half-degree left inside the closed diner like a listener waiting for upstairs news. Wet boxwood lived in her memory. Woodsmoke. Papers under glass. Clara asleep or not asleep with graphite under her nails. Voss's shadow still owned a corner of the ledger even while desire owned the air between her and John.

"There are parts," she said carefully, "that would destroy you in the specific way people get destroyed—not killed, rewritten. The part where Henry watched you rebuild the diner and called your maturity proof the cover had worked. The part where he practiced your father's death as weather until even he almost believed it. The part where my leaving was praised at Shaw breakfasts as the town's luck. Softening those is not sanding for his sake. It is triage. Or it is another theft. I cannot tell which until I hear which verb you want me to spend."

John's mouth tilted, wrecked and almost smiling. "Then do not triage me like a patient. Soften nothing—put every syllable in my ear the way he put it in yours, including the breakfast praise and the maturity insult and the whiskey that was never tea. Or soften only the parts that would destroy me—your judgment, not Henry's leftover mercy—and I will decide later whether the missing edges feel like love or like another platform goodbye. Both keep you honest if you name the choice aloud. Standing at my window inventing a third relay that costs neither of us is the only cowardice left above Market Street."

She turned from the rain. Close enough to smell coffee and clean work-sweat and the woodsmoke she had carried up the stairs. The unfinished almost of his mouth lived at the edge of her attention like a second conversation waiting for the first to finish being cruel enough. "If I soften nothing," [player_name] said, "you will hate him in high resolution. You may hate me for the clarity. If I soften the destructive cuts, you will hate the blur when you find it—and you will find it, because Clara's papers do not blur and Voss does not blur and your body already knows when a story has missing teeth."

"I can survive hate," John said. "I rebuilt fluorescent lights around it. What I cannot survive is you deciding my throat's capacity in private while kissing me like we are finished with secrets." His eyes flicked to her mouth and held. "Relay. Full temperature or curated. Then we deal with the burn. Not before. Not with a softer hour invented because your hands are shaking."

[player_name]'s hands were shaking. She let them. Sensory first: rain on glass, coffee steam, fryer ghost from below, wet wool cooling on the chair. Emotion: fury braided to tenderness braided to the fear of becoming Henry with a kinder vocabulary. Plot: confession already harvested alone; delivery method undecided; Clara's morning approaching; Henry alone with an empty mug and a clock; Market Street still ignorant or not, depending on other roads not taken tonight.

She thought of the station platform at twenty—ticket damp, rain practicing goodbye. She thought of Henry's voice breaking on Voss's name in a kitchen without John. She thought of the way John had raised Clara beside the diner lights and called survival maturity while an uncle smiled too carefully at breakfast. The relay was not paperwork. It was whether love got to edit.

"I am not asking permission to protect you," she said. "I am telling you the fork before I speak the pages. Softening nothing when I tell you—every edge, every breakfast lie, every time he watched you sand your own grief and called it growth. Or softening only the parts that would destroy you—my call on which temperatures your name can hold tonight without becoming someone who burns the flat down with Henry still breathing on Willow."

John nodded once. The burn scar whitened. He crossed the small kitchenette and stopped an inch from her, heat without contact, forehead nearly to hers. "Either verb. Soften nothing—and stay while I digest the poison in high resolution. Soften the destroying cuts—and stay while I ask later what you withheld and why. Both keep me here. Both keep you from leaving with a prettier suitcase. Choose the relay's shape before my mouth chooses for us and turns truth into wanting before the wanting has earned the plot."

Outside, freight complained. Inside, [player_name] tasted the fork bright behind her teeth. Rain needled. Coffee steamed. The blue door stuck below. Wet boxwood waited on Willow with Henry's unfinished breathing. Clara's charcoal waited. Voss's shadow waited. John's nearness was a second pulse she could answer after the words—never instead of them.

John poured coffee neither of them would drink properly and set the mug in her hands as if heat could stand in for courage. "Tell me what the kitchen smelled like when he broke," he said. "Not the plot points—I can get plot from Clara's margins. Tell me the part that made you climb my stairs shaking. That is the temperature I am asking for. Softened or not, I want the room, not the press release."

[player_name] wrapped her fingers around porcelain and let the burn steady her. "It smelled like woodsmoke trying to be forgiveness," she said. "Like wet boxwood coming through the window seal. Like an empty mug pretending it had never held whiskey dressed as tea. He looked at the grate more than at me. He said your father's name once and had to stop. He said Voss like a man tasting metal. He said my yes like a receipt he had kept in a drawer and hoped would yellow into innocence. When he finished, the mantel clock sounded rude. That is the room. That is what I am carrying up your stairs—whether I hand it to you raw or clipped."

John's throat worked. He paced to the bed and back, a small orbit of a man who had rebuilt a life in rooms too narrow for pacing and was doing it anyway. "Clara will ask tomorrow what you told me tonight," he said. "If my version has missing teeth, she will hear the gaps. She draws gaps for a living. Softening for my sake becomes lying to her by lunch. Softening nothing becomes a house where everyone wakes angry in high resolution. I am not asking you for a gentle story. I am asking you which damage we can afford before dawn."

She thought of Henry alone with the clock. She thought of Mae's lamp on Market Street and the cracked stool listening through rain. She thought of the blue door that stuck and the fryer hymn that would start again whether justice finished or not. Somerton did not pause for Shaw confessions. That was the cruelty and the mercy of a town with freight schedules. "Afford is Henry's word," [player_name] said quietly. "He afforded silence for fifteen years. I am done budgeting truth like rent. I am only deciding whether love gets an editor's pencil before your ear does."

The hook set without soft landing: half-spoken truth still locked behind her teeth, John's unfinished question hanging in coffee steam, the particular hurt of a woman who had harvested a confession alone and now had to decide whether love meant full temperature or triage. [player_name] drew a breath that tasted like rain and old coins and coffee and the man who had waited above Market Street for a train that had finally arrived carrying knives. The quiet of Somerton leaned in at the window to hear which hunger she would feed first—the honesty that destroys, or the mercy that edits, or the body waiting for either story to finish landing.

She did not kiss him yet. The relay came first. The night refused to land soft.`,
  textHot: `The diner above Market Street still smelled like coffee steam and fryer oil when [player_name] climbed the narrow stairs to John Shaw's flat with Henry's confession in her mouth and her cunt already aching from the walk—adrenaline and dread and the unfinished heat of taking an uncle alone while the man she wanted waited upstairs like a second reckoning.

John opened before she knocked. Grey eyes bright. Shirt open. Cock already a thick line against denim because waiting had never been celibate in this flat and tonight's waiting had teeth. He pulled her in by the coat, shut the door with his hip, and did not kiss her—terms first, even here. "You went alone," he said into her hair, hands spanning her waist under wet wool. "You made him speak where I could not watch. Now you decide how much poison my ear gets in your voice while my hands are on you—because I am not doing this relay like a news report across a polite table."

[player_name] shoved his chest enough to see his face and not enough to lose his heat. Rain sheeted the window. Clara's charcoal diner sketch watched from above the sink. Coffee steamed on the hot plate. "He confessed," she said, voice steadier than her thighs. "Ice. Whiskey tea. Voss. My yes. Ambition script. Your grief as weather. I have the whole ugly. Softening nothing means I put every breakfast lie and maturity insult in your ear while you can still feel my pulse. Softening only the destroying parts means I triage—and you may hate the blur later when you fuck me and taste the missing teeth."

John laughed—wrecked—and walked her backward until her ass hit the small table. He lifted her onto it like inventory, stepped between her knees, and kept his mouth an inch from hers. "Softening is Henry's religion," he rasped. "If you sand for my sake, you become him with a better mouth. If you speak every ugliness, you watch me break. I want the shape named. Full temperature or curated. Then I put my mouth where your courage lives."

His hand slid under her sweater, palm flat on her stomach, thumb brushing the underside of her breast until her nipple peaked against lace. She gripped his belt and felt his cock jump. "There are parts that rewrite a person," she managed. "Him watching you rebuild and calling it proof. Praising my exit at breakfast. Practicing your father's death until he almost believed weather. Triage or theft. I cannot tell which until you pick the verb."

"Then pick with my hand here." John shoved past her waistband and cotton—already damp, humiliating, honest—and found her cunt with two fingers that did not gentle for diplomacy. He held still inside the slick, pressure without stroke, a brand. "Soften nothing—say every syllable while I keep my fingers in you so you cannot float away into prettier language. Or soften only what would destroy me—your judgment—and I will decide later whether the missing edges feel like love or another platform goodbye while I am still hard enough to hate the edit. Both honest. Both keep me here. Inventing a third relay while your cunt clenches around nothing useful is the only lie left above the pie case."

[player_name] bit her lip. Rain needled glass. Freight complained toward the yard. Wet boxwood lived in her coat. Woodsmoke. Henry's empty mug. Clara possibly awake. Voss's shadow. John's fingers curled once—cruel mercy—and eased, waiting. "If I soften nothing," she whispered, rolling her hips despite herself, "you hate him in high resolution and maybe hate me for the clarity while you are inside me. If I soften the cuts, you hate the blur when Clara's papers refuse to blur—and you will put me on this table anyway and ask with your cock what I withheld."

"I can survive hate," John said, and kissed her once—hard, coffee-bitter, teeth scraping—then tore back so the relay could still happen with mouths free enough for words. His thumb found her clit and rested there like a held fuse. "What I cannot survive is you editing my uncle in private and then letting me fuck the copper taste out of your mouth as if sex were sand. Choose the relay. Soften nothing—full poison, full heat after. Soften only the destroying parts—and stay while I take the curated blade and still make you come on my hand for the honesty of naming the edit. Either way I need you after, because carrying Henry's voice up my stairs while you are wet for me is going to live in my body longer than any cover story."

She could have come from the sentence. Instead she held it, thighs shaking around his wrist, because coming before the verb felt like letting wanting choose the knife. John felt the fight and gentled to a throb that matched the rain. "Good," he murmured. "Hold it. Use it. Anger and want in the same fist. That is how we survive a relay without becoming Henry."

[player_name] dragged his mouth back to hers for one more filthy second, tasted coffee and rain and her own courage, then pushed him half an inch away—enough for words. "Softening nothing when I tell you," she said, pulse hammering around his stillness, "or softening only the parts that would destroy you. My voice. Your ear. Your fingers staying where they are until the shape is chosen so neither of us pretends this is polite."

John nodded against her forehead. Sticky fingers flexed once in promise and did not withdraw. Coffee steam ghosted. The blue door stuck below. Market Street dripped. The cracked stool listened through the floor. Henry's confession sat behind her teeth like a second orgasm refused. The unfinished kiss waited. The night refused to land soft.

John leaned over her on the table, free hand braced beside her hip, the other still buried to the knuckles in her heat. "Tell me what the kitchen smelled like when he broke," he demanded, voice wrecked, hips pinned still against the inside of her knee so his cock throbbed without thrusting. "Not press-release confession. The room. Softened or not—I want the smell in my mouth while I feel how wet the climb made you."

[player_name] tipped her head back and gave him woodsmoke trying to be forgiveness, wet boxwood at the window seal, empty mug, grate-staring, Voss like metal, her yes like a yellowing receipt, the mantel clock sounding rude. She said it while grinding once on his palm because speech without body had become another Shaw lie. John cursed—earned—and sucked a mark onto the side of her neck hard enough that morning would ask questions. "That is the room," he rasped. "Now choose the edit. Full poison into my ear while I finger you through the syllables—or triage the destroying cuts and say the word triage so I can hate it honestly when I fuck you after."

Clara's sketch watched. Coffee steamed forgotten. Rain sheeted. Freight complained. [player_name] clenched around his fingers and held, using want as ballast instead of escape. "Clara will hear gaps by lunch if I soften," she whispered. "She draws gaps. Softening nothing wakes the house angry in high resolution. Softening the worst cuts might let you sleep an hour before the papers refuse to blur. Afford is Henry's word. I am done budgeting truth like rent. I am only deciding whether love gets a pencil before your ear—and your cock—get the page."

John's thumb circled her clit once, slow, punitive and tender in the same stroke. "Then spend the verb. Soften nothing. Or soften only what would destroy me. I will not choose for you. I will only keep my hand honest until you do."

Outside, ordinary Somerton continued. Inside her ribs, the fork brightened: full temperature poison spoken with his hand in her cunt—or triage spoken with the same hand as witness, mercy named aloud so it could not pretend to be accident. Either exit hurt. Either exit moved. John's grey eyes waited. His cock pressed her thigh. Her voice still held the coin.

[player_name] drew a breath that tasted like rain and old coins and John. Soften nothing—or soften only the destroying cuts. His fingers stayed. The quiet leaned in at the rain-streaked window to hear which hunger she would feed first. Choose. His cock pressed a vow against her thigh. Wet boxwood still clung to her coat like evidence. Woodsmoke lived in both their throats. The cracked stool leaned below as if eavesdropping through fryer ghosts. Henry's name sat half-swallowed behind her teeth beside the coin of confession. She could spend full temperature or spend triage—and either spend would still end with John Shaw's mouth on her cunt or his cock in her before the freight yard finished its ordinary complaining toward a dawn that would not forgive editing. Soften nothing, or soften only the destroying cuts—speak the verb while his fingers wait and the rain keeps score on the glass like a stubborn second living witness.`,
  choices: [
    { id: "scene8g", text: "Softening nothing when you tell John", textHot: "Softening nothing — full poison with his hand still in you" },
    { id: "scene8j", text: "Softening only the parts that would destroy him", textHot: "Softening only the cuts that would destroy him — name the edit" }
  ]
};
