export default {
  id: "scene8h",
  layer: 8,
  title: "Hand in Hand",
  text: `Henry's kitchen on Willow Lane smelled like woodsmoke, steeped tea that was never only tea, and the particular electricity of a confession that had finally been forced to sit at a table with witnesses.

[player_name] stood with Jake's hand locked in hers—scar to palm, pulse to pulse—while rain ticked the slate roof and wet boxwood pressed the window glass like an audience that had waited fifteen years. The mantel clock kept guilty, even time. Papers under the glass weight had been moved aside; Clara's charcoal copies waited in a folder on the counter like a second gavel. Coffee steam did not reach this far from Market Street, but Jake's coat still carried fryer hymn and the blue door that stuck, and [player_name] tasted copper and rain and the unfinished courage of holding on while Henry's mouth opened.

Henry sat. Old. Smaller than memory. Hands around a mug that shook once and then steadied as if steadiness could still sand truth into weather. "You want the winter," he said. Not unkind. Not soft. "Then take it. Jake's father went through the ice. I had been drinking. There was a man—Voss—already circling what we owed. I asked [player_name], at twenty, to leave so the town could invent ambition for her exit and keep your name polite. She said yes. She left. I arranged the quiet. Clara found the papers. The letter was the crack. I am out of softer mornings."

Jake's grip tightened—not steering, present, a vow made of bone. Burn scar whitened against [player_name]'s knuckles. "Keep talking," Jake said, voice low enough to carry station platform hiss in it. "Ice. Whiskey. Debt. Her yes. My grief as season. Say it while she holds my hand so I do not have to decide alone whether my uncle is still a man I can stand in a kitchen with."

[player_name] watched Henry's face rearrange. Sensory first: woodsmoke, wet boxwood, mantel tick, rain on slate, paper rasp from Clara's folder, tea steam that smelled faintly of something harder, Jake's work-rough palm, the ghost of Market Street coffee on his sleeve. Emotion: fury braided to pity braided to the bright fear of forgiveness offered too early or refused too cleanly. Plot: forgive in Jake's hearing or refuse while still holding on; Clara upstairs or inbound with graphite honesty; Mae's trays rearranging across town; Voss's shadow owning a corner of every unpaid line.

Henry's eyes found [player_name]'s and then Jake's and then their joined hands as if the joining were the real accusation. "I loved my brother," Henry said. "I loved you. I loved the diner you would rebuild before you knew you would rebuild it. I thought silence was protection. Silence became furniture. Furniture became a house that could not say your father's name without lying. I am sorry in the only language I have left, which is not enough and is still the truth."

Clara's footsteps sounded on the stair—then stopped. Listening. Restless honesty pausing for a doorway. Jake did not look away from Henry. His thumb stroked once across [player_name]'s knuckles—consequence, not comfort. "She gets a verb," Jake told his uncle. "Forgive you in my hearing—speak grace over this table while I am still holding her, while the rain still ticks, while Clara still hears from the stair. Or refuse forgiveness and keep holding my hand—loyalty to the wound without granting you a softer landing. Both keep her in this kitchen. Neither invents a third road where we pretend the quiet was weather."

[player_name] tasted the fork bright behind her teeth. She thought of fifteen years of practiced belief—the girl who wanted more—and how forgiveness spoken aloud could become another quieter cover if it arrived before the cost finished landing. She thought of Jake under diner lights rebuilding a life around a wound Henry arranged into season. She thought of Clara's charcoal circles and Mae's civic trays and the blue door sticking like a vow that needed force. Ending the quiet meant feeding someone a true story. Whether grace belonged in the same breath as the story was the remaining blade.

"If I forgive you in Jake's hearing," [player_name] said carefully, voice carrying brighter rooms and rain, "I am not asking the kitchen to be kind for your sake. I am asking it to let mercy exist beside the ledger without sanding the ledger into nothing. If I refuse forgiveness and keep holding Jake's hand, I am not performing cruelty for sport. I am sequencing grace behind consequence—loyalty to Jake's wound and Clara's proof and the years your quiet stole from my mouth. Both hurt. Both move."

Henry's mug clicked against wood. Rain sheeted harder against Willow Lane. Wet boxwood tapped glass. Woodsmoke thickened until [player_name] could taste ash beside copper. Freight complained toward the yard in the distance. Station platform memory hissed. Market Street's cracked counter stool leaned its half-degree left two streets away as if listening through weather. Clara's breath on the stair held like a held stamp.

Jake shifted closer, coat brushing [player_name]'s, hand still locked. "I can hear you forgive him," he murmured for her alone, then louder for the table. "I can hear you refuse. What I cannot hear is you invent manners while my father's ice is still in this man's mouth. Hold my hand either way. That part is not the choice. The choice is whether grace lands in my hearing tonight or whether refusal stays honest until consequence finishes teaching this house what furniture cost."

Henry looked at their joined hands again. "I do not deserve her forgiveness," he said. "I may not deserve yours. I am still asking to be seen without weather. That is not the same as asking to be spared."

[player_name] felt Jake's pulse against her palm—steady, furious, alive. She thought of the letter that was not come home, only I thought you should know. She thought of tickets bought with rain in her hair. She thought of love spoken above a diner and papers face-up on a quilt and Clara choosing audiences with graphite under her nails. The kitchen refused to become a softer room.

"Your brother deserved better than ice and tea," she told Henry. "Jake deserved better than a cleaner grief than the one he earned. Clara deserved better than finding proof drawn over silence. I deserved better than ambition as cover. Forgiving you in Jake's hearing would be a verb of consequence, not a stamp of absolution. Refusing while I hold him would be a verb of consequence too—grace delayed, not erased, until the cost stops pretending it was season."

Jake's scar pressed her knuckles. "Then stop explaining and choose," he said, almost gentle, which in Henry's kitchen was sharper than shouting. "Forgive Henry in my hearing—speak it while the mantel clock listens and Clara hears from the stair and my hand stays in yours. Or refuse forgiveness and keep holding my hand—walk out of grace without walking out of me. Either way, the woodsmoke stays. Either way, Voss's name stays under the glass weight. Either way, I am yours in this kitchen with the quiet cracked open and no soft landing left on Willow Lane."

Outside, rain needled slate. Inside, tea steamed. Clara's folder waited. Mae's gold lettering fogged across town in civic breath. The blue door stuck. Fryer hymn waited for morning. Henry waited with an empty apology and a full confession. Jake waited with his hand locked like a vow that refused to go celibate of consequence.

The hook set without soft landing: truth spoken, forgiveness undecided, Jake's hand warm and scarred and refusing to let go, the particular hurt of a woman who had come home to a rain-wet town and was now deciding whether mercy belonged in the same kitchen hour as ice.

Forgive Henry in Jake's hearing—or refuse forgiveness and keep holding Jake's hand. [player_name] drew a breath that tasted like woodsmoke and tea and rain and the man whose pulse beat against her palm. Willow Lane held steady. The quiet of Somerton leaned in at the gutter to hear which hunger she would feed first—grace spoken aloud, or refusal kept honest, or the loyalty of a joined hand that hurt to leave either way.

Henry's mantel clock ticked once, hard. Clara's foot shifted on the stair. Wet boxwood tapped again. [player_name] thought of Jake raising Clara beside diner lights, of freight that never quite left the yard, of a winter accident arranged into weather and a creditor's shadow named Voss and a yes given at twenty that had protected a boy by disappearing the girl. Forgiveness in his hearing meant letting mercy exist without pretending the ledger vanished. Refusal while holding on meant keeping grace behind the wound until the house learned the cost in daylight. Both were loyalty. Neither was manners. The rain kept civic time. Jake had rebuilt a life around fryer hymn and a blue door that stuck; Henry had rebuilt a quiet around ice and tea; [player_name] had rebuilt nothing but a ticket home and a hand willing to stay locked through the cost. Forgiveness in Jake's hearing would not erase Voss or Clara's charcoal or the years ambition wore as a costume. Refusal would not erase the possibility of grace later—only refuse to let mercy arrive dressed as weather. The mantel clock ticked. Rain needled. Wet boxwood pressed the glass like a held breath. The joined hands stayed the only soft thing in the room that was not a lie.

Jake's hand stayed. The kitchen refused to land soft.`,
  textHot: `Henry's kitchen on Willow Lane smelled like woodsmoke, whiskey-tea, and the particular heat of a confession forced to sit at a table while [player_name] held Jake Shaw's hand so hard her cunt still echoed the unfinished claim from every night that had braided wanting to courage.

She stood hip to hip with Jake—his cock a thick aware line against her when he shifted, his scarred thumb locked over her knuckles, his coat open enough that she felt his heat through her sweater—while rain ticked slate and wet boxwood pressed the glass. Mantel clock. Clara's folder on the counter. Papers under glass weight pushed aside. Henry sat small with a shaking mug and a mouth finally out of softer mornings.

"You want the winter," Henry said. "Jake's father went through the ice. I drank. Voss circled. I asked [player_name] to leave. She said yes. Ambition as cover. Grief as season. Clara found the papers. I am done sanding."

Jake's grip tightened, possessive even in a kitchen, pulse slamming against [player_name]'s palm. "Keep talking," he rasped. "While she holds me. While I stay hard with anger and wanting in the same blood. Say ice and whiskey and her yes so I do not have to decide alone whether I can still stand here without fucking the quiet out of this house another way."

[player_name]'s nipples peaked against lace under the sweater; Jake's knuckle brushed the side of her breast as if by accident and then not by accident, a metronome timed to courage. "I hear you," she told Henry, steadier than the clench of her thighs. "Now I choose. Forgive you in Jake's hearing—speak grace over this table while his hand stays in mine and Clara listens from the stair. Or refuse forgiveness and keep holding him—loyalty to the wound without granting you a soft landing. Both keep me wet with adrenaline. Both keep his cock aware against my hip. Neither invents manners."

Henry's eyes flicked to their joined hands and to the flush at [player_name]'s throat and away, filing what he could not sand. "I do not deserve forgiveness," he said. "I am asking to be seen without weather."

Clara's footsteps stopped on the stair. Listening. Jake crowded closer—chest to [player_name]'s shoulder, mouth near her ear, loud enough for Henry, filthy enough for the pulse under his thumb. "Forgive him in my hearing," Jake murmured, "and I will still take you against the wet boxwood after we leave this kitchen, because mercy does not make me soft. Refuse him and keep holding my hand—and I will fuck the refusal into you upstairs or in the diner stairwell, because honesty keeps me harder than absolution ever did. Both verbs. Both keep you from inventing a third road where nobody gets muddy."

[player_name] gripped Jake's hand and the counter edge with her free fingers, woodsmoke and tea-steam and Jake's cock and Henry's waiting mug braided into one bright fork. "If I forgive you in his hearing," she told Henry, voice rough, "I am not performing penance with Jake hard against me. I am letting mercy exist beside the ledger without sanding the ledger into nothing. If I refuse and keep holding him, I am sequencing grace behind consequence—not cruelty for sport, loyalty to ice and Clara's charcoal and the years your quiet stole."

Jake's free hand slid under her sweater at the back—palm spanning her ribs, thumb brushing the underside of her breast through the bra until she bit her lip to keep the sound off Henry's tidy confession. Not a show for Henry. A claim for the choice. "Pick," Jake whispered. "While the mantel can still hear you refuse to tidy. Forgive him aloud with my hand in yours and my cock against you. Or refuse forgiveness and keep holding on—and stay shaking for me when we walk out into rain. Standing here inventing a softer tea while your cunt aches for a decision is the only cowardice left on Willow Lane."

Freight hissed toward the yard. Coffee steam ghosted in memory from Market Street. The cracked stool leaned. Blue door stuck. Mae's gold lettering fogged. Voss's coin under glass. Clara's breath on the stair. [player_name] rolled her hips a fraction against Jake's thigh because stillness had become another Shaw lie, then forced stillness back because forgiveness or refusal deserved a clear throat.

"If I forgive him," she breathed to Jake alone, then louder, "you do not soften. You stay angry and hard and mine while grace lands without erasing ice. If I refuse, you do not waste the refusal on cruelty—you help me keep consequence honest until daylight finishes teaching this house."

"Either exit," Jake promised, withdrawing his hand from her breast slowly enough that woodsmoke almost covered the loss, catching only her fingers again with a sticky warmth from nerves and wanting. His cock still pressed her. His mouth found the side of her neck—one open suck Henry absolutely saw and absolutely could not sand into weather—and then he made space for the choice like a man who understood confession and private heat could share a kitchen without apologizing. "Forgive Henry in my hearing. Or refuse forgiveness and keep holding my hand. I will not love you less. I will only need inside you after—boxwood, stair, diner above the blue door—because watching you threaten a quiet with honesty while wet for me is going to live in my body longer than any cover he ever arranged."

[player_name] tasted copper and woodsmoke and tea and Jake. Rain sheeted Willow Lane. Mantel clock ticked. Freight complained. Her nipples ached. Her cunt throbbed with unfinished claim. Henry's name trembled finished and unfinished at once. Clara waited on the stair. Jake's hand stayed locked, warm, marked, refusing to steer, refusing to leave.

Jake rolled his hips once against her—helpless, then locked still—and breathed hard enough that Henry filed the sound under consequence without lifting his mug. "I rebuilt a diner around a wound," Jake said to the table, then softer into [player_name]'s hair. "I can survive grace in my hearing. What I cannot survive is watching you invent a softer landing because you still think my cock and my name are too fragile for mercy and refusal in the same hour as ice. Forgive him loud, or refuse him honest. Do not invent a third road where nobody gets muddy."

She laughed once, wrecked, fogging nothing but her own courage. Wet boxwood lived against the glass. Woodsmoke. Clara's graphite folder. Voss's shadow. Fryer oil ticking in memory like a second timer. She covered Jake's knuckles with her other hand—not stopping him, calibrating—and faced Henry with her pulse arguing strategy in a joined grip. "Refusal is not sanding," she said. "It is sequencing. Forgiveness now is not absolution for sport—it is refusing another decade where mercy never arrives because the quiet ate it. Both hurt. Both move. Both keep his hand in mine until the kitchen door sticks open for whatever comes after your tea."

Henry set the mug down, a ceramic click like punctuation. "Then spend the verb before the clock invents another hour of weather. This table does not care about your cunt or his vow. It cares about what leaves your mouth in which order. Speak."

The hook held: confession landed, forgiveness undecided, body humming, evening refusing soft landing. Forgive Henry in Jake's hearing—or refuse forgiveness and keep holding Jake's hand. [player_name] drew a breath that tasted like rain and woodsmoke and the man whose pulse beat against her palm. Willow Lane held steady. The quiet leaned in at the gutter to hear which hunger she would feed first—grace spoken, or refusal kept honest, or the heat that had turned a kitchen into a reckoning she could feel in her pulse and her cunt and the place where apology used to live.

Choose. Jake's scar. The mercy or the wound. Somerton tracked mud either way and the night refused to land soft.

Freight complained again, metallic and useless against the throb between her thighs. Clara shifted on the stair. Wet boxwood tapped. [player_name] thought of tickets and platforms and every unfinished fuck that had braided wanting to courage until neither would go celibate for Henry's tea. Forgiving him in Jake's hearing meant letting mercy exist while Jake stayed hard with anger beside her. Refusing while holding on meant buying consequence a corridor—then taking that corridor with her cunt still aching and Jake's mouth on her neck in the rain. The mantel clock kept filthy time. Jake's hand stayed. The kitchen refused a softer room. Jake had rebuilt a life around fryer hymn and a blue door that stuck; Henry had rebuilt a quiet around ice and tea; [player_name] had rebuilt nothing but a ticket home and a cunt willing to stay honest through the cost. Forgiveness in Jake's hearing would not erase Voss or Clara's charcoal—or the thick line of Jake's cock against her hip while anger and wanting shared a bloodstream. Refusal would not erase grace later—only refuse to let mercy arrive dressed as weather while she still ached for him. Mantel clock ticked. Rain needled. Wet boxwood pressed glass. His scarred hand stayed the only soft thing in the room that was not a lie, and even that softness was a vow with teeth.

Henry waited. The joined grip hurt to leave either way.`,
  choices: [
    { id: "scene9g", text: "Forgive Henry in Jake's hearing", textHot: "Forgive Henry in Jake's hearing — mercy while he stays hard with anger" },
    { id: "scene9b", text: "Refuse forgiveness; keep holding Jake's hand", textHot: "Refuse forgiveness; keep holding Jake — then take him into the rain" }
  ]
};
