export default {
  id: "scene2a",
  layer: 2,
  title: "The Diner",
  art: "/art/until-the-quiet-breaks/scene2a.png",
  text: `Market Street took the rain the way it always had—into the gutters, into the cracks between the bricks, into the smell of fryer oil that rose even before [player_name] reached the blue door. The paint had softened with years; the brass knob shone where countless palms had turned it. She set her suitcase against the jamb, put her shoulder to the wood, and felt the familiar stick give way. The bell above the frame cried thin and true.

Inside: coffee steam ghosting the windows, the tick of the pie case, rain freckling the front glass. The cracked counter stool nearest the register still leaned a half-degree left, as if the years had argued with it and lost. A specials board listed beef stew and apple crumb. The air held butter, onion, clean grill, and the quiet of a place that kept people fed when words failed.

John Shaw looked up from behind the counter.

For a moment neither of them moved. He had broadened through the shoulders, grown into the stillness he used to borrow from Henry. Dark hair shorter than she remembered, threaded at the temples with early silver that rain would have hidden. Sleeves rolled to the forearm. A faint burn scar at the base of his thumb she did not remember—something earned in the years she had spent elsewhere. His eyes were the same grey as the Somerton sky—steadier now, as if he had learned to hold weather without flinching.

"[player_name]," he said. Not a question. Her name in his mouth sounded like a door being tested from the inside.

She could have made a joke about the blue door. She could have asked for coffee like a stranger. Instead she stood dripping on the mat and let him look at her the way a man looks at a letter he never expected to be answered in person.

"You're soaked," John said at last, and the ordinary kindness of it nearly undid her. He reached under the counter for a clean towel and set it beside a mug she had not ordered, handle turned toward her hand. "Henry wrote you." A pause, measured. "I asked him not to. Then I hoped he would anyway."

The diner held three locals at a back booth who pretended not to listen and failed—wet coats draped over vinyl, voices dropped to the careful murmur of people who had lived long enough in Somerton to know when history walked in and sat down. John ignored them with the grace of long practice. He wiped a clean circle on the laminate as if clarity could be polished into existence, then poured coffee without asking how she took it. Black, as she had always taken it when she was twenty and trying to look older than her fear.

[player_name] wrapped her fingers around the mug. Heat climbed her wrists. Steam rose between them like a small, temporary wall. She dried her face with the towel and tasted rain and coffee and the old ache of almost.

"Clara found papers," he went on, quieter, leaning in so the booth could not harvest every word. "In the desk Henry swore was empty. Sketches in the margins—her habit, charcoal pressed hard enough to ghost the next page—and underneath, names, dates, a winter I only half remember. Receipts. A letter draft that never got sent. Henry went pale when she laid them out on this very counter one night after close. Two days later he said he had mailed something. He would not say to whom. I knew."

"What does Clara think she found?" Her voice came out steadier than she felt.

"Enough to ask why you left." John's mouth tightened. The burn scar on his thumb caught the light when he flexed his hand against the counter edge. "Enough to ask why everyone told me it was because you wanted a bigger life, when the night I remember does not match the story I was fed. I remember you crying on the station steps. I remember Henry's hand on your shoulder. I remember you saying you were sorry in a way that did not sound like someone chasing a city. Then you were gone, and the town handed me a neat sentence to live inside, and I tried." He exhaled. "I stayed. I ran this place. I raised Clara after our mother stopped being able to—stopped cooking, stopped answering, stopped being a person we could reach. I did not spend fifteen years hating you. I spent them trying to make the pieces fit."

Rain hammered the glass harder, a sudden sheet that turned Market Street into a smear of headlights and slate. The dinner rush was beginning—wet coats shaking out in the vestibule, the smell of fryer oil sharpening as John's cook called through the pass, someone laughing too loud at a joke about the weather. A couple took the booth by the window. A man in a feed-store cap claimed the cracked stool two seats down and nodded at John without looking at her, as if politeness and curiosity could share a single gesture.

John glanced at the door, then back at her, torn between the work that kept the lights on and the woman who had walked into his unfinished questions. He moved with the economy of someone who had built a life from plate, napkin, refill—small motions that kept the lights on while the real conversation waited under the steam.

"You can stay," he said, voice low again when he returned to her end of the counter. "Through the rush. We can talk when the booths empty—really talk, not this half-version with ears in every corner. Or—" He nodded toward the street, toward the climb that led to Willow. "We can go to Henry together. I am tired of receiving the truth secondhand. If he finally decided you should know, then I want to hear it in a room where I can watch his face."

Behind him, through the kitchen pass, a girl's voice—Clara's, older than [player_name] remembered, edged with the same restless honesty that lived in her sketches—called that the soup was ready and that someone needed to taste the salt. John did not turn. He waited on [player_name]'s answer as if the whole town's weather hung on it.

She tasted the coffee. It was strong and a little burnt, the way Somerton preferred it, the way the diner had always preferred survival over perfection. Somewhere under the counter, the cracked stool waited for her weight. Somewhere up Willow Lane, Henry waited with whatever he had finally decided she should know, woodsmoke in his clothes, careful eyes practicing a confession fifteen years late. And somewhere in the kitchen, Clara moved among pots and charcoal-smudged notebooks, the girl who had pressed hard enough on the past to make Henry's silence crack.

John's hand rested on the counter near hers, not touching. Close enough to feel like a question. Close enough to see the scar again, the work-rough knuckles, the stillness he had perfected for moments exactly like this.

A truck hissed past on Market Street, tires throwing water against the curb. John's gaze flicked to the window and back, as if measuring how much of their reunion the town was allowed to witness. "People here still tell the story Henry gave them," he said. "That you were too bright for us. That I was too quiet to keep you. That Somerton was a temporary stop on a longer map. I let them, because arguing would have meant admitting I did not know my own life—that the night my father died and the night you left had been braided together somehow, and nobody would show me the knot." He scrubbed a circle into the laminate that was already clean. "Clara does not let anyone keep a story that neat. She found the papers because she was looking for drawing paper in Henry's desk and refused to put the wrong kind back. She is the reason you are standing here. She is also the reason I am terrified. Once the quiet breaks, I do not know what version of us survives the noise."

[player_name] thought of the letter's careful lines, of boxwood on the station wind, of a boy on rain-dark steps grown into this man with a burn scar and a diner that smelled like survival and unfinished sentences. She thought of Henry's hand on her shoulder fifteen winters ago, of the debt she had been asked not to name, of the accident that took John's father and left Somerton a kinder story. She had carried that silence across years until even she almost believed she wanted a bigger life. Standing here, coffee warming her palms, she felt the lie loosen like a stitch giving way.

"I did not come to take the diner from your hands," she said. "I came because the quiet broke on Henry's page, and I could not pretend I did not hear it. I left believing I was protecting you. I am not sure anymore who the silence protected."

John nodded once. Something in his face eased and tightened at the same time—relief braided with the dread of finally getting what he had asked for. The dinner rush pressed closer—wet coats, the specials board, a laugh from the back booth that did not know it was interrupting history, the thin cry of the blue door admitting another customer into the steam. He plated stew for the feed-store cap without looking away from her for more than a breath. When he leaned in again, it was just enough that only she could hear.

"Stay or walk to Willow," he said. "Either way, do not vanish between the bell and the rain. I have practiced losing you. I am done rehearsing it." His thumb brushed the mug's rim—a near-touch that sent heat up her arm that had nothing to do with coffee. "If you stay, I will feed this room and then give you the truth I have—what Clara found, what I remember of that winter, what I have been afraid to ask Henry aloud. If we walk, we put my uncle in a chair and we do not let him tidy the story into kindness again. You choose. I will follow either door."

Through the pass, Clara's voice rose again, closer, as if she might step out with soup and charcoal still under her nails. The blue door stuck once more. Rain silvered Market Street. John waited, grey eyes steady, the cracked stool empty beside [player_name] like an invitation written in laminate and fifteen years of weather held without flinching.`,
  textHot: `The blue door stuck under [player_name]'s shoulder the way it always had, and the stick went straight through wet wool into the soft place between her legs—as if Somerton had been waiting fifteen years to put its hand there again.

She shoved. The brass knob turned hot from other palms. Fryer oil rose before the bell even cried. Rain crawled the back of her thighs. Her suitcase hit the jamb. She stepped into coffee steam and the tick of the pie case with her nipples already tight from cold and from something older: the knowledge that John Shaw was somewhere in this room, and her cunt remembered him before her mouth did.

He looked up from behind the counter.

Broadened shoulders. Sleeves rolled. Early silver at his temples. The burn scar at the base of his thumb she had never seen—new geography earned in years she had spent touching herself to the old map and waking unfinished. Grey eyes the color of the Somerton sky, steadier now, and when they landed on her the steadiness cracked for one filthy second. She felt it in her throat. She felt it lower. She crossed her arms over wet wool so he would not see how hard her body answered a man who had not touched her yet.

"[player_name]." Not a question. Her name in his mouth sounded like he was already fucking her in his head and trying not to let the booths know.

"You're soaked," John said, and the ordinary kindness nearly undid her more than any filthy fantasy. He set a clean towel beside a mug she had not ordered, handle turned toward her hand. When he leaned, heat came off him—coffee, rain, clean sweat from the grill, soap that had lost the fight with work. She wanted to put her mouth on that burn scar. She wanted his palm at her waist the way it had been once behind this building, fryer off, her back to brick, his breath shaking against her cheek while his thigh pressed between hers and almost became a kind of sex all its own.

"Henry wrote you." A pause, measured, while his gaze flicked to her mouth and then—discipline failing—lower, to the wet cling of her blouse. "I asked him not to. Then I hoped he would anyway."

Three locals at a back booth pretended not to listen. John wiped a clean circle on the laminate and poured her coffee black without asking, the way she had taken it at twenty when she was trying to look older than her fear. His wrist flexed. The scar moved. She watched it and imagined tracing it with her tongue until he made a sound he could not plate for customers. Under the counter's edge she pressed her thighs together, a private, useless discipline against the pulse that had started the second the blue door gave.

[player_name] wrapped her fingers around the mug. Heat climbed her wrists. When his knuckles brushed hers on the towel, a brighter heat slid up her arm and settled shameless between her legs. Steam rose between them like a temporary wall she wanted to climb. She dried her face and tasted rain and coffee and the old ache of almost, sharpened now into want she could name: she wanted John Shaw's cock, not as a metaphor, as a fact her body had been holding like a secret ledger.

"Clara found papers," he said, quieter, leaning in so the booth could not harvest every word. Close enough that she felt his breath on her temple. Close enough that if she tipped forward she could have kissed the corner of his mouth and ruined the rush. "In the desk Henry swore was empty. Sketches in the margins—charcoal pressed hard enough to ghost the next page—and underneath, names, dates, a winter I only half remember. Receipts. A letter draft that never got sent. Henry went pale when she laid them out on this counter after close. Two days later he said he had mailed something. He would not say to whom. I knew."

"What does Clara think she found?" Her voice came out steadier than the heat licking her. Her body was less obedient: every inch aware of his forearms, the open collar of his shirt, the way his hips settled against the counter as if he needed something solid between them before he did something the dinner rush could not forgive.

"Enough to ask why you left." John's mouth tightened. The burn scar caught light when he flexed against the edge. "Enough to ask why everyone told me you wanted a bigger life, when the night I remember does not match the story I was fed. I remember you crying on the station steps. I remember Henry's hand on your shoulder. I remember you saying sorry in a way that did not sound like someone chasing a city—" His voice dropped. "And I remember wanting to pull you into the ticket office and keep you with my mouth if my words would not do it."

He exhaled like the admission cost him. Grey eyes dark, hungry under the restraint. "Then you were gone. The town handed me a neat sentence. I stayed. I ran this place. I raised Clara after our mother stopped being a person we could reach. I did not spend fifteen years hating you. I spent them trying to make the pieces fit. And some nights—" another drop, raw "—trying not to remember how you felt against me when we almost finished what we started. How wet you were. How close I came to fucking you against that brick and calling it forever."

Rain hammered the glass into a smear of headlights and slate. Wet coats shook out in the vestibule. Fryer oil sharpened as the cook called through the pass. A couple took the window booth. A man in a feed-store cap claimed the cracked stool two seats down and nodded at John without looking at her. [player_name] felt exposed anyway: rain-damp, cunt aching, sitting in the room where she had once mapped his mouth in stolen minutes and left before either of them came.

John glanced at the door, then back at her—torn between the work that kept the lights on and the woman who had walked into his unfinished questions with unfinished hunger written on her skin. She watched the roll of his shoulders as he plated, the flex of his back, and thought of locking the blue door after close, peeling that shirt off him, taking fifteen years out on the laminate if they were brave enough. Thought of his cock in her hand. Thought of saying stay and meaning in me.

"You can stay," he said when he returned to her end of the counter, voice rough as if his throat knew what his hands wanted. "Through the rush. We can talk when the booths empty—really talk, not this half-version with ears in every corner. Or—" He nodded toward the street, toward the climb to Willow. "We can go to Henry together. I am tired of receiving the truth secondhand. If he finally decided you should know, I want to hear it in a room where I can watch his face." His gaze held hers a beat too long. "And I want you where I can still reach you after. Touch you after. I am done pretending I only want answers."

Through the pass, Clara's voice—older than [player_name] remembered, edged with restless honesty—called that the soup was ready and someone needed to taste the salt. John did not turn. He waited on her answer as if the town's weather hung on it. Under the counter his knuckles brushed the wood near her knee—not quite a touch, a near-miss that made her breath catch and her cunt clench around nothing. She wanted him to close the distance. She wanted him to wait until the room emptied and then not wait at all. She wanted his fingers where she was wet and his mouth saying Henry's name only after he had made her come.

She tasted the coffee—strong, a little burnt, Somerton's preferred survival over perfection. The cracked stool waited for her weight. Up Willow Lane, Henry waited with woodsmoke and a confession fifteen years late. In the kitchen, Clara moved among pots and charcoal-smudged notebooks, the girl who had pressed hard enough on the past to crack the silence. [player_name] sat in the middle of it all with wet clothes and a body that had not forgotten John Shaw—not the boy on the station steps, not the man whose mouth she wanted on her throat, her breasts, her cunt, right now, while the fryer hymned and the town pretended not to stare.

John's hand rested on the counter near hers. Close enough to feel like a question. Close enough to see the scar again, work-rough knuckles, stillness pulled taut over want. She could have covered his hand. She could have walked around the counter and fitted herself against him the way she had in the alley when the world felt private—his thigh between hers, her moan swallowed into his neck, his cock hard against her hip through denim. She did not. Not yet. The wanting lived in her anyway: heat low in her belly, skin too aware of seams and damp fabric, imagination offering his weight, the soft filthy sound he might make if she finally said stay and meant fuck me after close until the quiet breaks for good.

A truck hissed past on Market Street. John's gaze flicked to the window and back, measuring how much reunion the town was allowed. "People here still tell the story Henry gave them," he said. "That you were too bright for us. That I was too quiet to keep you. That Somerton was a temporary stop. I let them, because arguing meant admitting I did not know my own life—that the night my father died and the night you left had been braided, and nobody would show me the knot." He scrubbed a circle into laminate already clean. Voice softened, intimate under the rush. "Clara does not let anyone keep a story that neat. She found the papers looking for drawing paper and refused to put the wrong kind back. She is why you are standing here. She is why I am terrified. Once the quiet breaks, I do not know what version of us survives the noise."

He swallowed. Color rose along his throat. "I do know I have spent too many nights imagining you back in this room—not as a ghost. As a woman I could put on this counter after lockup. As a cunt I could taste. As a mouth that might finally say why she left while I was inside her. Having you here and not touching you is a particular kind of hell."

[player_name] thought of the letter's careful lines, of boxwood on the station wind, of a boy on rain-dark steps grown into this man with a burn scar and a diner that smelled like survival and unfinished sex. She thought of Henry's hand on her shoulder fifteen winters ago, of the debt she had been asked not to name, of the accident that took John's father and left Somerton a kinder story. She had carried that silence until she almost believed she wanted a bigger life. Standing here, coffee warming her palms, thighs pressed together, wet and wanting under wool, she felt the lie loosen like a stitch giving way. Want rushed into the gap—plot and lust braided so tight she could not tell which pulse was choosing.

"I did not come to take the diner from your hands," she said. "I came because the quiet broke on Henry's page, and I could not pretend I did not hear it. I left believing I was protecting you. I am not sure anymore who the silence protected." She met his eyes and let him see the rest—the hunger under the apology, the shameless body-vote. "I am also not sure I can sit here and pretend I do not still want your hands on me. Your mouth. Your cock. I practiced wanting a bigger life. What I practiced was starving."

John nodded once. Relief braided with dread; desire braided with caution. The dinner rush pressed closer—wet coats, specials board, a laugh from the back booth interrupting history, the thin cry of the blue door admitting another customer into the steam. He plated stew for the feed-store cap without looking away from her for more than a breath. When he leaned in again, his mouth nearly brushed her temple. She smelled him and nearly whimpered.

"Stay or walk to Willow," he said, voice scraped honest. "Either way, do not vanish between the bell and the rain. I have practiced losing you. I am done rehearsing it." His thumb brushed the mug's rim—then, deliberately, the side of her hand, a slow stroke that sent heat straight between her legs and made her breath hitch like a first touch under clothes. "If you stay, I will feed this room and then give you the truth I have—what Clara found, what I remember of that winter, what I have been afraid to ask Henry aloud. And if the booths empty and you still look at me like that, I am not promising I will keep my hands to myself. I am not promising I will not lock the door and put you on your back on this laminate and finally learn what fifteen years of almost tastes like when it finishes."

A flicker of grey-eyed heat. "If we walk, we put my uncle in a chair and we do not let him tidy the story into kindness again. You choose. I will follow either door. Just know that whichever you pick, I am done pretending I only want answers. I want you. I want the truth. I want both in the same night if you will let me."

Through the pass, Clara's voice rose again, closer, soup and charcoal still under her nails if she stepped out. The blue door stuck once more. Rain silvered Market Street. John waited—grey eyes steady and dark with wanting—the cracked stool empty beside [player_name] like an invitation in laminate and weather held without flinching. Under it, the older invitation pulsed in her cunt: stay, talk, touch, fuck what the quiet tried to starve. Willow waited with Henry's face. The rush waited with ears. Her body had already chosen John. Her conscience still had to pick which door first—and the choice hurt the way unfinished heat always hurts, right before it becomes plot.`,
  choices: [
    { id: "scene3a", text: "Stay through the dinner rush — talk with John alone", textHot: "Stay through the rush — talk alone, then let him put his hands where the wanting lives" },
    { id: "scene3b", text: "Ask John to walk you to Willow — face Henry together", textHot: "Walk to Willow with John — face Henry before hunger finishes what the counter started" }
  ]
};
