export default {
  id: "scene3a",
  layer: 3,
  title: "Dinner Rush",
  art: "/art/until-the-quiet-breaks/scene3a.png",
  text: `The dinner rush arrived the way Somerton weather always did—without apology, without asking whether anyone was ready. Coats shook rain onto the mat in dark bursts. Voices overlapped: a man laughing about a flooded cellar, a woman counting change aloud as if arithmetic could keep the damp out, the fryer singing its hot metal hymn through the pass. The specials board still listed beef stew and apple crumb. Coffee steam ghosted the windows in soft curtains that rose and thinned and rose again. John moved through it with a competence that looked like calm until [player_name] watched his hands—precise, never still, always returning to the edge of the counter where her mug cooled between tickets like a small lighthouse he refused to abandon.

She stayed.

Clara tossed her an apron without ceremony, charcoal already smudged along the hem as if the fabric itself had been pressed into service as scrap paper. "If you're here, you're useful," she said, sixteen going on forty, eyes that catalogued everything and filed nothing under kindness alone. "[player_name], right? Henry wrote you. John practiced what he'd say if you came back. Don't make him use the polite version." Then she was gone into the kitchen with a ladle and a look that promised she would be listening through the floorboards whether they liked it or not.

[player_name] tied the apron. The knot sat against her ribs like a decision made tangible. She slid plates. She refilled coffee. She learned the new names for old booths—the window seat that used to belong to the feed-store regulars now claimed by a couple who tipped in folded ones and left sugar packets torn open like small apologies. The cracked stool by the register took her weight once between tickets and leaned its familiar half-degree left, as if welcoming her back into an unfinished argument with gravity. When she rose again, John's gaze flicked to the empty stool and then to her face, something unreadable moving behind the grey—gratitude, fear, the old almost of people who had once believed they had time.

Rain hammered Market Street harder. Headlights smeared across the front glass. The blue door stuck, yielded, stuck again; each thin cry of the bell admitted another wet coat into the steam. John plated stew without looking down, muscle memory braided with the sharper awareness of a woman who had walked fifteen years of silence into his diner and chosen, for this hour at least, not to leave. Once, passing behind him toward the pie case, [player_name] caught the faint burn scar at the base of his thumb where the light caught it, a pale comma earned in years she had spent elsewhere. She wanted to ask how. She did not. The rush did not allow confession; it allowed only motion and the kind of nearness that lived in shared work.

Clara passed with a pie, charcoal crescent dark on her knuckle. "Henry's letter smelled like fear," she murmured, barely loud enough for the counter. "Good." Another pass, later, soup bowls stacked along her forearms: "He stayed for me. Don't make that the only reason you stay for him." Then she vanished upstairs for a moment and returned with a sketchbook tucked under one arm like a weapon she refused to set down, charcoal dust ghosting the apron string.

Between tickets, John leaned close enough that only [player_name] could hear. "You don't have to earn the right to stand here by feeding strangers," he said. "But thank you." His breath smelled of coffee and the mint he kept in the register drawer for late shifts. Heat climbed her throat that had nothing to do with the grill. She nodded, unable to trust her voice over the fryer's hymn, and carried two plates to the back booth where the locals who had watched her arrive still pretended not to watch her stay.

The hours thinned. Wet coats dwindled. The specials board emptied of stew. John wiped the laminate in slow circles that had nothing left to clean and everything left to postpone. When the last couple drifted out into the rain—laughing about a flooded cellar as if weather were the only story Somerton told—John locked the blue door and flipped the sign to CLOSED with a soft finality that sounded louder than the bell. Fluorescent light hummed. Rain freckled the glass. The diner narrowed to the two of them and the ghosts of every conversation they had never finished.

Clara retreated upstairs with her sketchbook and a look that promised listening through the floorboards. "I'm not asleep," she called down the stairwell, not quite joking. "I'm drawing. Same thing." A chair scraped. Then quiet—the particular quiet of a sister who had forced Henry's hand and would not now politely vanish from the aftermath.

John poured fresh coffee, burnt-strong, Somerton-honest, and set the mug in front of [player_name] without asking. Handle toward her hand. The same gesture from the afternoon, now heavier with emptied booths and the knowledge that no more customers would interrupt whatever came next. He came around the counter and sat on the cracked stool beside her, close enough that their knees nearly touched, far enough that the almost still had room to breathe.

"I used to invent reasons you left that made me the fool instead of the abandoned," he said. Voice low. Thorough. Unwilling to miss a corner. "It was easier than wondering if Henry had asked you to disappear. Easier than wondering if I had been too small a life to keep you. I told myself you wanted trains and brighter rooms. I told myself Somerton was a temporary stop on a longer map. I almost believed it on good days. On bad days I remembered your face on the station steps and Henry's hand on your shoulder and the way you said sorry like someone carrying a weight that was not ambition."

[player_name] wrapped her fingers around the mug. Heat climbed her wrists. Steam rose between them like a small, temporary wall she no longer trusted. She told him what she could without Henry's full confession sitting in the room: that she had been asked to carry a cleaner story than the winter deserved; that loving him and leaving him had been the same motion, folded into one night of rain and debt and a father's ending Somerton still refused to say aloud; that the letter had not been forgiveness so much as a crack in a wall she had spent fifteen years pretending was architecture. She did not name every debt. She did not unpack every hour of ice and panic. She gave him the shape of the ask—Henry's ask—and watched his face receive it the way he wiped counters: slow, thorough, refusing to look away from the stain.

"I am angry," John said at last. Not only at her. At the shape of the kindness. At himself for swallowing it. At the neat sentence the town had handed him and the years he had spent trying to live inside it while the pieces never quite fit. He flexed his hand against the counter edge; the burn scar caught the light again. "And I am glad you are standing in my diner anyway. Glad is not the same as ready. It is still true."

Outside, thunder rolled over Market Street, a low drum that made the pie-case glass tremble. The rain thickened into sheets. Upstairs, another chair scrape—Clara, or a warning disguised as furniture. John's gaze flicked toward the stairwell and back, as if measuring how much of their private weather a sister with charcoal under her nails was allowed to harvest.

He stood. Came closer. Close enough that [player_name] smelled coffee and rain on his shirt and the faint ghost of fryer oil that never left a cook's skin, braided now with woodsmoke that might have clung from some earlier errand up Willow, or might have been only memory insisting on its anchors. Fifteen years pressed in from the windows. The cracked stool waited empty behind him. The blue door held the street at bay with its stubborn stick. He lifted a hand toward her cheek and stopped short of touching—offering her the choice of the last inch, heat without demand, the unfinished almost made visible in the space between his palm and her skin.

"We can have this moment before the papers and the uncle and the rest," John said, voice dropped to the register he used when the booths were empty and the truth had nowhere else to hide. "Or we can do this clean—truth first, whatever follows after. I will not hate either answer. I will feel both." His grey eyes held the Somerton sky the way they always had: steadier now, practiced at weather, still capable of breaking if she chose the wrong kind of silence. "Clara found enough to crack Henry open. Henry wrote enough to bring you home. What happens next is ours. Kiss me before the secret lands fully, and we take the spark as proof we survived the quiet. Or hold the line—demand every ugly line before any closeness—and I will give you what I have, even if my hands shake doing it."

[player_name] felt the fork settle into her bones again, not at the station this time, not at the counter with locals listening, but here in the emptied diner with rain silvering Market Street and a man who had practiced losing her and was done rehearsing it. The apron still tied at her ribs. Coffee cooling between them. His hand still hovering, the last inch a question written in heat and fifteen winters of unfinished sentences. Upstairs, Clara's pencil moved across paper with the soft rasp of someone documenting history whether history consented or not. The fluorescent lights hummed. The blue door did not open. The quiet around them was not empty. It was waiting—again—to break, and this time the break would be chosen.`,
  textHot: `Heat hit [player_name] first—pass-lick on the back of her neck, coffee steam on her lashes, the fryer's hymn vibrating up through her shoes into places that had no business waking on Market Street—before the dinner rush even finished announcing itself in coats and voices. Coats shook rain onto the mat. Voices stacked. Specials still promised beef stew and apple crumb. John moved through it like a man who had married competence, and every time his hands returned to the counter edge where her mug cooled, something low and shameless in her clenched as if those hands had already found her.

She stayed. The decision lived in her cunt first, ribs second, mouth last.

Clara tossed an apron without ceremony, charcoal already smudging the hem. "If you're here, you're useful," she said, sixteen going on forty. "[player_name], right? Henry wrote you. John practiced what he'd say if you came back. Don't make him use the polite version." Her eyes flicked—once—to John's mouth and back, as if she had already scored the wanting in the room and filed it under not-her-business-until-it-is. Then she was gone with a ladle, listening promised through the floorboards.

[player_name] tied the apron. The knot sat hard against her ribs; the bib pressed her breasts flat enough that she felt every breath as fabric and heat. She was suddenly, absurdly naked under diner cotton—aware of nipples tightening when John's gaze dragged across her, aware of the damp starting between her thighs that had nothing to do with rain. She slid plates. She refilled coffee. The cracked stool took her weight between tickets and leaned its half-degree left; when she rose, John's eyes went to the empty wood, then to her face, then—hungrier—to the cinch of the apron at her waist. Gratitude. Fear. Cock-hard almost, held behind a counter and fifteen years of practice. Heat climbed her throat and dropped lower, shameless.

Rain hammered Market Street. The blue door stuck, yielded, stuck; each bell-cry admitted another wet coat into the steam. Passing him toward the pie case, [player_name] brushed close enough to catch the burn scar at the base of his thumb—a pale comma earned in years she had spent elsewhere—and close enough that her breast dragged, soft and deliberate-seeming, along his upper arm. Neither of them said accident. She wanted her mouth on that scar. She wanted his thumb inside her while the stew plated itself by muscle memory. She did neither. The rush allowed only hips nearly kissing at the pass, the clean heat of his back when she reached for a ladle, the smell of his skin under coffee and fryer oil when the aisle narrowed and her cunt pulsed once, hard, like a second bell.

Clara passed with pie, charcoal crescent on her knuckle. "Henry's letter smelled like fear," she murmured. "Good." Later, bowls stacked on her forearms: "He stayed for me. Don't make that the only reason you stay for him." Upstairs, sketchbook under her arm like a weapon. [player_name] felt watched the way sisters watch—not prurient, knowing: desire and danger sharing a booth, and Clara's charcoal ready to document whichever broke first.

Between tickets John leaned in until his breath warmed the shell of her ear and sent a shiver straight down her spine into wet heat the apron could not hide. "You don't have to earn the right to stand here by feeding strangers," he said. "But thank you." Coffee. Mint from the register drawer. The rough edge of his voice. His chest nearly touching her shoulder; she felt the shape of him—broad, working, unfinished—and nodded because if she spoke she might ask him to lock the fucking door now. Thighs pressed together under the counter for one stolen second of pressure that did nothing. She carried plates to the back booth on legs that remembered how to walk while her body negotiated something else entirely.

Hours thinned. Wet coats dwindled. Stew emptied off the board. John wiped laminate in slow circles that looked like a man learning a woman's hip by proxy, and [player_name] watched his hands and ached. When the last couple drifted into the rain laughing about a flooded cellar, he locked the blue door and flipped CLOSED with a finality louder than the bell. Fluorescent hum. Rain freckling glass. The diner narrowed to two bodies and every unfinished sentence—and the heat banked since the apron knot now had nowhere polite to go.

Clara retreated upstairs with her sketchbook. "I'm not asleep," she called. "I'm drawing. Same thing." Chair scrape. Quiet that meant a sister forced Henry's hand and would not vanish from the aftermath, even if what the floorboards caught next was mouths instead of only mouths speaking.

John poured burnt-strong coffee and set it in front of [player_name] without asking—handle toward her hand, the afternoon's gesture made heavier by emptied booths and the knowledge that customers would not interrupt talk or the other thing their bodies had been bargaining all night. He came around and sat the cracked stool beside her. Their knees touched. Neither moved. Small contact. Electric. She felt the solid heat of his thigh through denim and knew, pulse shameless between her legs, that he was hard—or close enough that the almost counted—and that he knew she knew.

"I used to invent reasons you left that made me the fool instead of the abandoned," he said, voice low, rough with more than anger. "Easier than wondering if Henry asked you to disappear. Easier than wondering if I was too small a life. I told myself trains and brighter rooms. On bad days I remembered your face on the station steps and Henry's hand on your shoulder and the way you said sorry like the weight wasn't ambition—and God help me, I remembered how you used to look at my mouth when you thought I wasn't watching. I still get hard remembering it. Sitting here doesn't make that cleaner."

[player_name] wrapped her fingers around the mug. Wrist-heat. Steam like a wall she no longer trusted. She gave him what she could without Henry's full confession in the room: asked to carry a cleaner story than the winter deserved; loving him and leaving him the same motion—rain, debt, a father's ending Somerton still would not say; the letter a crack, not forgiveness. She did not name every debt. She gave the shape of Henry's ask and watched John receive it the way he wiped counters—slow, thorough, refusing the stain. All the while her knee stayed pressed to his. All the while she tracked his breathing, the width of his shoulders, how easy it would be to lean in, taste coffee on his tongue, and make the secret wait one more selfish minute while her hand found the hard line of him under denim.

"I am angry," John said. Not only at her. At the kindness's shape. At himself for swallowing it. At the tidy sentence he had lived inside while the pieces never fit—and while his body, traitor, kept wanting the woman the sentence said was gone. Burn scar catching light as he flexed against the counter. "And I am glad you are standing in my diner anyway. Glad is not ready. Still true. Ready would mean I could look at your mouth without wanting to ruin this careful talk—without wanting to put you on this counter and find out if you still get wet when I say your name."

Thunder rolled Market Street; pie-case glass trembled. Rain sheeted. Upstairs, another chair scrape—Clara, or furniture wearing a warning. John's gaze flicked stairwell then back, measuring how much private weather charcoal would harvest—and how much of the heat between them the boards would report.

He stood. Came closer. Coffee, rain, fryer-ghost on his shirt; clean male heat; woodsmoke that might be Willow or memory. Fifteen years pressed the windows. Cracked stool empty behind him. Blue door holding the street. He lifted a hand toward her cheek and stopped—last inch offered, heat without demand. She felt the warmth as if he had already claimed her. Lips parted. Pulse hammering low. She wanted that palm on her face, throat, waist; wanted it under the apron, between her legs, fingers slick with what the rush had built; wanted his cock against her belly through clothes if that was all Clara's floorboards would allow before the ledger landed.

"We can have this moment before the papers and the uncle and the rest," John said, voice dropped to empty-booth register—wanting under the words like a second confession. "Or we do this clean—truth first, whatever follows. I will not hate either answer. I will feel both. My hands shake either way. My cock doesn't care which door we open first, and I'm done pretending that's separate from loving you." Grey eyes: Somerton sky, practiced weather, hunger unhidden. "Clara cracked Henry. Henry wrote you home. What happens next is ours. Kiss me before the secret lands fully—put your mouth on mine, take the spark as proof we survived the quiet, bodies first, ledger second. Or hold the line—every ugly line before any closeness—and I give you what I have even if standing this close without fucking my tongue into your mouth kills me a little."

[player_name] felt the fork settle into bone—not station, not locals listening, here in the emptied diner with rain silvering Market Street and a man done rehearsing loss, body angled toward hers as if the night had already voted for the kiss. Apron still knotted. Coffee cooling. His hand hovering: last inch written in heat and fifteen winters and the shameless pulse in her cunt that already knew which answer her body preferred. Upstairs, Clara's pencil rasped history without consent. Fluorescent hum. Blue door shut. The quiet was not empty. It waited to break—mouth on mouth with her thighs open under the apron, or truth before tenderness with wanting still dripping between them—and this time the break would be chosen, both of them already half-undone by the almost.`,
  choices: [
    { id: "scene4a", text: "Lean into the spark — kiss him before the secret lands", textHot: "Take the spark — kiss him hard before the secret lands" },
    { id: "scene4b", text: "Hold the line — demand the truth before any closeness", textHot: "Hold the line — demand every ugly truth before you touch" }
  ]
};
